Repository actualbudget/actual, pull requests merged in 2022-12, with the labels that each got.

#385 feat: ability to add notes to accounts
  packages/desktop-client/src/components/accounts/Account.js
Labels: enhancement, waiting-review

#383 Fix child transaction selection edits also applying to their unselected siblings.
  packages/desktop-client/src/components/accounts/Account.js
Labels: bug, needs-testing, transactions, waiting-review

#223 Improve the UX around configuring a server URL
  packages/desktop-client/src/components/LoggedInUser.js
  packages/desktop-client/src/components/manager/ConfigServer.js
  packages/desktop-client/src/components/manager/ManagementApp.js
  packages/desktop-client/src/components/manager/ServerURL.js
  packages/desktop-client/src/hooks/useServerURL.js
Labels: enhancement, user-interface

#260 feat(account): button to create reconciliation balance updates
  packages/desktop-client/src/components/accounts/Account.js
Labels: enhancement, transactions

#267 Simplify the settings layout and merge everything onto one page
  packages/desktop-client/src/components/Settings.js
  packages/loot-core/src/mocks/setup.js
  packages/loot-core/src/server/main.js
  packages/loot-core/src/server/tracking/events.js
  packages/mobile/src/components/manager/Login.js
Labels: enhancement, user-interface

#354 Schedules editor: exclude closed accounts in Account autocomplete
  packages/desktop-client/src/components/schedules/EditSchedule.js
  packages/loot-design/src/components/AccountAutocomplete.js
Labels: enhancement, schedules, transactions
