Repository actualbudget/actual, pull requests merged in 2022-11, with the labels that each got.

#389 Add a help button to the menu
  packages/loot-design/src/components/sidebar.js
Labels: enhancement, fixed, user-interface

#218 Fix enter to create accounts
  packages/loot-design/src/components/common.js
  packages/loot-design/src/components/modals/CreateLocalAccount.js
Labels: bug, user-interface

#266 Update data-file-index.txt
  packages/desktop-client/public/data-file-index.txt
Labels: fixed

#272 a11y: update cleared state display for clarity
  packages/desktop-client/src/components/accounts/TransactionsTable.js
  packages/desktop-client/src/components/schedules/StatusBadge.js
  packages/loot-design/src/svg/v2/CheckCircleHollow.js
Labels: enhancement, fixed, user-interface
