Repository actualbudget/actual, pull requests merged in 2023-08, with the labels that each got.

#1450 fix eye coloring
  packages/desktop-client/src/icons/v2/Eye.js
  upcoming-release-notes/1450.md
Labels: ✅ Approved

#1449 Release note README link update
  upcoming-release-notes/1449.md
  upcoming-release-notes/README.md
Labels: ✅ Approved

#1446 Sentence case in menus
  packages/desktop-client/src/components/accounts/Header.js
  packages/desktop-client/src/components/budget/report/BudgetSummary.tsx
  packages/desktop-client/src/components/budget/rollover/BudgetSummary.tsx
  upcoming-release-notes/1446.md
Labels: ✅ Approved

#1447 Reports privacy filter
  packages/desktop-client/src/components/reports/CashFlow.js
  packages/desktop-client/src/components/reports/NetWorth.js
  packages/desktop-client/src/components/reports/Overview.js
  upcoming-release-notes/1447.md
Labels: ✅ Approved

#1451 Add options on Import transactions screen to mark transactions as cleared/uncleared
  packages/desktop-client/src/components/modals/ImportTransactions.js
  packages/desktop-client/src/icons/v2/Eye.js
  upcoming-release-notes/1451.md
Labels: ✅ Approved

#1437 :recycle: (crdt) adding more strict typings
  packages/crdt/src/crdt/merkle.test.ts
  packages/crdt/src/crdt/merkle.ts
  packages/crdt/src/crdt/timestamp.test.ts
  packages/crdt/src/crdt/timestamp.ts
  packages/crdt/tsconfig.dist.json
  upcoming-release-notes/1437.md
Labels: ✅ Approved

#1438 :arrow_up: (crdt) upgrade murmurhash
  packages/crdt/package.json
  upcoming-release-notes/1438.md
  yarn.lock
Labels: ✅ Approved

#1458 Bugfix: remove select component inner scrollbar
  packages/desktop-client/src/components/common/Select.tsx
  upcoming-release-notes/1458.md
Labels: ✅ Approved

#1431 Move big input component into Input.js, port some of the manager app to TS
  packages/desktop-client/src/components/ServerContext.tsx
  packages/desktop-client/src/components/common/Input.tsx
  packages/desktop-client/src/components/manager/ConfigServer.tsx
  packages/desktop-client/src/components/manager/ServerURL.tsx
  packages/desktop-client/src/components/manager/subscribe/ConfirmPasswordForm.tsx
  packages/desktop-client/src/components/manager/subscribe/Login.tsx
  packages/desktop-client/src/components/manager/subscribe/common.tsx
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/1431.md
Labels: ✅ Approved

#1463 :bug: (schedules) fix creating schedules with the same name
  packages/loot-core/migrations/1691233396000_add_schedule_next_date_tombstone.sql
  packages/loot-core/src/server/schedules/app.ts
  upcoming-release-notes/1463.md
Labels: ✅ Approved

#1456 Fix the mobile footer color
  packages/desktop-client/src/components/FinancesApp.tsx
  packages/desktop-client/src/style/themes/dark.ts
  packages/desktop-client/src/style/themes/light.ts
  upcoming-release-notes/1456.md
Labels: ✅ Approved

#1462 :bug: (import) fix YNAB (and other) importers
  packages/desktop-client/e2e/data/ynab5-demo-budget.json
  packages/desktop-client/e2e/onboarding.test.js
  packages/desktop-client/src/components/manager/ImportActual.tsx
  packages/desktop-client/src/components/manager/ImportYNAB4.tsx
  packages/desktop-client/src/components/manager/ImportYNAB5.tsx
  packages/desktop-client/src/global-events.js
  packages/loot-core/src/server/importers/ynab5-types.d.ts
  packages/loot-core/src/server/importers/ynab5.ts
  packages/loot-core/src/server/main.ts
  upcoming-release-notes/1462.md
Labels: ✅ Approved

#1460 Fix titlebar transparent background
  packages/desktop-client/src/components/FinancesApp.tsx
  upcoming-release-notes/1460.md
Labels: ✅ Approved

#1452 Goals: Schedule multi month forecasting
  packages/loot-core/src/server/budget/goaltemplates.ts
  upcoming-release-notes/1452.md
Labels: ✅ Approved

#1461 :recycle: (crdt) adding more strict typings
  packages/crdt/package.json
  packages/crdt/src/crdt/merkle.test.ts
  packages/crdt/src/crdt/merkle.ts
  packages/crdt/src/crdt/timestamp.ts
  packages/crdt/tsconfig.dist.json
  upcoming-release-notes/1461.md
Labels: ✅ Approved

#1473 :bug: (schedules) fix showing balance of approximate transactions
  .github/workflows/check.yml
  .github/workflows/issues-feature-implemented.yml
  packages/desktop-client/src/components/accounts/Account.js
  packages/desktop-client/src/components/accounts/Balance.js
  upcoming-release-notes/1473.md
Labels: ✅ Approved

#1464 [Bug]Goals: Applying templates would zero non-templated categories
  packages/loot-core/src/server/budget/goaltemplates.ts
  upcoming-release-notes/1464.md
Labels: ✅ Approved

#1478 [Bug] Goals: Monthly schedule can cause error
  packages/loot-core/src/server/budget/goaltemplates.ts
  upcoming-release-notes/1478.md
Labels: ✅ Approved

#1475 :bookmark: (23.8.1) fix nYNAB import, mobile colors and other smaller fixes
  packages/api/package.json
  packages/desktop-client/package.json
  packages/desktop-electron/package.json
  upcoming-release-notes/1431.md
  upcoming-release-notes/1437.md
  upcoming-release-notes/1438.md
  upcoming-release-notes/1446.md
  upcoming-release-notes/1447.md
  upcoming-release-notes/1448.md
  upcoming-release-notes/1449.md
  upcoming-release-notes/1450.md
  upcoming-release-notes/1451.md
  upcoming-release-notes/1452.md
  upcoming-release-notes/1456.md
  upcoming-release-notes/1458.md
  upcoming-release-notes/1460.md
  upcoming-release-notes/1461.md
  upcoming-release-notes/1462.md
  upcoming-release-notes/1463.md
  upcoming-release-notes/1464.md
  upcoming-release-notes/1473.md
  upcoming-release-notes/1478.md
Labels: ✅ Approved

#1482 eslint rule for capturing colors/themes
  .eslintrc.js
  upcoming-release-notes/1482.md
Labels: 🔍 Ready for Review, ✅ Approved

#1486 Fix mobile account view
  packages/desktop-client/src/components/accounts/MobileAccount.js
  upcoming-release-notes/1486.md
Labels: ✅ Approved

#1340 Initial port of react native edit transaction view
  packages/desktop-client/src/components/FinancesApp.tsx
  packages/desktop-client/src/components/accounts/MobileAccount.js
  packages/desktop-client/src/components/accounts/MobileAccountDetails.js
  packages/desktop-client/src/components/autocomplete/AccountAutocomplete.js
  packages/desktop-client/src/components/autocomplete/Autocomplete.tsx
  packages/desktop-client/src/components/autocomplete/CategorySelect.tsx
  packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.js
  packages/desktop-client/src/components/mobile/MobileAmountInput.js
  packages/desktop-client/src/components/mobile/MobileForms.js
  packages/desktop-client/src/components/modals/EditField.js
  packages/desktop-client/src/components/transactions/MobileTransaction.js
  packages/loot-core/src/shared/transactions.ts
  upcoming-release-notes/1340.md
Labels: 🔍 Ready for Review

#1469 add dev theme to list
  packages/desktop-client/src/style/theme.tsx
  packages/desktop-client/src/style/themes/development.ts
  upcoming-release-notes/1469.md
Labels: ✅ Approved

#1481 Goals: Ignore hidden categories when running goal templates
  packages/loot-core/src/server/budget/goaltemplates.ts
  upcoming-release-notes/1481.md
Labels: ✅ Approved

#1270 Remove page-based modals in favor of existing state-based modal logic
  packages/desktop-client/src/components/ActiveLocation.js
  packages/desktop-client/src/components/FinancesApp.tsx
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/Page.tsx
  packages/desktop-client/src/components/accounts/Account.js
  packages/desktop-client/src/components/accounts/Header.js
  packages/desktop-client/src/components/accounts/MobileAccountDetails.js
  packages/desktop-client/src/components/manager/Modals.js
  packages/desktop-client/src/components/responsive/wide.ts
  packages/desktop-client/src/components/schedules/DiscoverSchedules.js
  packages/desktop-client/src/components/schedules/EditSchedule.js
  packages/desktop-client/src/components/schedules/LinkSchedule.js
  packages/desktop-client/src/components/schedules/PostsOfflineNotification.js
  packages/desktop-client/src/components/schedules/index.js
  packages/desktop-client/src/components/transactions/SelectedTransactions.js
  packages/desktop-client/src/components/transactions/TransactionList.js
  packages/desktop-client/src/global-events.js
  packages/desktop-client/src/util/router-tools.tsx
  packages/desktop-electron/menu.js
  packages/loot-core/src/client/state-types/modals.d.ts
  packages/loot-core/typings/window.d.ts
  upcoming-release-notes/1270.md
Labels: ✅ Approved

#1494 Fix transactions button background color
  packages/desktop-client/src/components/table.tsx
  upcoming-release-notes/1494.md
Labels: ✅ Approved

#1379 Show correct payee for scheduled transactions on budgeted accounts page
  packages/desktop-client/src/components/transactions/TransactionsTable.js
  upcoming-release-notes/1379.md
Labels: 🔍 Ready for Review

#1508 :bug: show all available transaction icons
  packages/desktop-client/src/components/transactions/TransactionsTable.js
  upcoming-release-notes/1508.md
Labels: ✅ Approved

#1491 :sparkles: (reports) add loading indicators
  packages/desktop-client/src/components/reports/CategorySelector.tsx
  packages/desktop-client/src/components/reports/Overview.js
  packages/desktop-client/src/components/reports/graphs/category-spending-spreadsheet.tsx
  packages/desktop-client/src/components/reports/graphs/common.tsx
  upcoming-release-notes/1491.md
Labels: ✅ Approved

#1479 :recycle: (typescript) migrating hooks to TypeScript
  packages/desktop-client/src/hooks/usePrevious.ts
  packages/desktop-client/src/hooks/useProperFocus.tsx
  packages/desktop-client/src/hooks/useSelected.tsx
  packages/loot-core/src/platform/client/undo/index.d.ts
  upcoming-release-notes/1479.md
Labels: 🔍 Ready for Review

#1515 Import category notes from YNAB4 exports
  packages/loot-core/src/server/importers/ynab4-types.d.ts
  packages/loot-core/src/server/importers/ynab4.ts
  upcoming-release-notes/1515.md
Labels: ✅ Approved

#1402 Bugfix row render
  packages/desktop-client/src/components/transactions/TransactionsTable.js
  upcoming-release-notes/1402.md
Labels: ✅ Approved

#1518 :bug: (reports) fix incorrect cashflow balance
  packages/desktop-client/src/components/reports/util.js
  upcoming-release-notes/1518.md
Labels: ✅ Approved

#1492 :wrench: (eslint) add 'plugin:react/recommended'
  .eslintignore
  .eslintrc.js
  packages/desktop-client/src/components/Notifications.tsx
  packages/desktop-client/src/components/accounts/Account.js
  packages/desktop-client/src/components/budget/MobileBudgetTable.js
  packages/desktop-client/src/components/filters/FiltersMenu.js
  packages/desktop-client/src/components/schedules/PostsOfflineNotification.js
  packages/desktop-client/src/components/select/RecurringSchedulePicker.js
  upcoming-release-notes/1492.md
Labels: ✅ Approved

#1526 Correctly fix schedule transaction payee
  packages/desktop-client/src/components/accounts/Account.js
  packages/desktop-client/src/components/transactions/TransactionsTable.js
  upcoming-release-notes/1526.md
Labels: ✅ Approved

#1455 #1454 - Show projected balance when adding new transaction
  packages/desktop-client/src/components/transactions/TransactionsTable.js
  upcoming-release-notes/1455.md
Labels: 🔍 Ready for Review

#1499 Rely on date determined by server for GoCardless transactions
  packages/loot-core/src/server/accounts/sync.ts
  upcoming-release-notes/1499.md
Labels: 🔍 Ready for Review

#1529 :bug: (importer) fix nYNAB importer when decimal budgets used
  packages/loot-core/src/server/importers/ynab5.ts
  upcoming-release-notes/1529.md
Labels: ✅ Approved

#1530 :bug: (darkmode) fixing lightmode regressions in transaction table
  .eslintrc.js
  packages/desktop-client/src/components/accounts/Balance.js
  packages/desktop-client/src/components/accounts/Header.js
  packages/desktop-client/src/components/schedules/StatusBadge.js
  packages/desktop-client/src/components/transactions/TransactionsTable.js
  packages/desktop-client/src/style/themes/light.ts
  upcoming-release-notes/1530.md
Labels: ✅ Approved

#1531 :bug: (darkmode) fix transaction list hover effects
  packages/desktop-client/src/components/budget/misc.js
  packages/desktop-client/src/components/budget/report/components.tsx
  packages/desktop-client/src/components/budget/rollover/rollover-components.tsx
  packages/desktop-client/src/components/payees/index.js
  packages/desktop-client/src/components/schedules/DiscoverSchedules.js
  packages/desktop-client/src/components/schedules/SchedulesTable.js
  packages/desktop-client/src/components/table.tsx
  packages/desktop-client/src/components/transactions/TransactionList.js
  packages/desktop-client/src/components/transactions/TransactionsTable.js
  packages/desktop-client/src/style/themes/light.ts
  upcoming-release-notes/1531.md
Labels: ✅ Approved

#1532 Some typescript migration
  packages/desktop-client/src/components/AnimatedRefresh.tsx
  packages/desktop-client/src/components/BankSyncStatus.tsx
  packages/desktop-client/src/components/FinancesApp.tsx
  packages/desktop-client/src/components/GlobalKeys.tsx
  packages/desktop-client/src/components/LoggedInUser.tsx
  packages/desktop-client/src/components/ManageRulesPage.tsx
  packages/desktop-client/src/components/MobileWebMessage.tsx
  packages/desktop-client/src/components/SyncRefresh.js
  packages/desktop-client/src/components/SyncRefresh.tsx
  packages/desktop-client/src/components/Titlebar.tsx
  packages/desktop-client/src/components/UpdateNotification.tsx
  packages/desktop-client/src/components/settings/Format.tsx
  packages/desktop-client/src/components/sidebar.js
  packages/desktop-client/src/components/sidebar/Account.tsx
  packages/desktop-client/src/components/sidebar/Accounts.tsx
  packages/desktop-client/src/components/sidebar/Item.tsx
  packages/desktop-client/src/components/sidebar/ItemContent.tsx
  packages/desktop-client/src/components/sidebar/SecondaryItem.tsx
  packages/desktop-client/src/components/sidebar/Sidebar.tsx
  packages/desktop-client/src/components/sidebar/SidebarWithData.tsx
  packages/desktop-client/src/components/sidebar/ToggleButton.tsx
  packages/desktop-client/src/components/sidebar/Tools.tsx
  packages/desktop-client/src/components/sidebar/index.tsx
  packages/desktop-client/src/components/sort.tsx
  packages/desktop-client/src/components/spreadsheet/index.ts
  packages/loot-core/src/types/server-events.d.ts
  packages/loot-core/typings/window.d.ts
  upcoming-release-notes/1532.md
Labels: ✅ Approved

#1539 Mobile: Don't show hidden categories
  packages/desktop-client/src/components/budget/MobileBudgetTable.js
  upcoming-release-notes/1539.md
Labels: ✅ Approved

#1540 Mobile: To Budget inconsistency
  packages/desktop-client/src/components/modals/BudgetSummary.js
  upcoming-release-notes/1540.md
Labels: ✅ Approved

#1521 :white_check_mark: (e2e) adding mobile e2e tests
  packages/desktop-client/e2e/mobile.test.js
  packages/desktop-client/e2e/page-models/mobile-account-page.js
  packages/desktop-client/e2e/page-models/mobile-accounts-page.js
  packages/desktop-client/e2e/page-models/mobile-budget-page.js
  packages/desktop-client/e2e/page-models/mobile-navigation.js
  packages/desktop-client/e2e/page-models/mobile-transaction-entry-page.js
  packages/desktop-client/src/components/accounts/MobileAccountDetails.js
  packages/desktop-client/src/components/accounts/MobileAccounts.js
  packages/desktop-client/src/components/budget/MobileBudgetTable.js
  packages/desktop-client/src/components/common/Button.tsx
  packages/desktop-client/src/components/common/ButtonLink.tsx
  packages/desktop-client/src/components/mobile/MobileForms.js
  packages/desktop-client/src/components/spreadsheet/CellValue.tsx
  packages/desktop-client/src/components/transactions/MobileTransaction.js
  upcoming-release-notes/1521.md
Labels: ✅ Approved

#1533 :bug: (darkmode) fix colors used for schedules in transaction table
  .eslintrc.js
  packages/desktop-client/src/components/accounts/Balance.js
  packages/desktop-client/src/components/transactions/TransactionsTable.js
  packages/desktop-client/src/style/themes/light.ts
  upcoming-release-notes/1533.md
Labels: ✅ Approved

#1535 Port App and FatalError components to TS and functional components
  packages/desktop-client/package.json
  packages/desktop-client/src/components/App.js
  packages/desktop-client/src/components/App.tsx
  packages/desktop-client/src/components/AppBackground.tsx
  packages/desktop-client/src/components/FatalError.js
  packages/desktop-client/src/components/FatalError.tsx
  upcoming-release-notes/1535.md
  yarn.lock
Labels: ✅ Approved

#1505 Allow schedules to skip weekends
  packages/desktop-client/src/components/schedules/EditSchedule.js
  packages/desktop-client/src/components/select/RecurringSchedulePicker.js
  packages/loot-core/src/server/accounts/rules.ts
  packages/loot-core/src/server/schedules/app.ts
  upcoming-release-notes/1505.md
Labels: ✅ Approved

#1501 :bug: Schedule table in Link Schedule modal is collapsed
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/schedules/LinkSchedule.js
  packages/desktop-client/src/components/schedules/LinkSchedule.tsx
  packages/desktop-client/src/hooks/useActions.ts
  packages/desktop-client/src/types/modals.d.ts
  packages/loot-core/src/client/data-hooks/schedules.tsx
  upcoming-release-notes/1501.md
Labels: 🔍 Ready for Review

#1552 [Bug]: darkmode regression - fatal error message is ugly
  packages/desktop-client/src/components/FatalError.tsx
  upcoming-release-notes/1552.md
Labels: ✅ Approved

#1550 [Bug]: Mobile Header
  packages/desktop-client/src/components/budget/MobileBudgetTable.js
  upcoming-release-notes/1550.md
Labels: ✅ Approved

#1545 :sparkles: (mobile) allow creating transactions via the footer
  packages/desktop-client/e2e/mobile.test.js
  packages/desktop-client/e2e/page-models/mobile-navigation.js
  packages/desktop-client/e2e/page-models/mobile-transaction-entry-page.js
  packages/desktop-client/src/components/FinancesApp.tsx
  packages/desktop-client/src/components/accounts/MobileAccountDetails.js
  packages/desktop-client/src/components/transactions/MobileTransaction.js
  upcoming-release-notes/1545.md
Labels: ✅ Approved

#1551 :bug: Mobile entry will enter positive value instead of negative
  packages/desktop-client/src/components/mobile/MobileAmountInput.js
  upcoming-release-notes/1551.md
Labels: ✅ Approved

#1541 :bug: (darkmode) fix more issues - transaction table and csv imports
  packages/desktop-client/src/components/budget/misc.js
  packages/desktop-client/src/components/common/View.tsx
  packages/desktop-client/src/components/modals/ImportTransactions.js
  packages/desktop-client/src/components/table.tsx
  packages/desktop-client/src/components/transactions/TransactionsTable.js
  upcoming-release-notes/1541.md
Labels: ✅ Approved

#1546 :bug: (mobile) hide sync button if sync is not active
  packages/desktop-client/src/components/Titlebar.tsx
  packages/desktop-client/src/components/budget/MobileBudgetTable.js
  upcoming-release-notes/1546.md
Labels: ✅ Approved

#1548 🎨 improving category spending side-nav style
  packages/desktop-client/src/components/reports/CategorySelector.tsx
  packages/desktop-client/src/components/reports/CategorySpending.js
  upcoming-release-notes/1548.md
Labels: ✅ Approved

#1484 Make GoCardless fetch transactions from 7 days before the last imported transaction
  packages/loot-core/src/server/accounts/sync.ts
  upcoming-release-notes/1484.md
Labels: ✅ Approved

#1565 Month count selector ts refactor
  packages/desktop-client/src/components/budget/MonthCountSelector.tsx
  upcoming-release-notes/1565.md
Labels: ✅ Approved

#1559 Don't update transaction date when syncing from GoCardless.
  packages/loot-core/src/server/accounts/sync.ts
  upcoming-release-notes/1559.md
Labels: ✅ Approved

#1547 :bug: reset reconciliation status when switching accounts
  packages/desktop-client/src/components/accounts/Account.js
  upcoming-release-notes/1547.md
Labels: ✅ Approved

#1549 Sync on visibility change
  packages/desktop-client/src/components/App.tsx
  upcoming-release-notes/1549.md
Labels: ✅ Approved

#1465 Fix bug - Manually entered split transactions are not cleared on import #200
  packages/loot-core/src/server/accounts/sync.ts
  upcoming-release-notes/1465.md
Labels: ✅ Approved

#1571 :bug: Schedule editor: Linked transactions table collapses
  packages/desktop-client/src/components/schedules/EditSchedule.js
  packages/desktop-client/src/components/table.tsx
  upcoming-release-notes/1571.md
Labels: ✅ Approved

#1477 Update screenshot
  demo.png
  upcoming-release-notes/1477.md
Labels: 🔍 Ready for Review

#1590 :bug: (vrt) fix vrt - use static date
  packages/desktop-client/e2e/budget.test.js-snapshots/Budget-renders-the-summary-information-available-funds-overspent-budgeted-and-for-next-month-1-chromium-linux.png
  packages/desktop-client/e2e/budget.test.js-snapshots/Budget-transfer-funds-to-another-category-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-and-cash-flow-reports-1-chromium-linux.png
  packages/loot-core/src/server/schedules/app.test.ts
  packages/loot-core/src/server/schedules/app.ts
  packages/loot-core/src/shared/months.ts
  upcoming-release-notes/1590.md
Labels: ✅ Approved

#1581 Create transfer using child transaction instead of parent
  packages/loot-core/src/server/accounts/transfer.ts
  upcoming-release-notes/1581.md
Labels: ✅ Approved

#1580 Schedule privacy
  packages/desktop-client/src/components/schedules/SchedulesTable.js
  upcoming-release-notes/1580.md
Labels: ✅ Approved

#1579 Goals: fix percent goals in the same priority level not compounding
  packages/loot-core/src/server/budget/goaltemplates.ts
  upcoming-release-notes/1579.md
Labels: ✅ Approved

#1591 :wrench: mark PRs as stale and auto-close
  .github/workflows/stale.yml
  upcoming-release-notes/1591.md
Labels: ✅ Approved

#1602 Refactor budget/MobileTable to tsx
  packages/desktop-client/src/components/budget/MobileTable.tsx
  upcoming-release-notes/1602.md
Labels: ✅ Approved

#1605 :white_check_mark: (vrt) increased strictness, added datepicker test
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-1-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-2-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-creates-a-new-account-and-views-the-initial-balance-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/budget.test.js-snapshots/Budget-renders-the-summary-information-available-funds-overspent-budgeted-and-for-next-month-1-chromium-linux.png
  packages/desktop-client/e2e/budget.test.js-snapshots/Budget-transfer-funds-to-another-category-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-from-accounts-id-page-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-3-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-loads-the-budget-page-with-budgeted-amounts-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-3-chromium-linux.png
  packages/desktop-client/e2e/page-models/account-page.js
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-and-cash-flow-reports-1-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-1-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-checks-the-page-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-split-test-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-test-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-date-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-date-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-date-3-chromium-linux.png
  packages/desktop-client/playwright.config.js
  packages/desktop-client/src/components/budget/MobileBudgetTable.js
  packages/desktop-client/src/components/budget/MonthPicker.js
  packages/desktop-client/src/components/budget/report/BudgetSummary.tsx
  packages/desktop-client/src/components/budget/rollover/BudgetSummary.tsx
  packages/desktop-client/src/components/filters/FiltersMenu.js
  packages/desktop-client/src/components/reports/DateRange.js
  packages/desktop-client/src/components/schedules/SchedulesTable.js
  packages/desktop-client/src/components/select/DateSelect.js
  packages/desktop-client/src/components/tooltips.js
  packages/desktop-client/src/components/transactions/MobileTransaction.js
  packages/desktop-client/src/components/transactions/TransactionsTable.js
  packages/desktop-client/src/components/transactions/TransactionsTable.test.js
  packages/loot-core/src/shared/months.ts
  upcoming-release-notes/1605.md
Labels: 🔍 Ready for Review

#1607 [Bug] Mobile: Account picker text color
  packages/desktop-client/src/components/autocomplete/AccountAutocomplete.js
  upcoming-release-notes/1607.md
Labels: ✅ Approved

#1613 Close modals on route change
  packages/desktop-client/src/components/Modals.tsx
  upcoming-release-notes/1613.md
Labels: ✅ Approved
