Repository actualbudget/actual, pull requests merged in 2023-09, with the labels that each got.

#1622 :bug: fix filtering in transaction table
  .github/workflows/e2e-test.yml
  packages/desktop-client/e2e/transactions.test.js
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-category-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-category-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-category-3-chromium-linux.png
  packages/desktop-client/src/components/tooltips.js
  upcoming-release-notes/1622.md
Labels: ✅ Approved

#1623 :sparkles: releasing privacy mode feature
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-1-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-2-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-creates-a-new-account-and-views-the-initial-balance-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/budget.test.js-snapshots/Budget-renders-the-summary-information-available-funds-overspent-budgeted-and-for-next-month-1-chromium-linux.png
  packages/desktop-client/e2e/budget.test.js-snapshots/Budget-transfer-funds-to-another-category-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-and-cash-flow-reports-1-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-checks-the-page-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-checks-the-page-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-1-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-2-chromium-linux.png
  packages/desktop-client/e2e/settings.test.js-snapshots/Settings-checks-the-page-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-checks-the-page-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-split-test-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-test-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-category-3-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-date-3-chromium-linux.png
  packages/desktop-client/src/hooks/useFeatureFlag.ts
  upcoming-release-notes/1623.md
Labels: 🔍 Ready for Review

#1604 :bug: Mobile: fix Accounts page theme color
  packages/desktop-client/src/components/accounts/MobileAccount.js
  packages/desktop-client/src/components/accounts/MobileAccounts.js
  packages/desktop-client/src/components/budget/MobileBudget.js
  packages/desktop-client/src/components/manager/ConfigServer.tsx
  packages/desktop-client/src/components/settings/index.tsx
  packages/desktop-client/src/components/transactions/MobileTransaction.js
  packages/desktop-client/src/hooks/useSetThemeColor.ts
  packages/desktop-client/src/style/themes/dark.ts
  packages/desktop-client/src/style/themes/light.ts
  upcoming-release-notes/1604.md
Labels: ✅ Approved

#1625 :bug: Mobile: Account ledger jumps on first selection
  packages/desktop-client/package.json
  packages/desktop-client/src/components/accounts/MobileAccount.js
  packages/desktop-client/src/components/transactions/MobileTransaction.js
  upcoming-release-notes/1625.md
  yarn.lock
Labels: 🔍 Ready for Review

#1631 🐛 (imports) ability to toggle on/off OFX import fallback payee
  packages/desktop-client/src/components/modals/ImportTransactions.js
  packages/loot-core/src/server/accounts/parse-file.ts
  packages/loot-core/src/types/prefs.d.ts
  upcoming-release-notes/1631.md
Labels: ✅ Approved

#1636 Add github sponsors button to the repository
  .github/FUNDING.yml
Labels: ✅ Approved

#1632 ⬆️ upgrade absurd-sql and remove patch-package
  bin/package-electron
  package.json
  packages/loot-core/package.json
  patches/absurd-sql+0.0.53.patch
  upcoming-release-notes/1632.md
  yarn.lock
Labels: ✅ Approved

#1592 Make reports more responsive
  packages/desktop-client/src/components/forms.tsx
  packages/desktop-client/src/components/reports/CategorySelector.tsx
  packages/desktop-client/src/components/reports/CategorySpending.js
  packages/desktop-client/src/components/reports/NetWorth.js
  packages/desktop-client/src/components/reports/graphs/CategorySpendingGraph.tsx
  packages/desktop-client/src/components/reports/graphs/NetWorthGraph.tsx
  upcoming-release-notes/1592.md
Labels: ✅ Approved

#1614 Rename CategorySelect file to CategoryAutocomplete
  packages/desktop-client/src/components/autocomplete/CategoryAutocomplete.tsx
  packages/desktop-client/src/components/budget/rollover/TransferTooltip.tsx
  packages/desktop-client/src/components/budget/rollover/rollover-components.tsx
  packages/desktop-client/src/components/modals/CloseAccount.js
  packages/desktop-client/src/components/modals/ConfirmCategoryDelete.js
  packages/desktop-client/src/components/modals/EditField.js
  packages/desktop-client/src/components/reports/CategorySelector.tsx
  packages/desktop-client/src/components/transactions/TransactionsTable.js
  packages/desktop-client/src/components/util/GenericInput.js
  upcoming-release-notes/1614.md
Labels: ✅ Approved

#1630 Replace format with useFormat
  packages/desktop-client/src/components/accounts/Balance.js
  packages/desktop-client/src/components/accounts/Reconcile.js
  packages/desktop-client/src/components/budget/MobileBudgetTable.js
  packages/desktop-client/src/components/budget/report/BudgetSummary.tsx
  packages/desktop-client/src/components/budget/report/components.tsx
  packages/desktop-client/src/components/budget/rollover/BudgetSummary.tsx
  packages/desktop-client/src/components/budget/rollover/rollover-components.tsx
  packages/desktop-client/src/components/modals/BudgetSummary.js
  packages/desktop-client/src/components/spreadsheet/CellValue.tsx
  packages/desktop-client/src/components/spreadsheet/useFormat.ts
  packages/desktop-client/src/components/table.tsx
  upcoming-release-notes/1630.md
Labels: ✅ Approved

#1566 :recycle: convert budget component from class to hook component
  packages/desktop-client/src/components/budget/index.js
  upcoming-release-notes/1566.md
Labels: ✅ Approved

#1600 Experimental OFX parser
  packages/desktop-client/package.json
  packages/desktop-client/src/components/modals/ImportTransactions.js
  packages/desktop-client/src/components/settings/Experimental.tsx
  packages/desktop-client/src/hooks/useFeatureFlag.ts
  packages/loot-core/src/mocks/files/8859-1.qfx
  packages/loot-core/src/server/accounts/ofx2json.ts
  packages/loot-core/src/server/accounts/parse-file.test.ts
  packages/loot-core/src/server/accounts/parse-file.ts
  packages/loot-core/src/types/prefs.d.ts
  packages/loot-core/webpack/webpack.browser.config.js
  upcoming-release-notes/1600.md
  yarn.lock
Labels: ✅ Approved

#1597 :recycle: use useCategories everywhere
  packages/desktop-client/src/components/ManageRules.js
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/accounts/Account.js
  packages/desktop-client/src/components/budget/MobileBudget.js
  packages/desktop-client/src/components/budget/index.js
  packages/desktop-client/src/components/modals/EditField.js
  packages/desktop-client/src/components/payees/ManagePayeesWithData.js
  packages/desktop-client/src/components/rules/Value.tsx
  packages/desktop-client/src/components/transactions/MobileTransaction.js
  packages/desktop-client/src/components/transactions/SimpleTransactionsTable.js
  packages/desktop-client/src/components/util/GenericInput.js
  upcoming-release-notes/1597.md
Labels: ✅ Approved

#1643 :arrow_up: (better-sqlite3) upgrade to 8.6.0 to fix electron export crash
  packages/api/package.json
  packages/loot-core/package.json
  upcoming-release-notes/1643.md
  yarn.lock
Labels: ✅ Approved

#1587 Add support for markdown in notes
  packages/desktop-client/package.json
  packages/desktop-client/src/components/NotesButton.tsx
  packages/desktop-client/src/util/markdown.ts
  upcoming-release-notes/1587.md
  yarn.lock
Labels: 🔍 Ready for Review

#1644 [refactor] Schedules component in tsx
  packages/desktop-client/src/components/common/Search.tsx
  packages/desktop-client/src/components/schedules/index.tsx
  packages/desktop-client/src/components/settings/Encryption.tsx
  packages/loot-core/src/client/actions/budgets.ts
  packages/loot-core/src/client/actions/modals.ts
  packages/loot-core/src/client/data-hooks/schedules.tsx
  upcoming-release-notes/1644.md
Labels: ✅ Approved

#1645 Fix onNavigateToSchedule prop
  packages/desktop-client/src/components/transactions/TransactionsTable.js
  upcoming-release-notes/1645.md
Labels: ✅ Approved

#1637 Remove glamor css
  packages/desktop-client/src/components/AppBackground.tsx
  packages/desktop-client/src/components/NotesButton.tsx
  packages/desktop-client/src/components/autocomplete/Autocomplete.tsx
  packages/desktop-client/src/components/budget/BudgetSummaries.js
  packages/desktop-client/src/components/budget/report/BudgetSummary.tsx
  packages/desktop-client/src/components/budget/rollover/BudgetSummary.tsx
  packages/desktop-client/src/components/common/AnchorLink.tsx
  packages/desktop-client/src/components/common/Block.tsx
  packages/desktop-client/src/components/common/InlineField.tsx
  packages/desktop-client/src/components/common/Input.tsx
  packages/desktop-client/src/components/common/LinkButton.tsx
  packages/desktop-client/src/components/common/Paragraph.tsx
  packages/desktop-client/src/components/common/Select.tsx
  packages/desktop-client/src/components/common/Text.tsx
  packages/desktop-client/src/components/common/View.tsx
  packages/desktop-client/src/components/forms.tsx
  packages/desktop-client/src/components/mobile/MobileForms.js
  packages/desktop-client/src/components/modals/CreateEncryptionKey.js
  packages/desktop-client/src/components/reports/Tooltip.js
  packages/desktop-client/src/components/settings/UI.tsx
  packages/desktop-client/src/components/sidebar/Account.tsx
  packages/desktop-client/src/components/tooltips.js
  packages/desktop-client/src/components/transactions/MobileTransaction.js
  packages/desktop-client/src/icons/AnimatedLoading.js
  upcoming-release-notes/1637.md
Labels: 🔍 Ready for Review

#1648 Fix mobile page "back" behaviors
  packages/desktop-client/src/components/accounts/MobileAccountDetails.js
  packages/desktop-client/src/components/transactions/MobileTransaction.js
  upcoming-release-notes/1648.md
Labels: ✅ Approved

#1646 Fix blur performance issue in Safari
  packages/desktop-client/src/components/PrivacyFilter.tsx
  upcoming-release-notes/1646.md
Labels: ✅ Approved

#1584 Break apart budget/misc.js
  .eslintrc.js
  packages/desktop-client/e2e/budget.test.js-snapshots/Budget-renders-the-summary-information-available-funds-overspent-budgeted-and-for-next-month-1-chromium-linux.png
  packages/desktop-client/e2e/budget.test.js-snapshots/Budget-transfer-funds-to-another-category-1-chromium-linux.png
  packages/desktop-client/src/components/budget/BudgetCategories.js
  packages/desktop-client/src/components/budget/BudgetPageHeader.js
  packages/desktop-client/src/components/budget/BudgetTable.js
  packages/desktop-client/src/components/budget/BudgetTotals.js
  packages/desktop-client/src/components/budget/CategoryGroupsContext.js
  packages/desktop-client/src/components/budget/DynamicBudgetTable.js
  packages/desktop-client/src/components/budget/ExpenseCategory.js
  packages/desktop-client/src/components/budget/ExpenseGroup.js
  packages/desktop-client/src/components/budget/IncomeCategory.js
  packages/desktop-client/src/components/budget/IncomeGroup.js
  packages/desktop-client/src/components/budget/IncomeHeader.js
  packages/desktop-client/src/components/budget/RenderMonths.js
  packages/desktop-client/src/components/budget/SidebarCategory.js
  packages/desktop-client/src/components/budget/SidebarGroup.js
  packages/desktop-client/src/components/budget/misc.js
  packages/desktop-client/src/components/budget/rollover/TransferTooltip.tsx
  packages/desktop-client/src/components/budget/rollover/rollover-components.tsx
  packages/desktop-client/src/components/budget/util.js
  upcoming-release-notes/1584.md
Labels: 🔍 Ready for Review

#1634 Fix submit form on enter key pressed
  packages/desktop-client/src/components/common/Button.tsx
  packages/desktop-client/src/components/modals/FixEncryptionKey.js
  upcoming-release-notes/1634.md
Labels: 🔍 Ready for Review

#1649 Fix ofx/qfx import options
  packages/desktop-client/src/components/modals/ImportTransactions.js
  upcoming-release-notes/1649.md
Labels: ✅ Approved

#1639 Change Accounts page BUDGET label to FOR BUDGET in mobile
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-the-accounts-page-and-asserts-on-balances-1-chromium-linux.png
  packages/desktop-client/src/components/accounts/MobileAccounts.js
  upcoming-release-notes/1639.md
Labels: ✅ Approved

#1650 Webpack + SWC Loader
  packages/crdt/jest.config.js
  packages/crdt/package.json
  packages/desktop-client/.swcrc
  packages/desktop-client/config-overrides.js
  packages/desktop-client/craco.config.ts
  packages/desktop-client/package.json
  packages/loot-core/.babelrc
  packages/loot-core/.swcrc
  packages/loot-core/jest.config.js
  packages/loot-core/jest.web.config.js
  packages/loot-core/package.json
  packages/loot-core/webpack/webpack.browser.config.js
  tsconfig.json
  upcoming-release-notes/1650.md
  yarn.lock
Labels: ✅ Approved

#1660 TypeScript migration (partial).
  packages/desktop-client/src/components/schedules/SchedulesTable.tsx
  packages/desktop-client/src/components/schedules/StatusBadge.tsx
  packages/desktop-client/src/components/table.tsx
  upcoming-release-notes/1660.md
Labels: ✅ Approved

#1656 Mobile: don't show hidden income categories
  packages/desktop-client/src/components/budget/MobileBudgetTable.js
  upcoming-release-notes/1656.md
Labels: ✅ Approved

#1659 Enable swc sourcemap
  packages/desktop-client/.swcrc
  packages/loot-core/.swcrc
  upcoming-release-notes/1659.md
Labels: ✅ Approved

#1654 Mobile: Dont show hidden groups
  packages/desktop-client/src/components/budget/MobileBudgetTable.js
  upcoming-release-notes/1654.md
Labels: ✅ Approved

#1665 :bug: (mobile) fix sync button design
  packages/desktop-client/src/components/Titlebar.tsx
  packages/desktop-client/src/components/budget/MobileBudgetTable.js
  upcoming-release-notes/1665.md
Labels: ✅ Approved

#1663 :sparkles: (mobile) pull down to trigger bank-sync
  packages/desktop-client/package.json
  packages/desktop-client/src/components/accounts/MobileAccount.js
  packages/desktop-client/src/components/accounts/MobileAccountDetails.js
  packages/desktop-client/src/components/accounts/MobileAccounts.js
  packages/desktop-client/src/components/transactions/MobileTransaction.js
  upcoming-release-notes/1663.md
  yarn.lock
Labels: ✅ Approved

#1658 :wrench: (electron) improved OS detection
  package.json
  packages/loot-core/src/client/platform.electron.ts
  upcoming-release-notes/1658.md
Labels: ✅ Approved

#1668 Left over glamor style cleanup
  packages/desktop-client/e2e/budget.test.js-snapshots/Budget-renders-the-summary-information-available-funds-overspent-budgeted-and-for-next-month-1-chromium-linux.png
  packages/desktop-client/e2e/budget.test.js-snapshots/Budget-transfer-funds-to-another-category-1-chromium-linux.png
  packages/desktop-client/src/components/budget/BudgetTable.js
  packages/desktop-client/src/components/budget/ExpenseCategory.js
  packages/desktop-client/src/components/budget/RenderMonths.js
  packages/desktop-client/src/components/budget/SidebarCategory.js
  packages/desktop-client/src/components/budget/SidebarGroup.js
  upcoming-release-notes/1668.md
Labels: ✅ Approved

#1657 :bug: (signup) fix setting up for the first time with missing protocol
  packages/desktop-client/src/components/manager/ConfigServer.tsx
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/server/server-config.ts
  upcoming-release-notes/1657.md
Labels: ✅ Approved

#1669 :bug: (mobile) fix schedule status positioning
  packages/desktop-client/src/components/transactions/MobileTransaction.js
  upcoming-release-notes/1669.md
Labels: ✅ Approved

#1670 refactor budget/IncomeHeader to tsx
  packages/desktop-client/src/components/budget/IncomeHeader.tsx
  upcoming-release-notes/1670.md
Labels: ✅ Approved

#1599 🔧 (eslint) convert rules from ERROR to WARN to improve devX
  .eslintrc.js
  upcoming-release-notes/1599.md
Labels: ✅ Approved

#1487 DarkTheme Schedules/Payees
  .eslintrc.js
  packages/desktop-client/src/components/manager/subscribe/Bootstrap.tsx
  packages/desktop-client/src/components/manager/subscribe/ChangePassword.tsx
  packages/desktop-client/src/components/manager/subscribe/Error.tsx
  packages/desktop-client/src/components/manager/subscribe/Login.tsx
  packages/desktop-client/src/components/manager/subscribe/common.tsx
  packages/desktop-client/src/components/modals/MergeUnusedPayees.js
  packages/desktop-client/src/components/payees/index.js
  packages/desktop-client/src/components/schedules/DiscoverSchedules.js
  packages/desktop-client/src/components/schedules/PostsOfflineNotification.js
  packages/desktop-client/src/components/schedules/SchedulesTable.tsx
  packages/desktop-client/src/components/schedules/StatusBadge.tsx
  packages/desktop-client/src/components/schedules/index.tsx
  packages/desktop-client/src/components/select/DateSelect.js
  packages/desktop-client/src/components/select/RecurringSchedulePicker.js
  packages/desktop-client/src/components/sidebar/Account.tsx
  packages/desktop-client/src/components/sidebar/Item.tsx
  packages/desktop-client/src/components/sidebar/SecondaryItem.tsx
  packages/desktop-client/src/components/sidebar/Sidebar.tsx
  packages/desktop-client/src/components/util/AmountInput.js
  packages/desktop-client/src/style/palette.ts
  packages/desktop-client/src/style/themes/dark.ts
  packages/desktop-client/src/style/themes/development.ts
  packages/desktop-client/src/style/themes/light.ts
  upcoming-release-notes/1487.md
Labels: ✅ Approved

#1679 Mobile: Show proper name of income group
  packages/desktop-client/src/components/budget/MobileBudgetTable.js
  upcoming-release-notes/1679.md
Labels: ✅ Approved

#1674 :arrow_up: (electron) upgrading electron-based dependencies
  packages/desktop-electron/package.json
  upcoming-release-notes/1674.md
  yarn.lock
Labels: ✅ Approved

#1672 :white_check_mark: (e2e) adding sample schedules to test budget
  packages/desktop-client/e2e/mobile.test.js
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-from-accounts-id-page-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-1-chromium-linux.png
  packages/desktop-client/e2e/page-models/rules-page.js
  packages/desktop-client/e2e/page-models/schedules-page.js
  packages/desktop-client/e2e/rules.test.js
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-checks-the-page-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-checks-the-page-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-1-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-2-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-3-chromium-linux.png
  packages/desktop-client/src/components/ManageRules.js
  packages/desktop-client/src/components/transactions/MobileTransaction.js
  packages/desktop-client/src/util/versions.ts
  packages/loot-core/src/mocks/budget.ts
  packages/loot-core/src/server/schedules/app.ts
  packages/loot-core/src/server/schedules/types/handlers.ts
  upcoming-release-notes/1672.md
Labels: ✅ Approved

#1503 Dark Theme Manager and Modals
  .eslintrc.js
  packages/desktop-client/src/components/BankSyncStatus.tsx
  packages/desktop-client/src/components/alerts.tsx
  packages/desktop-client/src/components/manager/BudgetList.js
  packages/desktop-client/src/components/manager/ConfigServer.tsx
  packages/desktop-client/src/components/manager/DeleteFile.js
  packages/desktop-client/src/components/manager/Import.js
  packages/desktop-client/src/components/manager/ImportActual.tsx
  packages/desktop-client/src/components/manager/ImportYNAB4.tsx
  packages/desktop-client/src/components/manager/ImportYNAB5.tsx
  packages/desktop-client/src/components/manager/WelcomeScreen.js
  packages/desktop-client/src/components/modals/ConfirmCategoryDelete.js
  packages/desktop-client/src/components/modals/CreateEncryptionKey.js
  packages/desktop-client/src/components/modals/EditField.js
  packages/desktop-client/src/components/modals/FixEncryptionKey.js
  packages/desktop-client/src/components/modals/GoCardlessExternalMsg.js
  packages/desktop-client/src/components/modals/ImportTransactions.js
  packages/desktop-client/src/components/modals/LoadBackup.js
  packages/desktop-client/src/components/modals/PlaidExternalMsg.js
  packages/desktop-client/src/components/util/DisplayId.js
  packages/desktop-client/src/components/util/LoadComponent.tsx
  packages/desktop-client/src/style/themes/dark.ts
  packages/desktop-client/src/style/themes/light.ts
  upcoming-release-notes/1503.md
Labels: ✅ Approved

#1688 🔥 removing privacyMode feature flag
  packages/desktop-client/src/components/PrivacyFilter.tsx
  packages/desktop-client/src/components/Titlebar.tsx
  packages/desktop-client/src/components/settings/Experimental.tsx
  packages/desktop-client/src/hooks/useFeatureFlag.ts
  packages/loot-core/src/types/prefs.d.ts
  upcoming-release-notes/1688.md
Labels: ✅ Approved

#1687 :art: fix multiline label in schedules modal
  packages/desktop-client/src/components/schedules/EditSchedule.js
  upcoming-release-notes/1687.md
Labels: ✅ Approved

#1689 Update Visual Regression README File
  packages/desktop-client/README.md
Labels: ✅ Approved

#1684 Fix typo in GoCardlessLink.js
  packages/desktop-client/src/components/gocardless/GoCardlessLink.js
Labels: 🔍 Ready for Review, ✅ Approved

#1678 queried cleared balance for tooltip
  packages/desktop-client/src/components/accounts/Reconcile.js
  upcoming-release-notes/1678.md
Labels: ✅ Approved

#1512 Dark Theme Reports/Settings
  .eslintrc.js
  packages/desktop-client/src/components/budget/report/BudgetSummary.tsx
  packages/desktop-client/src/components/budget/report/components.tsx
  packages/desktop-client/src/components/common/Card.tsx
  packages/desktop-client/src/components/common/Label.tsx
  packages/desktop-client/src/components/reports/CashFlow.js
  packages/desktop-client/src/components/reports/Change.js
  packages/desktop-client/src/components/reports/DateRange.js
  packages/desktop-client/src/components/reports/Header.js
  packages/desktop-client/src/components/reports/NetWorth.js
  packages/desktop-client/src/components/reports/Overview.js
  packages/desktop-client/src/components/reports/Tooltip.js
  packages/desktop-client/src/components/reports/chart-theme.js
  packages/desktop-client/src/components/reports/graphs/CashFlowGraph.tsx
  packages/desktop-client/src/components/reports/graphs/CategorySpendingGraph.tsx
  packages/desktop-client/src/components/reports/graphs/NetWorthGraph.tsx
  packages/desktop-client/src/components/reports/graphs/common.tsx
  packages/desktop-client/src/components/settings/Encryption.tsx
  packages/desktop-client/src/components/settings/Experimental.tsx
  packages/desktop-client/src/components/settings/FixSplits.tsx
  packages/desktop-client/src/components/settings/Global.tsx
  packages/desktop-client/src/components/settings/UI.tsx
  packages/desktop-client/src/components/settings/index.tsx
  packages/desktop-client/src/style/themes/dark.ts
  packages/desktop-client/src/style/themes/development.ts
  packages/desktop-client/src/style/themes/light.ts
  upcoming-release-notes/1512.md
Labels: ✅ Approved

#1698 :bug: Mobile account transaction list: Fix sticky date section headers
  packages/desktop-client/src/components/transactions/MobileTransaction.js
  upcoming-release-notes/1698.md
Labels: ✅ Approved

#1692 :construction_worker: do not cancel github ci jobs on master branch
  .github/workflows/build.yml
  .github/workflows/check.yml
  .github/workflows/codeql.yml
  .github/workflows/electron.yml
  upcoming-release-notes/1692.md
Labels: ✅ Approved

#1703 Sidebar Account Fix
  packages/desktop-client/src/components/sidebar/Account.tsx
  packages/desktop-client/src/style/themes/dark.ts
  packages/desktop-client/src/style/themes/light.ts
  upcoming-release-notes/1703.md
Labels: ✅ Approved

#1513 Dark Theme Final
  .eslintrc.js
  packages/desktop-client/src/components/LoggedInUser.tsx
  packages/desktop-client/src/components/MobileWebMessage.tsx
  packages/desktop-client/src/components/NotesButton.tsx
  packages/desktop-client/src/components/Notifications.tsx
  packages/desktop-client/src/components/Page.tsx
  packages/desktop-client/src/components/Titlebar.tsx
  packages/desktop-client/src/components/UpdateNotification.tsx
  packages/desktop-client/src/components/accounts/Header.js
  packages/desktop-client/src/components/budget/BudgetCategories.js
  packages/desktop-client/src/components/budget/BudgetTotals.js
  packages/desktop-client/src/components/budget/ExpenseGroup.js
  packages/desktop-client/src/components/budget/IncomeGroup.js
  packages/desktop-client/src/components/budget/MobileBudget.js
  packages/desktop-client/src/components/budget/MobileBudgetTable.js
  packages/desktop-client/src/components/budget/MobileTable.tsx
  packages/desktop-client/src/components/budget/MonthCountSelector.tsx
  packages/desktop-client/src/components/budget/MonthPicker.js
  packages/desktop-client/src/components/budget/RenderMonths.js
  packages/desktop-client/src/components/budget/SidebarCategory.js
  packages/desktop-client/src/components/budget/SidebarGroup.js
  packages/desktop-client/src/components/budget/constants.js
  packages/desktop-client/src/components/budget/rollover/BudgetSummary.tsx
  packages/desktop-client/src/components/budget/rollover/rollover-components.tsx
  packages/desktop-client/src/components/budget/util.js
  packages/desktop-client/src/components/common/ExternalLink.tsx
  packages/desktop-client/src/components/mobile/MobileForms.js
  packages/desktop-client/src/components/modals/BudgetSummary.js
  packages/desktop-client/src/components/transactions/MobileTransaction.js
  packages/desktop-client/src/components/transactions/TransactionsTable.js
  packages/desktop-client/src/style/styles.ts
  packages/desktop-client/src/style/themes/dark.ts
  packages/desktop-client/src/style/themes/development.ts
  packages/desktop-client/src/style/themes/light.ts
  upcoming-release-notes/1513.md
Labels: ✅ Approved

#1681 Category autocomplete should only search selectable categories
  packages/desktop-client/src/components/autocomplete/CategoryAutocomplete.tsx
  packages/desktop-client/src/components/transactions/TransactionsTable.test.js
  upcoming-release-notes/1681.md
Labels: ✅ Approved

#1691 [refactor] Migrate Schedules Table to typescript
  packages/desktop-client/src/components/common/Menu.tsx
  packages/desktop-client/src/components/schedules/SchedulesTable.tsx
  packages/desktop-client/src/components/schedules/StatusBadge.tsx
  packages/desktop-client/src/components/schedules/index.tsx
  packages/desktop-client/src/components/table.tsx
  packages/loot-core/src/client/data-hooks/accounts.tsx
  packages/loot-core/src/client/data-hooks/payees.tsx
  packages/loot-core/src/client/data-hooks/schedules.tsx
  packages/loot-core/src/shared/util.ts
  packages/loot-core/src/types/models/schedule.d.ts
  upcoming-release-notes/1691.md
Labels: ✅ Approved

#1707 :wrench: removing unnecessary manual module resolution
  package.json
  upcoming-release-notes/1707.md
  yarn.lock
Labels: ✅ Approved

#1706 :bug: (mobile) scrolling in lists with pull-to-refresh
  packages/desktop-client/src/components/accounts/MobileAccountDetails.js
  packages/desktop-client/src/components/accounts/MobileAccounts.js
  packages/desktop-client/src/components/responsive/PullToRefresh.tsx
  upcoming-release-notes/1706.md
Labels: ✅ Approved

#1705 :lipstick: (mobile) updating apple home-screen icon
  packages/desktop-client/public/apple-touch-icon.png
  upcoming-release-notes/1705.md
Labels: ✅ Approved

#1709 Enhance Y-Axis Scaling on Net Worth Graph
  packages/desktop-client/src/components/reports/NetWorth.js
  packages/desktop-client/src/components/reports/graphs/NetWorthGraph.tsx
  packages/desktop-client/src/components/reports/graphs/net-worth-spreadsheet.tsx
  upcoming-release-notes/1709.md
Labels: ✅ Approved

#1718 Goals: speed up and a bugfix
  packages/loot-core/src/server/budget/goaltemplates.ts
  upcoming-release-notes/1718.md
Labels: ✅ Approved

#1722 refactor BudgetMonthCountContext to tsx
  packages/desktop-client/src/components/budget/BudgetMonthCountContext.js
  packages/desktop-client/src/components/budget/BudgetMonthCountContext.tsx
  upcoming-release-notes/1722.md
Labels: ✅ Approved

#1677 :recycle: moving rule server actions to separate file
  packages/desktop-client/src/components/rules/ActionExpression.tsx
  packages/desktop-client/src/components/rules/RuleRow.tsx
  packages/loot-core/src/server/accounts/transaction-rules.ts
  packages/loot-core/src/server/accounts/transactions.ts
  packages/loot-core/src/server/errors.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/server/rules/app.ts
  packages/loot-core/src/server/rules/types/handlers.ts
  packages/loot-core/src/types/models/rule.d.ts
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/1677.md
Labels: ✅ Approved

#1721 :bug: (mobile) redirect to budget page for all 404
  packages/desktop-client/src/components/FinancesApp.tsx
  upcoming-release-notes/1721.md
Labels: ✅ Approved

#1723 changed default months to 5 in cash flow report
  packages/desktop-client/src/components/reports/CashFlow.js
  upcoming-release-notes/1723.md
Labels: ✅ Approved

#1708 fix: filter empty note
  packages/loot-core/src/server/accounts/rules.ts
  packages/loot-core/src/server/accounts/transaction-rules.test.ts
  packages/loot-core/src/server/accounts/transaction-rules.ts
  packages/loot-core/src/shared/rules.ts
  upcoming-release-notes/1708.md
Labels: ✅ Approved

#1725 Add link type to Button Component
  packages/desktop-client/src/components/common/Button.tsx
  packages/desktop-client/src/components/settings/UI.tsx
  upcoming-release-notes/1725.md
Labels: ✅ Approved

#1729 Fix schedule searchbar
  packages/desktop-client/e2e/schedules.test.js
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-checks-the-page-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-1-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-2-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-3-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-4-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-split-test-transaction-1-chromium-linux.png
  packages/desktop-client/src/components/schedules/index.tsx
  upcoming-release-notes/1729.md
Labels: 🔍 Ready for Review

#1728 keep name after schedule completion or recreation
  packages/loot-core/src/server/schedules/app.ts
  upcoming-release-notes/1728.md
Labels: ✅ Approved

#1733 Maintenance: Consolidate useMergedRef and convert to typescript
  packages/desktop-client/src/components/sort.tsx
  packages/desktop-client/src/hooks/useMergedRefs.ts
  upcoming-release-notes/1733.md
Labels: ✅ Approved

#1734 Goal progress bar
  packages/desktop-client/e2e/schedules.test.js
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-checks-the-page-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-1-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-2-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-3-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-4-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-split-test-transaction-1-chromium-linux.png
  packages/desktop-client/src/components/budget/BalanceWithCarryover.tsx
  packages/desktop-client/src/components/budget/report/components.tsx
  packages/desktop-client/src/components/budget/rollover/rollover-components.tsx
  packages/desktop-client/src/components/budget/util.js
  packages/desktop-client/src/components/schedules/index.tsx
  packages/desktop-client/src/components/spreadsheet/CellValue.tsx
  packages/loot-core/migrations/1694438752000_add_goal_targets.sql
  packages/loot-core/src/client/queries.ts
  packages/loot-core/src/server/budget/actions.ts
  packages/loot-core/src/server/budget/goaltemplates.ts
  packages/loot-core/src/server/budget/types/handlers.d.ts
  packages/loot-core/src/server/sheet.ts
  upcoming-release-notes/1682.md
  upcoming-release-notes/1729.md
Labels: 🔍 Ready for Review

#1738 [Bugfix]: Goals - Fixed an overbudgeting condition
  packages/loot-core/src/server/budget/goaltemplates.ts
  upcoming-release-notes/1738.md
Labels: ✅ Approved

#1680 :recycle: (typescript) hardening data entity types
  packages/loot-core/src/mocks/budget.ts
  packages/loot-core/src/mocks/index.ts
  packages/loot-core/src/types/models/account.d.ts
  packages/loot-core/src/types/models/category-group.d.ts
  packages/loot-core/src/types/models/payee.d.ts
  packages/loot-core/src/types/models/rule.d.ts
  packages/loot-core/src/types/models/transaction.d.ts
  upcoming-release-notes/1680.md
Labels: ✅ Approved
