Repository actualbudget/actual, pull requests merged in 2023-11, with the labels that each got.

#1855 :bug: fix: add missing top border for budget menu icon
  packages/desktop-client/src/components/budget/rollover/rollover-components.tsx
  upcoming-release-notes/1855.md
Labels: ✅ Approved

#1856 :bug: fix: bring back rollover arrow in budget page
  packages/desktop-client/src/components/budget/BalanceWithCarryover.tsx
  packages/desktop-client/src/components/budget/report/components.tsx
  packages/desktop-client/src/components/budget/rollover/rollover-components.tsx
  upcoming-release-notes/1856.md
Labels: ✅ Approved

#1859 :bookmark: (23.11.0)
  packages/desktop-client/package.json
  packages/desktop-electron/package.json
  upcoming-release-notes/1662.md
  upcoming-release-notes/1694.md
  upcoming-release-notes/1720.md
  upcoming-release-notes/1724.md
  upcoming-release-notes/1737.md
  upcoming-release-notes/1740.md
  upcoming-release-notes/1743.md
  upcoming-release-notes/1745.md
  upcoming-release-notes/1750.md
  upcoming-release-notes/1751.md
  upcoming-release-notes/1753.md
  upcoming-release-notes/1755.md
  upcoming-release-notes/1756.md
  upcoming-release-notes/1759.md
  upcoming-release-notes/1768.md
  upcoming-release-notes/1770.md
  upcoming-release-notes/1774.md
  upcoming-release-notes/1776.md
  upcoming-release-notes/1781.md
  upcoming-release-notes/1783.md
  upcoming-release-notes/1784.md
  upcoming-release-notes/1785.md
  upcoming-release-notes/1795.md
  upcoming-release-notes/1797.md
  upcoming-release-notes/1799.md
  upcoming-release-notes/1800.md
  upcoming-release-notes/1802.md
  upcoming-release-notes/1808.md
  upcoming-release-notes/1814.md
  upcoming-release-notes/1819.md
  upcoming-release-notes/1823.md
  upcoming-release-notes/1824.md
  upcoming-release-notes/1844.md
  upcoming-release-notes/1855.md
  upcoming-release-notes/1856.md
Labels: ✅ Approved

#1834 Maintenance: Moving some components to Typescript
  packages/desktop-client/src/components/Titlebar.tsx
  packages/desktop-client/src/components/budget/BudgetPageHeader.tsx
  packages/desktop-client/src/components/budget/DynamicBudgetTable.tsx
  packages/desktop-client/src/components/budget/index.tsx
  packages/desktop-client/src/components/budget/rollover/HoldTooltip.tsx
  packages/desktop-client/src/components/budget/rollover/TransferTooltip.tsx
  packages/desktop-client/src/components/table.tsx
  packages/loot-core/src/client/SpreadsheetProvider.tsx
  packages/loot-core/src/client/actions/queries.ts
  packages/loot-core/src/server/spreadsheet/spreadsheet.ts
  packages/loot-core/src/types/prefs.d.ts
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/1834.md
Labels: ✅ Approved

#1820 fix styling of transaction page on mobile
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-from-accounts-id-page-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-2-chromium-linux.png
  packages/desktop-client/src/components/mobile/MobileForms.js
  packages/desktop-client/src/components/transactions/MobileTransaction.js
  upcoming-release-notes/1820.md
Labels: ✅ Approved

#1840 fixed:issue->#1762 Schedule creation modal notify user of weekend skip option
  packages/loot-core/src/shared/schedules.ts
  upcoming-release-notes/1840.md
Labels: ✅ Approved

#1765 [Bugfix]: Dark mode - darker tint for pageTextLink
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-checks-that-settings-page-can-be-opened-2-chromium-linux.png
  packages/desktop-client/e2e/settings.test.js-snapshots/Settings-checks-the-page-visuals-1-chromium-linux.png
  packages/desktop-client/src/components/settings/Encryption.tsx
  packages/desktop-client/src/components/settings/index.tsx
  packages/desktop-client/src/style/themes/dark.ts
  upcoming-release-notes/1765.md
Labels: ✅ Approved

#1858 Mobile budget pull down to sync
  packages/desktop-client/src/components/budget/MobileBudget.js
  packages/desktop-client/src/components/budget/MobileBudgetTable.js
  upcoming-release-notes/1858.md
Labels: ✅ Approved

#1836 fixed:issue->#1835 Support NYNAB import of transactions that contain subtransactions tha…
  packages/desktop-client/e2e/data/ynab5-demo-budget.json
  packages/desktop-client/e2e/onboarding.test.js
  packages/loot-core/src/server/importers/ynab5-types.d.ts
  packages/loot-core/src/server/importers/ynab5.ts
  upcoming-release-notes/1836.md
Labels: ✅ Approved

#1788 Enhancement: Add option to select in/out field during import
  packages/desktop-client/src/components/modals/ImportTransactions.js
  upcoming-release-notes/1788.md
Labels: ✅ Approved

#1798 Warning Color Consolidations
  packages/desktop-client/src/components/DevelopmentTopBar.tsx
  packages/desktop-client/src/components/Notifications.tsx
  packages/desktop-client/src/components/budget/MobileBudgetTable.js
  packages/desktop-client/src/components/budget/report/BudgetSummary.tsx
  packages/desktop-client/src/components/schedules/StatusBadge.tsx
  packages/desktop-client/src/components/transactions/MobileTransaction.js
  packages/desktop-client/src/components/transactions/TransactionsTable.js
  packages/desktop-client/src/icons/v2/Eye.tsx
  packages/desktop-client/src/style/themes/dark.ts
  packages/desktop-client/src/style/themes/development.ts
  packages/desktop-client/src/style/themes/light.ts
  upcoming-release-notes/1798.md
Labels: ✅ Approved

#1867 [Bugfix]: Account filter for budgeted and offbudget accounts
  packages/loot-core/src/client/queries.ts
  upcoming-release-notes/1867.md
Labels: ✅ Approved

#1780 Goals: Save full goal value and add an indicator of goal status
  packages/desktop-client/src/components/budget/BalanceWithCarryover.tsx
  packages/desktop-client/src/components/budget/MobileBudgetTable.js
  packages/desktop-client/src/components/budget/report/components.tsx
  packages/desktop-client/src/components/budget/rollover/rollover-components.tsx
  packages/desktop-client/src/components/budget/util.ts
  packages/loot-core/migrations/1694438752000_add_goal_targets.sql
  packages/loot-core/src/client/queries.ts
  packages/loot-core/src/server/budget/actions.ts
  packages/loot-core/src/server/budget/base.ts
  packages/loot-core/src/server/budget/goaltemplates.ts
  packages/loot-core/src/server/budget/types/handlers.d.ts
  packages/loot-core/src/server/sheet.ts
  upcoming-release-notes/1780.md
Labels: 🔍 Ready for Review

#1864 Make Select All respect filters and splits
  packages/desktop-client/src/components/accounts/Account.js
  packages/desktop-client/src/hooks/useSelected.tsx
  upcoming-release-notes/1864.md
Labels: ✅ Approved

#1862 Support month names when importing transactions
  packages/desktop-client/src/components/modals/ImportTransactions.js
  packages/desktop-client/src/components/modals/ImportTransactions.test.js
  upcoming-release-notes/1862.md
Labels: ✅ Approved

#1871 Final Colors Consolidation
  packages/desktop-client/src/components/Titlebar.tsx
  packages/desktop-client/src/components/accounts/Account.js
  packages/desktop-client/src/components/autocomplete/AccountAutocomplete.js
  packages/desktop-client/src/components/autocomplete/Autocomplete.tsx
  packages/desktop-client/src/components/autocomplete/CategoryAutocomplete.tsx
  packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.js
  packages/desktop-client/src/components/autocomplete/SavedFilterAutocomplete.js
  packages/desktop-client/src/components/budget/BudgetCategories.js
  packages/desktop-client/src/components/budget/ExpenseGroup.js
  packages/desktop-client/src/components/budget/IncomeGroup.tsx
  packages/desktop-client/src/components/budget/MobileBudgetTable.js
  packages/desktop-client/src/components/budget/SidebarGroup.tsx
  packages/desktop-client/src/components/budget/rollover/BudgetSummary.tsx
  packages/desktop-client/src/components/budget/rollover/rollover-components.tsx
  packages/desktop-client/src/components/budget/util.ts
  packages/desktop-client/src/components/common/Menu.tsx
  packages/desktop-client/src/components/common/Search.tsx
  packages/desktop-client/src/components/filters/FiltersMenu.js
  packages/desktop-client/src/components/modals/EditField.js
  packages/desktop-client/src/components/modals/LoadBackup.js
  packages/desktop-client/src/components/reports/Overview.js
  packages/desktop-client/src/components/reports/Tooltip.js
  packages/desktop-client/src/components/reports/graphs/NetWorthGraph.tsx
  packages/desktop-client/src/components/schedules/DiscoverSchedules.js
  packages/desktop-client/src/components/schedules/StatusBadge.tsx
  packages/desktop-client/src/components/transactions/MobileTransaction.js
  packages/desktop-client/src/components/transactions/TransactionsTable.js
  packages/desktop-client/src/style/themes/dark.ts
  packages/desktop-client/src/style/themes/development.ts
  packages/desktop-client/src/style/themes/light.ts
  upcoming-release-notes/1871.md
Labels: ✅ Approved

#1875 Remove Static Colors
  packages/desktop-client/src/components/budget/BudgetCategories.js
  packages/desktop-client/src/components/budget/SidebarCategory.js
  packages/desktop-client/src/components/budget/report/components.tsx
  packages/desktop-client/src/components/budget/rollover/rollover-components.tsx
  packages/desktop-client/src/components/transactions/TransactionsTable.js
  upcoming-release-notes/1875.md
Labels: 🔍 Ready for Review

#1879 Maintenance: BudgetSummaries, MonthPicker, SidebarCategory components to tsx.
  packages/desktop-client/src/components/budget/BudgetSummaries.tsx
  packages/desktop-client/src/components/budget/ExpenseGroup.js
  packages/desktop-client/src/components/budget/MonthPicker.tsx
  packages/desktop-client/src/components/budget/MonthsContext.tsx
  packages/desktop-client/src/components/budget/SidebarCategory.tsx
  packages/desktop-client/src/components/budget/SidebarGroup.tsx
  packages/desktop-client/src/components/budget/rollover/BudgetSummary.tsx
  packages/desktop-client/src/hooks/useResizeObserver.ts
  upcoming-release-notes/1879.md
Labels: ✅ Approved

#1888 [Maintenance] Goals break out goal target calculations to individual files
  packages/loot-core/src/server/budget/goals/goalsBy.ts
  packages/loot-core/src/server/budget/goals/goalsPercentage.ts
  packages/loot-core/src/server/budget/goals/goalsRemainder.ts
  packages/loot-core/src/server/budget/goals/goalsSchedule.ts
  packages/loot-core/src/server/budget/goals/goalsSimple.ts
  packages/loot-core/src/server/budget/goals/goalsSpend.ts
  packages/loot-core/src/server/budget/goals/goalsWeek.ts
  packages/loot-core/src/server/budget/goaltemplates.ts
  upcoming-release-notes/1888.md
Labels: ✅ Approved

#1893 :wrench: (eslint) enabling 'react/no-unstable-nested-components' rule
  .eslintrc.js
  packages/desktop-client/src/components/filters/SavedFilters.js
  packages/desktop-client/src/components/reports/graphs/NetWorthGraph.tsx
  packages/desktop-client/src/components/transactions/MobileTransaction.js
  upcoming-release-notes/1893.md
Labels: ✅ Approved

#1895 add budget tables to the aql schema
  packages/loot-core/src/server/aql/schema/index.ts
  upcoming-release-notes/1895.md
Labels: ✅ Approved

#1897 [Maintenance] Convert ExpenseGroup, ExpenseCategory, IncomeCategory components to Typescript.
  packages/desktop-client/src/components/budget/ExpenseCategory.tsx
  packages/desktop-client/src/components/budget/ExpenseGroup.tsx
  packages/desktop-client/src/components/budget/IncomeCategory.tsx
  packages/desktop-client/src/components/budget/RenderMonths.tsx
  packages/desktop-client/src/components/budget/SidebarCategory.tsx
  packages/desktop-client/src/components/budget/SidebarGroup.tsx
  packages/desktop-client/src/components/sidebar/Account.tsx
  packages/desktop-client/src/components/sort.tsx
  upcoming-release-notes/1897.md
Labels: ✅ Approved

#1876 Support ofx INVSTMTMSGSRSV1
  packages/desktop-client/src/components/modals/ImportTransactions.js
  packages/loot-core/src/server/accounts/ofx2json.ts
  upcoming-release-notes/1876.md
Labels: ✅ Approved

#1739 Sankey with Recharts
  packages/desktop-client/src/components/reports/Overview.js
  packages/desktop-client/src/components/reports/ReportRouter.js
  packages/desktop-client/src/components/reports/Sankey.js
  packages/desktop-client/src/components/reports/graphs/SankeyGraph.tsx
  packages/desktop-client/src/components/reports/graphs/sankey-spreadsheet.tsx
  packages/desktop-client/src/components/settings/Experimental.tsx
  packages/desktop-client/src/hooks/useFeatureFlag.ts
  packages/loot-core/src/types/prefs.d.ts
  upcoming-release-notes/1739.md
Labels: 🔍 Ready for Review

#1758 Swipe up mobile navbar
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-checks-that-settings-page-can-be-opened-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-checks-that-settings-page-can-be-opened-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-checks-that-settings-page-can-be-opened-3-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-checks-that-settings-page-can-be-opened-4-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-loads-the-budget-page-with-budgeted-amounts-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-loads-the-budget-page-with-budgeted-amounts-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-the-accounts-page-and-asserts-on-balances-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-the-accounts-page-and-asserts-on-balances-2-chromium-linux.png
  packages/desktop-client/e2e/page-models/mobile-navigation.js
  packages/desktop-client/package.json
  packages/desktop-client/src/components/ScrollProvider.tsx
  packages/desktop-client/src/components/mobile/MobileNavTabs.tsx
  upcoming-release-notes/1758.md
  yarn.lock
Labels: 🔍 Ready for Review

#1902 :arrow_up: (yarn) upgrade to v4 and better-sqlite3 to v9.1.1
  .github/workflows/electron.yml
  .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
  .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
  .yarn/releases/yarn-3.5.1.cjs
  .yarn/releases/yarn-4.0.1.cjs
  .yarnrc.yml
  package.json
  packages/api/package.json
  packages/loot-core/package.json
  upcoming-release-notes/1902.md
  yarn.lock
Labels: 🔍 Ready for Review

#1868 Color Consolidations
  packages/desktop-client/e2e/budget.test.js-snapshots/Budget-renders-the-summary-information-available-funds-overspent-budgeted-and-for-next-month-2-chromium-linux.png
  packages/desktop-client/e2e/budget.test.js-snapshots/Budget-transfer-funds-to-another-category-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-checks-that-settings-page-can-be-opened-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-6-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-7-chromium-linux.png
  packages/desktop-client/e2e/settings.test.js-snapshots/Settings-checks-the-page-visuals-1-chromium-linux.png
  packages/desktop-client/src/components/NotesButton.tsx
  packages/desktop-client/src/components/accounts/Balance.js
  packages/desktop-client/src/components/accounts/Header.js
  packages/desktop-client/src/components/alerts.tsx
  packages/desktop-client/src/components/budget/MonthCountSelector.tsx
  packages/desktop-client/src/components/budget/rollover/BudgetSummary.tsx
  packages/desktop-client/src/components/filters/FiltersMenu.js
  packages/desktop-client/src/components/forms.tsx
  packages/desktop-client/src/components/manager/Import.js
  packages/desktop-client/src/components/modals/EditField.js
  packages/desktop-client/src/components/modals/EditRule.js
  packages/desktop-client/src/components/modals/GoCardlessExternalMsg.js
  packages/desktop-client/src/components/rules/ActionExpression.tsx
  packages/desktop-client/src/components/rules/ConditionExpression.tsx
  packages/desktop-client/src/components/select/DateSelect.tsx
  packages/desktop-client/src/components/settings/UI.tsx
  packages/desktop-client/src/components/table.tsx
  packages/desktop-client/src/components/transactions/MobileTransaction.js
  packages/desktop-client/src/style/themes/dark.ts
  packages/desktop-client/src/style/themes/development.ts
  packages/desktop-client/src/style/themes/light.ts
  upcoming-release-notes/1868.md
Labels: ✅ Approved

#1909 Add typings condition operators for Action class
  packages/loot-core/src/server/accounts/rules.test.ts
  packages/loot-core/src/server/accounts/rules.ts
  upcoming-release-notes/1909.md
Labels: 🔍 Ready for Review, ✅ Approved

#1887 sideBar Dark Color changes
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-creates-a-new-account-and-views-the-initial-balance-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/budget.test.js-snapshots/Budget-renders-the-summary-information-available-funds-overspent-budgeted-and-for-next-month-2-chromium-linux.png
  packages/desktop-client/e2e/budget.test.js-snapshots/Budget-transfer-funds-to-another-category-2-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-and-cash-flow-reports-2-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-checks-the-page-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-4-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-checks-the-page-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-2-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-4-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-6-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-8-chromium-linux.png
  packages/desktop-client/e2e/settings.test.js-snapshots/Settings-checks-the-page-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-checks-the-page-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-split-test-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-test-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-category-6-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-date-6-chromium-linux.png
  packages/desktop-client/src/components/Page.tsx
  packages/desktop-client/src/components/sidebar/Account.tsx
  packages/desktop-client/src/style/themes/dark.ts
  packages/desktop-client/src/style/themes/development.ts
  packages/desktop-client/src/style/themes/light.ts
  upcoming-release-notes/1887.md
Labels: ✅ Approved

#1874 Mobile pages standardized (Colors/UI)
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-checks-that-settings-page-can-be-opened-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-checks-that-settings-page-can-be-opened-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-checks-that-settings-page-can-be-opened-3-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-checks-that-settings-page-can-be-opened-4-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-from-accounts-id-page-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-from-accounts-id-page-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-3-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-4-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-5-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-6-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-loads-the-budget-page-with-budgeted-amounts-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-loads-the-budget-page-with-budgeted-amounts-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-3-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-4-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-5-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-6-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-the-accounts-page-and-asserts-on-balances-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-the-accounts-page-and-asserts-on-balances-2-chromium-linux.png
  packages/desktop-client/src/components/AnimatedRefresh.tsx
  packages/desktop-client/src/components/Titlebar.tsx
  packages/desktop-client/src/components/accounts/MobileAccount.js
  packages/desktop-client/src/components/accounts/MobileAccountDetails.js
  packages/desktop-client/src/components/accounts/MobileAccounts.js
  packages/desktop-client/src/components/budget/MobileBudget.js
  packages/desktop-client/src/components/budget/MobileBudgetTable.js
  packages/desktop-client/src/components/mobile/MobileAmountInput.js
  packages/desktop-client/src/components/mobile/MobileForms.js
  packages/desktop-client/src/components/settings/index.tsx
  packages/desktop-client/src/components/transactions/MobileTransaction.js
  packages/desktop-client/src/style/themes/dark.ts
  packages/desktop-client/src/style/themes/light.ts
  upcoming-release-notes/1874.md
Labels: 🔍 Ready for Review

#1911 Duplicate color removal
  packages/desktop-client/src/style/themes/dark.ts
  packages/desktop-client/src/style/themes/light.ts
  upcoming-release-notes/1911.md
Labels: ✅ Approved

#1917 [Bugfix] Goals: Fix Schedule Infinite loop
  packages/loot-core/src/server/budget/goals/goalsSchedule.ts
  packages/loot-core/src/shared/months.ts
  upcoming-release-notes/1917.md
Labels: ✅ Approved

#1923 [Maintenance] Update CloseAccount, AccountAutocomplete, SavedFilterAutocomplete, PayeeAutocomplete components to Typescript.
  packages/desktop-client/src/components/autocomplete/AccountAutocomplete.tsx
  packages/desktop-client/src/components/autocomplete/Autocomplete.tsx
  packages/desktop-client/src/components/autocomplete/CategoryAutocomplete.tsx
  packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.tsx
  packages/desktop-client/src/components/autocomplete/SavedFilterAutocomplete.tsx
  packages/desktop-client/src/components/common/Button.tsx
  packages/desktop-client/src/components/modals/CloseAccount.tsx
  packages/loot-core/src/client/actions/queries.ts
  upcoming-release-notes/1923.md
Labels: ✅ Approved

#1853 Mobile create account
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-checks-that-settings-page-can-be-opened-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-checks-that-settings-page-can-be-opened-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-checks-that-settings-page-can-be-opened-3-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-checks-that-settings-page-can-be-opened-4-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-the-accounts-page-and-asserts-on-balances-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-the-accounts-page-and-asserts-on-balances-2-chromium-linux.png
  packages/desktop-client/src/components/Page.tsx
  packages/desktop-client/src/components/accounts/MobileAccountDetails.js
  packages/desktop-client/src/components/accounts/MobileAccounts.js
  packages/desktop-client/src/components/modals/CreateLocalAccount.tsx
  packages/desktop-client/src/components/transactions/MobileTransaction.js
  upcoming-release-notes/1853.md
Labels: ✅ Approved

#1880 Mobile report budget
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/accounts/MobileAccountDetails.js
  packages/desktop-client/src/components/budget/BudgetSummaries.tsx
  packages/desktop-client/src/components/budget/MobileBudget.js
  packages/desktop-client/src/components/budget/MobileBudgetTable.js
  packages/desktop-client/src/components/budget/index.tsx
  packages/desktop-client/src/components/budget/report/BalanceTooltip.tsx
  packages/desktop-client/src/components/budget/report/BudgetSummary.tsx
  packages/desktop-client/src/components/budget/report/ReportComponents.tsx
  packages/desktop-client/src/components/budget/report/budgetsummary/BudgetSummary.tsx
  packages/desktop-client/src/components/budget/report/budgetsummary/BudgetTotal.tsx
  packages/desktop-client/src/components/budget/report/budgetsummary/ExpenseProgress.tsx
  packages/desktop-client/src/components/budget/report/budgetsummary/ExpenseTotal.tsx
  packages/desktop-client/src/components/budget/report/budgetsummary/IncomeProgress.tsx
  packages/desktop-client/src/components/budget/report/budgetsummary/IncomeTotal.tsx
  packages/desktop-client/src/components/budget/report/budgetsummary/PieProgress.tsx
  packages/desktop-client/src/components/budget/report/budgetsummary/Saved.tsx
  packages/desktop-client/src/components/budget/report/budgetsummary/fraction.ts
  packages/desktop-client/src/components/budget/rollover/BudgetSummary.tsx
  packages/desktop-client/src/components/budget/rollover/HoldTooltip.tsx
  packages/desktop-client/src/components/budget/rollover/RolloverComponents.tsx
  packages/desktop-client/src/components/budget/rollover/TransferTooltip.tsx
  packages/desktop-client/src/components/budget/rollover/budgetsummary/BudgetSummary.tsx
  packages/desktop-client/src/components/budget/rollover/budgetsummary/ToBudget.tsx
  packages/desktop-client/src/components/budget/rollover/budgetsummary/TotalsList.tsx
  packages/desktop-client/src/components/budget/util.ts
  packages/desktop-client/src/components/common/HoverTarget.tsx
  packages/desktop-client/src/components/modals/BudgetSummary.tsx
  packages/desktop-client/src/components/modals/ReportBudgetSummary.tsx
  packages/desktop-client/src/components/modals/RolloverBudgetSummary.tsx
  packages/desktop-client/src/components/modals/SwitchBudgetType.tsx
  packages/desktop-client/src/components/spreadsheet/NamespaceContext.ts
  packages/loot-core/src/client/state-types/modals.d.ts
  upcoming-release-notes/1880.md
Labels: ✅ Approved

#1833 Don't allow duplicate category names (per group)
  packages/desktop-client/src/components/budget/index.tsx
  packages/loot-core/src/server/db/index.ts
  upcoming-release-notes/1833.md
Labels: ✅ Approved

#1926 Fix Electron Build
  packages/desktop-client/src/browser-preload.browser.js
  packages/desktop-client/src/global-events.js
  packages/desktop-electron/index.js
  packages/desktop-electron/preload.js
  upcoming-release-notes/1926.md
Labels: ✅ Approved

#1936 [Maintenance] Refactor amount input to typescript
  packages/desktop-client/src/components/common/InputWithContent.tsx
  packages/desktop-client/src/components/util/AmountInput.tsx
  upcoming-release-notes/1936.md
Labels: ✅ Approved

#1934 Specify minimum node version for @actual-app/api nom package
  packages/api/package.json
  upcoming-release-notes/1934.md
Labels: ✅ Approved

#1938 Switch from en-ZA to en-SE for space-comma NumberFormat
  packages/loot-core/src/shared/util.ts
  upcoming-release-notes/1938.md
Labels: ✅ Approved

#1916 [regression] Remove extra padding in mobile accounts page
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-the-accounts-page-and-asserts-on-balances-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-the-accounts-page-and-asserts-on-balances-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-split-test-transaction-1-chromium-linux.png
  packages/desktop-client/src/components/accounts/MobileAccounts.js
  upcoming-release-notes/1916.md
Labels: ✅ Approved

#1921 Support multiple months in experimental ofx parser
  packages/loot-core/src/server/accounts/ofx2json.ts
  upcoming-release-notes/1921.md
Labels: ✅ Approved

#1929 Fix flickering scroll bar on mobile transaction input (#1782)
  packages/desktop-client/src/components/mobile/MobileAmountInput.js
  upcoming-release-notes/1929.md
Labels: ✅ Approved

#1885 Fix crash when undoing a rule application
  packages/desktop-client/src/components/ManageRules.tsx
  packages/desktop-client/src/components/Modals.tsx
  upcoming-release-notes/1885.md
Labels: ✅ Approved

#1949 :wrench: (eslint) disallow using 'var': no-var rule
  .eslintrc.js
  packages/desktop-client/src/browser-preload.browser.js
  packages/desktop-electron/afterSignHook.js
  packages/desktop-electron/security.js
  packages/node-libofx/index.js
  upcoming-release-notes/1949.md
Labels: ✅ Approved

#1948 [Maintenance] Refactor payee table to typescript
  packages/desktop-client/src/components/payees/ManagePayees.js
  packages/desktop-client/src/components/payees/PayeeMenu.tsx
  packages/desktop-client/src/components/payees/PayeeTable.tsx
  packages/desktop-client/src/components/payees/PayeeTableRow.tsx
  packages/desktop-client/src/components/table.tsx
  upcoming-release-notes/1948.md
Labels: ✅ Approved

#1951 Consistent button size in budget title bar + use zondicon eye icon
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-1-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-2-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-3-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-4-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-creates-a-new-account-and-views-the-initial-balance-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-creates-a-new-account-and-views-the-initial-balance-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/budget.test.js-snapshots/Budget-renders-the-summary-information-available-funds-overspent-budgeted-and-for-next-month-1-chromium-linux.png
  packages/desktop-client/e2e/budget.test.js-snapshots/Budget-renders-the-summary-information-available-funds-overspent-budgeted-and-for-next-month-2-chromium-linux.png
  packages/desktop-client/e2e/budget.test.js-snapshots/Budget-transfer-funds-to-another-category-1-chromium-linux.png
  packages/desktop-client/e2e/budget.test.js-snapshots/Budget-transfer-funds-to-another-category-2-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-cash-flow-graph-and-checks-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-cash-flow-graph-and-checks-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-and-cash-flow-reports-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-and-cash-flow-reports-2-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-graph-and-checks-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-graph-and-checks-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-checks-the-page-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-checks-the-page-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-3-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-4-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-checks-the-page-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-checks-the-page-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-1-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-2-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-3-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-4-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-5-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-6-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-7-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-8-chromium-linux.png
  packages/desktop-client/e2e/settings.test.js-snapshots/Settings-checks-the-page-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/settings.test.js-snapshots/Settings-checks-the-page-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-checks-the-page-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-checks-the-page-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-split-test-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-split-test-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-test-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-test-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-category-5-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-category-6-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-date-5-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-date-6-chromium-linux.png
  packages/desktop-client/src/components/ThemeSelector.tsx
  packages/desktop-client/src/components/Titlebar.tsx
  packages/desktop-client/src/components/reports/CategorySelector.tsx
  packages/desktop-client/src/icons/v0/index.ts
  packages/desktop-client/src/icons/v2/Eye.tsx
  packages/desktop-client/src/icons/v2/EyeSlashed.tsx
  packages/desktop-client/src/icons/v2/ViewHide.tsx
  packages/desktop-client/src/icons/v2/ViewShow.tsx
  packages/desktop-client/src/icons/v2/eye-slashed.svg
  packages/desktop-client/src/icons/v2/eye.svg
  packages/desktop-client/src/icons/v2/index.ts
  packages/desktop-client/src/icons/v2/view-hide.svg
  packages/desktop-client/src/icons/v2/view-show.svg
  upcoming-release-notes/1951.md
Labels: ✅ Approved

#1956 [Maintenance] ESLint - prefer-const
  .eslintrc.js
  packages/api/app/query.js
  packages/crdt/src/crdt/merkle.test.ts
  packages/crdt/src/crdt/merkle.ts
  packages/crdt/src/crdt/timestamp.test.ts
  packages/crdt/src/crdt/timestamp.ts
  packages/desktop-client/src/browser-preload.browser.js
  packages/desktop-client/src/browser-server.js
  packages/desktop-client/src/global-events.js
  packages/desktop-client/src/gocardless.js
  packages/desktop-client/src/hooks/useLatestVersion.ts
  packages/desktop-client/src/hooks/useNavigate.ts
  packages/desktop-client/src/hooks/useProperFocus.tsx
  packages/desktop-client/src/hooks/useResizeObserver.ts
  packages/desktop-client/src/hooks/useSelected.tsx
  packages/desktop-client/src/icons/Loading.tsx
  packages/desktop-client/src/plaid.js
  packages/desktop-client/src/style/styles.ts
  packages/desktop-client/src/style/theme.tsx
  packages/desktop-client/src/util/router-tools.tsx
  packages/desktop-client/src/util/versions.ts
  packages/desktop-electron/afterSignHook.js
  packages/desktop-electron/index.js
  packages/desktop-electron/menu.js
  packages/desktop-electron/preload.js
  packages/desktop-electron/security.js
  packages/desktop-electron/server.js
  packages/desktop-electron/updater.js
  packages/desktop-electron/window-state.js
  upcoming-release-notes/1956.md
Labels: ✅ Approved

#1942 :recycle: (typescript) refactor global-events to TS
  packages/desktop-client/src/global-events.ts
  packages/desktop-client/src/index.tsx
  packages/loot-core/src/client/actions/budgets.ts
  packages/loot-core/src/platform/client/undo/index.d.ts
  packages/loot-core/src/types/server-events.d.ts
  upcoming-release-notes/1942.md
Labels: 🔍 Ready for Review

#1941 :recycle: (typescript) ported gocardless auth file to TS
  packages/desktop-client/src/components/modals/CreateAccount.tsx
  packages/desktop-client/src/gocardless.ts
  packages/desktop-client/src/hooks/useSyncServerStatus.ts
  packages/loot-core/src/client/state-types/modals.d.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/types/models/gocardless.d.ts
  packages/loot-core/src/types/models/index.d.ts
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/1941.md
Labels: ✅ Approved

#1789 Lock transactions after reconcilliation
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/accounts/Account.js
  packages/desktop-client/src/components/mobile/MobileForms.js
  packages/desktop-client/src/components/modals/ConfirmTransactionEdit.tsx
  packages/desktop-client/src/components/schedules/StatusBadge.tsx
  packages/desktop-client/src/components/transactions/MobileTransaction.js
  packages/desktop-client/src/components/transactions/TransactionList.js
  packages/desktop-client/src/components/transactions/TransactionsTable.js
  packages/desktop-client/src/icons/v2/LockClosed.tsx
  packages/desktop-client/src/icons/v2/index.ts
  packages/desktop-client/src/icons/v2/lock-closed.svg
  packages/loot-core/migrations/1697046240000_add_reconciled.sql
  packages/loot-core/src/server/__snapshots__/main.test.ts.snap
  packages/loot-core/src/server/accounts/__snapshots__/parse-file.test.ts.snap
  packages/loot-core/src/server/accounts/__snapshots__/sync.test.ts.snap
  packages/loot-core/src/server/accounts/__snapshots__/transfer.test.ts.snap
  packages/loot-core/src/server/aql/schema/index.ts
  packages/loot-core/src/types/models/transaction.d.ts
  upcoming-release-notes/1789.md
Labels: ✅ Approved

#1958 Part 2 of eslint prefer-const
  .eslintrc.js
  packages/loot-core/init-node.js
  packages/loot-core/src/client/SpreadsheetProvider.tsx
  packages/loot-core/src/client/actions/account.ts
  packages/loot-core/src/client/actions/budgets.ts
  packages/loot-core/src/client/actions/modals.ts
  packages/loot-core/src/client/actions/prefs.ts
  packages/loot-core/src/client/actions/queries.ts
  packages/loot-core/src/client/actions/sync.ts
  packages/loot-core/src/client/data-hooks/filters.tsx
  packages/loot-core/src/client/data-hooks/schedules.tsx
  packages/loot-core/src/client/queries.ts
  packages/loot-core/src/client/query-helpers.test.ts
  packages/loot-core/src/client/query-helpers.ts
  packages/loot-core/src/client/query-hooks.tsx
  packages/loot-core/src/client/reducers/account.ts
  packages/loot-core/src/client/reducers/budgets.ts
  packages/loot-core/src/client/reducers/queries.ts
  packages/loot-core/src/client/shared-listeners.ts
  packages/loot-core/src/client/update-notification.ts
  packages/loot-core/src/mocks/arbitrary-schema.ts
  packages/loot-core/src/mocks/budget.ts
  packages/loot-core/src/mocks/redux.tsx
  packages/loot-core/src/mocks/setup.ts
  packages/loot-core/src/mocks/spreadsheet.ts
  packages/loot-core/src/mocks/util.ts
  packages/loot-core/src/platform/client/fetch/__mocks__/index.web.ts
  packages/loot-core/src/platform/client/fetch/index.browser.ts
  packages/loot-core/src/platform/client/fetch/index.web.ts
  packages/loot-core/src/platform/client/undo/index.web.ts
  packages/loot-core/src/platform/server/asyncStorage/index.electron.ts
  packages/loot-core/src/platform/server/asyncStorage/index.web.ts
  packages/loot-core/src/platform/server/connection/index.electron.ts
  packages/loot-core/src/platform/server/connection/index.web.ts
  packages/loot-core/src/platform/server/fs/index.electron.ts
  packages/loot-core/src/platform/server/fs/index.web.test.ts
  packages/loot-core/src/platform/server/fs/index.web.ts
  packages/loot-core/src/platform/server/fs/path-join.web.ts
  packages/loot-core/src/platform/server/indexeddb/index.web.ts
  packages/loot-core/src/platform/server/sqlite/index.electron.ts
  packages/loot-core/src/platform/server/sqlite/index.web.test.ts
  packages/loot-core/src/platform/server/sqlite/index.web.ts
  packages/loot-core/src/shared/arithmetic.ts
  packages/loot-core/src/shared/async.test.ts
  packages/loot-core/src/shared/async.ts
  packages/loot-core/src/shared/categories.ts
  packages/loot-core/src/shared/errors.ts
  packages/loot-core/src/shared/months.ts
  packages/loot-core/src/shared/query.ts
  packages/loot-core/src/shared/rules.ts
  packages/loot-core/src/shared/schedules.ts
  packages/loot-core/src/shared/test-helpers.ts
  packages/loot-core/src/shared/transactions.test.ts
  packages/loot-core/src/shared/transactions.ts
  packages/loot-core/src/shared/util.ts
  packages/loot-core/webpack/webpack.api.config.js
  packages/loot-core/webpack/webpack.browser.config.js
  packages/loot-core/webpack/webpack.desktop.config.js
  upcoming-release-notes/1958.md
Labels: ✅ Approved

#1959 :wrench: (eslint) enable object-shorthand:properties rule
  .eslintrc.js
  packages/crdt/src/crdt/timestamp.ts
  packages/desktop-client/src/browser-preload.browser.js
  packages/desktop-client/src/components/FixedSizeList.js
  packages/desktop-client/src/components/accounts/Account.js
  packages/desktop-client/src/components/autocomplete/CategoryAutocomplete.tsx
  packages/desktop-client/src/components/budget/MobileBudget.js
  packages/desktop-client/src/components/budget/MobileBudgetTable.js
  packages/desktop-client/src/components/common/Select.tsx
  packages/desktop-client/src/components/filters/FiltersMenu.js
  packages/desktop-client/src/components/filters/SavedFilters.js
  packages/desktop-client/src/components/reports/spreadsheets/default-spreadsheet.tsx
  packages/desktop-client/src/components/schedules/EditSchedule.js
  packages/desktop-client/src/components/select/RecurringSchedulePicker.js
  packages/desktop-client/src/components/sidebar/Account.tsx
  packages/desktop-client/src/components/table.tsx
  packages/desktop-client/src/components/transactions/MobileTransaction.js
  packages/desktop-client/src/components/transactions/TransactionsTable.js
  packages/desktop-client/src/components/transactions/TransactionsTable.test.js
  packages/desktop-electron/afterSignHook.js
  packages/desktop-electron/index.js
  packages/loot-core/src/client/actions/account.ts
  packages/loot-core/src/mocks/index.ts
  packages/loot-core/src/mocks/plaid.ts
  packages/loot-core/src/server/accounts/ofx2json.ts
  packages/loot-core/src/server/accounts/sync.ts
  packages/loot-core/src/server/aql/compiler.ts
  packages/loot-core/src/server/budget/actions.ts
  packages/loot-core/src/server/budget/goals/goalsRemainder.ts
  packages/loot-core/src/server/budget/goals/goalsSchedule.ts
  packages/loot-core/src/server/budget/goaltemplates.ts
  packages/loot-core/src/server/db/index.ts
  packages/loot-core/src/server/importers/ynab4.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/server/spreadsheet/spreadsheet.ts
  packages/loot-core/src/server/sync/encoder.ts
  packages/loot-core/src/server/sync/migrate.test.ts
  packages/loot-core/src/server/sync/repair.ts
  upcoming-release-notes/1959.md
Labels: ✅ Approved

#1944 Create category rules for ynab imports
  packages/api/methods.js
  packages/loot-core/src/server/accounts/sync.ts
  packages/loot-core/src/server/accounts/transactions.ts
  packages/loot-core/src/server/api.ts
  packages/loot-core/src/server/importers/ynab4.ts
  packages/loot-core/src/server/importers/ynab5.ts
  upcoming-release-notes/1944.md
Labels: ✅ Approved

#1960 :wrench: (vrt) make screenshot comparisons more strict
  packages/desktop-client/playwright.config.js
  upcoming-release-notes/1960.md
Labels: ✅ Approved

#1962 [Bugfix] Fixed modal error and transactions now unlock when moved across accounts.
  packages/desktop-client/src/components/accounts/Account.js
  packages/desktop-client/src/components/modals/ConfirmTransactionEdit.tsx
  packages/desktop-client/src/components/transactions/TransactionsTable.js
  upcoming-release-notes/1962.md
Labels: 🔍 Ready for Review

#1955 Transfer and Off Budget category in mobile
  packages/desktop-client/src/components/transactions/MobileTransaction.js
  upcoming-release-notes/1955.md
Labels: ✅ Approved

#1970 :art: (fix) gocardless success button color
  packages/desktop-client/src/components/modals/GoCardlessExternalMsg.js
  packages/desktop-client/src/components/modals/PlaidExternalMsg.tsx
  upcoming-release-notes/1970.md
Labels: ✅ Approved

#1946 [refactor] Migrate Discover schedules to tsx
  packages/desktop-client/src/components/schedules/DiscoverSchedules.tsx
  packages/desktop-client/src/components/table.tsx
  packages/desktop-client/src/hooks/useSelected.tsx
  packages/desktop-client/src/hooks/useSendPlatformRequest.ts
  packages/loot-core/src/client/reducers/budgets.ts
  packages/loot-core/src/server/schedules/find-schedules.ts
  packages/loot-core/src/server/schedules/types/handlers.ts
  packages/loot-core/src/types/models/schedule.d.ts
  upcoming-release-notes/1946.md
Labels: ✅ Approved

#1976 Fix bug in rule transaction apply preventing amount overrides
  packages/desktop-client/src/components/modals/EditRule.js
  upcoming-release-notes/1976.md
Labels: ✅ Approved

#1975 Fix cancel add category group
  packages/desktop-client/src/components/budget/SidebarGroup.tsx
  upcoming-release-notes/1975.md
Labels: ✅ Approved

#1972 [Maintenance] Update ConfirmCategoryDelete, GoCardlessExternalMsg, ManageRulesModal to tsx
  packages/desktop-client/src/components/modals/ConfirmCategoryDelete.tsx
  packages/desktop-client/src/components/modals/GoCardlessExternalMsg.tsx
  packages/desktop-client/src/components/modals/ManageRulesModal.tsx
  packages/loot-core/src/types/models/gocardless.d.ts
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/1972.md
Labels: ✅ Approved

#1930 Custom Reports Bug Fixes
  packages/desktop-client/src/components/filters/CompactFiltersButton.tsx
  packages/desktop-client/src/components/filters/FiltersButton.tsx
  packages/desktop-client/src/components/filters/FiltersMenu.js
  packages/desktop-client/src/components/reports/CategorySelector.tsx
  packages/desktop-client/src/components/reports/GraphButton.tsx
  packages/desktop-client/src/components/reports/Header.js
  packages/desktop-client/src/components/reports/LoadingIndicator.tsx
  packages/desktop-client/src/components/reports/Overview.js
  packages/desktop-client/src/components/reports/ReportOptions.tsx
  packages/desktop-client/src/components/reports/ReportSidebar.js
  packages/desktop-client/src/components/reports/ReportTableHeader.tsx
  packages/desktop-client/src/components/reports/ReportTableList.tsx
  packages/desktop-client/src/components/reports/ReportTableTotals.tsx
  packages/desktop-client/src/components/reports/ReportTopbar.js
  packages/desktop-client/src/components/reports/getCustomTick.ts
  packages/desktop-client/src/components/reports/graphs/AreaGraph.tsx
  packages/desktop-client/src/components/reports/graphs/BarGraph.tsx
  packages/desktop-client/src/components/reports/graphs/StackedBarGraph.tsx
  packages/desktop-client/src/components/reports/reports/CashFlowCard.js
  packages/desktop-client/src/components/reports/reports/CategorySpendingCard.js
  packages/desktop-client/src/components/reports/reports/CustomReport.js
  packages/desktop-client/src/components/reports/reports/CustomReportCard.js
  packages/desktop-client/src/components/reports/reports/NetWorthCard.js
  packages/desktop-client/src/components/reports/reports/SankeyCard.js
  packages/desktop-client/src/components/reports/spreadsheets/default-spreadsheet.tsx
  packages/desktop-client/src/components/reports/util.js
  packages/desktop-client/src/icons/v2/CheckAll.tsx
  packages/desktop-client/src/icons/v2/UncheckAll.tsx
  packages/desktop-client/src/icons/v2/check-all.svg
  packages/desktop-client/src/icons/v2/index.ts
  packages/desktop-client/src/icons/v2/uncheck-all.svg
  packages/desktop-client/src/style/themes/dark.ts
  packages/loot-core/src/shared/months.ts
  upcoming-release-notes/1930.md
Labels: ✅ Approved

#1984 [Bugfix] Goals: Schedule overbudget condition
  packages/loot-core/src/server/budget/goals/goalsSchedule.ts
  packages/loot-core/src/server/budget/goaltemplates.ts
  upcoming-release-notes/1984.md
Labels: ✅ Approved

#1980 Validates minimum node version to 18.12.0 for @actual-app/api npm package
  packages/api/index.js
  packages/api/package.json
  packages/api/validateNodeVersion.js
  upcoming-release-notes/1980.md
  yarn.lock
Labels: ✅ Approved

#1987 Update rules API
  packages/loot-core/src/server/accounts/rules.ts
  packages/loot-core/src/types/models/rule.d.ts
  upcoming-release-notes/1987.md
Labels: ✅ Approved
