Repository actualbudget/actual, pull requests merged in 2023-06, with the labels that each got.

#1067 :bug: (budget) link from budget to transactions not working
  packages/desktop-client/src/components/budget/index.js
  upcoming-release-notes/1067.md
Labels: ✅ Approved

#1079 chore: remove `loot-design` reference from readme.md
  README.md
  upcoming-release-notes/1079.md
Labels: ✅ Approved

#1078 chore: migrate some JS to TS
  packages/desktop-client/src/hooks/useLatestVersion.ts
  packages/desktop-client/src/hooks/useResizeObserver.ts
  packages/desktop-client/src/hooks/useSyncServerStatus.ts
  packages/desktop-client/src/index.tsx
  packages/desktop-client/src/polyfills.ts
  packages/desktop-client/src/util.ts
  packages/desktop-client/src/util/versions.ts
  upcoming-release-notes/1078.md
Labels: ✅ Approved

#1083 fix parser bug where by goals couldn't repeat on months/years >9
  packages/loot-core/src/server/budget/goal-template.pegjs
  upcoming-release-notes/1083.md
Labels: ✅ Approved

#1084 Bug: Cleanup script
  packages/loot-core/src/server/budget/cleanup-template.ts
  upcoming-release-notes/1084.md
Labels: 🔍 Ready for Review

#1087 :bookmark: (23.6.0) category hiding and filters for reports
  .github/workflows/release-notes.yml
  packages/api/package.json
  packages/desktop-client/package.json
  upcoming-release-notes/1000.md
  upcoming-release-notes/1001.md
  upcoming-release-notes/1002.md
  upcoming-release-notes/1003.md
  upcoming-release-notes/1004.md
  upcoming-release-notes/1005.md
  upcoming-release-notes/1008.md
  upcoming-release-notes/1011.md
  upcoming-release-notes/1012.md
  upcoming-release-notes/1015.md
  upcoming-release-notes/1016.md
  upcoming-release-notes/1017.md
  upcoming-release-notes/1019.md
  upcoming-release-notes/1022.md
  upcoming-release-notes/1023.md
  upcoming-release-notes/1028.md
  upcoming-release-notes/1029.md
  upcoming-release-notes/1032.md
  upcoming-release-notes/1033.md
  upcoming-release-notes/1034.md
  upcoming-release-notes/1036.md
  upcoming-release-notes/1037.md
  upcoming-release-notes/1038.md
  upcoming-release-notes/1042.md
  upcoming-release-notes/1043.md
  upcoming-release-notes/1045.md
  upcoming-release-notes/1048.md
  upcoming-release-notes/1049.md
  upcoming-release-notes/1052.md
  upcoming-release-notes/1054.md
  upcoming-release-notes/1056.md
  upcoming-release-notes/1058.md
  upcoming-release-notes/1059.md
  upcoming-release-notes/1060.md
  upcoming-release-notes/1061.md
  upcoming-release-notes/1064.md
  upcoming-release-notes/1067.md
  upcoming-release-notes/1070.md
  upcoming-release-notes/1078.md
  upcoming-release-notes/1079.md
  upcoming-release-notes/1083.md
  upcoming-release-notes/1084.md
  upcoming-release-notes/964.md
  upcoming-release-notes/979.md
  upcoming-release-notes/994.md
  upcoming-release-notes/995.md
  upcoming-release-notes/999.md
Labels: ✅ Approved

#1075 Sync more often when using the API
  packages/api/index.js
  packages/api/methods.js
  packages/loot-core/src/server/api.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/types/main.handlers.d.ts
  upcoming-release-notes/1075.md
Labels: ✅ Approved

#1095 Goals: Cleanup script error
  packages/loot-core/src/server/budget/cleanup-template.ts
  upcoming-release-notes/1095.md
Labels: ✅ Approved

#1073 Add clear error to API when no budget is open
  packages/loot-core/src/server/api.ts
  upcoming-release-notes/1073.md
Labels: ✅ Approved

#1104 Disable “Reset sync” button when sync is disabled
  packages/desktop-client/src/components/settings/Reset.js
  packages/desktop-client/src/components/settings/index.js
  upcoming-release-notes/1104.md
Labels: ✅ Approved

#1105 Fix error in console when `hideFraction` pref is missing
  packages/desktop-client/src/components/settings/Format.js
  upcoming-release-notes/1105.md
Labels: ✅ Approved

#1106 :wrench: (cross-env) add missing dep and upgrade all to same version
  package.json
  packages/desktop-electron/package.json
  upcoming-release-notes/1106.md
  yarn.lock
Labels: ✅ Approved

#1099 More Electron fixes
  packages/desktop-electron/index.js
  packages/desktop-electron/menu.js
  packages/loot-core/src/platform/client/fetch/__mocks__/index.web.ts
  packages/loot-core/src/platform/client/fetch/index.browser.ts
  packages/loot-core/src/platform/client/fetch/index.d.ts
  packages/loot-core/src/platform/client/fetch/index.web.ts
  packages/loot-core/src/platform/server/connection/index.electron.ts
  upcoming-release-notes/1099.md
Labels: ✅ Approved

#1107 BUGFIX Unused Payees: Corrected an issue where the filter control was not being referenced
  packages/desktop-client/src/components/payees/index.js
  upcoming-release-notes/1107.md
Labels: ✅ Approved

#1101 Goals: Remainder option
  packages/loot-core/src/server/budget/goal-template.pegjs
  packages/loot-core/src/server/budget/goaltemplates.ts
  upcoming-release-notes/1101.md
Labels: ✅ Approved

#948 Remove account types
  packages/desktop-client/e2e/accounts.test.js
  packages/desktop-client/e2e/page-models/navigation.js
  packages/desktop-client/src/components/accounts/MobileAccounts.js
  packages/desktop-client/src/components/modals/ConfigureLinkedAccounts.js
  packages/desktop-client/src/components/modals/CreateLocalAccount.js
  packages/import-ynab4/importer.js
  packages/import-ynab5/importer.js
  packages/loot-core/migrations/1682265217543_remove_account_type.sql
  packages/loot-core/src/client/actions/queries.ts
  packages/loot-core/src/mocks/budget.ts
  packages/loot-core/src/mocks/index.ts
  packages/loot-core/src/server/accounts/link.ts
  packages/loot-core/src/server/api-models.ts
  packages/loot-core/src/server/api.ts
  packages/loot-core/src/server/aql/schema/index.ts
  packages/loot-core/src/server/db/index.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/server/models.ts
  packages/loot-core/src/shared/accounts.ts
  packages/loot-core/src/types/main.handlers.d.ts
  packages/loot-core/src/types/models/account.d.ts
  upcoming-release-notes/948.md
Labels: ✅ Approved

#1109 Fix migration ID for “remove account type” migration
  .github/actions/check-migrations.js
  .github/workflows/check.yml
  packages/loot-core/migrations/1686139660866_remove_account_type.sql
  upcoming-release-notes/1109.md
Labels: ✅ Approved

#1114 Stop mixing platform-specific code
  .eslintrc.js
  packages/api/index.js
  packages/desktop-client/src/components/budget/misc.js
  packages/desktop-client/src/components/sidebar.js
  packages/desktop-client/src/components/spreadsheet/SheetValue.tsx
  packages/desktop-client/src/components/spreadsheet/useSheetValue.js
  packages/desktop-electron/index.js
  packages/desktop-electron/server.js
  packages/desktop-electron/window-state.js
  packages/loot-core/init-node.js
  packages/loot-core/src/platform/client/fetch/index.testing.ts
  packages/loot-core/src/platform/server/fs/index.electron.ts
  packages/loot-core/src/platform/server/fs/index.web.ts
  packages/loot-core/src/platform/server/fs/path-join.electron.ts
  packages/loot-core/src/platform/server/fs/shared.ts
  packages/loot-core/src/platform/server/sqlite/index.web.test.ts
  packages/loot-core/src/server/migrate/migrations.ts
  packages/loot-core/src/types/api-handlers.d.ts
  packages/loot-core/src/types/handlers.d.ts
  packages/loot-core/src/types/main-handlers.d.ts
  upcoming-release-notes/1114.md
Labels: ✅ Approved

#1115 Update loot-core to webpack 5
  packages/loot-core/bin/build-browser
  packages/loot-core/package.json
  packages/loot-core/webpack/webpack.api.config.js
  packages/loot-core/webpack/webpack.browser.config.js
  upcoming-release-notes/1115.md
  yarn.lock
Labels: ✅ Approved

#1117 Update recommended version to Node.js 18
  .github/actions/setup/action.yml
  .nvmrc
  Dockerfile
  bin/docker-start
  package.json
  upcoming-release-notes/1117.md
Labels: ✅ Approved

#1108 Goals: Check template action
  packages/desktop-client/src/components/budget/rollover/BudgetSummary.tsx
  packages/loot-core/src/client/actions/queries.ts
  packages/loot-core/src/server/budget/app.ts
  packages/loot-core/src/server/budget/goaltemplates.ts
  packages/loot-core/src/server/budget/types/handlers.d.ts
  upcoming-release-notes/1108.md
Labels: ✅ Approved

#1118 Partition GitHub Actions cache based on Node version
  .github/actions/setup/action.yml
  upcoming-release-notes/1118.md
Labels: ✅ Approved

#984 Fix sync-related errors that show up in the console when not using a server
  packages/desktop-client/src/components/ServerContext.js
  packages/desktop-client/src/components/manager/subscribe/common.tsx
  packages/desktop-client/src/hooks/useFeatureFlag.ts
  packages/loot-core/src/server/accounts/sync.ts
  packages/loot-core/src/server/cloud-storage.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/types/main-handlers.d.ts
  upcoming-release-notes/984.md
Labels: ✅ Approved

#1127 :bug: (nordigen) perform status check only if server is online
  packages/desktop-client/src/hooks/useNordigenStatus.ts
  upcoming-release-notes/1127.md
Labels: ✅ Approved

#1133 :bug: (nordigen) expired bank-links
  packages/desktop-client/src/components/accounts/AccountSyncCheck.js
  packages/desktop-client/src/hooks/useNordigenStatus.ts
  upcoming-release-notes/1133.md
Labels: ✅ Approved

#1129 Update links to point to new domain
  README.md
  packages/api/README.md
  packages/desktop-client/src/components/FatalError.js
  packages/desktop-client/src/components/ManageRules.js
  packages/desktop-client/src/components/SidebarWithData.js
  packages/desktop-client/src/components/UpdateNotification.js
  packages/desktop-client/src/components/accounts/AccountSyncCheck.js
  packages/desktop-client/src/components/manager/ImportYNAB5.js
  packages/desktop-client/src/components/manager/ManagementApp.js
  packages/desktop-client/src/components/manager/WelcomeScreen.js
  packages/desktop-client/src/components/manager/subscribe/Bootstrap.tsx
  packages/desktop-client/src/components/modals/CreateAccount.js
  packages/desktop-client/src/components/modals/CreateEncryptionKey.js
  packages/desktop-client/src/components/modals/CreateLocalAccount.js
  packages/desktop-client/src/components/modals/FixEncryptionKey.js
  packages/desktop-client/src/components/schedules/EditSchedule.js
  packages/desktop-client/src/components/settings/Encryption.js
  packages/desktop-client/src/components/settings/index.js
  packages/desktop-client/src/components/tutorial/Final.js
  packages/desktop-client/src/components/tutorial/Intro.js
  packages/desktop-electron/menu.js
  packages/loot-core/src/client/shared-listeners.ts
  packages/loot-core/src/client/update-notification.ts
  packages/loot-core/src/platform/client/fetch/index.browser.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/shared/errors.ts
  packages/loot-core/src/shared/rules.ts
  upcoming-release-notes/1129.md
Labels: 🔍 Ready for Review

#1136 :bug: disable 'all payees' checkbox while schedules are loading
  packages/desktop-client/src/components/schedules/DiscoverSchedules.js
  packages/desktop-client/src/hooks/useSendPlatformRequest.ts
  upcoming-release-notes/1136.md
Labels: ✅ Approved

#1139 Remove 'export' keyword where not needed.
  packages/desktop-client/src/components/FixedSizeList.js
  packages/desktop-client/src/components/KeyHandlers.tsx
  packages/desktop-client/src/components/ManageRules.js
  packages/desktop-client/src/components/NotesButton.tsx
  packages/desktop-client/src/components/Titlebar.js
  packages/desktop-client/src/components/accounts/MobileAccounts.js
  packages/desktop-client/src/components/accounts/MobileTransaction.js
  packages/desktop-client/src/components/accounts/TransactionsTable.js
  packages/desktop-client/src/components/alerts.tsx
  packages/desktop-client/src/components/autocomplete/AccountAutocomplete.js
  packages/desktop-client/src/components/autocomplete/Autocomplete.tsx
  packages/desktop-client/src/components/autocomplete/CategorySelect.tsx
  packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.js
  packages/desktop-client/src/components/budget/BudgetMonthCountContext.js
  packages/desktop-client/src/components/budget/MobileBudgetTable.js
  packages/desktop-client/src/components/budget/misc.js
  packages/desktop-client/src/components/common.tsx
  packages/desktop-client/src/components/common/Text.tsx
  packages/desktop-client/src/components/modals/EditRule.js
  packages/desktop-client/src/components/modals/ImportTransactions.js
  packages/desktop-client/src/components/select/DateSelect.js
  packages/desktop-client/src/components/sort.js
  packages/desktop-client/src/components/table.tsx
  packages/desktop-client/src/hooks/useProperFocus.js
  packages/desktop-client/src/util/versions.ts
  upcoming-release-notes/1139.md
Labels: ✅ Approved

#1140 Strip a trailing slash off of server URLs
  packages/loot-core/src/server/main.ts
  upcoming-release-notes/1140.md
Labels: ✅ Approved

#1144 Revert “Make number parsing agnostic to decimal and thousands separators”
  packages/desktop-client/e2e/page-models/account-page.js
  packages/loot-core/src/mocks/number-formats.ts
  packages/loot-core/src/shared/arithmetic.test.ts
  packages/loot-core/src/shared/arithmetic.ts
  upcoming-release-notes/1144.md
Labels: ✅ Approved

#1145 Removing unused functions
  packages/desktop-client/src/components/common.tsx
  packages/desktop-client/src/components/manager/subscribe/common.tsx
  packages/desktop-client/src/components/reports/util.js
  packages/desktop-client/src/components/schedules/StatusBadge.js
  packages/desktop-client/src/hooks/index.js
  packages/desktop-client/src/style.tsx
  upcoming-release-notes/1145.md
Labels: ✅ Approved

#1146 Removing Tutorial code
  packages/desktop-client/src/components/accounts/Account.js
  packages/desktop-client/src/components/tutorial/AnimateIn.js
  packages/desktop-client/src/components/tutorial/BudgetCategories.js
  packages/desktop-client/src/components/tutorial/BudgetInitial.js
  packages/desktop-client/src/components/tutorial/BudgetNewIncome.js
  packages/desktop-client/src/components/tutorial/BudgetNextMonth.js
  packages/desktop-client/src/components/tutorial/BudgetSummary.js
  packages/desktop-client/src/components/tutorial/CategoryBalance.js
  packages/desktop-client/src/components/tutorial/DeleteTransactions.js
  packages/desktop-client/src/components/tutorial/Final.js
  packages/desktop-client/src/components/tutorial/Intro.js
  packages/desktop-client/src/components/tutorial/Navigation.js
  packages/desktop-client/src/components/tutorial/Overspending.js
  packages/desktop-client/src/components/tutorial/TransactionAdd.js
  packages/desktop-client/src/components/tutorial/TransactionEnter.js
  packages/desktop-client/src/components/tutorial/TransactionFinalize.js
  packages/desktop-client/src/components/tutorial/common.js
  packages/desktop-electron/index.js
  packages/desktop-electron/menu.js
  packages/loot-core/src/client/constants.ts
  packages/loot-core/src/client/reducers/index.ts
  packages/loot-core/src/client/reducers/tutorial.ts
  packages/loot-core/src/client/tutorial.ts
  packages/loot-core/src/types/main-handlers.d.ts
  upcoming-release-notes/1146.md
Labels: ✅ Approved

#1150 :recycle: (crdt) moved re-used utils in actual-server to separate package
  .github/workflows/build.yml
  .gitignore
  packages/crdt/.eslintignore
  packages/crdt/index.ts
  packages/crdt/jest.config.js
  packages/crdt/package.json
  packages/crdt/src/crdt/__snapshots__/merkle.test.ts.snap
  packages/crdt/src/crdt/index.ts
  packages/crdt/src/crdt/merkle.test.ts
  packages/crdt/src/crdt/merkle.ts
  packages/crdt/src/crdt/timestamp.test.ts
  packages/crdt/src/crdt/timestamp.ts
  packages/crdt/src/main.ts
  packages/crdt/src/proto/sync_pb.d.ts
  packages/crdt/src/proto/sync_pb.js
  packages/crdt/tsconfig.dist.json
  packages/loot-core/package.json
  packages/loot-core/src/mocks/setup.ts
  packages/loot-core/src/platform/uuid/index.testing.ts
  packages/loot-core/src/server/api.ts
  packages/loot-core/src/server/aql/schema/executors.test.ts
  packages/loot-core/src/server/db/index.ts
  packages/loot-core/src/server/main.test.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/server/prefs.ts
  packages/loot-core/src/server/sync/encoder.ts
  packages/loot-core/src/server/sync/index.ts
  packages/loot-core/src/server/sync/make-test-message.ts
  packages/loot-core/src/server/sync/migrate.ts
  packages/loot-core/src/server/sync/repair.ts
  packages/loot-core/src/server/sync/sync.property.test.ts
  packages/loot-core/src/server/sync/sync.test.ts
  packages/loot-core/src/server/tests/mockSyncServer.ts
  packages/loot-core/src/server/undo.ts
  upcoming-release-notes/1150.md
  yarn.lock
Labels: 🔍 Ready for Review

#1121 Improve error logging in the API
  packages/loot-core/src/server/api.ts
  packages/loot-core/src/server/cloud-storage.ts
  upcoming-release-notes/1121.md
Labels: ✅ Approved

#1135 :sparkles: (nordigen) release the feature
  packages/desktop-client/e2e/page-models/navigation.js
  packages/desktop-client/src/components/SidebarWithData.js
  packages/desktop-client/src/components/accounts/Account.js
  packages/desktop-client/src/components/modals/CreateAccount.js
  packages/desktop-client/src/components/settings/Experimental.js
  packages/desktop-client/src/hooks/useFeatureFlag.ts
  upcoming-release-notes/1135.md
Labels: ✅ Approved

#1143 Expand / collapse all categories
  packages/desktop-client/src/components/budget/misc.js
  upcoming-release-notes/1143.md
Labels: ✅ Approved

#1155 :bug: remove 'we have been notified' copy
  packages/desktop-client/src/components/manager/Import.js
  packages/desktop-client/src/components/manager/ImportActual.js
  packages/desktop-client/src/components/manager/ImportYNAB4.js
  packages/desktop-client/src/components/manager/ImportYNAB5.js
  packages/loot-core/src/client/actions/notifications.ts
  upcoming-release-notes/1155.md
Labels: ✅ Approved

#1147 Tidy up exports in loot-core
  packages/loot-core/src/client/data-hooks/accounts.tsx
  packages/loot-core/src/client/data-hooks/payees.tsx
  packages/loot-core/src/client/query-helpers.ts
  packages/loot-core/src/client/query-hooks.tsx
  packages/loot-core/src/client/reducers/budgets.ts
  packages/loot-core/src/server/accounts/rules.ts
  packages/loot-core/src/server/accounts/transaction-rules.ts
  packages/loot-core/src/server/aql/compiler.ts
  packages/loot-core/src/server/aql/schema/executors.ts
  packages/loot-core/src/server/backups.ts
  packages/loot-core/src/server/schedules/app.ts
  packages/loot-core/src/server/schedules/find-schedules.ts
  packages/loot-core/src/server/update.ts
  packages/loot-core/src/shared/transactions.ts
  upcoming-release-notes/1147.md
Labels: ✅ Approved

#1157 :fire: removing needs-triage github label
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/workflows/issues-add-triage-label.yml
  packages/loot-core/src/client/shared-listeners.ts
  upcoming-release-notes/1157.md
Labels: ✅ Approved

#1156 Remove upgrade notifications code
  packages/desktop-client/src/components/FinancesApp.js
  packages/loot-core/src/client/upgrade-notifications.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/server/prefs.ts
  packages/loot-core/src/types/main-handlers.d.ts
  upcoming-release-notes/1156.md
Labels: 🔍 Ready for Review

#1161 Log more details when migrations are out of sync
  packages/loot-core/src/server/migrate/migrations.ts
  upcoming-release-notes/1161.md
Labels: ✅ Approved

#1158 Deleting all unused files, deleting unused functions from loot-core
  packages/desktop-client/src/components/SyncNotifications.js
  packages/desktop-client/src/components/debug/index.js
  packages/desktop-client/src/util.ts
  packages/loot-core/src/server/api-models.ts
  packages/loot-core/src/server/aql/compiler.ts
  packages/loot-core/src/server/errors.ts
  packages/loot-core/src/server/perf.ts
  packages/loot-core/src/server/spreadsheet/globals.ts
  packages/loot-core/src/server/spreadsheet/new/REQUIREMENTS.txt
  packages/loot-core/src/server/spreadsheet/new/__snapshots__/compiler.test.ts.snap
  packages/loot-core/src/server/spreadsheet/new/__snapshots__/lexer.test.ts.snap
  packages/loot-core/src/server/spreadsheet/new/__snapshots__/vm.test.ts.snap
  packages/loot-core/src/server/spreadsheet/new/compiler.test.ts
  packages/loot-core/src/server/spreadsheet/new/compiler.ts
  packages/loot-core/src/server/spreadsheet/new/get-sql-fields.ts
  packages/loot-core/src/server/spreadsheet/new/lexer.test.ts
  packages/loot-core/src/server/spreadsheet/new/lexer.ts
  packages/loot-core/src/server/spreadsheet/new/nodes.ts
  packages/loot-core/src/server/spreadsheet/new/ops.ts
  packages/loot-core/src/server/spreadsheet/new/parser.ts
  packages/loot-core/src/server/spreadsheet/new/sqlconvert.ts
  packages/loot-core/src/server/spreadsheet/new/sqlgen.ts
  packages/loot-core/src/server/spreadsheet/new/vm.test.ts
  packages/loot-core/src/server/spreadsheet/new/vm.ts
  packages/loot-core/src/server/spreadsheet/sqlinterp.test.ts
  packages/loot-core/src/server/spreadsheet/util.ts
  packages/loot-core/src/shared/errors.ts
  packages/loot-core/src/shared/rules.ts
  packages/loot-core/src/shared/util.ts
  upcoming-release-notes/1158.md
Labels: ✅ Approved

#1066 react-router 6 upgrade
  packages/desktop-client/package.json
  packages/desktop-client/src/components/FinancesApp.js
  packages/desktop-client/src/components/FloatableSidebar.js
  packages/desktop-client/src/components/GlobalKeys.js
  packages/desktop-client/src/components/LoggedInUser.js
  packages/desktop-client/src/components/Modals.js
  packages/desktop-client/src/components/Page.js
  packages/desktop-client/src/components/SidebarWithData.js
  packages/desktop-client/src/components/Titlebar.js
  packages/desktop-client/src/components/accounts/Account.js
  packages/desktop-client/src/components/accounts/MobileAccount.js
  packages/desktop-client/src/components/accounts/MobileAccounts.js
  packages/desktop-client/src/components/accounts/TransactionList.js
  packages/desktop-client/src/components/budget/index.js
  packages/desktop-client/src/components/common.tsx
  packages/desktop-client/src/components/manager/ConfigServer.js
  packages/desktop-client/src/components/manager/ManagementApp.js
  packages/desktop-client/src/components/manager/Modals.js
  packages/desktop-client/src/components/manager/subscribe/ChangePassword.tsx
  packages/desktop-client/src/components/manager/subscribe/Error.tsx
  packages/desktop-client/src/components/manager/subscribe/common.tsx
  packages/desktop-client/src/components/modals/CreateLocalAccount.js
  packages/desktop-client/src/components/modals/EditRule.js
  packages/desktop-client/src/components/modals/MergeUnusedPayees.js
  packages/desktop-client/src/components/reports/Overview.js
  packages/desktop-client/src/components/reports/index.js
  packages/desktop-client/src/components/schedules/DiscoverSchedules.js
  packages/desktop-client/src/components/schedules/EditSchedule.js
  packages/desktop-client/src/components/schedules/LinkSchedule.js
  packages/desktop-client/src/components/schedules/PostsOfflineNotification.js
  packages/desktop-client/src/components/schedules/index.js
  packages/desktop-client/src/components/sidebar.js
  packages/desktop-client/src/global-events.js
  packages/desktop-client/src/util/location-state.js
  packages/desktop-client/src/util/router-tools.tsx
  packages/desktop-electron/menu.js
  packages/loot-core/src/client/actions/budgets.ts
  packages/loot-core/typings/window.d.ts
  upcoming-release-notes/1066.md
  yarn.lock
Labels: help wanted, ✅ Approved

#1174 Remove remaining tutorial code
  packages/loot-core/src/server/main.ts
  upcoming-release-notes/1174.md
Labels: ✅ Approved

#1178 React Router 6 fixes
  packages/desktop-client/src/components/accounts/Account.js
  packages/desktop-client/src/components/accounts/MobileAccount.js
  packages/desktop-client/src/components/budget/index.js
  packages/desktop-client/src/components/payees/index.js
  upcoming-release-notes/1178.md
Labels: ✅ Approved

#1173 New linter rule import/no-unused-modules & fixing import on typescript
  .eslintrc.js
  package.json
  packages/desktop-client/.eslintignore
  packages/desktop-client/src/components/accounts/MobileAccount.js
  packages/desktop-client/src/components/accounts/MobileTransaction.js
  packages/desktop-client/src/plaid.js
  packages/import-ynab4/.eslintignore
  packages/import-ynab5/.eslintignore
  packages/loot-core/src/platform/client/fetch/index.testing.ts
  packages/loot-core/src/platform/server/sqlite/index.web.test.ts
  packages/loot-core/src/server/accounts/payees.ts
  packages/loot-core/src/server/spreadsheet/sqlinterp.ts
  packages/loot-core/src/shared/environment.ts
  upcoming-release-notes/1173.md
  yarn.lock
Labels: ✅ Approved

#1176 Automatic category selection for new category transactions
  packages/desktop-client/src/components/accounts/Account.js
  packages/desktop-client/src/components/accounts/TransactionList.js
  packages/desktop-client/src/components/accounts/TransactionsTable.js
  upcoming-release-notes/1176.md
Labels: ✅ Approved

#1077 chore: enforce proper types in `sync/index`
  packages/crdt/src/crdt/timestamp.ts
  packages/loot-core/src/server/budget/actions.ts
  packages/loot-core/src/server/db/index.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/server/mutators.ts
  packages/loot-core/src/server/sync/encoder.ts
  packages/loot-core/src/server/sync/index.ts
  packages/loot-core/src/server/sync/migrate.test.ts
  packages/loot-core/src/server/sync/sync.property.test.ts
  packages/loot-core/src/server/sync/sync.test.ts
  packages/loot-core/src/server/sync/utils.ts
  packages/loot-core/src/shared/async.ts
  packages/loot-core/src/shared/util.ts
  upcoming-release-notes/1077.md
Labels: ✅ Approved

#1170 Fix “delete file” modal layout
  packages/desktop-client/src/components/manager/DeleteFile.js
  upcoming-release-notes/1066.md
  upcoming-release-notes/1170.md
Labels: ✅ Approved

#1183 Fix completed feature request handling
  .github/workflows/issues-feature-implemented.yml
  upcoming-release-notes/1183.md
Labels: ✅ Approved

#1082 Goals: Use shared 'months' functions for time
  packages/loot-core/src/server/budget/goaltemplates.ts
  packages/loot-core/src/shared/months.ts
  upcoming-release-notes/1082.md
Labels: ✅ Approved

#1189 :fire: remove beta code and some unused scripts
  bin/format-staged
  bin/import-open-source-package
  bin/make-release
  bin/package-browser
  bin/package-electron
  packages/desktop-client/src/browser-preload.browser.js
  packages/loot-core/src/client/shared-listeners.ts
  packages/loot-core/src/platform/server/fs/index.web.ts
  packages/loot-core/src/server/cloud-storage.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/server/sync/index.ts
  packages/loot-core/src/shared/errors.ts
  packages/loot-core/webpack/webpack.browser.config.js
  upcoming-release-notes/1189.md
Labels: ✅ Approved

#1190 :arrow_up: upgrade @reach/listbox and remove monkeypatch
  packages/desktop-client/package.json
  patches/@reach+listbox+0.11.2.patch
  upcoming-release-notes/1190.md
  yarn.lock
Labels: ✅ Approved

#1192 :arrow_up: upgrade react-dnd and remove monkeypatch
  packages/desktop-client/package.json
  packages/desktop-client/src/components/FinancesApp.js
  packages/desktop-client/src/components/sort.js
  patches/react-dnd-html5-backend+10.0.2.patch
  upcoming-release-notes/1192.md
  yarn.lock
Labels: ✅ Approved

#1195 :arrow_up: upgrade hotkeys-js from v3.8.2 to v3.10.3, remove monkeypatch
  packages/desktop-client/package.json
  packages/desktop-client/src/components/accounts/Account.js
  patches/hotkeys-js+3.8.2.patch
  upcoming-release-notes/1195.md
  yarn.lock
Labels: ✅ Approved

#1200 Remove unused deps from desktop-client
  packages/desktop-client/package.json
  upcoming-release-notes/1200.md
  yarn.lock
Labels: ✅ Approved

#1199 Add public/data to .eslintignore in desktop-client
  packages/desktop-client/.eslintignore
  upcoming-release-notes/1199.md
Labels: ✅ Approved

#1202 Run ESLint at the top level once
  .eslintignore
  .eslintrc.js
  package.json
  packages/api/.eslintignore
  packages/api/package.json
  packages/crdt/.eslintignore
  packages/crdt/package.json
  packages/desktop-client/.eslintignore
  packages/desktop-client/package.json
  packages/desktop-electron/.eslintignore
  packages/desktop-electron/package.json
  packages/eslint-plugin-actual/package.json
  packages/import-ynab4/.eslintignore
  packages/import-ynab4/package.json
  packages/import-ynab5/.eslintignore
  packages/import-ynab5/package.json
  packages/loot-core/.eslintignore
  packages/loot-core/package.json
  packages/node-libofx/.eslintignore
  packages/node-libofx/package.json
Labels: ✅ Approved

#1206 Add size comparison workflow
  .github/workflows/build.yml
  .github/workflows/check.yml
  .github/workflows/codeql.yml
  .github/workflows/electron.yml
  .github/workflows/release-notes.yml
  .github/workflows/size-compare.yml
Labels: 🔍 Ready for Review

#1184 Consistently use ExternalLink
  .eslintrc.js
  packages/desktop-client/src/components/FatalError.js
  packages/desktop-client/src/components/ManageRules.js
  packages/desktop-client/src/components/Notifications.js
  packages/desktop-client/src/components/Titlebar.js
  packages/desktop-client/src/components/UpdateNotification.js
  packages/desktop-client/src/components/accounts/AccountSyncCheck.js
  packages/desktop-client/src/components/common.tsx
  packages/desktop-client/src/components/manager/ImportYNAB5.js
  packages/desktop-client/src/components/manager/ManagementApp.js
  packages/desktop-client/src/components/manager/WelcomeScreen.js
  packages/desktop-client/src/components/manager/subscribe/Bootstrap.tsx
  packages/desktop-client/src/components/modals/CloseAccount.js
  packages/desktop-client/src/components/modals/CreateAccount.js
  packages/desktop-client/src/components/modals/CreateEncryptionKey.js
  packages/desktop-client/src/components/modals/CreateLocalAccount.js
  packages/desktop-client/src/components/modals/FixEncryptionKey.js
  packages/desktop-client/src/components/modals/NordigenExternalMsg.js
  packages/desktop-client/src/components/modals/NordigenInitialise.tsx
  packages/desktop-client/src/components/settings/Encryption.js
  packages/desktop-client/src/components/settings/Experimental.js
  packages/desktop-client/src/components/settings/UI.tsx
  packages/desktop-client/src/components/settings/index.js
  upcoming-release-notes/1184.md
Labels: ✅ Approved

#1205 Display bundle size changes in comments on opened PRs
  .github/workflows/build.yml
  .github/workflows/check.yml
  .github/workflows/codeql.yml
  .github/workflows/electron.yml
  .github/workflows/release-notes.yml
  packages/desktop-client/.gitignore
  packages/desktop-client/bin/build-browser
  packages/desktop-client/config-overrides.js
  packages/desktop-client/package.json
  packages/loot-core/package.json
  packages/loot-core/webpack/webpack.browser.config.js
  packages/loot-core/webpack/webpack.desktop.config.js
  upcoming-release-notes/1205.md
  yarn.lock
Labels: ✅ Approved

#1180 Improve some of the typings in loot-core
  packages/desktop-client/package.json
  packages/desktop-client/src/components/budget/rollover/BudgetSummary.tsx
  packages/loot-core/package.json
  packages/loot-core/src/client/actions/account.ts
  packages/loot-core/src/client/actions/app.ts
  packages/loot-core/src/client/actions/sync.ts
  packages/loot-core/src/mocks/budget.ts
  packages/loot-core/src/platform/server/connection/index.d.ts
  packages/loot-core/src/server/accounts/parse-file.test.ts
  packages/loot-core/src/server/accounts/parse-file.ts
  packages/loot-core/src/server/accounts/transactions.ts
  packages/loot-core/src/server/api.ts
  packages/loot-core/src/server/app.ts
  packages/loot-core/src/server/backups.ts
  packages/loot-core/src/server/budget/app.ts
  packages/loot-core/src/server/budget/base.ts
  packages/loot-core/src/server/budget/types/handlers.d.ts
  packages/loot-core/src/server/cloud-storage.ts
  packages/loot-core/src/server/main-app.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/server/mutators.ts
  packages/loot-core/src/server/notes/app.ts
  packages/loot-core/src/server/schedules/app.ts
  packages/loot-core/src/server/schedules/types/handlers.ts
  packages/loot-core/src/server/sync/index.ts
  packages/loot-core/src/server/sync/reset.ts
  packages/loot-core/src/server/tools/app.ts
  packages/loot-core/src/server/tools/types/handlers.d.ts
  packages/loot-core/src/server/undo.ts
  packages/loot-core/src/shared/errors.ts
  packages/loot-core/src/shared/months.ts
  packages/loot-core/src/types/handlers.d.ts
  packages/loot-core/src/types/server-handlers.d.ts
  packages/loot-core/src/types/util.d.ts
  upcoming-release-notes/1180.md
  yarn.lock
Labels: ✅ Approved

#1213 Bundle only the variable font version of Inter
  packages/desktop-client/package.json
  packages/desktop-client/src/fonts.scss
  packages/desktop-client/src/index.tsx
  upcoming-release-notes/1213.md
  yarn.lock
Labels: ✅ Approved

#1214 Fix size comparison workflow on fork PRs
  .github/workflows/build.yml
  .github/workflows/size-compare.yml
  upcoming-release-notes/1214.md
Labels: 🔍 Ready for Review

#1216 Remove redundant UUID wrapper module, update uuid package to 9.x
  .eslintrc.js
  packages/api/package.json
  packages/crdt/package.json
  packages/crdt/src/crdt/timestamp.ts
  packages/desktop-client/package.json
  packages/desktop-client/src/components/accounts/TransactionsTable.test.js
  packages/import-ynab4/importer.js
  packages/import-ynab4/package.json
  packages/import-ynab5/importer.js
  packages/import-ynab5/package.json
  packages/loot-core/package.json
  packages/loot-core/src/client/actions/notifications.ts
  packages/loot-core/src/mocks/index.ts
  packages/loot-core/src/mocks/plaid.ts
  packages/loot-core/src/platform/client/fetch/index.browser.ts
  packages/loot-core/src/platform/client/fetch/index.web.ts
  packages/loot-core/src/platform/client/undo/index.web.ts
  packages/loot-core/src/platform/uuid/index.d.ts
  packages/loot-core/src/platform/uuid/index.electron.ts
  packages/loot-core/src/platform/uuid/index.web.ts
  packages/loot-core/src/server/accounts/link.ts
  packages/loot-core/src/server/accounts/sync.ts
  packages/loot-core/src/server/aql/exec.test.ts
  packages/loot-core/src/server/backups.ts
  packages/loot-core/src/server/cloud-storage.ts
  packages/loot-core/src/server/db/index.ts
  packages/loot-core/src/server/encryption.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/server/migrate/migrations.ts
  packages/loot-core/src/server/schedules/app.ts
  packages/loot-core/src/server/schedules/find-schedules.ts
  packages/loot-core/src/server/util/budget-name.ts
  packages/loot-core/src/shared/transactions.test.ts
  packages/loot-core/src/shared/transactions.ts
  upcoming-release-notes/1216.md
  yarn.lock
Labels: ✅ Approved

#1218 Update .eslintignore
  .eslintignore
Labels: 🔍 Ready for Review

#1187 Clean up the public/ folder
  packages/desktop-client/.gitignore
  packages/desktop-client/public/codemirror.css
  packages/desktop-client/public/libofx.web.wasm
  packages/desktop-client/public/monokai.css
  packages/desktop-client/public/sql-wasm-debug.wasm
  packages/desktop-client/public/sql-wasm.wasm
  packages/loot-core/bin/build-browser
  upcoming-release-notes/1187.md
Labels: ✅ Approved

#1204 Fix drag and drop on touch devices (#1194)
  packages/desktop-client/package.json
  packages/desktop-client/src/components/FinancesApp.js
  upcoming-release-notes/1204.md
  yarn.lock
Labels: ✅ Approved

#1221 Tidy up electron
  packages/desktop-electron/build.sh
  packages/desktop-electron/electron-builder-fork.sh
  packages/desktop-electron/package.json
  upcoming-release-notes/1221.md
Labels: 🔍 Ready for Review, ✅ Approved

#1222 Move netlify-wait-for-build into github/actions folder
  .github/actions/netlify-wait-for-build
  .github/workflows/e2e-test.yml
  upcoming-release-notes/1222.md
Labels: 🔍 Ready for Review

#1227 :fire: remove unused scripts; simplify version script
  packages/desktop-client/bin/build-browser
  packages/desktop-client/bin/watch-browser
  packages/desktop-client/src/browser-preload.browser.js
  packages/loot-core/bin/get-db-schema
  packages/loot-core/bin/migrate.js
  packages/loot-core/bin/profile-sql.js
  packages/loot-core/bin/sql-regenerate-views
  upcoming-release-notes/1227.md
Labels: ✅ Approved

#1203 :fire: remove pikaday monkeypatch
  packages/desktop-client/config-overrides.js
  patches/pikaday+1.8.0.patch
  upcoming-release-notes/1203.md
Labels: ✅ Approved

#1229 :sparkles: add netlify development banner
  packages/desktop-client/config-overrides.js
  packages/desktop-client/src/components/App.js
  packages/desktop-client/src/components/DevelopmentTopBar.tsx
  packages/desktop-client/src/components/FatalError.js
  upcoming-release-notes/1229.md
Labels: ✅ Approved

#1231 :wrench: fix the build - ignore missing moment
  packages/desktop-client/config-overrides.js
Labels: ✅ Approved

#1230 :wrench: improved dev-server - enable asset cache
  packages/desktop-client/config-overrides.js
  packages/desktop-client/package.json
  upcoming-release-notes/1230.md
  yarn.lock
Labels: ✅ Approved

#1223 Lint tweaks
  .eslintignore
  .eslintrc.js
  package.json
  packages/loot-core/src/server/main.ts
  upcoming-release-notes/1223.md
  yarn.lock
Labels: ✅ Approved

#1210 Extract the reports page into a separate JS file
  packages/desktop-client/src/components/LoggedInUser.js
  packages/desktop-client/src/components/reports/ReportRouter.js
  packages/desktop-client/src/components/reports/index.js
  packages/desktop-client/src/components/reports/index.tsx
  packages/desktop-client/src/polyfills.ts
  packages/desktop-client/src/style.tsx
  upcoming-release-notes/1210.md
Labels: ✅ Approved

#1234 Restore undo-url-saving behavior
  packages/desktop-client/src/components/FinancesApp.js
  packages/desktop-client/src/global-events.js
  packages/loot-core/typings/window.d.ts
  upcoming-release-notes/1234.md
Labels: ✅ Approved

#1193 Goals: Add recurring schedule support
  packages/loot-core/src/server/budget/goaltemplates.ts
  upcoming-release-notes/1193.md
Labels: ✅ Approved

#1212 Remove usage of Formik
  packages/desktop-client/package.json
  packages/desktop-client/src/components/common.tsx
  packages/desktop-client/src/components/modals/CloseAccount.js
  packages/desktop-client/src/components/modals/CreateLocalAccount.js
  upcoming-release-notes/1212.md
  yarn.lock
Labels: ✅ Approved

#1228 Add onClick handlers to the schedule and transaction icons in the transaction list (#547)
  packages/desktop-client/src/components/accounts/Account.js
  packages/desktop-client/src/components/accounts/TransactionList.js
  packages/desktop-client/src/components/accounts/TransactionsTable.js
  upcoming-release-notes/1228.md
Labels: ✅ Approved

#1239 Add electron options to bug-report.yml
  .github/ISSUE_TEMPLATE/bug-report.yml
  upcoming-release-notes/1239.md
Labels: ✅ Approved
