Repository actualbudget/actual, pull requests merged in 2023-12, with the labels that each got.

#2000 [Goals]: Sort the priorities properly
  packages/loot-core/src/server/budget/goaltemplates.ts
  upcoming-release-notes/2000.md
Labels: ✅ Approved

#1900 Larger mobile autocomplete fonts and paddings
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-from-accounts-id-page-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-from-accounts-id-page-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-3-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-4-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js
  packages/desktop-client/src/components/autocomplete/AccountAutocomplete.tsx
  packages/desktop-client/src/components/autocomplete/CategoryAutocomplete.tsx
  packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.tsx
  packages/desktop-client/src/components/autocomplete/SavedFilterAutocomplete.tsx
  packages/desktop-client/src/components/mobile/MobileNavTabs.tsx
  packages/desktop-client/src/components/modals/EditField.js
  packages/desktop-client/src/components/transactions/MobileTransaction.js
  packages/desktop-client/src/components/transactions/TransactionsTable.test.js
  upcoming-release-notes/1900.md
Labels: ✅ Approved

#1991 Add some initial api tests for budgets and accounts
  packages/api/.gitignore
  packages/api/__snapshots__/methods.test.ts.snap
  packages/api/index.js
  packages/api/jest.config.js
  packages/api/methods.test.ts
  packages/api/mocks/budgets/.gitkeep
  packages/api/package.json
  upcoming-release-notes/1991.md
  yarn.lock
Labels: ✅ Approved

#2004 [Maintenance] BudgetTotals, GoCardlessLink, Import, WelcomeScreen components to Typescript.
  packages/desktop-client/src/components/budget/BudgetTotals.tsx
  packages/desktop-client/src/components/gocardless/GoCardlessLink.tsx
  packages/desktop-client/src/components/manager/Import.tsx
  packages/desktop-client/src/components/manager/WelcomeScreen.tsx
  packages/loot-core/src/client/actions/budgets.ts
  packages/loot-core/src/client/state-types/modals.d.ts
  packages/loot-core/src/types/file.d.ts
  upcoming-release-notes/2004.md
Labels: ✅ Approved

#2025 [Maintenance] Adding Aria labels for accessibility
  packages/desktop-client/src/components/NotesButton.tsx
  packages/desktop-client/src/components/Notifications.tsx
  packages/desktop-client/src/components/ThemeSelector.tsx
  packages/desktop-client/src/components/Titlebar.tsx
  packages/desktop-client/src/components/UpdateNotification.tsx
  packages/desktop-client/src/components/accounts/Header.js
  packages/desktop-client/src/components/budget/BudgetTotals.tsx
  packages/desktop-client/src/components/budget/MobileBudgetTable.js
  packages/desktop-client/src/components/budget/report/budgetsummary/BudgetSummary.tsx
  packages/desktop-client/src/components/budget/rollover/budgetsummary/BudgetSummary.tsx
  packages/desktop-client/src/components/manager/BudgetList.js
  packages/desktop-client/src/components/schedules/SchedulesTable.tsx
  packages/desktop-client/src/components/select/RecurringSchedulePicker.js
  packages/desktop-client/src/components/sidebar/ToggleButton.tsx
  packages/desktop-client/src/components/transactions/TransactionsTable.js
  packages/desktop-client/src/components/util/AmountInput.tsx
  upcoming-release-notes/2025.md
Labels: ✅ Approved

#2008 Fix #1977: Filter Amount formatting issue
  packages/desktop-client/src/components/filters/FiltersMenu.js
  upcoming-release-notes/2008.md
Labels: ✅ Approved

#2002 Fix failure to create category with deleted name
  packages/loot-core/src/server/db/index.test.ts
  packages/loot-core/src/server/db/index.ts
  upcoming-release-notes/2002.md
Labels: ✅ Approved

#2029 :recycle: (eslint) enable 'react/no-children-prop' rule and fix issues
  .eslintrc.js
  packages/desktop-client/src/components/NotesButton.tsx
  packages/desktop-client/src/components/ScrollProvider.tsx
  packages/desktop-client/src/components/Titlebar.tsx
  packages/desktop-client/src/components/budget/report/ReportContext.tsx
  packages/desktop-client/src/components/budget/rollover/RolloverContext.tsx
  packages/desktop-client/src/hooks/useSelected.tsx
  packages/loot-core/src/client/data-hooks/accounts.tsx
  packages/loot-core/src/client/data-hooks/payees.tsx
  packages/loot-core/src/client/data-hooks/schedules.tsx
  packages/loot-core/src/client/query-hooks.tsx
  upcoming-release-notes/2029.md
Labels: ✅ Approved

#1993 [Maintenance] Use Page component for mobile pages
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-checks-that-settings-page-can-be-opened-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-checks-that-settings-page-can-be-opened-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-checks-that-settings-page-can-be-opened-3-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-checks-that-settings-page-can-be-opened-4-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-from-accounts-id-page-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-from-accounts-id-page-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-3-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-4-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-5-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-6-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-loads-the-budget-page-with-budgeted-amounts-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-loads-the-budget-page-with-budgeted-amounts-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-3-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-4-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-5-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-6-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-the-accounts-page-and-asserts-on-balances-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-the-accounts-page-and-asserts-on-balances-2-chromium-linux.png
  packages/desktop-client/e2e/settings.test.js-snapshots/Settings-checks-the-page-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/settings.test.js-snapshots/Settings-checks-the-page-visuals-2-chromium-linux.png
  packages/desktop-client/src/components/MobileBackButton.tsx
  packages/desktop-client/src/components/Page.tsx
  packages/desktop-client/src/components/Titlebar.tsx
  packages/desktop-client/src/components/accounts/MobileAccountDetails.js
  packages/desktop-client/src/components/accounts/MobileAccounts.js
  packages/desktop-client/src/components/budget/MobileBudgetTable.js
  packages/desktop-client/src/components/settings/UI.tsx
  packages/desktop-client/src/components/settings/index.tsx
  packages/desktop-client/src/components/transactions/MobileTransaction.js
  upcoming-release-notes/1993.md
Labels: ✅ Approved

#2036 Add API category tests
  packages/api/methods.test.ts
  upcoming-release-notes/2036.md
Labels: 🔍 Ready for Review

#2023 :recycle: (typescript) adding strict typings to utils.ts
  packages/loot-core/src/mocks/budget.ts
  packages/loot-core/src/server/accounts/transaction-rules.ts
  packages/loot-core/src/shared/transactions.ts
  packages/loot-core/src/shared/util.ts
  packages/loot-core/src/types/models/transaction.d.ts
  upcoming-release-notes/2023.md
Labels: ✅ Approved

#2009 [Maintenance] Migrating util.js and chartTheme.js to typescript
  packages/desktop-client/src/components/reports/chart-theme.ts
  packages/desktop-client/src/components/reports/util.js
  packages/desktop-client/src/components/reports/util.ts
  upcoming-release-notes/2009.md
Labels: ✅ Approved

#1988 Custom Reports optimization
  packages/desktop-client/src/components/reports/ChooseGraph.tsx
  packages/desktop-client/src/components/reports/ReportOptions.tsx
  packages/desktop-client/src/components/reports/ReportTable.tsx
  packages/desktop-client/src/components/reports/ReportTableHeader.tsx
  packages/desktop-client/src/components/reports/ReportTableList.tsx
  packages/desktop-client/src/components/reports/ReportTableTotals.tsx
  packages/desktop-client/src/components/reports/graphs/AreaGraph.tsx
  packages/desktop-client/src/components/reports/graphs/BarGraph.tsx
  packages/desktop-client/src/components/reports/graphs/BarLineGraph.tsx
  packages/desktop-client/src/components/reports/graphs/DonutGraph.tsx
  packages/desktop-client/src/components/reports/graphs/LineGraph.tsx
  packages/desktop-client/src/components/reports/graphs/StackedBarGraph.tsx
  packages/desktop-client/src/components/reports/reports/CustomReport.js
  packages/desktop-client/src/components/reports/reports/CustomReportCard.js
  packages/desktop-client/src/components/reports/spreadsheets/default-spreadsheet.tsx
  packages/desktop-client/src/components/reports/spreadsheets/filterHiddenItems.ts
  packages/desktop-client/src/components/reports/spreadsheets/grouped-spreadsheet.ts
  packages/desktop-client/src/components/reports/spreadsheets/makeQuery.ts
  packages/desktop-client/src/components/reports/spreadsheets/recalculate.ts
  packages/desktop-client/src/components/reports/util.ts
  packages/loot-core/src/server/aql/compiler.ts
  packages/loot-core/src/types/models/rule.d.ts
  upcoming-release-notes/1988.md
Labels: ✅ Approved

#2067 Add new types for reports files
  packages/desktop-client/src/components/reports/ChooseGraph.tsx
  packages/desktop-client/src/components/reports/ReportOptions.tsx
  packages/desktop-client/src/components/reports/ReportTableHeader.tsx
  packages/desktop-client/src/components/reports/ReportTableTotals.tsx
  packages/desktop-client/src/components/reports/entities.d.ts
  packages/desktop-client/src/components/reports/graphs/AreaGraph.tsx
  packages/desktop-client/src/components/reports/graphs/BarGraph.tsx
  packages/desktop-client/src/components/reports/graphs/DonutGraph.tsx
  packages/desktop-client/src/components/reports/graphs/StackedBarGraph.tsx
  packages/desktop-client/src/components/reports/reports/CustomReport.js
  packages/desktop-client/src/components/reports/spreadsheets/default-spreadsheet.tsx
  packages/desktop-client/src/components/reports/spreadsheets/grouped-spreadsheet.ts
  upcoming-release-notes/2067.md
Labels: ✅ Approved

#2005 Cashflow.js -> Cashflow.tsx
  packages/desktop-client/src/components/reports/reports/CashFlow.tsx
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/2005.md
Labels: ✅ Approved

#2069 Renaming variables for reports files
  packages/desktop-client/src/components/reports/ChooseGraph.tsx
  packages/desktop-client/src/components/reports/ReportOptions.tsx
  packages/desktop-client/src/components/reports/ReportSidebar.js
  packages/desktop-client/src/components/reports/ReportSummary.js
  packages/desktop-client/src/components/reports/ReportTableHeader.tsx
  packages/desktop-client/src/components/reports/ReportTopbar.js
  packages/desktop-client/src/components/reports/reports/CustomReport.js
  packages/desktop-client/src/components/reports/reports/CustomReportCard.js
  packages/desktop-client/src/components/reports/spreadsheets/default-spreadsheet.tsx
  packages/desktop-client/src/components/reports/spreadsheets/grouped-spreadsheet.ts
  packages/desktop-client/src/components/reports/spreadsheets/makeQuery.ts
  upcoming-release-notes/2069.md
Labels: ✅ Approved

#2046 Custom Reports typescript updates and small functional changes
  packages/desktop-client/src/components/reports/ChooseGraph.tsx
  packages/desktop-client/src/components/reports/ModeButton.tsx
  packages/desktop-client/src/components/reports/ReportLegend.tsx
  packages/desktop-client/src/components/reports/ReportSidebar.js
  packages/desktop-client/src/components/reports/ReportSummary.tsx
  packages/desktop-client/src/components/reports/graphs/BarGraph.tsx
  packages/desktop-client/src/components/reports/reports/CustomReport.js
  packages/desktop-client/src/components/reports/spreadsheets/cash-flow-spreadsheet.tsx
  packages/desktop-client/src/components/reports/spreadsheets/makeQuery.ts
  packages/desktop-client/src/components/reports/spreadsheets/net-worth-spreadsheet.tsx
  upcoming-release-notes/2046.md
Labels: ✅ Approved

#1906 add support for auto theme
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-1-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-2-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-3-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-4-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-creates-a-new-account-and-views-the-initial-balance-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-creates-a-new-account-and-views-the-initial-balance-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/budget.test.js-snapshots/Budget-renders-the-summary-information-available-funds-overspent-budgeted-and-for-next-month-1-chromium-linux.png
  packages/desktop-client/e2e/budget.test.js-snapshots/Budget-renders-the-summary-information-available-funds-overspent-budgeted-and-for-next-month-2-chromium-linux.png
  packages/desktop-client/e2e/budget.test.js-snapshots/Budget-transfer-funds-to-another-category-1-chromium-linux.png
  packages/desktop-client/e2e/budget.test.js-snapshots/Budget-transfer-funds-to-another-category-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-checks-that-settings-page-can-be-opened-4-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-cash-flow-graph-and-checks-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-cash-flow-graph-and-checks-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-and-cash-flow-reports-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-and-cash-flow-reports-2-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-graph-and-checks-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-graph-and-checks-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-checks-the-page-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-checks-the-page-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-3-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-4-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-checks-the-page-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-checks-the-page-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-1-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-2-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-3-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-4-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-5-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-6-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-7-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-8-chromium-linux.png
  packages/desktop-client/e2e/settings.test.js-snapshots/Settings-checks-the-page-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/settings.test.js-snapshots/Settings-checks-the-page-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-checks-the-page-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-checks-the-page-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-split-test-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-split-test-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-test-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-test-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-category-5-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-category-6-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-date-5-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-date-6-chromium-linux.png
  packages/desktop-client/src/components/ThemeSelector.tsx
  packages/desktop-client/src/icons/v2/System.svg
  packages/desktop-client/src/icons/v2/System.tsx
  packages/desktop-client/src/icons/v2/index.ts
  packages/desktop-client/src/style/theme.tsx
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/types/prefs.d.ts
  upcoming-release-notes/1906.md
Labels: ✅ Approved

#2082 Add left and right margins to modals
  packages/desktop-client/src/components/common/Modal.tsx
  upcoming-release-notes/2082.md
Labels: ✅ Approved

#1899 Add schedule end date/count field
  packages/desktop-client/src/components/common/Select.tsx
  packages/desktop-client/src/components/rules/Value.tsx
  packages/desktop-client/src/components/schedules/DiscoverSchedules.tsx
  packages/desktop-client/src/components/schedules/EditSchedule.js
  packages/desktop-client/src/components/select/RecurringSchedulePicker.js
  packages/loot-core/src/server/budget/goals/goalsSchedule.ts
  packages/loot-core/src/server/schedules/app.ts
  packages/loot-core/src/shared/schedules.test.ts
  packages/loot-core/src/shared/schedules.ts
  packages/loot-core/src/types/models/schedule.d.ts
  upcoming-release-notes/1899.md
Labels: ✅ Approved

#2074 :construction_worker: (ci) adding helper comments for failed CI jobs
  .github/workflows/e2e-test.yml
  upcoming-release-notes/2074.md
Labels: ✅ Approved

#2092 Added BG Color to view to fix Issue 2089
  packages/desktop-client/src/components/FinancesApp.tsx
  upcoming-release-notes/2092.md
Labels: 🔍 Ready for Review, ✅ Approved

#2093 Fix issue 1878
  packages/desktop-client/src/components/budget/rollover/RolloverComponents.tsx
  upcoming-release-notes/2093.md
Labels: ✅ Approved

#2062 API – Return Hidden for Category and CategoryGroup
  packages/api/methods.test.ts
  packages/desktop-client/src/components/budget/index.tsx
  packages/loot-core/src/client/actions/queries.ts
  packages/loot-core/src/server/api-models.ts
  packages/loot-core/src/server/api.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/2062.md
Labels: ✅ Approved

#2065 :recycle: (TypeScript) fix strictFunctionTypes violations (pt 1)
  packages/loot-core/src/server/budget/types/handlers.d.ts
  packages/loot-core/src/server/mutators.ts
  packages/loot-core/src/server/undo.ts
  packages/loot-core/src/shared/async.ts
  packages/loot-core/src/types/api-handlers.d.ts
  packages/loot-core/src/types/handlers.d.ts
  packages/loot-core/src/types/server-handlers.d.ts
  tsconfig.json
  upcoming-release-notes/2065.md
Labels: ✅ Approved

#2080 Custom Reports date paused
  packages/desktop-client/src/components/reports/CategorySelector.tsx
  packages/desktop-client/src/components/reports/ReportSidebar.js
  packages/desktop-client/src/components/reports/reports/CustomReport.js
  packages/desktop-client/src/components/reports/spreadsheets/default-spreadsheet.tsx
  packages/desktop-client/src/components/reports/spreadsheets/grouped-spreadsheet.ts
  upcoming-release-notes/2080.md
Labels: ✅ Approved

#2078 Custom Reports Enable Legend
  packages/desktop-client/src/components/reports/ReportSidebar.js
  packages/desktop-client/src/components/reports/ReportTopbar.js
  packages/desktop-client/src/components/reports/entities.d.ts
  packages/desktop-client/src/components/reports/graphs/BarGraph.tsx
  packages/desktop-client/src/components/reports/graphs/DonutGraph.tsx
  packages/desktop-client/src/components/reports/graphs/StackedBarGraph.tsx
  packages/desktop-client/src/components/reports/reports/CustomReport.js
  packages/desktop-client/src/components/reports/spreadsheets/calculateLegend.ts
  packages/desktop-client/src/components/reports/spreadsheets/default-spreadsheet.tsx
  upcoming-release-notes/2078.md
Labels: ✅ Approved

#2073 [TS migration] Reafactor tooltips.js to use typescript
  packages/desktop-client/src/components/NotesButton.tsx
  packages/desktop-client/src/components/tooltips.tsx
  upcoming-release-notes/2073.md
Labels: ✅ Approved

#2094 Custom reports: make views global
  packages/desktop-client/src/components/reports/ReportLegend.tsx
  packages/desktop-client/src/components/reports/ReportSidebar.js
  packages/desktop-client/src/components/reports/ReportSummary.tsx
  packages/desktop-client/src/components/reports/ReportTopbar.js
  packages/desktop-client/src/components/reports/reports/CustomReport.js
  packages/loot-core/src/types/prefs.d.ts
  upcoming-release-notes/2094.md
Labels: ✅ Approved

#2099 [Goals]: fully skip budgeted categories when only applying
  packages/loot-core/src/server/budget/goaltemplates.ts
  upcoming-release-notes/2099.md
Labels: ✅ Approved

#2100 [Goals]: don't run templates in hidden groups
  packages/loot-core/src/server/budget/goaltemplates.ts
  upcoming-release-notes/2100.md
Labels: ✅ Approved

#2066 :recycle: (TypeScript) fix strictFunctionTypes violations (pt 2)
  packages/desktop-client/src/components/sidebar/Item.tsx
  packages/desktop-client/src/components/sidebar/SecondaryItem.tsx
  packages/desktop-client/src/components/sort.tsx
  packages/desktop-client/src/components/table.tsx
  packages/loot-core/package.json
  packages/loot-core/src/server/sync/sync.property.test.ts
  upcoming-release-notes/2066.md
  yarn.lock
Labels: ✅ Approved

#2096 :bug: fix category spending report
  packages/desktop-client/src/components/reports/reports/CategorySpending.jsx
  upcoming-release-notes/2096.md
Labels: ✅ Approved

#2070 :recycle: (TypeScript) fix strictFunctionTypes violations (pt 3)
  packages/desktop-client/src/components/autocomplete/Autocomplete.tsx
  packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.tsx
  packages/desktop-client/src/components/autocomplete/SavedFilterAutocomplete.tsx
  packages/loot-core/src/client/data-hooks/filters.ts
  packages/loot-core/src/types/models/index.d.ts
  packages/loot-core/src/types/models/transaction-filter.d.ts
  upcoming-release-notes/2070.md
Labels: ✅ Approved

#2111 :recycle: (eslint) disallow unnecessary curly braces
  .eslintrc.js
  packages/desktop-client/src/components/filters/FiltersButton.tsx
  packages/desktop-client/src/components/reports/ReportTableHeader.tsx
  packages/desktop-client/src/components/reports/ReportTableTotals.tsx
  packages/desktop-client/src/components/reports/SaveReport.tsx
  packages/desktop-client/src/components/reports/graphs/BarGraph.tsx
  packages/desktop-client/src/components/reports/graphs/StackedBarGraph.tsx
  upcoming-release-notes/2111.md
Labels: ✅ Approved

#2112 :recycle: (typescript) moving DeleteFile modal to TS
  packages/desktop-client/src/components/manager/DeleteFile.tsx
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/2112.md
Labels: ✅ Approved

#2113 [ESLint] Enable prefer-const project-wide
  .eslintrc.js
  packages/desktop-client/e2e/budget.test.js
  packages/eslint-plugin-actual/lib/rules/prefer-if-statement.js
  packages/eslint-plugin-actual/lib/rules/typography.js
  packages/loot-core/migrations/1632571489012_remove_cache.js
  packages/node-libofx/index.js
  upcoming-release-notes/2113.md
Labels: ✅ Approved

#2098 Custom Reports Donut Graph refactor
  packages/desktop-client/src/components/reports/graphs/DonutGraph.tsx
  upcoming-release-notes/2098.md
Labels: ✅ Approved

#2071 :recycle: (TypeScript) fix strictFunctionTypes violations (pt 4)
  packages/desktop-client/src/components/common/Menu.tsx
  packages/desktop-client/src/components/payees/PayeeTable.tsx
  packages/desktop-client/src/components/schedules/SchedulesTable.tsx
  packages/desktop-client/src/components/table.tsx
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  packages/loot-core/src/server/sync/sync.property.test.ts
  upcoming-release-notes/2071.md
Labels: ✅ Approved

#2068 Mobile split transactions
  packages/desktop-client/e2e/mobile.test.js
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-from-accounts-id-page-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-from-accounts-id-page-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-3-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-4-chromium-linux.png
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/budget/MobileBudgetTable.jsx
  packages/desktop-client/src/components/mobile/MobileAmountInput.jsx
  packages/desktop-client/src/components/mobile/MobileForms.jsx
  packages/desktop-client/src/components/modals/EditField.jsx
  packages/desktop-client/src/components/schedules/EditSchedule.jsx
  packages/desktop-client/src/components/transactions/MobileTransaction.jsx
  packages/desktop-client/src/components/util/AmountInput.tsx
  packages/desktop-client/src/hooks/useSingleActiveEditForm.tsx
  packages/loot-core/src/client/state-types/modals.d.ts
  upcoming-release-notes/2068.md
Labels: ✅ Approved

#1964 Mobile category modal menu
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/Notes.tsx
  packages/desktop-client/src/components/NotesButton.tsx
  packages/desktop-client/src/components/budget/MobileBudget.jsx
  packages/desktop-client/src/components/budget/MobileBudgetTable.jsx
  packages/desktop-client/src/components/common/Menu.tsx
  packages/desktop-client/src/components/common/Modal.tsx
  packages/desktop-client/src/components/modals/CategoryGroupMenu.tsx
  packages/desktop-client/src/components/modals/CategoryMenu.tsx
  packages/desktop-client/src/components/modals/EditRule.jsx
  packages/desktop-client/src/components/modals/ManageRulesModal.tsx
  packages/desktop-client/src/components/modals/Notes.tsx
  packages/desktop-client/src/components/modals/SingleInput.tsx
  packages/desktop-client/src/components/reports/reports/CustomReport.jsx
  packages/desktop-client/src/components/reports/reports/CustomReportCard.jsx
  packages/desktop-client/src/components/util/GenericInput.jsx
  packages/loot-core/src/client/actions/modals.ts
  packages/loot-core/src/client/constants.ts
  packages/loot-core/src/client/reducers/modals.ts
  packages/loot-core/src/client/state-types/modals.d.ts
  upcoming-release-notes/1964.md
Labels: ✅ Approved

#2085 Custom reports header fix
  packages/desktop-client/src/components/reports/ChooseGraph.tsx
  packages/desktop-client/src/components/reports/ReportTable.tsx
  packages/desktop-client/src/components/reports/ReportTableHeader.tsx
  packages/desktop-client/src/components/reports/ReportTableList.tsx
  packages/desktop-client/src/components/reports/ReportTableTotals.tsx
  packages/desktop-client/src/components/reports/entities.d.ts
  upcoming-release-notes/2085.md
Labels: ✅ Approved

#2127 [Bugfix] Fix update transaction API bug
  packages/loot-core/src/server/api.ts
  upcoming-release-notes/2127.md
Labels: ✅ Approved

#2128 revert: ♻️ (TypeScript) fix strictFunctionTypes violations (pt 4)
  packages/desktop-client/src/components/common/Menu.tsx
  packages/desktop-client/src/components/payees/PayeeTable.tsx
  packages/desktop-client/src/components/schedules/SchedulesTable.tsx
  packages/desktop-client/src/components/table.tsx
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  packages/loot-core/src/server/sync/sync.property.test.ts
  upcoming-release-notes/2071.md
Labels: ✅ Approved
