Repository actualbudget/actual, pull requests merged in 2023-07, with the labels that each got.

#1243 Run “Handle completed feature requests” in pull_request_target
  .github/actions/handle-feature-requests.js
  .github/workflows/issues-feature-implemented.yml
  upcoming-release-notes/1243.md
Labels: ✅ Approved

#1219 Auto-close the local/nordigen picker modal after creating an account
  packages/desktop-client/src/components/modals/CreateLocalAccount.js
  upcoming-release-notes/1219.md
Labels: ✅ Approved

#1224 Fix importing transfers from YNAB4/5
  packages/import-ynab4/importer.js
  packages/import-ynab5/importer.js
  upcoming-release-notes/1224.md
Labels: ✅ Approved

#1246 .gitattributes Check line endings for tsx files
  .gitattributes
  upcoming-release-notes/1246.md
Labels: ✅ Approved

#1251 :wrench: cancel previous CI runs if a new push is made
  .github/workflows/build.yml
  .github/workflows/check.yml
  .github/workflows/codeql.yml
  .github/workflows/e2e-test.yml
  .github/workflows/electron.yml
  .github/workflows/release-notes.yml
  .github/workflows/size-compare.yml
  upcoming-release-notes/1251.md
Labels: ✅ Approved

#1122 Saved Filters Page
  packages/desktop-client/src/components/ManageRules.js
  packages/desktop-client/src/components/accounts/Account.js
  packages/desktop-client/src/components/autocomplete/SavedFilterAutocomplete.js
  packages/desktop-client/src/components/common.tsx
  packages/desktop-client/src/components/filters/FiltersMenu.js
  packages/desktop-client/src/components/filters/SavedFilters.js
  packages/desktop-client/src/components/modals/EditRule.js
  packages/desktop-client/src/components/reports/CashFlow.js
  packages/desktop-client/src/components/reports/Header.js
  packages/desktop-client/src/components/reports/NetWorth.js
  packages/desktop-client/src/components/reports/graphs/cash-flow-spreadsheet.tsx
  packages/desktop-client/src/components/reports/graphs/net-worth-spreadsheet.tsx
  packages/desktop-client/src/components/util/GenericInput.js
  packages/desktop-client/src/hooks/useFilters.ts
  packages/loot-core/migrations/1685375406832_transaction_filters.sql
  packages/loot-core/src/client/data-hooks/filters.tsx
  packages/loot-core/src/server/accounts/transaction-rules.ts
  packages/loot-core/src/server/aql/schema/index.ts
  packages/loot-core/src/server/filters/app.ts
  packages/loot-core/src/server/filters/types/handlers.d.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/shared/rules.ts
  packages/loot-core/src/types/handlers.d.ts
  upcoming-release-notes/1122.md
Labels: 🔍 Ready for Review

#1242 Fix electron export issue
  packages/loot-core/src/platform/server/sqlite/index.d.ts
  packages/loot-core/src/platform/server/sqlite/index.electron.ts
  packages/loot-core/src/platform/server/sqlite/index.web.ts
  packages/loot-core/src/server/cloud-storage.ts
  upcoming-release-notes/1242.md
Labels: ✅ Approved

#1247 :bug: (mobile) reduce the size of account cards
  packages/desktop-client/src/components/accounts/MobileAccounts.js
  upcoming-release-notes/1247.md
Labels: ✅ Approved

#1252 :bug: fix toggling of balances in all-accounts view
  packages/desktop-client/src/components/accounts/Account.js
  upcoming-release-notes/1252.md
Labels: ✅ Approved

#1248 :recycle: moving some components from common.tsx to separate files
  packages/desktop-client/src/components/common.tsx
  packages/desktop-client/src/components/common/Block.tsx
  packages/desktop-client/src/components/common/Card.tsx
  packages/desktop-client/src/components/common/HoverTarget.tsx
  packages/desktop-client/src/components/common/InlineField.tsx
  packages/desktop-client/src/components/common/Label.tsx
  packages/desktop-client/src/components/common/Select.tsx
  packages/desktop-client/src/components/common/TextOneLine.tsx
  upcoming-release-notes/1248.md
Labels: ✅ Approved

#1256 Remove remaining locationPtr usage
  packages/desktop-client/src/components/accounts/Account.js
  packages/desktop-client/src/global-events.js
  packages/desktop-client/src/util/router-tools.tsx
  packages/desktop-electron/menu.js
  packages/loot-core/typings/window.d.ts
  upcoming-release-notes/1256.md
Labels: ✅ Approved

#1257 :recycle: moving more components out of common.tsx
  packages/desktop-client/src/components/common.tsx
  packages/desktop-client/src/components/common/AlignedText.tsx
  packages/desktop-client/src/components/common/CustomSelect.tsx
  packages/desktop-client/src/components/common/FormError.tsx
  packages/desktop-client/src/components/common/InitialFocus.tsx
  packages/desktop-client/src/components/common/InputWithContent.tsx
  packages/desktop-client/src/components/common/Menu.tsx
  packages/desktop-client/src/components/common/Search.tsx
  upcoming-release-notes/1257.md
Labels: ✅ Approved

#1262 Fix calculation of how many table rows to render
  packages/desktop-client/src/components/FixedSizeList.js
  upcoming-release-notes/1262.md
Labels: ✅ Approved

#1265 cleared/uncleared background update
  packages/desktop-client/src/components/accounts/Account.js
  upcoming-release-notes/1265.md
Labels: ✅ Approved

#1250 :bug: fix link-schedule option in transaction table
  packages/desktop-client/src/components/accounts/Account.js
  packages/desktop-client/src/global-events.js
  packages/desktop-client/src/util/router-tools.tsx
  packages/desktop-electron/menu.js
  packages/loot-core/typings/window.d.ts
  upcoming-release-notes/1250.md
  upcoming-release-notes/1256.md
Labels: ✅ Approved

#1260 Fix transaction list scrolling behavior
  packages/desktop-client/src/components/accounts/TransactionsTable.js
  packages/desktop-client/src/components/table.tsx
  upcoming-release-notes/1260.md
Labels: ✅ Approved

#1259 :recycle: (select) removing 2x usages of the Select component
  packages/desktop-client/e2e/page-models/account-page.js
  packages/desktop-client/e2e/page-models/close-account-modal.js
  packages/desktop-client/src/components/modals/CloseAccount.js
  packages/desktop-client/src/components/reports/Header.js
  upcoming-release-notes/1259.md
Labels: ✅ Approved

#1267 Fix layout of the management app with the demo bar in place
  packages/desktop-client/src/components/App.js
  upcoming-release-notes/1267.md
Labels: ✅ Approved

#1076 chore: add types to `crdt` package
  packages/crdt/src/crdt/index.ts
  packages/crdt/src/crdt/merkle.test.ts
  packages/crdt/src/crdt/merkle.ts
  packages/crdt/src/crdt/timestamp.test.ts
  packages/crdt/src/crdt/timestamp.ts
  packages/crdt/src/main.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/server/migrate/migrations.ts
  packages/loot-core/src/server/sync/encoder.ts
  packages/loot-core/src/server/sync/index.ts
  packages/loot-core/src/server/sync/migrate.test.ts
  packages/loot-core/src/server/sync/migrate.ts
  packages/loot-core/src/server/sync/repair.ts
  packages/loot-core/src/server/sync/sync.property.test.ts
  packages/loot-core/src/server/sync/sync.test.ts
  packages/loot-core/src/server/tests/mockSyncServer.ts
  packages/loot-core/src/server/undo.ts
  upcoming-release-notes/1076.md
Labels: ✅ Approved

#1258 Reorganize Accounts Folder
  packages/desktop-client/src/components/accounts/Account.js
  packages/desktop-client/src/components/accounts/Balance.js
  packages/desktop-client/src/components/accounts/Header.js
  packages/desktop-client/src/components/accounts/MobileAccountDetails.js
  packages/desktop-client/src/components/accounts/Reconcile.js
  packages/desktop-client/src/components/common.tsx
  packages/desktop-client/src/components/common/MenuButton.tsx
  packages/desktop-client/src/components/common/MenuTooltip.tsx
  packages/desktop-client/src/components/filters/SavedFilters.js
  packages/desktop-client/src/components/modals/EditRule.js
  packages/desktop-client/src/components/schedules/EditSchedule.js
  packages/desktop-client/src/components/transactions/MobileTransaction.js
  packages/desktop-client/src/components/transactions/SelectedTransactions.js
  packages/desktop-client/src/components/transactions/SimpleTransactionsTable.js
  packages/desktop-client/src/components/transactions/TransactionList.js
  packages/desktop-client/src/components/transactions/TransactionsTable.js
  packages/desktop-client/src/components/transactions/TransactionsTable.test.js
  upcoming-release-notes/1258.md
Labels: ✅ Approved

#1254 Goals: Add option to percent goal to use available funds
  packages/loot-core/src/server/budget/goaltemplates.ts
  upcoming-release-notes/1254.md
Labels: 🔍 Ready for Review

#1268 Fallback to memo in ofx if payee is not found
  packages/loot-core/src/server/accounts/parse-file.ts
  upcoming-release-notes/1268.md
Labels: 🔍 Ready for Review, ✅ Approved

#1279 :bookmark: (crdt) v2.0.0
  packages/crdt/package.json
  packages/loot-core/src/server/main.ts
Labels: ✅ Approved

#1289 :bug: fix nordigen sync bug
  packages/desktop-client/src/components/budget/misc.js
  packages/loot-core/src/client/actions/sync.ts
  upcoming-release-notes/1289.md
Labels: 🔍 Ready for Review

#1294 :bug: custom select width and scrollbars
  packages/desktop-client/src/components/common/CustomSelect.tsx
  packages/desktop-client/src/components/reports/Header.js
  upcoming-release-notes/1294.md
Labels: ✅ Approved

#1291 🐛 fix new budget files not syncing
  packages/crdt/package.json
  packages/crdt/src/crdt/merkle.ts
  packages/crdt/src/crdt/timestamp.ts
  upcoming-release-notes/1291.md
Labels: ✅ Approved

#1295 :bookmark: (23.7.1) critical sync fixes
  packages/desktop-client/package.json
  packages/desktop-electron/package.json
  upcoming-release-notes/1289.md
  upcoming-release-notes/1291.md
  upcoming-release-notes/1294.md
Labels: ✅ Approved

#1302 :loud_sound: improving 'invalid-schema' error logs
  packages/loot-core/src/server/sync/index.ts
  upcoming-release-notes/1302.md
Labels: ✅ Approved

#1297 Fix page not found error in README
  README.md
  upcoming-release-notes/1297.md
Labels: ✅ Approved

#1308 :bug: fix zero budget values
  packages/desktop-client/src/components/spreadsheet/format.js
  upcoming-release-notes/1308.md
Labels: ✅ Approved

#1306 Revert "Fix drag and drop on touch devices (#1194)"
  packages/desktop-client/package.json
  packages/desktop-client/src/components/FinancesApp.js
  upcoming-release-notes/1306.md
  yarn.lock
Labels: ✅ Approved

#1305 :bug: changing pages while adding a transaction
  packages/desktop-client/src/components/accounts/Account.js
  upcoming-release-notes/1305.md
Labels: ✅ Approved

#1307 Fix migration check script
  .github/actions/check-migrations.js
  .github/workflows/check.yml
  upcoming-release-notes/1307.md
Labels: ✅ Approved

#1314 Fix Custom Select unnecessary disabled scrollbar
  packages/desktop-client/src/components/common/CustomSelect.tsx
  upcoming-release-notes/1314.md
Labels: ✅ Approved

#1309 Fix ID for transaction_filters migration, patch existing migration
  packages/loot-core/migrations/1688749527273_transaction_filters.sql
  packages/loot-core/src/server/migrate/migrations.ts
  upcoming-release-notes/1309.md
Labels: ✅ Approved

#1317 :bug: fix sync: add back 'accounts.type' column
  packages/api/package.json
  packages/loot-core/migrations/1688841238000_add_account_type.sql
  upcoming-release-notes/1317.md
Labels: ✅ Approved

#1322 :bookmark: (23.7.2) more patches (not so critical, but still annoying)
  packages/desktop-client/package.json
  packages/desktop-electron/package.json
  upcoming-release-notes/1297.md
  upcoming-release-notes/1302.md
  upcoming-release-notes/1305.md
  upcoming-release-notes/1306.md
  upcoming-release-notes/1307.md
  upcoming-release-notes/1308.md
  upcoming-release-notes/1309.md
  upcoming-release-notes/1314.md
  upcoming-release-notes/1317.md
Labels: ✅ Approved

#1277 Remove some usages of the Select component
  packages/desktop-client/src/components/common/CustomSelect.tsx
  packages/desktop-client/src/components/modals/ImportTransactions.js
  packages/desktop-client/src/components/select/RecurringSchedulePicker.js
  packages/desktop-client/src/components/settings/Format.js
  upcoming-release-notes/1277.md
Labels: 🔍 Ready for Review, ✅ Approved

#1288 Goals: Improve remainder calculation when combined with other keywords
  packages/loot-core/src/server/budget/goaltemplates.ts
  upcoming-release-notes/1288.md
Labels: ✅ Approved

#1311 Add transfers to CashFlow Report
  packages/desktop-client/src/components/reports/CashFlow.js
  packages/desktop-client/src/components/reports/graphs/cash-flow-spreadsheet.tsx
  packages/desktop-client/src/components/reports/util.js
  upcoming-release-notes/1311.md
Labels: ✅ Approved

#1325 Fix the CashFlow report crash because of the new CustomSelect
  packages/desktop-client/src/components/common/CustomSelect.tsx
  packages/desktop-client/src/components/reports/Header.js
  upcoming-release-notes/1325.md
Labels: ✅ Approved

#1235 Month picker rework
  packages/desktop-client/src/components/budget/MonthPicker.js
  packages/desktop-client/src/components/budget/misc.js
  packages/desktop-client/src/components/budget/rollover/BudgetSummary.tsx
  upcoming-release-notes/1235.md
Labels: ✅ Approved

#1344 Goals: Use setZero function within goal templates for speed improvement
  packages/loot-core/src/server/budget/goaltemplates.ts
  upcoming-release-notes/1344.md
Labels: ✅ Approved

#1343 Remove legacy Select and NativeCategorySelect Component
  packages/desktop-client/src/components/autocomplete/CategorySelect.tsx
  packages/desktop-client/src/components/common.tsx
  packages/desktop-client/src/components/common/Select.tsx
  packages/desktop-client/src/components/modals/ConfirmCategoryDelete.js
  upcoming-release-notes/1343.md
Labels: ✅ Approved

#1349 Fix importing transactions in Safari and clean up openFileDialog API
  packages/desktop-client/src/browser-preload.browser.js
  packages/desktop-client/src/components/modals/ImportTransactions.js
  upcoming-release-notes/1349.md
Labels: ✅ Approved

#1351 Fix a bug in confirm category delete
  packages/desktop-client/src/components/modals/ConfirmCategoryDelete.js
  upcoming-release-notes/1351.md
Labels: ✅ Approved

#1298 Sort saved filters by alphabetical order
  packages/loot-core/src/client/data-hooks/filters.tsx
  upcoming-release-notes/1298.md
Labels: ✅ Approved

#1353 Stop the demo build bar from shrinking on mobile/small sizes
  packages/desktop-client/src/components/DevelopmentTopBar.tsx
  upcoming-release-notes/1353.md
Labels: ✅ Approved

#1335 Update logic for showing and rendering the “Show unused payees” button
  packages/desktop-client/src/components/payees/index.js
  upcoming-release-notes/1335.md
Labels: ✅ Approved

#1355 Add a few more ESLint rules
  .eslintrc.js
  packages/desktop-client/src/components/Background.js
  packages/desktop-client/src/components/Modals.js
  packages/desktop-client/src/components/NotesButton.tsx
  packages/desktop-client/src/components/accounts/Account.js
  packages/desktop-client/src/components/accounts/MobileAccount.js
  packages/desktop-client/src/components/autocomplete/Autocomplete.tsx
  packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.js
  packages/desktop-client/src/components/common.tsx
  packages/desktop-client/src/components/common/Input.tsx
  packages/desktop-client/src/components/common/InputWithContent.tsx
  packages/desktop-client/src/components/common/Menu.tsx
  packages/desktop-client/src/components/modals/EditRule.js
  packages/desktop-client/src/components/modals/FixEncryptionKey.js
  packages/desktop-client/src/components/modals/NordigenExternalMsg.js
  packages/desktop-client/src/components/modals/PlaidExternalMsg.js
  packages/desktop-client/src/components/payees/index.js
  packages/desktop-client/src/components/reports/useReport.js
  packages/desktop-client/src/components/schedules/SchedulesTable.js
  packages/desktop-client/src/components/select/DateSelect.js
  packages/desktop-client/src/components/select/RecurringSchedulePicker.js
  packages/desktop-client/src/components/table.tsx
  packages/desktop-client/src/components/tooltips.js
  packages/desktop-client/src/components/transactions/MobileTransaction.js
  packages/desktop-client/src/components/transactions/SelectedTransactions.js
  packages/desktop-client/src/components/transactions/TransactionsTable.test.js
  packages/desktop-client/src/hooks/useSelected.js
  packages/desktop-electron/updater.js
  packages/eslint-plugin-actual/lib/rules/__tests__/prefer-if-statement.js
  packages/eslint-plugin-actual/lib/rules/__tests__/typography.js
  packages/eslint-plugin-actual/lib/rules/prefer-if-statement.js
  packages/loot-core/.babelrc
  packages/loot-core/webpack/webpack.browser.config.js
  upcoming-release-notes/1355.md
  yarn.lock
Labels: ✅ Approved

#1312 Goals: Fix calculated fill when using multiple 'up to' statements in different priority levels
  packages/loot-core/src/server/budget/goaltemplates.ts
  upcoming-release-notes/1312.md
Labels: ✅ Approved

#1348 Rename <CustomSelect> to <Select>
  packages/desktop-client/src/components/common.tsx
  packages/desktop-client/src/components/common/Select.tsx
  packages/desktop-client/src/components/filters/FiltersMenu.js
  packages/desktop-client/src/components/modals/EditRule.js
  packages/desktop-client/src/components/modals/ImportTransactions.js
  packages/desktop-client/src/components/reports/Header.js
  packages/desktop-client/src/components/select/RecurringSchedulePicker.js
  packages/desktop-client/src/components/settings/Format.js
  upcoming-release-notes/1348.md
Labels: 🔍 Ready for Review

#1334 Remove bottom border radius from the payee table
  packages/desktop-client/src/components/payees/index.js
  upcoming-release-notes/1334.md
Labels: ✅ Approved

#1281 Remove author from electron package.json
  packages/desktop-electron/package.json
  upcoming-release-notes/1281.md
Labels: ✅ Approved

#1316 Fix clicking enter will create empty transaction
  packages/desktop-client/src/components/select/DateSelect.js
  upcoming-release-notes/1316.md
Labels: ✅ Approved

#1269 Add typings to most of the Redux logic
  .eslintrc.js
  packages/desktop-client/package.json
  packages/desktop-client/src/components/Modals.js
  packages/desktop-client/src/components/Notifications.tsx
  packages/desktop-client/src/components/manager/ImportActual.js
  packages/desktop-client/src/components/manager/ImportYNAB4.js
  packages/desktop-client/src/components/manager/ImportYNAB5.js
  packages/desktop-client/src/components/manager/Modals.js
  packages/desktop-client/src/components/modals/ConfigureLinkedAccounts.js
  packages/desktop-client/src/hooks/useActions.ts
  packages/desktop-client/src/hooks/useFeatureFlag.ts
  packages/loot-core/package.json
  packages/loot-core/src/client/actions/account.ts
  packages/loot-core/src/client/actions/app.ts
  packages/loot-core/src/client/actions/backups.ts
  packages/loot-core/src/client/actions/budgets.ts
  packages/loot-core/src/client/actions/debug.ts
  packages/loot-core/src/client/actions/index.ts
  packages/loot-core/src/client/actions/modals.ts
  packages/loot-core/src/client/actions/notifications.ts
  packages/loot-core/src/client/actions/prefs.ts
  packages/loot-core/src/client/actions/queries.ts
  packages/loot-core/src/client/actions/types.d.ts
  packages/loot-core/src/client/constants.ts
  packages/loot-core/src/client/reducers/account.ts
  packages/loot-core/src/client/reducers/app.ts
  packages/loot-core/src/client/reducers/budgets.ts
  packages/loot-core/src/client/reducers/debug.ts
  packages/loot-core/src/client/reducers/index.ts
  packages/loot-core/src/client/reducers/modals.ts
  packages/loot-core/src/client/reducers/notifications.ts
  packages/loot-core/src/client/reducers/prefs.ts
  packages/loot-core/src/client/reducers/profile.ts
  packages/loot-core/src/client/reducers/queries.ts
  packages/loot-core/src/client/reducers/user.ts
  packages/loot-core/src/client/shared-listeners.ts
  packages/loot-core/src/client/state-types/account.d.ts
  packages/loot-core/src/client/state-types/app.d.ts
  packages/loot-core/src/client/state-types/budgets.d.ts
  packages/loot-core/src/client/state-types/index.d.ts
  packages/loot-core/src/client/state-types/modals.d.ts
  packages/loot-core/src/client/state-types/notifications.d.ts
  packages/loot-core/src/client/state-types/prefs.d.ts
  packages/loot-core/src/client/state-types/queries.d.ts
  packages/loot-core/src/client/state-types/user.d.ts
  packages/loot-core/src/mocks/budget.ts
  packages/loot-core/src/server/accounts/sync.ts
  packages/loot-core/src/server/budget/cleanup-template.ts
  packages/loot-core/src/server/budget/goaltemplates.ts
  packages/loot-core/src/server/budget/types/handlers.d.ts
  packages/loot-core/src/server/undo.ts
  packages/loot-core/src/shared/accounts.ts
  packages/loot-core/src/shared/util.ts
  packages/loot-core/src/types/budget.d.ts
  packages/loot-core/src/types/file.d.ts
  packages/loot-core/src/types/models/account.d.ts
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/1269.md
  yarn.lock
Labels: ✅ Approved

#1232 Sort Transactions on Accounts Page
  packages/desktop-client/src/components/accounts/Account.js
  packages/desktop-client/src/components/accounts/Header.js
  packages/desktop-client/src/components/table.tsx
  packages/desktop-client/src/components/transactions/TransactionList.js
  packages/desktop-client/src/components/transactions/TransactionsTable.js
  upcoming-release-notes/1232.md
Labels: ✅ Approved

#1272 Privacy mode
  packages/desktop-client/src/components/PrivacyFilter.tsx
  packages/desktop-client/src/components/Titlebar.js
  packages/desktop-client/src/components/accounts/Balance.js
  packages/desktop-client/src/components/budget/MobileBudgetTable.js
  packages/desktop-client/src/components/budget/report/BudgetSummary.tsx
  packages/desktop-client/src/components/budget/report/components.tsx
  packages/desktop-client/src/components/budget/rollover/BudgetSummary.tsx
  packages/desktop-client/src/components/budget/rollover/rollover-components.tsx
  packages/desktop-client/src/components/modals/BudgetSummary.js
  packages/desktop-client/src/components/settings/Experimental.js
  packages/desktop-client/src/components/spreadsheet/CellValue.tsx
  packages/desktop-client/src/components/spreadsheet/NamespaceContext.ts
  packages/desktop-client/src/components/spreadsheet/SheetValue.tsx
  packages/desktop-client/src/components/spreadsheet/format.ts
  packages/desktop-client/src/components/spreadsheet/index.ts
  packages/desktop-client/src/components/spreadsheet/useSheetName.ts
  packages/desktop-client/src/components/spreadsheet/useSheetValue.js
  packages/desktop-client/src/components/spreadsheet/useSheetValue.ts
  packages/desktop-client/src/components/table.tsx
  packages/desktop-client/src/components/transactions/TransactionsTable.js
  packages/desktop-client/src/components/transactions/TransactionsTable.test.js
  packages/desktop-client/src/hooks/useFeatureFlag.ts
  packages/desktop-client/src/icons/v2/Eye.js
  packages/desktop-client/src/icons/v2/EyeSlashed.js
  packages/desktop-client/src/icons/v2/eye-slashed.svg
  packages/desktop-client/src/icons/v2/eye.svg
  packages/loot-core/src/client/privacy.ts
  packages/loot-core/src/client/state-types/prefs.d.ts
  upcoming-release-notes/1272.md
Labels: 🔍 Ready for Review

#1359 Add clear typings to the modals
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/hooks/useActions.ts
  packages/loot-core/src/client/actions/budgets.ts
  packages/loot-core/src/client/actions/modals.ts
  packages/loot-core/src/client/reducers/modals.ts
  packages/loot-core/src/client/state-types/modals.d.ts
  upcoming-release-notes/1359.md
Labels: ✅ Approved

#1361 :recycle: (Nordigen) rename to GoCardless
  packages/desktop-client/src/components/FinancesApp.js
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/accounts/Account.js
  packages/desktop-client/src/components/accounts/AccountSyncCheck.js
  packages/desktop-client/src/components/gocardless/GoCardlessLink.js
  packages/desktop-client/src/components/modals/CreateAccount.js
  packages/desktop-client/src/components/modals/GoCardlessExternalMsg.js
  packages/desktop-client/src/components/modals/GoCardlessInitialise.tsx
  packages/desktop-client/src/gocardless.js
  packages/desktop-client/src/hooks/useGoCardlessStatus.ts
  packages/loot-core/src/client/actions/account.ts
  packages/loot-core/src/client/state-types/modals.d.ts
  packages/loot-core/src/server/accounts/link.ts
  packages/loot-core/src/server/accounts/sync.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/server/server-config.ts
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/1361.md
Labels: ✅ Approved

#1363 spelling error in FixSplit.js
  packages/desktop-client/src/components/settings/FixSplits.js
  upcoming-release-notes/1363.md
Labels: ✅ Approved

#1329 Goals: Implement goals in Report Budget
  packages/desktop-client/src/components/budget/report/BudgetSummary.tsx
  packages/loot-core/src/server/budget/actions.ts
  packages/loot-core/src/server/budget/goaltemplates.ts
  upcoming-release-notes/1329.md
Labels: ✅ Approved

#1240 Further reduce bundle size by code splitting out pages that are only used on desktop/mobile
  packages/desktop-client/src/components/FinancesApp.tsx
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/Notifications.tsx
  packages/desktop-client/src/components/Titlebar.js
  packages/desktop-client/src/components/reports/index.tsx
  packages/desktop-client/src/components/responsive/index.tsx
  packages/desktop-client/src/components/responsive/narrow.ts
  packages/desktop-client/src/components/responsive/wide.ts
  packages/desktop-client/src/components/transactions/MobileTransaction.js
  packages/desktop-client/src/components/util/LoadComponent.tsx
  packages/desktop-client/src/fonts.scss
  packages/desktop-client/src/style.tsx
  packages/desktop-client/src/util/withThemeColor.tsx
  upcoming-release-notes/1240.md
Labels: ✅ Approved

#1362 Fix onExpose is not a function error
  packages/desktop-client/src/components/transactions/TransactionsTable.js
  upcoming-release-notes/1362.md
Labels: 🔍 Ready for Review, ✅ Approved

#1372 Add support for parsing TSV files using the CSV logic
  packages/desktop-client/src/components/accounts/Account.js
  packages/desktop-client/src/components/modals/ImportTransactions.js
  packages/loot-core/src/client/state-types/prefs.d.ts
  packages/loot-core/src/server/accounts/parse-file.ts
  upcoming-release-notes/1372.md
Labels: ✅ Approved

#1354 Scheduled transactions for the month to show up in Account's running balance
  packages/desktop-client/src/components/accounts/Account.js
  packages/desktop-client/src/components/transactions/TransactionList.js
  packages/desktop-client/src/components/transactions/TransactionsTable.js
  upcoming-release-notes/1354.md
Labels: ✅ Approved

#1374 Update the text of the comment posted when closing feature requests
  .github/workflows/issues-close-feature-requests.yml
  upcoming-release-notes/1374.md
Labels: ✅ Approved

#1367 Begin integrating support for themes
  packages/desktop-client/src/components/App.js
  packages/desktop-client/src/components/ThemeSelector.tsx
  packages/desktop-client/src/components/Titlebar.js
  packages/desktop-client/src/components/settings/Experimental.js
  packages/desktop-client/src/components/settings/Experimental.tsx
  packages/desktop-client/src/components/settings/Themes.js
  packages/desktop-client/src/components/settings/index.js
  packages/desktop-client/src/hooks/useFeatureFlag.ts
  packages/desktop-client/src/icons/v2/MoonStars.js
  packages/desktop-client/src/icons/v2/Sun.js
  packages/desktop-client/src/icons/v2/moon-stars.svg
  packages/desktop-client/src/icons/v2/sun.svg
  packages/desktop-client/src/style/colors.ts
  packages/desktop-client/src/style/index.ts
  packages/desktop-client/src/style/palette.ts
  packages/desktop-client/src/style/styles.ts
  packages/desktop-client/src/style/theme.tsx
  packages/desktop-client/src/style/themes/dark.ts
  packages/desktop-client/src/style/themes/development.ts
  packages/desktop-client/src/style/themes/light.ts
  packages/loot-core/src/client/state-types/prefs.d.ts
  packages/loot-core/src/server/main.ts
  upcoming-release-notes/1367.md
Labels: ✅ Approved

#1287 Add "not" checkbox for string filters
  packages/desktop-client/e2e/page-models/rules-page.js
  packages/desktop-client/src/components/ManageRules.js
  packages/desktop-client/src/components/common/Select.tsx
  packages/desktop-client/src/components/filters/FiltersMenu.js
  packages/desktop-client/src/components/modals/EditRule.js
  packages/loot-core/src/server/accounts/rules.ts
  packages/loot-core/src/server/accounts/transaction-rules.ts
  packages/loot-core/src/server/aql/compiler.ts
  packages/loot-core/src/shared/rules.ts
  upcoming-release-notes/1287.md
Labels: ✅ Approved

#1237 Storing start month in user prefs
  packages/desktop-client/src/components/budget/index.js
  upcoming-release-notes/1237.md
Labels: ✅ Approved

#1378 Update coloring of newly added icons
  packages/desktop-client/src/icons/v2/MoonStars.js
  packages/desktop-client/src/icons/v2/Sun.js
  upcoming-release-notes/1378.md
Labels: ✅ Approved

#1373 Add support for importing the first row of a CSV file without a header row
  packages/desktop-client/src/components/modals/ImportTransactions.js
  packages/loot-core/src/client/state-types/prefs.d.ts
  packages/loot-core/src/server/accounts/parse-file.ts
  upcoming-release-notes/1373.md
Labels: ✅ Approved

#1366 Move saveScrollWidth call to layout effect
  packages/desktop-client/src/components/table.tsx
  upcoming-release-notes/1366.md
Labels: ✅ Approved

#1380 Correct the width of StatusCell
  packages/desktop-client/src/components/transactions/TransactionsTable.js
  upcoming-release-notes/1380.md
Labels: ✅ Approved

#1385 Remove double scrollbar as the screen is big enough
  packages/desktop-client/src/components/FixedSizeList.js
  packages/desktop-client/src/style/styles.ts
  upcoming-release-notes/1385.md
Labels: ✅ Approved

#1342 Delete table navigator from rules page
  packages/desktop-client/src/components/ManageRules.js
  upcoming-release-notes/1342.md
Labels: ✅ Approved

#1390 Consistency improvements for <AnimatedLoading>
  packages/desktop-client/src/components/Notifications.tsx
  packages/desktop-client/src/components/accounts/Header.js
  packages/desktop-client/src/components/common/Button.tsx
  packages/desktop-client/src/components/common/Modal.tsx
  packages/desktop-client/src/icons/Loading.js
  upcoming-release-notes/1390.md
Labels: ✅ Approved

#1389 Exclude “isbetween” op from the filter UI
  packages/desktop-client/src/components/filters/FiltersMenu.js
  upcoming-release-notes/1389.md
Labels: ✅ Approved

#1391 Adapt the top level components to dark mode
  packages/desktop-client/public/index.html
  packages/desktop-client/src/components/App.js
  packages/desktop-client/src/components/AppBackground.js
  packages/desktop-client/src/components/Background.js
  packages/desktop-client/src/components/Background.tsx
  packages/desktop-client/src/components/BackgroundImage.tsx
  packages/desktop-client/src/components/DevelopmentTopBar.tsx
  packages/desktop-client/src/components/FatalError.js
  packages/desktop-client/src/components/FinancesApp.tsx
  packages/desktop-client/src/components/manager/ManagementApp.js
  packages/desktop-client/src/components/manager/bg.svg
  packages/desktop-client/src/style/palette.ts
  packages/desktop-client/src/style/themes/dark.ts
  packages/desktop-client/src/style/themes/development.ts
  packages/desktop-client/src/style/themes/light.ts
  upcoming-release-notes/1391.md
Labels: ✅ Approved

#1396 Improve messaging when the API fails to download a file
  packages/loot-core/src/server/api.ts
  packages/loot-core/src/shared/errors.ts
  upcoming-release-notes/1396.md
Labels: ✅ Approved

#1350 Add per-category button to fill budget cells, including Goal template support
  packages/desktop-client/src/components/budget/report/components.tsx
  packages/desktop-client/src/components/budget/rollover/rollover-components.tsx
  packages/loot-core/src/client/actions/queries.ts
  packages/loot-core/src/server/budget/actions.ts
  packages/loot-core/src/server/budget/app.ts
  packages/loot-core/src/server/budget/goaltemplates.ts
  packages/loot-core/src/server/budget/types/handlers.d.ts
  upcoming-release-notes/1350.md
Labels: ✅ Approved

#1400 Goals: fix leftover 1 cent in remainder goal
  packages/loot-core/src/server/budget/goaltemplates.ts
  upcoming-release-notes/1400.md
Labels: ✅ Approved

#1406 Fix Sorting/Balance interactions
  packages/desktop-client/src/components/accounts/Account.js
  packages/desktop-client/src/components/transactions/TransactionsTable.js
  upcoming-release-notes/1406.md
Labels: 🔍 Ready for Review, ✅ Approved

#1404 More typing improvements for Redux-related code
  packages/desktop-client/src/components/App.js
  packages/desktop-client/src/components/BankSyncStatus.js
  packages/desktop-client/src/components/FinancesApp.tsx
  packages/desktop-client/src/components/FloatableSidebar.js
  packages/desktop-client/src/components/LoggedInUser.js
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/SidebarWithData.js
  packages/desktop-client/src/components/Titlebar.js
  packages/desktop-client/src/components/UpdateNotification.js
  packages/desktop-client/src/components/accounts/AccountSyncCheck.js
  packages/desktop-client/src/components/accounts/MobileAccount.js
  packages/desktop-client/src/components/accounts/MobileAccounts.js
  packages/desktop-client/src/components/budget/DynamicBudgetTable.js
  packages/desktop-client/src/components/budget/MobileBudget.js
  packages/desktop-client/src/components/budget/MobileBudgetTable.js
  packages/desktop-client/src/components/budget/index.js
  packages/desktop-client/src/components/budget/misc.js
  packages/desktop-client/src/components/manager/BudgetList.js
  packages/desktop-client/src/components/manager/ConfigServer.js
  packages/desktop-client/src/components/manager/ManagementApp.js
  packages/desktop-client/src/components/manager/Modals.js
  packages/desktop-client/src/components/manager/WelcomeScreen.js
  packages/desktop-client/src/components/modals/EditField.js
  packages/desktop-client/src/components/payees/ManagePayeesWithData.js
  packages/desktop-client/src/components/payees/index.js
  packages/desktop-client/src/components/reports/NetWorth.js
  packages/desktop-client/src/components/reports/Overview.js
  packages/desktop-client/src/components/settings/Encryption.js
  packages/desktop-client/src/components/settings/Export.js
  packages/desktop-client/src/components/settings/Format.js
  packages/desktop-client/src/components/settings/Global.js
  packages/desktop-client/src/components/settings/Reset.js
  packages/desktop-client/src/components/settings/Themes.js
  packages/desktop-client/src/components/settings/index.js
  packages/desktop-client/src/hooks/index.js
  packages/desktop-client/src/hooks/useActions.ts
  packages/desktop-client/src/hooks/useSetThemeColor.ts
  packages/desktop-client/src/util/withThemeColor.tsx
  packages/loot-core/src/client/actions/account.ts
  packages/loot-core/src/client/actions/app.ts
  packages/loot-core/src/client/actions/backups.ts
  packages/loot-core/src/client/actions/budgets.ts
  packages/loot-core/src/client/actions/modals.ts
  packages/loot-core/src/client/actions/notifications.ts
  packages/loot-core/src/client/actions/prefs.ts
  packages/loot-core/src/client/actions/queries.ts
  packages/loot-core/src/client/actions/sync.ts
  packages/loot-core/src/client/actions/types.d.ts
  packages/loot-core/src/client/actions/user.ts
  upcoming-release-notes/1404.md
Labels: ✅ Approved

#1411 Fix typo in handle-feature-requests.js
  .github/actions/handle-feature-requests.js
  upcoming-release-notes/1411.md
Labels: ✅ Approved

#1410 Goals: fix remaining funds calculation
  packages/loot-core/src/server/budget/goaltemplates.ts
  upcoming-release-notes/1410.md
Labels: ✅ Approved

#1403 Goals: add flag to percent goals to use previous month income instead of this months
  packages/loot-core/src/server/budget/goal-template.pegjs
  packages/loot-core/src/server/budget/goaltemplates.ts
  upcoming-release-notes/1403.md
Labels: ✅ Approved

#1412 Add Indian numbering format
  packages/loot-core/src/shared/util.test.ts
  packages/loot-core/src/shared/util.ts
  upcoming-release-notes/1412.md
Labels: ✅ Approved

#1413 :recycle: moving P, useStableCallback, AnchorLink common components
  packages/desktop-client/src/components/FatalError.js
  packages/desktop-client/src/components/Titlebar.js
  packages/desktop-client/src/components/common.tsx
  packages/desktop-client/src/components/common/AnchorLink.tsx
  packages/desktop-client/src/components/common/Paragraph.tsx
  packages/desktop-client/src/components/gocardless/GoCardlessLink.js
  packages/desktop-client/src/components/manager/ImportActual.js
  packages/desktop-client/src/components/manager/ImportYNAB4.js
  packages/desktop-client/src/components/manager/ImportYNAB5.js
  packages/desktop-client/src/components/manager/WelcomeScreen.js
  packages/desktop-client/src/components/manager/subscribe/Bootstrap.tsx
  packages/desktop-client/src/components/modals/CloseAccount.js
  packages/desktop-client/src/components/modals/CreateAccount.js
  packages/desktop-client/src/components/modals/CreateEncryptionKey.js
  packages/desktop-client/src/components/modals/FixEncryptionKey.js
  packages/desktop-client/src/components/modals/GoCardlessExternalMsg.js
  packages/desktop-client/src/components/modals/MergeUnusedPayees.js
  packages/desktop-client/src/components/modals/PlaidExternalMsg.js
  packages/desktop-client/src/components/payees/index.js
  packages/desktop-client/src/components/reports/CashFlow.js
  packages/desktop-client/src/components/reports/NetWorth.js
  packages/desktop-client/src/components/schedules/DiscoverSchedules.js
  packages/desktop-client/src/components/schedules/PostsOfflineNotification.js
  packages/desktop-client/src/components/settings/FixSplits.js
  packages/desktop-client/src/hooks/useStableCallback.ts
  upcoming-release-notes/1413.md
Labels: ✅ Approved

#1186 chore: add more concrete types to `loot-core`
  packages/desktop-client/src/components/settings/Experimental.tsx
  packages/desktop-client/src/hooks/useFeatureFlag.ts
  packages/desktop-client/src/style/theme.tsx
  packages/loot-core/src/client/state-types/prefs.d.ts
  packages/loot-core/src/mocks/budget.ts
  packages/loot-core/src/server/accounts/parse-file.ts
  packages/loot-core/src/server/api.ts
  packages/loot-core/src/server/budget/actions.ts
  packages/loot-core/src/server/main.test.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/server/prefs.ts
  packages/loot-core/src/server/server-config.ts
  packages/loot-core/src/server/sheet.ts
  packages/loot-core/src/server/spreadsheet/globals.ts
  packages/loot-core/src/server/spreadsheet/spreadsheet.ts
  packages/loot-core/src/server/spreadsheet/util.ts
  packages/loot-core/src/server/sync/encoder.ts
  packages/loot-core/src/server/sync/index.ts
  packages/loot-core/src/shared/months.ts
  packages/loot-core/src/shared/util.ts
  packages/loot-core/src/types/prefs.d.ts
  upcoming-release-notes/1186.md
Labels: ✅ Approved

#1417 :bug: (electron) always show titlebar
  packages/desktop-electron/index.js
  upcoming-release-notes/1417.md
Labels: ✅ Approved

#1418 :recycle: (common) migrating to specific common component import paths
  packages/desktop-client/src/components/LoggedInUser.js
  packages/desktop-client/src/components/NotesButton.tsx
  packages/desktop-client/src/components/SidebarWithData.js
  packages/desktop-client/src/components/Titlebar.js
  packages/desktop-client/src/components/accounts/AccountSyncCheck.js
  packages/desktop-client/src/components/accounts/Header.js
  packages/desktop-client/src/components/accounts/MobileAccountDetails.js
  packages/desktop-client/src/components/accounts/MobileAccounts.js
  packages/desktop-client/src/components/accounts/Reconcile.js
  packages/desktop-client/src/components/autocomplete/Autocomplete.tsx
  packages/desktop-client/src/components/budget/misc.js
  packages/desktop-client/src/components/budget/report/BudgetSummary.tsx
  packages/desktop-client/src/components/budget/report/components.tsx
  packages/desktop-client/src/components/budget/rollover/BudgetSummary.tsx
  packages/desktop-client/src/components/budget/rollover/HoldTooltip.tsx
  packages/desktop-client/src/components/budget/rollover/TransferTooltip.tsx
  packages/desktop-client/src/components/budget/rollover/rollover-components.tsx
  packages/desktop-client/src/components/common.tsx
  packages/desktop-client/src/components/common/MenuTooltip.tsx
  packages/desktop-client/src/components/common/Stack.tsx
  packages/desktop-client/src/components/filters/FiltersMenu.js
  packages/desktop-client/src/components/filters/SavedFilters.js
  packages/desktop-client/src/components/manager/BudgetList.js
  packages/desktop-client/src/components/modals/CreateLocalAccount.js
  packages/desktop-client/src/components/modals/EditRule.js
  packages/desktop-client/src/components/modals/GoCardlessExternalMsg.js
  packages/desktop-client/src/components/payees/index.js
  packages/desktop-client/src/components/reports/CashFlow.js
  packages/desktop-client/src/components/reports/graphs/cash-flow-spreadsheet.tsx
  packages/desktop-client/src/components/reports/graphs/net-worth-spreadsheet.tsx
  packages/desktop-client/src/components/schedules/LinkSchedule.js
  packages/desktop-client/src/components/schedules/SchedulesTable.js
  packages/desktop-client/src/components/schedules/index.js
  packages/desktop-client/src/components/select/DateSelect.js
  packages/desktop-client/src/components/select/RecurringSchedulePicker.js
  packages/desktop-client/src/components/sidebar.js
  packages/desktop-client/src/components/table.tsx
  packages/desktop-client/src/components/tooltips.js
  packages/desktop-client/src/components/transactions/MobileTransaction.js
  packages/desktop-client/src/components/transactions/TransactionsTable.js
  packages/desktop-client/src/components/util/AmountInput.js
  upcoming-release-notes/1418.md
Labels: ✅ Approved

#1405 Port the settings components to TS
  packages/desktop-client/src/components/Page.tsx
  packages/desktop-client/src/components/common/Select.tsx
  packages/desktop-client/src/components/settings/Encryption.tsx
  packages/desktop-client/src/components/settings/Experimental.tsx
  packages/desktop-client/src/components/settings/Export.tsx
  packages/desktop-client/src/components/settings/FixSplits.tsx
  packages/desktop-client/src/components/settings/Format.tsx
  packages/desktop-client/src/components/settings/Global.tsx
  packages/desktop-client/src/components/settings/Reset.tsx
  packages/desktop-client/src/components/settings/Themes.tsx
  packages/desktop-client/src/components/settings/UI.tsx
  packages/desktop-client/src/components/settings/index.tsx
  packages/loot-core/src/client/actions/modals.ts
  packages/loot-core/src/client/actions/prefs.ts
  packages/loot-core/src/client/state-types/modals.d.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/server/sync/index.ts
  packages/loot-core/src/types/prefs.d.ts
  packages/loot-core/src/types/server-handlers.d.ts
  packages/loot-core/src/types/util.d.ts
  packages/loot-core/typings/window.d.ts
  upcoming-release-notes/1405.md
Labels: ✅ Approved

#1419 :recycle: (common) migrating to specific common component import paths pt2
  packages/desktop-client/src/components/AppBackground.js
  packages/desktop-client/src/components/FatalError.js
  packages/desktop-client/src/components/ManageRules.js
  packages/desktop-client/src/components/Notifications.tsx
  packages/desktop-client/src/components/Page.tsx
  packages/desktop-client/src/components/UpdateNotification.js
  packages/desktop-client/src/components/accounts/Reconcile.js
  packages/desktop-client/src/components/budget/MobileBudgetTable.js
  packages/desktop-client/src/components/budget/misc.js
  packages/desktop-client/src/components/common.tsx
  packages/desktop-client/src/components/gocardless/GoCardlessLink.js
  packages/desktop-client/src/components/manager/BudgetList.js
  packages/desktop-client/src/components/manager/DeleteFile.js
  packages/desktop-client/src/components/manager/Import.js
  packages/desktop-client/src/components/manager/ImportActual.js
  packages/desktop-client/src/components/manager/ImportYNAB4.js
  packages/desktop-client/src/components/manager/ImportYNAB5.js
  packages/desktop-client/src/components/modals/BudgetSummary.js
  packages/desktop-client/src/components/modals/ConfirmCategoryDelete.js
  packages/desktop-client/src/components/modals/CreateAccount.js
  packages/desktop-client/src/components/modals/CreateEncryptionKey.js
  packages/desktop-client/src/components/modals/EditField.js
  packages/desktop-client/src/components/modals/FixEncryptionKey.js
  packages/desktop-client/src/components/modals/ImportTransactions.js
  packages/desktop-client/src/components/modals/LoadBackup.js
  packages/desktop-client/src/components/modals/ManageRulesModal.js
  packages/desktop-client/src/components/modals/MergeUnusedPayees.js
  packages/desktop-client/src/components/modals/PlaidExternalMsg.js
  packages/desktop-client/src/components/modals/SelectLinkedAccounts.js
  packages/desktop-client/src/components/reports/Change.js
  packages/desktop-client/src/components/reports/DateRange.js
  packages/desktop-client/src/components/reports/Overview.js
  packages/desktop-client/src/components/schedules/DiscoverSchedules.js
  packages/desktop-client/src/components/schedules/EditSchedule.js
  packages/desktop-client/src/components/schedules/PostsOfflineNotification.js
  packages/desktop-client/src/components/settings/Experimental.tsx
  packages/desktop-client/src/components/settings/UI.tsx
  packages/desktop-client/src/components/transactions/SelectedTransactions.js
  packages/desktop-client/src/components/util/LoadComponent.tsx
  upcoming-release-notes/1419.md
Labels: 🔍 Ready for Review

#1420 :recycle: (common) migrating to specific common component import paths pt3
  packages/desktop-client/src/components/BankSyncStatus.js
  packages/desktop-client/src/components/FinancesApp.tsx
  packages/desktop-client/src/components/FixedSizeList.js
  packages/desktop-client/src/components/FloatableSidebar.js
  packages/desktop-client/src/components/MobileWebMessage.js
  packages/desktop-client/src/components/PrivacyFilter.tsx
  packages/desktop-client/src/components/ThemeSelector.tsx
  packages/desktop-client/src/components/Titlebar.js
  packages/desktop-client/src/components/accounts/Account.js
  packages/desktop-client/src/components/accounts/Balance.js
  packages/desktop-client/src/components/autocomplete/AccountAutocomplete.js
  packages/desktop-client/src/components/autocomplete/CategorySelect.tsx
  packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.js
  packages/desktop-client/src/components/autocomplete/SavedFilterAutocomplete.js
  packages/desktop-client/src/components/budget/BalanceWithCarryover.tsx
  packages/desktop-client/src/components/budget/BudgetSummaries.js
  packages/desktop-client/src/components/budget/DynamicBudgetTable.js
  packages/desktop-client/src/components/budget/MobileBudget.js
  packages/desktop-client/src/components/budget/MobileTable.js
  packages/desktop-client/src/components/budget/MonthCountSelector.js
  packages/desktop-client/src/components/budget/MonthPicker.js
  packages/desktop-client/src/components/budget/index.js
  packages/desktop-client/src/components/common.tsx
  packages/desktop-client/src/components/forms.tsx
  packages/desktop-client/src/components/manager/ConfigServer.js
  packages/desktop-client/src/components/manager/ManagementApp.js
  packages/desktop-client/src/components/manager/Modals.js
  packages/desktop-client/src/components/manager/ServerURL.js
  packages/desktop-client/src/components/manager/WelcomeScreen.js
  packages/desktop-client/src/components/manager/subscribe/Bootstrap.tsx
  packages/desktop-client/src/components/manager/subscribe/ChangePassword.tsx
  packages/desktop-client/src/components/manager/subscribe/ConfirmPasswordForm.tsx
  packages/desktop-client/src/components/manager/subscribe/Error.tsx
  packages/desktop-client/src/components/manager/subscribe/Login.tsx
  packages/desktop-client/src/components/manager/subscribe/common.tsx
  packages/desktop-client/src/components/reports/Container.tsx
  packages/desktop-client/src/components/reports/Header.js
  packages/desktop-client/src/components/reports/index.tsx
  packages/desktop-client/src/components/schedules/StatusBadge.js
  packages/desktop-client/src/components/settings/Encryption.tsx
  packages/desktop-client/src/components/settings/Export.tsx
  packages/desktop-client/src/components/settings/FixSplits.tsx
  packages/desktop-client/src/components/settings/Format.tsx
  packages/desktop-client/src/components/settings/Global.tsx
  packages/desktop-client/src/components/settings/Reset.tsx
  packages/desktop-client/src/components/settings/Themes.tsx
  packages/desktop-client/src/components/settings/index.tsx
  packages/desktop-client/src/components/sort.js
  packages/desktop-client/src/components/util/DisplayId.js
  packages/desktop-client/src/components/util/GenericInput.js
  upcoming-release-notes/1418.md
  upcoming-release-notes/1420.md
Labels: ✅ Approved

#1422 ♻️ (common) migrating to specific common component import paths pt4
  packages/desktop-client/src/components/DevelopmentTopBar.tsx
  packages/desktop-client/src/components/FatalError.js
  packages/desktop-client/src/components/ManageRules.js
  packages/desktop-client/src/components/Notifications.tsx
  packages/desktop-client/src/components/Titlebar.js
  packages/desktop-client/src/components/accounts/AccountSyncCheck.js
  packages/desktop-client/src/components/common.tsx
  packages/desktop-client/src/components/common/ButtonLink.tsx
  packages/desktop-client/src/components/common/ExternalLink.tsx
  packages/desktop-client/src/components/manager/ImportYNAB5.js
  packages/desktop-client/src/components/manager/WelcomeScreen.js
  packages/desktop-client/src/components/manager/subscribe/Bootstrap.tsx
  packages/desktop-client/src/components/modals/CreateAccount.js
  packages/desktop-client/src/components/modals/CreateEncryptionKey.js
  packages/desktop-client/src/components/modals/CreateLocalAccount.js
  packages/desktop-client/src/components/modals/FixEncryptionKey.js
  packages/desktop-client/src/components/modals/GoCardlessExternalMsg.js
  packages/desktop-client/src/components/modals/GoCardlessInitialise.tsx
  packages/desktop-client/src/components/reports/Header.js
  packages/desktop-client/src/components/settings/Encryption.tsx
  packages/desktop-client/src/components/settings/index.tsx
  upcoming-release-notes/1422.md
Labels: ✅ Approved

#1421 :bug: fix side-nav collapse/pin icon color
  packages/desktop-client/src/components/sidebar.js
  upcoming-release-notes/1421.md
Labels: ✅ Approved

#1423 :bug: fix number formatter not listening to state changes
  packages/desktop-client/src/components/spreadsheet/CellValue.tsx
  packages/desktop-client/src/components/spreadsheet/format.ts
  packages/loot-core/package.json
  packages/loot-core/src/client/selectors.ts
  packages/loot-core/src/shared/util.ts
  upcoming-release-notes/1423.md
  yarn.lock
Labels: ✅ Approved

#1408 Search Bar Changes
  packages/desktop-client/src/components/ManageRules.js
  packages/desktop-client/src/components/accounts/Header.js
  packages/desktop-client/src/components/common/Input.tsx
  packages/desktop-client/src/components/common/InputWithContent.tsx
  packages/desktop-client/src/components/common/Search.tsx
  packages/desktop-client/src/components/payees/index.js
  packages/desktop-client/src/components/schedules/index.js
  packages/desktop-client/src/components/table.tsx
  packages/desktop-client/src/style/themes/dark.ts
  packages/desktop-client/src/style/themes/light.ts
  upcoming-release-notes/1408.md
Labels: ✅ Approved

#1429 Include the schedule name when filtering schedules
  packages/desktop-client/src/components/schedules/SchedulesTable.js
  upcoming-release-notes/1429.md
Labels: ✅ Approved

#1430 Remove no-op applyFilter call
  packages/desktop-client/src/components/payees/index.js
  upcoming-release-notes/1430.md
Labels: 🔍 Ready for Review, ✅ Approved

#1434 :bug: (crdt) export Clock as a type to fix warning
  packages/crdt/package.json
  packages/crdt/src/crdt/index.ts
  packages/crdt/src/main.ts
  upcoming-release-notes/1434.md
Labels: ✅ Approved

#1433 :bug: fix incorrect state slice usage
  packages/desktop-client/src/components/LoggedInUser.js
  upcoming-release-notes/1433.md
Labels: ✅ Approved

#1435 Update to the latest version of the size compare action
  .github/workflows/size-compare.yml
  upcoming-release-notes/1435.md
Labels: 🔍 Ready for Review
