Repository actualbudget/actual, pull requests merged in 2023-02, with the labels that each got.

#570 Use navigitor.userAgent to determine isMobile
  packages/desktop-client/src/components/FinancesApp.js
  packages/desktop-client/src/util.js
Labels: ✅ Approved

#609 :arrow_up: upgrade node-fetch to ^2.6.9
  packages/api/package.json
  packages/desktop-electron/package.json
  packages/loot-core/package.json
  yarn.lock
Labels: ✅ Approved

#610 :bookmark: (api) 4.1.6: node-fetch upgrade
  packages/api/package.json
Labels: ✅ Approved

#355 Schedule Editor: Keep payee list open while toggling transfer payees focus
  packages/loot-design/src/components/PayeeAutocomplete.js
Labels: enhancement, schedules, user-interface, ✅ Approved

#591 Allow libofx to handle decoding imported files
  packages/loot-core/src/mocks/files/8859-1.qfx
  packages/loot-core/src/server/accounts/__snapshots__/parse-file.test.js.snap
  packages/loot-core/src/server/accounts/parse-file.js
  packages/loot-core/src/server/accounts/parse-file.test.js
  packages/node-libofx/ffi.js
Labels: ✅ Approved

#590 Add support for filtering the schedules table
  packages/desktop-client/src/components/schedules/LinkSchedule.js
  packages/desktop-client/src/components/schedules/SchedulesTable.js
  packages/desktop-client/src/components/schedules/index.js
  packages/loot-design/src/components/common.js
Labels: ✅ Approved

#617 Improve behavior of deleted payees/categories/accounts in rules
  packages/desktop-client/src/components/ManageRules.js
Labels: ✅ Approved

#600 Add a warning when SharedArrayBuffer is not available
  packages/desktop-client/src/browser-server.js
  packages/desktop-client/src/components/FatalError.js
Labels: ✅ Approved

#620 Fixes editing closed account names issue #616
  packages/desktop-client/src/components/accounts/Account.js
Labels: ✅ Approved

#629 Fix form submission on TransferTooltip when pressing enter
  packages/loot-design/src/components/budget/rollover/TransferTooltip.js
Labels: ✅ Approved

#630 Skip the “Starting Balance” transaction if the balance is 0
  packages/loot-core/src/server/main.js
Labels: ✅ Approved

#632 Fix default value of “Move to a category”
  packages/loot-design/src/components/budget/rollover/BudgetSummary.js
Labels: ✅ Approved

#633 Removed reference to blog
  packages/desktop-client/src/components/UpdateNotification.js
  packages/desktop-client/src/components/manager/ManagementApp.js
Labels: ✅ Approved

#624 Fatal error dialog update to reflect open source.
  packages/desktop-client/src/components/FatalError.js
Labels: ✅ Approved

#635 Removing dead links
  packages/loot-core/src/client/upgrade-notifications.js
  packages/loot-design/src/components/modals/PlaidExternalMsg.js
Labels: ✅ Approved

#627 Remove all references to help@actualbudget.com
  packages/desktop-client/src/components/accounts/AccountSyncCheck.js
  packages/desktop-client/src/components/tutorial/Final.js
  packages/loot-core/src/client/actions/budgets.js
  packages/loot-core/src/platform/client/fetch/index.browser.js
  packages/loot-core/src/server/main.js
  packages/loot-core/src/shared/rules.js
Labels: ✅ Approved

#636 :bookmark: (23.2.5) security focused release
  packages/desktop-client/package.json
Labels: ✅ Approved

#638 Allow the Netlify frontend to connect to arbitrary servers
  packages/desktop-client/public/_headers
Labels: ✅ Approved

#639 Move desktop-client deps to devDeps
  packages/desktop-client/package.json
Labels: ✅ Approved

#640 Fix coloring of the “Split Transaction” button in the category picker
  packages/loot-design/src/components/CategorySelect.js
  packages/loot-design/src/svg/v0/Delete.js
  packages/loot-design/src/svg/v0/Delete.svg
  packages/loot-design/src/svg/v0/Merge.js
  packages/loot-design/src/svg/v0/Split.js
  packages/loot-design/src/svg/v0/merge.svg
  packages/loot-design/src/svg/v0/split.svg
Labels: ✅ Approved

#641 Fix prop name for button to enable e2ee
  packages/desktop-client/src/components/settings/Encryption.js
Labels: ✅ Approved

#644 Allow bypassing SharedArrayBuffer override
  packages/desktop-client/src/browser-preload.browser.js
  packages/desktop-client/src/browser-server.js
  packages/desktop-client/src/components/FatalError.js
  packages/loot-core/src/client/actions/budgets.js
Labels: ✅ Approved

#646 Allow editing filters
  packages/desktop-client/src/components/ManageRules.js
  packages/desktop-client/src/components/accounts/Account.js
  packages/desktop-client/src/components/accounts/Filters.js
Labels: ✅ Approved

#588 Updates to the template/goal feature
  packages/desktop-client/src/components/Notifications.js
  packages/loot-core/jest.config.js
  packages/loot-core/jest.web.config.js
  packages/loot-core/package.json
  packages/loot-core/src/client/actions/queries.js
  packages/loot-core/src/server/budget/goal-template.pegjs
  packages/loot-core/src/server/budget/goaltemplates.js
  packages/loot-core/webpack/webpack.browser.config.js
  packages/loot-core/webpack/webpack.desktop.config.js
  yarn.lock
Labels: ✅ Approved

#648 Block enabling e2e encryption when the crypto API is unavailable
  packages/desktop-client/src/components/settings/Encryption.js
Labels: ✅ Approved

#654 Delete loot-design/README.md
  packages/loot-design/README.md
Labels: ✅ Approved

#653 :pencil: updated CONTRIBUTING guidelines
  CONTRIBUTING.md
Labels: ✅ Approved

#657 Better explain the process for importing an exported file
  packages/desktop-client/src/components/settings/Export.js
Labels: ✅ Approved

#660 Stop editing when clicking on blank areas of tables
  packages/loot-design/src/components/table.js
Labels: ✅ Approved

#663 :fire: remove closed-source subscription notification code
  packages/loot-core/src/server/main.js
Labels: ✅ Approved

#659 Improve handling of the undo/redo shortcuts
  packages/desktop-client/src/browser-preload.browser.js
  packages/desktop-client/src/components/accounts/TransactionsTable.js
Labels: ✅ Approved

#666 :pencil: add demo image to the README
  README.md
  demo.png
Labels: ✅ Approved

#671 Log more debugging information for an invalid-schema sync error
  packages/loot-core/src/client/shared-listeners.js
  packages/loot-core/src/server/spreadsheet/spreadsheet.js
  packages/loot-core/src/server/sync/index.js
Labels: ✅ Approved

#683 :arrow_up: upgrade yarn to v3.4.1 (latest stable)
  .yarn/releases/yarn-3.2.0.cjs
  .yarn/releases/yarn-3.4.1.cjs
  .yarnrc.yml
  package.json
  yarn.lock
Labels: ✅ Approved

#684 :heavy_plus_sign: add interactive-tools yarn plugin
  .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
  .yarnrc.yml
Labels: ✅ Approved

#675 Don’t force user to re-enter password after changing it
  packages/desktop-client/src/components/manager/subscribe/ChangePassword.js
Labels: ✅ Approved

#674 Make the “Not logged in” warning a button
  packages/desktop-client/src/components/LoggedInUser.js
Labels: ✅ Approved

#678 Fix error cases in displaying filters/rules
  packages/desktop-client/src/components/ManageRules.js
  packages/desktop-client/src/components/accounts/Filters.js
  packages/loot-core/src/shared/rules.js
Labels: ✅ Approved

#464 Updates to the @actual-budget/api package
  .github/workflows/build.yml
  packages/api/index.js
  packages/api/methods.js
  packages/api/package.json
  packages/loot-core/src/client/actions/budgets.js
  packages/loot-core/src/server/api.js
  packages/loot-core/src/server/main.js
  packages/loot-core/src/shared/errors.js
  packages/loot-core/webpack/webpack.api.config.js
Labels: 🔍 Ready for Review

#689 Don’t run linting while building in CI
  packages/desktop-client/config/webpack.config.js
Labels: ✅ Approved

#681 Don’t post messages to the worker until it is ready
  packages/loot-core/src/platform/client/fetch/index.browser.js
Labels: ✅ Approved

#692 :bug: (import) date formats supporting digits without leading zeros
  packages/loot-design/src/components/modals/ImportTransactions.js
  packages/loot-design/src/components/modals/ImportTransactions.test.js
Labels: ✅ Approved

#694 :white_check_mark: (e2e) adding e2e tests for schedules page
  packages/desktop-client/e2e/page-models/navigation.js
  packages/desktop-client/e2e/page-models/schedules-page.js
  packages/desktop-client/e2e/schedules.test.js
  packages/desktop-client/src/components/schedules/EditSchedule.js
  packages/desktop-client/src/components/schedules/SchedulesTable.js
  packages/desktop-client/src/components/util/AmountInput.js
  packages/loot-design/src/components/common.js
  packages/loot-design/src/components/forms.js
Labels: ✅ Approved

#693 Add button and 'esc' shortcut to clear transaction filter
  packages/desktop-client/src/components/accounts/Account.js
Labels: ✅ Approved

#695 :white_check_mark: (e2e) adding e2e tests for accounts: creating & closing
  packages/desktop-client/e2e/accounts.test.js
  packages/desktop-client/e2e/page-models/account-page.js
  packages/desktop-client/e2e/page-models/close-account-modal.js
  packages/desktop-client/e2e/page-models/navigation.js
  packages/desktop-client/e2e/page-models/reports-page.js
  packages/desktop-client/e2e/page-models/rules-page.js
  packages/desktop-client/e2e/page-models/schedules-page.js
  packages/desktop-client/e2e/page-models/settings-page.js
  packages/desktop-client/e2e/reports.test.js
  packages/desktop-client/e2e/rules.test.js
  packages/desktop-client/e2e/settings.test.js
  packages/desktop-client/src/components/ManageRules.js
  packages/desktop-client/src/components/accounts/Account.js
  packages/desktop-client/src/components/modals/EditRule.js
  packages/desktop-client/src/components/reports/Overview.js
  packages/desktop-client/src/components/reports/index.js
  packages/loot-design/src/components/Stack.js
Labels: ✅ Approved

#668 Adds delay before note is displayed on hover. Solves issue #658.
  packages/loot-design/src/components/NotesButton.js
Labels: ✅ Approved

#704 :fire: remove unused component library code
  packages/loot-design/manifest.json
  packages/loot-design/public/favicon.ico
  packages/loot-design/public/img/logo.svg
  packages/loot-design/public/index.html
  packages/loot-design/src/components/Autocomplete.usage.js
  packages/loot-design/src/components/DateSelect.usage.js
  packages/loot-design/src/components/RecurringSchedulePicker.usage.js
  packages/loot-design/src/components/budget/index.usage.js
  packages/loot-design/src/components/common.usage.js
  packages/loot-design/src/components/icons.usage.js
  packages/loot-design/src/components/manager/BudgetList.usage.js
  packages/loot-design/src/components/manager/DeleteFile.usage.js
  packages/loot-design/src/components/manager/Import.usage.js
  packages/loot-design/src/components/modals/CloseAccount.usage.js
  packages/loot-design/src/components/modals/ConfigureLinkedAccounts.usage.js
  packages/loot-design/src/components/modals/CreateLocalAccount.usage.js
  packages/loot-design/src/components/modals/ImportTransactions.usage.js
  packages/loot-design/src/components/modals/LoadBackup.usage.js
  packages/loot-design/src/components/modals/PlaidExternalMsg.usage.js
  packages/loot-design/src/components/modals/SelectLinkedAccounts.usage.js
  packages/loot-design/src/components/payees.usage.js
  packages/loot-design/src/components/sidebar.usage.js
  packages/loot-design/src/components/table.usage.js
  packages/loot-design/src/guide/components.js
  packages/loot-design/src/guide/document.js
  packages/loot-design/src/index.js
Labels: ✅ Approved

#703 :fire: removing lively from MonthPicker
  packages/loot-design/src/components/budget/index.js
Labels: ✅ Approved

#697 :building_construction: moving back to create-react-app
  .eslintrc.js
  package.json
  packages/desktop-client/.babelrc
  packages/desktop-client/bin/build-browser
  packages/desktop-client/bin/watch-browser
  packages/desktop-client/config-overrides.js
  packages/desktop-client/config/env.js
  packages/desktop-client/config/getHttpsConfig.js
  packages/desktop-client/config/jest/cssTransform.js
  packages/desktop-client/config/jest/fileTransform.js
  packages/desktop-client/config/paths.js
  packages/desktop-client/config/webpack.config.js
  packages/desktop-client/config/webpackDevServer.config.js
  packages/desktop-client/jest.config.js
  packages/desktop-client/package.json
  packages/desktop-client/scripts/build.js
  packages/desktop-client/scripts/start.js
  packages/desktop-client/scripts/test.js
  packages/desktop-client/src/browser-preload.browser.js
  packages/desktop-client/src/browser-server.js
  packages/desktop-client/src/components/accounts/TransactionsTable.test.js
  packages/desktop-client/src/components/accounts/__snapshots__/TransactionsTable.test.js.snap
  packages/desktop-client/src/setupTests.js
  packages/desktop-electron/index.js
  packages/desktop-electron/package.json
  packages/loot-core/bin/build-browser
  packages/loot-core/jest.config.js
  packages/loot-core/jest.web.config.js
  packages/loot-core/package.json
  packages/loot-core/src/client/platform.js
  packages/loot-core/src/platform/client/fetch/__mocks__/index.web.js
  packages/loot-core/src/platform/client/fetch/index.browser.js
  packages/loot-core/src/platform/client/fetch/index.testing.js
  packages/loot-core/src/platform/server/fs/index.web.js
  packages/loot-core/src/server/main.js
  packages/loot-core/src/server/mutators.js
  packages/loot-core/src/server/prefs.js
  packages/loot-core/src/server/sheet.js
  packages/loot-core/src/server/sync/index.js
  packages/loot-design/package.json
  packages/loot-design/src/components/budget/report/BudgetSummary.js
  packages/loot-design/src/components/budget/report/components.js
  packages/loot-design/src/components/budget/rollover/BudgetSummary.js
  packages/loot-design/src/components/budget/rollover/rollover-components.js
  yarn.lock
Labels: ✅ Approved

#707 Fix check for crypto.subtle
  packages/desktop-client/src/components/settings/Encryption.js
Labels: ✅ Approved

#705 Don’t allow bulk editing to set a field to null
  packages/loot-design/src/components/modals/EditField.js
Labels: ✅ Approved

#709 :fire: refactor MonthPicker and remove ElementQuery
  packages/loot-design/src/components/ElementQuery.js
  packages/loot-design/src/components/budget/index.js
Labels: ✅ Approved

#710 :fire: remove more dead code
  packages/desktop-client/src/components/Box.js
  packages/desktop-client/src/components/SpreadsheetInterface.js
  packages/desktop-client/src/components/manager/GraphBackground.js
  packages/desktop-client/src/components/manager/GraphBackground.svg
  packages/desktop-client/src/components/manager/GraphBackground2.js
  packages/desktop-client/src/components/manager/GraphBackground3.js
  packages/loot-design/src/components/table.js
Labels: ✅ Approved

#706 Allow rendering a schedule in <Value />
  packages/desktop-client/e2e/page-models/rules-page.js
  packages/desktop-client/e2e/rules.test.js
  packages/desktop-client/e2e/schedules.test.js
  packages/desktop-client/src/components/ManageRules.js
Labels: ✅ Approved

#676 Update the Bootstrap page to be more welcoming
  packages/desktop-client/src/components/manager/subscribe/Bootstrap.js
Labels: ✅ Approved

#702 Remove/dedupe/upgrade several dependencies
  package.json
  packages/desktop-client/package.json
  packages/desktop-client/src/components/budget/MobileBudgetTable.js
  packages/loot-core/package.json
  packages/loot-core/src/client/platform.js
  packages/loot-core/src/server/accounts/__snapshots__/transaction-rules.test.js.snap
  packages/loot-core/src/server/accounts/transaction-rules.test.js
  packages/loot-design/jest.config.js
  packages/loot-design/package.json
  packages/loot-design/src/components/sidebar.js
  packages/loot-design/src/style.js
  yarn.lock
Labels: ✅ Approved

#712 Add a missing space to the fatal error message
  packages/desktop-client/src/components/FatalError.js
Labels: ✅ Approved

#713 :fire: removed usage of babel-preset-jwl-app
  packages/loot-core/.babelrc
  packages/loot-core/package.json
  packages/loot-core/webpack/webpack.browser.config.js
  packages/loot-design/babel.config.json
  packages/loot-design/package.json
  yarn.lock
Labels: ✅ Approved

#714 Upgrade better-sqlite3 to the latest version
  packages/api/package.json
  packages/loot-core/package.json
  packages/loot-core/src/server/accounts/transaction-rules.js
  yarn.lock
Labels: ✅ Approved

#680 Intelligently adjust field for newly added action
  packages/desktop-client/src/components/modals/EditRule.js
  packages/loot-core/src/shared/rules.js
Labels: ✅ Approved
