Repository actualbudget/actual, pull requests merged in 2023-01, with the labels that each got.

#118 Strip down and refactor package scripts
  bin/package
  packages/desktop-electron/bin/update-client
  packages/desktop-electron/package.json
Labels: needs-testing, waiting-review

#231 Update sidebar to expose rules/payees as pages rather than modals
  packages/desktop-client/src/components/FinancesApp.js
  packages/desktop-client/src/components/ManageRules.js
  packages/desktop-client/src/components/ManageRulesPage.js
  packages/desktop-client/src/components/Modals.js
  packages/desktop-client/src/components/accounts/Account.js
  packages/desktop-client/src/components/accounts/Filters.js
  packages/desktop-client/src/components/accounts/TransactionList.js
  packages/desktop-client/src/components/modals/ManageRulesModal.js
  packages/desktop-client/src/components/payees/ManagePayeesPage.js
  packages/desktop-client/src/components/payees/ManagePayeesWithData.js
  packages/desktop-client/src/components/schedules/DiscoverSchedules.js
  packages/desktop-electron/index.js
  packages/desktop-electron/menu.js
  packages/loot-design/src/components/common.js
  packages/loot-design/src/components/payees.js
  packages/loot-design/src/components/sidebar.js
  packages/loot-design/src/components/table.js
  packages/loot-design/src/components/tooltips.js
Labels: needs-testing, user-interface, waiting-review

#418 fix: some react warnings
  packages/loot-design/src/components/budget/rollover/rollover-components.js
  packages/loot-design/src/components/common.js
Labels: waiting-review

#428 chore: remove more unused variables
  packages/loot-core/package.json
  packages/loot-core/src/client/actions/budgets.js
  packages/loot-core/src/client/actions/queries.js
  packages/loot-core/src/client/actions/user.js
  packages/loot-core/src/client/query-helpers.test.js
  packages/loot-core/src/client/query-hooks.js
  packages/loot-core/src/client/shared-listeners.js
  packages/loot-core/src/mocks/budget.js
  packages/loot-core/src/platform/client/undo/index.web.js
  packages/loot-core/src/platform/server/asyncStorage/index.web.js
  packages/loot-core/src/platform/server/connection/index.web.js
  packages/loot-core/src/platform/server/indexeddb/index.web.js
  packages/loot-core/src/platform/server/sqlite/index.web.test.js
  packages/loot-core/src/server/accounts/parse-file.test.js
  packages/loot-core/src/server/accounts/rules.js
  packages/loot-core/src/server/accounts/rules.test.js
  packages/loot-core/src/server/accounts/sync.js
  packages/loot-core/src/server/accounts/sync.test.js
  packages/loot-core/src/server/accounts/transaction-rules.js
  packages/loot-core/src/server/accounts/transfer.js
  packages/loot-core/src/server/aql/compiler.js
  packages/loot-core/src/server/aql/schema/executors.js
  packages/loot-core/src/server/aql/schema/index.js
  packages/loot-core/src/server/budget/actions.js
  packages/loot-core/src/server/budget/base.js
  packages/loot-core/src/server/cloud-storage.js
  packages/loot-core/src/server/crdt/merkle.test.js
  packages/loot-core/src/server/db/index.js
  packages/loot-core/src/server/main.js
  packages/loot-core/src/server/main.test.js
  packages/loot-core/src/server/post.js
  packages/loot-core/src/server/schedules/app.js
  packages/loot-core/src/server/schedules/find-schedules.js
  packages/loot-core/src/server/spreadsheet/new/compiler.js
  packages/loot-core/src/server/spreadsheet/new/parser.js
  packages/loot-core/src/server/spreadsheet/new/sqlgen.js
  packages/loot-core/src/server/spreadsheet/spreadsheet.test.js
  packages/loot-core/src/server/spreadsheet/sqlinterp.test.js
  packages/loot-core/src/server/spreadsheet/tests/data-propagation.js
  packages/loot-core/src/server/spreadsheet/usage.js
  packages/loot-core/src/server/spreadsheet/util.js
  packages/loot-core/src/server/sync/index.js
  packages/loot-core/src/server/sync/migrate.js
  packages/loot-core/src/server/sync/sync.test.js
  packages/loot-core/src/server/tests/mockSyncServer.js
  packages/loot-core/src/shared/arithmetic.js
  packages/loot-core/src/shared/async.test.js
  yarn.lock
Labels: waiting-review

#430 fix: select date filtering by month #406 :ambulance:
  packages/loot-design/src/components/DateSelect.js
Labels: waiting-review

#439 docs: add netlify as sponsors to README
  README.md
Labels: waiting-review

#437 chore: remove unsed vars & cleanups
  packages/desktop-client/src/components/LoggedInUser.js
  packages/loot-core/src/server/aql/compiler.js
  packages/loot-core/src/server/spreadsheet/__snapshots__/spreadsheet.test.js.snap
  packages/loot-core/src/server/spreadsheet/spreadsheet.js
  packages/loot-core/src/server/spreadsheet/spreadsheet.test.js
  packages/loot-design/src/svg/AnimatedLoading.mobile.js
  packages/loot-design/src/svg/AnimatedLoading.web.js
Labels: waiting-review

#453 :speech_balloon: change misleading automatic bug-report text
  packages/loot-core/src/client/shared-listeners.js
Labels: waiting-review

#447 :bug: make build-browser, watch-browser commands use desktop-client vers
  packages/desktop-client/bin/build-browser
  packages/desktop-client/bin/watch-browser
Labels: waiting-review

#465 :fire: delete unused file: wtftags
  packages/desktop-client/src/wtftags.js
Labels: waiting-review

#265 Allow enabling end-to-end encryption again
  packages/desktop-client/src/components/modals/CreateEncryptionKey.js
  packages/desktop-client/src/components/settings/Encryption.js
Labels: enhancement, needs-testing

#452 :construction_worker: improving playwright install speed
  .github/workflows/e2e-test.yml
Labels: waiting-review

#459 Move the “…” menu to the budget name
  packages/desktop-client/src/components/SidebarWithData.js
  packages/loot-design/src/components/sidebar.js
Labels: waiting-review

#469 :rotating_light: enabling no-unused-vars eslint rule
  .eslintrc.js
  packages/desktop-client/src/components/MobileWebMessage.js
  packages/desktop-client/src/components/SyncRefresh.js
  packages/desktop-client/src/components/Titlebar.js
  packages/desktop-client/src/components/accounts/MobileAccount.js
  packages/desktop-client/src/components/accounts/MobileAccounts.js
  packages/desktop-client/src/components/accounts/MobileTransaction.js
  packages/desktop-client/src/components/budget/MobileBudget.js
  packages/desktop-client/src/components/budget/MobileBudgetTable.js
  packages/desktop-client/src/components/reports/graphs/NetWorthGraph.js
  packages/desktop-client/src/components/settings/UI.js
  packages/loot-core/src/platform/exceptions/index.web.js
  packages/loot-design/src/components/common.js
  packages/loot-design/src/components/sidebar.js
  packages/loot-design/src/setupTests.js
Labels: waiting-review

#472 :construction_worker: disable failing electron builds
  .github/workflows/build.yml
Labels: waiting-review

#467 Add an “Experimental Features” section in the settings
  packages/desktop-client/src/components/settings/Encryption.js
  packages/desktop-client/src/components/settings/Experimental.js
  packages/desktop-client/src/components/settings/Export.js
  packages/desktop-client/src/components/settings/FixSplits.js
  packages/desktop-client/src/components/settings/Reset.js
  packages/desktop-client/src/components/settings/UI.js
  packages/desktop-client/src/components/settings/index.js
Labels: 🔍 Ready for Review

#486 Fix TypeScript warning about too many files
  tsconfig.json
Labels: ✅ Approved

#455 Move Settings to the sidebar
  packages/desktop-client/src/components/SidebarWithData.js
  packages/loot-design/src/components/sidebar.js
Labels: 🔍 Ready for Review

#489 Fix “Repair split transactions” button being missing
  packages/desktop-client/src/components/settings/FixSplits.js
Labels: ✅ Approved

#88 Fix some YNAB4 importer bugs
  packages/import-ynab4/importer.js
Labels: bug, needs-testing, importers, 🔍 Ready for Review

#482 [Feature] Add option to control the "cleared state" in Rules
  packages/desktop-client/src/components/accounts/TransactionList.js
  packages/desktop-client/src/components/modals/EditRule.js
  packages/desktop-client/src/components/util/GenericInput.js
  packages/loot-core/src/shared/rules.js
Labels: ✅ Approved

#490 :bug: (ynab4) transaction cleared state in imports
  packages/import-ynab4/importer.js
Labels: needs-testing, ✅ Approved

#569 [Feature] List of categories in transfer money dialog
  packages/loot-design/src/components/budget/rollover/TransferTooltip.js
Labels: ✅ Approved

#571 opens the category/payee/account lists on focus
  packages/desktop-client/src/components/util/GenericInput.js
Labels: 🔍 Ready for Review, ✅ Approved

#572 fix: typo in reconcilation transaction creation
  packages/desktop-client/src/components/accounts/Account.js
Labels: ✅ Approved

#574 Fix #488
  packages/desktop-client/src/components/budget/MobileBudgetTable.js
Labels: ✅ Approved

#575 Add an issue template for feature requests
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
Labels: ✅ Approved

#576 Remove GUID on hover from PayeeCell
  packages/desktop-client/src/components/accounts/TransactionsTable.js
Labels: 🔍 Ready for Review

#491 :bug: allow deleting both transfer transactions at the same time
  packages/loot-core/src/server/accounts/transfer.js
Labels: 🔍 Ready for Review

#579 Add 'View on Hover' to Category Notes for #563
  packages/loot-design/src/components/NotesButton.js
Labels: ✅ Approved

#580 Added date to export file name
  packages/desktop-client/src/components/settings/Export.js
Labels: ✅ Approved

#573 Goal templates
  packages/desktop-client/src/components/settings/Experimental.js
  packages/loot-core/src/client/actions/queries.js
  packages/loot-core/src/server/budget/actions.js
  packages/loot-core/src/server/budget/app.js
  packages/loot-core/src/server/budget/goaltemplates.js
  packages/loot-design/src/components/budget/rollover/BudgetSummary.js
Labels: ✅ Approved

#582 Add 'Duplicate Transaction' to bulk editor for #548
  packages/desktop-client/src/components/accounts/Account.js
Labels: 🔍 Ready for Review

#584 Cover Overspending dropdown menu, open on click
  packages/loot-design/src/components/budget/rollover/rollover-components.js
Labels: ✅ Approved

#585 Add truthy condition to ambiguousDuplication check
  packages/desktop-client/src/components/accounts/Account.js
Labels: 🔍 Ready for Review, ✅ Approved

#586 :arrow_up: upgrade caniuse-lite
  yarn.lock
Labels: ✅ Approved

#592 Update SelectedBalance to use useSheetValue
  packages/desktop-client/src/components/accounts/Account.js
Labels: ✅ Approved

#593 Allow creating a payee with a name matching an existing account
  packages/loot-design/src/components/PayeeAutocomplete.js
Labels: ✅ Approved

#599 Don’t crash when loading an invalid account ID
  packages/desktop-client/src/components/accounts/Account.js
Labels: ✅ Approved

#598 Allow configuring the server from any page on the management app
  packages/desktop-client/src/components/manager/ManagementApp.js
Labels: ✅ Approved

#602 Support arbitrary currency symbols in expressions
  packages/loot-core/src/shared/arithmetic.js
Labels: ✅ Approved

#475 Add support for filtering the rules list
  packages/desktop-client/src/components/ManageRules.js
Labels: ✅ Approved
