Repository actualbudget/actual, pull requests merged in 2024-05, with the labels that each got.

#2690 [Mobile] Fix mobile account notes modal not retrieving correct notes
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/Notes.tsx
  packages/desktop-client/src/components/mobile/accounts/AccountTransactions.jsx
  packages/desktop-client/src/components/mobile/budget/index.tsx
  packages/desktop-client/src/components/modals/AccountMenuModal.tsx
  packages/desktop-client/src/components/modals/NotesModal.tsx
  packages/desktop-client/src/components/modals/ReportBudgetMonthMenuModal.tsx
  packages/desktop-client/src/components/modals/RolloverBudgetMonthMenuModal.tsx
  packages/loot-core/src/client/state-types/modals.d.ts
  upcoming-release-notes/2690.md
Labels: ✅ Approved

#2692 Fix management app flashing on page init
  packages/desktop-client/src/components/App.tsx
  upcoming-release-notes/2692.md
Labels: ✅ Approved

#2677 Custom Reports changes
  packages/desktop-client/src/components/reports/ReportOptions.ts
  packages/desktop-client/src/components/reports/ReportSidebar.jsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableTotals.tsx
  packages/desktop-client/src/components/reports/reportRanges.ts
  packages/desktop-client/src/components/reports/reports/CustomReport.jsx
  packages/desktop-client/src/components/reports/spreadsheets/custom-spreadsheet.ts
  packages/desktop-client/src/components/reports/spreadsheets/grouped-spreadsheet.ts
  packages/desktop-client/src/style/styles.ts
  packages/loot-core/src/shared/months.ts
  upcoming-release-notes/2677.md
Labels: ✅ Approved

#2622 Monthly spending report
  packages/desktop-client/src/components/reports/Header.jsx
  packages/desktop-client/src/components/reports/Overview.jsx
  packages/desktop-client/src/components/reports/ReportRouter.jsx
  packages/desktop-client/src/components/reports/graphs/SpendingGraph.tsx
  packages/desktop-client/src/components/reports/reports/Spending.tsx
  packages/desktop-client/src/components/reports/reports/SpendingCard.tsx
  packages/desktop-client/src/components/reports/spreadsheets/spending-spreadsheet.ts
  packages/desktop-client/src/components/settings/Experimental.tsx
  packages/desktop-client/src/hooks/useFeatureFlag.ts
  packages/loot-core/src/types/models/reports.d.ts
  packages/loot-core/src/types/prefs.d.ts
  upcoming-release-notes/2622.md
Labels: 🔍 Ready for Review

#2676 Fix some additional incorrect types
  packages/desktop-client/src/components/ThemeSelector.tsx
  packages/desktop-client/src/style/theme.tsx
  packages/loot-core/src/types/models/index.d.ts
  packages/loot-core/src/types/models/transaction.d.ts
  packages/loot-core/src/types/prefs.d.ts
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/2676.md
Labels: ✅ Approved

#2362 Added Header Authentication - Client Part
  packages/desktop-client/src/components/manager/ManagementApp.jsx
  packages/desktop-client/src/components/manager/subscribe/Login.tsx
  packages/desktop-client/src/components/manager/subscribe/common.tsx
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/2362.md
Labels: 🔍 Ready for Review

#2713 Use budget name as export file name
  packages/desktop-client/src/components/settings/Export.tsx
  upcoming-release-notes/2713.md
Labels: ✅ Approved

#2715 :bug: remove mac electron app code-signing
  .github/workflows/electron-master.yml
  bin/package-electron
  packages/api/package.json
  packages/crdt/package.json
  packages/desktop-client/package.json
  packages/desktop-client/vite.config.mts
  packages/loot-core/package.json
  upcoming-release-notes/2715.md
  yarn.lock
Labels: ✅ Approved

#2716 Create types for the external versions of entities meant for the API
  packages/loot-core/src/server/api-models.ts
  packages/loot-core/src/types/api-handlers.d.ts
  upcoming-release-notes/2716.md
Labels: ✅ Approved

#2631 :recycle: (tooltip) refactoring to react-aria (vol.3)
  packages/desktop-client/e2e/transactions.test.js
  packages/desktop-client/src/components/autocomplete/Autocomplete.tsx
  packages/desktop-client/src/components/autocomplete/CategoryAutocomplete.tsx
  packages/desktop-client/src/components/common/Input.tsx
  packages/desktop-client/src/components/common/Popover.tsx
  packages/desktop-client/src/components/common/Select.tsx
  packages/desktop-client/src/components/filters/FilterExpression.tsx
  packages/desktop-client/src/components/filters/FilterMenu.tsx
  packages/desktop-client/src/components/filters/FiltersMenu.jsx
  packages/desktop-client/src/components/filters/NameFilter.tsx
  packages/desktop-client/src/components/filters/SavedFilterMenuButton.tsx
  packages/desktop-client/src/components/select/DateSelect.tsx
  packages/desktop-client/src/components/transactions/TransactionsTable.test.jsx
  upcoming-release-notes/2631.md
Labels: ✅ Approved

#2664 [Mobile] Schedule name and date in mobile scheduled transaction modal
  packages/desktop-client/src/components/NotesButton.tsx
  packages/desktop-client/src/components/common/Modal.tsx
  packages/desktop-client/src/components/common/Tooltip.tsx
  packages/desktop-client/src/components/modals/ScheduledTransactionMenuModal.tsx
  upcoming-release-notes/2664.md
Labels: ✅ Approved

#2707 Custom Reports convert all jsx files
  packages/desktop-client/src/components/autocomplete/CategoryAutocomplete.tsx
  packages/desktop-client/src/components/reports/CategorySelector.tsx
  packages/desktop-client/src/components/reports/Overview.tsx
  packages/desktop-client/src/components/reports/ReportOptions.ts
  packages/desktop-client/src/components/reports/ReportRouter.tsx
  packages/desktop-client/src/components/reports/ReportSidebar.tsx
  packages/desktop-client/src/components/reports/ReportTopbar.tsx
  packages/desktop-client/src/components/reports/disabledList.ts
  packages/desktop-client/src/components/reports/getLiveRange.ts
  packages/desktop-client/src/components/reports/reportRanges.ts
  packages/desktop-client/src/components/reports/reports/CustomReport.tsx
  packages/desktop-client/src/components/reports/spreadsheets/custom-spreadsheet.ts
  packages/desktop-client/src/components/reports/spreadsheets/grouped-spreadsheet.ts
  packages/desktop-client/src/hooks/useFilters.ts
  packages/loot-core/src/types/models/reports.d.ts
  upcoming-release-notes/2707.md
Labels: ✅ Approved

#2696 Custom Reports: Show table activity
  packages/desktop-client/src/components/budget/BalanceWithCarryover.tsx
  packages/desktop-client/src/components/reports/ChooseGraph.tsx
  packages/desktop-client/src/components/reports/graphs/showActivity.ts
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTable.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableList.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableRow.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableTotals.tsx
  packages/desktop-client/src/components/table.tsx
  packages/loot-core/src/types/models/reports.d.ts
  upcoming-release-notes/2696.md
Labels: ✅ Approved

#2714 [WIP] revise modal margin
  packages/desktop-client/src/components/modals/CreateEncryptionKeyModal.tsx
  packages/desktop-client/src/components/modals/FixEncryptionKeyModal.tsx
  upcoming-release-notes/2714.md
Labels: 🚧 WIP

#2507 [Mobile] Budget file quick switch
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/manager/BudgetList.jsx
  packages/desktop-client/src/components/mobile/budget/index.tsx
  packages/desktop-client/src/components/modals/BudgetListModal.tsx
  packages/desktop-client/src/components/modals/BudgetPageMenuModal.tsx
  packages/desktop-client/src/components/modals/ScheduledTransactionMenuModal.tsx
  packages/loot-core/src/client/actions/budgets.ts
  packages/loot-core/src/client/state-types/modals.d.ts
  upcoming-release-notes/2507.md
Labels: ✅ Approved

#2729 Filters icon
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-1-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-2-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-3-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-4-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-5-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-6-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-creates-a-new-account-and-views-the-initial-balance-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-creates-a-new-account-and-views-the-initial-balance-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-creates-a-new-account-and-views-the-initial-balance-transaction-3-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-cash-flow-graph-and-checks-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-cash-flow-graph-and-checks-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-cash-flow-graph-and-checks-visuals-3-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-graph-and-checks-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-graph-and-checks-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-graph-and-checks-visuals-3-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-4-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-5-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-6-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-split-transaction-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-split-transaction-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-split-transaction-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-3-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-checks-the-page-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-checks-the-page-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-checks-the-page-visuals-3-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-split-test-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-split-test-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-split-test-transaction-3-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-test-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-test-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-test-transaction-3-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-category-7-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-category-8-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-category-9-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-date-7-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-date-8-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-date-9-chromium-linux.png
  packages/desktop-client/src/components/filters/FiltersButton.tsx
  upcoming-release-notes/2729.md
Labels: 🔍 Ready for Review, ✅ Approved

#2730 Update load budget loading texts
  packages/loot-core/src/client/actions/budgets.ts
  upcoming-release-notes/2730.md
Labels: ✅ Approved

#2706 [Feature] CAMT.053 import (new version)
  packages/desktop-client/src/components/accounts/Account.jsx
  packages/desktop-client/src/components/modals/ImportTransactions.jsx
  packages/loot-core/src/mocks/files/camt/camt.053.xml
  packages/loot-core/src/server/accounts/__snapshots__/parse-file.test.ts.snap
  packages/loot-core/src/server/accounts/parse-file.test.ts
  packages/loot-core/src/server/accounts/parse-file.ts
  packages/loot-core/src/server/accounts/xmlcamt2json.ts
  upcoming-release-notes/2706.md
Labels: ✅ Approved

#2712 Fix preview transactions not detecting schedule as paid when a child transaction is linked.
  packages/loot-core/src/shared/schedules.ts
  upcoming-release-notes/2712.md
Labels: ✅ Approved

#2726 Custom Reports: TS strict changes #1
  packages/desktop-client/src/components/reports/ChooseGraph.tsx
  packages/desktop-client/src/components/reports/ReportSummary.tsx
  packages/desktop-client/src/components/reports/graphs/AreaGraph.tsx
  packages/desktop-client/src/components/reports/graphs/BarGraph.tsx
  packages/desktop-client/src/components/reports/graphs/DonutGraph.tsx
  packages/desktop-client/src/components/reports/graphs/LineGraph.tsx
  packages/desktop-client/src/components/reports/graphs/StackedBarGraph.tsx
  packages/desktop-client/src/components/reports/graphs/adjustTextSize.ts
  packages/desktop-client/src/components/reports/graphs/tableGraph/RenderTableRow.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTable.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableHeader.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableList.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableRow.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableTotals.tsx
  packages/desktop-client/src/components/reports/reports/CustomReport.tsx
  packages/desktop-client/src/components/reports/spreadsheets/calculateLegend.ts
  packages/desktop-client/src/components/reports/spreadsheets/custom-spreadsheet.ts
  packages/desktop-client/src/components/reports/spreadsheets/grouped-spreadsheet.ts
  packages/loot-core/src/types/models/reports.d.ts
  upcoming-release-notes/2726.md
Labels: ✅ Approved

#2745 Fix spending report error
  packages/desktop-client/src/components/reports/graphs/SpendingGraph.tsx
  upcoming-release-notes/2745.md
Labels: ✅ Approved

#2725 :bug: fix networth graph loading forever for empty budgets
  packages/desktop-client/package.json
  packages/desktop-client/src/components/reports/spreadsheets/net-worth-spreadsheet.ts
  packages/desktop-client/src/components/reports/spreadsheets/spending-spreadsheet.ts
  packages/desktop-client/src/components/reports/util.ts
  upcoming-release-notes/2725.md
  yarn.lock
Labels: ✅ Approved

#2746 Auto insert decimals to mobile split transaction amounts
  packages/desktop-client/src/components/mobile/transactions/FocusableAmountInput.tsx
  packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
  packages/desktop-client/src/components/util/AmountInput.tsx
  packages/loot-core/src/shared/util.ts
  upcoming-release-notes/2746.md
Labels: ✅ Approved

#2568 Add API for working with rules
  packages/api/methods.test.ts
  packages/api/methods.ts
  packages/desktop-client/src/components/ManageRules.tsx
  packages/loot-core/src/client/state-types/modals.d.ts
  packages/loot-core/src/server/api.ts
  packages/loot-core/src/server/errors.ts
  packages/loot-core/src/server/rules/app.ts
  packages/loot-core/src/types/api-handlers.d.ts
  packages/loot-core/src/types/models/rule.d.ts
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/2568.md
Labels: ✅ Approved

#2727 Custom Reports: TS strict changes #2
  packages/desktop-client/src/components/reports/ReportOptions.ts
  packages/desktop-client/src/components/reports/SaveReport.tsx
  packages/desktop-client/src/components/reports/spreadsheets/custom-spreadsheet.ts
  packages/desktop-client/src/components/reports/spreadsheets/filterEmptyRows.ts
  packages/desktop-client/src/components/reports/spreadsheets/grouped-spreadsheet.ts
  upcoming-release-notes/2727.md
Labels: ✅ Approved

#2754 [Mobile] Do not remember last entered category in mobile transaction entry
  packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
  upcoming-release-notes/2754.md
Labels: ✅ Approved

#2724 ♻️ (tooltip) refactoring to react-aria (vol.4)
  .eslintrc.js
  packages/desktop-client/e2e/budget.test.js-snapshots/Budget-transfer-funds-to-another-category-1-chromium-linux.png
  packages/desktop-client/e2e/budget.test.js-snapshots/Budget-transfer-funds-to-another-category-2-chromium-linux.png
  packages/desktop-client/e2e/budget.test.js-snapshots/Budget-transfer-funds-to-another-category-3-chromium-linux.png
  packages/desktop-client/src/components/budget/BudgetTotals.tsx
  packages/desktop-client/src/components/budget/SidebarCategory.tsx
  packages/desktop-client/src/components/budget/SidebarGroup.tsx
  packages/desktop-client/src/components/budget/rollover/BalanceMovementMenu.tsx
  packages/desktop-client/src/components/budget/rollover/CoverMenu.tsx
  packages/desktop-client/src/components/budget/rollover/HoldMenu.tsx
  packages/desktop-client/src/components/budget/rollover/RolloverComponents.tsx
  packages/desktop-client/src/components/budget/rollover/TransferMenu.tsx
  packages/desktop-client/src/components/budget/rollover/budgetsummary/BudgetSummary.tsx
  packages/desktop-client/src/components/budget/rollover/budgetsummary/ToBudget.tsx
  packages/desktop-client/src/components/budget/rollover/budgetsummary/ToBudgetAmount.tsx
  packages/desktop-client/src/components/common/Menu.tsx
  packages/desktop-client/src/components/transactions/TransactionsTable.test.jsx
  upcoming-release-notes/2724.md
Labels: ✅ Approved

#2698 :bug: (api) fix performing api operations for local e2e encrypted files
  packages/loot-core/src/server/api.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/types/budget.d.ts
  upcoming-release-notes/2698.md
Labels: ✅ Approved

#2648 Don't update transaction date when importing manually
  packages/api/methods.test.ts
  packages/loot-core/src/server/accounts/sync.ts
  upcoming-release-notes/2648.md
Labels: ✅ Approved

#2683 :sparkles: (api) ability to run bank sync via the API
  packages/api/methods.ts
  packages/loot-core/src/client/actions/account.ts
  packages/loot-core/src/server/api.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/shared/errors.ts
  packages/loot-core/src/types/api-handlers.d.ts
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/2683.md
Labels: ✅ Approved

#2672 [Feature] Make comma's and period interchangeable when entering figures
  packages/loot-core/src/shared/arithmetic.ts
  packages/loot-core/src/shared/util.ts
  upcoming-release-notes/2672.md
Labels: ✅ Approved

#2753 [Mobile] Require account in mobile transaction entry + confirm transaction delete
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-3-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-split-transaction-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-split-transaction-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-split-transaction-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-3-chromium-linux.png
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/Notifications.tsx
  packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
  packages/desktop-client/src/components/modals/ConfirmTransactionDelete.tsx
  packages/loot-core/src/client/state-types/modals.d.ts
  packages/loot-core/src/client/state-types/notifications.d.ts
  upcoming-release-notes/2753.md
Labels: ✅ Approved

#2643 Fix amount filter to include both incoming and outgoing amounts
  packages/loot-core/src/server/accounts/transaction-rules.test.ts
  packages/loot-core/src/server/accounts/transaction-rules.ts
  upcoming-release-notes/2643.md
Labels: ✅ Approved

#2763 :electron: Update Electron to latest stable version
  packages/api/package.json
  packages/desktop-client/package.json
  packages/desktop-electron/package.json
  packages/loot-core/package.json
  upcoming-release-notes/2763.md
  yarn.lock
Labels: ✅ Approved

#2762 Add run-vrt script to run vrt inside docker
  bin/run-vrt
  package.json
  packages/desktop-client/README.md
  upcoming-release-notes/2762.md
Labels: ✅ Approved

#2728 Custom Reports: TS strict changes #3
  packages/desktop-client/src/components/reports/ChooseGraph.tsx
  packages/desktop-client/src/components/reports/Container.tsx
  packages/desktop-client/src/components/reports/GraphButton.tsx
  packages/desktop-client/src/components/reports/graphs/AreaGraph.tsx
  packages/desktop-client/src/components/reports/graphs/BarGraph.tsx
  packages/desktop-client/src/components/reports/graphs/DonutGraph.tsx
  packages/desktop-client/src/components/reports/graphs/LineGraph.tsx
  packages/desktop-client/src/components/reports/graphs/StackedBarGraph.tsx
  packages/desktop-client/src/components/reports/graphs/showActivity.ts
  packages/desktop-client/src/components/reports/spreadsheets/calculateLegend.ts
  packages/desktop-client/src/components/reports/spreadsheets/filterEmptyRows.ts
  packages/desktop-client/src/components/reports/spreadsheets/grouped-spreadsheet.ts
  packages/desktop-client/src/components/reports/spreadsheets/recalculate.ts
  upcoming-release-notes/2728.md
Labels: ✅ Approved

#2738 Add crdt to the API package to fix types
  packages/api/package.json
  packages/loot-core/webpack/webpack.api.config.js
  upcoming-release-notes/2738.md
  yarn.lock
Labels: 🔍 Ready for Review, ✅ Approved

#2559 Ensure api types are included in the npm package
  packages/api/package.json
  upcoming-release-notes/2559.md
Labels: 🔍 Ready for Review

#2775 fix: put income on left and expense on right always, hide when 0
  packages/desktop-client/src/components/reports/reports/CashFlowCard.jsx
  upcoming-release-notes/2775.md
Labels: ✅ Approved

#2750 Github action to automatically deploy a release image to Netlify
  .github/workflows/netlify-release.yml
  .gitignore
  upcoming-release-notes/2750.md
Labels: ✅ Approved

#2768 Custom Reports: Table Totals Callback
  packages/desktop-client/src/components/reports/ChooseGraph.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/RenderTableRow.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTable.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableHeader.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableList.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableRow.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableTotals.tsx
  packages/desktop-client/src/components/reports/spreadsheets/custom-spreadsheet.ts
  packages/desktop-client/src/components/reports/spreadsheets/recalculate.ts
  packages/loot-core/src/types/models/reports.d.ts
  upcoming-release-notes/2768.md
Labels: ✅ Approved

#2773 Fix notes icon changing size/position with long category or group names
  packages/desktop-client/src/components/budget/SidebarCategory.tsx
  packages/desktop-client/src/components/budget/SidebarGroup.tsx
  upcoming-release-notes/2773.md
Labels: ✅ Approved

#2652 Template only the relevant amount in a split-schedule category
  packages/loot-core/src/server/accounts/rules.ts
  packages/loot-core/src/server/budget/goals/goalsSchedule.ts
  packages/loot-core/src/server/schedules/app.ts
  upcoming-release-notes/2652.md
Labels: ✅ Approved

#2778 ♻️ (tooltip) refactoring to react-aria (vol.7)
  packages/desktop-client/src/components/common/MenuButton.tsx
  packages/desktop-client/src/components/common/Popover.tsx
  packages/desktop-client/src/components/reports/GraphButton.tsx
  packages/desktop-client/src/components/reports/ReportSidebar.tsx
  packages/desktop-client/src/components/reports/SaveReport.tsx
  packages/desktop-client/src/components/reports/SaveReportChoose.tsx
  packages/desktop-client/src/components/reports/SaveReportDelete.tsx
  packages/desktop-client/src/components/reports/SaveReportMenu.tsx
  packages/desktop-client/src/components/reports/SaveReportName.tsx
  packages/desktop-client/src/components/reports/reports/CustomReportListCards.tsx
  upcoming-release-notes/2778.md
Labels: ✅ Approved

#2765 Avoid using underlines for emphasis
  packages/desktop-client/src/components/modals/CreateAccountModal.tsx
  upcoming-release-notes/2765.md
Labels: ✅ Approved

#2786 Match on `amount` when creating a rule from a transaction
  packages/desktop-client/src/components/accounts/Account.jsx
  upcoming-release-notes/2786.md
Labels: 🔍 Ready for Review

#2797 Make picking budget months easier to see
  packages/desktop-client/src/components/budget/MonthPicker.tsx
  upcoming-release-notes/2797.md
Labels: ✨ Merged

#2803 Revert #2643
  packages/loot-core/src/server/accounts/transaction-rules.test.ts
  packages/loot-core/src/server/accounts/transaction-rules.ts
  upcoming-release-notes/2803.md
Labels: ✨ Merged

#2809 Spending report error fix with some visual changes
  packages/desktop-client/src/components/reports/graphs/SpendingGraph.tsx
  packages/desktop-client/src/components/reports/reports/Spending.tsx
  packages/desktop-client/src/components/reports/reports/SpendingCard.tsx
  packages/desktop-client/src/components/reports/spreadsheets/spending-spreadsheet.ts
  upcoming-release-notes/2809.md
Labels: ✅ Approved

#2788 Initial support for linking to off-budget accounts
  packages/desktop-client/src/components/modals/SelectLinkedAccounts.jsx
  packages/loot-core/src/client/actions/account.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/2788.md
Labels: ✅ Approved
