Repository actualbudget/actual, pull requests merged in 2024-11, with the labels that each got.

#3768 Fix bugs in payee table
  packages/desktop-client/src/components/payees/PayeeTable.tsx
  packages/desktop-client/src/components/payees/PayeeTableRow.tsx
  upcoming-release-notes/3768.md
Labels: :white_check_mark: Approved

#3732 Fix #2932: Schedule reset amount to ten (10) when amount is zero (0)
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-10-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-11-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-12-chromium-linux.png
  packages/desktop-client/src/components/schedules/ScheduleDetails.jsx
  packages/desktop-client/src/components/util/AmountInput.tsx
  upcoming-release-notes/3732.md
Labels: :white_check_mark: Approved

#3764 ci: /update-vrt
  .github/workflows/update-vrt.yml
  upcoming-release-notes/3764.md
Labels: :white_check_mark: Approved

#3693 Auto-reload on app updates
  packages/desktop-client/src/browser-preload.browser.js
  packages/desktop-client/src/components/App.tsx
  packages/desktop-client/src/components/FinancesApp.tsx
  packages/desktop-client/src/index.tsx
  packages/desktop-client/vite.config.mts
  packages/desktop-electron/preload.ts
  packages/loot-core/src/client/actions/app.ts
  upcoming-release-notes/3693.md
Labels: :white_check_mark: Approved

#3381 Add context menu's
  packages/desktop-client/src/components/ManageRules.tsx
  packages/desktop-client/src/components/accounts/Account.tsx
  packages/desktop-client/src/components/budget/SidebarCategory.tsx
  packages/desktop-client/src/components/budget/SidebarGroup.tsx
  packages/desktop-client/src/components/budget/envelope/BalanceMovementMenu.tsx
  packages/desktop-client/src/components/budget/envelope/EnvelopeBudgetComponents.tsx
  packages/desktop-client/src/components/budget/envelope/budgetsummary/ToBudget.tsx
  packages/desktop-client/src/components/budget/envelope/budgetsummary/ToBudgetAmount.tsx
  packages/desktop-client/src/components/common/Popover.tsx
  packages/desktop-client/src/components/payees/ManagePayees.tsx
  packages/desktop-client/src/components/payees/PayeeTable.tsx
  packages/desktop-client/src/components/payees/PayeeTableRow.tsx
  packages/desktop-client/src/components/rules/RuleRow.tsx
  packages/desktop-client/src/components/rules/RulesList.tsx
  packages/desktop-client/src/components/schedules/SchedulesTable.tsx
  packages/desktop-client/src/components/settings/Experimental.tsx
  packages/desktop-client/src/components/transactions/TransactionList.jsx
  packages/desktop-client/src/components/transactions/TransactionMenu.tsx
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  packages/desktop-client/src/components/transactions/TransactionsTable.test.jsx
  packages/desktop-client/src/hooks/useFeatureFlag.ts
  packages/loot-core/src/types/prefs.d.ts
  upcoming-release-notes/3381.md
Labels: :mag: Ready for review

#3757 [Typescript migration] Migrate AccountSyncCheck to ts
  packages/desktop-client/src/components/accounts/AccountSyncCheck.tsx
  packages/desktop-client/src/components/budget/util.ts
  upcoming-release-notes/3757.md
Labels: :white_check_mark: Approved

#3666 Apply Template to All Categories in Group for Web
  packages/desktop-client/src/components/budget/BudgetCategories.jsx
  packages/desktop-client/src/components/budget/BudgetTable.jsx
  packages/desktop-client/src/components/budget/ExpenseGroup.tsx
  packages/desktop-client/src/components/budget/SidebarGroup.tsx
  packages/desktop-client/src/components/budget/index.tsx
  packages/loot-core/src/client/actions/queries.ts
  packages/loot-core/src/server/budget/app.ts
  packages/loot-core/src/server/budget/goaltemplates.ts
  packages/loot-core/src/server/budget/types/handlers.d.ts
  upcoming-release-notes/3666.md
Labels: :white_check_mark: Approved

#3753 Fix: #3719: Imported payee overflowing on transaction record
  packages/desktop-client/src/components/common/Tooltip.tsx
  upcoming-release-notes/3753.md
Labels: :white_check_mark: Approved

#3773 fix: /update-vrt on forks
  .github/workflows/update-vrt.yml
Labels: :white_check_mark: Approved

#3581 implement SimpleFin batch sync
  packages/loot-core/src/client/actions/account.ts
  packages/loot-core/src/server/accounts/sync.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/types/models/bank-sync.d.ts
  packages/loot-core/src/types/models/gocardless.d.ts
  packages/loot-core/src/types/models/index.d.ts
  packages/loot-core/src/types/models/simplefin.d.ts
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/3581.md
Labels: :mag: Ready for review

#3748 fix: maintain the sort order of the server sync
  packages/loot-core/src/server/accounts/__snapshots__/parse-file.test.ts.snap
  packages/loot-core/src/server/accounts/sync.ts
  upcoming-release-notes/3748.md
Labels: :white_check_mark: Approved

#3745 :bug: (dashboards) save cash flow balance setting
  packages/desktop-client/src/components/reports/reports/CashFlow.tsx
  packages/loot-core/src/types/models/dashboard.d.ts
  upcoming-release-notes/3745.md
Labels: :white_check_mark: Approved

#3754 :recycle: make templates classy and replace :spaghetti: code
  packages/loot-core/src/server/budget/categoryTemplate.ts
  packages/loot-core/src/server/budget/goal-template.pegjs
  packages/loot-core/src/server/budget/goals/goalsAverage.test.ts
  packages/loot-core/src/server/budget/goals/goalsAverage.ts
  packages/loot-core/src/server/budget/goals/goalsBy.test.ts
  packages/loot-core/src/server/budget/goals/goalsBy.ts
  packages/loot-core/src/server/budget/goals/goalsCopy.ts
  packages/loot-core/src/server/budget/goals/goalsPercentage.test.ts
  packages/loot-core/src/server/budget/goals/goalsPercentage.ts
  packages/loot-core/src/server/budget/goals/goalsRemainder.test.ts
  packages/loot-core/src/server/budget/goals/goalsRemainder.ts
  packages/loot-core/src/server/budget/goals/goalsSimple.test.ts
  packages/loot-core/src/server/budget/goals/goalsSimple.ts
  packages/loot-core/src/server/budget/goals/goalsSpend.test.ts
  packages/loot-core/src/server/budget/goals/goalsSpend.ts
  packages/loot-core/src/server/budget/goals/goalsWeek.test.ts
  packages/loot-core/src/server/budget/goals/goalsWeek.ts
  packages/loot-core/src/server/budget/goalsSchedule.test.ts
  packages/loot-core/src/server/budget/goalsSchedule.ts
  packages/loot-core/src/server/budget/goaltemplates.ts
  packages/loot-core/src/server/budget/types/templates.d.ts
  upcoming-release-notes/3754.md
Labels: :white_check_mark: Approved

#3782 :electron: Removing node-fetch and updating root ca impl for more support
  packages/desktop-electron/index.ts
  packages/desktop-electron/package.json
  packages/desktop-electron/server.ts
  packages/loot-core/package.json
  packages/loot-core/src/platform/server/fetch/index.electron.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/webpack/webpack.desktop.config.js
  upcoming-release-notes/3782.md
  yarn.lock
Labels: :white_check_mark: Approved

#3787 fix: /update-vrt
  .github/workflows/update-vrt.yml
Labels: :white_check_mark: Approved

#3788 Update update-vrt.yml
  .github/workflows/update-vrt.yml
Labels: :mag: Ready for review

#3729 Fix loading of mobile/desktop page on window resize
  packages/desktop-client/src/components/App.tsx
  packages/desktop-client/src/components/FinancesApp.tsx
  packages/desktop-client/src/components/Notes.tsx
  packages/desktop-client/src/components/Notifications.tsx
  packages/desktop-client/src/components/Page.tsx
  packages/desktop-client/src/components/PrivacyFilter.tsx
  packages/desktop-client/src/components/ThemeSelector.tsx
  packages/desktop-client/src/components/Titlebar.tsx
  packages/desktop-client/src/components/autocomplete/AccountAutocomplete.tsx
  packages/desktop-client/src/components/autocomplete/Autocomplete.tsx
  packages/desktop-client/src/components/autocomplete/CategoryAutocomplete.tsx
  packages/desktop-client/src/components/autocomplete/ItemHeader.tsx
  packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.test.tsx
  packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.tsx
  packages/desktop-client/src/components/budget/BalanceWithCarryover.tsx
  packages/desktop-client/src/components/manager/BudgetList.tsx
  packages/desktop-client/src/components/manager/ManagementApp.jsx
  packages/desktop-client/src/components/mobile/MobileNavTabs.tsx
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  packages/desktop-client/src/components/modals/AccountAutocompleteModal.tsx
  packages/desktop-client/src/components/modals/CategoryAutocompleteModal.tsx
  packages/desktop-client/src/components/modals/CloseAccountModal.tsx
  packages/desktop-client/src/components/modals/ConfirmTransactionDeleteModal.tsx
  packages/desktop-client/src/components/modals/CreateEncryptionKeyModal.tsx
  packages/desktop-client/src/components/modals/EditFieldModal.jsx
  packages/desktop-client/src/components/modals/FixEncryptionKeyModal.tsx
  packages/desktop-client/src/components/modals/PayeeAutocompleteModal.tsx
  packages/desktop-client/src/components/reports/Header.tsx
  packages/desktop-client/src/components/reports/Overview.tsx
  packages/desktop-client/src/components/reports/ReportCard.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableRow.tsx
  packages/desktop-client/src/components/reports/reports/CashFlow.tsx
  packages/desktop-client/src/components/reports/reports/CustomReport.tsx
  packages/desktop-client/src/components/reports/reports/GetCardData.tsx
  packages/desktop-client/src/components/reports/reports/NetWorth.tsx
  packages/desktop-client/src/components/reports/reports/NetWorthCard.tsx
  packages/desktop-client/src/components/reports/reports/Spending.tsx
  packages/desktop-client/src/components/responsive/ResponsiveProvider.tsx
  packages/desktop-client/src/components/responsive/index.tsx
  packages/desktop-client/src/components/settings/index.tsx
  packages/desktop-client/src/components/sidebar/Sidebar.tsx
  packages/desktop-client/src/components/sidebar/SidebarProvider.tsx
  packages/desktop-client/src/components/sidebar/index.tsx
  packages/desktop-client/src/components/transactions/TransactionsTable.test.jsx
  packages/desktop-client/src/components/util/LoadComponent.tsx
  upcoming-release-notes/3729.md
Labels: :white_check_mark: Approved

#3789 ci: add reactions to /update-vrt comment
  .github/workflows/update-vrt.yml
Labels: :white_check_mark: Approved

#3794 Fixes #3729: Typescript and Runtime error after previous merge
  packages/desktop-client/src/components/common/Modal.tsx
  upcoming-release-notes/3794.md
Labels: :white_check_mark: Approved

#3785 :bug: (dashboards) remove faulty dashboard widgets
  packages/loot-core/migrations/1730744182000_fix_dashboard_table.sql
  upcoming-release-notes/3785.md
Labels: :white_check_mark: Approved

#3593 Update Sidebar - Refactor the Budget Name component
  packages/desktop-client/src/components/sidebar/BudgetName.tsx
  packages/desktop-client/src/components/sidebar/Sidebar.tsx
  upcoming-release-notes/3593.md
Labels: :mag: Ready for review

#3793 Check gocardless bank data type before setting state
  packages/desktop-client/src/components/modals/GoCardlessExternalMsgModal.tsx
  upcoming-release-notes/3793.md
Labels: :white_check_mark: Approved

#3798 [WIP] Update update-vrt.yml
  .github/workflows/update-vrt.yml
Labels: :construction: WIP

#3817 [Goals] fix how goal values are calculated
  packages/loot-core/src/server/budget/categoryTemplate.ts
  packages/loot-core/src/server/budget/goaltemplates.ts
  upcoming-release-notes/3817.md
Labels: :white_check_mark: Approved

#3822 [Goals] fix remainder goal
  packages/loot-core/src/server/budget/categoryTemplate.ts
Labels: :white_check_mark: Approved

#3823 🐛 Fix iphone 13 unable to use regex lookbehinds
  packages/loot-core/src/server/accounts/transaction-rules.ts
  upcoming-release-notes/3823.md
Labels: :white_check_mark: Approved

#3825 Fix back button behavior after adding tx on mobile
  packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
  upcoming-release-notes/3825.md
Labels: :white_check_mark: Approved

#3571 Fixes #2885 - Focus ring getting stuck on last column of /accounts/budgeted
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  upcoming-release-notes/3571.md
Labels: :white_check_mark: Approved

#3801 :electron: Separate build folders for easier switching between web and electron
  bin/package-electron
  packages/desktop-client/.gitignore
  packages/desktop-client/vite.config.mts
  packages/desktop-electron/bin/update-client
  packages/desktop-electron/index.ts
  packages/desktop-electron/package.json
  packages/loot-core/src/platform/server/fs/index.electron.ts
  packages/loot-core/webpack/webpack.desktop.config.js
  upcoming-release-notes/3801.md
Labels: :white_check_mark: Approved

#3827 Marked files for translation
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/modals/BudgetPageMenuModal.tsx
  packages/desktop-client/src/components/payees/ManagePayeesPage.jsx
  packages/desktop-client/src/components/reports/SaveReportChoose.tsx
  packages/desktop-client/src/components/reports/SaveReportMenu.tsx
  packages/desktop-client/src/components/util/DisplayId.tsx
  packages/loot-core/src/server/budget/cleanup-template.ts
  packages/loot-core/src/server/budget/goaltemplates.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/server/mutators.ts
  packages/loot-core/src/server/sheet.ts
  packages/loot-core/src/shared/errors.ts
  packages/loot-core/src/shared/rules.ts
  upcoming-release-notes/3827.md
Labels: :white_check_mark: Approved

#3832 Marked files for translation
  packages/desktop-client/src/components/modals/EnvelopeBalanceMenuModal.tsx
  packages/desktop-client/src/components/modals/EnvelopeBudgetMenuModal.tsx
  packages/desktop-client/src/components/modals/EnvelopeBudgetMonthMenuModal.tsx
  packages/desktop-client/src/components/modals/EnvelopeBudgetSummaryModal.tsx
  packages/desktop-client/src/components/modals/LoadBackupModal.tsx
  packages/desktop-client/src/components/modals/TrackingBalanceMenuModal.tsx
  packages/desktop-client/src/components/modals/TrackingBudgetMenuModal.tsx
  packages/desktop-client/src/components/modals/TrackingBudgetMonthMenuModal.tsx
  packages/desktop-client/src/components/modals/TrackingBudgetSummaryModal.tsx
  packages/desktop-client/src/components/reports/Header.tsx
  packages/desktop-client/src/components/reports/reports/NetWorth.tsx
  packages/desktop-client/src/components/select/RecurringSchedulePicker.tsx
  upcoming-release-notes/3832.md
Labels: :white_check_mark: Approved

#3837 🐛 Fix validation issue for invalid server URLs in /config-server page
  packages/desktop-client/src/components/manager/ConfigServer.tsx
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/server/server-config.ts
  upcoming-release-notes/3837.md
Labels: :white_check_mark: Approved

#3731 Fix mobile navigation tabs expanding/collapsing when scrolling in modals
  packages/desktop-client/e2e/settings.mobile.test.js-snapshots/Mobile-Settings-checks-that-settings-page-can-be-opened-1-chromium-linux.png
  packages/desktop-client/e2e/settings.mobile.test.js-snapshots/Mobile-Settings-checks-that-settings-page-can-be-opened-2-chromium-linux.png
  packages/desktop-client/e2e/settings.mobile.test.js-snapshots/Mobile-Settings-checks-that-settings-page-can-be-opened-3-chromium-linux.png
  packages/desktop-client/src/components/App.tsx
  packages/desktop-client/src/components/FinancesApp.tsx
  packages/desktop-client/src/components/ScrollProvider.tsx
  packages/desktop-client/src/components/mobile/MobileNavTabs.tsx
  packages/desktop-client/src/components/mobile/transactions/ListBox.jsx
  upcoming-release-notes/3731.md
Labels: :white_check_mark: Approved

#3761 Convert Mobile Transaction component to TransactionListItem + cleanup
  packages/desktop-client/e2e/accounts.mobile.test.js-snapshots/Mobile-Accounts-opens-individual-account-page-and-checks-that-filtering-is-working-1-chromium-linux.png
  packages/desktop-client/e2e/accounts.mobile.test.js-snapshots/Mobile-Accounts-opens-individual-account-page-and-checks-that-filtering-is-working-2-chromium-linux.png
  packages/desktop-client/e2e/accounts.mobile.test.js-snapshots/Mobile-Accounts-opens-individual-account-page-and-checks-that-filtering-is-working-3-chromium-linux.png
  packages/desktop-client/e2e/accounts.mobile.test.js-snapshots/Mobile-Accounts-opens-individual-account-page-and-checks-that-filtering-is-working-7-chromium-linux.png
  packages/desktop-client/e2e/accounts.mobile.test.js-snapshots/Mobile-Accounts-opens-individual-account-page-and-checks-that-filtering-is-working-8-chromium-linux.png
  packages/desktop-client/e2e/accounts.mobile.test.js-snapshots/Mobile-Accounts-opens-individual-account-page-and-checks-that-filtering-is-working-9-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.js-snapshots/Mobile-Budget-Envelope-checks-that-clicking--c18ad-l-redirects-to-the-category-transactions-page-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.js-snapshots/Mobile-Budget-Envelope-checks-that-clicking--e995e-l-redirects-to-the-category-transactions-page-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.js-snapshots/Mobile-Budget-Envelope-checks-that-clicking--ff568-l-redirects-to-the-category-transactions-page-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.js-snapshots/Mobile-Budget-Tracking-checks-that-clicking--11290-l-redirects-to-the-category-transactions-page-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.js-snapshots/Mobile-Budget-Tracking-checks-that-clicking--57d88-l-redirects-to-the-category-transactions-page-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.js-snapshots/Mobile-Budget-Tracking-checks-that-clicking--5d90c-l-redirects-to-the-category-transactions-page-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.mobile.test.js-snapshots/Mobile-Transactions-creates-a-transaction-via-footer-button-7-chromium-linux.png
  packages/desktop-client/e2e/transactions.mobile.test.js-snapshots/Mobile-Transactions-creates-a-transaction-via-footer-button-8-chromium-linux.png
  packages/desktop-client/e2e/transactions.mobile.test.js-snapshots/Mobile-Transactions-creates-a-transaction-via-footer-button-9-chromium-linux.png
  packages/desktop-client/package.json
  packages/desktop-client/src/components/mobile/accounts/AccountTransactions.tsx
  packages/desktop-client/src/components/mobile/transactions/ListBox.jsx
  packages/desktop-client/src/components/mobile/transactions/ListBoxSection.jsx
  packages/desktop-client/src/components/mobile/transactions/Option.jsx
  packages/desktop-client/src/components/mobile/transactions/Transaction.jsx
  packages/desktop-client/src/components/mobile/transactions/TransactionList.jsx
  packages/desktop-client/src/components/mobile/transactions/TransactionListItem.tsx
  packages/desktop-client/src/components/mobile/transactions/TransactionListWithBalances.jsx
  packages/loot-core/src/shared/months.ts
  upcoming-release-notes/3761.md
  yarn.lock
Labels: :white_check_mark: Approved

#3821 add simplefin batch sync to api
  packages/loot-core/src/client/actions/account.ts
  packages/loot-core/src/server/api.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/3821.md
Labels: :white_check_mark: Approved

#3833 :sparkles: release tracking budget feature
  packages/desktop-client/e2e/page-models/settings-page.js
  packages/desktop-client/e2e/settings.mobile.test.js-snapshots/Mobile-Settings-checks-that-settings-page-can-be-opened-1-chromium-linux.png
  packages/desktop-client/e2e/settings.mobile.test.js-snapshots/Mobile-Settings-checks-that-settings-page-can-be-opened-2-chromium-linux.png
  packages/desktop-client/e2e/settings.mobile.test.js-snapshots/Mobile-Settings-checks-that-settings-page-can-be-opened-3-chromium-linux.png
  packages/desktop-client/e2e/settings.mobile.test.js-snapshots/Mobile-Settings-checks-that-settings-page-can-be-opened-4-chromium-linux.png
  packages/desktop-client/e2e/settings.mobile.test.js-snapshots/Mobile-Settings-checks-that-settings-page-can-be-opened-5-chromium-linux.png
  packages/desktop-client/e2e/settings.mobile.test.js-snapshots/Mobile-Settings-checks-that-settings-page-can-be-opened-6-chromium-linux.png
  packages/desktop-client/src/components/mobile/MobileNavTabs.tsx
  packages/desktop-client/src/components/settings/Experimental.tsx
  packages/desktop-client/src/components/settings/index.tsx
  packages/desktop-client/src/hooks/useFeatureFlag.ts
  packages/loot-core/src/types/prefs.d.ts
  upcoming-release-notes/3833.md
Labels: :white_check_mark: Approved

#3829 [Goals] fix limits
  packages/loot-core/src/server/budget/actions.ts
  packages/loot-core/src/server/budget/categoryTemplate.ts
  packages/loot-core/src/server/budget/goaltemplates.ts
  upcoming-release-notes/3829.md
Labels: :white_check_mark: Approved

#3548 Marked files for translation
  packages/desktop-client/src/components/reports/DateRange.tsx
  packages/desktop-client/src/components/reports/ReportOptions.ts
  packages/desktop-client/src/components/reports/disabledList.ts
  packages/desktop-client/src/components/reports/index.tsx
  upcoming-release-notes/3548.md
Labels: :white_check_mark: Approved

#3402 Fix wrong scheduled transfer payment direction on PWA
  packages/desktop-client/e2e/accounts.mobile.test.js-snapshots/Mobile-Accounts-opens-individual-account-page-and-checks-that-filtering-is-working-1-chromium-linux.png
  packages/desktop-client/e2e/accounts.mobile.test.js-snapshots/Mobile-Accounts-opens-individual-account-page-and-checks-that-filtering-is-working-2-chromium-linux.png
  packages/desktop-client/e2e/accounts.mobile.test.js-snapshots/Mobile-Accounts-opens-individual-account-page-and-checks-that-filtering-is-working-3-chromium-linux.png
  packages/desktop-client/src/components/accounts/Account.tsx
  packages/desktop-client/src/components/mobile/accounts/AccountTransactions.tsx
  packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
  packages/desktop-client/src/components/mobile/transactions/TransactionListItem.tsx
  packages/desktop-client/src/components/mobile/utils.ts
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  packages/desktop-client/src/hooks/useAccountPreviewTransactions.ts
  packages/desktop-client/src/hooks/usePreviewTransactions.ts
  packages/loot-core/src/client/data-hooks/schedules.tsx
  packages/loot-core/src/client/data-hooks/transactions.ts
  packages/loot-core/src/client/query-hooks.ts
  packages/loot-core/src/shared/schedules.ts
  packages/loot-core/src/types/models/schedule.d.ts
  upcoming-release-notes/3402.md
Labels: :white_check_mark: Approved

#3856 :sparkles: (dashboards) release as first party feature
  packages/desktop-client/e2e/page-models/reports-page.js
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-cash-flow-graph-and-checks-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-cash-flow-graph-and-checks-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-cash-flow-graph-and-checks-visuals-3-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-and-cash-flow-reports-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-and-cash-flow-reports-2-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-and-cash-flow-reports-3-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-graph-and-checks-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-graph-and-checks-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-graph-and-checks-visuals-3-chromium-linux.png
  packages/desktop-client/src/components/reports/Header.tsx
  packages/desktop-client/src/components/reports/Overview.tsx
  packages/desktop-client/src/components/reports/reports/CashFlowCard.tsx
  packages/desktop-client/src/components/reports/reports/CustomReportListCards.tsx
  packages/desktop-client/src/components/reports/reports/NetWorthCard.tsx
  packages/desktop-client/src/components/reports/reports/Spending.tsx
  packages/desktop-client/src/components/reports/reports/SpendingCard.tsx
  packages/desktop-client/src/components/settings/Experimental.tsx
  packages/desktop-client/src/hooks/useFeatureFlag.ts
  packages/loot-core/src/types/prefs.d.ts
  upcoming-release-notes/3856.md
Labels: :white_check_mark: Approved

#3669 Fix category is/is not (nothing) filters
  packages/desktop-client/src/components/filters/FiltersMenu.jsx
  packages/loot-core/src/server/accounts/rules.ts
  packages/loot-core/src/server/accounts/transaction-rules.test.ts
  packages/loot-core/src/server/accounts/transaction-rules.ts
  packages/loot-core/src/server/aql/compiler.test.ts
  packages/loot-core/src/server/aql/compiler.ts
  packages/loot-core/src/shared/rules.ts
  packages/loot-core/src/types/models/rule.d.ts
  upcoming-release-notes/3669.md
Labels: :white_check_mark: Approved

#3859 Strict TS typing for useResizeObserver
  packages/desktop-client/src/components/budget/BudgetSummaries.tsx
  packages/desktop-client/src/components/sidebar/Sidebar.tsx
  packages/desktop-client/src/hooks/useResizeObserver.ts
  upcoming-release-notes/3859.md
Labels: :white_check_mark: Approved

#3860 Convert ManagementApp.jsx to tsx
  packages/desktop-client/src/components/manager/ManagementApp.tsx
  upcoming-release-notes/3860.md
Labels: :white_check_mark: Approved

#3873 Fix preview transactions not showing on all accounts page and aggregated accounts page (budgeted/offbudget)
  packages/desktop-client/src/hooks/useAccountPreviewTransactions.ts
  upcoming-release-notes/3873.md
Labels: :white_check_mark: Approved

#3872 Allow the report table columns to grow to fill available space
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableHeader.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableRow.tsx
  upcoming-release-notes/3872.md
Labels: :white_check_mark: Approved

#3868 Convert PostsOfflineNotification.jsx to tsx
  packages/desktop-client/src/components/schedules/PostsOfflineNotification.tsx
  upcoming-release-notes/3868.md
Labels: :white_check_mark: Approved

#3870 Convert SimpleTransactionsTable.jsx to tsx
  packages/desktop-client/src/components/transactions/SimpleTransactionsTable.tsx
  upcoming-release-notes/3870.md
Labels: :white_check_mark: Approved

#3865 Convert EditFieldModal.jsx to tsx
  packages/desktop-client/src/components/modals/EditFieldModal.tsx
  upcoming-release-notes/3865.md
Labels: :white_check_mark: Approved

#3866 Convert MergeUnusedPayeesModal.jsx to tsx
  packages/desktop-client/src/components/modals/MergeUnusedPayeesModal.tsx
  upcoming-release-notes/3866.md
Labels: :white_check_mark: Approved

#3867 Convert ManagePayees components to Typescript
  packages/desktop-client/src/components/payees/ManagePayees.tsx
  packages/desktop-client/src/components/payees/ManagePayeesPage.tsx
  packages/desktop-client/src/components/payees/ManagePayeesWithData.tsx
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/3867.md
Labels: :white_check_mark: Approved

#3864 Use strict typing in useSheetValue and fix bug where query is not being updated when changed
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-category-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-category-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-category-4-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-category-5-chromium-linux.png
  packages/desktop-client/src/components/accounts/Reconcile.tsx
  packages/desktop-client/src/components/autocomplete/CategoryAutocomplete.tsx
  packages/desktop-client/src/components/budget/envelope/BalanceMenu.tsx
  packages/desktop-client/src/components/budget/envelope/BalanceMovementMenu.tsx
  packages/desktop-client/src/components/budget/envelope/budgetsummary/ToBudgetMenu.tsx
  packages/desktop-client/src/components/spreadsheet/useSheetValue.ts
  upcoming-release-notes/3864.md
Labels: :white_check_mark: Approved

#3862 Convert mobile Accounts.jsx to tsx
  packages/desktop-client/src/components/accounts/Account.tsx
  packages/desktop-client/src/components/mobile/accounts/Accounts.tsx
  packages/loot-core/src/client/reducers/queries.ts
  packages/loot-core/src/client/state-types/queries.d.ts
  upcoming-release-notes/3862.md
Labels: :white_check_mark: Approved

#3871 🔧 Summary Card: Change the font size implementation to be simpler & fix import dashboard
  packages/desktop-client/src/components/reports/SummaryNumber.tsx
  packages/loot-core/src/server/dashboard/app.ts
  upcoming-release-notes/3871.md
Labels: :white_check_mark: Approved

#3882 🐛 Fix performance when navigating between budget/accounts
  packages/desktop-client/src/components/spreadsheet/useSheetValue.ts
  upcoming-release-notes/3882.md
Labels: :white_check_mark: Approved

#3905 Fix mobile transaction edit page's back button behavior
  packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
  upcoming-release-notes/3905.md
Labels: :white_check_mark: Approved
