Repository actualbudget/actual, pull requests merged in 2024-09, with the labels that each got.

#3337 :bug: fix schedules modal closing when selecting link transactions
  packages/desktop-client/src/components/table.tsx
  upcoming-release-notes/3337.md
Labels: :white_check_mark: Approved

#3340 :bug: fix long payee name overflow
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  upcoming-release-notes/3340.md
Labels: :white_check_mark: Approved

#3338 :bug: fix reconciliation closing on enter click
  packages/desktop-client/src/components/accounts/Reconcile.jsx
  upcoming-release-notes/3338.md
Labels: :white_check_mark: Approved

#3342 🐛 Fix tooltip when using touch devices
  packages/desktop-client/src/components/common/Tooltip.tsx
  upcoming-release-notes/3342.md
Labels: :white_check_mark: Approved

#3277 🌍 add translations for `desktop-client/components/accounts`
  packages/desktop-client/src/components/accounts/Account.jsx
  packages/desktop-client/src/components/accounts/AccountSyncCheck.jsx
  packages/desktop-client/src/components/accounts/Balance.jsx
  packages/desktop-client/src/components/accounts/Header.jsx
  packages/desktop-client/src/components/accounts/Reconcile.jsx
  upcoming-release-notes/3277.md
Labels: :white_check_mark: Approved

#3313 Translation: desktop-client/components/schedules
  packages/desktop-client/src/components/schedules/DiscoverSchedules.tsx
  packages/desktop-client/src/components/schedules/PostsOfflineNotification.jsx
  packages/desktop-client/src/components/schedules/ScheduleDetails.jsx
  packages/desktop-client/src/components/schedules/ScheduleLink.tsx
  packages/desktop-client/src/components/schedules/SchedulesTable.tsx
  packages/desktop-client/src/components/schedules/index.tsx
  packages/desktop-client/src/hooks/useFormatList.ts
  upcoming-release-notes/3313.md
Labels: :white_check_mark: Approved

#3288 ✨ (dashboards) text widget
  packages/desktop-client/src/components/Notes.tsx
  packages/desktop-client/src/components/reports/Overview.tsx
  packages/desktop-client/src/components/reports/ReportCardName.tsx
  packages/desktop-client/src/components/reports/reports/MarkdownCard.tsx
  packages/loot-core/src/server/dashboard/app.ts
  packages/loot-core/src/types/models/dashboard.d.ts
  upcoming-release-notes/3288.md
Labels: :white_check_mark: Approved

#3356 fix incorrect hook usage in #3277
  packages/desktop-client/src/components/accounts/Account.tsx
  upcoming-release-notes/3356.md
Labels: :white_check_mark: Approved

#3355 :recycle: (typescript) migrate reconcile file to TS
  packages/desktop-client/src/components/accounts/Reconcile.tsx
  packages/desktop-client/src/components/spreadsheet/index.ts
  packages/loot-core/src/client/queries.ts
  upcoming-release-notes/3355.md
Labels: :white_check_mark: Approved

#3085 [Mobile] Budget page actions undo notifications
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/budget/report/ReportComponents.tsx
  packages/desktop-client/src/components/budget/rollover/RolloverComponents.tsx
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  packages/desktop-client/src/components/mobile/transactions/Transaction.jsx
  packages/desktop-client/src/components/modals/ReportBudgetMonthMenuModal.tsx
  packages/desktop-client/src/components/modals/RolloverBudgetMonthMenuModal.tsx
  packages/desktop-client/src/components/modals/RolloverBudgetSummaryModal.tsx
  upcoming-release-notes/3085.md
Labels: :white_check_mark: Approved

#3344 enhance mobile header links
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-7-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-8-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-9-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-loads-the-budget-page-with-budgeted-amounts-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-loads-the-budget-page-with-budgeted-amounts-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-loads-the-budget-page-with-budgeted-amounts-3-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-3-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-4-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-5-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-6-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-7-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-8-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-9-chromium-linux.png
  packages/desktop-client/src/components/mobile/accounts/AccountTransactions.jsx
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  packages/desktop-client/src/style/styles.ts
  upcoming-release-notes/3344.md
Labels: :white_check_mark: Approved

#3367 [WIP] Translation: desktop-client/src/components/budget/BudgetTotals.tsx
  packages/desktop-client/src/components/budget/BudgetTotals.tsx
  upcoming-release-notes/3367.md
Labels: :construction: WIP

#3119 Auto notes when transferring budgets
  packages/desktop-client/e2e/budget.test.js-snapshots/Budget-transfer-funds-to-another-category-1-chromium-linux.png
  packages/desktop-client/e2e/budget.test.js-snapshots/Budget-transfer-funds-to-another-category-2-chromium-linux.png
  packages/desktop-client/e2e/budget.test.js-snapshots/Budget-transfer-funds-to-another-category-3-chromium-linux.png
  packages/desktop-client/src/components/budget/report/ReportComponents.tsx
  packages/desktop-client/src/components/budget/rollover/BalanceMovementMenu.tsx
  packages/desktop-client/src/components/budget/rollover/RolloverComponents.tsx
  packages/loot-core/src/types/util.d.ts
  upcoming-release-notes/3119.md
Labels: :white_check_mark: Approved

#3379 Report Header: fix validateStart bug
  packages/desktop-client/src/components/reports/reportRanges.ts
  upcoming-release-notes/3379.md
Labels: :white_check_mark: Approved

#3389 :electron: Prevent keyboard shortcuts modal when entering shortcut into editable field
  packages/desktop-client/src/index.tsx
  packages/desktop-electron/menu.ts
  upcoming-release-notes/3389.md
Labels: :white_check_mark: Approved

#3325 add option to select dark theme for "System default"
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-checks-that-settings-page-can-be-opened-4-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-checks-that-settings-page-can-be-opened-5-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-checks-that-settings-page-can-be-opened-6-chromium-linux.png
  packages/desktop-client/e2e/settings.test.js-snapshots/Settings-checks-the-page-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/settings.test.js-snapshots/Settings-checks-the-page-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/settings.test.js-snapshots/Settings-checks-the-page-visuals-3-chromium-linux.png
  packages/desktop-client/src/components/settings/Themes.tsx
  packages/desktop-client/src/style/theme.tsx
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/types/prefs.d.ts
  upcoming-release-notes/3325.md
Labels: :white_check_mark: Approved

#3332 set html theme-color to match the webmanifest
  packages/desktop-client/index.html
  upcoming-release-notes/3332.md
Labels: :white_check_mark: Approved

#3393 🔧 Prevent sidebar from saving to metadata until resize is complete
  packages/desktop-client/src/components/sidebar/Sidebar.tsx
  upcoming-release-notes/3393.md
Labels: :white_check_mark: Approved

#3394 🔧 Remove unneeded console log
  packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.tsx
  upcoming-release-notes/3394.md
Labels: :white_check_mark: Approved

#3391 Refine `Menu`/`Select` types to allow broader types for the `value`/`name` attribute
  packages/desktop-client/src/components/common/Menu.tsx
  packages/desktop-client/src/components/common/Select.tsx
  packages/desktop-client/src/components/reports/ReportSidebar.tsx
  packages/desktop-client/src/components/reports/SaveReportMenu.tsx
  upcoming-release-notes/3391.md
Labels: :white_check_mark: Approved

#3396 Convert `RecurringSchedulePicker.jsx` -> `RecurringSchedulePicker.tsx`
  packages/desktop-client/src/components/common/Select.tsx
  packages/desktop-client/src/components/forms.tsx
  packages/desktop-client/src/components/select/DateSelect.tsx
  packages/desktop-client/src/components/select/RecurringSchedulePicker.tsx
  packages/loot-core/src/types/models/schedule.d.ts
  upcoming-release-notes/3396.md
Labels: :white_check_mark: Approved

#3398 🔧 Prevent metadata.json update if the sync time value is the same
  packages/loot-core/src/server/sync/index.ts
  upcoming-release-notes/3398.md
Labels: :white_check_mark: Approved

#3395 :recycle: (synced-prefs) refactor some SyncedPrefs to string type
  packages/desktop-client/src/components/Titlebar.tsx
  packages/desktop-client/src/components/accounts/Account.tsx
  packages/desktop-client/src/components/mobile/accounts/Account.jsx
  packages/desktop-client/src/components/mobile/accounts/AccountTransactions.jsx
  packages/desktop-client/src/components/mobile/accounts/Accounts.jsx
  packages/desktop-client/src/components/mobile/budget/Category.tsx
  packages/desktop-client/src/components/mobile/budget/CategoryTransactions.jsx
  packages/desktop-client/src/components/mobile/budget/index.tsx
  packages/desktop-client/src/components/mobile/transactions/FocusableAmountInput.tsx
  packages/desktop-client/src/components/modals/ImportTransactions.jsx
  packages/desktop-client/src/components/settings/Experimental.tsx
  packages/desktop-client/src/components/settings/Format.tsx
  packages/desktop-client/src/components/util/AmountInput.tsx
  packages/desktop-client/src/hooks/useFeatureFlag.ts
  packages/desktop-client/src/hooks/usePrivacyMode.ts
  packages/loot-core/src/client/reducers/prefs.ts
  packages/loot-core/src/client/selectors.ts
  packages/loot-core/src/shared/util.ts
  packages/loot-core/src/types/prefs.d.ts
  tsconfig.json
  upcoming-release-notes/3395.md
Labels: :white_check_mark: Approved

#3400 Update splash background to match theming
  packages/desktop-client/public/site.webmanifest
  upcoming-release-notes/3400.md
Labels: :white_check_mark: Approved

#3397 :recycle: (synced-prefs) refactor number formatter away from redux
  packages/desktop-client/src/components/spreadsheet/useFormat.ts
  packages/desktop-client/src/hooks/useDateFormat.ts
  packages/desktop-client/src/hooks/useFeatureFlag.ts
  packages/loot-core/src/client/reducers/prefs.ts
  packages/loot-core/src/client/selectors.ts
  packages/loot-core/src/client/state-types/prefs.d.ts
  packages/loot-core/src/shared/util.ts
  upcoming-release-notes/3397.md
Labels: :white_check_mark: Approved

#3408 :recycle: (synced-prefs) refactor ImportedTransactions usage of prefs
  packages/desktop-client/src/components/modals/ImportTransactions.jsx
  packages/desktop-client/src/hooks/useSyncedPrefs.ts
  upcoming-release-notes/3408.md
Labels: :white_check_mark: Approved

#3364 :sparkles: (dashboards) ability to save net-worth widget details
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-cash-flow-graph-and-checks-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-cash-flow-graph-and-checks-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-cash-flow-graph-and-checks-visuals-3-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-graph-and-checks-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-graph-and-checks-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-graph-and-checks-visuals-3-chromium-linux.png
  packages/desktop-client/src/components/common/Button2.tsx
  packages/desktop-client/src/components/reports/Header.tsx
  packages/desktop-client/src/components/reports/Overview.tsx
  packages/desktop-client/src/components/reports/ReportRouter.tsx
  packages/desktop-client/src/components/reports/ReportSidebar.tsx
  packages/desktop-client/src/components/reports/getLiveRange.ts
  packages/desktop-client/src/components/reports/reportRanges.ts
  packages/desktop-client/src/components/reports/reports/CashFlow.tsx
  packages/desktop-client/src/components/reports/reports/NetWorth.jsx
  packages/desktop-client/src/components/reports/reports/NetWorthCard.tsx
  packages/desktop-client/src/hooks/useFilters.ts
  packages/loot-core/src/client/data-hooks/widget.ts
  packages/loot-core/src/types/models/dashboard.d.ts
  upcoming-release-notes/3364.md
Labels: :white_check_mark: Approved

#3163 [React Aria Button] All remaining components except filters, mobile transaction edit, and autocomplete
  packages/desktop-client/.gitignore
  packages/desktop-client/e2e/page-models/mobile-accounts-page.js
  packages/desktop-client/playwright.config.js
  packages/desktop-client/src/components/Titlebar.tsx
  packages/desktop-client/src/components/common/Link.tsx
  packages/desktop-client/src/components/common/Modal.tsx
  packages/desktop-client/src/components/common/Modal2.tsx
  packages/desktop-client/src/components/common/Search.tsx
  packages/desktop-client/src/components/common/Select.tsx
  packages/desktop-client/src/components/manager/ServerURL.tsx
  packages/desktop-client/src/components/manager/subscribe/Login.tsx
  packages/desktop-client/src/components/mobile/MobileBackButton.tsx
  packages/desktop-client/src/components/mobile/accounts/Account.jsx
  packages/desktop-client/src/components/mobile/accounts/Accounts.jsx
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  packages/desktop-client/src/components/mobile/transactions/AddTransactionButton.tsx
  packages/desktop-client/src/components/mobile/transactions/FocusableAmountInput.tsx
  packages/desktop-client/src/components/modals/CoverModal.tsx
  packages/desktop-client/src/components/reports/reports/CashFlow.tsx
  packages/desktop-client/src/components/reports/reports/CustomReport.tsx
  packages/desktop-client/src/components/reports/reports/NetWorth.jsx
  packages/desktop-client/src/components/reports/reports/Spending.tsx
  packages/desktop-client/src/components/sidebar/Account.tsx
  packages/desktop-client/src/components/sidebar/Item.tsx
  packages/desktop-client/src/components/sidebar/ItemContent.tsx
  packages/desktop-client/src/components/table.tsx
  upcoming-release-notes/3163.md
Labels: :white_check_mark: Approved

#3406 :electron: Adding retries in to the file system writes
  packages/loot-core/src/platform/server/fs/index.electron.ts
  upcoming-release-notes/3406.md
Labels: :white_check_mark: Approved

#3410 :recycle: (synced-prefs) moving budgetType pref back to MetadataPrefs
  packages/desktop-client/src/components/autocomplete/CategoryAutocomplete.tsx
  packages/desktop-client/src/components/budget/index.tsx
  packages/desktop-client/src/components/budget/util.ts
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  packages/desktop-client/src/components/mobile/budget/index.tsx
  packages/desktop-client/src/components/settings/BudgetTypeSettings.tsx
  packages/desktop-client/src/components/settings/Experimental.tsx
  packages/loot-core/src/server/prefs.ts
  packages/loot-core/src/types/prefs.d.ts
  upcoming-release-notes/3410.md
Labels: :white_check_mark: Approved

#3380 Spending Report: Header update
  packages/desktop-client/src/components/reports/DateRange.tsx
  packages/desktop-client/src/components/reports/graphs/SpendingGraph.tsx
  packages/desktop-client/src/components/reports/reports/Spending.tsx
  packages/desktop-client/src/components/reports/reports/SpendingCard.tsx
  packages/desktop-client/src/components/reports/spreadsheets/spending-spreadsheet.ts
  packages/loot-core/src/types/models/reports.d.ts
  packages/loot-core/src/types/prefs.d.ts
  upcoming-release-notes/3380.md
Labels: :white_check_mark: Approved

#3352 Translation: desktop-client/src/components/budget/BalanceWithCarryover.tsx
  packages/desktop-client/src/components/budget/BalanceWithCarryover.tsx
  upcoming-release-notes/3352.md
Labels: :white_check_mark: Approved

#3426 Translation for IncomeHeader, BalanceMenu & BudgetMenu .tsx
  packages/desktop-client/src/components/budget/IncomeHeader.tsx
  packages/desktop-client/src/components/budget/rollover/BalanceMenu.tsx
  packages/desktop-client/src/components/budget/rollover/BudgetMenu.tsx
  upcoming-release-notes/3426.md
Labels: :white_check_mark: Approved

#3417 ✨ (dashboards) ability to save cash-flow report filters/date-range
  .eslintignore
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-cash-flow-graph-and-checks-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-cash-flow-graph-and-checks-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-cash-flow-graph-and-checks-visuals-3-chromium-linux.png
  packages/desktop-client/src/components/reports/Header.tsx
  packages/desktop-client/src/components/reports/Overview.tsx
  packages/desktop-client/src/components/reports/ReportRouter.tsx
  packages/desktop-client/src/components/reports/graphs/CashFlowGraph.tsx
  packages/desktop-client/src/components/reports/reportRanges.ts
  packages/desktop-client/src/components/reports/reports/CashFlow.tsx
  packages/desktop-client/src/components/reports/reports/CashFlowCard.tsx
  packages/desktop-client/src/components/reports/reports/NetWorth.jsx
  packages/desktop-client/src/components/reports/spreadsheets/cash-flow-spreadsheet.tsx
  packages/desktop-client/src/components/reports/spreadsheets/net-worth-spreadsheet.ts
  packages/loot-core/src/client/data-hooks/widget.ts
  packages/loot-core/src/shared/months.ts
  packages/loot-core/src/types/models/dashboard.d.ts
  tsconfig.json
  upcoming-release-notes/3417.md
Labels: :white_check_mark: Approved

#3430 Marked files for translation
  packages/desktop-client/src/components/FatalError.tsx
  packages/desktop-client/src/components/LoggedInUser.tsx
  packages/desktop-client/src/components/gocardless/GoCardlessLink.tsx
  packages/desktop-client/src/components/manager/BudgetList.tsx
  packages/desktop-client/src/components/modals/GoCardlessExternalMsgModal.tsx
  upcoming-release-notes/3430.md
Labels: :white_check_mark: Approved

#3448 [Maintenance] Reduce budget table re-renders
  packages/desktop-client/src/components/mobile/budget/index.tsx
  upcoming-release-notes/3448.md
Labels: :white_check_mark: Approved

#3441 :bug: fix account filters being overridden
  packages/desktop-client/src/components/accounts/Account.tsx
  upcoming-release-notes/3441.md
Labels: :white_check_mark: Approved

#3443 :electron: Reduce package size
  packages/desktop-electron/beforePackHook.ts
  packages/desktop-electron/package.json
  upcoming-release-notes/3443.md
Labels: :white_check_mark: Approved

#3450 [Maintenance] Cleanup react aria packages and dedupe
  packages/desktop-client/package.json
  packages/desktop-client/src/components/filters/FiltersMenu.jsx
  packages/desktop-client/src/components/mobile/transactions/ListBox.jsx
  packages/desktop-client/src/components/mobile/transactions/ListBoxSection.jsx
  packages/desktop-client/src/components/mobile/transactions/Option.jsx
  packages/desktop-client/src/components/mobile/transactions/Transaction.jsx
  packages/desktop-client/src/components/mobile/transactions/TransactionList.jsx
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  upcoming-release-notes/3450.md
  yarn.lock
Labels: :white_check_mark: Approved

#3431 :electron: Restart server silently when adding self signed cert and add some logs
  packages/desktop-client/src/browser-preload.browser.js
  packages/desktop-client/src/components/manager/ConfigServer.tsx
  packages/desktop-client/src/hooks/useGlobalPref.ts
  packages/desktop-electron/index.ts
  packages/desktop-electron/preload.ts
  packages/loot-core/src/client/actions/prefs.ts
  packages/loot-core/src/platform/server/fetch/index.electron.ts
  packages/loot-core/typings/window.d.ts
  upcoming-release-notes/3431.md
Labels: :white_check_mark: Approved

#3427 :recycle: (synced-prefs) move budget type to synced prefs
  packages/desktop-client/src/components/autocomplete/CategoryAutocomplete.tsx
  packages/desktop-client/src/components/budget/index.tsx
  packages/desktop-client/src/components/budget/util.ts
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  packages/desktop-client/src/components/mobile/budget/index.tsx
  packages/desktop-client/src/components/settings/BudgetTypeSettings.tsx
  packages/desktop-client/src/components/settings/Experimental.tsx
  packages/loot-core/migrations/1723665565000_prefs.js
  packages/loot-core/src/server/budget/actions.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/server/prefs.ts
  packages/loot-core/src/server/sheet.ts
  packages/loot-core/src/server/sync/index.ts
  packages/loot-core/src/types/prefs.d.ts
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/3352.md
  upcoming-release-notes/3427.md
Labels: :white_check_mark: Approved

#3452 update synced account balance in db if available
  packages/loot-core/src/server/accounts/sync.ts
  upcoming-release-notes/3452.md
Labels: :white_check_mark: Approved

#3460 :bug: (synced-prefs) fix bulk-reading not working in import modal
  packages/desktop-client/src/hooks/useSyncedPrefs.ts
  packages/loot-core/src/client/query-hooks.tsx
  upcoming-release-notes/3460.md
Labels: :white_check_mark: Approved

#3456 fix: csv import deduplication
  packages/desktop-client/src/components/modals/ImportTransactionsModal.jsx
  upcoming-release-notes/3456.md
Labels: :white_check_mark: Approved

#3459 :sparkles: release simplefin as a first-party feature
  packages/desktop-client/src/components/modals/CreateAccountModal.tsx
  packages/desktop-client/src/components/settings/Experimental.tsx
  packages/desktop-client/src/hooks/useFeatureFlag.ts
  packages/loot-core/src/types/prefs.d.ts
  upcoming-release-notes/3459.md
Labels: :white_check_mark: Approved

#3463 Do not allow renaming to an empty category or group name
  packages/desktop-client/src/components/modals/CategoryGroupMenuModal.tsx
  packages/desktop-client/src/components/modals/CategoryMenuModal.tsx
  upcoming-release-notes/3463.md
Labels: :white_check_mark: Approved

#3374 [Mobile] Fix #3214 - Pull down to refresh triggering clicks on budget cells
  packages/desktop-client/e2e/budget.test.js-snapshots/Budget-transfer-funds-to-another-category-1-chromium-linux.png
  packages/desktop-client/e2e/budget.test.js-snapshots/Budget-transfer-funds-to-another-category-2-chromium-linux.png
  packages/desktop-client/e2e/budget.test.js-snapshots/Budget-transfer-funds-to-another-category-3-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-loads-the-budget-page-with-budgeted-amounts-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-loads-the-budget-page-with-budgeted-amounts-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-loads-the-budget-page-with-budgeted-amounts-3-chromium-linux.png
  packages/desktop-client/src/components/accounts/Balance.jsx
  packages/desktop-client/src/components/budget/BalanceWithCarryover.tsx
  packages/desktop-client/src/components/budget/report/ReportComponents.tsx
  packages/desktop-client/src/components/budget/report/budgetsummary/BudgetTotal.tsx
  packages/desktop-client/src/components/budget/rollover/RolloverComponents.tsx
  packages/desktop-client/src/components/budget/rollover/budgetsummary/TotalsList.tsx
  packages/desktop-client/src/components/mobile/accounts/Accounts.jsx
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  packages/desktop-client/src/components/mobile/transactions/TransactionListWithBalances.jsx
  packages/desktop-client/src/components/modals/ReportBalanceMenuModal.tsx
  packages/desktop-client/src/components/modals/RolloverBalanceMenuModal.tsx
  packages/desktop-client/src/components/spreadsheet/CellValue.tsx
  upcoming-release-notes/3374.md
Labels: :white_check_mark: Approved

#3462 Fix reports form submit handlers
  packages/desktop-client/src/components/reports/SaveReportChoose.tsx
  packages/desktop-client/src/components/reports/SaveReportName.tsx
  upcoming-release-notes/3462.md
Labels: :white_check_mark: Approved

#3468 :electron: Remove some old updater code
  packages/desktop-client/src/global-events.ts
  upcoming-release-notes/3468.md
Labels: :white_check_mark: Approved

#3467 CSV import e2e tests
  packages/desktop-client/e2e/accounts.test.js
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-Import-Transactions-import-csv-file-twice-1-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-Import-Transactions-import-csv-file-twice-2-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-Import-Transactions-import-csv-file-twice-3-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-Import-Transactions-imports-transactions-from-a-CSV-file-1-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-Import-Transactions-imports-transactions-from-a-CSV-file-2-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-Import-Transactions-imports-transactions-from-a-CSV-file-3-chromium-linux.png
  packages/desktop-client/e2e/data/test.csv
  packages/desktop-client/e2e/page-models/close-account-modal.js
  packages/desktop-client/src/components/modals/CloseAccountModal.tsx
  upcoming-release-notes/3467.md
Labels: :white_check_mark: Approved

#3453 Fix React Aria Button hover styles
  packages/desktop-client/src/components/Notifications.tsx
  packages/desktop-client/src/components/Titlebar.tsx
  packages/desktop-client/src/components/common/Button2.tsx
  packages/desktop-client/src/components/common/Link.tsx
  packages/desktop-client/src/components/common/Select.tsx
  packages/desktop-client/src/components/mobile/MobileBackButton.tsx
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  packages/desktop-client/src/components/modals/EditRuleModal.jsx
  packages/desktop-client/src/components/modals/ImportTransactionsModal.jsx
  packages/desktop-client/src/components/modals/ReportBudgetMonthMenuModal.tsx
  packages/desktop-client/src/components/modals/RolloverBudgetMonthMenuModal.tsx
  packages/desktop-client/src/components/reports/Header.tsx
  packages/desktop-client/src/components/select/RecurringSchedulePicker.tsx
  packages/desktop-client/src/components/settings/Format.tsx
  packages/desktop-client/src/components/settings/Themes.tsx
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  upcoming-release-notes/3453.md
Labels: :white_check_mark: Approved

#3411 Undoable auto transfer notes + auto notes for cover
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/budget/rollover/BalanceMovementMenu.tsx
  packages/desktop-client/src/components/budget/rollover/CoverMenu.tsx
  packages/desktop-client/src/components/budget/rollover/TransferMenu.tsx
  packages/desktop-client/src/components/budget/util.ts
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  packages/desktop-client/src/components/modals/CoverModal.tsx
  packages/desktop-client/src/components/modals/TransferModal.tsx
  packages/loot-core/src/client/state-types/modals.d.ts
  packages/loot-core/src/server/budget/actions.ts
  packages/loot-core/src/server/db/index.ts
  packages/loot-core/src/server/notes/app.ts
  upcoming-release-notes/3411.md
Labels: :white_check_mark: Approved

#3474 Revert "CSV import e2e tests"
  packages/desktop-client/e2e/accounts.test.js
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-Import-Transactions-import-csv-file-twice-1-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-Import-Transactions-import-csv-file-twice-2-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-Import-Transactions-import-csv-file-twice-3-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-Import-Transactions-imports-transactions-from-a-CSV-file-1-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-Import-Transactions-imports-transactions-from-a-CSV-file-2-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-Import-Transactions-imports-transactions-from-a-CSV-file-3-chromium-linux.png
  packages/desktop-client/e2e/data/test.csv
  packages/desktop-client/e2e/page-models/close-account-modal.js
  packages/desktop-client/src/components/modals/CloseAccountModal.tsx
  upcoming-release-notes/3467.md
Labels: :white_check_mark: Approved

#3458 :recycle: (synced-prefs) separate metadata and local prefs out
  packages/desktop-client/src/components/FinancesApp.tsx
  packages/desktop-client/src/hooks/useLocalPref.ts
  packages/desktop-client/src/hooks/useMetadataPref.ts
  packages/loot-core/src/client/actions/prefs.ts
  packages/loot-core/src/client/state-types/prefs.d.ts
  packages/loot-core/src/client/update-notification.ts
  packages/loot-core/src/server/sync/index.ts
  packages/loot-core/src/types/prefs.d.ts
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/3458.md
Labels: :white_check_mark: Approved

#3475 :electron: Replace deprecated file protocol registration
  packages/desktop-electron/index.ts
  upcoming-release-notes/3475.md
Labels: :white_check_mark: Approved

#3480 update sql regexp to default to empty string when field is null
  packages/loot-core/src/platform/server/sqlite/index.electron.ts
  packages/loot-core/src/platform/server/sqlite/index.web.test.ts
  packages/loot-core/src/platform/server/sqlite/index.web.ts
  upcoming-release-notes/3480.md
Labels: :white_check_mark: Approved

#3483 ♻️ rename report/rollover budget to tracking/envelope
  .eslintrc.js
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/autocomplete/CategoryAutocomplete.tsx
  packages/desktop-client/src/components/budget/BalanceWithCarryover.tsx
  packages/desktop-client/src/components/budget/BudgetSummaries.tsx
  packages/desktop-client/src/components/budget/envelope/BalanceMenu.tsx
  packages/desktop-client/src/components/budget/envelope/BalanceMovementMenu.tsx
  packages/desktop-client/src/components/budget/envelope/BudgetMenu.tsx
  packages/desktop-client/src/components/budget/envelope/CoverMenu.tsx
  packages/desktop-client/src/components/budget/envelope/EnvelopeBudgetComponents.tsx
  packages/desktop-client/src/components/budget/envelope/EnvelopeBudgetContext.tsx
  packages/desktop-client/src/components/budget/envelope/HoldMenu.tsx
  packages/desktop-client/src/components/budget/envelope/TransferMenu.tsx
  packages/desktop-client/src/components/budget/envelope/budgetsummary/BudgetMonthMenu.tsx
  packages/desktop-client/src/components/budget/envelope/budgetsummary/BudgetSummary.tsx
  packages/desktop-client/src/components/budget/envelope/budgetsummary/ToBudget.tsx
  packages/desktop-client/src/components/budget/envelope/budgetsummary/ToBudgetAmount.tsx
  packages/desktop-client/src/components/budget/envelope/budgetsummary/ToBudgetMenu.tsx
  packages/desktop-client/src/components/budget/envelope/budgetsummary/TotalsList.tsx
  packages/desktop-client/src/components/budget/index.tsx
  packages/desktop-client/src/components/budget/tracking/BalanceMenu.tsx
  packages/desktop-client/src/components/budget/tracking/BudgetMenu.tsx
  packages/desktop-client/src/components/budget/tracking/TrackingBudgetComponents.tsx
  packages/desktop-client/src/components/budget/tracking/TrackingBudgetContext.tsx
  packages/desktop-client/src/components/budget/tracking/budgetsummary/BudgetMonthMenu.tsx
  packages/desktop-client/src/components/budget/tracking/budgetsummary/BudgetSummary.tsx
  packages/desktop-client/src/components/budget/tracking/budgetsummary/BudgetTotal.tsx
  packages/desktop-client/src/components/budget/tracking/budgetsummary/ExpenseProgress.tsx
  packages/desktop-client/src/components/budget/tracking/budgetsummary/ExpenseTotal.tsx
  packages/desktop-client/src/components/budget/tracking/budgetsummary/IncomeProgress.tsx
  packages/desktop-client/src/components/budget/tracking/budgetsummary/IncomeTotal.tsx
  packages/desktop-client/src/components/budget/tracking/budgetsummary/PieProgress.tsx
  packages/desktop-client/src/components/budget/tracking/budgetsummary/Saved.tsx
  packages/desktop-client/src/components/budget/tracking/budgetsummary/fraction.ts
  packages/desktop-client/src/components/budget/util.ts
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  packages/desktop-client/src/components/mobile/budget/index.tsx
  packages/desktop-client/src/components/modals/EnvelopeBalanceMenuModal.tsx
  packages/desktop-client/src/components/modals/EnvelopeBudgetMenuModal.tsx
  packages/desktop-client/src/components/modals/EnvelopeBudgetMonthMenuModal.tsx
  packages/desktop-client/src/components/modals/EnvelopeBudgetSummaryModal.tsx
  packages/desktop-client/src/components/modals/EnvelopeToBudgetMenuModal.tsx
  packages/desktop-client/src/components/modals/HoldBufferModal.tsx
  packages/desktop-client/src/components/modals/TrackingBalanceMenuModal.tsx
  packages/desktop-client/src/components/modals/TrackingBudgetMenuModal.tsx
  packages/desktop-client/src/components/modals/TrackingBudgetMonthMenuModal.tsx
  packages/desktop-client/src/components/modals/TrackingBudgetSummaryModal.tsx
  packages/desktop-client/src/components/settings/BudgetTypeSettings.tsx
  packages/desktop-client/src/components/settings/Experimental.tsx
  packages/desktop-client/src/components/spreadsheet/index.ts
  packages/loot-core/src/client/queries.ts
  packages/loot-core/src/client/state-types/modals.d.ts
  packages/loot-core/src/server/budget/base.ts
  packages/loot-core/src/server/budget/envelope.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/3483.md
Labels: :white_check_mark: Approved

#3478 :bug: (import) fix csv import checkboxes not working
  packages/desktop-client/src/components/modals/ImportTransactionsModal.jsx
  upcoming-release-notes/3478.md
Labels: :white_check_mark: Approved

#3487 fix modals on mobile BudgetTable
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  upcoming-release-notes/3487.md
Labels: :white_check_mark: Approved

#3472 Fix privacy filter
  packages/desktop-client/src/components/accounts/Balance.jsx
  packages/desktop-client/src/components/budget/BalanceWithCarryover.tsx
  packages/desktop-client/src/components/budget/envelope/EnvelopeBudgetComponents.tsx
  packages/desktop-client/src/components/budget/tracking/TrackingBudgetComponents.tsx
  packages/desktop-client/src/components/spreadsheet/CellValue.tsx
  upcoming-release-notes/3472.md
Labels: :white_check_mark: Approved

#3484 :bug: fix custom reports crashing when opening table
  packages/desktop-client/src/components/reports/reports/CustomReport.tsx
  upcoming-release-notes/3484.md
Labels: :white_check_mark: Approved

#3493 :test_tube: (tests) adding custom report e2e tests
  packages/desktop-client/e2e/page-models/custom-report-page.js
  packages/desktop-client/e2e/page-models/reports-page.js
  packages/desktop-client/e2e/reports.test.js
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-custom-reports-Switches-to-Area-Graph-and-checks-the-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-custom-reports-Switches-to-Area-Graph-and-checks-the-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-custom-reports-Switches-to-Area-Graph-and-checks-the-visuals-3-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-custom-reports-Switches-to-Bar-Graph-and-checks-the-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-custom-reports-Switches-to-Bar-Graph-and-checks-the-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-custom-reports-Switches-to-Bar-Graph-and-checks-the-visuals-3-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-custom-reports-Switches-to-Data-Table-and-checks-the-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-custom-reports-Switches-to-Data-Table-and-checks-the-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-custom-reports-Switches-to-Data-Table-and-checks-the-visuals-3-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-custom-reports-Switches-to-Donut-Graph-and-checks-the-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-custom-reports-Switches-to-Donut-Graph-and-checks-the-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-custom-reports-Switches-to-Donut-Graph-and-checks-the-visuals-3-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-custom-reports-Switches-to-Line-Graph-and-checks-the-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-custom-reports-Switches-to-Line-Graph-and-checks-the-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-custom-reports-Switches-to-Line-Graph-and-checks-the-visuals-3-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-custom-reports-Validates-that-show-labels-button-shows-the-labels-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-custom-reports-Validates-that-show-labels-button-shows-the-labels-2-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-custom-reports-Validates-that-show-labels-button-shows-the-labels-3-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-custom-reports-Validates-that-show-legend-button-shows-the-legend-side-bar-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-custom-reports-Validates-that-show-legend-button-shows-the-legend-side-bar-2-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-custom-reports-Validates-that-show-legend-button-shows-the-legend-side-bar-3-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-custom-reports-Validates-that-show-summary-button-shows-the-summary-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-custom-reports-Validates-that-show-summary-button-shows-the-summary-2-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-custom-reports-Validates-that-show-summary-button-shows-the-summary-3-chromium-linux.png
  packages/desktop-client/src/components/reports/GraphButton.tsx
  upcoming-release-notes/3493.md
Labels: :white_check_mark: Approved

#3432 :sparkles: (dashboards) ability to save filters & timeframes on spending widgets
  packages/desktop-client/src/components/common/Select.tsx
  packages/desktop-client/src/components/reports/DateRange.tsx
  packages/desktop-client/src/components/reports/Header.tsx
  packages/desktop-client/src/components/reports/Overview.tsx
  packages/desktop-client/src/components/reports/ReportRouter.tsx
  packages/desktop-client/src/components/reports/graphs/SpendingGraph.tsx
  packages/desktop-client/src/components/reports/reportRanges.ts
  packages/desktop-client/src/components/reports/reports/Spending.tsx
  packages/desktop-client/src/components/reports/reports/SpendingCard.tsx
  packages/desktop-client/src/components/reports/spreadsheets/spending-spreadsheet.ts
  packages/loot-core/src/types/models/dashboard.d.ts
  packages/loot-core/src/types/models/reports.d.ts
  packages/loot-core/src/types/prefs.d.ts
  upcoming-release-notes/3432.md
Labels: :white_check_mark: Approved

#3491 Fix mobile page header buttons
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-loads-the-budget-page-with-budgeted-amounts-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-loads-the-budget-page-with-budgeted-amounts-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-loads-the-budget-page-with-budgeted-amounts-3-chromium-linux.png
  packages/desktop-client/src/components/Page.tsx
  packages/desktop-client/src/components/common/Button2.tsx
  packages/desktop-client/src/components/mobile/MobileBackButton.tsx
  packages/desktop-client/src/components/mobile/MobileNavTabs.tsx
  packages/desktop-client/src/components/mobile/accounts/AccountTransactions.jsx
  packages/desktop-client/src/components/mobile/accounts/Accounts.jsx
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  packages/desktop-client/src/components/mobile/transactions/AddTransactionButton.tsx
  packages/desktop-client/src/components/mobile/transactions/FocusableAmountInput.tsx
  upcoming-release-notes/3491.md
Labels: :white_check_mark: Approved

#3498 :test_tube: improving rules e2e test stability
  packages/desktop-client/src/components/ManageRules.tsx
  upcoming-release-notes/3498.md
Labels: :mag: Ready for review

#3451 SpendingReport: Fixing some display issues
  packages/desktop-client/src/components/reports/LegendItem.tsx
  packages/desktop-client/src/components/reports/ReportLegend.tsx
  packages/desktop-client/src/components/reports/graphs/SpendingGraph.tsx
  packages/desktop-client/src/components/reports/reports/Spending.tsx
  packages/desktop-client/src/style/themes/dark.ts
  packages/desktop-client/src/style/themes/development.ts
  packages/desktop-client/src/style/themes/light.ts
  packages/desktop-client/src/style/themes/midnight.ts
  upcoming-release-notes/3451.md
Labels: :white_check_mark: Approved

#3501 Update README.md to fix typo
  README.md
  upcoming-release-notes/3501.md
Labels: :white_check_mark: Approved

#3497 fix: vrt:docker with git-bash
  bin/run-vrt
  upcoming-release-notes/3497.md
Labels: :white_check_mark: Approved

#3495 Fix issue #3252 remove extra space from category name
  packages/loot-core/src/server/main.ts
  upcoming-release-notes/3495.md
Labels: :white_check_mark: Approved

#3286 Forcibly reload app from server when API is redirected
  packages/desktop-client/src/browser-preload.browser.js
  packages/desktop-client/src/global-events.ts
  packages/loot-core/src/client/actions/app.ts
  packages/loot-core/src/platform/server/fetch/index.web.ts
  packages/loot-core/src/types/server-events.d.ts
  packages/loot-core/typings/window.d.ts
  upcoming-release-notes/3286.md
Labels: :white_check_mark: Approved

#3503 :test_tube: improve onboarding e2e test stability
  packages/desktop-client/src/components/FinancesApp.tsx
  upcoming-release-notes/3503.md
Labels: :white_check_mark: Approved

#3326 Add UncategorizedButton to mobile budget view
  packages/desktop-client/src/components/common/Link.tsx
  packages/desktop-client/src/components/mobile/accounts/Account.jsx
  packages/desktop-client/src/components/mobile/accounts/Account.tsx
  packages/desktop-client/src/components/mobile/accounts/AccountTransactions.jsx
  packages/desktop-client/src/components/mobile/accounts/AccountTransactions.tsx
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  packages/desktop-client/src/components/mobile/transactions/AddTransactionButton.tsx
  packages/desktop-client/src/components/mobile/transactions/TransactionListWithBalances.jsx
  packages/desktop-client/src/hooks/usePreviewTransactions.ts
  packages/loot-core/src/client/query-helpers.ts
  upcoming-release-notes/3326.md
Labels: :white_check_mark: Approved

#3412 Fix Issue 3331, sort favorite payees before other frequently used payees
  packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.test.tsx
  packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.tsx
  packages/desktop-client/src/components/transactions/TransactionsTable.test.jsx
  packages/loot-core/src/mocks/index.ts
  upcoming-release-notes/3412.md
Labels: :white_check_mark: Approved

#3492 Fix mobile balance modal colors
  packages/desktop-client/src/components/budget/BalanceWithCarryover.tsx
  packages/desktop-client/src/components/budget/tracking/TrackingBudgetComponents.tsx
  packages/desktop-client/src/components/modals/EnvelopeBalanceMenuModal.tsx
  packages/desktop-client/src/components/modals/TrackingBalanceMenuModal.tsx
  upcoming-release-notes/3492.md
Labels: :white_check_mark: Approved

#3509 add disable option for ToBudgetAmount popover when displaying modal
  packages/desktop-client/src/components/modals/EnvelopeBudgetSummaryModal.tsx
  upcoming-release-notes/3509.md
Labels: :white_check_mark: Approved

#3377 Privacy mode: instead of blurring, use an illegible font (#3376)
  packages/desktop-client/package.json
  packages/desktop-client/src/components/PrivacyFilter.tsx
  packages/desktop-client/src/components/budget/envelope/EnvelopeBudgetComponents.tsx
  packages/desktop-client/src/components/budget/envelope/budgetsummary/ToBudgetAmount.tsx
  packages/desktop-client/src/components/budget/tracking/TrackingBudgetComponents.tsx
  packages/desktop-client/src/components/budget/tracking/budgetsummary/Saved.tsx
  packages/desktop-client/src/components/reports/ReportSummary.tsx
  packages/desktop-client/src/components/reports/reports/CustomReport.tsx
  packages/desktop-client/src/components/reports/reports/NetWorth.jsx
  packages/desktop-client/src/components/reports/reports/Spending.tsx
  packages/desktop-client/src/components/table.tsx
  packages/desktop-client/src/fonts.scss
  upcoming-release-notes/3377.md
  yarn.lock
Labels: :white_check_mark: Approved

#3513 :test_tube: improve setting e2e test stability
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-checks-that-settings-page-can-be-opened-4-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-checks-that-settings-page-can-be-opened-5-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-checks-that-settings-page-can-be-opened-6-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-from-accounts-id-page-2-chromium-linux.png
  packages/desktop-client/e2e/settings.test.js-snapshots/Settings-checks-the-page-visuals-1-chromium-linux.png
  packages/desktop-client/playwright.config.js
  packages/desktop-client/src/style/theme.tsx
  upcoming-release-notes/3513.md
Labels: :white_check_mark: Approved

#3512 :test_tube: improving rules test e2e stability
  packages/desktop-client/src/components/ManageRules.tsx
  packages/desktop-client/src/components/reports/reports/CashFlow.tsx
  packages/desktop-client/src/components/reports/reports/Spending.tsx
  packages/desktop-client/src/components/rules/ScheduleValue.tsx
  packages/desktop-client/src/components/rules/SchedulesQuery.ts
  packages/desktop-client/src/hooks/useSchedules.ts
  packages/loot-core/src/client/query-hooks.ts
  packages/loot-core/src/client/query-hooks.tsx
  upcoming-release-notes/3512.md
Labels: :white_check_mark: Approved

#3514 Add goal info to the prewarm list
  packages/loot-core/src/server/main.ts
  upcoming-release-notes/3514.md
Labels: :white_check_mark: Approved

#3526 Fix electron build workflows for ubuntu-latest
  .github/workflows/electron-master.yml
  .github/workflows/electron-pr.yml
  upcoming-release-notes/3526.md
Labels: :white_check_mark: Approved

#3515 fix: pushModal not dispatched in GoCardless linking
  packages/desktop-client/src/gocardless.ts
  upcoming-release-notes/3515.md
Labels: :white_check_mark: Approved

#3525 pass causes along in failed-to-load exceptions
  packages/desktop-client/src/components/util/LoadComponent.tsx
  packages/loot-core/src/shared/errors.ts
  upcoming-release-notes/3525.md
Labels: :white_check_mark: Approved

#3399 Fix regression in case sensitivity for `is`/`matches` operator
  packages/desktop-client/src/components/filters/FiltersMenu.jsx
  packages/desktop-client/src/components/filters/updateFilterReducer.ts
  packages/desktop-client/src/components/modals/EditRuleModal.jsx
  packages/loot-core/src/server/accounts/rules.test.ts
  packages/loot-core/src/server/accounts/rules.ts
  packages/loot-core/src/server/accounts/transaction-rules.ts
  packages/loot-core/src/server/rules/app.ts
  packages/loot-core/src/server/schedules/app.ts
  packages/loot-core/src/shared/rules.ts
  packages/loot-core/src/types/models/rule.d.ts
  upcoming-release-notes/3399.md
Labels: :white_check_mark: Approved

#3523 [e2e stability] Check for data-theme before taking a screenshot
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-from-accounts-id-page-2-chromium-linux.png
  packages/desktop-client/playwright.config.js
  packages/desktop-client/src/components/App.tsx
  upcoming-release-notes/3523.md
Labels: :white_check_mark: Approved

#3521 Set theme-color at App level instead of per page
  packages/desktop-client/src/components/FinancesApp.tsx
  packages/desktop-client/src/components/manager/ConfigServer.tsx
  packages/desktop-client/src/components/manager/ManagementApp.jsx
  packages/desktop-client/src/components/mobile/accounts/Account.tsx
  packages/desktop-client/src/components/mobile/accounts/Accounts.jsx
  packages/desktop-client/src/components/mobile/budget/Category.tsx
  packages/desktop-client/src/components/mobile/budget/index.tsx
  packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
  packages/desktop-client/src/components/settings/index.tsx
  packages/desktop-client/src/hooks/useMetaThemeColor.ts
  upcoming-release-notes/3521.md
Labels: :white_check_mark: Approved

#3530 [e2e] Account page tests - wait for transaction table to be visible
  packages/desktop-client/e2e/onboarding.test.js
  packages/desktop-client/e2e/page-models/configuration-page.js
  upcoming-release-notes/3530.md
Labels: :white_check_mark: Approved
