Repository actualbudget/actual, pull requests merged in 2024-01, with the labels that each got.

#2140 :bug: (import) fix reconciled transactions getting overriden on import
  packages/loot-core/src/server/accounts/sync.ts
  upcoming-release-notes/2140.md
Labels: ✅ Approved

#2167 Fix load more when scrolling to end of rules table
  packages/desktop-client/src/components/ManageRules.tsx
  packages/desktop-client/src/components/rules/SimpleTable.tsx
Labels: ✅ Approved

#2166 Fix mobile transaction page amount input
  packages/desktop-client/src/components/mobile/MobileAmountInput.jsx
  packages/desktop-client/src/hooks/useSingleActiveEditForm.tsx
  upcoming-release-notes/2166.md
Labels: ✅ Approved

#2141 :bug: (rules) fix filtering in the rules page
  packages/desktop-client/src/components/ManageRules.tsx
  packages/desktop-client/src/components/rules/SimpleTable.tsx
  upcoming-release-notes/2141.md
Labels: ✅ Approved

#2177 :bookmark: (24.1.0) Mobile split transactions
  packages/api/package.json
  packages/desktop-client/package.json
  packages/desktop-electron/package.json
  upcoming-release-notes/1899.md
  upcoming-release-notes/1906.md
  upcoming-release-notes/1964.md
  upcoming-release-notes/1988.md
  upcoming-release-notes/1991.md
  upcoming-release-notes/1993.md
  upcoming-release-notes/2002.md
  upcoming-release-notes/2004.md
  upcoming-release-notes/2005.md
  upcoming-release-notes/2007.md
  upcoming-release-notes/2008.md
  upcoming-release-notes/2009.md
  upcoming-release-notes/2022.md
  upcoming-release-notes/2023.md
  upcoming-release-notes/2025.md
  upcoming-release-notes/2029.md
  upcoming-release-notes/2031.md
  upcoming-release-notes/2032.md
  upcoming-release-notes/2033.md
  upcoming-release-notes/2034.md
  upcoming-release-notes/2036.md
  upcoming-release-notes/2046.md
  upcoming-release-notes/2048.md
  upcoming-release-notes/2062.md
  upcoming-release-notes/2064.md
  upcoming-release-notes/2065.md
  upcoming-release-notes/2066.md
  upcoming-release-notes/2067.md
  upcoming-release-notes/2068.md
  upcoming-release-notes/2069.md
  upcoming-release-notes/2070.md
  upcoming-release-notes/2073.md
  upcoming-release-notes/2074.md
  upcoming-release-notes/2078.md
  upcoming-release-notes/2080.md
  upcoming-release-notes/2082.md
  upcoming-release-notes/2085.md
  upcoming-release-notes/2092.md
  upcoming-release-notes/2093.md
  upcoming-release-notes/2094.md
  upcoming-release-notes/2096.md
  upcoming-release-notes/2098.md
  upcoming-release-notes/2099.md
  upcoming-release-notes/2100.md
  upcoming-release-notes/2101.md
  upcoming-release-notes/2111.md
  upcoming-release-notes/2112.md
  upcoming-release-notes/2113.md
  upcoming-release-notes/2125.md
  upcoming-release-notes/2127.md
  upcoming-release-notes/2140.md
  upcoming-release-notes/2141.md
  upcoming-release-notes/2166.md
Labels: ✅ Approved

#2142 ♻️ (TypeScript) fix strictFunctionTypes violations (pt 4)
  packages/desktop-client/src/components/common/Menu.tsx
  packages/desktop-client/src/components/payees/PayeeTable.tsx
  packages/desktop-client/src/components/schedules/SchedulesTable.tsx
  packages/desktop-client/src/components/table.tsx
  packages/loot-core/src/server/sync/sync.property.test.ts
  upcoming-release-notes/2142.md
Labels: ✅ Approved

#2072 :recycle: (TypeScript) fix strictFunctionTypes violations (pt 5)
  packages/desktop-client/src/components/autocomplete/SavedFilterAutocomplete.tsx
  packages/desktop-client/src/hooks/useActions.ts
  packages/loot-core/src/platform/server/sqlite/index.electron.ts
  packages/loot-core/src/server/aql/compiler.ts
  packages/loot-core/src/server/aql/schema/index.ts
  packages/loot-core/src/server/sync/sync.property.test.ts
  tsconfig.json
  upcoming-release-notes/2072.md
Labels: ✅ Approved

#2108 Adding filter for reconciled transactions
  packages/desktop-client/src/components/filters/FiltersMenu.jsx
  packages/loot-core/src/shared/rules.ts
  upcoming-release-notes/2108.md
Labels: ✅ Approved

#2132 Change net worth graph to show more detail in compact card view
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-and-cash-flow-reports-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-and-cash-flow-reports-2-chromium-linux.png
  packages/desktop-client/src/components/reports/graphs/NetWorthGraph.tsx
  upcoming-release-notes/2132.md
Labels: ✅ Approved

#2134 Ask for confirmation when editing date of a locked transaction
  packages/desktop-client/src/components/accounts/Account.jsx
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  upcoming-release-notes/2134.md
Labels: ✅ Approved

#2144 Fix when pressing Enter adds an extra split transaction when no split remains
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  upcoming-release-notes/2144.md
Labels: ✅ Approved

#2185 ESLint no-default-export 13 - final
  .eslintrc.js
  packages/loot-core/src/server/accounts/ofx2json.ts
  packages/loot-core/src/server/accounts/parse-file.ts
  packages/loot-core/src/server/accounts/qif2json.ts
  packages/loot-core/src/server/accounts/sync.ts
  packages/loot-core/src/server/accounts/title/index.ts
  packages/loot-core/src/server/accounts/title/lower-case.ts
  packages/loot-core/src/server/accounts/title/specials.ts
  packages/loot-core/src/server/api.ts
  packages/loot-core/src/server/budget/app.ts
  packages/loot-core/src/server/filters/app.ts
  packages/loot-core/src/server/importers/actual.ts
  packages/loot-core/src/server/importers/index.ts
  packages/loot-core/src/server/main-app.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/server/notes/app.ts
  packages/loot-core/src/server/rules/app.ts
  packages/loot-core/src/server/schedules/app.ts
  packages/loot-core/src/server/sheet.ts
  packages/loot-core/src/server/spreadsheet/graph-data-structure.ts
  packages/loot-core/src/server/spreadsheet/spreadsheet.test.ts
  packages/loot-core/src/server/spreadsheet/spreadsheet.ts
  packages/loot-core/src/server/sync/index.ts
  packages/loot-core/src/server/sync/make-test-message.ts
  packages/loot-core/src/server/sync/repair.ts
  packages/loot-core/src/server/sync/reset.ts
  packages/loot-core/src/server/tools/app.ts
  packages/node-libofx/ffi.js
  packages/node-libofx/index.js
  upcoming-release-notes/2185.md
Labels: ✅ Approved

#2081 [TS migration] MobileBudget tsx
  packages/desktop-client/src/components/SyncRefresh.tsx
  packages/desktop-client/src/components/budget/MobileBudget.jsx
  packages/desktop-client/src/components/budget/MobileBudget.tsx
  packages/desktop-client/src/components/reports/ReportOptions.ts
  packages/desktop-client/src/components/reports/spreadsheets/grouped-spreadsheet.ts
  packages/loot-core/src/client/state-types/modals.d.ts
  packages/loot-core/src/types/models/category-group.d.ts
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/2081.md
Labels: ✅ Approved

#2114 Add "error" Page for special accounts in Mobile
  packages/desktop-client/src/components/accounts/MobileAccount.jsx
  upcoming-release-notes/2114.md
Labels: ✅ Approved

#2186 Revert "Add "error" Page for special accounts in Mobile"
  packages/desktop-client/src/components/accounts/MobileAccount.jsx
  upcoming-release-notes/2114.md
  upcoming-release-notes/2186.md
Labels: ✅ Approved

#2153 Custom reports reorganize table graph files
  packages/desktop-client/src/components/reports/ChooseGraph.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTable.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableHeader.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableList.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableTotals.tsx
  upcoming-release-notes/2153.md
Labels: ✅ Approved

#2102 [Maintenence] Refactor Goals Schedule file
  packages/loot-core/src/server/budget/goals/goalsSchedule.ts
  upcoming-release-notes/2102.md
Labels: ✅ Approved

#2163 Add ability to import categories from CSV
  packages/desktop-client/src/components/accounts/Account.jsx
  packages/desktop-client/src/components/modals/ImportTransactions.jsx
  upcoming-release-notes/2163.md
Labels: ✅ Approved

#2196 change the pie chart background color in the report status
  packages/desktop-client/src/components/budget/report/budgetsummary/ExpenseProgress.tsx
  packages/desktop-client/src/components/budget/report/budgetsummary/IncomeProgress.tsx
  upcoming-release-notes/2196.md
Labels: ✅ Approved

#2195 fix missing borders in single category drop down in report budget
  packages/desktop-client/src/components/budget/report/ReportComponents.tsx
  upcoming-release-notes/2195.md
Labels: ✅ Approved

#2190 :recycle: refactor(electron): moving back from websockets to IPC
  .gitattributes
  packages/desktop-client/src/browser-preload.browser.js
  packages/desktop-electron/index.js
  packages/desktop-electron/package.json
  packages/desktop-electron/preload.js
  packages/desktop-electron/server.js
  packages/loot-core/package.json
  packages/loot-core/src/client/actions/app.ts
  packages/loot-core/src/platform/client/fetch/index.web.ts
  packages/loot-core/src/platform/server/connection/index.electron.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/webpack/webpack.desktop.config.js
  upcoming-release-notes/2190.md
  yarn.lock
Labels: ✅ Approved

#2183 Revert ":construction_worker: (ci) adding helper comments for failed CI jobs"
  .github/workflows/e2e-test.yml
Labels: ✅ Approved

#2199 :bug: (rules) add 'no rules' message & always show rule table
  packages/desktop-client/src/components/ManageRules.tsx
  upcoming-release-notes/2199.md
Labels: ✅ Approved

#2176 Update sync.ts with additionalInformation as fallback
  packages/loot-core/src/server/accounts/sync.ts
  upcoming-release-notes/2176.md
Labels: ✅ Approved

#2202 Fix webmanifest to enable Actual to be installed as Chromium PWA
  packages/desktop-client/public/site.webmanifest
  upcoming-release-notes/2202.md
Labels: ✅ Approved

#2182 :wrench: (electron) release electron app to app store (osx)
  .github/workflows/electron.yml
  .secret-tokens.example
  bin/package-electron
  packages/api/package.json
  packages/desktop-client/README.md
  packages/desktop-client/e2e/onboarding.test.js-snapshots/Onboarding-checks-the-page-visuals-3-chromium-linux.png
  packages/desktop-client/e2e/onboarding.test.js-snapshots/Onboarding-checks-the-page-visuals-4-chromium-linux.png
  packages/desktop-client/src/components/manager/WelcomeScreen.tsx
  packages/desktop-electron/about/index.js
  packages/desktop-electron/afterSignHook.js
  packages/desktop-electron/index.js
  packages/desktop-electron/package.json
  packages/loot-core/package.json
  upcoming-release-notes/2182.md
  yarn.lock
Labels: ✅ Approved

#2168 Tests: Add api tests for payees and transactions
  packages/api/methods.test.ts
  upcoming-release-notes/2168.md
Labels: ✅ Approved

#2181 :recycle: (gocardless) rename nordigen_* secrets to gocardless_*
  packages/desktop-client/src/components/modals/GoCardlessInitialise.tsx
  upcoming-release-notes/2181.md
Labels: ✅ Approved

#2209 :wrench: (ci) fork the electron build job - master and PR
  .github/workflows/electron-master.yml
  .github/workflows/electron-pr.yml
  upcoming-release-notes/2209.md
Labels: ✅ Approved

#2208 ESLint to enforce Actual's useNavigate hook
  .eslintrc.js
  packages/desktop-client/src/components/FinancesApp.tsx
  upcoming-release-notes/2208.md
Labels: ✅ Approved

#2206 [Enhancement] Add crossorigin field to manifest line
  packages/desktop-client/public/index.html
  upcoming-release-notes/2206.md
Labels: ✅ Approved

#2136 Add proper types to runHandler
  packages/loot-core/src/mocks/budget.ts
  packages/loot-core/src/platform/server/connection/index.web.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/server/mutators.ts
  packages/loot-core/src/server/schedules/types/handlers.ts
  packages/loot-core/src/types/api-handlers.d.ts
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/2136.md
Labels: ✅ Approved

#2056 Mobile - Add cleared and uncleared Balances in Account Details
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-5-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-6-chromium-linux.png
  packages/desktop-client/src/components/accounts/MobileAccount.jsx
  packages/desktop-client/src/components/accounts/MobileAccountDetails.jsx
  packages/loot-core/src/client/queries.ts
  upcoming-release-notes/2056.md
Labels: ✅ Approved

#2204 ReAdd Mobile Account Error Page
  packages/desktop-client/src/components/accounts/MobileAccount.jsx
  upcoming-release-notes/2204.md
Labels: ✅ Approved

#2207 :bug: (autocomplete) fix multi-autocomplete causing crashes
  packages/desktop-client/src/components/autocomplete/Autocomplete.tsx
  upcoming-release-notes/2207.md
Labels: ✅ Approved

#2084 Proposal for switching desktop-client to vite
  .eslintrc.js
  .github/workflows/size-compare.yml
  packages/desktop-client/.gitignore
  packages/desktop-client/bin/build-browser
  packages/desktop-client/craco.config.ts
  packages/desktop-client/index.html
  packages/desktop-client/package.json
  packages/desktop-client/src/build-shims.js
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  packages/desktop-client/src/components/transactions/TransactionsTable.test.jsx
  packages/desktop-client/src/fonts.scss
  packages/desktop-client/src/setupTests.jsx
  packages/desktop-client/vite.config.mts
  tsconfig.json
  upcoming-release-notes/2084.md
  yarn.lock
Labels: ✅ Approved

#2214 Proposal - Disable Save Button in Mobile Transaction View if field is edited
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-from-accounts-id-page-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-from-accounts-id-page-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-3-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-4-chromium-linux.png
  packages/desktop-client/src/components/transactions/MobileTransaction.jsx
  upcoming-release-notes/2214.md
Labels: ✅ Approved

#2212 :recycle: (typescript) fixing strictNullChecks=true issues
  packages/crdt/src/crdt/merkle.ts
  packages/loot-core/src/client/actions/queries.ts
  packages/loot-core/src/client/reducers/queries.ts
  packages/loot-core/src/client/state-types/queries.d.ts
  packages/loot-core/src/mocks/budget.ts
  packages/loot-core/src/server/db/index.ts
  packages/loot-core/src/shared/transactions.test.ts
  packages/loot-core/src/shared/transactions.ts
  packages/loot-core/src/shared/util.ts
  packages/loot-core/src/types/models/payee.d.ts
  tsconfig.json
  upcoming-release-notes/2212.md
Labels: ✅ Approved

#2191 fixed:issue->#1968 Import from nYNAB fails with unknown error
  packages/loot-core/src/server/importers/ynab5.ts
  upcoming-release-notes/2191.md
Labels: ✅ Approved

#2124 Custom Reports: Enable Show Labels
  packages/desktop-client/src/components/reports/ChooseGraph.tsx
  packages/desktop-client/src/components/reports/ReportTopbar.jsx
  packages/desktop-client/src/components/reports/graphs/AreaGraph.tsx
  packages/desktop-client/src/components/reports/graphs/BarGraph.tsx
  packages/desktop-client/src/components/reports/graphs/DonutGraph.tsx
  packages/desktop-client/src/components/reports/graphs/StackedBarGraph.tsx
  packages/desktop-client/src/components/reports/graphs/adjustTextSize.ts
  packages/desktop-client/src/components/reports/graphs/renderCustomLabel.tsx
  packages/desktop-client/src/components/reports/reports/CustomReport.jsx
  packages/desktop-client/src/components/reports/reports/CustomReportCard.jsx
  packages/desktop-client/src/components/reports/spreadsheets/custom-spreadsheet.ts
  packages/desktop-client/src/components/reports/spreadsheets/grouped-spreadsheet.ts
  packages/desktop-client/src/style/themes/dark.ts
  packages/desktop-client/src/style/themes/light.ts
  packages/loot-core/src/shared/util.ts
  upcoming-release-notes/2124.md
Labels: ✅ Approved

#2217 vite host regression fix
  packages/desktop-client/vite.config.mts
  upcoming-release-notes/2217.md
Labels: ✅ Approved

#2151 Add split distribution
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  packages/desktop-client/src/components/transactions/TransactionsTable.test.jsx
  upcoming-release-notes/2151.md
Labels: ✅ Approved

#2227 chore: Update actions.ts
  packages/loot-core/src/server/budget/actions.ts
Labels: ✅ Approved

#2224 Change the vite chunk filename hash usage
  .github/workflows/size-compare.yml
  packages/desktop-client/vite.config.mts
  upcoming-release-notes/2224.md
Labels: ✅ Approved

#2233 Restore ability to use console.log in vite
  packages/desktop-client/package.json
  packages/desktop-client/vite.config.mts
  upcoming-release-notes/2233.md
  yarn.lock
Labels: ✅ Approved

#2192 Custom Reports: fix table rendering
  packages/desktop-client/src/components/common/Block.tsx
  packages/desktop-client/src/components/reports/ChooseGraph.tsx
  packages/desktop-client/src/components/reports/ReportOptions.ts
  packages/desktop-client/src/components/reports/entities.d.ts
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTable.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableHeader.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableList.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableRow.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableTotals.tsx
  upcoming-release-notes/2192.md
Labels: ✅ Approved

#2238 :bug: (gocardless) fix sync when additionalInformation field is null
  packages/loot-core/src/server/accounts/sync.ts
  upcoming-release-notes/2238.md
Labels: ✅ Approved

#2228 ♻️ (typescript) fixing strictNullChecks=true issues
  packages/loot-core/src/shared/async.ts
  packages/loot-core/src/shared/months.ts
  packages/loot-core/src/shared/query.ts
  packages/loot-core/src/shared/schedules.ts
  packages/loot-core/src/shared/test-helpers.ts
  upcoming-release-notes/2228.md
Labels: ✅ Approved

#2244 Custom Reports update entites
  packages/desktop-client/src/components/reports/ChooseGraph.tsx
  packages/desktop-client/src/components/reports/ReportSummary.tsx
  packages/desktop-client/src/components/reports/graphs/AreaGraph.tsx
  packages/desktop-client/src/components/reports/graphs/BarGraph.tsx
  packages/desktop-client/src/components/reports/graphs/DonutGraph.tsx
  packages/desktop-client/src/components/reports/graphs/StackedBarGraph.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTable.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableHeader.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableList.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableRow.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableTotals.tsx
  packages/desktop-client/src/components/reports/spreadsheets/calculateLegend.ts
  packages/loot-core/src/types/models/index.d.ts
  packages/loot-core/src/types/models/reports.d.ts
  upcoming-release-notes/2244.md
Labels: ✨ Merged

#2245 Custom Reports compact additions
  packages/desktop-client/src/components/common/MenuButton.tsx
  packages/desktop-client/src/components/reports/ChooseGraph.tsx
  packages/desktop-client/src/components/reports/graphs/BarGraph.tsx
  packages/desktop-client/src/components/reports/graphs/BarLineGraph.tsx
  packages/desktop-client/src/components/reports/graphs/DonutGraph.tsx
  packages/desktop-client/src/components/reports/graphs/LineGraph.tsx
  packages/desktop-client/src/components/reports/graphs/StackedBarGraph.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTable.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableHeader.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableList.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableTotals.tsx
  packages/desktop-client/src/components/reports/reports/CustomReport.jsx
  packages/desktop-client/src/hooks/useFilters.ts
  packages/desktop-client/src/style/styles.ts
  upcoming-release-notes/2245.md
Labels: ✅ Approved

#2249 Custom Reports: fix broken table
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTable.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableList.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableRow.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableTotals.tsx
  upcoming-release-notes/2249.md
Labels: ✅ Approved

#2251 :bug: fix 'delete budget' button always deleting cloud file
  packages/desktop-client/src/components/manager/DeleteFile.tsx
  upcoming-release-notes/2251.md
Labels: ✅ Approved

#2253 :arrow_up: (prettier) upgrade, fix issues and enable for jsx files
  .eslintrc.js
  package.json
  packages/crdt/src/crdt/timestamp.ts
  packages/desktop-client/src/components/Notifications.tsx
  packages/desktop-client/src/components/Titlebar.tsx
  packages/desktop-client/src/components/accounts/Balance.jsx
  packages/desktop-client/src/components/autocomplete/AccountAutocomplete.tsx
  packages/desktop-client/src/components/budget/BudgetCategories.jsx
  packages/desktop-client/src/components/budget/MobileBudgetTable.jsx
  packages/desktop-client/src/components/budget/report/budgetsummary/Saved.tsx
  packages/desktop-client/src/components/budget/util.ts
  packages/desktop-client/src/components/common/Stack.tsx
  packages/desktop-client/src/components/filters/FiltersMenu.jsx
  packages/desktop-client/src/components/modals/GoCardlessExternalMsg.tsx
  packages/desktop-client/src/components/modals/ImportTransactions.jsx
  packages/desktop-client/src/components/modals/ImportTransactions.test.js
  packages/desktop-client/src/components/modals/MergeUnusedPayees.jsx
  packages/desktop-client/src/components/modals/PlaidExternalMsg.tsx
  packages/desktop-client/src/components/payees/PayeeTableRow.tsx
  packages/desktop-client/src/components/reports/ChooseGraph.tsx
  packages/desktop-client/src/components/reports/ReportSidebar.jsx
  packages/desktop-client/src/components/reports/ReportSummary.tsx
  packages/desktop-client/src/components/reports/spreadsheets/calculateLegend.ts
  packages/desktop-client/src/components/rules/RuleRow.tsx
  packages/desktop-client/src/components/rules/Value.tsx
  packages/desktop-client/src/components/schedules/PostsOfflineNotification.jsx
  packages/desktop-client/src/components/sidebar/Account.tsx
  packages/desktop-client/src/components/spreadsheet/CellValue.tsx
  packages/desktop-client/src/components/table.tsx
  packages/desktop-client/src/components/transactions/MobileTransaction.jsx
  packages/desktop-client/src/components/transactions/TransactionList.jsx
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  packages/desktop-client/src/components/transactions/TransactionsTable.test.jsx
  packages/desktop-client/src/setupTests.js
  packages/desktop-client/vite.config.mts
  packages/desktop-electron/security.js
  packages/loot-core/src/client/platform.electron.ts
  packages/loot-core/src/client/platform.web.ts
  packages/loot-core/src/client/query-helpers.test.ts
  packages/loot-core/src/platform/server/connection/index.web.ts
  packages/loot-core/src/server/accounts/export-to-csv.ts
  packages/loot-core/src/server/accounts/parse-file.test.ts
  packages/loot-core/src/server/accounts/rules.ts
  packages/loot-core/src/server/backups.ts
  packages/loot-core/src/server/budget/goals/goalsSchedule.ts
  packages/loot-core/src/server/budget/goaltemplates.ts
  packages/loot-core/src/server/importers/ynab4.ts
  upcoming-release-notes/2253.md
  yarn.lock
Labels: ✅ Approved

#2254 Clean-up some custom reports code
  packages/desktop-client/src/components/reports/ReportSidebar.jsx
  packages/desktop-client/src/components/reports/ReportTopbar.jsx
  packages/desktop-client/src/components/reports/reports/CustomReport.jsx
  upcoming-release-notes/2254.md
Labels: ✅ Approved

#2255 :fire: removing unused variables (batch 1)
  packages/api/methods.js
  packages/desktop-client/src/components/modals/ImportTransactions.jsx
  packages/desktop-client/src/components/reports/CategorySelector.tsx
  packages/desktop-client/src/components/rules/RulesHeader.tsx
  packages/desktop-client/src/components/schedules/SchedulesTable.tsx
  packages/desktop-client/src/components/select/DateSelect.tsx
  packages/desktop-client/src/components/sidebar/Accounts.tsx
  packages/desktop-client/src/components/table.tsx
  packages/desktop-client/src/components/transactions/SimpleTransactionsTable.jsx
  packages/desktop-client/src/components/transactions/TransactionsTable.test.jsx
  packages/desktop-client/src/components/util/AmountInput.tsx
  packages/desktop-electron/security.js
  packages/desktop-electron/updater.js
  packages/loot-core/migrations/1632571489012_remove_cache.js
  packages/loot-core/src/client/actions/account.ts
  packages/loot-core/src/client/actions/queries.ts
  packages/loot-core/src/client/query-helpers.test.ts
  packages/loot-core/src/platform/client/fetch/index.web.ts
  packages/loot-core/src/platform/exceptions/index.browser.ts
  packages/loot-core/src/platform/exceptions/index.electron.ts
  packages/loot-core/src/platform/exceptions/index.testing.ts
  packages/loot-core/src/platform/exceptions/index.web.ts
  packages/loot-core/src/platform/server/asyncStorage/index.web.ts
  packages/loot-core/src/platform/server/connection/index.api.ts
  packages/loot-core/src/platform/server/fs/index.web.ts
  packages/loot-core/src/platform/server/indexeddb/index.web.ts
  packages/loot-core/src/server/__mocks__/post.ts
  packages/loot-core/src/server/accounts/rules.test.ts
  packages/loot-core/src/server/accounts/rules.ts
  packages/loot-core/src/server/api.ts
  packages/loot-core/src/server/aql/compiler.ts
  packages/loot-core/src/server/bench.ts
  packages/loot-core/src/server/cloud-storage.ts
  packages/loot-core/src/server/db/index.ts
  packages/loot-core/src/server/importers/actual.ts
  packages/loot-core/src/server/importers/ynab4.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/server/migrate/cli.ts
  packages/loot-core/src/server/schedules/app.ts
  packages/loot-core/src/server/schedules/find-schedules.ts
  packages/loot-core/src/server/spreadsheet/spreadsheet.ts
  packages/loot-core/src/server/sync/index.ts
  packages/loot-core/src/server/tests/mockSyncServer.ts
  packages/loot-core/src/shared/async.test.ts
  packages/loot-core/src/types/api-handlers.d.ts
  upcoming-release-notes/2255.md
Labels: ✅ Approved

#2246 Custom Reports - add schema
  packages/desktop-client/src/components/common/AnchorLink.tsx
  packages/desktop-client/src/components/reports/Overview.jsx
  packages/desktop-client/src/components/reports/ReportCard.tsx
  packages/desktop-client/src/components/reports/ReportOptions.ts
  packages/desktop-client/src/components/reports/reports/CustomReport.jsx
  packages/desktop-client/src/components/reports/reports/CustomReportCard.jsx
  packages/loot-core/src/client/data-hooks/reports.ts
  packages/loot-core/src/server/aql/schema/index.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/server/reports/app.ts
  packages/loot-core/src/server/reports/types/handlers.ts
  packages/loot-core/src/types/handlers.d.ts
  packages/loot-core/src/types/models/reports.d.ts
  upcoming-release-notes/2246.md
Labels: ✅ Approved

#2250 :wrench: add link to community discord for support
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  upcoming-release-notes/2250.md
Labels: ✅ Approved

#2053 Bundle loot-core types into the API
  .eslintignore
  .eslintrc.js
  .gitignore
  packages/api/index.js
  packages/api/index.ts
  packages/api/methods.ts
  packages/api/package.json
  packages/api/tsconfig.dist.json
  packages/loot-core/bin/build-api
  packages/loot-core/package.json
  packages/loot-core/src/server/importers/ynab5.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/server/mutators.ts
  packages/loot-core/src/shared/schedules.ts
  packages/loot-core/src/types/api-handlers.d.ts
  packages/loot-core/tsconfig.api.json
  tsconfig.json
  upcoming-release-notes/2053.md
  yarn.lock
Labels: ✅ Approved

#2258 add compact to custom reports
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTable.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableHeader.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableList.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableRow.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableTotals.tsx
  packages/desktop-client/src/components/reports/reports/CustomReport.jsx
  upcoming-release-notes/2258.md
Labels: ✅ Approved

#2261 fix color of schedule before/after weekend box
  packages/desktop-client/src/components/select/RecurringSchedulePicker.jsx
  upcoming-release-notes/2261.md
Labels: ✅ Approved

#2256 :fire: removing unused variables (batch 2)
  .eslintrc.js
  packages/desktop-client/src/browser-preload.browser.js
  packages/desktop-client/src/components/FatalError.tsx
  packages/desktop-client/src/components/FixedSizeList.tsx
  packages/desktop-client/src/components/ManageRules.tsx
  packages/desktop-client/src/components/accounts/Account.jsx
  packages/desktop-client/src/components/accounts/MobileAccount.jsx
  packages/desktop-client/src/components/budget/MobileBudget.tsx
  packages/desktop-client/src/components/budget/MobileBudgetTable.jsx
  packages/desktop-client/src/components/budget/SidebarCategory.tsx
  packages/desktop-client/src/components/budget/SidebarGroup.tsx
  packages/desktop-client/src/components/budget/index.tsx
  packages/desktop-client/src/components/budget/report/BalanceTooltip.tsx
  packages/desktop-client/src/components/budget/rollover/CoverTooltip.tsx
  packages/desktop-client/src/components/budget/rollover/TransferTooltip.tsx
  packages/desktop-client/src/components/budget/rollover/budgetsummary/BudgetSummary.tsx
  packages/desktop-client/src/components/common/Menu.tsx
  packages/desktop-client/src/components/modals/CategoryGroupMenu.tsx
  packages/desktop-client/src/components/modals/CategoryMenu.tsx
  packages/desktop-client/src/components/modals/EditRule.jsx
  packages/desktop-client/src/components/modals/Notes.tsx
  packages/desktop-client/src/components/modals/SingleInput.tsx
  packages/desktop-client/src/components/payees/ManagePayeesWithData.jsx
  packages/desktop-client/src/components/reports/ChooseGraph.tsx
  packages/desktop-client/src/components/reports/Header.jsx
  packages/desktop-client/src/components/reports/graphs/AreaGraph.tsx
  packages/desktop-client/src/components/reports/graphs/BarGraph.tsx
  packages/desktop-client/src/components/reports/graphs/BarLineGraph.tsx
  packages/desktop-client/src/components/reports/graphs/DonutGraph.tsx
  packages/desktop-client/src/components/reports/graphs/LineGraph.tsx
  packages/desktop-client/src/components/reports/graphs/NetWorthGraph.tsx
  packages/desktop-client/src/components/reports/graphs/SankeyGraph.tsx
  packages/desktop-client/src/components/reports/graphs/StackedBarGraph.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableHeader.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableTotals.tsx
  packages/desktop-client/src/components/reports/reports/CashFlow.tsx
  packages/desktop-client/src/components/reports/spreadsheets/cash-flow-spreadsheet.tsx
  upcoming-release-notes/2256.md
Labels: ✅ Approved

#2252 :sparkles: allow un-reconciling (unlocking) transactions
  packages/desktop-client/src/components/modals/ConfirmTransactionEdit.tsx
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  upcoming-release-notes/2252.md
Labels: ✅ Approved

#2260 :recycle: refactored cash-flow report from victory to recharts
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-cash-flow-graph-and-checks-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-cash-flow-graph-and-checks-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-and-cash-flow-reports-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-and-cash-flow-reports-2-chromium-linux.png
  packages/desktop-client/src/components/reports/graphs/CashFlowGraph.tsx
  packages/desktop-client/src/components/reports/reports/CashFlowCard.jsx
  packages/desktop-client/src/components/reports/spreadsheets/cash-flow-spreadsheet.tsx
  upcoming-release-notes/2260.md
Labels: ✅ Approved

#2273 :bug: fix uncategorized transaction banner flashing on load
  packages/desktop-client/src/components/Titlebar.tsx
  upcoming-release-notes/2273.md
Labels: ✅ Approved

#2277 :bug: Fix a missing ref param warning for forwardRef
  packages/desktop-client/src/components/table.tsx
  upcoming-release-notes/2277.md
Labels: ✅ Approved

#2278 :bug: Avoid passing a boolean to the import trans category title
  packages/desktop-client/src/components/modals/ImportTransactions.jsx
  upcoming-release-notes/2278.md
Labels: ✅ Approved

#2281 [Bugfix] Goals: Database entry
  packages/loot-core/src/server/budget/actions.ts
  upcoming-release-notes/2281.md
Labels: ✅ Approved

#2174 Custom reports: hide "show ..." checkboxes in menu
  packages/desktop-client/src/components/common/Menu.tsx
  packages/desktop-client/src/components/common/Toggle.tsx
  packages/desktop-client/src/components/reports/ReportSidebar.jsx
  packages/desktop-client/src/components/reports/graphs/adjustTextSize.ts
  packages/desktop-client/src/style/themes/dark.ts
  packages/desktop-client/src/style/themes/light.ts
  upcoming-release-notes/2174.md
Labels: ✅ Approved

#2284 Mobile Off Budget category label
  packages/desktop-client/src/components/accounts/MobileAccountDetails.jsx
  packages/desktop-client/src/components/transactions/MobileTransaction.jsx
  upcoming-release-notes/2284.md
Labels: ✅ Approved

#2276 Updating link for GoCardless Bank Account Sync
  packages/desktop-client/src/components/modals/GoCardlessInitialise.tsx
  upcoming-release-notes/2276.md
Labels: ✅ Approved

#2287 update vrt instructions
  packages/desktop-client/README.md
  upcoming-release-notes/2287.md
Labels: ✅ Approved

#2279 fix bad account sort order in demo
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-1-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-2-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-3-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-4-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-creates-a-new-account-and-views-the-initial-balance-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-creates-a-new-account-and-views-the-initial-balance-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/budget.test.js-snapshots/Budget-renders-the-summary-information-available-funds-overspent-budgeted-and-for-next-month-1-chromium-linux.png
  packages/desktop-client/e2e/budget.test.js-snapshots/Budget-renders-the-summary-information-available-funds-overspent-budgeted-and-for-next-month-2-chromium-linux.png
  packages/desktop-client/e2e/budget.test.js-snapshots/Budget-transfer-funds-to-another-category-1-chromium-linux.png
  packages/desktop-client/e2e/budget.test.js-snapshots/Budget-transfer-funds-to-another-category-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-the-accounts-page-and-asserts-on-balances-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-the-accounts-page-and-asserts-on-balances-2-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-cash-flow-graph-and-checks-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-cash-flow-graph-and-checks-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-and-cash-flow-reports-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-and-cash-flow-reports-2-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-graph-and-checks-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-graph-and-checks-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-checks-the-page-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-checks-the-page-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-3-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-4-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-checks-the-page-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-checks-the-page-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-1-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-2-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-3-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-4-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-5-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-6-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-7-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-8-chromium-linux.png
  packages/desktop-client/e2e/settings.test.js-snapshots/Settings-checks-the-page-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/settings.test.js-snapshots/Settings-checks-the-page-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-checks-the-page-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-checks-the-page-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-split-test-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-split-test-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-test-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-test-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-category-5-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-category-6-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-date-5-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-date-6-chromium-linux.png
  packages/loot-core/src/mocks/budget.ts
  upcoming-release-notes/2279.md
Labels: ✅ Approved

#2263 [Cleanup] useSingleActiveEditForm hook on mobile budget table
  packages/desktop-client/src/components/budget/MobileBudget.tsx
  packages/desktop-client/src/components/budget/MobileBudgetTable.jsx
  upcoming-release-notes/2263.md
Labels: 🔍 Ready for Review

#2282 [Enhancement] Goal Target with cleanup template
  packages/loot-core/src/server/budget/cleanup-template.ts
  upcoming-release-notes/2282.md
Labels: ✅ Approved
