Repository actualbudget/actual, pull requests merged in 2024-04, with the labels that each got.

#2530 Fix mobile autocomplete colors
  packages/desktop-client/src/components/autocomplete/AccountAutocomplete.tsx
  packages/desktop-client/src/components/autocomplete/CategoryAutocomplete.tsx
  packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.tsx
  upcoming-release-notes/2530.md
Labels: ✅ Approved

#2537 :bookmark: (24.4.0) custom reports improvements, stability enhancements
  packages/api/package.json
  packages/desktop-client/package.json
  packages/desktop-electron/package.json
  upcoming-release-notes/2381.md
  upcoming-release-notes/2388.md
  upcoming-release-notes/2398.md
  upcoming-release-notes/2403.md
  upcoming-release-notes/2404.md
  upcoming-release-notes/2408.md
  upcoming-release-notes/2409.md
  upcoming-release-notes/2410.md
  upcoming-release-notes/2416.md
  upcoming-release-notes/2417.md
  upcoming-release-notes/2419.md
  upcoming-release-notes/2421.md
  upcoming-release-notes/2422.md
  upcoming-release-notes/2425.md
  upcoming-release-notes/2429.md
  upcoming-release-notes/2434.md
  upcoming-release-notes/2441.md
  upcoming-release-notes/2443.md
  upcoming-release-notes/2446.md
  upcoming-release-notes/2447.md
  upcoming-release-notes/2452.md
  upcoming-release-notes/2453.md
  upcoming-release-notes/2455.md
  upcoming-release-notes/2459.md
  upcoming-release-notes/2460.md
  upcoming-release-notes/2461.md
  upcoming-release-notes/2462.md
  upcoming-release-notes/2464.md
  upcoming-release-notes/2474.md
  upcoming-release-notes/2475.md
  upcoming-release-notes/2476.md
  upcoming-release-notes/2479.md
  upcoming-release-notes/2481.md
  upcoming-release-notes/2485.md
  upcoming-release-notes/2487.md
  upcoming-release-notes/2489.md
  upcoming-release-notes/2492.md
  upcoming-release-notes/2494.md
  upcoming-release-notes/2500.md
  upcoming-release-notes/2504.md
  upcoming-release-notes/2505.md
  upcoming-release-notes/2526.md
  upcoming-release-notes/2528.md
  upcoming-release-notes/2529.md
  upcoming-release-notes/2530.md
Labels: ✅ Approved

#2535 Goals: Up To Template calculation with negative category balance
  packages/loot-core/src/server/budget/goals/goalsSimple.ts
  packages/loot-core/src/server/budget/goaltemplates.ts
  upcoming-release-notes/2535.md
Labels: 🚧 WIP

#2468 Append, Prepend, or Replace notes in bulk actions
  packages/desktop-client/src/components/accounts/Account.jsx
  packages/desktop-client/src/components/modals/EditField.jsx
  upcoming-release-notes/2468.md
Labels: ✅ Approved

#2518 Bump GoCardless access validity from 30 to 90 days
  packages/desktop-client/src/gocardless.ts
  upcoming-release-notes/2518.md
Labels: 🔍 Ready for Review

#2509 [Maintenance] Replace react-merge-refs with useMergedRefs
  packages/desktop-client/package.json
  packages/desktop-client/src/components/common/Input.tsx
  packages/desktop-client/src/hooks/useMergedRefs.ts
  upcoming-release-notes/2509.md
  yarn.lock
Labels: ✅ Approved

#2466 Add yearly to custom reports
  packages/desktop-client/src/components/reports/ReportOptions.ts
  packages/desktop-client/src/components/reports/ReportSidebar.jsx
  packages/desktop-client/src/components/reports/ReportSummary.tsx
  packages/desktop-client/src/components/reports/reportRanges.ts
  packages/desktop-client/src/components/reports/reports/CustomReport.jsx
  packages/desktop-client/src/components/reports/spreadsheets/custom-spreadsheet.ts
  packages/desktop-client/src/components/reports/spreadsheets/grouped-spreadsheet.ts
  packages/desktop-client/src/components/reports/spreadsheets/makeQuery.ts
  packages/loot-core/src/shared/months.ts
  upcoming-release-notes/2466.md
Labels: ✅ Approved

#2521 Custom Reports: Confirm delete report
  packages/desktop-client/src/components/reports/SaveReport.tsx
  packages/desktop-client/src/components/reports/SaveReportDelete.tsx
  packages/desktop-client/src/components/reports/reports/CustomReportListCards.tsx
  upcoming-release-notes/2521.md
Labels: ✅ Approved

#2511 [Maintenance] Extract menus to separate files (changes split from #2472)
  packages/desktop-client/src/components/budget/index.tsx
  packages/desktop-client/src/components/budget/report/BalanceMenu.tsx
  packages/desktop-client/src/components/budget/report/BalanceTooltip.tsx
  packages/desktop-client/src/components/budget/rollover/BalanceMenu.tsx
  packages/desktop-client/src/components/budget/rollover/BalanceTooltip.tsx
  packages/desktop-client/src/components/budget/rollover/CoverTooltip.tsx
  packages/desktop-client/src/components/budget/rollover/RolloverContext.tsx
  packages/desktop-client/src/components/budget/rollover/TransferTooltip.tsx
  packages/desktop-client/src/components/budget/rollover/budgetsummary/ToBudget.tsx
  packages/desktop-client/src/components/budget/rollover/budgetsummary/ToBudgetAmount.tsx
  packages/desktop-client/src/components/budget/rollover/budgetsummary/ToBudgetMenu.tsx
  packages/desktop-client/src/components/common/Menu.tsx
  packages/desktop-client/src/components/mobile/MobileForms.jsx
  packages/desktop-client/src/components/mobile/MobileForms.tsx
  upcoming-release-notes/2511.md
Labels: 🔍 Ready for Review, ✅ Approved

#2506 modify existing LineGraph to track budget items over time
  packages/desktop-client/src/components/reports/ChooseGraph.tsx
  packages/desktop-client/src/components/reports/ReportTopbar.jsx
  packages/desktop-client/src/components/reports/disabledList.ts
  packages/desktop-client/src/components/reports/graphs/BarLineGraph.tsx
  packages/desktop-client/src/components/reports/graphs/LineGraph.tsx
  upcoming-release-notes/2506.md
Labels: ✅ Approved

#2542 Show/hide reconciled transactions in the account view
  packages/desktop-client/src/components/accounts/Account.jsx
  packages/desktop-client/src/components/accounts/Header.jsx
  packages/loot-core/src/types/prefs.d.ts
  upcoming-release-notes/2542.md
Labels: ✅ Approved

#2548 :wrench: updated github issue template to hopefully reduce the amount of support
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  upcoming-release-notes/2548.md
Labels: ✅ Approved

#2472 [Mobile]: More functionalities
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-5-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-3-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-5-chromium-linux.png
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/autocomplete/AccountAutocomplete.tsx
  packages/desktop-client/src/components/autocomplete/CategoryAutocomplete.tsx
  packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.tsx
  packages/desktop-client/src/components/budget/index.tsx
  packages/desktop-client/src/components/budget/report/BalanceMenu.tsx
  packages/desktop-client/src/components/budget/rollover/BalanceMenu.tsx
  packages/desktop-client/src/components/budget/rollover/RolloverContext.tsx
  packages/desktop-client/src/components/budget/rollover/budgetsummary/ToBudgetMenu.tsx
  packages/desktop-client/src/components/mobile/MobileForms.tsx
  packages/desktop-client/src/components/mobile/accounts/Account.jsx
  packages/desktop-client/src/components/mobile/accounts/AccountDetails.jsx
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  packages/desktop-client/src/components/mobile/budget/index.tsx
  packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
  packages/desktop-client/src/components/modals/AccountAutocompleteModal.tsx
  packages/desktop-client/src/components/modals/AccountMenuModal.tsx
  packages/desktop-client/src/components/modals/CategoryAutocompleteModal.tsx
  packages/desktop-client/src/components/modals/CategoryGroupMenuModal.tsx
  packages/desktop-client/src/components/modals/CategoryMenuModal.tsx
  packages/desktop-client/src/components/modals/CloseAccountModal.tsx
  packages/desktop-client/src/components/modals/CoverModal.tsx
  packages/desktop-client/src/components/modals/EditField.jsx
  packages/desktop-client/src/components/modals/HoldBufferModal.tsx
  packages/desktop-client/src/components/modals/PayeeAutocompleteModal.tsx
  packages/desktop-client/src/components/modals/ReportBalanceMenuModal.tsx
  packages/desktop-client/src/components/modals/ReportBudgetSummaryModal.tsx
  packages/desktop-client/src/components/modals/RolloverBalanceMenuModal.tsx
  packages/desktop-client/src/components/modals/RolloverBudgetSummary.tsx
  packages/desktop-client/src/components/modals/RolloverBudgetSummaryModal.tsx
  packages/desktop-client/src/components/modals/RolloverToBudgetMenuModal.tsx
  packages/desktop-client/src/components/modals/ScheduledTransactionMenuModal.tsx
  packages/desktop-client/src/components/modals/SingleInputModal.tsx
  packages/desktop-client/src/components/modals/TransferModal.tsx
  packages/desktop-client/src/hooks/useInitialMount.ts
  packages/loot-core/src/client/state-types/modals.d.ts
  upcoming-release-notes/2472.md
Labels: ✅ Approved

#2553 Fix toggle bug
  packages/desktop-client/src/components/common/Menu.tsx
  upcoming-release-notes/2553.md
Labels: ✅ Approved

#2556 Custom Reports bug fix
  packages/desktop-client/src/components/reports/reportRanges.ts
  upcoming-release-notes/2556.md
Labels: ✅ Approved

#2555 [Maintenance] Update TransactionEdit conponent onEdit function to use serialized transactions
  packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
  upcoming-release-notes/2555.md
Labels: ✅ Approved

#2557 Custom Reports: Fix live range
  packages/desktop-client/src/components/reports/ReportSidebar.jsx
  packages/desktop-client/src/components/reports/getLiveRange.ts
  packages/desktop-client/src/components/reports/reportRanges.ts
  packages/desktop-client/src/components/reports/reports/CustomReport.jsx
  packages/desktop-client/src/components/reports/reports/CustomReportListCards.tsx
  packages/desktop-client/src/components/reports/reports/GetCardData.tsx
  upcoming-release-notes/2557.md
Labels: ✅ Approved

#2480 Cleanup tool group enhancement
  packages/loot-core/src/server/budget/cleanup-template.pegjs
  packages/loot-core/src/server/budget/cleanup-template.ts
  upcoming-release-notes/2480.md
Labels: ✅ Approved

#2558 Consolidate Link props
  .eslintrc.js
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-1-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-2-chromium-linux.png
  packages/desktop-client/src/components/DevelopmentTopBar.tsx
  packages/desktop-client/src/components/FatalError.tsx
  packages/desktop-client/src/components/ManageRules.tsx
  packages/desktop-client/src/components/Notifications.tsx
  packages/desktop-client/src/components/Titlebar.tsx
  packages/desktop-client/src/components/UpdateNotification.tsx
  packages/desktop-client/src/components/accounts/AccountSyncCheck.jsx
  packages/desktop-client/src/components/common/AnchorLink.tsx
  packages/desktop-client/src/components/common/Button.tsx
  packages/desktop-client/src/components/common/ButtonLink.tsx
  packages/desktop-client/src/components/common/ExternalLink.tsx
  packages/desktop-client/src/components/common/Link.tsx
  packages/desktop-client/src/components/common/LinkButton.tsx
  packages/desktop-client/src/components/manager/ImportYNAB5.tsx
  packages/desktop-client/src/components/manager/WelcomeScreen.tsx
  packages/desktop-client/src/components/manager/subscribe/Bootstrap.tsx
  packages/desktop-client/src/components/mobile/accounts/AccountDetails.jsx
  packages/desktop-client/src/components/modals/CloseAccountModal.tsx
  packages/desktop-client/src/components/modals/CreateAccount.tsx
  packages/desktop-client/src/components/modals/CreateEncryptionKey.tsx
  packages/desktop-client/src/components/modals/CreateLocalAccount.tsx
  packages/desktop-client/src/components/modals/FixEncryptionKey.tsx
  packages/desktop-client/src/components/modals/GoCardlessExternalMsg.tsx
  packages/desktop-client/src/components/modals/GoCardlessInitialise.tsx
  packages/desktop-client/src/components/modals/SimpleFinInitialise.tsx
  packages/desktop-client/src/components/modals/SwitchBudgetType.tsx
  packages/desktop-client/src/components/reports/Header.jsx
  packages/desktop-client/src/components/reports/Overview.jsx
  packages/desktop-client/src/components/reports/ReportCard.tsx
  packages/desktop-client/src/components/rules/Value.tsx
  packages/desktop-client/src/components/settings/Encryption.tsx
  packages/desktop-client/src/components/settings/Experimental.tsx
  packages/desktop-client/src/components/settings/UI.tsx
  packages/desktop-client/src/components/settings/index.tsx
  packages/desktop-client/src/components/sidebar/Account.tsx
  packages/desktop-client/src/components/sidebar/ItemContent.tsx
  upcoming-release-notes/2558.md
Labels: ✅ Approved

#2560 Show sync indicator in account header
  packages/desktop-client/src/components/accounts/Account.jsx
  packages/desktop-client/src/components/accounts/Header.jsx
  upcoming-release-notes/2560.md
Labels: ✅ Approved

#2493 :recycle: (tooltip) refactored tooltip to react-aria
  packages/desktop-client/package.json
  packages/desktop-client/src/components/NotesButton.tsx
  packages/desktop-client/src/components/budget/report/budgetsummary/BudgetSummary.tsx
  packages/desktop-client/src/components/budget/rollover/budgetsummary/BudgetSummary.tsx
  packages/desktop-client/src/components/common/Tooltip.tsx
  packages/desktop-client/src/components/common/View.tsx
  packages/desktop-client/src/components/modals/CategoryGroupMenuModal.tsx
  packages/desktop-client/src/components/modals/CategoryMenuModal.tsx
  packages/desktop-client/src/components/modals/Notes.tsx
  packages/desktop-client/src/components/select/DateSelect.tsx
  packages/desktop-client/src/components/tooltips.tsx
  packages/desktop-client/src/style/styles.ts
  packages/loot-core/src/client/query-hooks.tsx
  packages/loot-core/src/types/models/index.d.ts
  packages/loot-core/src/types/models/note.d.ts
  upcoming-release-notes/2493.md
  yarn.lock
Labels: ✅ Approved

#2570 [Bugfix] Remove menu from income group on mobile view
  packages/desktop-client/src/components/modals/CategoryGroupMenuModal.tsx
  upcoming-release-notes/2570.md
Labels: ✅ Approved

#2534 :recycle: (bank-sync) unify the sync/reconciliation logic for internal & external sync
  packages/loot-core/src/client/actions/account.ts
  packages/loot-core/src/server/accounts/__snapshots__/sync.test.ts.snap
  packages/loot-core/src/server/accounts/link.ts
  packages/loot-core/src/server/accounts/sync.test.ts
  packages/loot-core/src/server/accounts/sync.ts
  packages/loot-core/src/server/main.test.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/2534.md
Labels: ✅ Approved

#2538 Bugfix:Midnight theme button contrast
  packages/desktop-client/src/components/autocomplete/CategoryAutocomplete.tsx
  packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.tsx
  packages/desktop-client/src/style/themes/dark.ts
  packages/desktop-client/src/style/themes/development.ts
  packages/desktop-client/src/style/themes/light.ts
  packages/desktop-client/src/style/themes/midnight.ts
  upcoming-release-notes/2538.md
Labels: ✅ Approved

#2522 Custom Reports: Show Activity onClick
  packages/desktop-client/src/components/reports/ChooseGraph.tsx
  packages/desktop-client/src/components/reports/Overview.jsx
  packages/desktop-client/src/components/reports/ReportSidebar.jsx
  packages/desktop-client/src/components/reports/ReportTopbar.jsx
  packages/desktop-client/src/components/reports/graphs/BarGraph.tsx
  packages/desktop-client/src/components/reports/reports/CustomReport.jsx
  upcoming-release-notes/2522.md
Labels: ✅ Approved

#2572 [Mobile] Close modal after transferring / covering balance in mobile budget page
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  upcoming-release-notes/2572.md
Labels: ✅ Approved

#2573 [Mobile] Fix report budget income budgeted input
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  upcoming-release-notes/2573.md
Labels: ✅ Approved

#2523 When starting input with operator, append to existing value instead of replacing
  packages/desktop-client/src/components/table.tsx
  upcoming-release-notes/2523.md
Labels: ✅ Approved

#2569 Support splits in create-rule option on account page
  packages/desktop-client/src/components/accounts/Account.jsx
  upcoming-release-notes/2569.md
Labels: ✅ Approved

#2567 Improve api output types
  packages/api/tsconfig.dist.json
  packages/loot-core/src/server/importers/ynab5.ts
  packages/loot-core/src/types/api-handlers.d.ts
  upcoming-release-notes/2567.md
Labels: ✅ Approved

#2491 [Mobile] Budget menu modals
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-1-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-loads-the-budget-page-with-budgeted-amounts-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-loads-the-budget-page-with-budgeted-amounts-2-chromium-linux.png
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/common/Menu.tsx
  packages/desktop-client/src/components/common/Modal.tsx
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  packages/desktop-client/src/components/mobile/budget/index.tsx
  packages/desktop-client/src/components/modals/AccountMenuModal.tsx
  packages/desktop-client/src/components/modals/BudgetMenuModal.tsx
  packages/desktop-client/src/components/modals/CategoryGroupMenuModal.tsx
  packages/desktop-client/src/components/modals/CategoryMenuModal.tsx
  packages/desktop-client/src/components/modals/ReportBalanceMenuModal.tsx
  packages/desktop-client/src/components/modals/RolloverBalanceMenuModal.tsx
  packages/desktop-client/src/components/modals/RolloverToBudgetMenuModal.tsx
  packages/desktop-client/src/components/modals/ScheduledTransactionMenuModal.tsx
  packages/desktop-client/src/components/modals/SingleInputModal.tsx
  packages/desktop-client/src/components/modals/SwitchBudgetTypeModal.tsx
  packages/loot-core/src/client/state-types/modals.d.ts
  upcoming-release-notes/2491.md
Labels: ✅ Approved

#2577 Use desktop colors for mobile autocomplete modals
  packages/desktop-client/src/components/FatalError.tsx
  packages/desktop-client/src/components/MobileWebMessage.tsx
  packages/desktop-client/src/components/autocomplete/AccountAutocomplete.tsx
  packages/desktop-client/src/components/autocomplete/CategoryAutocomplete.tsx
  packages/desktop-client/src/components/autocomplete/ItemHeader.tsx
  packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.tsx
  packages/desktop-client/src/components/common/Modal.tsx
  packages/desktop-client/src/components/gocardless/GoCardlessLink.tsx
  packages/desktop-client/src/components/mobile/transactions/Option.jsx
  packages/desktop-client/src/components/modals/AccountAutocompleteModal.tsx
  packages/desktop-client/src/components/modals/CategoryAutocompleteModal.tsx
  packages/desktop-client/src/components/modals/EditField.jsx
  packages/desktop-client/src/components/modals/PayeeAutocompleteModal.tsx
  packages/desktop-client/src/style/themes/dark.ts
  packages/desktop-client/src/style/themes/development.ts
  packages/desktop-client/src/style/themes/light.ts
  packages/desktop-client/src/style/themes/midnight.ts
  upcoming-release-notes/2577.md
Labels: ✅ Approved

#2586 [Maintenance] Remove left behind editableTitle prop
  packages/desktop-client/src/components/common/Modal.tsx
  upcoming-release-notes/2586.md
Labels: ✅ Approved

#2581 Do not allow hiding income category group
  packages/desktop-client/src/components/budget/SidebarGroup.tsx
  packages/loot-core/migrations/1712784523000_unhide_input_group.sql
  upcoming-release-notes/2581.md
Labels: ✅ Approved

#2585 Add option to disable reconciliation when importing CSV and files.
  packages/desktop-client/src/components/modals/ImportTransactions.jsx
  upcoming-release-notes/2585.md
Labels: ✅ Approved

#2582 Dim categories hidden by their groups
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/budget/BudgetCategories.jsx
  packages/desktop-client/src/components/budget/ExpenseCategory.tsx
  packages/desktop-client/src/components/budget/SidebarCategory.tsx
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  packages/desktop-client/src/components/mobile/budget/index.tsx
  packages/desktop-client/src/components/modals/CategoryMenuModal.tsx
  packages/loot-core/src/client/state-types/modals.d.ts
  upcoming-release-notes/2582.md
Labels: ✅ Approved

#2588 Allow 5 decimal places in file import parser
  packages/loot-core/src/shared/util.test.ts
  packages/loot-core/src/shared/util.ts
  upcoming-release-notes/2588.md
Labels: ✅ Approved

#2580 Electron: Fix load backup functionality
  packages/desktop-client/src/components/App.tsx
  packages/desktop-electron/index.js
  packages/desktop-electron/menu.js
  packages/desktop-electron/preload.js
  upcoming-release-notes/2580.md
Labels: ✅ Approved

#2583 Custom Reports: Show Activity for donutGraph
  packages/desktop-client/src/components/reports/ChooseGraph.tsx
  packages/desktop-client/src/components/reports/graphs/DonutGraph.tsx
  upcoming-release-notes/2583.md
Labels: ✅ Approved

#2594 Hide Y axis values of net worth graph when privacy mode i…
  packages/desktop-client/src/components/reports/graphs/NetWorthGraph.tsx
  upcoming-release-notes/2594.md
Labels: ✅ Approved

#2589 Force transaction cleared checkboxes to show on reconcile view
  packages/desktop-client/src/components/accounts/Account.jsx
  upcoming-release-notes/2589.md
Labels: ✅ Approved

#2531 [Mobile] Category activity/transactions page
  packages/desktop-client/e2e/page-models/mobile-account-page.js
  packages/desktop-client/src/components/App.tsx
  packages/desktop-client/src/components/FinancesApp.tsx
  packages/desktop-client/src/components/accounts/Account.jsx
  packages/desktop-client/src/components/common/Link.tsx
  packages/desktop-client/src/components/mobile/MobileBackButton.tsx
  packages/desktop-client/src/components/mobile/MobileWebMessage.tsx
  packages/desktop-client/src/components/mobile/accounts/Account.jsx
  packages/desktop-client/src/components/mobile/accounts/AccountDetails.jsx
  packages/desktop-client/src/components/mobile/accounts/AccountTransactions.jsx
  packages/desktop-client/src/components/mobile/accounts/Accounts.jsx
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  packages/desktop-client/src/components/mobile/budget/Category.tsx
  packages/desktop-client/src/components/mobile/budget/CategoryTransactions.jsx
  packages/desktop-client/src/components/mobile/transactions/AddTransactionButton.tsx
  packages/desktop-client/src/components/mobile/transactions/ListBox.jsx
  packages/desktop-client/src/components/mobile/transactions/Transaction.jsx
  packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
  packages/desktop-client/src/components/mobile/transactions/TransactionList.jsx
  packages/desktop-client/src/components/mobile/transactions/TransactionListWithBalances.jsx
  packages/desktop-client/src/hooks/usePreviewTransactions.ts
  packages/loot-core/src/client/data-hooks/schedules.tsx
  packages/loot-core/src/client/queries.ts
  upcoming-release-notes/2531.md
Labels: ✅ Approved

#2501 [Mobile] Category budget actions modal
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-from-accounts-id-page-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-from-accounts-id-page-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-3-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-4-chromium-linux.png
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/budget/BudgetTable.jsx
  packages/desktop-client/src/components/budget/ExpenseCategory.tsx
  packages/desktop-client/src/components/budget/IncomeCategory.tsx
  packages/desktop-client/src/components/budget/RenderMonths.tsx
  packages/desktop-client/src/components/budget/report/BalanceTooltip.tsx
  packages/desktop-client/src/components/budget/report/BudgetMenu.tsx
  packages/desktop-client/src/components/budget/report/ReportComponents.tsx
  packages/desktop-client/src/components/budget/report/ReportContext.tsx
  packages/desktop-client/src/components/budget/rollover/BalanceTooltip.tsx
  packages/desktop-client/src/components/budget/rollover/BudgetMenu.tsx
  packages/desktop-client/src/components/budget/rollover/RolloverComponents.tsx
  packages/desktop-client/src/components/budget/rollover/RolloverContext.tsx
  packages/desktop-client/src/components/budget/rollover/budgetsummary/ToBudget.tsx
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  packages/desktop-client/src/components/mobile/budget/index.tsx
  packages/desktop-client/src/components/mobile/transactions/FocusableAmountInput.tsx
  packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
  packages/desktop-client/src/components/modals/AccountMenuModal.tsx
  packages/desktop-client/src/components/modals/BudgetMonthMenuModal.tsx
  packages/desktop-client/src/components/modals/CategoryGroupMenuModal.tsx
  packages/desktop-client/src/components/modals/CategoryMenuModal.tsx
  packages/desktop-client/src/components/modals/ReportBudgetMenuModal.tsx
  packages/desktop-client/src/components/modals/RolloverBudgetMenuModal.tsx
  packages/desktop-client/src/components/modals/RolloverBudgetSummaryModal.tsx
  packages/desktop-client/src/hooks/useCategory.ts
  packages/desktop-client/src/hooks/useCategoryGroup.ts
  packages/desktop-client/src/hooks/useMergedRefs.ts
  packages/loot-core/src/client/state-types/modals.d.ts
  upcoming-release-notes/2501.md
Labels: ✅ Approved

#2598 Balance menu modal enhancement
  packages/desktop-client/src/components/budget/BalanceWithCarryover.tsx
  packages/desktop-client/src/components/modals/ReportBalanceMenuModal.tsx
  packages/desktop-client/src/components/modals/RolloverBalanceMenuModal.tsx
  upcoming-release-notes/2598.md
Labels: ✅ Approved

#2593 :recycle: (tooltip) migration to react-aria (vol 2)
  packages/desktop-client/src/components/LoggedInUser.tsx
  packages/desktop-client/src/components/NotesButton.tsx
  packages/desktop-client/src/components/ThemeSelector.tsx
  packages/desktop-client/src/components/Titlebar.tsx
  packages/desktop-client/src/components/accounts/AccountSyncCheck.jsx
  packages/desktop-client/src/components/common/Popover.tsx
  packages/desktop-client/src/components/sidebar/Sidebar.tsx
  upcoming-release-notes/2593.md
Labels: ✅ Approved

#2601 :zap: extra error handling in case backend failed loading
  packages/desktop-client/src/browser-server.js
  packages/desktop-client/src/components/FatalError.tsx
  upcoming-release-notes/2601.md
Labels: ✅ Approved

#2608 [Mobile] Scheduled transaction menu modal
  packages/desktop-client/src/components/mobile/accounts/AccountTransactions.jsx
  upcoming-release-notes/2608.md
Labels: 🔍 Ready for Review

#2483 Add daily and weekly to custom reports interval list
  packages/desktop-client/src/components/reports/ChooseGraph.tsx
  packages/desktop-client/src/components/reports/ReportOptions.ts
  packages/desktop-client/src/components/reports/ReportSidebar.jsx
  packages/desktop-client/src/components/reports/ReportSummary.tsx
  packages/desktop-client/src/components/reports/disabledList.ts
  packages/desktop-client/src/components/reports/getLiveRange.ts
  packages/desktop-client/src/components/reports/reportRanges.ts
  packages/desktop-client/src/components/reports/reports/CustomReport.jsx
  packages/desktop-client/src/components/reports/reports/GetCardData.tsx
  packages/desktop-client/src/components/reports/spreadsheets/custom-spreadsheet.ts
  packages/desktop-client/src/components/reports/spreadsheets/grouped-spreadsheet.ts
  packages/desktop-client/src/components/reports/spreadsheets/makeQuery.ts
  packages/loot-core/src/server/aql/compiler.ts
  packages/loot-core/src/shared/months.ts
  upcoming-release-notes/2483.md
Labels: 🔍 Ready for Review, ✅ Approved

#2597 fix(#2575): Stop cash flow card labels from getting cutting off if bar height is too low
  packages/desktop-client/src/components/reports/reports/CashFlowCard.jsx
  upcoming-release-notes/2597.md
Labels: 🔍 Ready for Review

#2609 [Maintenance] Add missing key prop to all modals
  packages/desktop-client/src/components/Modals.tsx
  upcoming-release-notes/2609.md
Labels: ✅ Approved

#2614 :bug: (tooltip) add scrollbars to tooltips that go out of bounds
  packages/desktop-client/src/style/styles.ts
  upcoming-release-notes/2614.md
Labels: ✅ Approved

#2551 Display balances in category autocomplete
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/accounts/Account.jsx
  packages/desktop-client/src/components/autocomplete/CategoryAutocomplete.tsx
  packages/desktop-client/src/components/budget/util.ts
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
  packages/desktop-client/src/components/modals/CategoryAutocompleteModal.tsx
  packages/desktop-client/src/components/modals/CoverModal.tsx
  packages/desktop-client/src/components/modals/EditField.jsx
  packages/desktop-client/src/components/modals/RolloverBudgetSummaryModal.tsx
  packages/desktop-client/src/components/modals/TransferModal.tsx
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  packages/desktop-client/src/components/transactions/TransactionsTable.test.jsx
  packages/desktop-client/src/style/themes/dark.ts
  packages/desktop-client/src/style/themes/midnight.ts
  packages/loot-core/src/client/state-types/modals.d.ts
  upcoming-release-notes/2551.md
Labels: ✅ Approved

#2599 [Mobile] Fix account notes not retrieving correctly in mobile
  packages/desktop-client/src/components/NotesButton.tsx
  packages/desktop-client/src/components/modals/AccountMenuModal.tsx
  packages/desktop-client/src/components/modals/CategoryGroupMenuModal.tsx
  packages/desktop-client/src/components/modals/CategoryMenuModal.tsx
  packages/desktop-client/src/components/modals/Notes.tsx
  packages/desktop-client/src/hooks/useNotes.ts
  upcoming-release-notes/2599.md
Labels: ✅ Approved

#2613 [Mobile] Use budget start month pref on mobile to match desktop behavior
  packages/desktop-client/src/components/budget/index.tsx
  packages/desktop-client/src/components/mobile/budget/index.tsx
  upcoming-release-notes/2613.md
Labels: ✅ Approved

#2611 [Mobile] Collapsible budget groups
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-loads-the-budget-page-with-budgeted-amounts-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-loads-the-budget-page-with-budgeted-amounts-2-chromium-linux.png
  packages/desktop-client/src/components/budget/BudgetCategories.jsx
  packages/desktop-client/src/components/budget/BudgetTable.jsx
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  upcoming-release-notes/2611.md
Labels: ✅ Approved

#2607 [Mobile] Use decimal input mode for mobile modal amount fields
  packages/desktop-client/src/components/modals/HoldBufferModal.tsx
  packages/desktop-client/src/components/modals/RolloverBudgetSummaryModal.tsx
  packages/desktop-client/src/components/modals/TransferModal.tsx
  upcoming-release-notes/2607.md
Labels: ✅ Approved

#2620 rename electron master workflow
  .github/workflows/electron-master.yml
  upcoming-release-notes/2620.md
Labels: ✅ Approved

#2616 :fire: stripping out plaid integration
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/modals/PlaidExternalMsg.tsx
  packages/desktop-client/src/plaid.js
  packages/loot-core/src/client/state-types/modals.d.ts
  packages/loot-core/src/mocks/plaid.ts
  packages/loot-core/src/server/accounts/link.ts
  packages/loot-core/src/server/accounts/sync.test.ts
  packages/loot-core/src/server/accounts/sync.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/server/server-config.ts
  packages/loot-core/src/server/tests/mockSyncServer.ts
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/2616.md
Labels: ✅ Approved

#2610 [Mobile] Budget month notes and budget action menu
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-loads-the-budget-page-with-budgeted-amounts-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-loads-the-budget-page-with-budgeted-amounts-2-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-1-chromium-linux.png
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/budget/index.tsx
  packages/desktop-client/src/components/budget/report/budgetsummary/BudgetMonthMenu.tsx
  packages/desktop-client/src/components/budget/report/budgetsummary/BudgetSummary.tsx
  packages/desktop-client/src/components/budget/rollover/budgetsummary/BudgetMonthMenu.tsx
  packages/desktop-client/src/components/budget/rollover/budgetsummary/BudgetSummary.tsx
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  packages/desktop-client/src/components/mobile/budget/index.tsx
  packages/desktop-client/src/components/modals/BudgetPageMenuModal.tsx
  packages/desktop-client/src/components/modals/ReportBudgetMonthMenuModal.tsx
  packages/desktop-client/src/components/modals/RolloverBudgetMonthMenuModal.tsx
  packages/desktop-client/src/style/styles.ts
  packages/loot-core/src/client/state-types/modals.d.ts
  packages/loot-core/src/shared/months.ts
  upcoming-release-notes/2610.md
Labels: ✅ Approved

#2612 Custom Reports: Add filters to sessionStorage
  packages/desktop-client/src/components/reports/ChooseGraph.tsx
  packages/desktop-client/src/components/reports/ReportSidebar.jsx
  packages/desktop-client/src/components/reports/ReportTopbar.jsx
  packages/desktop-client/src/components/reports/graphs/BarGraph.tsx
  packages/desktop-client/src/components/reports/graphs/DonutGraph.tsx
  packages/desktop-client/src/components/reports/reports/CustomReport.jsx
  packages/desktop-client/src/components/reports/setSessionReport.ts
  upcoming-release-notes/2612.md
Labels: ✅ Approved

#2617 add flatpak to electron build list
  .github/workflows/electron-master.yml
  .github/workflows/electron-pr.yml
  packages/desktop-electron/package.json
  upcoming-release-notes/2617.md
Labels: ✅ Approved

#2632 Add assets to release
  .github/workflows/electron-master.yml
  upcoming-release-notes/2632.md
Labels: ✅ Approved

#2623 [Maintenance] Organize .gitignore
  .gitignore
  upcoming-release-notes/2623.md
Labels: ✅ Approved

#2634 [Maintenance] Fix slow/flaky VRT test
  packages/desktop-client/e2e/schedules.test.js
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-1-chromium-linux.png
  upcoming-release-notes/2634.md
Labels: ✅ Approved

#2650 fix superfluous tooltip scrollbars fixes #2621
  packages/desktop-client/src/style/styles.ts
  upcoming-release-notes/2650.md
Labels: ✅ Approved

#2649 :bug: fix budget-type identification when deleting files
  packages/loot-core/src/server/main.ts
  upcoming-release-notes/2649.md
Labels: ✅ Approved

#2606 Custom Reports StackedBar show activity
  packages/desktop-client/src/components/reports/ChooseGraph.tsx
  packages/desktop-client/src/components/reports/graphs/StackedBarGraph.tsx
  packages/desktop-client/src/components/reports/reports/CustomReport.jsx
  packages/desktop-client/src/components/reports/spreadsheets/calculateLegend.ts
  packages/desktop-client/src/components/reports/spreadsheets/custom-spreadsheet.ts
  packages/loot-core/src/types/models/reports.d.ts
  upcoming-release-notes/2606.md
Labels: ✅ Approved

#2637 Custom Reports update TS issues
  packages/desktop-client/src/components/reports/getLiveRange.ts
  packages/desktop-client/src/components/reports/reportRanges.ts
  packages/desktop-client/src/components/reports/reports/CustomReport.jsx
  packages/desktop-client/src/components/reports/reports/CustomReportListCards.tsx
  packages/desktop-client/src/components/reports/reports/GetCardData.tsx
  packages/desktop-client/src/components/reports/spreadsheets/custom-spreadsheet.ts
  packages/loot-core/src/shared/months.ts
  upcoming-release-notes/2637.md
Labels: ✅ Approved

#2651 Improve 'Before split' section in rule splits
  packages/desktop-client/src/components/modals/EditRule.jsx
  packages/desktop-client/src/components/rules/RuleRow.tsx
  packages/desktop-client/src/components/transactions/TransactionsTable.test.jsx
  packages/loot-core/src/server/accounts/rules.ts
  packages/loot-core/src/shared/transactions.ts
  upcoming-release-notes/2651.md
Labels: ✅ Approved

#2633 [Mobile] Fix encryption modals for mobile
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/common/Modal.tsx
  packages/desktop-client/src/components/manager/Modals.jsx
  packages/desktop-client/src/components/modals/CreateEncryptionKey.tsx
  packages/desktop-client/src/components/modals/CreateEncryptionKeyModal.tsx
  packages/desktop-client/src/components/modals/FixEncryptionKey.tsx
  packages/desktop-client/src/components/modals/FixEncryptionKeyModal.tsx
  upcoming-release-notes/2633.md
Labels: ✅ Approved

#2639 :sparkles: added loading descriptions and lazy-loaded module retries
  packages/desktop-client/package.json
  packages/desktop-client/src/components/App.tsx
  packages/desktop-client/src/components/AppBackground.tsx
  packages/desktop-client/src/components/util/LoadComponent.tsx
  upcoming-release-notes/2639.md
  yarn.lock
Labels: ✅ Approved

#2604 Add VRT test for validating that split transaction rules work as expected
  packages/desktop-client/e2e/page-models/account-page.js
  packages/desktop-client/e2e/page-models/rules-page.js
  packages/desktop-client/e2e/page-models/settings-page.js
  packages/desktop-client/e2e/rules.test.js
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-split-transaction-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-split-transaction-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-2-chromium-linux.png
  packages/desktop-client/src/components/modals/EditRule.jsx
  packages/desktop-client/src/components/settings/Experimental.tsx
  packages/desktop-client/src/components/settings/UI.tsx
  upcoming-release-notes/2604.md
Labels: 🔍 Ready for Review

#2635 [Mobile] Add To Be Budgeted category to cover and transfer modal
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/modals/CoverModal.tsx
  packages/desktop-client/src/components/modals/TransferModal.tsx
  upcoming-release-notes/2635.md
Labels: ✅ Approved

#2627 [Mobile] Update mobile labels to be sentence case + add labels to mobile budget and balance modals
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-1-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-2-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-3-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-from-accounts-id-page-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-from-accounts-id-page-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-from-accounts-id-page-3-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-3-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-4-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-5-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-6-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-7-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-8-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-9-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-loads-the-budget-page-with-budgeted-amounts-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-loads-the-budget-page-with-budgeted-amounts-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-loads-the-budget-page-with-budgeted-amounts-3-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-3-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-4-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-5-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-6-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-7-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-8-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-9-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-the-accounts-page-and-asserts-on-balances-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-the-accounts-page-and-asserts-on-balances-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-the-accounts-page-and-asserts-on-balances-3-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-12-chromium-linux.png
  packages/desktop-client/src/components/common/Label.tsx
  packages/desktop-client/src/components/common/Modal.tsx
  packages/desktop-client/src/components/mobile/MobileForms.tsx
  packages/desktop-client/src/components/mobile/accounts/Accounts.jsx
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  packages/desktop-client/src/components/mobile/transactions/TransactionListWithBalances.jsx
  packages/desktop-client/src/components/modals/CoverModal.tsx
  packages/desktop-client/src/components/modals/ReportBalanceMenuModal.tsx
  packages/desktop-client/src/components/modals/ReportBudgetMenuModal.tsx
  packages/desktop-client/src/components/modals/RolloverBalanceMenuModal.tsx
  packages/desktop-client/src/components/modals/RolloverBudgetMenuModal.tsx
  upcoming-release-notes/2627.md
Labels: ✅ Approved

#2571 Consistent modal paddings
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-1-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-2-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-3-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-split-transaction-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-3-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-12-chromium-linux.png
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/common/Modal.tsx
  packages/desktop-client/src/components/manager/DeleteFile.tsx
  packages/desktop-client/src/components/modals/AccountAutocompleteModal.tsx
  packages/desktop-client/src/components/modals/AccountMenuModal.tsx
  packages/desktop-client/src/components/modals/BudgetPageMenuModal.tsx
  packages/desktop-client/src/components/modals/CategoryAutocompleteModal.tsx
  packages/desktop-client/src/components/modals/CategoryGroupMenuModal.tsx
  packages/desktop-client/src/components/modals/CategoryMenuModal.tsx
  packages/desktop-client/src/components/modals/CoverModal.tsx
  packages/desktop-client/src/components/modals/CreateAccountModal.tsx
  packages/desktop-client/src/components/modals/CreateEncryptionKeyModal.tsx
  packages/desktop-client/src/components/modals/CreateLocalAccountModal.tsx
  packages/desktop-client/src/components/modals/EditField.jsx
  packages/desktop-client/src/components/modals/EditRule.jsx
  packages/desktop-client/src/components/modals/FixEncryptionKeyModal.tsx
  packages/desktop-client/src/components/modals/HoldBufferModal.tsx
  packages/desktop-client/src/components/modals/LoadBackup.jsx
  packages/desktop-client/src/components/modals/ManageRulesModal.tsx
  packages/desktop-client/src/components/modals/MergeUnusedPayees.jsx
  packages/desktop-client/src/components/modals/Notes.tsx
  packages/desktop-client/src/components/modals/PayeeAutocompleteModal.tsx
  packages/desktop-client/src/components/modals/ReportBalanceMenuModal.tsx
  packages/desktop-client/src/components/modals/ReportBudgetMenuModal.tsx
  packages/desktop-client/src/components/modals/ReportBudgetMonthMenuModal.tsx
  packages/desktop-client/src/components/modals/ReportBudgetSummaryModal.tsx
  packages/desktop-client/src/components/modals/RolloverBalanceMenuModal.tsx
  packages/desktop-client/src/components/modals/RolloverBudgetMenuModal.tsx
  packages/desktop-client/src/components/modals/RolloverBudgetMonthMenuModal.tsx
  packages/desktop-client/src/components/modals/RolloverBudgetSummaryModal.tsx
  packages/desktop-client/src/components/modals/RolloverToBudgetMenuModal.tsx
  packages/desktop-client/src/components/modals/ScheduledTransactionMenuModal.tsx
  packages/desktop-client/src/components/modals/SingleInputModal.tsx
  packages/desktop-client/src/components/modals/SwitchBudgetTypeModal.tsx
  packages/desktop-client/src/components/modals/TransferModal.tsx
  upcoming-release-notes/2571.md
Labels: ✅ Approved

#2636 Custom Reports: Line show activity
  packages/desktop-client/src/components/reports/ChooseGraph.tsx
  packages/desktop-client/src/components/reports/ReportTopbar.jsx
  packages/desktop-client/src/components/reports/graphs/LineGraph.tsx
  packages/desktop-client/src/components/reports/graphs/StackedBarGraph.tsx
  upcoming-release-notes/2636.md
Labels: ✅ Approved

#2641 Make /login show descriptive error when an incorrect password is submitted
  packages/loot-core/src/server/main.ts
  upcoming-release-notes/2641.md
Labels: ✅ Approved

#2658 Fix for electron builds
  .github/workflows/electron-master.yml
  .github/workflows/electron-pr.yml
  upcoming-release-notes/2658.md
Labels: ✅ Approved

#2502 Fix reconciling split translations from nYNAB import creates orphan transfers
  packages/desktop-client/e2e/data/ynab5-demo-budget.json
  packages/loot-core/src/server/importers/ynab5-types.d.ts
  packages/loot-core/src/server/importers/ynab5.ts
  upcoming-release-notes/2502.md
Labels: ✅ Approved

#2657 :sparkles: improving error handling for lazy-loading
  packages/desktop-client/src/components/App.tsx
  packages/desktop-client/src/components/FatalError.tsx
  packages/desktop-client/src/components/common/Modal.tsx
  packages/desktop-client/src/components/gocardless/GoCardlessLink.tsx
  packages/desktop-client/src/components/util/LoadComponent.tsx
  packages/loot-core/src/shared/errors.ts
  upcoming-release-notes/2657.md
Labels: ✅ Approved

#2665 [Mobile] Add amount colors to mobile accounts and transaction list
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-7-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-8-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-9-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-3-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-7-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-8-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-9-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-the-accounts-page-and-asserts-on-balances-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-the-accounts-page-and-asserts-on-balances-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-the-accounts-page-and-asserts-on-balances-3-chromium-linux.png
  packages/desktop-client/src/components/budget/BalanceWithCarryover.tsx
  packages/desktop-client/src/components/budget/util.ts
  packages/desktop-client/src/components/mobile/accounts/Accounts.jsx
  packages/desktop-client/src/components/mobile/transactions/Transaction.jsx
  upcoming-release-notes/2665.md
Labels: ✅ Approved

#2659 Custom Reports Adjustments
  packages/desktop-client/src/components/filters/AppliedFilters.tsx
  packages/desktop-client/src/components/filters/FilterExpression.tsx
  packages/desktop-client/src/components/filters/FiltersMenu.jsx
  packages/desktop-client/src/components/filters/FiltersStack.tsx
  packages/desktop-client/src/components/reports/Change.tsx
  packages/desktop-client/src/components/reports/ModeButton.tsx
  packages/desktop-client/src/components/reports/ReportCard.tsx
  packages/desktop-client/src/components/reports/reports/CashFlowCard.jsx
  packages/desktop-client/src/components/reports/reports/NetWorthCard.jsx
  packages/desktop-client/src/components/reports/spreadsheets/custom-spreadsheet.ts
  packages/desktop-client/src/components/reports/spreadsheets/grouped-spreadsheet.ts
  packages/desktop-client/src/components/reports/spreadsheets/makeQuery.ts
  packages/desktop-client/src/style/themes/dark.ts
  packages/desktop-client/src/style/themes/development.ts
  packages/desktop-client/src/style/themes/light.ts
  packages/desktop-client/src/style/themes/midnight.ts
  packages/loot-core/src/shared/months.ts
  upcoming-release-notes/2659.md
Labels: ✅ Approved

#2663 Fix loading screen not showing when opening a budget file
  packages/desktop-client/src/components/App.tsx
  packages/desktop-client/src/components/AppBackground.tsx
  packages/desktop-client/src/components/manager/BudgetList.jsx
  packages/loot-core/src/types/file.d.ts
  upcoming-release-notes/2663.md
Labels: ✅ Approved

#2638 Fix menuItemTextHeader contrast in dark mode
  packages/desktop-client/src/style/themes/dark.ts
  packages/desktop-client/src/style/themes/midnight.ts
  upcoming-release-notes/2638.md
Labels: ✅ Approved

#2653 Ignore transactions with empty date & amount
  packages/loot-core/src/server/accounts/parse-file.ts
  upcoming-release-notes/2653.md
Labels: 🔍 Ready for Review

#2688 [Goals]add template to set x month average
  packages/loot-core/src/server/budget/goal-template.pegjs
  packages/loot-core/src/server/budget/goals/goalsAverage.ts
  packages/loot-core/src/server/budget/goaltemplates.ts
  upcoming-release-notes/2688.md
Labels: ✅ Approved

#2689 [Goals] Allow decimal in percent templates
  packages/loot-core/src/server/budget/goal-template.pegjs
  upcoming-release-notes/2689.md
Labels: ✅ Approved
