Repository actualbudget/actual, pull requests merged in 2024-03, with the labels that each got.

#2386 Custom reports updates
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-and-cash-flow-reports-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-and-cash-flow-reports-2-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-graph-and-checks-visuals-2-chromium-linux.png
  packages/desktop-client/src/components/reports/Header.jsx
  packages/desktop-client/src/components/reports/Overview.jsx
  packages/desktop-client/src/components/reports/ReportOptions.ts
  packages/desktop-client/src/components/reports/ReportSidebar.jsx
  packages/desktop-client/src/components/reports/SaveReport.tsx
  packages/desktop-client/src/components/reports/SaveReportName.tsx
  packages/desktop-client/src/components/reports/reports/CustomReport.jsx
  packages/desktop-client/src/components/reports/reports/CustomReportCard.jsx
  packages/desktop-client/src/components/reports/reports/CustomReportListCards.tsx
  packages/loot-core/src/types/models/reports.d.ts
  upcoming-release-notes/2386.md
Labels: ✅ Approved

#2411 BarGraph crash
  packages/desktop-client/src/components/reports/graphs/BarGraph.tsx
  packages/desktop-client/src/components/reports/graphs/renderCustomLabel.tsx
  upcoming-release-notes/2411.md
Labels: ✅ Approved

#2403 :recycle: (typescript) move some files to strict mode
  packages/desktop-client/src/components/FatalError.tsx
  packages/desktop-client/src/components/GlobalKeys.ts
  packages/desktop-client/src/components/accounts/Account.jsx
  packages/desktop-client/src/components/manager/ImportActual.tsx
  packages/desktop-client/src/components/manager/ImportYNAB4.tsx
  packages/desktop-client/src/components/manager/ImportYNAB5.tsx
  packages/desktop-client/src/components/manager/ManagementApp.jsx
  packages/desktop-client/src/components/modals/ImportTransactions.jsx
  packages/desktop-client/src/components/settings/Export.tsx
  packages/desktop-client/src/components/settings/FixSplits.tsx
  packages/desktop-client/src/components/settings/Global.tsx
  packages/desktop-client/src/components/settings/Reset.tsx
  packages/desktop-client/src/components/settings/index.tsx
  packages/desktop-client/src/gocardless.ts
  packages/desktop-client/src/hooks/useFeatureFlag.ts
  packages/desktop-client/src/plaid.js
  packages/desktop-client/src/tokens.ts
  packages/desktop-client/src/util/versions.ts
  upcoming-release-notes/2403.md
Labels: ✅ Approved

#2388 Update shared transaction module to strict typescript
  packages/loot-core/src/shared/transactions.ts
  packages/loot-core/src/types/models/transaction.d.ts
  upcoming-release-notes/2388.md
Labels: ✅ Approved

#2398 Add option to make a transfer from two selected transactions
  packages/desktop-client/e2e/accounts.test.js
  packages/desktop-client/e2e/page-models/account-page.js
  packages/desktop-client/src/components/accounts/Account.jsx
  packages/desktop-client/src/components/accounts/Header.jsx
  packages/desktop-client/src/components/table.tsx
  packages/desktop-client/src/components/transactions/SelectedTransactions.jsx
  packages/loot-core/src/client/transfer.test.ts
  packages/loot-core/src/client/transfer.ts
  upcoming-release-notes/2398.md
Labels: ✅ Approved

#2416 :sparkles: (bank-sync) quality of life improvements for sync
  packages/desktop-client/src/components/BankSyncStatus.tsx
  packages/desktop-client/src/components/accounts/Account.jsx
  packages/desktop-client/src/components/accounts/Header.jsx
  packages/desktop-client/src/components/sidebar/Account.tsx
  packages/desktop-client/src/components/sidebar/Accounts.tsx
  packages/desktop-client/src/style/themes/dark.ts
  packages/desktop-client/src/style/themes/development.ts
  packages/desktop-client/src/style/themes/light.ts
  packages/desktop-client/src/style/themes/midnight.ts
  packages/loot-core/src/client/actions/account.ts
  packages/loot-core/src/client/actions/sync.ts
  packages/loot-core/src/client/constants.ts
  packages/loot-core/src/client/reducers/account.ts
  packages/loot-core/src/client/state-types/account.d.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/2416.md
Labels: ✅ Approved

#2409 [End of Month Cleanup] Remove automatic funding of rollover categories
  packages/loot-core/src/server/budget/cleanup-template.ts
  upcoming-release-notes/2409.md
Labels: ✅ Approved

#2404 [Goals] Schedule top off amount
  packages/loot-core/src/server/budget/goals/goalsSchedule.ts
  upcoming-release-notes/2404.md
Labels: ✅ Approved

#2422 [Bugfix] Midnight theme - Budget Name color, Mobile category color in account view
  packages/desktop-client/src/components/accounts/MobileAccounts.jsx
  packages/desktop-client/src/components/transactions/MobileTransaction.jsx
  packages/desktop-client/src/style/themes/midnight.ts
  upcoming-release-notes/2422.md
Labels: ✅ Approved

#2421 Fix ofx amount parsing for longer decimal places
  packages/loot-core/src/mocks/files/data-multi-decimal.ofx
  packages/loot-core/src/server/accounts/parse-file.test.ts
  packages/loot-core/src/server/accounts/parse-file.ts
  upcoming-release-notes/2421.md
Labels: ✅ Approved

#2408 Show activity updates
  packages/desktop-client/e2e/budget.test.js
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-category-5-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-category-6-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-date-5-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-date-6-chromium-linux.png
  packages/desktop-client/src/components/accounts/Account.jsx
  packages/desktop-client/src/components/accounts/Balance.jsx
  packages/desktop-client/src/components/accounts/Header.jsx
  packages/desktop-client/src/components/budget/BudgetTable.jsx
  packages/desktop-client/src/components/budget/ExpenseCategory.tsx
  packages/desktop-client/src/components/budget/IncomeCategory.tsx
  packages/desktop-client/src/components/budget/index.tsx
  packages/desktop-client/src/components/budget/report/ReportComponents.tsx
  packages/desktop-client/src/components/budget/rollover/RolloverComponents.tsx
  upcoming-release-notes/2408.md
Labels: ✅ Approved

#2419 [WIP] Implement "pill gesture" icon in navigation bar on Mobile view for better UX
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-checks-that-settings-page-can-be-opened-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-checks-that-settings-page-can-be-opened-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-loads-the-budget-page-with-budgeted-amounts-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-loads-the-budget-page-with-budgeted-amounts-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-the-accounts-page-and-asserts-on-balances-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-the-accounts-page-and-asserts-on-balances-2-chromium-linux.png
  packages/desktop-client/src/components/accounts/MobileAccounts.jsx
  packages/desktop-client/src/components/budget/MobileBudgetTable.jsx
  packages/desktop-client/src/components/mobile/MobileNavTabs.tsx
  upcoming-release-notes/2419.md
Labels: 🚧 WIP

#2434 Fix flaky transfer e2e test
  packages/desktop-client/e2e/accounts.test.js
  upcoming-release-notes/2434.md
Labels: ✅ Approved

#2447 Show scheduled transactions when viewing "All accounts"
  packages/desktop-client/src/components/accounts/Account.jsx
  upcoming-release-notes/2447.md
Labels: ✅ Approved

#2446 Provide "api/category-groups-get" API endpoint
  packages/api/methods.test.ts
  packages/api/methods.ts
  packages/loot-core/src/server/api.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/types/api-handlers.d.ts
  upcoming-release-notes/2446.md
Labels: ✅ Approved

#2441 Show a modal to confirm unlinking accounts
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/accounts/Account.jsx
  packages/desktop-client/src/components/modals/ConfirmUnlinkAccount.tsx
  upcoming-release-notes/2441.md
Labels: ✅ Approved

#2452 Fix budget key tab navigation
  packages/desktop-client/src/components/budget/BudgetTable.jsx
  upcoming-release-notes/2452.md
Labels: 🔍 Ready for Review

#2381 [Maintenance] Input onChangeValue and onUpdate prop naming
  packages/desktop-client/src/components/accounts/MobileAccountDetails.jsx
  packages/desktop-client/src/components/common/Input.tsx
  packages/desktop-client/src/components/common/Search.tsx
  packages/desktop-client/src/components/filters/NameFilter.tsx
  packages/desktop-client/src/components/manager/ConfigServer.tsx
  packages/desktop-client/src/components/mobile/MobileAmountInput.jsx
  packages/desktop-client/src/components/mobile/MobileForms.jsx
  packages/desktop-client/src/components/modals/GoCardlessInitialise.tsx
  packages/desktop-client/src/components/modals/ImportTransactions.jsx
  packages/desktop-client/src/components/modals/SimpleFinInitialise.tsx
  packages/desktop-client/src/components/modals/SingleInput.tsx
  packages/desktop-client/src/components/reports/SaveReportName.tsx
  packages/desktop-client/src/components/table.tsx
  packages/desktop-client/src/components/util/AmountInput.tsx
  upcoming-release-notes/2381.md
Labels: ✅ Approved

#2461 Fix midnight theme autocomplete hover
  packages/desktop-client/src/components/autocomplete/CategoryAutocomplete.tsx
  packages/desktop-client/src/components/autocomplete/ItemHeader.tsx
  packages/desktop-client/src/style/themes/midnight.ts
  upcoming-release-notes/2461.md
Labels: 🔍 Ready for Review

#2425 [Maintenance] Reorganize mobile components
  packages/desktop-client/package.json
  packages/desktop-client/src/components/FinancesApp.tsx
  packages/desktop-client/src/components/accounts/Account.jsx
  packages/desktop-client/src/components/accounts/Balance.jsx
  packages/desktop-client/src/components/accounts/Header.jsx
  packages/desktop-client/src/components/mobile/PullToRefresh.tsx
  packages/desktop-client/src/components/mobile/accounts/Account.jsx
  packages/desktop-client/src/components/mobile/accounts/AccountDetails.jsx
  packages/desktop-client/src/components/mobile/accounts/Accounts.jsx
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  packages/desktop-client/src/components/mobile/budget/ListItem.tsx
  packages/desktop-client/src/components/mobile/budget/index.tsx
  packages/desktop-client/src/components/mobile/transactions/FocusableAmountInput.jsx
  packages/desktop-client/src/components/mobile/transactions/ListBox.jsx
  packages/desktop-client/src/components/mobile/transactions/ListBoxSection.jsx
  packages/desktop-client/src/components/mobile/transactions/Option.jsx
  packages/desktop-client/src/components/mobile/transactions/Transaction.jsx
  packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
  packages/desktop-client/src/components/mobile/transactions/TransactionList.jsx
  packages/desktop-client/src/components/responsive/narrow.ts
  packages/desktop-client/src/components/transactions/SelectedTransactions.jsx
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  packages/desktop-client/src/components/transactions/TransactionsTable.test.jsx
  packages/desktop-client/src/hooks/useSplitsExpanded.jsx
  packages/loot-core/src/client/state-types/modals.d.ts
  packages/loot-core/src/shared/transactions.ts
  upcoming-release-notes/2425.md
  yarn.lock
Labels: ✅ Approved

#2453 :recycle: (typescript) make rollover budget components strict TS compliant
  packages/desktop-client/src/components/autocomplete/Autocomplete.tsx
  packages/desktop-client/src/components/autocomplete/CategoryAutocomplete.tsx
  packages/desktop-client/src/components/budget/rollover/BalanceTooltip.tsx
  packages/desktop-client/src/components/budget/rollover/CoverTooltip.tsx
  packages/desktop-client/src/components/budget/rollover/HoldTooltip.tsx
  packages/desktop-client/src/components/budget/rollover/RolloverComponents.tsx
  packages/desktop-client/src/components/budget/rollover/RolloverContext.tsx
  packages/desktop-client/src/components/budget/rollover/TransferTooltip.tsx
  packages/desktop-client/src/components/budget/rollover/budgetsummary/BudgetSummary.tsx
  packages/desktop-client/src/components/budget/rollover/budgetsummary/ToBudget.tsx
  packages/desktop-client/src/components/budget/util.ts
  packages/desktop-client/src/components/util/AmountInput.tsx
  packages/loot-core/src/shared/arithmetic.ts
  upcoming-release-notes/2453.md
Labels: ✅ Approved

#2460 [Theme] Bugfix: Bulk edit background color for Midnight theme
  packages/desktop-client/src/style/themes/midnight.ts
  upcoming-release-notes/2460.md
Labels: ✅ Approved

#2455 import locked transactions ynab4
  packages/loot-core/src/server/importers/ynab4.ts
  upcoming-release-notes/2455.md
Labels: ✅ Approved

#2410 Custom Reports disabled list
  packages/desktop-client/src/components/reports/ReportOptions.ts
  packages/desktop-client/src/components/reports/ReportSidebar.jsx
  packages/desktop-client/src/components/reports/ReportTopbar.jsx
  packages/desktop-client/src/components/reports/disabledList.ts
  packages/desktop-client/src/components/reports/reports/CustomReport.jsx
  upcoming-release-notes/2410.md
Labels: ✅ Approved

#2459 Convert BudgetTable to a functional component
  packages/desktop-client/src/components/budget/BudgetTable.jsx
  packages/desktop-client/src/components/budget/DynamicBudgetTable.tsx
  packages/desktop-client/src/components/budget/index.tsx
  upcoming-release-notes/2459.md
Labels: ✅ Approved

#2462 Increase minimum cleared column width (Fix #2341)
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-1-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-2-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-3-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-4-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-creates-a-new-account-and-views-the-initial-balance-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-creates-a-new-account-and-views-the-initial-balance-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-3-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-4-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-checks-the-page-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-checks-the-page-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-split-test-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-split-test-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-test-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-test-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-category-5-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-category-6-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-date-5-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-date-6-chromium-linux.png
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  upcoming-release-notes/2462.md
Labels: ✅ Approved

#2478 Update sync.ts
  packages/loot-core/src/server/accounts/sync.ts
Labels: ✅ Approved

#2479 Custom Reports: Intervals Updates
  packages/desktop-client/src/components/reports/ChooseGraph.tsx
  packages/desktop-client/src/components/reports/Header.jsx
  packages/desktop-client/src/components/reports/ReportOptions.ts
  packages/desktop-client/src/components/reports/ReportSidebar.jsx
  packages/desktop-client/src/components/reports/ReportSummary.tsx
  packages/desktop-client/src/components/reports/graphs/AreaGraph.tsx
  packages/desktop-client/src/components/reports/graphs/BarGraph.tsx
  packages/desktop-client/src/components/reports/graphs/DonutGraph.tsx
  packages/desktop-client/src/components/reports/graphs/StackedBarGraph.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTable.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableList.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableRow.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableTotals.tsx
  packages/desktop-client/src/components/reports/reportRanges.ts
  packages/desktop-client/src/components/reports/reports/CustomReport.jsx
  packages/desktop-client/src/components/reports/spreadsheets/calculateLegend.ts
  packages/desktop-client/src/components/reports/spreadsheets/custom-spreadsheet.ts
  packages/desktop-client/src/components/reports/spreadsheets/grouped-spreadsheet.ts
  packages/desktop-client/src/components/reports/spreadsheets/makeQuery.ts
  packages/desktop-client/src/components/reports/spreadsheets/recalculate.ts
  packages/loot-core/src/types/models/reports.d.ts
  upcoming-release-notes/2479.md
Labels: ✅ Approved

#2474 Import locked transactions from nYNAB
  packages/desktop-client/e2e/data/ynab5-demo-budget.json
  packages/loot-core/src/server/importers/ynab5.ts
  upcoming-release-notes/2474.md
Labels: ✅ Approved

#2475 Fix error when viewing uncategorized transactions when there are upcoming scheduled transactions.
  packages/desktop-client/src/components/accounts/Account.jsx
  upcoming-release-notes/2475.md
Labels: 🔍 Ready for Review, ✅ Approved

#2464 :bug: (import) patch phantom transactions getting created
  packages/loot-core/src/server/accounts/sync.ts
  upcoming-release-notes/2464.md
Labels: ✅ Approved

#2485 :bug: (report) do not include offbudget transfers in cash-flow card expenses
  packages/desktop-client/src/components/reports/spreadsheets/cash-flow-spreadsheet.tsx
  upcoming-release-notes/2485.md
Labels: ✅ Approved

#2487 Force async onRefresh on PullToRefresh component
  packages/desktop-client/src/components/mobile/PullToRefresh.tsx
  upcoming-release-notes/2487.md
Labels: ✅ Approved

#2443 Create wip
  .github/workflows/wip.yml
  upcoming-release-notes/2443.md
Labels: ✅ Approved

#2481 :recycle: (typescript) port some common components to strict TS
  packages/desktop-client/src/components/common/AlignedText.tsx
  packages/desktop-client/src/components/common/Button.tsx
  packages/desktop-client/src/components/common/InitialFocus.ts
  packages/desktop-client/src/components/common/Input.tsx
  packages/desktop-client/src/components/common/InputWithContent.tsx
  packages/desktop-client/src/components/common/Link.tsx
  packages/desktop-client/src/components/common/Menu.tsx
  packages/desktop-client/src/components/common/MenuTooltip.tsx
  packages/desktop-client/src/components/common/Modal.tsx
  packages/desktop-client/src/components/common/Search.tsx
  packages/desktop-client/src/components/util/AmountInput.tsx
  packages/desktop-client/src/hooks/useMergedRefs.ts
  packages/desktop-client/src/hooks/useProperFocus.tsx
  upcoming-release-notes/2481.md
Labels: ✅ Approved

#2494 :bug: (import) disallow importing transactions with too large or small amounts
  packages/desktop-client/src/components/modals/ImportTransactions.jsx
  packages/loot-core/src/shared/util.ts
  upcoming-release-notes/2494.md
Labels: ✅ Approved

#2489 :bug: fix hotkeys sometimes not working
  .eslintrc.js
  packages/desktop-client/package.json
  packages/desktop-client/src/components/App.tsx
  packages/desktop-client/src/components/FinancesApp.tsx
  packages/desktop-client/src/components/KeyHandlers.tsx
  packages/desktop-client/src/components/Titlebar.tsx
  packages/desktop-client/src/components/accounts/Header.jsx
  packages/desktop-client/src/components/common/Modal.tsx
  packages/desktop-client/src/components/table.tsx
  packages/desktop-client/src/components/transactions/SelectedTransactions.jsx
  upcoming-release-notes/2489.md
  yarn.lock
Labels: ✅ Approved

#2500 Autocomplete changes related to mobile modals PR
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-5-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-creates-a-transaction-via-footer-button-6-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-3-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-4-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-5-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-6-chromium-linux.png
  packages/desktop-client/src/components/autocomplete/AccountAutocomplete.tsx
  packages/desktop-client/src/components/autocomplete/Autocomplete.tsx
  packages/desktop-client/src/components/autocomplete/CategoryAutocomplete.tsx
  packages/desktop-client/src/components/autocomplete/ItemHeader.tsx
  packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.tsx
  packages/desktop-client/src/components/autocomplete/ReportAutocomplete.tsx
  packages/desktop-client/src/components/budget/rollover/CoverTooltip.tsx
  packages/desktop-client/src/components/budget/rollover/TransferTooltip.tsx
  packages/desktop-client/src/components/common/Input.tsx
  packages/desktop-client/src/components/common/Menu.tsx
  packages/desktop-client/src/components/mobile/accounts/AccountDetails.jsx
  packages/desktop-client/src/components/mobile/transactions/Transaction.jsx
  packages/desktop-client/src/components/modals/CloseAccount.tsx
  packages/desktop-client/src/components/modals/ConfirmCategoryDelete.tsx
  packages/desktop-client/src/components/modals/EditField.jsx
  packages/desktop-client/src/components/reports/SaveReportMenu.tsx
  packages/desktop-client/src/components/schedules/ScheduleDetails.jsx
  packages/desktop-client/src/components/select/DateSelect.tsx
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  packages/desktop-client/src/components/util/GenericInput.jsx
  packages/desktop-client/src/style/styles.ts
  packages/loot-core/src/client/actions/queries.ts
  upcoming-release-notes/2500.md
Labels: ✅ Approved

#2504 Fix mobile transactions load more
  packages/desktop-client/src/components/ScrollProvider.tsx
  packages/desktop-client/src/components/mobile/transactions/ListBox.jsx
  upcoming-release-notes/2504.md
Labels: ✅ Approved

#2476 feature: Show account sync indicators when viewing accounts on mobile
  packages/desktop-client/src/components/mobile/accounts/Account.jsx
  packages/desktop-client/src/components/mobile/accounts/AccountDetails.jsx
  packages/desktop-client/src/components/mobile/accounts/Accounts.jsx
  upcoming-release-notes/2476.md
Labels: ✅ Approved

#2505 Custom Reports live data
  packages/desktop-client/src/components/reports/reports/CustomReport.jsx
  packages/desktop-client/src/components/reports/reports/CustomReportListCards.tsx
  packages/desktop-client/src/components/reports/reports/GetCardData.tsx
  packages/desktop-client/src/components/reports/spreadsheets/cash-flow-spreadsheet.tsx
  packages/desktop-client/src/components/reports/spreadsheets/custom-spreadsheet.ts
  packages/desktop-client/src/components/reports/spreadsheets/filterEmptyRows.ts
  packages/desktop-client/src/components/reports/spreadsheets/grouped-spreadsheet.ts
  packages/desktop-client/src/components/reports/useReport.ts
  upcoming-release-notes/2505.md
Labels: 🔍 Ready for Review

#2528 [WIP] Fix custom reports cold-reload crash
  packages/desktop-client/src/components/reports/CategorySelector.tsx
  upcoming-release-notes/2528.md
Labels: 🚧 WIP

#2526 Add Area Icon
  packages/desktop-client/src/components/reports/ReportTopbar.jsx
  packages/desktop-client/src/icons/v1/ChartArea.tsx
  packages/desktop-client/src/icons/v1/index.ts
  upcoming-release-notes/2526.md
Labels: ✅ Approved

#2529 :chart_with_upwards_trend: adding extra console.log lines for bank-sync to help with troubleshooting
  packages/loot-core/src/server/accounts/sync.ts
  packages/loot-core/src/server/main.ts
  upcoming-release-notes/2529.md
Labels: ✅ Approved
