Repository actualbudget/actual, pull requests merged in 2024-06, with the labels that each got.

#2819 :bookmark: (24.6.0)
  packages/api/package.json
  packages/desktop-client/package.json
  packages/desktop-electron/package.json
  upcoming-release-notes/2362.md
  upcoming-release-notes/2507.md
  upcoming-release-notes/2559.md
  upcoming-release-notes/2568.md
  upcoming-release-notes/2622.md
  upcoming-release-notes/2631.md
  upcoming-release-notes/2643.md
  upcoming-release-notes/2648.md
  upcoming-release-notes/2652.md
  upcoming-release-notes/2664.md
  upcoming-release-notes/2672.md
  upcoming-release-notes/2676.md
  upcoming-release-notes/2677.md
  upcoming-release-notes/2683.md
  upcoming-release-notes/2696.md
  upcoming-release-notes/2698.md
  upcoming-release-notes/2700.md
  upcoming-release-notes/2706.md
  upcoming-release-notes/2707.md
  upcoming-release-notes/2712.md
  upcoming-release-notes/2713.md
  upcoming-release-notes/2714.md
  upcoming-release-notes/2715.md
  upcoming-release-notes/2716.md
  upcoming-release-notes/2719.md
  upcoming-release-notes/2724.md
  upcoming-release-notes/2725.md
  upcoming-release-notes/2726.md
  upcoming-release-notes/2727.md
  upcoming-release-notes/2728.md
  upcoming-release-notes/2729.md
  upcoming-release-notes/2730.md
  upcoming-release-notes/2733.md
  upcoming-release-notes/2738.md
  upcoming-release-notes/2745.md
  upcoming-release-notes/2746.md
  upcoming-release-notes/2750.md
  upcoming-release-notes/2753.md
  upcoming-release-notes/2754.md
  upcoming-release-notes/2762.md
  upcoming-release-notes/2763.md
  upcoming-release-notes/2765.md
  upcoming-release-notes/2766.md
  upcoming-release-notes/2768.md
  upcoming-release-notes/2769.md
  upcoming-release-notes/2773.md
  upcoming-release-notes/2774.md
  upcoming-release-notes/2775.md
  upcoming-release-notes/2777.md
  upcoming-release-notes/2778.md
  upcoming-release-notes/2786.md
  upcoming-release-notes/2788.md
  upcoming-release-notes/2795.md
  upcoming-release-notes/2797.md
  upcoming-release-notes/2803.md
  upcoming-release-notes/2809.md
Labels: ✅ Approved

#2771 ♻️ (tooltip) refactoring to react-aria (vol.6)
  packages/desktop-client/src/components/manager/BudgetList.jsx
  packages/desktop-client/src/components/modals/AccountMenuModal.tsx
  packages/desktop-client/src/components/modals/CategoryGroupMenuModal.tsx
  packages/desktop-client/src/components/modals/CategoryMenuModal.tsx
  packages/desktop-client/src/components/modals/EditRule.jsx
  packages/desktop-client/src/components/modals/GoCardlessExternalMsg.tsx
  packages/desktop-client/src/components/payees/ManagePayees.jsx
  packages/desktop-client/src/components/payees/PayeeMenu.tsx
  packages/desktop-client/src/components/schedules/SchedulesTable.tsx
  upcoming-release-notes/2771.md
Labels: ✅ Approved

#2796 Show account notes in tooltip on sidebar
  packages/desktop-client/src/components/sidebar/Account.tsx
  upcoming-release-notes/2796.md
Labels: ✅ Approved

#2789 Release 'Splits in rules' feature
  packages/desktop-client/e2e/rules.test.js
  packages/desktop-client/src/components/modals/EditRule.jsx
  packages/desktop-client/src/components/settings/Experimental.tsx
  packages/desktop-client/src/hooks/useFeatureFlag.ts
  packages/loot-core/src/server/accounts/rules.ts
  packages/loot-core/src/types/prefs.d.ts
  upcoming-release-notes/2789.md
Labels: ✅ Approved

#2799 Update regex for `looselyParseAmount` for 5-9 decimal places
  packages/loot-core/src/shared/util.test.ts
  packages/loot-core/src/shared/util.ts
  upcoming-release-notes/2799.md
Labels: ✅ Approved

#2821 [Mobile] Auto create 2 child transactions on split
  packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
  packages/loot-core/src/shared/transactions.ts
  upcoming-release-notes/2821.md
Labels: ✅ Approved

#2817 Fix nYnab imports with income on them
  packages/desktop-client/e2e/data/ynab5-demo-budget.json
  packages/desktop-client/e2e/onboarding.test.js
  packages/loot-core/src/server/importers/ynab5.ts
  upcoming-release-notes/2817.md
Labels: ✅ Approved

#2642 [Mobile] Budget table revamp
  packages/desktop-client/e2e/mobile.test.js
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-loads-the-budget-page-with-budgeted-amounts-1-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-loads-the-budget-page-with-budgeted-amounts-2-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-loads-the-budget-page-with-budgeted-amounts-3-chromium-linux.png
  packages/desktop-client/package.json
  packages/desktop-client/src/components/budget/BalanceWithCarryover.tsx
  packages/desktop-client/src/components/budget/report/ReportComponents.tsx
  packages/desktop-client/src/components/budget/rollover/RolloverComponents.tsx
  packages/desktop-client/src/components/common/Label.tsx
  packages/desktop-client/src/components/common/Modal.tsx
  packages/desktop-client/src/components/common/Text.tsx
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  packages/desktop-client/src/components/mobile/budget/ListItem.tsx
  packages/desktop-client/src/components/modals/EditRule.jsx
  packages/desktop-client/src/components/modals/ReportBalanceMenuModal.tsx
  packages/desktop-client/src/components/modals/ReportBudgetMenuModal.tsx
  packages/desktop-client/src/components/modals/RolloverBalanceMenuModal.tsx
  packages/desktop-client/src/components/modals/RolloverBudgetMenuModal.tsx
  packages/desktop-client/src/components/modals/ScheduledTransactionMenuModal.tsx
  packages/desktop-client/src/components/rules/RuleRow.tsx
  packages/desktop-client/src/style/styles.ts
  packages/desktop-client/src/style/themes/dark.ts
  packages/desktop-client/src/style/themes/development.ts
  packages/desktop-client/src/style/themes/light.ts
  packages/desktop-client/src/style/themes/midnight.ts
  upcoming-release-notes/2642.md
  yarn.lock
Labels: ✅ Approved

#2838 [WIP] Don't show account tooltips during VRT
  packages/desktop-client/src/components/sidebar/Account.tsx
  upcoming-release-notes/2838.md
Labels: 🚧 WIP

#2566 Use amount input on rules page instead of plain text field
  packages/desktop-client/src/components/modals/EditRule.jsx
  packages/desktop-client/src/components/spreadsheet/useFormat.ts
  packages/desktop-client/src/components/util/GenericInput.jsx
  packages/desktop-client/src/components/util/PercentInput.tsx
  upcoming-release-notes/2566.md
Labels: ✅ Approved

#2840 Spending Report: filter out offbudget items
  packages/desktop-client/src/components/reports/spreadsheets/spending-spreadsheet.ts
  upcoming-release-notes/2840.md
Labels: ✅ Approved

#2831 [Mobile] Add loading indicator on mobile transactions list
  packages/desktop-client/src/components/mobile/accounts/AccountTransactions.jsx
  packages/desktop-client/src/components/mobile/budget/CategoryTransactions.jsx
  packages/desktop-client/src/components/mobile/transactions/TransactionList.jsx
  packages/desktop-client/src/components/mobile/transactions/TransactionListWithBalances.jsx
  upcoming-release-notes/2831.md
Labels: 🔍 Ready for Review

#2837 [Mobile] Use AmountInput on mobile transfer and hold buffer modals
  packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
  packages/desktop-client/src/components/modals/HoldBufferModal.tsx
  packages/desktop-client/src/components/modals/TransferModal.tsx
  packages/desktop-client/src/components/util/AmountInput.tsx
  upcoming-release-notes/2837.md
Labels: ✅ Approved

#2825 Enable compress to avoid minified scripts from throwing SyntaxError in safari16
  packages/loot-core/webpack/webpack.browser.config.js
  upcoming-release-notes/2825.md
Labels: 🔍 Ready for Review

#2822 ♻️ (tooltip) refactoring to react-aria (vol.8)
  packages/desktop-client/src/components/budget/BudgetTable.jsx
  packages/desktop-client/src/components/budget/report/BalanceTooltip.tsx
  packages/desktop-client/src/components/budget/report/ReportComponents.tsx
  packages/desktop-client/src/components/budget/report/budgetsummary/BudgetSummary.tsx
  packages/desktop-client/src/components/budget/report/budgetsummary/Saved.tsx
  packages/desktop-client/src/components/budget/rollover/budgetsummary/BudgetSummary.tsx
  packages/desktop-client/src/components/budget/rollover/budgetsummary/TotalsList.tsx
  packages/desktop-client/src/components/tooltips.tsx
  upcoming-release-notes/2822.md
Labels: 🔍 Ready for Review

#2853 :bookmark: (api) 6.8.1: fix #2829
  packages/api/package.json
  upcoming-release-notes/2853.md
Labels: 🔍 Ready for Review

#2806 Added Year comparison feature.
  packages/desktop-client/src/components/reports/graphs/SpendingGraph.tsx
  packages/desktop-client/src/components/reports/reports/Spending.tsx
  packages/desktop-client/src/components/reports/reports/SpendingCard.tsx
  packages/desktop-client/src/components/reports/spreadsheets/spending-spreadsheet.ts
  packages/loot-core/src/types/models/reports.d.ts
  upcoming-release-notes/2806.md
Labels: ⚠️ Changes requested

#2812 Fix amounts over 1 million cutting off
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-1-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-2-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-3-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-4-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-5-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-6-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-creates-a-new-account-and-views-the-initial-balance-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-creates-a-new-account-and-views-the-initial-balance-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-creates-a-new-account-and-views-the-initial-balance-transaction-3-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-4-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-5-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-6-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-split-transaction-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-split-transaction-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-split-transaction-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-3-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-checks-the-page-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-checks-the-page-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-checks-the-page-visuals-3-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-split-test-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-split-test-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-split-test-transaction-3-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-test-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-test-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-test-transaction-3-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-category-7-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-category-8-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-category-9-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-date-7-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-date-8-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-date-9-chromium-linux.png
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  upcoming-release-notes/2812.md
Labels: 🔍 Ready for Review

#2850 Cover overbudgeted action + make balance movement menus only appear on relevant conditions
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/budget/rollover/BalanceMenu.tsx
  packages/desktop-client/src/components/budget/rollover/BalanceMovementMenu.tsx
  packages/desktop-client/src/components/budget/rollover/CoverMenu.tsx
  packages/desktop-client/src/components/budget/rollover/budgetsummary/ToBudget.tsx
  packages/desktop-client/src/components/budget/rollover/budgetsummary/ToBudgetMenu.tsx
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  packages/desktop-client/src/components/modals/CoverModal.tsx
  packages/desktop-client/src/components/modals/RolloverBudgetSummaryModal.tsx
  packages/desktop-client/src/components/modals/RolloverToBudgetMenuModal.tsx
  packages/loot-core/src/client/actions/queries.ts
  packages/loot-core/src/client/state-types/modals.d.ts
  packages/loot-core/src/server/budget/actions.ts
  packages/loot-core/src/server/budget/app.ts
  packages/loot-core/src/server/budget/types/handlers.d.ts
  upcoming-release-notes/2850.md
Labels: 🔍 Ready for Review

#2836 Handle Null Org Domain in SimpleFIN for bank_id
  packages/desktop-client/src/components/modals/CreateAccountModal.tsx
  packages/loot-core/src/server/main.ts
  upcoming-release-notes/2836.md
Labels: 🔍 Ready for Review

#2842 Changing the autocomplete search to accept text without accents to match options with accents
  packages/desktop-client/src/components/autocomplete/Autocomplete.tsx
  upcoming-release-notes/2842.md
Labels: 🔍 Ready for Review

#2826 ♻️ (tooltip) refactoring to react-aria (vol.9)
  packages/desktop-client/src/components/accounts/Header.jsx
  packages/desktop-client/src/components/accounts/Reconcile.jsx
  packages/desktop-client/src/components/common/HoverTarget.tsx
  packages/desktop-client/src/components/common/MenuTooltip.tsx
  packages/desktop-client/src/components/filters/FiltersMenu.jsx
  packages/desktop-client/src/components/table.tsx
  upcoming-release-notes/2826.md
Labels: 🚧 WIP

#2684 Custom Reports: Include current
  packages/desktop-client/src/components/reports/ReportOptions.ts
  packages/desktop-client/src/components/reports/ReportSidebar.tsx
  packages/desktop-client/src/components/reports/disabledList.ts
  packages/desktop-client/src/components/reports/getLiveRange.ts
  packages/desktop-client/src/components/reports/reportRanges.ts
  packages/desktop-client/src/components/reports/reports/CustomReport.tsx
  packages/desktop-client/src/components/reports/reports/GetCardData.tsx
  packages/loot-core/migrations/1716359441000_include_current.sql
  packages/loot-core/src/client/data-hooks/reports.ts
  packages/loot-core/src/server/aql/schema/index.ts
  packages/loot-core/src/server/reports/app.ts
  packages/loot-core/src/shared/months.ts
  packages/loot-core/src/types/models/reports.d.ts
  upcoming-release-notes/2684.md
Labels: 🔍 Ready for Review

#2848 Removed recursion in place for iterable solution to prevent stack overflow
  packages/desktop-client/src/components/settings/Experimental.tsx
  packages/desktop-client/src/hooks/useFeatureFlag.ts
  packages/loot-core/src/server/spreadsheet/graph-data-structure.ts
  packages/loot-core/src/types/prefs.d.ts
  upcoming-release-notes/2848.md
Labels: 🔍 Ready for Review

#2895 Trafico embedded action
  .github/workflows/trafico.yml
  upcoming-release-notes/2895.md
Labels: ✅ Approved

#2554 Unflag custom reports
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-and-cash-flow-reports-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-and-cash-flow-reports-2-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-and-cash-flow-reports-3-chromium-linux.png
  packages/desktop-client/src/components/reports/Overview.tsx
  packages/desktop-client/src/components/settings/Experimental.tsx
  packages/desktop-client/src/hooks/useFeatureFlag.ts
  packages/loot-core/src/types/prefs.d.ts
  upcoming-release-notes/2554.md
Labels: ✅ Approved

#2899 :speech_balloon: (bank-sync) update sync button label to improve discoverability
  packages/desktop-client/src/components/accounts/Header.jsx
  upcoming-release-notes/2899.md
Labels: 🔍 Ready for Review

#2867 Fix: column titles incorrect when selecting transactions and resizing window
  packages/desktop-client/src/components/table.tsx
  upcoming-release-notes/2867.md
Labels: 🔍 Ready for Review

#2670 Format transaction notes as clickable tags
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-category-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-category-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-category-3-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-category-7-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-category-8-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-category-9-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-date-7-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-date-8-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-date-9-chromium-linux.png
  packages/desktop-client/src/components/accounts/Account.jsx
  packages/desktop-client/src/components/accounts/Balance.jsx
  packages/desktop-client/src/components/accounts/Header.jsx
  packages/desktop-client/src/components/budget/index.tsx
  packages/desktop-client/src/components/filters/AppliedFilters.tsx
  packages/desktop-client/src/components/filters/ConditionsOpMenu.tsx
  packages/desktop-client/src/components/filters/FilterExpression.tsx
  packages/desktop-client/src/components/filters/FiltersMenu.jsx
  packages/desktop-client/src/components/filters/FiltersStack.tsx
  packages/desktop-client/src/components/filters/SavedFilterMenuButton.tsx
  packages/desktop-client/src/components/filters/updateFilterReducer.ts
  packages/desktop-client/src/components/modals/EditRule.jsx
  packages/desktop-client/src/components/reports/Header.jsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableRow.tsx
  packages/desktop-client/src/components/reports/reports/CashFlow.tsx
  packages/desktop-client/src/components/reports/reports/CustomReport.tsx
  packages/desktop-client/src/components/reports/reports/NetWorth.jsx
  packages/desktop-client/src/components/reports/reports/Spending.tsx
  packages/desktop-client/src/components/table.tsx
  packages/desktop-client/src/components/transactions/TransactionList.jsx
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  packages/desktop-client/src/hooks/useFilters.ts
  packages/desktop-client/src/style/themes/dark.ts
  packages/desktop-client/src/style/themes/development.ts
  packages/desktop-client/src/style/themes/light.ts
  packages/desktop-client/src/style/themes/midnight.ts
  packages/loot-core/src/platform/server/sqlite/index.d.ts
  packages/loot-core/src/platform/server/sqlite/index.web.ts
  packages/loot-core/src/server/accounts/rules.ts
  packages/loot-core/src/server/accounts/transaction-rules.ts
  packages/loot-core/src/server/aql/compiler.ts
  packages/loot-core/src/server/db/index.ts
  packages/loot-core/src/server/migrate/migrations.ts
  packages/loot-core/src/server/sheet.ts
  packages/loot-core/src/shared/rules.ts
  packages/loot-core/src/types/models/rule.d.ts
  upcoming-release-notes/2670.md
Labels: ✅ Approved

#2910 Revert "fix(#2562): Prevent transaction deduplication for imported transactions"
  packages/loot-core/src/server/accounts/sync.test.ts
  packages/loot-core/src/server/accounts/sync.ts
  upcoming-release-notes/2770.md
Labels: ✅ Approved

#2929 :electron: Fix regex filters on electron app
  packages/loot-core/src/platform/server/sqlite/index.electron.ts
  upcoming-release-notes/2929.md
Labels: 🔍 Ready for Review

#2871 Custom Reports: Adjust Net values
  packages/desktop-client/src/components/reports/ReportOptions.ts
  packages/desktop-client/src/components/reports/ReportSummary.tsx
  packages/desktop-client/src/components/reports/disabledList.ts
  packages/desktop-client/src/components/reports/graphs/AreaGraph.tsx
  packages/desktop-client/src/components/reports/graphs/BarGraph.tsx
  packages/desktop-client/src/components/reports/graphs/DonutGraph.tsx
  packages/desktop-client/src/components/reports/graphs/LineGraph.tsx
  packages/desktop-client/src/components/reports/graphs/StackedBarGraph.tsx
  packages/desktop-client/src/components/reports/graphs/showActivity.ts
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTable.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableHeader.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableList.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableRow.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableTotals.tsx
  packages/desktop-client/src/components/reports/reports/CustomReport.tsx
  packages/desktop-client/src/components/reports/spreadsheets/calculateLegend.ts
  packages/desktop-client/src/components/reports/spreadsheets/custom-spreadsheet.ts
  packages/desktop-client/src/components/reports/spreadsheets/filterEmptyRows.ts
  packages/desktop-client/src/components/reports/spreadsheets/grouped-spreadsheet.ts
  packages/desktop-client/src/components/reports/spreadsheets/recalculate.ts
  packages/loot-core/src/types/models/reports.d.ts
  upcoming-release-notes/2871.md
Labels: 🔍 Ready for Review

#2925 :electron: Fix "Export" function on desktop app
  packages/desktop-electron/index.js
  upcoming-release-notes/2925.md
Labels: ✅ Approved

#2941 Fix: Transaction table constantly resizing
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  upcoming-release-notes/2941.md
Labels: 🔍 Ready for Review

#2940 change the mobile budget balance colors to be the same as desktop
  packages/desktop-client/src/components/budget/BalanceWithCarryover.tsx
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  upcoming-release-notes/2940.md
Labels: ✅ Approved

#2805 Group and ungroup split transactions
  packages/desktop-client/e2e/rules.test.js
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-split-transaction-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-split-transaction-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-split-transaction-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-3-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-split-test-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-split-test-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-split-test-transaction-3-chromium-linux.png
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/accounts/Account.jsx
  packages/desktop-client/src/components/accounts/Header.jsx
  packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
  packages/desktop-client/src/components/modals/PayeeAutocompleteModal.tsx
  packages/desktop-client/src/components/schedules/ScheduleLink.tsx
  packages/desktop-client/src/components/transactions/SelectedTransactionsButton.jsx
  packages/desktop-client/src/components/transactions/TransactionList.jsx
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  packages/loot-core/src/client/state-types/modals.d.ts
  packages/loot-core/src/server/accounts/transactions.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/shared/transactions.ts
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/2805.md
Labels: ✅ Approved

#2772 [WIP] :bug: fix the app randomly navigating back (closing)
  packages/desktop-client/src/hooks/useNavigate.ts
  upcoming-release-notes/2772.md
Labels: 🚧 WIP
