Repository actualbudget/actual, pull requests merged in 2024-08, with the labels that each got.

#3169 Fix budget type toggle not working the first time
  packages/desktop-client/src/components/autocomplete/CategoryAutocomplete.tsx
  packages/desktop-client/src/components/budget/index.tsx
  packages/desktop-client/src/components/mobile/budget/index.tsx
  packages/desktop-client/src/components/settings/BudgetTypeSettings.tsx
  packages/desktop-client/src/components/settings/Experimental.tsx
  upcoming-release-notes/3169.md
Labels: :white_check_mark: Approved

#3161 :bug: (modals) allow content to be vertically scrollable
  packages/desktop-client/src/components/common/InputWithContent.tsx
  packages/desktop-client/src/components/common/Modal2.tsx
  upcoming-release-notes/3161.md
Labels: :white_check_mark: Approved

#3180 :recycle: (typescript) make category and rule types stricter
  packages/desktop-client/src/components/budget/rollover/CoverMenu.tsx
  packages/desktop-client/src/components/budget/rollover/TransferMenu.tsx
  packages/desktop-client/src/components/filters/AppliedFilters.tsx
  packages/desktop-client/src/components/filters/ConditionsOpMenu.tsx
  packages/desktop-client/src/components/filters/FilterExpression.tsx
  packages/desktop-client/src/components/filters/subfieldFromFilter.ts
  packages/desktop-client/src/components/filters/updateFilterReducer.ts
  packages/desktop-client/src/components/modals/CoverModal.tsx
  packages/desktop-client/src/components/modals/TransferModal.tsx
  packages/desktop-client/src/components/reports/ReportOptions.ts
  packages/desktop-client/src/hooks/useFilters.ts
  packages/loot-core/src/mocks/budget.ts
  packages/loot-core/src/types/models/category-group.d.ts
  packages/loot-core/src/types/models/category.d.ts
  packages/loot-core/src/types/models/reports.d.ts
  packages/loot-core/src/types/models/rule.d.ts
  upcoming-release-notes/3180.md
Labels: :white_check_mark: Approved

#3114 Disable typography linter in tests
  .eslintrc.js
  packages/loot-core/src/server/aql/views.test.ts
  upcoming-release-notes/3114.md
Labels: :white_check_mark: Approved

#3093 Support type-checking on spreadsheet fields (part 1)
  packages/desktop-client/src/components/sidebar/Account.tsx
  packages/desktop-client/src/components/spreadsheet/index.ts
  packages/desktop-client/src/components/table.tsx
  packages/loot-core/src/client/queries.ts
  upcoming-release-notes/3093.md
Labels: :white_check_mark: Approved

#3186 :white_check_mark: (vrt) improving stability - rules test
  packages/desktop-client/e2e/rules.test.js
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-3-chromium-linux.png
  upcoming-release-notes/3186.md
Labels: :white_check_mark: Approved

#2970 Fix false positives for duplicate filters error when saving a new filter
  packages/loot-core/src/server/filters/app.ts
  upcoming-release-notes/2970.md
Labels: :white_check_mark: Approved

#3122 Shorten hidden category names imported from YNAB4
  packages/loot-core/src/server/importers/ynab4.ts
  upcoming-release-notes/3122.md
Labels: :white_check_mark: Approved

#3181 Update monthly spending report option name
  packages/desktop-client/src/components/settings/Experimental.tsx
  upcoming-release-notes/3181.md
Labels: :white_check_mark: Approved

#3044 Fix a few number parsing issues
  packages/loot-core/src/server/accounts/parse-file.test.ts
  packages/loot-core/src/server/accounts/parse-file.ts
  packages/loot-core/src/shared/util.test.ts
  packages/loot-core/src/shared/util.ts
  upcoming-release-notes/3044.md
Labels: :white_check_mark: Approved

#3140 Add Reset Hold and Hold For Next Month api
  packages/api/methods.ts
  packages/loot-core/src/server/api.ts
  packages/loot-core/src/types/api-handlers.d.ts
  upcoming-release-notes/3140.md
Labels: :white_check_mark: Approved

#3166 Spending Report: UI Adjustments
  packages/desktop-client/src/components/reports/ModeButton.tsx
  packages/desktop-client/src/components/reports/graphs/SpendingGraph.tsx
  packages/desktop-client/src/components/reports/reports/Spending.tsx
  upcoming-release-notes/3166.md
Labels: :white_check_mark: Approved

#3178 :recycle: (reports) unify selectedCategories and conditions
  packages/desktop-client/src/components/reports/ReportSidebar.tsx
  packages/desktop-client/src/components/reports/reports/CustomReport.tsx
  packages/desktop-client/src/components/reports/reports/GetCardData.tsx
  packages/desktop-client/src/components/reports/reports/Spending.tsx
  packages/desktop-client/src/components/reports/reports/SpendingCard.tsx
  packages/desktop-client/src/components/reports/spreadsheets/custom-spreadsheet.ts
  packages/desktop-client/src/components/reports/spreadsheets/grouped-spreadsheet.ts
  packages/desktop-client/src/components/reports/spreadsheets/makeQuery.ts
  packages/desktop-client/src/components/reports/spreadsheets/spending-spreadsheet.ts
  packages/loot-core/migrations/1722717601000_reports_move_selected_categories.js
  packages/loot-core/src/client/data-hooks/reports.ts
  packages/loot-core/src/server/aql/schema/index.ts
  packages/loot-core/src/server/migrate/migrations.ts
  packages/loot-core/src/server/reports/app.ts
  packages/loot-core/src/shared/rules.ts
  packages/loot-core/src/types/models/reports.d.ts
  upcoming-release-notes/3178.md
Labels: :white_check_mark: Approved

#3183 Add unit tests for goal template types
  packages/loot-core/src/server/budget/goals/goalsAverage.test.ts
  packages/loot-core/src/server/budget/goals/goalsBy.test.ts
  packages/loot-core/src/server/budget/goals/goalsPercentage.test.ts
  packages/loot-core/src/server/budget/goals/goalsRemainder.test.ts
  packages/loot-core/src/server/budget/goals/goalsSchedule.test.ts
  packages/loot-core/src/server/budget/goals/goalsSimple.test.ts
  packages/loot-core/src/server/budget/goals/goalsSpend.test.ts
  packages/loot-core/src/server/budget/goals/goalsWeek.test.ts
  upcoming-release-notes/3183.md
Labels: :white_check_mark: Approved

#3018 Adds a tooltip to the transaction tables to show the imported payee
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  upcoming-release-notes/3018.md
Labels: :white_check_mark: Approved

#3206 Fix mobile status indicators cutting off.
  packages/desktop-client/src/components/mobile/accounts/AccountTransactions.jsx
  packages/desktop-client/src/components/mobile/accounts/Accounts.jsx
  upcoming-release-notes/3206.md
Labels: :white_check_mark: Approved

#2984 [React Aria Button] - Migrate sidebar, notifications, transactions, recurring schedule picker buttons
  packages/desktop-client/e2e/page-models/account-page.js
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-4-chromium-linux.png
  packages/desktop-client/src/components/FatalError.tsx
  packages/desktop-client/src/components/LoggedInUser.tsx
  packages/desktop-client/src/components/ManageRules.tsx
  packages/desktop-client/src/components/NotesButton.tsx
  packages/desktop-client/src/components/Notifications.tsx
  packages/desktop-client/src/components/ThemeSelector.tsx
  packages/desktop-client/src/components/Titlebar.tsx
  packages/desktop-client/src/components/UpdateNotification.tsx
  packages/desktop-client/src/components/accounts/Header.jsx
  packages/desktop-client/src/components/common/Button.tsx
  packages/desktop-client/src/components/common/Button2.tsx
  packages/desktop-client/src/components/common/MenuButton.tsx
  packages/desktop-client/src/components/reports/reports/ListCardsPopover.tsx
  packages/desktop-client/src/components/select/RecurringSchedulePicker.jsx
  packages/desktop-client/src/components/sidebar/Sidebar.tsx
  packages/desktop-client/src/components/sidebar/ToggleButton.tsx
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  upcoming-release-notes/2984.md
Labels: :white_check_mark: Approved

#3205 fix "unkown" typo in error message
  packages/loot-core/src/client/shared-listeners.ts
  upcoming-release-notes/3205.md
Labels: :white_check_mark: Approved

#3203 Identify Payee and Notes fields by name if they exist in CSV import
  packages/desktop-client/src/components/modals/ImportTransactions.jsx
  upcoming-release-notes/3203.md
Labels: :white_check_mark: Approved

#3200 :recycle: (reports) add 'showTooltip' prop to various graphs
  packages/desktop-client/src/components/reports/ChooseGraph.tsx
  packages/desktop-client/src/components/reports/graphs/AreaGraph.tsx
  packages/desktop-client/src/components/reports/graphs/BarGraph.tsx
  packages/desktop-client/src/components/reports/graphs/BarLineGraph.tsx
  packages/desktop-client/src/components/reports/graphs/LineGraph.tsx
  packages/desktop-client/src/components/reports/graphs/StackedBarGraph.tsx
  packages/desktop-client/src/components/reports/reports/GetCardData.tsx
  upcoming-release-notes/3200.md
Labels: :white_check_mark: Approved

#3209 Spending Report: Mobile UI
  packages/desktop-client/src/components/reports/Header.jsx
  packages/desktop-client/src/components/reports/reports/Spending.tsx
  upcoming-release-notes/3209.md
Labels: :white_check_mark: Approved

#3198 :recycle: (reports) improve useReports data fetching hook to return loading state
  packages/desktop-client/src/components/autocomplete/ReportAutocomplete.tsx
  packages/desktop-client/src/components/reports/Overview.tsx
  packages/desktop-client/src/components/reports/SaveReport.tsx
  packages/desktop-client/src/components/util/GenericInput.jsx
  packages/loot-core/src/client/data-hooks/reports.ts
  upcoming-release-notes/3198.md
Labels: :white_check_mark: Approved

#3095 Support type-checking on spreadsheet fields (part 2)
  packages/desktop-client/src/components/budget/rollover/BalanceMenu.tsx
  packages/desktop-client/src/components/budget/rollover/BalanceMovementMenu.tsx
  packages/desktop-client/src/components/budget/rollover/RolloverComponents.tsx
  packages/desktop-client/src/components/budget/rollover/budgetsummary/ToBudget.tsx
  packages/desktop-client/src/components/budget/rollover/budgetsummary/ToBudgetAmount.tsx
  packages/desktop-client/src/components/budget/rollover/budgetsummary/ToBudgetMenu.tsx
  packages/desktop-client/src/components/budget/rollover/budgetsummary/TotalsList.tsx
  packages/desktop-client/src/components/modals/HoldBufferModal.tsx
  packages/desktop-client/src/components/modals/RolloverBudgetMenuModal.tsx
  packages/desktop-client/src/components/modals/RolloverBudgetSummaryModal.tsx
  packages/desktop-client/src/components/spreadsheet/CellValue.tsx
  packages/desktop-client/src/components/spreadsheet/index.ts
  packages/desktop-client/src/components/table.tsx
  packages/loot-core/src/client/queries.ts
  upcoming-release-notes/3095.md
Labels: :white_check_mark: Approved

#3212 :electron: Fix gocardless "Linking account" integration
  packages/loot-core/src/platform/server/fetch/index.electron.ts
  upcoming-release-notes/3212.md
Labels: :white_check_mark: Approved

#3219 :electron: Making Electron server logs visible in devtools
  packages/desktop-electron/index.ts
  packages/loot-core/src/platform/exceptions/index.electron.ts
  upcoming-release-notes/3219.md
Labels: :white_check_mark: Approved

#3188 Filter by account when linking schedules
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/accounts/Header.jsx
  packages/desktop-client/src/components/modals/KeyboardShortcutModal.tsx
  packages/desktop-client/src/components/schedules/ScheduleLink.tsx
  packages/desktop-client/src/components/transactions/SelectedTransactionsButton.jsx
  upcoming-release-notes/3188.md
Labels: :white_check_mark: Approved

#2991 fix(#2562): Prevent transaction deduplication for imported transactions
  packages/loot-core/src/server/accounts/sync.test.ts
  packages/loot-core/src/server/accounts/sync.ts
  upcoming-release-notes/2991.md
Labels: :white_check_mark: Approved

#3111 Highlight current month in budgets.
  packages/desktop-client/src/components/budget/MonthPicker.tsx
  packages/desktop-client/src/components/budget/report/ReportComponents.tsx
  packages/desktop-client/src/components/budget/report/budgetsummary/BudgetSummary.tsx
  packages/desktop-client/src/components/budget/rollover/RolloverComponents.tsx
  packages/desktop-client/src/components/budget/rollover/budgetsummary/BudgetSummary.tsx
  packages/desktop-client/src/style/palette.ts
  packages/desktop-client/src/style/themes/dark.ts
  packages/desktop-client/src/style/themes/development.ts
  packages/desktop-client/src/style/themes/light.ts
  packages/desktop-client/src/style/themes/midnight.ts
  packages/loot-core/src/shared/months.ts
  upcoming-release-notes/3111.md
Labels: :white_check_mark: Approved

#3232 Fix reconcileTransactions Invokation To Use strictIdChecking
  packages/loot-core/src/server/main.ts
  upcoming-release-notes/3232.md
Labels: :white_check_mark: Approved

#3036 feat: introduce i18n framework
  package.json
  packages/desktop-client/i18next-parser.config.js
  packages/desktop-client/package.json
  packages/desktop-client/src/components/App.tsx
  packages/desktop-client/src/components/common/Menu.tsx
  packages/desktop-client/src/components/manager/ConfigServer.tsx
  packages/desktop-client/src/components/manager/WelcomeScreen.tsx
  packages/desktop-client/src/components/manager/subscribe/Bootstrap.tsx
  packages/desktop-client/src/components/schedules/ScheduleDetails.jsx
  packages/desktop-client/src/components/table.tsx
  packages/desktop-client/src/components/transactions/SelectedTransactionsButton.jsx
  packages/desktop-client/src/hooks/useSelected.tsx
  packages/desktop-client/src/i18n.ts
  packages/desktop-client/src/index.tsx
  packages/loot-core/package.json
  packages/loot-core/src/client/actions/budgets.ts
  packages/loot-core/src/client/actions/notifications.ts
  packages/loot-core/src/client/actions/queries.ts
  packages/loot-core/src/client/shared-listeners.ts
  packages/loot-core/src/client/update-notification.ts
  packages/loot-core/src/platform/client/fetch/index.browser.ts
  upcoming-release-notes/3036.md
  yarn.lock
Labels: :white_check_mark: Approved

#3237 Correct type for `to-budget` field
  packages/desktop-client/src/components/budget/rollover/budgetsummary/ToBudget.tsx
  packages/desktop-client/src/components/budget/rollover/budgetsummary/ToBudgetAmount.tsx
  tsconfig.json
  upcoming-release-notes/3237.md
Labels: :white_check_mark: Approved

#3241 Fix off-by-one error when placing category into 2nd-to-last place
  packages/desktop-client/src/components/budget/BudgetTable.jsx
  packages/desktop-client/src/components/budget/util.ts
  upcoming-release-notes/3241.md
Labels: :white_check_mark: Approved

#3236 :recycle: (prefs) initial type implementation for synced/local/metadata prefs
  packages/desktop-client/src/components/App.tsx
  packages/desktop-client/src/components/Titlebar.tsx
  packages/desktop-client/src/components/accounts/Account.jsx
  packages/desktop-client/src/components/autocomplete/CategoryAutocomplete.tsx
  packages/desktop-client/src/components/budget/index.tsx
  packages/desktop-client/src/components/budget/util.ts
  packages/desktop-client/src/components/manager/BudgetList.tsx
  packages/desktop-client/src/components/mobile/accounts/Account.jsx
  packages/desktop-client/src/components/mobile/accounts/AccountTransactions.jsx
  packages/desktop-client/src/components/mobile/accounts/Accounts.jsx
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  packages/desktop-client/src/components/mobile/budget/Category.tsx
  packages/desktop-client/src/components/mobile/budget/CategoryTransactions.jsx
  packages/desktop-client/src/components/mobile/budget/index.tsx
  packages/desktop-client/src/components/mobile/transactions/FocusableAmountInput.tsx
  packages/desktop-client/src/components/modals/BudgetListModal.tsx
  packages/desktop-client/src/components/modals/LoadBackup.jsx
  packages/desktop-client/src/components/reports/ReportSidebar.tsx
  packages/desktop-client/src/components/reports/getLiveRange.ts
  packages/desktop-client/src/components/reports/reportRanges.ts
  packages/desktop-client/src/components/reports/reports/CustomReport.tsx
  packages/desktop-client/src/components/reports/reports/CustomReportListCards.tsx
  packages/desktop-client/src/components/reports/reports/GetCardData.tsx
  packages/desktop-client/src/components/reports/spreadsheets/custom-spreadsheet.ts
  packages/desktop-client/src/components/select/DateSelect.tsx
  packages/desktop-client/src/components/settings/BudgetTypeSettings.tsx
  packages/desktop-client/src/components/settings/Encryption.tsx
  packages/desktop-client/src/components/settings/Experimental.tsx
  packages/desktop-client/src/components/settings/Export.tsx
  packages/desktop-client/src/components/settings/Format.tsx
  packages/desktop-client/src/components/settings/Reset.tsx
  packages/desktop-client/src/components/settings/index.tsx
  packages/desktop-client/src/components/sidebar/Sidebar.tsx
  packages/desktop-client/src/components/util/AmountInput.tsx
  packages/desktop-client/src/hooks/useMetadataPref.ts
  packages/desktop-client/src/hooks/useSyncedPref.ts
  packages/loot-core/src/client/queries.ts
  packages/loot-core/src/client/state-types/prefs.d.ts
  packages/loot-core/src/server/prefs.ts
  packages/loot-core/src/shared/months.ts
  packages/loot-core/src/types/prefs.d.ts
  upcoming-release-notes/3219.md
  upcoming-release-notes/3236.md
Labels: :white_check_mark: Approved

#3242 fix: i18n: Use 'en' as default language
  packages/desktop-client/src/i18n.ts
  upcoming-release-notes/3242.md
Labels: :white_check_mark: Approved

#2892 [Mobile] Long press transaction to reveal floating action bar with bulk actions
  packages/desktop-client/package.json
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/Notifications.tsx
  packages/desktop-client/src/components/accounts/Account.jsx
  packages/desktop-client/src/components/accounts/Header.jsx
  packages/desktop-client/src/components/mobile/FloatingActionBar.tsx
  packages/desktop-client/src/components/mobile/accounts/AccountTransactions.jsx
  packages/desktop-client/src/components/mobile/budget/CategoryTransactions.jsx
  packages/desktop-client/src/components/mobile/transactions/Transaction.jsx
  packages/desktop-client/src/components/mobile/transactions/TransactionList.jsx
  packages/desktop-client/src/components/mobile/transactions/TransactionListWithBalances.jsx
  packages/desktop-client/src/components/modals/ConfirmTransactionDelete.tsx
  packages/desktop-client/src/components/payees/ManagePayees.jsx
  packages/desktop-client/src/components/payees/PayeeTableRow.tsx
  packages/desktop-client/src/components/rules/RuleRow.tsx
  packages/desktop-client/src/components/rules/RulesHeader.tsx
  packages/desktop-client/src/components/schedules/DiscoverSchedules.tsx
  packages/desktop-client/src/components/schedules/ScheduleLink.tsx
  packages/desktop-client/src/components/transactions/SelectedTransactionsButton.jsx
  packages/desktop-client/src/components/transactions/SimpleTransactionsTable.jsx
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  packages/desktop-client/src/hooks/useSelected.tsx
  packages/desktop-client/src/hooks/useTransactionBatchActions.ts
  packages/desktop-client/src/hooks/useUndo.ts
  packages/desktop-client/src/style/themes/dark.ts
  packages/desktop-client/src/style/themes/development.ts
  packages/desktop-client/src/style/themes/light.ts
  packages/desktop-client/src/style/themes/midnight.ts
  packages/loot-core/src/client/actions/notifications.ts
  packages/loot-core/src/client/constants.ts
  packages/loot-core/src/client/reducers/notifications.ts
  packages/loot-core/src/client/state-types/modals.d.ts
  packages/loot-core/src/client/state-types/notifications.d.ts
  packages/loot-core/src/mocks/budget.ts
  packages/loot-core/src/server/accounts/transactions.ts
  packages/loot-core/src/shared/transactions.test.ts
  packages/loot-core/src/shared/transactions.ts
  packages/loot-core/src/shared/util.ts
  packages/loot-core/src/types/models/category.d.ts
  packages/loot-core/src/types/models/payee.d.ts
  packages/loot-core/src/types/models/transaction.d.ts
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/2892.md
  yarn.lock
Labels: :white_check_mark: Approved

#3159 [React Aria Button] Reports page buttons
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-and-cash-flow-reports-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-and-cash-flow-reports-2-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-and-cash-flow-reports-3-chromium-linux.png
  packages/desktop-client/src/components/reports/CategorySelector.tsx
  packages/desktop-client/src/components/reports/GraphButton.tsx
  packages/desktop-client/src/components/reports/Header.jsx
  packages/desktop-client/src/components/reports/ModeButton.tsx
  packages/desktop-client/src/components/reports/Overview.tsx
  packages/desktop-client/src/components/reports/ReportSidebar.tsx
  packages/desktop-client/src/components/reports/SaveReport.tsx
  packages/desktop-client/src/components/reports/SaveReportChoose.tsx
  packages/desktop-client/src/components/reports/SaveReportDelete.tsx
  packages/desktop-client/src/components/reports/SaveReportName.tsx
  packages/desktop-client/src/components/reports/reports/CashFlow.tsx
  packages/desktop-client/src/components/reports/reports/Spending.tsx
  upcoming-release-notes/3159.md
Labels: :white_check_mark: Approved

#3220 :electron: Fix "Unknown problem opening <local actual file>" on Electron
  bin/package-electron
  packages/desktop-electron/beforePackHook.ts
  packages/desktop-electron/package.json
  upcoming-release-notes/3220.md
Labels: :white_check_mark: Approved

#3239 Fix transfer category in temporary transactions
  packages/desktop-client/e2e/page-models/account-page.js
  packages/desktop-client/e2e/transactions.test.js
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-transfer-test-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-transfer-test-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-transfer-test-transaction-3-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-transfer-test-transaction-4-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-transfer-test-transaction-5-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-transfer-test-transaction-6-chromium-linux.png
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  upcoming-release-notes/3239.md
Labels: :white_check_mark: Approved

#3221 Refactor template logic: Part 1 - Extract and refactor the note handling logic
  packages/loot-core/src/server/budget/goaltemplates.ts
  packages/loot-core/src/server/budget/statements.ts
  packages/loot-core/src/server/budget/template-notes.test.ts
  packages/loot-core/src/server/budget/template-notes.ts
  packages/loot-core/src/server/budget/types/templates.d.ts
  packages/loot-core/src/server/db/types.d.ts
  upcoming-release-notes/3221.md
Labels: :mag: Ready for review

#3251 3211: Fix broken transaction import on new accounts
  packages/desktop-client/src/components/modals/ImportTransactions.jsx
  upcoming-release-notes/3251.md
Labels: :mag: Ready for review

#3250 :electron: Fix export on mac
  packages/loot-core/src/platform/server/sqlite/index.electron.ts
  upcoming-release-notes/3250.md
Labels: :mag: Ready for review

#3258 fix(mobile): show category for on-to-off-budget transfers
  packages/desktop-client/src/components/mobile/transactions/Transaction.jsx
  upcoming-release-notes/3258.md
Labels: :mag: Ready for review

#3238 Remove some `any` types from the API
  packages/api/methods.test.ts
  packages/api/methods.ts
  packages/loot-core/src/server/accounts/transaction-rules.test.ts
  packages/loot-core/src/server/accounts/transaction-rules.ts
  packages/loot-core/src/server/api.ts
  packages/loot-core/src/server/rules/app.ts
  packages/loot-core/src/server/rules/types/handlers.ts
  packages/loot-core/src/types/api-handlers.d.ts
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/3238.md
Labels: :white_check_mark: Approved

#3246 Allow escaping tags with double ##.
  packages/desktop-client/src/components/transactions/TransactionList.jsx
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  packages/loot-core/src/server/accounts/sync.ts
  upcoming-release-notes/3246.md
Labels: :mag: Ready for review

#3257 Update ModeButton.tsx
  packages/desktop-client/src/components/reports/ModeButton.tsx
  upcoming-release-notes/3257.md
Labels: :white_check_mark: Approved

#3234 Added configuration to CSV importer that allows to skip lines
  packages/desktop-client/src/components/modals/ImportTransactions.jsx
  packages/loot-core/src/server/accounts/parse-file.ts
  packages/loot-core/src/types/prefs.d.ts
  upcoming-release-notes/3234.md
Labels: :white_check_mark: Approved

#3097 Support type-checking on spreadsheet fields (part 3—last part)
  packages/desktop-client/src/components/autocomplete/CategoryAutocomplete.tsx
  packages/desktop-client/src/components/budget/BalanceWithCarryover.tsx
  packages/desktop-client/src/components/budget/report/BalanceMenu.tsx
  packages/desktop-client/src/components/budget/report/ReportComponents.tsx
  packages/desktop-client/src/components/budget/report/budgetsummary/BudgetTotal.tsx
  packages/desktop-client/src/components/budget/report/budgetsummary/ExpenseProgress.tsx
  packages/desktop-client/src/components/budget/report/budgetsummary/Saved.tsx
  packages/desktop-client/src/components/budget/rollover/budgetsummary/ToBudgetMenu.tsx
  packages/desktop-client/src/components/modals/HoldBufferModal.tsx
  packages/desktop-client/src/components/modals/ReportBudgetMenuModal.tsx
  packages/desktop-client/src/components/modals/RolloverBudgetSummaryModal.tsx
  packages/desktop-client/src/components/spreadsheet/CellValue.tsx
  packages/desktop-client/src/components/spreadsheet/index.ts
  packages/desktop-client/src/components/spreadsheet/useSheetName.ts
  packages/desktop-client/src/components/spreadsheet/useSheetValue.ts
  packages/desktop-client/src/components/table.tsx
  packages/desktop-client/src/components/transactions/TransactionsTable.test.jsx
  packages/loot-core/src/client/queries.ts
  upcoming-release-notes/3097.md
Labels: :white_check_mark: Approved

#2974 Automatically focus inputs, or the primary button, in modals.
  packages/desktop-client/src/components/accounts/Account.jsx
  packages/desktop-client/src/components/accounts/AccountSyncCheck.jsx
  packages/desktop-client/src/components/accounts/Reconcile.jsx
  packages/desktop-client/src/components/manager/ImportActual.tsx
  packages/desktop-client/src/components/manager/ImportYNAB4.tsx
  packages/desktop-client/src/components/manager/ImportYNAB5.tsx
  packages/desktop-client/src/components/manager/WelcomeScreen.tsx
  packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
  packages/desktop-client/src/components/modals/CloseAccountModal.tsx
  packages/desktop-client/src/components/modals/ConfirmCategoryDelete.tsx
  packages/desktop-client/src/components/modals/ConfirmTransactionDelete.tsx
  packages/desktop-client/src/components/modals/ConfirmTransactionEdit.tsx
  packages/desktop-client/src/components/modals/ConfirmUnlinkAccount.tsx
  packages/desktop-client/src/components/modals/CreateAccountModal.tsx
  packages/desktop-client/src/components/modals/GoCardlessExternalMsg.tsx
  packages/desktop-client/src/components/modals/GoCardlessInitialise.tsx
  packages/desktop-client/src/components/modals/ImportTransactions.jsx
  packages/desktop-client/src/components/modals/MergeUnusedPayees.jsx
  packages/desktop-client/src/components/modals/SimpleFinInitialise.tsx
  packages/desktop-client/src/components/reports/SaveReportDelete.tsx
  packages/desktop-client/src/components/schedules/PostsOfflineNotification.jsx
  packages/desktop-client/src/components/schedules/ScheduleDetails.jsx
  packages/desktop-client/src/components/schedules/ScheduleLink.tsx
  packages/desktop-client/src/components/select/RecurringSchedulePicker.jsx
  upcoming-release-notes/2974.md
Labels: :white_check_mark: Approved

#3215 Add rule actions to prepend/append to transaction notes.
  packages/desktop-client/e2e/page-models/rules-page.js
  packages/desktop-client/e2e/rules.test.js
  packages/desktop-client/src/components/ManageRules.tsx
  packages/desktop-client/src/components/modals/EditRule.jsx
  packages/desktop-client/src/components/rules/ActionExpression.tsx
  packages/loot-core/src/server/accounts/rules.ts
  packages/loot-core/src/server/accounts/transaction-rules.ts
  packages/loot-core/src/server/rules/app.ts
  packages/loot-core/src/shared/rules.ts
  packages/loot-core/src/types/models/rule.d.ts
  upcoming-release-notes/3215.md
Labels: :white_check_mark: Approved

#3115 hide target category from cover overspending list
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/budget/rollover/BalanceMovementMenu.tsx
  packages/desktop-client/src/components/budget/rollover/CoverMenu.tsx
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  packages/desktop-client/src/components/modals/CoverModal.tsx
  upcoming-release-notes/3115.md
Labels: :white_check_mark: Approved

#3270 Translation: desktop-client/components/filters
  packages/desktop-client/src/components/filters/FilterExpression.tsx
  packages/desktop-client/src/components/filters/FilterMenu.tsx
  packages/desktop-client/src/components/filters/FiltersButton.tsx
  packages/desktop-client/src/components/filters/FiltersMenu.jsx
  packages/desktop-client/src/components/filters/NameFilter.tsx
  packages/desktop-client/src/components/filters/SavedFilterMenuButton.tsx
  upcoming-release-notes/3270.md
Labels: :white_check_mark: Approved

#3271 feat: [localization] Update README to mention weblate
  README.md
  upcoming-release-notes/3271.md
Labels: :white_check_mark: Approved

#3275 Translation: desktop-client/components/autocomplete
  packages/desktop-client/src/components/autocomplete/AccountAutocomplete.tsx
  packages/desktop-client/src/components/autocomplete/CategoryAutocomplete.tsx
  packages/desktop-client/src/components/autocomplete/FilterList.tsx
  packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.tsx
  packages/desktop-client/src/components/autocomplete/ReportList.tsx
  upcoming-release-notes/3275.md
Labels: :white_check_mark: Approved

#3231 ✨ customizable reports homepage - drag-able and resizable widgets
  packages/desktop-client/e2e/page-models/reports-page.js
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-and-cash-flow-reports-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-and-cash-flow-reports-2-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-and-cash-flow-reports-3-chromium-linux.png
  packages/desktop-client/package.json
  packages/desktop-client/src/components/common/Input.tsx
  packages/desktop-client/src/components/common/Menu.tsx
  packages/desktop-client/src/components/reports/ChooseGraph.tsx
  packages/desktop-client/src/components/reports/Overview.tsx
  packages/desktop-client/src/components/reports/ReportCard.tsx
  packages/desktop-client/src/components/reports/SaveReport.tsx
  packages/desktop-client/src/components/reports/constants.ts
  packages/desktop-client/src/components/reports/graphs/BarGraph.tsx
  packages/desktop-client/src/components/reports/graphs/DonutGraph.tsx
  packages/desktop-client/src/components/reports/graphs/LineGraph.tsx
  packages/desktop-client/src/components/reports/graphs/NetWorthGraph.tsx
  packages/desktop-client/src/components/reports/graphs/StackedBarGraph.tsx
  packages/desktop-client/src/components/reports/overview.scss
  packages/desktop-client/src/components/reports/reports/CashFlowCard.jsx
  packages/desktop-client/src/components/reports/reports/CustomReport.tsx
  packages/desktop-client/src/components/reports/reports/CustomReportListCards.tsx
  packages/desktop-client/src/components/reports/reports/ListCardsMenu.tsx
  packages/desktop-client/src/components/reports/reports/ListCardsPopover.tsx
  packages/desktop-client/src/components/reports/reports/MissingReportCard.tsx
  packages/desktop-client/src/components/reports/reports/NetWorth.jsx
  packages/desktop-client/src/components/reports/reports/NetWorthCard.jsx
  packages/desktop-client/src/components/reports/reports/SpendingCard.tsx
  packages/desktop-client/src/components/settings/Experimental.tsx
  packages/desktop-client/src/hooks/useFeatureFlag.ts
  packages/desktop-client/src/hooks/useIsInViewport.ts
  packages/loot-core/migrations/1722804019000_create_dashboard_table.js
  packages/loot-core/src/client/data-hooks/dashboard.ts
  packages/loot-core/src/client/reports.ts
  packages/loot-core/src/server/aql/schema/index.ts
  packages/loot-core/src/server/dashboard/app.ts
  packages/loot-core/src/server/dashboard/types/handlers.d.ts
  packages/loot-core/src/server/db/index.ts
  packages/loot-core/src/server/errors.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/server/migrate/migrations.ts
  packages/loot-core/src/server/models.ts
  packages/loot-core/src/server/reports/app.ts
  packages/loot-core/src/shared/dashboard.ts
  packages/loot-core/src/types/handlers.d.ts
  packages/loot-core/src/types/models/dashboard.d.ts
  packages/loot-core/src/types/models/index.d.ts
  packages/loot-core/src/types/prefs.d.ts
  packages/loot-core/src/types/util.d.ts
  packages/loot-core/typings/window.d.ts
  upcoming-release-notes/3044.md
  upcoming-release-notes/3140.md
  upcoming-release-notes/3183.md
  upcoming-release-notes/3220.md
  upcoming-release-notes/3221.md
  upcoming-release-notes/3231.md
  yarn.lock
Labels: :white_check_mark: Approved

#3280 Translation: desktop-client/components/budget/report
  packages/desktop-client/src/components/budget/report/BalanceMenu.tsx
  packages/desktop-client/src/components/budget/report/BudgetMenu.tsx
  packages/desktop-client/src/components/budget/report/ReportComponents.tsx
  packages/desktop-client/src/components/budget/report/budgetsummary/BudgetMonthMenu.tsx
  packages/desktop-client/src/components/budget/report/budgetsummary/BudgetSummary.tsx
  packages/desktop-client/src/components/budget/report/budgetsummary/BudgetTotal.tsx
  packages/desktop-client/src/components/budget/report/budgetsummary/ExpenseTotal.tsx
  packages/desktop-client/src/components/budget/report/budgetsummary/IncomeTotal.tsx
  packages/desktop-client/src/components/budget/report/budgetsummary/Saved.tsx
  upcoming-release-notes/3280.md
Labels: :white_check_mark: Approved

#2923 Display splits in previews
  packages/desktop-client/src/components/accounts/Account.jsx
  packages/desktop-client/src/components/mobile/transactions/Transaction.jsx
  packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
  packages/desktop-client/src/components/mobile/transactions/TransactionList.jsx
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  packages/desktop-client/src/hooks/usePreviewTransactions.ts
  packages/desktop-client/src/hooks/useSplitsExpanded.jsx
  upcoming-release-notes/2923.md
Labels: :white_check_mark: Approved

#3283 :sparkles: adding feedback links besides the feature flags
  packages/desktop-client/src/components/settings/Experimental.tsx
  upcoming-release-notes/3283.md
Labels: :white_check_mark: Approved

#3285 typescript: migrate cards from jsx to tsx
  packages/desktop-client/src/components/reports/reports/CashFlowCard.tsx
  packages/desktop-client/src/components/reports/reports/NetWorthCard.tsx
  packages/desktop-client/src/components/reports/reports/SpendingCard.tsx
  packages/desktop-client/src/components/reports/spreadsheets/cash-flow-spreadsheet.tsx
  packages/desktop-client/src/components/reports/spreadsheets/net-worth-spreadsheet.ts
  packages/desktop-client/src/components/reports/util.ts
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/3285.md
Labels: :white_check_mark: Approved

#3295 Fix wrong month on spending card
  packages/desktop-client/src/components/reports/reports/SpendingCard.tsx
  upcoming-release-notes/3295.md
Labels: :white_check_mark: Approved

#3289 :arrow_up: upgrade typescript, eslint, prettier
  .eslintrc.js
  package.json
  packages/api/package.json
  packages/crdt/package.json
  packages/crdt/src/crdt/merkle.test.ts
  packages/crdt/src/crdt/merkle.ts
  packages/crdt/src/crdt/timestamp.test.ts
  packages/crdt/src/crdt/timestamp.ts
  packages/desktop-client/src/components/accounts/Account.jsx
  packages/desktop-client/src/components/budget/rollover/RolloverComponents.tsx
  packages/desktop-client/src/components/manager/BudgetList.tsx
  packages/desktop-client/src/components/reports/graphs/AreaGraph.tsx
  packages/desktop-client/src/components/reports/graphs/BarGraph.tsx
  packages/desktop-client/src/components/reports/graphs/BarLineGraph.tsx
  packages/desktop-client/src/components/reports/graphs/LineGraph.tsx
  packages/desktop-client/src/components/reports/graphs/NetWorthGraph.tsx
  packages/desktop-client/src/components/reports/graphs/SpendingGraph.tsx
  packages/desktop-client/src/components/reports/graphs/StackedBarGraph.tsx
  packages/desktop-client/src/components/reports/reports/CustomReport.tsx
  packages/desktop-client/src/hooks/useMergedRefs.ts
  packages/desktop-client/src/polyfills.ts
  packages/desktop-electron/package.json
  packages/eslint-plugin-actual/package.json
  packages/loot-core/package.json
  packages/loot-core/src/client/state-types/index.d.ts
  packages/loot-core/src/server/accounts/rules.ts
  packages/loot-core/src/server/budget/goals/goalsSchedule.ts
  packages/loot-core/src/server/schedules/app.ts
  packages/loot-core/src/server/schedules/find-schedules.ts
  upcoming-release-notes/3289.md
  yarn.lock
Labels: :white_check_mark: Approved

#3284 :sparkles: (dashboards) ability to rename all widgets
  packages/desktop-client/src/components/reports/Overview.tsx
  packages/desktop-client/src/components/reports/ReportCardName.tsx
  packages/desktop-client/src/components/reports/reports/CashFlowCard.tsx
  packages/desktop-client/src/components/reports/reports/CustomReportListCards.tsx
  packages/desktop-client/src/components/reports/reports/NetWorthCard.tsx
  packages/desktop-client/src/components/reports/reports/SpendingCard.tsx
  packages/loot-core/src/server/dashboard/app.ts
  packages/loot-core/src/types/models/dashboard.d.ts
  upcoming-release-notes/3284.md
Labels: :white_check_mark: Approved

#3299 Translation: desktop-client/components/reports/graphs
  packages/desktop-client/src/components/reports/graphs/AreaGraph.tsx
  packages/desktop-client/src/components/reports/graphs/BarGraph.tsx
  packages/desktop-client/src/components/reports/graphs/BarLineGraph.tsx
  packages/desktop-client/src/components/reports/graphs/CashFlowGraph.tsx
  packages/desktop-client/src/components/reports/graphs/LineGraph.tsx
  packages/desktop-client/src/components/reports/graphs/NetWorthGraph.tsx
  packages/desktop-client/src/components/reports/graphs/SpendingGraph.tsx
  packages/desktop-client/src/components/reports/graphs/StackedBarGraph.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableHeader.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableTotals.tsx
  upcoming-release-notes/3299.md
Labels: :white_check_mark: Approved

#3302 Translation: desktop-client/components/sidebar
  packages/desktop-client/src/components/sidebar/Accounts.tsx
  packages/desktop-client/src/components/sidebar/Sidebar.tsx
  packages/desktop-client/src/components/sidebar/ToggleButton.tsx
  packages/desktop-client/src/components/sidebar/Tools.tsx
  upcoming-release-notes/3302.md
Labels: :white_check_mark: Approved

#3287 Apply regular expression conditions to imported transactions.
  packages/loot-core/src/server/accounts/rules.test.ts
  packages/loot-core/src/server/accounts/rules.ts
  upcoming-release-notes/3287.md
Labels: :white_check_mark: Approved

#3300 :electron: Notarize the mac desktop app
  .github/workflows/electron-master.yml
  packages/desktop-electron/package.json
  upcoming-release-notes/3300.md
  yarn.lock
Labels: :white_check_mark: Approved

#3290 "has tags" filter
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-category-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-category-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-category-3-chromium-linux.png
  packages/desktop-client/src/components/filters/FilterExpression.tsx
  packages/desktop-client/src/components/filters/FiltersMenu.jsx
  packages/desktop-client/src/components/filters/updateFilterReducer.ts
  packages/desktop-client/src/components/modals/EditRule.jsx
  packages/desktop-client/src/components/reports/reports/CustomReport.tsx
  packages/desktop-client/src/components/transactions/TransactionList.jsx
  packages/loot-core/src/server/accounts/rules.ts
  packages/loot-core/src/server/accounts/transaction-rules.ts
  packages/loot-core/src/shared/rules.ts
  packages/loot-core/src/types/models/rule.d.ts
  upcoming-release-notes/3290.md
Labels: :white_check_mark: Approved

#3278 Filter fix when alternating all <-> any
  packages/desktop-client/src/components/accounts/Account.jsx
  packages/desktop-client/src/components/filters/FiltersStack.tsx
  packages/desktop-client/src/components/modals/EditRule.jsx
  upcoming-release-notes/3278.md
Labels: :white_check_mark: Approved

#3279 🧹 optimise GoCardless bank sync to use fewer api calls
  packages/loot-core/src/server/accounts/sync.ts
  upcoming-release-notes/3279.md
Labels: :white_check_mark: Approved

#3323 :bug: (dashboards) add back spending report if dashboards feature is not enabled
  packages/desktop-client/src/components/reports/Overview.tsx
  upcoming-release-notes/3323.md
Labels: :white_check_mark: Approved

#3308 :electron: Desktop app to work with self signed certificates
  packages/desktop-client/src/components/manager/ConfigServer.tsx
  packages/loot-core/src/platform/server/fetch/index.electron.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/types/prefs.d.ts
  packages/loot-core/webpack/webpack.browser.config.js
  upcoming-release-notes/3308.md
Labels: :white_check_mark: Approved

#3318 Fix suggested payee issues #3317 #3316
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  packages/loot-core/src/server/db/index.ts
  upcoming-release-notes/3318.md
Labels: :white_check_mark: Approved

#3333 [WIP] fix toggleSpentColumn being called on every render
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  upcoming-release-notes/3333.md
Labels: :construction: WIP
