Repository actualbudget/actual, pull requests merged in 2024-02, with the labels that each got.

#2308 :bug: (goCardless) patch incomplete migration
  packages/desktop-client/src/components/accounts/Header.jsx
  packages/loot-core/migrations/1704572023730_add_account_sync_source.sql
  packages/loot-core/migrations/1704572023731_add_missing_goCardless_sync_source.sql
  upcoming-release-notes/2308.md
Labels: ✅ Approved

#2302 Custom Reports - split out hidden categories from offbudget
  packages/desktop-client/src/components/reports/CategorySelector.tsx
  packages/desktop-client/src/components/reports/ReportOptions.ts
  packages/desktop-client/src/components/reports/ReportSidebar.jsx
  packages/desktop-client/src/components/reports/reports/CategorySpending.jsx
  packages/desktop-client/src/components/reports/reports/CustomReport.jsx
  packages/desktop-client/src/components/reports/reports/CustomReportCard.jsx
  packages/desktop-client/src/components/reports/spreadsheets/custom-spreadsheet.ts
  packages/desktop-client/src/components/reports/spreadsheets/filterEmptyRows.ts
  packages/desktop-client/src/components/reports/spreadsheets/filterHiddenItems.ts
  packages/desktop-client/src/components/reports/spreadsheets/grouped-spreadsheet.ts
  packages/desktop-client/src/components/reports/spreadsheets/makeQuery.ts
  packages/desktop-client/src/components/reports/spreadsheets/recalculate.ts
  packages/loot-core/src/types/models/reports.d.ts
  upcoming-release-notes/2302.md
Labels: ✅ Approved

#2313 fix budget header collapsed colors
  packages/desktop-client/src/components/budget/rollover/budgetsummary/BudgetSummary.tsx
  upcoming-release-notes/2313.md
Labels: ✅ Approved

#2231 Convert FiltersMenu to Typescript (part 1)
  packages/desktop-client/src/components/filters/AppliedFilters.tsx
  packages/desktop-client/src/components/filters/CompactFiltersButton.tsx
  packages/desktop-client/src/components/filters/FilterExpression.tsx
  packages/desktop-client/src/components/filters/FiltersButton.tsx
  packages/desktop-client/src/components/filters/FiltersMenu.jsx
  packages/desktop-client/src/components/filters/OpButton.tsx
  packages/desktop-client/src/components/filters/SavedFilters.jsx
  packages/desktop-client/src/components/filters/subfieldFromFilter.ts
  packages/desktop-client/src/components/filters/subfieldToOptions.ts
  packages/desktop-client/src/components/filters/updateFilterReducer.ts
  packages/desktop-client/src/components/reports/Header.jsx
  packages/desktop-client/src/components/reports/reports/CustomReport.jsx
  packages/loot-core/src/types/models/rule.d.ts
  upcoming-release-notes/2231.md
Labels: ✅ Approved

#2262 feat: Don't allow duplicate cat-groups in budget
  packages/desktop-client/src/components/budget/index.tsx
  packages/loot-core/src/server/db/index.ts
  upcoming-release-notes/2262.md
Labels: ✅ Approved

#2121 Change month picker hover background color
  packages/desktop-client/src/components/budget/MonthPicker.tsx
  upcoming-release-notes/2121.md
Labels: ✅ Approved

#2319 :wrench: upgrade deprecated github actions
  .github/actions/setup/action.yml
  .github/workflows/build.yml
  .github/workflows/check.yml
  .github/workflows/codeql.yml
  .github/workflows/e2e-test.yml
  .github/workflows/electron-master.yml
  .github/workflows/electron-pr.yml
  .github/workflows/issues-feature-implemented.yml
  .github/workflows/release-notes.yml
  .github/workflows/size-compare.yml
  upcoming-release-notes/2319.md
Labels: ✅ Approved

#2316 [Maintenance] Pass HTTPS flag to dev container to enable HTTPS
  docker-compose.yml
  packages/desktop-client/README.md
  upcoming-release-notes/2316.md
Labels: ✅ Approved

#2123 Bugfix: Add Primary Button hover background colors for light and dark theme #1971
  packages/desktop-client/src/style/themes/dark.ts
  packages/desktop-client/src/style/themes/light.ts
  upcoming-release-notes/2123.md
Labels: ✅ Approved

#2317 [Bugfix] Dark Theme variable name misspelled
  packages/desktop-client/src/style/themes/dark.ts
  upcoming-release-notes/2317.md
Labels: ✅ Approved

#2304 Fix docker start browser error
  bin/docker-start
  upcoming-release-notes/2304.md
Labels: ✅ Approved

#2298 [Maintenance] Remove modals.d.ts
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/manager/DeleteFile.tsx
  packages/desktop-client/src/components/manager/Import.tsx
  packages/desktop-client/src/components/modals/CategoryGroupMenu.tsx
  packages/desktop-client/src/components/modals/CategoryMenu.tsx
  packages/desktop-client/src/components/modals/CloseAccount.tsx
  packages/desktop-client/src/components/modals/ConfirmCategoryDelete.tsx
  packages/desktop-client/src/components/modals/ConfirmTransactionEdit.tsx
  packages/desktop-client/src/components/modals/CreateAccount.tsx
  packages/desktop-client/src/components/modals/CreateEncryptionKey.tsx
  packages/desktop-client/src/components/modals/CreateLocalAccount.tsx
  packages/desktop-client/src/components/modals/FixEncryptionKey.tsx
  packages/desktop-client/src/components/modals/GoCardlessExternalMsg.tsx
  packages/desktop-client/src/components/modals/ManageRulesModal.tsx
  packages/desktop-client/src/components/modals/Notes.tsx
  packages/desktop-client/src/components/modals/PlaidExternalMsg.tsx
  packages/desktop-client/src/components/modals/ReportBudgetSummary.tsx
  packages/desktop-client/src/components/modals/RolloverBudgetSummary.tsx
  packages/desktop-client/src/components/modals/SingleInput.tsx
  packages/desktop-client/src/components/modals/SwitchBudgetType.tsx
  packages/desktop-client/src/components/schedules/DiscoverSchedules.tsx
  packages/desktop-client/src/components/schedules/ScheduleLink.tsx
  packages/desktop-client/src/types/modals.d.ts
  upcoming-release-notes/2298.md
Labels: ✅ Approved

#2309 Consider child transactions when fuzzy matching imported transactions
  packages/loot-core/src/server/accounts/sync.ts
  upcoming-release-notes/2309.md
Labels: ✅ Approved

#2274 Update and organize reports
  packages/desktop-client/src/components/reports/ReportOptions.ts
  packages/desktop-client/src/components/reports/ReportSidebar.jsx
  packages/desktop-client/src/components/reports/ReportTopbar.jsx
  packages/desktop-client/src/components/reports/SaveReport.tsx
  packages/desktop-client/src/components/reports/reports/CustomReport.jsx
  packages/loot-core/src/client/data-hooks/reports.ts
  packages/loot-core/src/server/reports/app.ts
  packages/loot-core/src/types/models/reports.d.ts
  upcoming-release-notes/2274.md
Labels: ✅ Approved

#2300 Change lookback and look forward time range when fuzzy matching
  packages/loot-core/src/server/accounts/sync.ts
  upcoming-release-notes/2300.md
Labels: ✅ Approved

#2325 Re-open autocomplete dropdown on change
  packages/desktop-client/src/components/autocomplete/Autocomplete.tsx
  upcoming-release-notes/2325.md
Labels: ✅ Approved

#2222 [Feature] Add ability to create schedules from existing transactions
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/schedules/ScheduleDetails.jsx
  packages/desktop-client/src/components/schedules/ScheduleLink.tsx
  packages/desktop-client/src/components/transactions/SelectedTransactions.jsx
  packages/desktop-client/src/components/transactions/SimpleTransactionsTable.jsx
  upcoming-release-notes/2222.md
Labels: 🔍 Ready for Review

#2328 :fire: removing unused/dead code
  packages/loot-core/src/server/main.ts
  upcoming-release-notes/2328.md
Labels: ✅ Approved

#2327 Save name fields on unfocus
  packages/desktop-client/src/components/accounts/Header.jsx
  packages/desktop-client/src/components/common/Input.tsx
  packages/desktop-client/src/components/sidebar/SidebarWithData.tsx
  upcoming-release-notes/2327.md
Labels: ✅ Approved

#2295 [Bugfix] Cleanup tool: Add balance check
  packages/loot-core/src/server/budget/cleanup-template.ts
  upcoming-release-notes/2295.md
Labels: ✅ Approved

#2326 :sparkles: allow running AQL against local database
  packages/loot-core/src/server/main.ts
  upcoming-release-notes/2326.md
Labels: ✅ Approved

#1994 Make transaction list sortable by cleared status
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-1-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-2-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-3-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-4-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-creates-a-new-account-and-views-the-initial-balance-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-creates-a-new-account-and-views-the-initial-balance-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-3-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-4-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-checks-the-page-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-checks-the-page-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-split-test-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-split-test-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-test-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-test-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-category-5-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-category-6-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-date-5-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-date-6-chromium-linux.png
  packages/desktop-client/src/components/accounts/Account.jsx
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  upcoming-release-notes/1994.md
Labels: ✅ Approved

#2270 Update desktop client package versions
  packages/api/package.json
  packages/crdt/package.json
  packages/desktop-client/package.json
  packages/desktop-client/src/components/App.tsx
  packages/desktop-client/src/components/BankSyncStatus.tsx
  packages/desktop-client/src/components/LoggedInUser.tsx
  packages/desktop-client/src/components/ManageRules.tsx
  packages/desktop-client/src/components/MobileWebMessage.tsx
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/Notifications.tsx
  packages/desktop-client/src/components/ThemeSelector.tsx
  packages/desktop-client/src/components/Titlebar.tsx
  packages/desktop-client/src/components/UpdateNotification.tsx
  packages/desktop-client/src/components/budget/DynamicBudgetTable.tsx
  packages/desktop-client/src/components/budget/MobileBudget.tsx
  packages/desktop-client/src/components/budget/index.tsx
  packages/desktop-client/src/components/modals/SwitchBudgetType.tsx
  packages/desktop-client/src/components/rules/ScheduleValue.tsx
  packages/desktop-client/src/components/rules/Value.tsx
  packages/desktop-client/src/components/schedules/DiscoverSchedules.tsx
  packages/desktop-client/src/components/schedules/SchedulesTable.tsx
  packages/desktop-client/src/components/select/DateSelect.tsx
  packages/desktop-client/src/components/settings/Encryption.tsx
  packages/desktop-client/src/components/settings/Experimental.tsx
  packages/desktop-client/src/components/settings/Export.tsx
  packages/desktop-client/src/components/settings/Format.tsx
  packages/desktop-client/src/components/settings/Global.tsx
  packages/desktop-client/src/components/settings/Reset.tsx
  packages/desktop-client/src/components/settings/index.tsx
  packages/desktop-client/src/components/sidebar/SidebarWithData.tsx
  packages/desktop-client/src/components/sidebar/index.tsx
  packages/desktop-client/src/hooks/useCategories.ts
  packages/desktop-client/src/hooks/useFeatureFlag.ts
  packages/desktop-client/src/hooks/useSelected.tsx
  packages/desktop-client/src/hooks/useSyncServerStatus.ts
  packages/desktop-client/src/style/theme.tsx
  packages/eslint-plugin-actual/package.json
  packages/loot-core/package.json
  packages/loot-core/src/client/state-types/prefs.d.ts
  upcoming-release-notes/2270.md
  yarn.lock
Labels: ✅ Approved

#2280 Update loot-core deps
  package.json
  packages/api/package.json
  packages/desktop-client/src/components/MobileWebMessage.tsx
  packages/desktop-client/src/components/settings/Experimental.tsx
  packages/desktop-electron/package.json
  packages/loot-core/package.json
  upcoming-release-notes/2280.md
  yarn.lock
Labels: ✅ Approved

#2059 Add rules with splits
  packages/desktop-client/src/components/modals/EditRule.jsx
  packages/desktop-client/src/components/settings/Experimental.tsx
  packages/desktop-client/src/components/spreadsheet/CellValue.tsx
  packages/desktop-client/src/components/spreadsheet/useFormat.ts
  packages/desktop-client/src/components/table.tsx
  packages/desktop-client/src/components/transactions/MobileTransaction.jsx
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  packages/desktop-client/src/hooks/useFeatureFlag.ts
  packages/loot-core/src/server/accounts/rules.ts
  packages/loot-core/src/server/accounts/sync.ts
  packages/loot-core/src/server/accounts/transaction-rules.ts
  packages/loot-core/src/server/rules/app.ts
  packages/loot-core/src/server/rules/types/handlers.ts
  packages/loot-core/src/shared/rules.ts
  packages/loot-core/src/shared/schedules.ts
  packages/loot-core/src/shared/transactions.ts
  packages/loot-core/src/types/models/rule.d.ts
  packages/loot-core/src/types/prefs.d.ts
  upcoming-release-notes/2059.md
Labels: ✅ Approved

#2334 Typescript: pass 2 at updating api-handlers to match server handlers
  packages/loot-core/src/types/api-handlers.d.ts
  upcoming-release-notes/2334.md
Labels: ✅ Approved

#2285 update manifest
  packages/desktop-client/public/maskable-192x192.png
  packages/desktop-client/public/maskable-512x512.png
  packages/desktop-client/public/screenshot_narrow.png
  packages/desktop-client/public/screenshot_wide.png
  packages/desktop-client/public/site.webmanifest
  upcoming-release-notes/2285.md
Labels: ✅ Approved

#2343 :bug: (typescript) patching sendCatch type
  packages/loot-core/src/platform/client/fetch/index.d.ts
  packages/loot-core/src/platform/client/fetch/index.web.ts
  upcoming-release-notes/2343.md
Labels: ✅ Approved

#2342 Fix parse errors with OFX data with no transactions
  packages/loot-core/src/server/accounts/ofx2json.ts
  upcoming-release-notes/2342.md
Labels: ✅ Approved

#2346 Dynamic graph margins
  packages/desktop-client/src/components/reports/ChooseGraph.tsx
  packages/desktop-client/src/components/reports/graphs/AreaGraph.tsx
  packages/desktop-client/src/components/reports/graphs/BarGraph.tsx
  packages/desktop-client/src/components/reports/graphs/StackedBarGraph.tsx
  upcoming-release-notes/2346.md
Labels: ✅ Approved

#2345 Update Custom Report styles
  packages/desktop-client/src/components/reports/ChooseGraph.tsx
  packages/desktop-client/src/components/reports/SaveReport.tsx
  packages/desktop-client/src/components/reports/SaveReportName.tsx
  packages/desktop-client/src/components/reports/graphs/AreaGraph.tsx
  packages/desktop-client/src/components/reports/graphs/DonutGraph.tsx
  packages/desktop-client/src/components/reports/graphs/StackedBarGraph.tsx
  packages/desktop-client/src/components/reports/graphs/renderCustomLabel.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTable.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableHeader.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableList.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableRow.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableTotals.tsx
  packages/desktop-client/src/components/reports/reports/CustomReport.jsx
  packages/loot-core/src/client/data-hooks/reports.ts
  packages/loot-core/src/server/reports/app.ts
  packages/loot-core/src/types/models/reports.d.ts
  upcoming-release-notes/2345.md
Labels: ✅ Approved

#2352 fix: Mobile menu blocks items #2040
  packages/desktop-client/src/components/accounts/MobileAccounts.jsx
  packages/desktop-client/src/components/budget/MobileBudgetTable.jsx
  packages/desktop-client/src/components/mobile/MobileNavTabs.tsx
  upcoming-release-notes/2352.md
Labels: ✅ Approved

#2344 Remove category spending report
  packages/desktop-client/src/components/reports/Overview.jsx
  packages/desktop-client/src/components/reports/ReportRouter.jsx
  packages/desktop-client/src/components/reports/Tooltip.jsx
  packages/desktop-client/src/components/reports/graphs/CategorySpendingGraph.tsx
  packages/desktop-client/src/components/reports/graphs/common.tsx
  packages/desktop-client/src/components/reports/reports/CategorySpending.jsx
  packages/desktop-client/src/components/reports/reports/CategorySpendingCard.jsx
  packages/desktop-client/src/components/reports/spreadsheets/category-spending-spreadsheet.tsx
  packages/desktop-client/src/components/settings/Experimental.tsx
  packages/desktop-client/src/hooks/useFeatureFlag.ts
  packages/loot-core/src/types/prefs.d.ts
  upcoming-release-notes/2344.md
Labels: ✅ Approved

#2356 :fire: (remove victory dependency)
  packages/desktop-client/package.json
  upcoming-release-notes/2356.md
  yarn.lock
Labels: ✅ Approved

#2320 Convert SavedFilters to Typescript
  packages/desktop-client/src/components/accounts/Header.jsx
  packages/desktop-client/src/components/filters/AppliedFilters.tsx
  packages/desktop-client/src/components/filters/CondOpMenu.tsx
  packages/desktop-client/src/components/filters/FilterMenu.tsx
  packages/desktop-client/src/components/filters/FiltersStack.tsx
  packages/desktop-client/src/components/filters/NameFilter.tsx
  packages/desktop-client/src/components/filters/SavedFilterMenuButton.tsx
  packages/desktop-client/src/components/filters/SavedFilters.jsx
  upcoming-release-notes/2320.md
Labels: ✅ Approved

#2358 #1383 Allow early post transaction of schedules
  packages/desktop-client/src/components/schedules/SchedulesTable.tsx
  upcoming-release-notes/2358.md
Labels: ✅ Approved

#2286 fix: Margin when editing account on desktop
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-1-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-2-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-3-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-4-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-creates-a-new-account-and-views-the-initial-balance-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-creates-a-new-account-and-views-the-initial-balance-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-3-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-4-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-checks-the-page-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-checks-the-page-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-split-test-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-split-test-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-test-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-test-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-category-5-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-category-6-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-date-5-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-date-6-chromium-linux.png
  packages/desktop-client/src/components/accounts/Balance.jsx
  packages/desktop-client/src/components/accounts/Header.jsx
  upcoming-release-notes/2286.md
Labels: ✅ Approved

#2357 :recycle: (eslint) enable some rules to enforce better code quality
  .eslintrc.js
  packages/desktop-client/src/components/budget/BudgetCategories.jsx
  packages/desktop-client/src/components/budget/BudgetPageHeader.tsx
  packages/desktop-client/src/components/budget/DynamicBudgetTable.tsx
  packages/desktop-client/src/components/budget/index.tsx
  packages/desktop-client/src/components/common/Button.tsx
  packages/desktop-client/src/components/common/Card.tsx
  packages/desktop-client/src/components/common/ExternalLink.tsx
  packages/desktop-client/src/components/common/Stack.tsx
  packages/desktop-client/src/components/payees/ManagePayees.jsx
  packages/desktop-client/src/components/payees/PayeeTable.tsx
  packages/desktop-client/src/components/payees/PayeeTableRow.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableRow.tsx
  packages/desktop-client/src/components/rules/RuleRow.tsx
  packages/desktop-client/src/components/select/DateSelect.tsx
  packages/desktop-client/src/components/table.tsx
  packages/desktop-client/src/components/transactions/MobileTransaction.jsx
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  upcoming-release-notes/2357.md
Labels: ✅ Approved

#2312 [Enhancement] Theme: Midnight
  packages/desktop-client/src/components/ThemeSelector.tsx
  packages/desktop-client/src/style/theme.tsx
  packages/desktop-client/src/style/themes/midnight.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/types/prefs.d.ts
  upcoming-release-notes/2312.md
Labels: ✅ Approved

#2360 schedule default amount
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-7-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.js-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-8-chromium-linux.png
  packages/desktop-client/src/components/schedules/ScheduleDetails.jsx
  upcoming-release-notes/2360.md
Labels: ✅ Approved

#2383 Fix ability to rename budget in the UI
  packages/desktop-client/src/components/sidebar/Sidebar.tsx
  upcoming-release-notes/2383.md
Labels: ✅ Approved

#2380 [Maintenance] Add tsconfig excludes
  tsconfig.json
  upcoming-release-notes/2380.md
Labels: ✅ Approved

#2369 Add plugin for offline PWA support
  package.json
  packages/desktop-client/package.json
  packages/desktop-client/vite.config.mts
  upcoming-release-notes/2369.md
  yarn.lock
Labels: ✅ Approved

#2335 Custom Reports: save reports (*new SQL table creation*)
  packages/desktop-client/src/components/reports/ChooseGraph.tsx
  packages/desktop-client/src/components/reports/Overview.jsx
  packages/desktop-client/src/components/reports/SaveReport.tsx
  packages/desktop-client/src/components/reports/graphs/AreaGraph.tsx
  packages/desktop-client/src/components/reports/graphs/BarGraph.tsx
  packages/desktop-client/src/components/reports/graphs/DonutGraph.tsx
  packages/desktop-client/src/components/reports/graphs/StackedBarGraph.tsx
  packages/desktop-client/src/components/reports/reports/CustomReport.jsx
  packages/desktop-client/src/components/reports/reports/CustomReportListCards.tsx
  packages/desktop-client/src/components/reports/spreadsheets/filterHiddenItems.ts
  packages/loot-core/migrations/1707267033000_reports.sql
  packages/loot-core/src/client/data-hooks/reports.ts
  packages/loot-core/src/server/aql/schema/index.ts
  upcoming-release-notes/2335.md
Labels: ✅ Approved

#2368 Display rules with splits on rules page
  packages/desktop-client/src/components/modals/EditRule.jsx
  packages/desktop-client/src/components/rules/ActionExpression.tsx
  packages/desktop-client/src/components/rules/RuleRow.tsx
  packages/loot-core/src/server/accounts/transaction-rules.ts
  packages/loot-core/src/server/rules/app.ts
  packages/loot-core/src/shared/rules.ts
  packages/loot-core/src/types/models/rule.d.ts
  upcoming-release-notes/2368.md
Labels: 🔍 Ready for Review, ✅ Approved

#2394 [Theme] Midnight updates
  packages/desktop-client/src/components/payees/PayeeTableRow.tsx
  packages/desktop-client/src/style/themes/midnight.ts
  upcoming-release-notes/2394.md
Labels: ✅ Approved

#2401 fix #2363 broken create schedule from transaction
  packages/desktop-client/src/components/schedules/ScheduleDetails.jsx
  upcoming-release-notes/2401.md
Labels: ✅ Approved

#2399 Update csv amount parser. Fix #2374
  packages/loot-core/src/shared/util.test.ts
  packages/loot-core/src/shared/util.ts
  upcoming-release-notes/2399.md
Labels: ✅ Approved

#2389 Add interval split and menu items to custom reports
  packages/desktop-client/src/components/reports/ChooseGraph.tsx
  packages/desktop-client/src/components/reports/ReportLegend.tsx
  packages/desktop-client/src/components/reports/ReportOptions.ts
  packages/desktop-client/src/components/reports/ReportSidebar.jsx
  packages/desktop-client/src/components/reports/ReportTopbar.jsx
  packages/desktop-client/src/components/reports/graphs/BarGraph.tsx
  packages/desktop-client/src/components/reports/graphs/DonutGraph.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableHeader.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableList.tsx
  packages/desktop-client/src/components/reports/reports/CustomReport.jsx
  packages/desktop-client/src/components/reports/reports/CustomReportListCards.tsx
  packages/desktop-client/src/components/reports/spreadsheets/calculateLegend.ts
  packages/loot-core/src/client/data-hooks/reports.ts
  packages/loot-core/src/server/aql/schema/index.ts
  packages/loot-core/src/server/reports/app.ts
  packages/loot-core/src/types/models/reports.d.ts
  upcoming-release-notes/2389.md
Labels: ✅ Approved

#2350 Custom Reports AutoComplete
  packages/desktop-client/src/components/autocomplete/ReportAutocomplete.tsx
  packages/desktop-client/src/components/autocomplete/ReportList.tsx
  packages/desktop-client/src/components/common/Menu.tsx
  packages/desktop-client/src/components/reports/ReportOptions.ts
  packages/desktop-client/src/components/reports/ReportTopbar.jsx
  packages/desktop-client/src/components/reports/SaveReport.tsx
  packages/desktop-client/src/components/reports/SaveReportChoose.tsx
  packages/desktop-client/src/components/reports/SaveReportMenu.tsx
  packages/desktop-client/src/components/reports/SaveReportName.tsx
  packages/desktop-client/src/components/reports/reports/CustomReport.jsx
  packages/desktop-client/src/components/util/GenericInput.jsx
  packages/loot-core/src/types/models/reports.d.ts
  upcoming-release-notes/2350.md
Labels: ✅ Approved
