Repository actualbudget/actual, pull requests merged in 2024-07, with the labels that each got.

#2966 Revert "[WIP] :bug: fix the app randomly navigating back (closing)"
  packages/desktop-client/src/hooks/useNavigate.ts
  upcoming-release-notes/2772.md
Labels: ✅ Approved

#2955 :bookmark: (24.7.0) custom reports, splits in rules, tags and more
  packages/api/package.json
  packages/desktop-client/package.json
  packages/desktop-electron/package.json
  upcoming-release-notes/2554.md
  upcoming-release-notes/2566.md
  upcoming-release-notes/2642.md
  upcoming-release-notes/2670.md
  upcoming-release-notes/2684.md
  upcoming-release-notes/2771.md
  upcoming-release-notes/2785.md
  upcoming-release-notes/2789.md
  upcoming-release-notes/2790.md
  upcoming-release-notes/2796.md
  upcoming-release-notes/2799.md
  upcoming-release-notes/2805.md
  upcoming-release-notes/2806.md
  upcoming-release-notes/2812.md
  upcoming-release-notes/2817.md
  upcoming-release-notes/2821.md
  upcoming-release-notes/2822.md
  upcoming-release-notes/2825.md
  upcoming-release-notes/2826.md
  upcoming-release-notes/2831.md
  upcoming-release-notes/2836.md
  upcoming-release-notes/2837.md
  upcoming-release-notes/2838.md
  upcoming-release-notes/2840.md
  upcoming-release-notes/2842.md
  upcoming-release-notes/2847.md
  upcoming-release-notes/2848.md
  upcoming-release-notes/2850.md
  upcoming-release-notes/2853.md
  upcoming-release-notes/2861.md
  upcoming-release-notes/2862.md
  upcoming-release-notes/2863.md
  upcoming-release-notes/2864.md
  upcoming-release-notes/2866.md
  upcoming-release-notes/2867.md
  upcoming-release-notes/2870.md
  upcoming-release-notes/2871.md
  upcoming-release-notes/2875.md
  upcoming-release-notes/2878.md
  upcoming-release-notes/2881.md
  upcoming-release-notes/2887.md
  upcoming-release-notes/2890.md
  upcoming-release-notes/2891.md
  upcoming-release-notes/2895.md
  upcoming-release-notes/2896.md
  upcoming-release-notes/2899.md
  upcoming-release-notes/2925.md
  upcoming-release-notes/2927.md
  upcoming-release-notes/2929.md
  upcoming-release-notes/2940.md
  upcoming-release-notes/2941.md
Labels: ✅ Approved

#2960 :electron: Fix backup time format in electron
  packages/loot-core/src/server/backups.ts
  upcoming-release-notes/2960.md
Labels: 🔍 Ready for Review

#2834 Reapply rules to split transactions when the parent changes
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-split-transaction-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-3-chromium-linux.png
  packages/desktop-client/src/components/table.tsx
  packages/desktop-client/src/components/transactions/TransactionList.jsx
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  packages/loot-core/src/shared/transactions.ts
  upcoming-release-notes/2834.md
Labels: 🔍 Ready for Review

#2898 :bug: (bank-sync) fix account highlight dissapearing
  packages/loot-core/src/client/reducers/queries.ts
  packages/loot-core/src/server/main.ts
  upcoming-release-notes/2898.md
Labels: ✅ Approved

#2904 React Aria Button as base of Button component
  packages/desktop-client/e2e/page-models/schedules-page.js
  packages/desktop-client/package.json
  packages/desktop-client/src/components/common/Button2.tsx
  packages/desktop-client/src/components/schedules/DiscoverSchedules.tsx
  packages/desktop-client/src/components/schedules/PostsOfflineNotification.jsx
  packages/desktop-client/src/components/schedules/ScheduleDetails.jsx
  packages/desktop-client/src/components/schedules/ScheduleLink.tsx
  packages/desktop-client/src/components/schedules/SchedulesTable.tsx
  packages/desktop-client/src/components/schedules/index.tsx
  packages/desktop-client/src/components/util/AmountInput.tsx
  upcoming-release-notes/2904.md
  yarn.lock
Labels: ✅ Approved

#2905 :recycle: refactoring Select component to use existing Menu
  packages/desktop-client/e2e/page-models/rules-page.js
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-cash-flow-graph-and-checks-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-cash-flow-graph-and-checks-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-cash-flow-graph-and-checks-visuals-3-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-graph-and-checks-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-graph-and-checks-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-graph-and-checks-visuals-3-chromium-linux.png
  packages/desktop-client/e2e/settings.test.js-snapshots/Settings-checks-the-page-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/settings.test.js-snapshots/Settings-checks-the-page-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/settings.test.js-snapshots/Settings-checks-the-page-visuals-3-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-date-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-date-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-filters-transactions-by-date-3-chromium-linux.png
  packages/desktop-client/package.json
  packages/desktop-client/src/components/common/Popover.tsx
  packages/desktop-client/src/components/common/Select.tsx
  packages/desktop-client/src/components/filters/FiltersMenu.jsx
  packages/desktop-client/src/components/modals/EditRule.jsx
  packages/desktop-client/src/components/modals/ImportTransactions.jsx
  packages/desktop-client/src/components/reports/ReportSidebar.tsx
  packages/desktop-client/src/components/select/RecurringSchedulePicker.jsx
  packages/desktop-client/src/components/settings/Format.tsx
  packages/desktop-client/src/components/settings/Themes.tsx
  packages/desktop-client/src/index.tsx
  upcoming-release-notes/2905.md
  yarn.lock
Labels: ✅ Approved

#2943 Fix rollover arrow display for mobile and desktop
  packages/desktop-client/src/components/budget/BalanceWithCarryover.tsx
  packages/desktop-client/src/components/budget/report/ReportComponents.tsx
  packages/desktop-client/src/components/budget/rollover/RolloverComponents.tsx
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  packages/desktop-client/src/components/modals/ReportBalanceMenuModal.tsx
  packages/desktop-client/src/components/modals/RolloverBalanceMenuModal.tsx
  upcoming-release-notes/2943.md
Labels: 🔍 Ready for Review

#2913 React Aria Button on Settings and Rules Page
  packages/desktop-client/e2e/settings.test.js-snapshots/Settings-checks-the-page-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/settings.test.js-snapshots/Settings-checks-the-page-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/settings.test.js-snapshots/Settings-checks-the-page-visuals-3-chromium-linux.png
  packages/desktop-client/src/components/rules/RuleRow.tsx
  packages/desktop-client/src/components/settings/Encryption.tsx
  packages/desktop-client/src/components/settings/Export.tsx
  packages/desktop-client/src/components/settings/FixSplits.tsx
  packages/desktop-client/src/components/settings/Format.tsx
  packages/desktop-client/src/components/settings/Global.tsx
  packages/desktop-client/src/components/settings/Reset.tsx
  packages/desktop-client/src/components/settings/Themes.tsx
  packages/desktop-client/src/components/settings/index.tsx
  upcoming-release-notes/2913.md
Labels: ✅ Approved

#2880 :electron: Electron package Typescript starting point
  .gitignore
  packages/desktop-electron/bin/update-client
  packages/desktop-electron/index.ts
  packages/desktop-electron/menu.js
  packages/desktop-electron/package.json
  packages/desktop-electron/tsconfig.dist.json
  upcoming-release-notes/2880.md
  yarn.lock
Labels: 🔍 Ready for Review

#2956 Fix warning modal not showing a second time.
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/modals/ConfirmTransactionEdit.tsx
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  packages/loot-core/src/client/state-types/modals.d.ts
  upcoming-release-notes/2956.md
Labels: ✅ Approved

#2903 fix: use Unicode-aware SQLite LIKE filtering
  packages/loot-core/src/platform/server/sqlite/index.electron.ts
  packages/loot-core/src/platform/server/sqlite/index.web.ts
  packages/loot-core/src/platform/server/sqlite/unicodeLike.test.ts
  packages/loot-core/src/platform/server/sqlite/unicodeLike.ts
  packages/loot-core/src/server/aql/compiler.test.ts
  packages/loot-core/src/server/aql/compiler.ts
  upcoming-release-notes/2903.md
Labels: ✅ Approved

#2980 Add PWA shortcuts
  packages/desktop-client/public/shortcut-accounts.svg
  packages/desktop-client/public/shortcut-reports.svg
  packages/desktop-client/public/shortcut-transaction.svg
  packages/desktop-client/public/site.webmanifest
  upcoming-release-notes/2980.md
Labels: 🔍 Ready for Review

#2914 React Aria Button on Accounts and Payees page
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-split-transaction-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-split-transaction-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-2-chromium-linux.png
  packages/desktop-client/src/components/accounts/Account.jsx
  packages/desktop-client/src/components/accounts/AccountSyncCheck.jsx
  packages/desktop-client/src/components/accounts/Balance.jsx
  packages/desktop-client/src/components/accounts/Header.jsx
  packages/desktop-client/src/components/accounts/Reconcile.jsx
  packages/desktop-client/src/components/payees/ManagePayees.jsx
  upcoming-release-notes/2914.md
Labels: 🔍 Ready for Review

#2978 :electron: Electron menu.js ➡️ menu.ts
  packages/desktop-electron/index.ts
  packages/desktop-electron/menu.ts
  upcoming-release-notes/2978.md
Labels: 🔍 Ready for Review

#2983 :electron: Remove "About" screen and broken updater
  packages/desktop-electron/about.js
  packages/desktop-electron/about/about.html
  packages/desktop-electron/about/index.js
  packages/desktop-electron/index.ts
  packages/desktop-electron/menu.ts
  packages/desktop-electron/package.json
  packages/desktop-electron/preload.js
  packages/desktop-electron/updater.js
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/types/prefs.d.ts
  upcoming-release-notes/2983.md
  yarn.lock
Labels: 🔍 Ready for Review

#2995 :electron: server.js ➡️ server.ts
  packages/desktop-electron/index.ts
  packages/desktop-electron/modules.d.ts
  packages/desktop-electron/server.html
  packages/desktop-electron/server.js
  packages/desktop-electron/server.ts
  upcoming-release-notes/2995.md
Labels: 🔍 Ready for Review

#2990 Assign schedule to both transactions if schedule is a transfer
  packages/desktop-client/src/components/accounts/Account.jsx
  packages/desktop-client/src/components/mobile/accounts/AccountTransactions.jsx
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  packages/loot-core/migrations/1720310586000_link_transfer_schedules.sql
  packages/loot-core/src/client/data-hooks/schedules.tsx
  packages/loot-core/src/server/accounts/transfer.ts
  upcoming-release-notes/2990.md
Labels: 🔍 Ready for Review

#2993 Adds ability to resize sidebar
  packages/desktop-client/package.json
  packages/desktop-client/src/components/sidebar/Sidebar.tsx
  packages/desktop-client/src/components/sidebar/index.tsx
  packages/loot-core/src/types/prefs.d.ts
  upcoming-release-notes/2993.md
  yarn.lock
Labels: 🔍 Ready for Review

#3000 remove version from electron build names
  packages/desktop-electron/package.json
  upcoming-release-notes/3000.md
Labels: 🔍 Ready for Review

#2818 Add computed padding for handling clipped large Net worth amounts
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-graph-and-checks-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-graph-and-checks-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-graph-and-checks-visuals-3-chromium-linux.png
  packages/desktop-client/src/components/reports/graphs/NetWorthGraph.tsx
  upcoming-release-notes/2818.md
Labels: 🔍 Ready for Review

#3001 reorders 'Rename' above 'Hide' in menu popovers, adds debounce to sidebar animation
  packages/desktop-client/src/components/Titlebar.tsx
  packages/desktop-client/src/components/budget/SidebarCategory.tsx
  packages/desktop-client/src/components/budget/SidebarGroup.tsx
  packages/desktop-client/src/components/sidebar/index.tsx
  upcoming-release-notes/3001.md
Labels: 🔍 Ready for Review

#3008 Fix cover modal title
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  upcoming-release-notes/3008.md
Labels: ✅ Approved

#2924 Disable interactivity on preview status icons
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  upcoming-release-notes/2924.md
Labels: 🔍 Ready for Review

#3009 :bug: (popover) fix date popover closing when editing a filter
  packages/desktop-client/src/components/filters/FilterExpression.tsx
  upcoming-release-notes/3009.md
Labels: 🔍 Ready for Review

#2717 Explicitly ask when reconciling transactions on manual import
  packages/desktop-client/src/components/forms.tsx
  packages/desktop-client/src/components/modals/ImportTransactions.jsx
  packages/desktop-client/src/icons/v2/DownAndRightArrow.tsx
  packages/desktop-client/src/icons/v2/down-and-right-arrow.svg
  packages/desktop-client/src/icons/v2/index.ts
  packages/loot-core/src/client/actions/account.ts
  packages/loot-core/src/server/accounts/sync.ts
  packages/loot-core/src/server/api.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/2717.md
Labels: ✅ Approved

#3014 :electron: Remove unneded files
  packages/desktop-electron/index.ts
  packages/desktop-electron/server.ts
  packages/desktop-electron/setRequireHook.js
  packages/desktop-electron/signWindowsHook.js
  upcoming-release-notes/3014.md
Labels: 🔍 Ready for Review

#2721 Move bank sync payee name normalisation from `actual` to `actual-server`
  packages/loot-core/src/server/accounts/sync.ts
  upcoming-release-notes/2721.md
Labels: ✅ Approved

#2982 Add apostrophe dot format
  packages/loot-core/src/shared/arithmetic.test.ts
  packages/loot-core/src/shared/arithmetic.ts
  packages/loot-core/src/shared/util.test.ts
  packages/loot-core/src/shared/util.ts
  upcoming-release-notes/2982.md
Labels: 🔍 Ready for Review

#3019 Fix mobile payee creation display for long payee names
  packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.tsx
  upcoming-release-notes/3019.md
Labels: 🔍 Ready for Review

#3022 Expose bank sync account data in AQL.
  packages/loot-core/src/server/aql/schema/index.ts
  upcoming-release-notes/3022.md
Labels: 🔍 Ready for Review

#2930 Add getAccountBalance() API.
  packages/api/methods.test.ts
  packages/api/methods.ts
  packages/loot-core/src/server/api.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/types/api-handlers.d.ts
  upcoming-release-notes/2930.md
Labels: 🔍 Ready for Review

#3017 :sparkles: (budget-type) moving the selector to settings page
  packages/desktop-client/src/components/FinancesApp.tsx
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/Titlebar.tsx
  packages/desktop-client/src/components/budget/index.tsx
  packages/desktop-client/src/components/mobile/budget/index.tsx
  packages/desktop-client/src/components/modals/BudgetPageMenuModal.tsx
  packages/desktop-client/src/components/modals/SwitchBudgetTypeModal.tsx
  packages/desktop-client/src/components/settings/BudgetTypeSettings.tsx
  packages/desktop-client/src/components/settings/index.tsx
  packages/loot-core/src/client/state-types/modals.d.ts
  upcoming-release-notes/3017.md
Labels: 🔍 Ready for Review

#2968 Fix editing transactions on mobile not going back.
  packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
  upcoming-release-notes/2968.md
Labels: ✅ Approved

#3007 Fix alignment of reports
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-and-cash-flow-reports-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-and-cash-flow-reports-2-chromium-linux.png
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-and-cash-flow-reports-3-chromium-linux.png
  packages/desktop-client/src/components/reports/Overview.tsx
  packages/desktop-client/src/components/reports/ReportCard.tsx
  packages/desktop-client/src/components/reports/reports/CashFlowCard.jsx
  packages/desktop-client/src/components/reports/reports/CustomReportListCards.tsx
  packages/desktop-client/src/components/reports/reports/NetWorthCard.jsx
  packages/desktop-client/src/components/reports/reports/SpendingCard.tsx
  upcoming-release-notes/3007.md
Labels: ✅ Approved

#2928 API: add getBudgets() methods to list all budgets in the local cache or remote server.
  packages/api/methods.test.ts
  packages/api/methods.ts
  packages/loot-core/src/server/api-models.ts
  packages/loot-core/src/server/api.ts
  packages/loot-core/src/types/api-handlers.d.ts
  upcoming-release-notes/2928.md
Labels: 🔍 Ready for Review

#3029 Perform bank sync in same order as accounts shown in sidebar.
  packages/loot-core/src/client/actions/account.ts
  packages/loot-core/src/server/main.ts
  upcoming-release-notes/3029.md
Labels: 🔍 Ready for Review

#3028 Add mergePayees method to the API
  packages/api/methods.ts
  packages/loot-core/src/server/api.ts
  packages/loot-core/src/types/api-handlers.d.ts
  upcoming-release-notes/3028.md
Labels: ✅ Approved

#3032 Dim hidden income category rows
  packages/desktop-client/src/components/budget/IncomeCategory.tsx
  upcoming-release-notes/3032.md
Labels: 🔍 Ready for Review

#3023 Remove Trafico workflow in favour of our new GitHub bot
  .github/workflows/trafico.yml
  .github/workflows/wip.yml
  upcoming-release-notes/3023.md
Labels: 🔍 Ready for Review

#3011 [Goals]: don't reset goals when using "apply template"
  packages/loot-core/src/server/budget/goaltemplates.ts
  upcoming-release-notes/3011.md
Labels: 🔍 Ready for Review, :white_check_mark: Approved

#3037 Fix the position of the separator in the operator menu when editing a rule
  packages/desktop-client/src/components/modals/EditRule.jsx
  upcoming-release-notes/3037.md
Labels: :white_check_mark: Approved

#3046 fixes alignment of notifications on mobile to be centered
  packages/desktop-client/src/components/Notifications.tsx
  upcoming-release-notes/3046.md
Labels: :white_check_mark: Approved

#3027 :electron: Convert window-state.js ➡️ window-state.ts
  packages/desktop-electron/index.ts
  packages/desktop-electron/modules.d.ts
  packages/desktop-electron/window-state.ts
  upcoming-release-notes/3027.md
Labels: 🔍 Ready for Review, :white_check_mark: Approved

#3026 migrate BudgetList to typescript
  packages/desktop-client/src/components/manager/BudgetList.tsx
  packages/loot-core/src/client/reducers/budgets.ts
  packages/loot-core/src/types/file.d.ts
  upcoming-release-notes/3026.md
Labels: 🔍 Ready for Review, :white_check_mark: Approved

#3015 :electron: Build electron for Mac Universal arch
  packages/desktop-electron/package.json
  upcoming-release-notes/3015.md
Labels: :white_check_mark: Approved

#3033 Add help modal for keyboard shortcuts.
  packages/desktop-client/src/browser-preload.browser.js
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/modals/KeyboardShortcutModal.tsx
  packages/loot-core/src/client/reducers/modals.ts
  upcoming-release-notes/3033.md
Labels: :white_check_mark: Approved

#2828 ♻️ (tooltip) refactoring to react-aria (vol.10)
  packages/desktop-client/src/components/modals/CreateAccountModal.tsx
  packages/desktop-client/src/components/schedules/SchedulesTable.tsx
  packages/desktop-client/src/components/table.tsx
  packages/desktop-client/src/components/tooltips.tsx
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  packages/desktop-client/src/components/transactions/TransactionsTable.test.jsx
  upcoming-release-notes/2828.md
Labels: :white_check_mark: Approved

#3058 🔧 add lint-staged and husky to auto-patch formatting issues
  .husky/pre-commit
  package.json
  upcoming-release-notes/3058.md
  yarn.lock
Labels: :white_check_mark: Approved

#3056 Add autocapitalize to payee autocomplete
  packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.tsx
  upcoming-release-notes/3056.md
Labels: :white_check_mark: Approved

#3084 Fix "?" crashing on budget selection page.
  packages/desktop-client/src/components/manager/Modals.jsx
  upcoming-release-notes/3084.md
Labels: :white_check_mark: Approved

#2916 React Aria Button on Management App
  packages/desktop-client/src/components/manager/BudgetList.tsx
  packages/desktop-client/src/components/manager/ConfigServer.tsx
  packages/desktop-client/src/components/manager/DeleteFile.tsx
  packages/desktop-client/src/components/manager/Import.tsx
  packages/desktop-client/src/components/manager/ImportActual.tsx
  packages/desktop-client/src/components/manager/ImportYNAB4.tsx
  packages/desktop-client/src/components/manager/ImportYNAB5.tsx
  packages/desktop-client/src/components/manager/WelcomeScreen.tsx
  packages/desktop-client/src/components/manager/subscribe/Bootstrap.tsx
  packages/desktop-client/src/components/manager/subscribe/ChangePassword.tsx
  packages/desktop-client/src/components/manager/subscribe/ConfirmPasswordForm.tsx
  packages/desktop-client/src/components/manager/subscribe/Error.tsx
  packages/desktop-client/src/components/manager/subscribe/Login.tsx
  upcoming-release-notes/2916.md
Labels: :white_check_mark: Approved

#3073 Fix rules not being applied in mobile transaction entry
  packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
  upcoming-release-notes/3073.md
Labels: :white_check_mark: Approved

#2918 React Aria Button on Modals
  packages/desktop-client/src/components/modals/AccountMenuModal.tsx
  packages/desktop-client/src/components/modals/CategoryGroupMenuModal.tsx
  packages/desktop-client/src/components/modals/CategoryMenuModal.tsx
  packages/desktop-client/src/components/modals/CloseAccountModal.tsx
  packages/desktop-client/src/components/modals/ConfirmCategoryDelete.tsx
  packages/desktop-client/src/components/modals/ConfirmTransactionDelete.tsx
  packages/desktop-client/src/components/modals/ConfirmTransactionEdit.tsx
  packages/desktop-client/src/components/modals/ConfirmUnlinkAccount.tsx
  packages/desktop-client/src/components/modals/CoverModal.tsx
  packages/desktop-client/src/components/modals/CreateAccountModal.tsx
  packages/desktop-client/src/components/modals/CreateEncryptionKeyModal.tsx
  packages/desktop-client/src/components/modals/CreateLocalAccountModal.tsx
  packages/desktop-client/src/components/modals/EditField.jsx
  packages/desktop-client/src/components/modals/EditRule.jsx
  packages/desktop-client/src/components/modals/FixEncryptionKeyModal.tsx
  packages/desktop-client/src/components/modals/GoCardlessExternalMsg.tsx
  packages/desktop-client/src/components/modals/GoCardlessInitialise.tsx
  packages/desktop-client/src/components/modals/HoldBufferModal.tsx
  packages/desktop-client/src/components/modals/ImportTransactions.jsx
  packages/desktop-client/src/components/modals/LoadBackup.jsx
  packages/desktop-client/src/components/modals/MergeUnusedPayees.jsx
  packages/desktop-client/src/components/modals/NotesModal.tsx
  packages/desktop-client/src/components/modals/ReportBudgetMonthMenuModal.tsx
  packages/desktop-client/src/components/modals/RolloverBudgetMonthMenuModal.tsx
  packages/desktop-client/src/components/modals/SelectLinkedAccounts.jsx
  packages/desktop-client/src/components/modals/SimpleFinInitialise.tsx
  packages/desktop-client/src/components/modals/SingleInputModal.tsx
  packages/desktop-client/src/components/modals/TransferModal.tsx
  upcoming-release-notes/2918.md
Labels: :white_check_mark: Approved

#3086 CAMT.053: Handle missing ValDt on entries with Sts Book
  packages/loot-core/src/mocks/files/camt/camt.053.xml
  packages/loot-core/src/server/accounts/xmlcamt2json.ts
  upcoming-release-notes/3086.md
Labels: :white_check_mark: Approved

#3061 Add additional hotkeys
  packages/desktop-client/src/components/Titlebar.tsx
  packages/desktop-client/src/components/accounts/Header.jsx
  packages/desktop-client/src/components/budget/BudgetPageHeader.tsx
  packages/desktop-client/src/components/budget/DynamicBudgetTable.tsx
  packages/desktop-client/src/components/filters/FiltersMenu.jsx
  packages/desktop-client/src/components/modals/KeyboardShortcutModal.tsx
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  upcoming-release-notes/3061.md
Labels: :white_check_mark: Approved

#3066 :electron: security.js and preload.js ➡️ .ts
  packages/desktop-electron/index.ts
  packages/desktop-electron/preload.ts
  packages/desktop-electron/security.ts
  upcoming-release-notes/3066.md
Labels: :white_check_mark: Approved

#2973 update split transaction handling for csv export
  packages/loot-core/src/server/accounts/export-to-csv.ts
  upcoming-release-notes/2973.md
Labels: :white_check_mark: Approved

#3100 :electron: Added keyboard shortcuts reference to Help menu
  packages/desktop-electron/menu.ts
  upcoming-release-notes/3100.md
Labels: :white_check_mark: Approved

#3101 Add callouts to starting fresh and migration documentations in README
  README.md
  upcoming-release-notes/3101.md
Labels: :white_check_mark: Approved

#2832 fix: number format config not being respected for graphs
  packages/desktop-client/src/components/reports/graphs/BarLineGraph.tsx
  packages/desktop-client/src/components/reports/graphs/NetWorthGraph.tsx
  packages/loot-core/src/shared/util.ts
  upcoming-release-notes/2832.md
Labels: :white_check_mark: Approved

#2814 Recently used and favorite payees
  packages/api/methods.ts
  packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.tsx
  packages/desktop-client/src/components/payees/ManagePayees.jsx
  packages/desktop-client/src/components/payees/PayeeMenu.tsx
  packages/desktop-client/src/components/payees/PayeeTableRow.tsx
  packages/desktop-client/src/components/transactions/TransactionsTable.test.jsx
  packages/desktop-client/src/hooks/usePayees.ts
  packages/loot-core/migrations/1720664867241_add_payee_favorite.sql
  packages/loot-core/src/client/actions/queries.ts
  packages/loot-core/src/client/constants.ts
  packages/loot-core/src/client/reducers/queries.ts
  packages/loot-core/src/client/state-types/queries.d.ts
  packages/loot-core/src/server/api.ts
  packages/loot-core/src/server/aql/schema/index.ts
  packages/loot-core/src/server/db/index.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/types/api-handlers.d.ts
  packages/loot-core/src/types/models/payee.d.ts
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/2814.md
Labels: :white_check_mark: Approved

#3105 :arrow_up: upgrade yarn to 4.3.1
  .yarn/releases/yarn-4.0.2.cjs
  .yarn/releases/yarn-4.3.1.cjs
  .yarnrc.yml
  package.json
  packages/desktop-electron/package.json
  upcoming-release-notes/3105.md
  yarn.lock
Labels: :white_check_mark: Approved

#3104 :fire: (preferences) remove unused user prefs
  packages/desktop-client/src/components/App.tsx
  packages/desktop-client/src/components/mobile/MobileWebMessage.tsx
  packages/loot-core/src/mocks/budget.ts
  packages/loot-core/src/types/prefs.d.ts
  upcoming-release-notes/3104.md
Labels: :white_check_mark: Approved

#3106 :pencil: update some information in the README
  README.md
  upcoming-release-notes/3106.md
Labels: :white_check_mark: Approved

#2946 Port finance modals to use new Modal component based on React Aria Modal
  packages/desktop-client/e2e/page-models/account-page.js
  packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-cash-flow-graph-and-checks-visuals-1-chromium-linux.png
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/common/Modal.tsx
  packages/desktop-client/src/components/common/Modal2.tsx
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  packages/desktop-client/src/components/mobile/budget/index.tsx
  packages/desktop-client/src/components/modals/AccountAutocompleteModal.tsx
  packages/desktop-client/src/components/modals/AccountMenuModal.tsx
  packages/desktop-client/src/components/modals/BudgetListModal.tsx
  packages/desktop-client/src/components/modals/BudgetPageMenuModal.tsx
  packages/desktop-client/src/components/modals/CategoryAutocompleteModal.tsx
  packages/desktop-client/src/components/modals/CategoryGroupMenuModal.tsx
  packages/desktop-client/src/components/modals/CategoryMenuModal.tsx
  packages/desktop-client/src/components/modals/CloseAccountModal.tsx
  packages/desktop-client/src/components/modals/ConfirmCategoryDelete.tsx
  packages/desktop-client/src/components/modals/ConfirmTransactionDelete.tsx
  packages/desktop-client/src/components/modals/ConfirmTransactionEdit.tsx
  packages/desktop-client/src/components/modals/ConfirmUnlinkAccount.tsx
  packages/desktop-client/src/components/modals/CoverModal.tsx
  packages/desktop-client/src/components/modals/CreateAccountModal.tsx
  packages/desktop-client/src/components/modals/CreateEncryptionKeyModal.tsx
  packages/desktop-client/src/components/modals/CreateLocalAccountModal.tsx
  packages/desktop-client/src/components/modals/EditField.jsx
  packages/desktop-client/src/components/modals/EditRule.jsx
  packages/desktop-client/src/components/modals/FixEncryptionKeyModal.tsx
  packages/desktop-client/src/components/modals/GoCardlessExternalMsg.tsx
  packages/desktop-client/src/components/modals/GoCardlessInitialise.tsx
  packages/desktop-client/src/components/modals/HoldBufferModal.tsx
  packages/desktop-client/src/components/modals/ImportTransactions.jsx
  packages/desktop-client/src/components/modals/KeyboardShortcutModal.tsx
  packages/desktop-client/src/components/modals/LoadBackup.jsx
  packages/desktop-client/src/components/modals/ManageRulesModal.tsx
  packages/desktop-client/src/components/modals/MergeUnusedPayees.jsx
  packages/desktop-client/src/components/modals/NotesModal.tsx
  packages/desktop-client/src/components/modals/PayeeAutocompleteModal.tsx
  packages/desktop-client/src/components/modals/ReportBalanceMenuModal.tsx
  packages/desktop-client/src/components/modals/ReportBudgetMenuModal.tsx
  packages/desktop-client/src/components/modals/ReportBudgetMonthMenuModal.tsx
  packages/desktop-client/src/components/modals/ReportBudgetSummaryModal.tsx
  packages/desktop-client/src/components/modals/RolloverBalanceMenuModal.tsx
  packages/desktop-client/src/components/modals/RolloverBudgetMenuModal.tsx
  packages/desktop-client/src/components/modals/RolloverBudgetMonthMenuModal.tsx
  packages/desktop-client/src/components/modals/RolloverBudgetSummaryModal.tsx
  packages/desktop-client/src/components/modals/RolloverToBudgetMenuModal.tsx
  packages/desktop-client/src/components/modals/ScheduledTransactionMenuModal.tsx
  packages/desktop-client/src/components/modals/SelectLinkedAccounts.jsx
  packages/desktop-client/src/components/modals/SimpleFinInitialise.tsx
  packages/desktop-client/src/components/modals/SingleInputModal.tsx
  packages/desktop-client/src/components/modals/TransferModal.tsx
  packages/desktop-client/src/components/schedules/DiscoverSchedules.tsx
  packages/desktop-client/src/components/schedules/PostsOfflineNotification.jsx
  packages/desktop-client/src/components/schedules/ScheduleDetails.jsx
  packages/desktop-client/src/components/schedules/ScheduleLink.tsx
  packages/desktop-client/src/hooks/useModalState.ts
  packages/loot-core/src/client/actions/modals.ts
  packages/loot-core/src/client/state-types/modals.d.ts
  upcoming-release-notes/2946.md
Labels: :white_check_mark: Approved

#3049 Include more information in payee of split parent
  packages/desktop-client/e2e/rules.test.js
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-split-transaction-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-split-transaction-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/rules.test.js-snapshots/Rules-creates-a-split-transaction-rule-and-makes-sure-it-is-applied-when-creating-a-transaction-3-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-split-test-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-split-test-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.js-snapshots/Transactions-creates-a-split-test-transaction-3-chromium-linux.png
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  upcoming-release-notes/3049.md
Labels: :white_check_mark: Approved

#3107 :wrench: ping WIP PRs that have been inactive for a week
  .github/workflows/stale.yml
  upcoming-release-notes/3107.md
Labels: :white_check_mark: Approved

#3113 [WIP] modify fly.io url to point to correct documentation
  README.md
  upcoming-release-notes/3113.md
Labels: :construction: WIP

#3117 Custom Reports: PlusOne
  packages/desktop-client/src/components/reports/ReportSidebar.tsx
  upcoming-release-notes/3117.md
Labels: :white_check_mark: Approved

#3092 Fixes #3089: Dismiss pop-over on budget action
  packages/desktop-client/src/components/budget/report/ReportComponents.tsx
  packages/desktop-client/src/components/budget/rollover/RolloverComponents.tsx
  upcoming-release-notes/3092.md
Labels: :white_check_mark: Approved

#3127 Custom Reports: updateReport db Schema fix
  packages/loot-core/src/server/reports/app.ts
  upcoming-release-notes/3127.md
Labels: :white_check_mark: Approved

#3112 Spending Report: add save button
  packages/desktop-client/src/components/reports/ReportSidebar.tsx
  packages/desktop-client/src/components/reports/reports/Spending.tsx
  packages/desktop-client/src/components/reports/reports/SpendingCard.tsx
  packages/loot-core/src/types/prefs.d.ts
  upcoming-release-notes/3112.md
Labels: :white_check_mark: Approved

#3135 Spending Report: card fix
  packages/desktop-client/src/components/reports/graphs/SpendingGraph.tsx
  packages/desktop-client/src/components/reports/reports/Spending.tsx
  packages/desktop-client/src/components/reports/reports/SpendingCard.tsx
  packages/loot-core/src/types/models/reports.d.ts
  packages/loot-core/src/types/prefs.d.ts
  upcoming-release-notes/3135.md
Labels: :white_check_mark: Approved

#3131 Fix menus autoclosed when clicked element on top of the menu item
  packages/desktop-client/src/components/common/Menu.tsx
  packages/desktop-client/src/components/mobile/accounts/Accounts.jsx
  packages/desktop-client/src/components/mobile/transactions/Transaction.jsx
  upcoming-release-notes/3131.md
Labels: :white_check_mark: Approved

#3012 [Goals]: Add a long term goal template
  packages/desktop-client/src/components/budget/BalanceWithCarryover.tsx
  packages/desktop-client/src/components/budget/report/ReportComponents.tsx
  packages/desktop-client/src/components/budget/rollover/RolloverComponents.tsx
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  packages/desktop-client/src/components/modals/ReportBalanceMenuModal.tsx
  packages/desktop-client/src/components/modals/RolloverBalanceMenuModal.tsx
  packages/loot-core/migrations/1720665000000_goal_context.sql
  packages/loot-core/src/client/queries.ts
  packages/loot-core/src/server/aql/schema/index.ts
  packages/loot-core/src/server/budget/actions.ts
  packages/loot-core/src/server/budget/base.ts
  packages/loot-core/src/server/budget/cleanup-template.ts
  packages/loot-core/src/server/budget/goal-template.pegjs
  packages/loot-core/src/server/budget/goaltemplates.ts
  packages/loot-core/src/server/sheet.ts
  upcoming-release-notes/3012.md
Labels: :white_check_mark: Approved

#3082 Fix running balances thick header.
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  upcoming-release-notes/3082.md
Labels: :white_check_mark: Approved

#3142 :bug: add missing hover cursor to new button component
  packages/desktop-client/src/components/common/Button2.tsx
  upcoming-release-notes/3142.md
Labels: :white_check_mark: Approved

#3143 :bug: add missing underline to links
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-1-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-2-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-3-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-checks-that-settings-page-can-be-opened-4-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-checks-that-settings-page-can-be-opened-5-chromium-linux.png
  packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-checks-that-settings-page-can-be-opened-6-chromium-linux.png
  packages/desktop-client/src/components/common/Link.tsx
  upcoming-release-notes/3143.md
Labels: :mag: Ready for review

#3146 Fix Button2 isDisabled prop
  packages/desktop-client/src/components/common/Button2.tsx
  upcoming-release-notes/3146.md
Labels: :white_check_mark: Approved

#3144 :wrench: improve unit test stability while using uuid
  packages/loot-core/src/mocks/setup.ts
  upcoming-release-notes/3144.md
Labels: :white_check_mark: Approved

#3151 :bug: fix plain-text link in simplefin error
  packages/desktop-client/src/components/accounts/AccountSyncCheck.jsx
  packages/desktop-client/src/components/modals/SimpleFinInitialise.tsx
  upcoming-release-notes/3151.md
Labels: :white_check_mark: Approved

#3133 :electron: Fix electron "Data Dir" picker on Settings page
  packages/desktop-client/src/components/settings/Global.tsx
  packages/desktop-client/src/components/settings/index.tsx
  upcoming-release-notes/3133.md
Labels: :white_check_mark: Approved

#3153 [Fix] "Enter" key should save on "Cover Overspending" popup
  packages/desktop-client/src/components/budget/rollover/CoverMenu.tsx
  upcoming-release-notes/3153.md
Labels: :white_check_mark: Approved

#3147 Add Modal2 backdrop
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-1-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-2-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-3-chromium-linux.png
  packages/desktop-client/playwright.config.js
  packages/desktop-client/src/components/common/Modal2.tsx
  upcoming-release-notes/3147.md
Labels: :white_check_mark: Approved

#3149 :bug: (rules) fix error handling
  packages/desktop-client/src/components/modals/CreateEncryptionKeyModal.tsx
  packages/desktop-client/src/components/modals/EditRule.jsx
  packages/desktop-client/src/components/modals/FixEncryptionKeyModal.tsx
  packages/desktop-client/src/components/modals/GoCardlessInitialise.tsx
  packages/desktop-client/src/components/modals/ImportTransactions.jsx
  packages/desktop-client/src/components/modals/SimpleFinInitialise.tsx
  packages/desktop-client/src/components/schedules/ScheduleDetails.jsx
  packages/loot-core/src/server/accounts/rules.test.ts
  packages/loot-core/src/server/accounts/rules.ts
  packages/loot-core/src/server/rules/app.ts
  upcoming-release-notes/3149.md
Labels: :white_check_mark: Approved

#3158 Fix local playwright reporter config
  packages/desktop-client/playwright.config.js
  upcoming-release-notes/3158.md
Labels: :white_check_mark: Approved

#3160 :bug: (modals) remove focus outline
  packages/desktop-client/src/components/common/Modal2.tsx
  upcoming-release-notes/3160.md
Labels: :white_check_mark: Approved

#3123 add goal tooltip to balance in budget table
  packages/desktop-client/src/components/budget/BalanceWithCarryover.tsx
  upcoming-release-notes/3123.md
Labels: :white_check_mark: Approved

#3132 Spending Report: Add Last Month
  packages/desktop-client/src/components/reports/graphs/SpendingGraph.tsx
  packages/desktop-client/src/components/reports/reports/Spending.tsx
  packages/desktop-client/src/components/reports/reports/SpendingCard.tsx
  packages/desktop-client/src/components/reports/spreadsheets/spending-spreadsheet.ts
  packages/loot-core/src/types/models/reports.d.ts
  packages/loot-core/src/types/prefs.d.ts
  upcoming-release-notes/3132.md
Labels: :white_check_mark: Approved

#3168 Set minWidth on <input /> to allow it to shrink.
  packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
  upcoming-release-notes/3168.md
Labels: :white_check_mark: Approved
