Repository actualbudget/actual, pull requests merged in 2025-08, with the labels that each got.

#5423 fix crash when enter is used to submit empty date in date picker
  packages/desktop-client/src/components/select/DateSelect.tsx
  upcoming-release-notes/5423.md
Labels: :white_check_mark: approved

#5440 clarify ai generated release note comment
  .github/actions/ai-generated-release-notes/comment-on-pr.js
Labels: :white_check_mark: approved

#5448 🐛 Paginate the count points list files call
  .github/scripts/count-points.mjs
Labels: :white_check_mark: approved

#5450 improvements to release PR points counting logic
  .github/scripts/count-points.mjs
Labels: :white_check_mark: approved

#5457 fix tag colors when using the light theme as system default
  packages/desktop-client/src/style/tags.ts
  upcoming-release-notes/5457.md
Labels: :white_check_mark: approved

#5460 make payeeName fall back to default if the custom mapped bank sync field is missing
  packages/loot-core/src/server/accounts/sync.ts
  upcoming-release-notes/5460.md
Labels: :white_check_mark: approved

#5404 Allow Docker image build by workflow dispatch on forks
  .github/workflows/docker-edge.yml
  upcoming-release-notes/5404.md
Labels: :white_check_mark: approved

#5461 import category notes from nYNAB
  packages/desktop-client/e2e/data/ynab5-demo-budget.json
  packages/loot-core/src/server/importers/ynab5-types.ts
  packages/loot-core/src/server/importers/ynab5.ts
  upcoming-release-notes/5461.md
Labels: :white_check_mark: approved

#5421 Fix translate rule stages
  packages/desktop-client/e2e/help-menu.test.ts
  packages/desktop-client/src/components/rules/RuleRow.tsx
  packages/loot-core/src/shared/rules.ts
  upcoming-release-notes/5421.md
Labels: :white_check_mark: approved

#5396 Fix missing translations
  packages/desktop-client/src/components/budget/SidebarGroup.tsx
  packages/desktop-client/src/components/modals/CategoryGroupMenuModal.tsx
  packages/desktop-client/src/components/reports/SaveReport.tsx
  upcoming-release-notes/5396.md
Labels: :white_check_mark: approved

#5477 Add currencies SEK and TRY
  packages/desktop-client/src/components/settings/Currency.tsx
  packages/loot-core/src/shared/currencies.ts
  upcoming-release-notes/5477.md
Labels: :white_check_mark: approved

#5411 Fix/i18n translate status and date
  packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
  packages/desktop-client/src/components/modals/ImportTransactionsModal/ImportTransactionsModal.jsx
  packages/desktop-client/src/components/schedules/StatusBadge.tsx
  packages/desktop-client/src/components/settings/AuthSettings.tsx
  packages/desktop-client/src/components/settings/index.tsx
  packages/desktop-client/src/components/sidebar/BalanceHistoryGraph.tsx
  packages/desktop-client/src/components/transactions/TransactionsTable.tsx
  upcoming-release-notes/5411.md
Labels: :white_check_mark: approved

#5462 prevent closing an account into itself
  packages/desktop-client/src/components/autocomplete/AccountAutocomplete.tsx
  packages/desktop-client/src/components/modals/AccountAutocompleteModal.tsx
  packages/desktop-client/src/components/modals/CloseAccountModal.tsx
  packages/desktop-client/src/modals/modalsSlice.ts
  packages/loot-core/src/server/accounts/app.ts
  upcoming-release-notes/5462.md
Labels: :white_check_mark: approved

#5452 feat: show/hide balance graph in side nav
  packages/component-library/src/SpaceBetween.tsx
  packages/desktop-client/src/components/sidebar/Account.tsx
  packages/loot-core/src/types/prefs.ts
  upcoming-release-notes/5452.md
Labels: :white_check_mark: approved

#5480 merge automatic package versioning GitHub workflows
  .github/actions/bump-package-versions
  .github/actions/get-next-package-version.js
  .github/workflows/generate-release-pr.yml
  upcoming-release-notes/5480.md
Labels: :white_check_mark: approved

#5495 fix live report date mode not supporting a 2 month window
  packages/desktop-client/src/components/reports/Header.tsx
  packages/desktop-client/src/components/reports/reportRanges.ts
  upcoming-release-notes/5495.md
Labels: :white_check_mark: approved

#5475 Enhance Tooltip component with close delay functionality
  packages/component-library/src/Tooltip.tsx
  packages/desktop-client/src/components/sidebar/Account.tsx
  upcoming-release-notes/5475.md
Labels: :white_check_mark: approved

#5479 Added Länsförsäkringar bank
  packages/sync-server/src/app-gocardless/bank-factory.js
  upcoming-release-notes/5479.md
Labels: :white_check_mark: approved

#5464 make bulk notes prepend/append behaviour consistent with rules
  packages/desktop-client/src/hooks/useTransactionBatchActions.ts
  upcoming-release-notes/5464.md
Labels: :white_check_mark: approved

#5486 Fix translate custom report and rule
  packages/desktop-client/src/components/modals/EditRuleModal.jsx
  packages/desktop-client/src/components/reports/DateRange.tsx
  packages/desktop-client/src/components/reports/ReportSidebar.tsx
  packages/desktop-client/src/components/reports/reports/CustomReportListCards.tsx
  packages/desktop-client/src/components/rules/ActionExpression.tsx
  packages/desktop-client/src/components/rules/RuleRow.tsx
  packages/desktop-client/src/components/rules/Value.tsx
  packages/loot-core/src/shared/rules.ts
  upcoming-release-notes/5486.md
Labels: :white_check_mark: approved

#5507 Add Philippine Peso (PHP) currency
  packages/desktop-client/src/components/settings/Currency.tsx
  packages/loot-core/src/shared/currencies.ts
  upcoming-release-notes/5507.md
Labels: :white_check_mark: approved

#5483 Add Indian Rupee (INR) Currency
  packages/desktop-client/src/components/settings/Currency.tsx
  packages/loot-core/src/shared/currencies.ts
  upcoming-release-notes/5483.md
Labels: :white_check_mark: approved

#5419 Add 'Prior year to date' time range
  packages/desktop-client/e2e/reports.test.ts-snapshots/Reports-loads-cash-flow-graph-and-checks-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.ts-snapshots/Reports-loads-cash-flow-graph-and-checks-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/reports.test.ts-snapshots/Reports-loads-cash-flow-graph-and-checks-visuals-3-chromium-linux.png
  packages/desktop-client/e2e/reports.test.ts-snapshots/Reports-loads-net-worth-graph-and-checks-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.ts-snapshots/Reports-loads-net-worth-graph-and-checks-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/reports.test.ts-snapshots/Reports-loads-net-worth-graph-and-checks-visuals-3-chromium-linux.png
  packages/desktop-client/src/components/reports/Header.tsx
  packages/desktop-client/src/components/reports/ReportOptions.ts
  packages/desktop-client/src/components/reports/disabledList.ts
  packages/desktop-client/src/components/reports/getLiveRange.ts
  packages/desktop-client/src/components/reports/reportRanges.ts
  packages/loot-core/src/shared/months.ts
  packages/loot-core/src/types/models/dashboard.ts
  upcoming-release-notes/5419.md
Labels: :white_check_mark: approved

#5518 Extracted rule editor outside of the modal and into its own component
  packages/desktop-client/src/components/filters/AppliedFilters.tsx
  packages/desktop-client/src/components/filters/ConditionsOpMenu.tsx
  packages/desktop-client/src/components/modals/EditRuleModal.jsx
  packages/desktop-client/src/components/reports/reports/Summary.tsx
  packages/desktop-client/src/components/rules/RuleEditor.tsx
  packages/desktop-client/src/components/schedules/ScheduleDetails.tsx
  upcoming-release-notes/5518.md
Labels: :white_check_mark: approved

#5472 [WIP] add Polish Złoty currency
  packages/desktop-client/src/components/settings/Currency.tsx
  packages/loot-core/src/shared/currencies.ts
  upcoming-release-notes/5472.md
Labels: :construction: WIP

#5528 [BUG] Fix incorrect mathematic calculation in reconcile window
  packages/desktop-client/src/components/accounts/Reconcile.test.tsx
  packages/desktop-client/src/components/accounts/Reconcile.tsx
  upcoming-release-notes/5528.md
Labels: :white_check_mark: approved

#5529 Fix display of link schedules condition
  packages/component-library/src/View.tsx
  packages/desktop-client/src/components/rules/RuleEditor.tsx
  upcoming-release-notes/5529.md
Labels: :white_check_mark: approved

#5532 Add backend logic to support automations UI
  packages/desktop-client/src/components/budget/goals/BudgetAutomation.tsx
  packages/desktop-client/src/components/budget/goals/actions.ts
  packages/desktop-client/src/components/budget/goals/editor/HistoricalAutomation.tsx
  packages/desktop-client/src/components/budget/goals/reducer.ts
  packages/desktop-client/src/components/modals/BudgetAutomationsModal.tsx
  packages/loot-core/migrations/1754611200000_add_category_template_settings.sql
  packages/loot-core/src/server/aql/schema/index.ts
  packages/loot-core/src/server/budget/app.ts
  packages/loot-core/src/server/budget/category-template-context.test.ts
  packages/loot-core/src/server/budget/category-template-context.ts
  packages/loot-core/src/server/budget/goal-template.ts
  packages/loot-core/src/server/budget/schedule-template.test.ts
  packages/loot-core/src/server/budget/statements.ts
  packages/loot-core/src/server/budget/template-notes.test.ts
  packages/loot-core/src/server/budget/template-notes.ts
  packages/loot-core/src/server/db/types/index.ts
  packages/loot-core/src/types/models/category.ts
  packages/loot-core/src/types/models/templates.ts
  upcoming-release-notes/5532.md
Labels: :white_check_mark: approved, contains DB migrations

#5383 Add gocardless support for Stadtsparkasse München
  packages/sync-server/src/app-gocardless/banks/ssk_munchen.js
  upcoming-release-notes/5383.md
Labels: :white_check_mark: approved

#5543 TypeScript: convert edit rules modal
  .cursor/rules/commands.mdc
  .cursor/rules/pull-request.mdc
  .cursor/rules/typescript.mdc
  packages/desktop-client/src/components/modals/EditRuleModal.tsx
  packages/desktop-client/src/components/rules/RuleEditor.tsx
  upcoming-release-notes/5543.md
Labels: :white_check_mark: approved, AI generated

#5415 Fix transaction hooks and improve transactions loading experience in mobile
  packages/desktop-client/src/components/mobile/accounts/AccountTransactions.tsx
  packages/desktop-client/src/components/mobile/budget/CategoryTransactions.tsx
  packages/desktop-client/src/components/mobile/transactions/TransactionList.tsx
  packages/desktop-client/src/components/mobile/transactions/TransactionListItem.tsx
  packages/desktop-client/src/components/mobile/transactions/TransactionListWithBalances.tsx
  packages/desktop-client/src/hooks/useAccountPreviewTransactions.ts
  packages/desktop-client/src/hooks/useCategoryPreviewTransactions.ts
  packages/desktop-client/src/hooks/usePreviewTransactions.ts
  packages/desktop-client/src/hooks/useTransactions.ts
  upcoming-release-notes/5415.md
Labels: :white_check_mark: approved

#5544 Added CODEOWNERS file
  CODEOWNERS
  upcoming-release-notes/5544.md
Labels: :white_check_mark: approved

#5521 Display absolute date of reconciliation
  packages/desktop-client/src/components/accounts/Header.tsx
  packages/desktop-client/src/components/accounts/Reconcile.tsx
  upcoming-release-notes/5521.md
Labels: :white_check_mark: approved

#5379 🛠️ Moving loot-core to Vite
  .github/workflows/size-compare.yml
  packages/crdt/src/index.ts
  packages/desktop-client/package.json
  packages/loot-core/bin/build-api
  packages/loot-core/bin/build-browser
  packages/loot-core/package.json
  packages/loot-core/peg-loader.js
  packages/loot-core/src/server/budgetfiles/app.ts
  packages/loot-core/src/server/polyfills.ts
  packages/loot-core/src/server/rules/index.ts
  packages/loot-core/src/server/schedules/app.ts
  packages/loot-core/src/server/schedules/find-schedules.ts
  packages/loot-core/src/server/util/rschedule.ts
  packages/loot-core/vite.api.config.ts
  packages/loot-core/vite.config.ts
  packages/loot-core/vite.desktop.config.ts
  packages/loot-core/vitest.config.ts
  packages/loot-core/webpack/webpack.api.config.js
  packages/loot-core/webpack/webpack.browser.config.js
  packages/loot-core/webpack/webpack.desktop.config.js
  upcoming-release-notes/5379.md
  yarn.lock
Labels: :white_check_mark: approved

#5556 feat(mobile): ability to delete rules
  packages/desktop-client/e2e/rules.mobile.test.ts-snapshots/Mobile-Rules-clicking-on-a-rule-opens-edit-form-1-chromium-linux.png
  packages/desktop-client/e2e/rules.mobile.test.ts-snapshots/Mobile-Rules-clicking-on-a-rule-opens-edit-form-2-chromium-linux.png
  packages/desktop-client/e2e/rules.mobile.test.ts-snapshots/Mobile-Rules-clicking-on-a-rule-opens-edit-form-3-chromium-linux.png
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/mobile/rules/MobileRuleEditPage.tsx
  packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
  packages/desktop-client/src/components/modals/ConfirmDeleteModal.tsx
  packages/desktop-client/src/components/rules/RuleEditor.tsx
  packages/desktop-client/src/hooks/useTransactionBatchActions.ts
  packages/desktop-client/src/modals/modalsSlice.ts
  upcoming-release-notes/5556.md
Labels: :white_check_mark: approved

#5566 🗑️ Remove unused package (reselect)
  packages/loot-core/package.json
  upcoming-release-notes/5566.md
  yarn.lock
Labels: :white_check_mark: approved

#5565 translate import transactions
  packages/desktop-client/src/components/App.tsx
  packages/desktop-client/src/components/modals/ImportTransactionsModal/ImportTransactionsModal.jsx
  packages/desktop-client/src/components/modals/ImportTransactionsModal/InOutOption.tsx
  packages/desktop-client/src/components/modals/ImportTransactionsModal/Transaction.tsx
  upcoming-release-notes/5565.md
Labels: :white_check_mark: approved

#5438 fix filter transactions by closed account transfer payee
  eslint.config.mjs
  packages/desktop-client/src/components/FixedSizeList.tsx
  packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.tsx
  packages/desktop-client/src/components/filters/FiltersMenu.jsx
  packages/desktop-client/src/components/filters/PayeeFilter.tsx
  upcoming-release-notes/5438.md
Labels: :white_check_mark: approved

#5533 Connect automations UI to backend
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/NotesButton.tsx
  packages/desktop-client/src/components/budget/SidebarCategory.tsx
  packages/desktop-client/src/components/budget/SidebarCategoryButtons.tsx
  packages/desktop-client/src/components/budget/goals/BudgetAutomationEditor.tsx
  packages/desktop-client/src/components/budget/goals/CategoryAutomationButton.tsx
  packages/desktop-client/src/components/budget/goals/editor/SimpleAutomation.tsx
  packages/desktop-client/src/components/budget/goals/editor/SimpleAutomationReadOnly.tsx
  packages/desktop-client/src/components/budget/goals/editor/WeekAutomation.tsx
  packages/desktop-client/src/components/budget/goals/editor/WeekAutomationReadOnly.tsx
  packages/desktop-client/src/components/budget/goals/reducer.ts
  packages/desktop-client/src/components/forms.tsx
  packages/desktop-client/src/components/modals/BudgetAutomationsModal.tsx
  packages/desktop-client/src/hooks/useBudgetAutomations.ts
  packages/desktop-client/src/modals/modalsSlice.ts
  upcoming-release-notes/5533.md
Labels: :white_check_mark: approved

#5586 Dispatch github ci jobs after running update-vrt workflow
  .github/workflows/build.yml
  .github/workflows/check.yml
  .github/workflows/codeql.yml
  .github/workflows/update-vrt.yml
  upcoming-release-notes/5586.md
Labels: :white_check_mark: approved, AI generated

#5589 [Mobile] Do not show transfer transactions on uncategorized transactions view/page
  packages/desktop-client/src/components/mobile/budget/UncategorizedTransactions.tsx
  packages/desktop-client/src/queries/index.ts
  packages/desktop-client/src/spreadsheet/bindings.ts
  upcoming-release-notes/5589.md
Labels: :white_check_mark: approved

#5591 Command bar VRTs
  packages/desktop-client/e2e/command-bar.test.ts
  packages/desktop-client/e2e/command-bar.test.ts-snapshots/Command-bar-Check-the-command-bar-search-works-correctly-1-chromium-linux.png
  packages/desktop-client/e2e/command-bar.test.ts-snapshots/Command-bar-Check-the-command-bar-search-works-correctly-2-chromium-linux.png
  packages/desktop-client/e2e/command-bar.test.ts-snapshots/Command-bar-Check-the-command-bar-search-works-correctly-3-chromium-linux.png
  packages/desktop-client/e2e/command-bar.test.ts-snapshots/Command-bar-Check-the-command-bar-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/command-bar.test.ts-snapshots/Command-bar-Check-the-command-bar-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/command-bar.test.ts-snapshots/Command-bar-Check-the-command-bar-visuals-3-chromium-linux.png
  upcoming-release-notes/5591.md
Labels: :white_check_mark: approved

#5581 [Redux] Move account states from queriesSlice to accountsSlice
  packages/desktop-client/src/accounts/accountsSlice.ts
  packages/desktop-client/src/components/FinancesApp.tsx
  packages/desktop-client/src/components/accounts/Account.tsx
  packages/desktop-client/src/components/mobile/accounts/AccountPage.tsx
  packages/desktop-client/src/components/mobile/accounts/AccountTransactions.tsx
  packages/desktop-client/src/components/mobile/accounts/AccountsPage.tsx
  packages/desktop-client/src/components/modals/CloseAccountModal.tsx
  packages/desktop-client/src/components/modals/CreateLocalAccountModal.tsx
  packages/desktop-client/src/components/sidebar/Account.tsx
  packages/desktop-client/src/components/transactions/TransactionsTable.tsx
  packages/desktop-client/src/global-events.ts
  packages/desktop-client/src/hooks/useAccounts.ts
  packages/desktop-client/src/hooks/useUpdatedAccounts.ts
  packages/desktop-client/src/modals/modalsSlice.ts
  packages/desktop-client/src/queries/queriesSlice.ts
  packages/desktop-client/src/sync-events.ts
  upcoming-release-notes/5581.md
Labels: :white_check_mark: approved

#5592 [Redux] Move payee states from queriesSlice to payeesSlice
  packages/desktop-client/src/accounts/accountsSlice.ts
  packages/desktop-client/src/components/ManageRules.tsx
  packages/desktop-client/src/components/accounts/Account.tsx
  packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.tsx
  packages/desktop-client/src/components/modals/ImportTransactionsModal/ImportTransactionsModal.jsx
  packages/desktop-client/src/components/payees/ManagePayeesWithData.tsx
  packages/desktop-client/src/components/rules/RuleEditor.tsx
  packages/desktop-client/src/components/rules/ScheduleValue.tsx
  packages/desktop-client/src/components/schedules/ScheduleDetails.tsx
  packages/desktop-client/src/components/transactions/TransactionsTable.tsx
  packages/desktop-client/src/global-events.ts
  packages/desktop-client/src/hooks/usePayees.ts
  packages/desktop-client/src/payees/payeesSlice.ts
  packages/desktop-client/src/queries/queriesSlice.ts
  packages/desktop-client/src/redux/mock.tsx
  packages/desktop-client/src/redux/store.ts
  packages/desktop-client/src/sync-events.ts
  upcoming-release-notes/5592.md
Labels: :white_check_mark: approved

#5593 [Redux] Move category states from queriesSlice to budgetSlice
  packages/desktop-client/src/auth/ProtectedRoute.tsx
  packages/desktop-client/src/budget/budgetSlice.ts
  packages/desktop-client/src/budgetfiles/budgetfilesSlice.ts
  packages/desktop-client/src/components/App.tsx
  packages/desktop-client/src/components/LoggedInUser.tsx
  packages/desktop-client/src/components/budget/index.tsx
  packages/desktop-client/src/components/manager/BudgetFileSelection.tsx
  packages/desktop-client/src/components/manager/ConfigServer.tsx
  packages/desktop-client/src/components/manager/ManagementApp.tsx
  packages/desktop-client/src/components/manager/WelcomeScreen.tsx
  packages/desktop-client/src/components/manager/subscribe/Bootstrap.tsx
  packages/desktop-client/src/components/mobile/budget/BudgetPage.tsx
  packages/desktop-client/src/components/mobile/budget/ExpenseCategoryList.tsx
  packages/desktop-client/src/components/mobile/budget/ExpenseGroupList.tsx
  packages/desktop-client/src/components/mobile/budget/IncomeCategoryList.tsx
  packages/desktop-client/src/components/modals/BudgetFileSelectionModal.tsx
  packages/desktop-client/src/components/modals/CreateEncryptionKeyModal.tsx
  packages/desktop-client/src/components/modals/LoadBackupModal.tsx
  packages/desktop-client/src/components/modals/OpenIDEnableModal.tsx
  packages/desktop-client/src/components/modals/OutOfSyncMigrationsModal.tsx
  packages/desktop-client/src/components/modals/PasswordEnableModal.tsx
  packages/desktop-client/src/components/modals/TransferOwnership.tsx
  packages/desktop-client/src/components/modals/manager/DeleteFileModal.tsx
  packages/desktop-client/src/components/modals/manager/DuplicateFileModal.tsx
  packages/desktop-client/src/components/modals/manager/FilesSettingsModal.tsx
  packages/desktop-client/src/components/modals/manager/ImportActualModal.tsx
  packages/desktop-client/src/components/modals/manager/ImportYNAB4Modal.tsx
  packages/desktop-client/src/components/modals/manager/ImportYNAB5Modal.tsx
  packages/desktop-client/src/components/settings/index.tsx
  packages/desktop-client/src/components/sidebar/BudgetName.tsx
  packages/desktop-client/src/components/transactions/TransactionsTable.tsx
  packages/desktop-client/src/global-events.ts
  packages/desktop-client/src/hooks/useCategories.ts
  packages/desktop-client/src/index.tsx
  packages/desktop-client/src/queries/queriesSlice.ts
  packages/desktop-client/src/redux/mock.tsx
  packages/desktop-client/src/redux/store.ts
  packages/desktop-client/src/sync-events.ts
  packages/desktop-client/src/users/usersSlice.ts
  packages/loot-core/src/server/budget/app.ts
  packages/loot-core/src/server/db/index.ts
  upcoming-release-notes/5593.md
Labels: :white_check_mark: approved

#5604 Enable Make Transfer menu for child transactions
  packages/loot-core/src/shared/transfer.ts
  upcoming-release-notes/5604.md
Labels: :white_check_mark: approved

#5597 [Redux] Move tags states from queriesSlice to tagsSlice
  packages/desktop-client/src/components/tags/ManageTags.tsx
  packages/desktop-client/src/components/tags/TagCreationRow.tsx
  packages/desktop-client/src/components/tags/TagEditor.tsx
  packages/desktop-client/src/components/tags/TagRow.tsx
  packages/desktop-client/src/components/tags/TagsList.tsx
  packages/desktop-client/src/hooks/useTags.ts
  packages/desktop-client/src/queries/queriesSlice.ts
  packages/desktop-client/src/redux/mock.tsx
  packages/desktop-client/src/redux/store.ts
  packages/desktop-client/src/tags/tagsSlice.ts
  packages/loot-core/src/server/tags/app.ts
  packages/loot-core/src/types/models/tags.ts
  upcoming-release-notes/5597.md
Labels: :white_check_mark: approved

#5607 Implement responsive DateSelect component for mobile view
  packages/desktop-client/src/components/select/DateSelect.tsx
  upcoming-release-notes/5607.md
Labels: :white_check_mark: approved

#5628 Release Pluggy bank-sync integration
  packages/desktop-client/src/components/modals/CreateAccountModal.tsx
  packages/desktop-client/src/components/settings/Experimental.tsx
  packages/desktop-client/src/hooks/useFeatureFlag.ts
  packages/loot-core/src/types/prefs.ts
  upcoming-release-notes/5628.md
Labels: :white_check_mark: approved

#5634 [fix] Adjust modal styles and text wrapping in TransactionError
  packages/desktop-client/src/components/transactions/TransactionsTable.tsx
  upcoming-release-notes/5634.md
Labels: :white_check_mark: approved
