Repository actualbudget/actual, pull requests merged in 2025-06, with the labels that each got.

#5052 Add 'GLS Gemeinschaftsbank' to banks with limited history
  packages/sync-server/src/app-gocardless/bank-factory.js
  upcoming-release-notes/5052.md
Labels: :white_check_mark: approved

#5073 Add ING PL (ING_PL_INGBPLPW) to banks with limited history
  packages/sync-server/src/app-gocardless/bank-factory.js
  upcoming-release-notes/5073.md
Labels: :white_check_mark: approved

#5080 :bug: (mobile) fix - show loading indicator if schedules not yet loaded
  packages/desktop-client/src/components/mobile/accounts/AccountTransactions.tsx
  packages/desktop-client/src/hooks/usePreviewTransactions.ts
  upcoming-release-notes/5080.md
Labels: :white_check_mark: approved

#5095 fix crash when datepicker deselected with no date set
  packages/desktop-client/src/components/select/DateSelect.tsx
  upcoming-release-notes/5095.md
Labels: :white_check_mark: approved

#5093 :bug: Fix server version on docker
  packages/sync-server/src/app.ts
  upcoming-release-notes/5093.md
Labels: :white_check_mark: approved

#4778 Add ability to auto hold funds for future months
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/budget/envelope/BalanceMenu.tsx
  packages/desktop-client/src/components/budget/envelope/EnvelopeBudgetComponents.tsx
  packages/desktop-client/src/components/budget/envelope/IncomeMenu.tsx
  packages/desktop-client/src/components/budget/envelope/budgetsummary/ToBudget.tsx
  packages/desktop-client/src/components/budget/envelope/budgetsummary/ToBudgetMenu.tsx
  packages/desktop-client/src/components/budget/util.ts
  packages/desktop-client/src/components/mobile/budget/IncomeCategoryListItem.tsx
  packages/desktop-client/src/components/modals/EnvelopeBudgetSummaryModal.tsx
  packages/desktop-client/src/components/modals/EnvelopeIncomeBalanceMenuModal.tsx
  packages/desktop-client/src/components/modals/EnvelopeToBudgetMenuModal.tsx
  packages/desktop-client/src/components/spreadsheet/index.ts
  packages/desktop-client/src/modals/modalsSlice.ts
  packages/desktop-client/src/queries/queries.ts
  packages/desktop-client/src/queries/queriesSlice.ts
  packages/loot-core/src/server/budget/actions.ts
  packages/loot-core/src/server/budget/app.ts
  packages/loot-core/src/server/budget/envelope.ts
  upcoming-release-notes/4778.md
Labels: :white_check_mark: approved

#5101 Trim EndToEndID from the Danish Danske Bank branch
  packages/sync-server/src/app-gocardless/banks/danskebank_privat.js
  upcoming-release-notes/5101.md
Labels: :white_check_mark: approved

#4952 Add test that docker images are working
  .github/workflows/check.yml
  .github/workflows/docker-edge.yml
  upcoming-release-notes/4952.md
Labels: :white_check_mark: approved

#5081 :wrench: (eslint) patch no-restricted-imports rule
  eslint.config.mjs
  packages/desktop-client/src/hooks/useNavigate.ts
  packages/desktop-client/src/redux/index.ts
  packages/desktop-client/src/style/index.ts
  packages/desktop-client/src/style/palette.ts
  packages/desktop-client/src/style/themes/dark.ts
  packages/desktop-client/src/style/themes/development.ts
  packages/desktop-client/src/style/themes/light.ts
  packages/desktop-client/src/style/themes/midnight.ts
  packages/desktop-electron/e2e/onboarding.test.ts
  upcoming-release-notes/5081.md
Labels: :white_check_mark: approved

#5109 :wrench: auto close issues with inaactivity and 'needs info' label
  .github/workflows/stale.yml
  upcoming-release-notes/5109.md
Labels: :white_check_mark: approved

#5110 :wrench: improving the needs-info stale issue management
  .github/workflows/stale.yml
  upcoming-release-notes/5110.md
Labels: :white_check_mark: approved

#5107 :electron: Guide user to the docs on the electron configure server page
  packages/desktop-client/src/components/manager/ConfigServer.tsx
  packages/desktop-electron/e2e/__screenshots__/onboarding.test.ts/Onboarding-checks-the-page-visuals-1-linux.png
  upcoming-release-notes/5107.md
Labels: :white_check_mark: approved

#5111 fix: add missing dependency array to useEffect in SaveReportChoose.tsx (#5044)
  packages/desktop-client/src/components/reports/SaveReportChoose.tsx
  upcoming-release-notes/5111.md
Labels: :mag: ready for review, AI generated

#5048 ⬆️ upgrade uuid from 9.0.1 -> 11.1.0
  packages/api/package.json
  packages/crdt/package.json
  packages/desktop-client/package.json
  packages/loot-core/package.json
  packages/loot-core/src/platform/client/undo/index.ts
  packages/sync-server/package.json
  upcoming-release-notes/5048.md
  yarn.lock
Labels: :white_check_mark: approved, dependencies

#5112 :bug: group template apply
  packages/loot-core/src/server/budget/goal-template.ts
  upcoming-release-notes/5112.md
Labels: :white_check_mark: approved

#5129 Fix net worth graph gradient conflict
  packages/desktop-client/src/components/reports/graphs/NetWorthGraph.tsx
  upcoming-release-notes/5129.md
Labels: :white_check_mark: approved

#5133 fix: add missing 'enabled' in sentence.
  packages/desktop-client/src/components/settings/Reset.tsx
  upcoming-release-notes/5133.md
Labels: :white_check_mark: approved

#5134 fix: ensure correct PR number is used for release notes file
  bin/release-note-generator.ts
  upcoming-release-notes/5134.md
Labels: :sparkles: merged

#5087 add LCL to the list of bank with only 90 days of sync
  packages/sync-server/src/app-gocardless/bank-factory.js
  upcoming-release-notes/5087.md
Labels: :white_check_mark: approved

#5047 :octocat: Add workflow for publishing nightly npm packages
  .github/actions/get-next-package-version.js
  .github/workflows/publish-nightly-npm-packages.yml
  upcoming-release-notes/5047.md
Labels: :white_check_mark: approved

#5085 :sparkles: show account historical balance change in side-nav hover tooltip
  packages/desktop-client/e2e/accounts.test.ts-snapshots/Accounts-closes-an-account-4-chromium-linux.png
  packages/desktop-client/e2e/reports.test.ts-snapshots/Reports-loads-net-worth-and-cash-flow-reports-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.ts-snapshots/Reports-loads-net-worth-and-cash-flow-reports-2-chromium-linux.png
  packages/desktop-client/e2e/reports.test.ts-snapshots/Reports-loads-net-worth-and-cash-flow-reports-3-chromium-linux.png
  packages/desktop-client/e2e/reports.test.ts-snapshots/Reports-loads-net-worth-graph-and-checks-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.ts-snapshots/Reports-loads-net-worth-graph-and-checks-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/reports.test.ts-snapshots/Reports-loads-net-worth-graph-and-checks-visuals-3-chromium-linux.png
  packages/desktop-client/src/components/reports/graphs/NetWorthGraph.tsx
  packages/desktop-client/src/components/sidebar/Account.tsx
  packages/desktop-client/src/components/sidebar/BalanceHistoryGraph.tsx
  upcoming-release-notes/5085.md
Labels: :white_check_mark: approved, AI generated

#5157 Add GitHub Actions workflow for automatic code formatting
  .github/workflows/autofix.yml
  upcoming-release-notes/5157.md
Labels: :white_check_mark: approved, AI generated

#5115 Fix account properties being overriden with empty values from metadata
  packages/sync-server/src/app-gocardless/services/gocardless-service.js
  packages/sync-server/src/app-gocardless/services/tests/gocardless-service.spec.js
  upcoming-release-notes/5115.md
Labels: :white_check_mark: approved

#5147 Add GitHub workflow and script for counting monthly contributor points
  .github/actions/get-next-package-version.js
  .github/scripts/count-points.mjs
  .github/workflows/count-points.yml
  .github/workflows/docker-edge.yml
  .github/workflows/i18n-string-extract-master.yml
  .github/workflows/netlify-release.yml
  .github/workflows/stale.yml
  .prettierignore
  package.json
  upcoming-release-notes/5147.md
  yarn.lock
Labels: :mag: ready for review, AI generated

#5118 Added unit tests for CategorySelector and Change components
  .cursor/rules/pull-request.mdc
  .cursor/rules/typescript.mdc
  .cursor/rules/unit-tests.mdc
  packages/desktop-client/package.json
  packages/desktop-client/src/components/reports/CategorySelector.test.tsx
  packages/desktop-client/src/components/reports/Change.test.tsx
  packages/desktop-client/src/setupTests.js
  upcoming-release-notes/5118.md
  yarn.lock
Labels: :white_check_mark: approved, AI generated

#5165 Fix: display notifications below modal windows
  packages/desktop-client/src/components/Notifications.tsx
  packages/desktop-client/src/components/common/Modal.tsx
  upcoming-release-notes/5165.md
Labels: :white_check_mark: approved

#5172 Upgrade react router to v7
  eslint.config.mjs
  packages/desktop-client/package.json
  packages/desktop-client/src/components/App.tsx
  packages/desktop-client/src/components/FinancesApp.tsx
  packages/desktop-client/src/components/HelpMenu.tsx
  packages/desktop-client/src/components/LoggedInUser.tsx
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/Titlebar.tsx
  packages/desktop-client/src/components/accounts/Account.tsx
  packages/desktop-client/src/components/accounts/AccountSyncCheck.tsx
  packages/desktop-client/src/components/common/Link.tsx
  packages/desktop-client/src/components/manager/ManagementApp.tsx
  packages/desktop-client/src/components/manager/subscribe/Error.tsx
  packages/desktop-client/src/components/manager/subscribe/Login.tsx
  packages/desktop-client/src/components/manager/subscribe/OpenIdForm.tsx
  packages/desktop-client/src/components/manager/subscribe/common.tsx
  packages/desktop-client/src/components/mobile/MobileNavTabs.tsx
  packages/desktop-client/src/components/mobile/accounts/Account.tsx
  packages/desktop-client/src/components/mobile/budget/Category.tsx
  packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
  packages/desktop-client/src/components/modals/KeyboardShortcutModal.tsx
  packages/desktop-client/src/components/modals/ManageRulesModal.tsx
  packages/desktop-client/src/components/payees/ManagePayeesPage.tsx
  packages/desktop-client/src/components/reports/Overview.tsx
  packages/desktop-client/src/components/reports/ReportRouter.tsx
  packages/desktop-client/src/components/reports/graphs/showActivity.ts
  packages/desktop-client/src/components/reports/reports/Calendar.tsx
  packages/desktop-client/src/components/reports/reports/CashFlow.tsx
  packages/desktop-client/src/components/reports/reports/CustomReport.tsx
  packages/desktop-client/src/components/reports/reports/NetWorth.tsx
  packages/desktop-client/src/components/reports/reports/Spending.tsx
  packages/desktop-client/src/components/reports/reports/Summary.tsx
  packages/desktop-client/src/components/schedules/PostsOfflineNotification.tsx
  packages/desktop-client/src/components/settings/UI.tsx
  packages/desktop-client/src/components/sidebar/PrimaryButtons.tsx
  packages/desktop-client/src/hooks/useNavigate.ts
  upcoming-release-notes/5172.md
  yarn.lock
Labels: :white_check_mark: approved

#5179 Enhance PullToRefresh component to ensure full height usage on mobile devices
  packages/desktop-client/src/components/mobile/PullToRefresh.tsx
  upcoming-release-notes/5179.md
Labels: :white_check_mark: approved

#5181 Clean up configuration files
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/actions/setup/action.yml
  .prettierignore
  upcoming-release-notes/5181.md
Labels: :white_check_mark: approved

#5060 Move more .d.ts files to .ts
  packages/api/tsconfig.dist.json
  packages/desktop-client/src/browser-preload.browser.js
  packages/desktop-client/src/components/App.tsx
  packages/desktop-client/src/components/budget/goals/BudgetAutomation.tsx
  packages/desktop-client/src/components/budget/goals/CategoryAutomationButton.tsx
  packages/desktop-client/src/components/budget/goals/actions.ts
  packages/desktop-client/src/components/budget/goals/constants.ts
  packages/desktop-client/src/components/budget/goals/editor/HistoricalAutomation.tsx
  packages/desktop-client/src/components/budget/goals/editor/HistoricalAutomationReadOnly.tsx
  packages/desktop-client/src/components/budget/goals/editor/PercentageAutomation.tsx
  packages/desktop-client/src/components/budget/goals/editor/PercentageAutomationReadOnly.tsx
  packages/desktop-client/src/components/budget/goals/editor/ScheduleAutomation.tsx
  packages/desktop-client/src/components/budget/goals/editor/ScheduleAutomationReadOnly.tsx
  packages/desktop-client/src/components/budget/goals/editor/SimpleAutomation.tsx
  packages/desktop-client/src/components/budget/goals/editor/SimpleAutomationReadOnly.tsx
  packages/desktop-client/src/components/budget/goals/editor/WeekAutomation.tsx
  packages/desktop-client/src/components/budget/goals/editor/WeekAutomationReadOnly.tsx
  packages/desktop-client/src/components/budget/goals/reducer.ts
  packages/desktop-client/src/components/modals/BudgetAutomationsModal.tsx
  packages/desktop-electron/index.ts
  packages/loot-core/src/platform/client/fetch/__mocks__/index.ts
  packages/loot-core/src/platform/client/fetch/index-types.ts
  packages/loot-core/src/platform/client/fetch/index.browser.ts
  packages/loot-core/src/platform/client/fetch/index.ts
  packages/loot-core/src/server/accounts/app.ts
  packages/loot-core/src/server/budget/category-template-context.test.ts
  packages/loot-core/src/server/budget/category-template-context.ts
  packages/loot-core/src/server/budget/goal-template.ts
  packages/loot-core/src/server/budget/schedule-template.ts
  packages/loot-core/src/server/budget/template-notes.ts
  packages/loot-core/src/types/api-handlers.ts
  packages/loot-core/src/types/models/account.ts
  packages/loot-core/src/types/models/bank.ts
  packages/loot-core/src/types/models/import-transaction.ts
  packages/loot-core/src/types/models/index.ts
  packages/loot-core/src/types/models/pluggyai.ts
  packages/loot-core/src/types/models/templates.ts
  packages/loot-core/src/types/models/user-access.ts
  packages/loot-core/src/types/models/user.ts
  packages/loot-core/tsconfig.api.json
  packages/loot-core/typings/pegjs.ts
  packages/loot-core/typings/vite-plugin-peggy-loader.ts
  packages/loot-core/typings/window.ts
  upcoming-release-notes/5060.md
Labels: :white_check_mark: approved

#5189 Update parsing of schedule names (issue #4607)
  packages/loot-core/src/server/budget/goal-template.pegjs
  upcoming-release-notes/5189.md
Labels: :white_check_mark: approved

#5187 add BNP_BE_GEBABEBB in gocardless bank-factory.js
  packages/sync-server/src/app-gocardless/bank-factory.js
  upcoming-release-notes/5187.md
Labels: :white_check_mark: approved

#4799 [Feature] Store and use last synced account balances
  packages/desktop-client/src/components/accounts/Reconcile.tsx
  packages/loot-core/src/server/accounts/sync.ts
  upcoming-release-notes/4799.md
Labels: :white_check_mark: approved

#5183 add Belfius and KBC to banks with limited history
  packages/sync-server/src/app-gocardless/bank-factory.js
  upcoming-release-notes/5183.md
Labels: :white_check_mark: approved

#5193 fix: wrong payeeName for KBC Brussels
  packages/sync-server/src/app-gocardless/banks/kbc_kredbebb.js
  upcoming-release-notes/5193.md
Labels: :white_check_mark: approved

#5197 ♻️ remove body-parser dependency
  packages/sync-server/package.json
  packages/sync-server/src/app.ts
  upcoming-release-notes/5197.md
  yarn.lock
Labels: :white_check_mark: approved, dependencies

#5182 Auto generate Release Notes
  .github/actions/ai-generated-release-notes/check-first-comment.js
  .github/actions/ai-generated-release-notes/check-release-notes-exists.js
  .github/actions/ai-generated-release-notes/comment-on-pr.js
  .github/actions/ai-generated-release-notes/create-release-notes-file.js
  .github/actions/ai-generated-release-notes/determine-category.js
  .github/actions/ai-generated-release-notes/generate-summary.js
  .github/actions/ai-generated-release-notes/pr-details.js
  .github/workflows/ai-generated-release-notes.yml
  upcoming-release-notes/5182.md
Labels: :white_check_mark: approved

#5198 ⬆️ bump csv-parse and csv-stringify to latest
  packages/loot-core/package.json
  packages/loot-core/src/server/transactions/export/export-to-csv.ts
  packages/loot-core/src/server/transactions/import/parse-file.ts
  upcoming-release-notes/5198.md
  yarn.lock
Labels: :white_check_mark: approved, dependencies

#5196 ⬆️ bump react-i18next from 14.1.3 -> 15.5.3
  packages/desktop-client/package.json
  packages/loot-core/package.json
  upcoming-release-notes/5196.md
  yarn.lock
Labels: :white_check_mark: approved, dependencies

#5200 🐛 Fix to AI generated release note
  .github/workflows/ai-generated-release-notes.yml
  upcoming-release-notes/5200.md
Labels: :white_check_mark: approved

#5202 Improve Boursobank Gocardless transaction parsing
  packages/sync-server/src/app-gocardless/banks/boursobank_bousfrppxxx.js
  packages/sync-server/src/app-gocardless/banks/tests/boursobank_bousfrppxxx.spec.js
  upcoming-release-notes/5202.md
Labels: :white_check_mark: approved

#5203 improve compatibility with OFX/QFX files
  packages/loot-core/src/server/transactions/import/ofx2json.ts
  upcoming-release-notes/5203.md
Labels: :white_check_mark: approved

#5205 Revert "Mobile running balance"
  packages/desktop-client/src/components/mobile/accounts/AccountTransactions.tsx
  packages/desktop-client/src/components/mobile/budget/CategoryTransactions.tsx
  packages/desktop-client/src/components/mobile/transactions/TransactionList.tsx
  packages/desktop-client/src/components/mobile/transactions/TransactionListItem.tsx
  packages/desktop-client/src/components/mobile/transactions/TransactionListWithBalances.tsx
  packages/desktop-client/src/components/modals/AccountMenuModal.tsx
  packages/desktop-client/src/components/reports/reports/Calendar.tsx
  packages/desktop-client/src/hooks/useAccountPreviewTransactions.ts
  packages/desktop-client/src/modals/modalsSlice.ts
  upcoming-release-notes/4809.md
Labels: :white_check_mark: approved

#5204 Move more `.d.ts` files to `.ts`
  packages/loot-core/package.json
  packages/loot-core/src/platform/server/connection/__mocks__/index.ts
  packages/loot-core/src/platform/server/connection/index-types.ts
  packages/loot-core/src/platform/server/connection/index.api.ts
  packages/loot-core/src/platform/server/connection/index.electron.ts
  packages/loot-core/src/platform/server/connection/index.ts
  packages/loot-core/src/platform/server/fs/index.d.ts
  packages/loot-core/src/platform/server/fs/index.electron.ts
  packages/loot-core/src/platform/server/fs/index.ts
  packages/loot-core/src/platform/server/fs/index.web.test.ts
  packages/loot-core/src/platform/server/fs/index.web.ts
  packages/loot-core/src/platform/server/fs/path-join.d.ts
  packages/loot-core/src/platform/server/fs/path-join.ts
  packages/loot-core/src/platform/server/fs/shared.ts
  packages/loot-core/src/platform/server/sqlite/index.d.ts
  packages/loot-core/src/platform/server/sqlite/index.ts
  packages/loot-core/src/platform/server/sqlite/index.web.ts
  packages/loot-core/src/server/importers/ynab4-types.d.ts
  packages/loot-core/src/server/importers/ynab4-types.ts
  packages/loot-core/src/server/importers/ynab4.ts
  packages/loot-core/src/server/importers/ynab5-types.d.ts
  packages/loot-core/src/server/importers/ynab5-types.ts
  packages/loot-core/src/server/importers/ynab5.ts
  packages/loot-core/src/types/prefs.ts
  upcoming-release-notes/5204.md
  yarn.lock
Labels: :white_check_mark: approved

#5206 🌍 mark titlebar strings for translation
  packages/desktop-client/e2e/schedules.test.ts-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-10-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.ts-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-11-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.ts-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-12-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.ts-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-13-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.ts-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-14-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.ts-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-15-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.ts-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-4-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.ts-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-5-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.ts-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-6-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.ts-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-7-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.ts-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-8-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.ts-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-9-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.ts-snapshots/Transactions-creates-a-split-test-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.ts-snapshots/Transactions-creates-a-split-test-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.ts-snapshots/Transactions-creates-a-split-test-transaction-3-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.ts-snapshots/Transactions-creates-a-transfer-test-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.ts-snapshots/Transactions-creates-a-transfer-test-transaction-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.ts-snapshots/Transactions-creates-a-transfer-test-transaction-3-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.ts-snapshots/Transactions-creates-a-transfer-test-transaction-4-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.ts-snapshots/Transactions-creates-a-transfer-test-transaction-5-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.ts-snapshots/Transactions-creates-a-transfer-test-transaction-6-chromium-linux.png
  packages/desktop-client/src/components/Titlebar.tsx
  upcoming-release-notes/5206.md
Labels: :white_check_mark: approved

#5213 Prevent forks from running nightly worfkflows
  .github/workflows/publish-nightly-npm-packages.yml
  upcoming-release-notes/5213.md
Labels: :white_check_mark: approved

#5246 Update links pointing to /budgeting/users/.
  packages/desktop-client/src/components/admin/UserAccess/UserAccess.tsx
  packages/desktop-client/src/components/admin/UserDirectory/UserDirectory.tsx
  upcoming-release-notes/5246.md
Labels: :white_check_mark: approved

#5244 Added a gocardless bank parser for Raiffeisen AT bank
  packages/sync-server/src/app-gocardless/banks/raiffeisen_at_rzbaatww.js
  packages/sync-server/src/app-gocardless/banks/tests/raiffeisen_at_rzbaatww.spec.js
  upcoming-release-notes/5244.md
Labels: :white_check_mark: approved

#5220 fix: reapply thousand separators before passing input to appendDecimals
  packages/desktop-client/src/components/mobile/transactions/FocusableAmountInput.tsx
  packages/desktop-client/src/components/util/AmountInput.tsx
  packages/loot-core/src/shared/util.ts
  upcoming-release-notes/5220.md
Labels: :white_check_mark: approved

#5253 Fix switching budget type requiring hard reload to take effect
  packages/desktop-client/src/components/settings/BudgetTypeSettings.tsx
  upcoming-release-notes/5253.md
Labels: :white_check_mark: approved, AI generated

#5251 fix: Tracking budget income budget fields missing in mobile view
  packages/desktop-client/src/components/mobile/budget/BalanceCell.tsx
  packages/desktop-client/src/components/mobile/budget/IncomeCategoryListItem.tsx
  upcoming-release-notes/5251.md
Labels: :white_check_mark: approved
