Repository actualbudget/actual, pull requests merged in 2025-09, with the labels that each got.

#5622 Fix range calculator on the MonthPicker component
  packages/desktop-client/src/components/budget/MonthPicker.tsx
  upcoming-release-notes/5622.md
Labels: :white_check_mark: approved

#5688 Add Romanian and Moldovan currency
  packages/desktop-client/src/components/settings/Currency.tsx
  packages/loot-core/src/shared/currencies.ts
  upcoming-release-notes/5688.md
Labels: :white_check_mark: approved

#5685 [Maintenance] Remove usage of a raw variable in AccountAutocomplete component
  packages/desktop-client/src/components/autocomplete/AccountAutocomplete.tsx
  upcoming-release-notes/5685.md
Labels: :white_check_mark: approved

#5690 Optimize usage of useScrollListener and useTransactionsSearch
  packages/desktop-client/src/components/ScrollProvider.tsx
  packages/desktop-client/src/components/mobile/MobileNavTabs.tsx
  packages/desktop-client/src/components/mobile/transactions/TransactionList.tsx
  packages/desktop-client/src/hooks/useTransactionsSearch.ts
  upcoming-release-notes/5690.md
Labels: :white_check_mark: approved

#5584 Introduction of APIs to handle Schedule + a bit more.
  packages/api/methods.test.ts
  packages/api/methods.ts
  packages/loot-core/src/server/api-models.ts
  packages/loot-core/src/server/api.ts
  packages/loot-core/src/types/api-handlers.ts
  upcoming-release-notes/5584.md
Labels: :mag: ready for review

#5414 Schedules with the same amount and date are now handled properly
  packages/desktop-client/e2e/schedules.test.ts
  packages/desktop-client/e2e/schedules.test.ts-snapshots/Schedules-creates-a-full-list-of-schedules-1-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.ts-snapshots/Schedules-creates-a-full-list-of-schedules-2-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.ts-snapshots/Schedules-creates-a-full-list-of-schedules-3-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.ts-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-13-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.ts-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-14-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.ts-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-15-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.ts-snapshots/Schedules-creates-two-new-schedules-posts-both-transactions-and-later-completes-one-1-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.ts-snapshots/Schedules-creates-two-new-schedules-posts-both-transactions-and-later-completes-one-10-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.ts-snapshots/Schedules-creates-two-new-schedules-posts-both-transactions-and-later-completes-one-11-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.ts-snapshots/Schedules-creates-two-new-schedules-posts-both-transactions-and-later-completes-one-12-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.ts-snapshots/Schedules-creates-two-new-schedules-posts-both-transactions-and-later-completes-one-13-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.ts-snapshots/Schedules-creates-two-new-schedules-posts-both-transactions-and-later-completes-one-14-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.ts-snapshots/Schedules-creates-two-new-schedules-posts-both-transactions-and-later-completes-one-15-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.ts-snapshots/Schedules-creates-two-new-schedules-posts-both-transactions-and-later-completes-one-16-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.ts-snapshots/Schedules-creates-two-new-schedules-posts-both-transactions-and-later-completes-one-17-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.ts-snapshots/Schedules-creates-two-new-schedules-posts-both-transactions-and-later-completes-one-18-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.ts-snapshots/Schedules-creates-two-new-schedules-posts-both-transactions-and-later-completes-one-19-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.ts-snapshots/Schedules-creates-two-new-schedules-posts-both-transactions-and-later-completes-one-2-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.ts-snapshots/Schedules-creates-two-new-schedules-posts-both-transactions-and-later-completes-one-20-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.ts-snapshots/Schedules-creates-two-new-schedules-posts-both-transactions-and-later-completes-one-21-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.ts-snapshots/Schedules-creates-two-new-schedules-posts-both-transactions-and-later-completes-one-3-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.ts-snapshots/Schedules-creates-two-new-schedules-posts-both-transactions-and-later-completes-one-4-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.ts-snapshots/Schedules-creates-two-new-schedules-posts-both-transactions-and-later-completes-one-5-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.ts-snapshots/Schedules-creates-two-new-schedules-posts-both-transactions-and-later-completes-one-6-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.ts-snapshots/Schedules-creates-two-new-schedules-posts-both-transactions-and-later-completes-one-7-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.ts-snapshots/Schedules-creates-two-new-schedules-posts-both-transactions-and-later-completes-one-8-chromium-linux.png
  packages/desktop-client/e2e/schedules.test.ts-snapshots/Schedules-creates-two-new-schedules-posts-both-transactions-and-later-completes-one-9-chromium-linux.png
  packages/desktop-client/src/components/transactions/TransactionsTable.tsx
  packages/loot-core/src/server/schedules/app.ts
  packages/loot-core/src/server/transactions/transaction-rules.ts
  upcoming-release-notes/5414.md
Labels: :white_check_mark: approved

#5752 fix scrolling inside modal with an input that autofocuses
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-checks-that-clicking--14404-in-the-page-header-opens-the-month-menu-modal-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-checks-that-clicking--321fd-ed-amount-opens-the-budget-summary-menu-modal-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-checks-that-clicking--4bb70-ed-amount-opens-the-budget-summary-menu-modal-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-checks-that-clicking--6ab37-roup-name-opens-the-category-group-menu-modal-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-checks-that-clicking--94a79-roup-name-opens-the-category-group-menu-modal-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-checks-that-clicking--94a85-ed-amount-opens-the-budget-summary-menu-modal-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-checks-that-clicking--9e6aa-in-the-page-header-opens-the-budget-page-menu-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-checks-that-clicking--bbde3-roup-name-opens-the-category-group-menu-modal-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-checks-that-clicking--bed18-in-the-page-header-opens-the-month-menu-modal-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-checks-that-clicking--ceb3a-in-the-page-header-opens-the-month-menu-modal-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-checks-that-clicking--d270d-in-the-page-header-opens-the-budget-page-menu-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-checks-that-clicking--fdd57-in-the-page-header-opens-the-budget-page-menu-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-checks-that-clicking-the-balance-cell-opens-the-balance-menu-modal-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-checks-that-clicking-the-balance-cell-opens-the-balance-menu-modal-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-checks-that-clicking-the-balance-cell-opens-the-balance-menu-modal-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-checks-that-clicking-the-budgeted-cell-opens-the-budget-menu-modal-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-checks-that-clicking-the-budgeted-cell-opens-the-budget-menu-modal-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-checks-that-clicking-the-budgeted-cell-opens-the-budget-menu-modal-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-checks-that-clicking-the-category-name-opens-the-category-menu-modal-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-checks-that-clicking-the-category-name-opens-the-category-menu-modal-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-checks-that-clicking-the-category-name-opens-the-category-menu-modal-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--0ba04-nt-amount-opens-the-budget-summary-menu-modal-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--1ce6d-nt-amount-opens-the-budget-summary-menu-modal-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--42062-in-the-page-header-opens-the-month-menu-modal-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--49fb6-in-the-page-header-opens-the-month-menu-modal-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--5f098-roup-name-opens-the-category-group-menu-modal-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--929be-roup-name-opens-the-category-group-menu-modal-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--a3783-in-the-page-header-opens-the-budget-page-menu-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--a8b5e-in-the-page-header-opens-the-budget-page-menu-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--b1562-in-the-page-header-opens-the-month-menu-modal-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--dc927-roup-name-opens-the-category-group-menu-modal-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--f224f-nt-amount-opens-the-budget-summary-menu-modal-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--f8a19-in-the-page-header-opens-the-budget-page-menu-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking-the-balance-cell-opens-the-balance-menu-modal-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking-the-balance-cell-opens-the-balance-menu-modal-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking-the-balance-cell-opens-the-balance-menu-modal-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking-the-budgeted-cell-opens-the-budget-menu-modal-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking-the-budgeted-cell-opens-the-budget-menu-modal-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking-the-budgeted-cell-opens-the-budget-menu-modal-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking-the-category-name-opens-the-category-menu-modal-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking-the-category-name-opens-the-category-menu-modal-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking-the-category-name-opens-the-category-menu-modal-3-chromium-linux.png
  packages/desktop-client/src/components/common/Modal.tsx
  upcoming-release-notes/5752.md
Labels: :white_check_mark: approved

#5753 feat(reports): extend report end date to the latest transaction date
  packages/desktop-client/src/components/reports/Header.tsx
  packages/desktop-client/src/components/reports/ReportSidebar.tsx
  packages/desktop-client/src/components/reports/getLiveRange.ts
  packages/desktop-client/src/components/reports/reportRanges.ts
  packages/desktop-client/src/components/reports/reports/Calendar.tsx
  packages/desktop-client/src/components/reports/reports/CashFlow.tsx
  packages/desktop-client/src/components/reports/reports/CustomReport.tsx
  packages/desktop-client/src/components/reports/reports/CustomReportListCards.tsx
  packages/desktop-client/src/components/reports/reports/GetCardData.tsx
  packages/desktop-client/src/components/reports/reports/NetWorth.tsx
  packages/desktop-client/src/components/reports/reports/Spending.tsx
  packages/desktop-client/src/components/reports/reports/Summary.tsx
  packages/loot-core/src/server/transactions/app.ts
  upcoming-release-notes/5753.md
Labels: :white_check_mark: approved

#5758 add a 'dryRun' option to transactions import API
  packages/api/methods.ts
  upcoming-release-notes/5758.md
Labels: API, :white_check_mark: approved

#5761 Avoid repeated calls to payee.find in useDisplayPayee.ts
  packages/desktop-client/src/components/transactions/TransactionsTable.test.tsx
  packages/desktop-client/src/hooks/useDisplayPayee.ts
  packages/desktop-client/src/hooks/usePayees.ts
  upcoming-release-notes/5761.md
Labels: :white_check_mark: approved

#5767 Create mobile payees list page
  packages/desktop-client/src/components/FinancesApp.tsx
  packages/desktop-client/src/components/mobile/MobileNavTabs.tsx
  packages/desktop-client/src/components/mobile/payees/MobilePayeesPage.tsx
  packages/desktop-client/src/components/mobile/payees/PayeesList.tsx
  packages/desktop-client/src/components/mobile/payees/PayeesListItem.tsx
  packages/desktop-client/src/components/responsive/narrow.ts
  packages/desktop-client/src/components/responsive/wide.ts
  upcoming-release-notes/5767.md
Labels: :white_check_mark: approved

#5777 [WIP] [FIX] Translate Schedule '(No payee)'
  packages/desktop-client/src/components/transactions/TransactionsTable.tsx
  upcoming-release-notes/5777.md
Labels: :construction: WIP

#5780 Frontend plugins Support [1/10]: CORS proxy
  packages/sync-server/package.json
  packages/sync-server/src/app-cors-proxy.js
  packages/sync-server/src/app-cors-proxy.test.js
  packages/sync-server/src/app.ts
  packages/sync-server/src/load-config.js
  upcoming-release-notes/5780.md
  yarn.lock
Labels: :white_check_mark: approved

#5782 Fix token expiration parsing
  packages/sync-server/src/load-config.js
  packages/sync-server/src/load-config.test.js
  upcoming-release-notes/5782.md
Labels: :white_check_mark: approved

#5790 fix live report time ranges
  packages/desktop-client/src/components/reports/reportRanges.ts
  packages/desktop-client/src/components/reports/reports/Calendar.tsx
  packages/desktop-client/src/components/reports/reports/CalendarCard.tsx
  packages/desktop-client/src/components/reports/reports/CashFlow.tsx
  packages/desktop-client/src/components/reports/reports/CashFlowCard.tsx
  packages/desktop-client/src/components/reports/reports/NetWorth.tsx
  packages/desktop-client/src/components/reports/reports/NetWorthCard.tsx
  packages/desktop-client/src/components/reports/reports/SpendingCard.tsx
  packages/desktop-client/src/components/reports/reports/Summary.tsx
  packages/desktop-client/src/components/reports/reports/SummaryCard.tsx
  upcoming-release-notes/5790.md
Labels: :white_check_mark: approved

#5791 replace deprecated function in count points script
  .github/scripts/count-points.mjs
  upcoming-release-notes/5791.md
Labels: :white_check_mark: approved

#5803 Mobile Payees - add back padding around searchbar
  packages/desktop-client/src/components/mobile/payees/PayeesList.tsx
  upcoming-release-notes/5803.md
Labels: :white_check_mark: approved

#5817 fix payee autocomplete hovering randomly
  packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.tsx
  upcoming-release-notes/5817.md
Labels: :white_check_mark: approved
