Repository actualbudget/actual, pull requests merged in 2025-05, with the labels that each got.

#4787 Rename AQL module's `runQuery` function to `aqlQuery` to disambiguate with DB module's `runQuery` function + AQL types
  packages/api/methods.ts
  packages/desktop-client/src/components/accounts/Account.tsx
  packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
  packages/desktop-client/src/components/modals/EditRuleModal.jsx
  packages/desktop-client/src/components/reports/spreadsheets/calendar-spreadsheet.ts
  packages/desktop-client/src/components/reports/spreadsheets/custom-spreadsheet.ts
  packages/desktop-client/src/components/reports/spreadsheets/grouped-spreadsheet.ts
  packages/desktop-client/src/components/reports/spreadsheets/net-worth-spreadsheet.ts
  packages/desktop-client/src/components/reports/spreadsheets/spending-spreadsheet.ts
  packages/desktop-client/src/components/reports/spreadsheets/summary-spreadsheet.ts
  packages/desktop-client/src/components/reports/util.ts
  packages/desktop-client/src/components/schedules/DiscoverSchedules.tsx
  packages/desktop-client/src/components/schedules/ScheduleDetails.tsx
  packages/desktop-client/src/hooks/useTransactionBatchActions.ts
  packages/desktop-client/src/index.tsx
  packages/loot-core/src/client/query-helpers.test.ts
  packages/loot-core/src/client/query-helpers.ts
  packages/loot-core/src/mocks/budget.ts
  packages/loot-core/src/server/accounts/sync.ts
  packages/loot-core/src/server/api.ts
  packages/loot-core/src/server/aql/compiler.ts
  packages/loot-core/src/server/aql/exec.test.ts
  packages/loot-core/src/server/aql/exec.ts
  packages/loot-core/src/server/aql/index.ts
  packages/loot-core/src/server/aql/schema/executors.test.ts
  packages/loot-core/src/server/aql/schema/executors.ts
  packages/loot-core/src/server/aql/schema/run-query.ts
  packages/loot-core/src/server/budget/app.ts
  packages/loot-core/src/server/budget/base.ts
  packages/loot-core/src/server/dashboard/app.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/server/schedules/app.test.ts
  packages/loot-core/src/server/schedules/app.ts
  packages/loot-core/src/server/schedules/find-schedules.ts
  packages/loot-core/src/server/spreadsheet/spreadsheet.ts
  packages/loot-core/src/server/tools/app.ts
  packages/loot-core/src/server/transactions/app.ts
  packages/loot-core/src/server/transactions/export/export-to-csv.ts
  packages/loot-core/src/server/transactions/transaction-rules.test.ts
  upcoming-release-notes/4787.md
Labels: :white_check_mark: approved

#4933 Use the latest release tag instead of the latest tag for version checks
  packages/desktop-client/src/util/versions.ts
  upcoming-release-notes/4933.md
Labels: :mag: ready for review, :white_check_mark: approved

#4766 Payees functional tests
  packages/desktop-client/e2e/page-models/navigation.ts
  packages/desktop-client/e2e/page-models/payees-page.ts
  packages/desktop-client/e2e/payees.test.ts
  packages/desktop-client/e2e/payees.test.ts-snapshots/Payees-checks-the-payees-page-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/payees.test.ts-snapshots/Payees-checks-the-payees-page-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/payees.test.ts-snapshots/Payees-checks-the-payees-page-visuals-3-chromium-linux.png
  packages/desktop-client/e2e/payees.test.ts-snapshots/Payees-checks-the-payees-page-visuals-4-chromium-linux.png
  packages/desktop-client/e2e/payees.test.ts-snapshots/Payees-checks-the-payees-page-visuals-5-chromium-linux.png
  packages/desktop-client/e2e/payees.test.ts-snapshots/Payees-checks-the-payees-page-visuals-6-chromium-linux.png
  upcoming-release-notes/4766.md
Labels: :mag: ready for review, :white_check_mark: approved

#4942 Fix lint error accidentally pushed to master
  packages/desktop-client/src/components/settings/AuthSettings.tsx
  upcoming-release-notes/4942.md
Labels: :mag: ready for review, :white_check_mark: approved

#4953 🐛 Fixing docker edge
  packages/sync-server/src/migrations.js
  upcoming-release-notes/4953.md
Labels: :white_check_mark: approved

#4943 Deduplicate vite versions
  package.json
  packages/desktop-client/package.json
  upcoming-release-notes/4943.md
  yarn.lock
Labels: :white_check_mark: approved

#4810 Add basic modal for budget automations
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/budget/goals/BudgetAutomation.tsx
  packages/desktop-client/src/components/budget/goals/BudgetAutomationEditor.tsx
  packages/desktop-client/src/components/budget/goals/BudgetAutomationReadOnly.tsx
  packages/desktop-client/src/components/budget/goals/actions.ts
  packages/desktop-client/src/components/budget/goals/constants.ts
  packages/desktop-client/src/components/budget/goals/editor/HistoricalAutomation.tsx
  packages/desktop-client/src/components/budget/goals/editor/HistoricalAutomationReadOnly.tsx
  packages/desktop-client/src/components/budget/goals/editor/PercentageAutomation.tsx
  packages/desktop-client/src/components/budget/goals/editor/PercentageAutomationReadOnly.tsx
  packages/desktop-client/src/components/budget/goals/editor/ScheduleAutomation.tsx
  packages/desktop-client/src/components/budget/goals/editor/ScheduleAutomationReadOnly.tsx
  packages/desktop-client/src/components/budget/goals/editor/SimpleAutomation.tsx
  packages/desktop-client/src/components/budget/goals/editor/SimpleAutomationReadOnly.tsx
  packages/desktop-client/src/components/budget/goals/editor/WeekAutomation.tsx
  packages/desktop-client/src/components/budget/goals/editor/WeekAutomationReadOnly.tsx
  packages/desktop-client/src/components/budget/goals/reducer.ts
  packages/desktop-client/src/components/budget/goals/useBudgetAutomationCategories.ts
  packages/desktop-client/src/components/modals/BudgetAutomationsModal.tsx
  upcoming-release-notes/4810.md
Labels: :white_check_mark: approved

#4917 Fixed graphical bug in monthly spending report
  packages/desktop-client/src/components/reports/reports/Spending.tsx
  upcoming-release-notes/4917.md
Labels: :white_check_mark: approved

#4911 Ofx parsing dates incorrectly
  packages/loot-core/src/server/transactions/import/ofx2json.ts
  upcoming-release-notes/4911.md
Labels: :white_check_mark: approved

#4908 Fix title first null undefined
  packages/loot-core/src/shared/util.test.ts
  packages/loot-core/src/shared/util.ts
  upcoming-release-notes/4908.md
Labels: :white_check_mark: approved

#4954 🐛 Sync server - resolving the user-files and server-files to an absolute dir
  packages/sync-server/bin/actual-server.js
  packages/sync-server/src/account-db.js
  packages/sync-server/src/util/paths.js
  upcoming-release-notes/4954.md
Labels: :white_check_mark: approved

#4968 🐛 Fix sync server build not copying sql files over
  packages/sync-server/package.json
  packages/sync-server/src/load-config.js
  upcoming-release-notes/4968.md
Labels: :white_check_mark: approved

#4864 Stabilize electron build directory paths
  packages/desktop-electron/index.ts
  packages/desktop-electron/package.json
  packages/desktop-electron/tsconfig.dist.json
  upcoming-release-notes/4864.md
Labels: :white_check_mark: approved

#4923 🐛 fixed scrollbar being impossible to grab
  bin/release-note-generator.ts
  packages/desktop-client/src/style/styles.ts
  upcoming-release-notes/4923.md
Labels: :white_check_mark: approved

#4869 invert most of seb kort credit card transactions
  packages/sync-server/src/app-gocardless/banks/seb_kort_bank_ab.js
  upcoming-release-notes/4869.md
Labels: :white_check_mark: approved

#4958 Add BoursoBank GoCardless Integration
  packages/sync-server/src/app-gocardless/bank-factory.js
  packages/sync-server/src/app-gocardless/banks/boursobank_bousfrppxxx.js
  packages/sync-server/src/app-gocardless/banks/tests/boursobank_bousfrppxxx.spec.js
  upcoming-release-notes/4958.md
Labels: :white_check_mark: approved

#4970 Add Abanca to the list of banks with limited history
  packages/sync-server/src/app-gocardless/bank-factory.js
  upcoming-release-notes/4970.md
Labels: :white_check_mark: approved

#4949 [Mobile] 🐛 Fix widget order
  packages/desktop-client/src/components/reports/Overview.tsx
  upcoming-release-notes/4949.md
Labels: :white_check_mark: approved

#4882 Tests for goal templates
  packages/loot-core/src/server/budget/categoryTemplate.test.ts
  packages/loot-core/src/server/budget/categoryTemplate.ts
  packages/loot-core/src/server/budget/types/templates.d.ts
  upcoming-release-notes/4882.md
Labels: :white_check_mark: approved

#4889 Split transactions repair tool to remove categories from parent transactions + prevent adding/updating parent transactions with categories
  packages/desktop-client/src/components/settings/RepairTransactions.tsx
  packages/loot-core/src/server/tools/app.ts
  packages/loot-core/src/server/transactions/index.ts
  upcoming-release-notes/4889.md
Labels: :white_check_mark: approved

#4815 Add upcoming/missed/due schedules indicator on budget table (based on category schedule templates)
  packages/desktop-client/src/components/budget/BalanceWithCarryover.tsx
  packages/desktop-client/src/components/budget/BudgetTable.tsx
  packages/desktop-client/src/components/budget/SidebarCategory.tsx
  packages/desktop-client/src/components/budget/envelope/EnvelopeBudgetComponents.tsx
  packages/desktop-client/src/components/budget/tracking/TrackingBudgetComponents.tsx
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  packages/desktop-client/src/components/mobile/budget/CategoryTransactions.tsx
  packages/desktop-client/src/components/mobile/budget/ExpenseCategoryListItem.tsx
  packages/desktop-client/src/components/mobile/budget/SpentCell.tsx
  packages/desktop-client/src/components/modals/EnvelopeBalanceMenuModal.tsx
  packages/desktop-client/src/hooks/useCategoryPreviewTransactions.ts
  packages/desktop-client/src/hooks/useCategoryScheduleGoalTemplateIndicator.ts
  packages/desktop-client/src/hooks/useCategoryScheduleGoalTemplates.ts
  packages/loot-core/src/shared/months.ts
  packages/loot-core/src/types/models/category.ts
  upcoming-release-notes/4815.md
Labels: :white_check_mark: approved

#4818 Move loot-core/client/budgets code over to desktop-client package
  packages/desktop-client/src/budgets/budgetsSlice.ts
  packages/desktop-client/src/components/App.tsx
  packages/desktop-client/src/components/LoggedInUser.tsx
  packages/desktop-client/src/components/manager/BudgetFileSelection.tsx
  packages/desktop-client/src/components/manager/ConfigServer.tsx
  packages/desktop-client/src/components/manager/WelcomeScreen.tsx
  packages/desktop-client/src/components/manager/subscribe/Bootstrap.tsx
  packages/desktop-client/src/components/modals/CreateEncryptionKeyModal.tsx
  packages/desktop-client/src/components/modals/LoadBackupModal.tsx
  packages/desktop-client/src/components/modals/OpenIDEnableModal.tsx
  packages/desktop-client/src/components/modals/OutOfSyncMigrationsModal.tsx
  packages/desktop-client/src/components/modals/PasswordEnableModal.tsx
  packages/desktop-client/src/components/modals/TransferOwnership.tsx
  packages/desktop-client/src/components/modals/manager/DeleteFileModal.tsx
  packages/desktop-client/src/components/modals/manager/DuplicateFileModal.tsx
  packages/desktop-client/src/components/modals/manager/FilesSettingsModal.tsx
  packages/desktop-client/src/components/modals/manager/ImportActualModal.tsx
  packages/desktop-client/src/components/modals/manager/ImportYNAB4Modal.tsx
  packages/desktop-client/src/components/modals/manager/ImportYNAB5Modal.tsx
  packages/desktop-client/src/components/settings/index.tsx
  packages/desktop-client/src/components/sidebar/BudgetName.tsx
  packages/desktop-client/src/global-events.ts
  packages/desktop-client/src/index.tsx
  packages/loot-core/src/client/shared-listeners.ts
  packages/loot-core/src/client/store/index.ts
  packages/loot-core/src/client/store/mock.ts
  packages/loot-core/src/client/users/usersSlice.ts
  upcoming-release-notes/4818.md
Labels: :white_check_mark: approved

#4897 Replacing Actuator with our own implementation
  packages/sync-server/package.json
  packages/sync-server/src/app.ts
  upcoming-release-notes/4897.md
  yarn.lock
Labels: :white_check_mark: approved

#4978 change minimum version of Node.js to version 20
  .github/actions/setup/action.yml
  .github/workflows/check.yml
  .github/workflows/issues-feature-implemented.yml
  .github/workflows/publish-npm-packages.yml
  .nvmrc
  package.json
  packages/api/package.json
  upcoming-release-notes/4978.md
Labels: :white_check_mark: approved

#4935 [Mobile] 🐛 Fix viewing pie/donut charts on mobile
  packages/desktop-client/src/components/reports/graphs/DonutGraph.tsx
  upcoming-release-notes/4935.md
Labels: :white_check_mark: approved

#4980 increase OpenID timeout
  packages/sync-server/src/accounts/openid.js
  upcoming-release-notes/4980.md
Labels: :white_check_mark: approved

#4914 Fix new transactions account notes not clearing
  packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
  upcoming-release-notes/4914.md
Labels: :white_check_mark: approved

#4910 Inconsistent date update mobile new transaction
  packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
  upcoming-release-notes/4910.md
Labels: :white_check_mark: approved

#4987 Add option to calculate running balances in useTransactions hook
  packages/loot-core/src/client/data-hooks/transactions.ts
  packages/loot-core/src/types/models/transaction.ts
  upcoming-release-notes/4987.md
Labels: :white_check_mark: approved

#4893 [WIP] Add DNB (DNB_DNBANOKK) to banks with limited history
  packages/sync-server/src/app-gocardless/bank-factory.js
Labels: Stale, :construction: WIP

#4821 Move loot-core/client/prefs code over to desktop-client package
  packages/desktop-client/src/app/appSlice.ts
  packages/desktop-client/src/budgets/budgetsSlice.ts
  packages/desktop-client/src/components/App.tsx
  packages/desktop-client/src/components/modals/CreateEncryptionKeyModal.tsx
  packages/desktop-client/src/components/settings/index.tsx
  packages/desktop-client/src/global-events.ts
  packages/desktop-client/src/hooks/useGlobalPref.ts
  packages/desktop-client/src/hooks/useMetadataPref.ts
  packages/desktop-client/src/hooks/useSyncedPref.ts
  packages/desktop-client/src/hooks/useSyncedPrefs.ts
  packages/desktop-client/src/index.tsx
  packages/desktop-client/src/prefs/prefsSlice.ts
  packages/loot-core/src/client/shared-listeners.ts
  packages/loot-core/src/client/store/index.ts
  packages/loot-core/src/client/store/mock.ts
  packages/loot-core/src/client/users/usersSlice.ts
  upcoming-release-notes/4821.md
Labels: :white_check_mark: approved

#4992 Update react-spring to v10.0.0
  packages/desktop-client/package.json
  packages/desktop-client/src/components/AppBackground.tsx
  packages/desktop-client/src/components/BankSyncStatus.tsx
  packages/desktop-client/src/components/Notifications.tsx
  packages/desktop-client/src/components/budget/BudgetSummaries.tsx
  packages/desktop-client/src/components/mobile/MobileNavTabs.tsx
  packages/desktop-client/src/components/reports/reports/Calendar.tsx
  upcoming-release-notes/4992.md
  yarn.lock
Labels: :sparkles: merged

#4870 :electron: Server config ui
  packages/desktop-client/src/components/manager/ConfigServer.tsx
  packages/desktop-electron/e2e/__screenshots__/onboarding.test.ts/Onboarding-checks-the-page-visuals-1-linux.png
  packages/desktop-electron/index.ts
  upcoming-release-notes/4870.md
Labels: :white_check_mark: approved

#4996 Fix pipeline build
  packages/desktop-client/src/components/manager/ConfigServer.tsx
Labels: :mag: ready for review

#4995 Fix prefsSlice import
  packages/desktop-client/src/components/manager/ConfigServer.tsx
  upcoming-release-notes/4995.md
Labels: :white_check_mark: approved

#4822 Move loot-core/client/queries code over to desktop-client package
  packages/desktop-client/src/accounts/accountsSlice.ts
  packages/desktop-client/src/components/ManageRules.tsx
  packages/desktop-client/src/components/accounts/Account.tsx
  packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.tsx
  packages/desktop-client/src/components/budget/index.tsx
  packages/desktop-client/src/components/mobile/accounts/AccountTransactions.tsx
  packages/desktop-client/src/components/mobile/budget/ExpenseCategoryList.tsx
  packages/desktop-client/src/components/mobile/budget/ExpenseGroupList.tsx
  packages/desktop-client/src/components/mobile/budget/IncomeCategoryList.tsx
  packages/desktop-client/src/components/mobile/budget/index.tsx
  packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
  packages/desktop-client/src/components/modals/CloseAccountModal.tsx
  packages/desktop-client/src/components/modals/CreateLocalAccountModal.tsx
  packages/desktop-client/src/components/modals/EditRuleModal.jsx
  packages/desktop-client/src/components/modals/ImportTransactionsModal/ImportTransactionsModal.jsx
  packages/desktop-client/src/components/payees/ManagePayeesWithData.tsx
  packages/desktop-client/src/components/rules/ScheduleValue.tsx
  packages/desktop-client/src/components/schedules/ScheduleDetails.tsx
  packages/desktop-client/src/components/sidebar/Account.tsx
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  packages/desktop-client/src/global-events.ts
  packages/desktop-client/src/hooks/useAccounts.ts
  packages/desktop-client/src/hooks/useCategories.ts
  packages/desktop-client/src/hooks/usePayees.ts
  packages/desktop-client/src/index.tsx
  packages/desktop-client/src/queries/queriesSlice.ts
  packages/loot-core/src/client/shared-listeners.ts
  packages/loot-core/src/client/store/index.ts
  packages/loot-core/src/client/store/mock.ts
  upcoming-release-notes/4822.md
Labels: :white_check_mark: approved

#4997 Remove duplicate import
  packages/desktop-client/src/components/manager/ConfigServer.tsx
Labels: :white_check_mark: approved

#4823 Move loot-core/client/users code over to desktop-client package
  packages/desktop-client/src/budgets/budgetsSlice.ts
  packages/desktop-client/src/components/App.tsx
  packages/desktop-client/src/components/LoggedInUser.tsx
  packages/desktop-client/src/components/admin/UserAccess/UserAccessRow.tsx
  packages/desktop-client/src/components/admin/UserDirectory/UserDirectory.tsx
  packages/desktop-client/src/components/manager/BudgetFileSelection.tsx
  packages/desktop-client/src/components/manager/ConfigServer.tsx
  packages/desktop-client/src/components/manager/ManagementApp.tsx
  packages/desktop-client/src/components/manager/subscribe/Login.tsx
  packages/desktop-client/src/components/manager/subscribe/OpenIdCallback.ts
  packages/desktop-client/src/components/modals/EditAccess.tsx
  packages/desktop-client/src/components/modals/EditUser.tsx
  packages/desktop-client/src/index.tsx
  packages/desktop-client/src/modals/modalsSlice.ts
  packages/desktop-client/src/users/usersSlice.ts
  packages/loot-core/src/client/shared-listeners.ts
  packages/loot-core/src/client/store/index.ts
  packages/loot-core/src/client/store/mock.ts
  upcoming-release-notes/4823.md
Labels: :white_check_mark: approved

#4827 Move loot-core/client/store and loot-core/client/redux code over to desktop-client package
  packages/desktop-client/src/accounts/accountsSlice.ts
  packages/desktop-client/src/app/appSlice.ts
  packages/desktop-client/src/budgets/budgetsSlice.ts
  packages/desktop-client/src/components/accounts/Account.tsx
  packages/desktop-client/src/global-events.ts
  packages/desktop-client/src/gocardless.ts
  packages/desktop-client/src/index.tsx
  packages/desktop-client/src/modals/modalsSlice.ts
  packages/desktop-client/src/prefs/prefsSlice.ts
  packages/desktop-client/src/queries/queriesSlice.ts
  packages/desktop-client/src/redux/index.ts
  packages/desktop-client/src/redux/mock.tsx
  packages/desktop-client/src/redux/store.ts
  packages/desktop-client/src/setupTests.js
  packages/desktop-client/src/users/usersSlice.ts
  packages/loot-core/src/client/redux.ts
  packages/loot-core/src/client/redux/index.ts
  packages/loot-core/src/client/shared-listeners.ts
  packages/loot-core/src/client/store/mock.ts
  upcoming-release-notes/4827.md
Labels: :white_check_mark: approved

#5002 [WIP] Qif empty lines
  packages/loot-core/src/server/transactions/import/qif2json.ts
  upcoming-release-notes/5002.md
Labels: :construction: WIP

#4828 Move loot-core/client/data-hooks over to desktop-client package
  packages/desktop-client/src/components/ManageRules.tsx
  packages/desktop-client/src/components/accounts/Account.tsx
  packages/desktop-client/src/components/accounts/Balance.tsx
  packages/desktop-client/src/components/autocomplete/FilterAutocomplete.tsx
  packages/desktop-client/src/components/autocomplete/ReportAutocomplete.tsx
  packages/desktop-client/src/components/banksync/EditSyncAccount.tsx
  packages/desktop-client/src/components/budget/BudgetTable.tsx
  packages/desktop-client/src/components/filters/FiltersMenu.jsx
  packages/desktop-client/src/components/mobile/accounts/AccountTransactions.tsx
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  packages/desktop-client/src/components/mobile/budget/CategoryTransactions.tsx
  packages/desktop-client/src/components/mobile/transactions/TransactionListItem.tsx
  packages/desktop-client/src/components/modals/BudgetAutomationsModal.tsx
  packages/desktop-client/src/components/modals/EditRuleModal.jsx
  packages/desktop-client/src/components/modals/ScheduledTransactionMenuModal.tsx
  packages/desktop-client/src/components/reports/Overview.tsx
  packages/desktop-client/src/components/reports/SaveReport.tsx
  packages/desktop-client/src/components/reports/reports/Calendar.tsx
  packages/desktop-client/src/components/reports/reports/CashFlow.tsx
  packages/desktop-client/src/components/reports/reports/CustomReport.tsx
  packages/desktop-client/src/components/reports/reports/NetWorth.tsx
  packages/desktop-client/src/components/reports/reports/Spending.tsx
  packages/desktop-client/src/components/reports/reports/Summary.tsx
  packages/desktop-client/src/components/rules/ScheduleValue.tsx
  packages/desktop-client/src/components/schedules/ScheduleLink.tsx
  packages/desktop-client/src/components/schedules/SchedulesTable.tsx
  packages/desktop-client/src/components/schedules/StatusBadge.tsx
  packages/desktop-client/src/components/schedules/index.tsx
  packages/desktop-client/src/components/transactions/SelectedTransactionsButton.tsx
  packages/desktop-client/src/components/transactions/TransactionMenu.tsx
  packages/desktop-client/src/components/transactions/TransactionsTable.test.tsx
  packages/desktop-client/src/components/transactions/TransactionsTable.tsx
  packages/desktop-client/src/components/util/GenericInput.jsx
  packages/desktop-client/src/hooks/useAccountPreviewTransactions.ts
  packages/desktop-client/src/hooks/useCachedSchedules.tsx
  packages/desktop-client/src/hooks/useCategoryPreviewTransactions.ts
  packages/desktop-client/src/hooks/useCategoryScheduleGoalTemplateIndicator.ts
  packages/desktop-client/src/hooks/useCategoryScheduleGoalTemplates.ts
  packages/desktop-client/src/hooks/useDashboard.ts
  packages/desktop-client/src/hooks/useDisplayPayee.ts
  packages/desktop-client/src/hooks/usePreviewTransactions.ts
  packages/desktop-client/src/hooks/useReport.ts
  packages/desktop-client/src/hooks/useReports.ts
  packages/desktop-client/src/hooks/useRuleConditionFilters.ts
  packages/desktop-client/src/hooks/useSchedules.ts
  packages/desktop-client/src/hooks/useTransactionFilters.ts
  packages/desktop-client/src/hooks/useTransactions.ts
  packages/desktop-client/src/hooks/useTransactionsSearch.ts
  packages/desktop-client/src/hooks/useWidget.ts
  packages/loot-core/src/shared/schedules.ts
  upcoming-release-notes/4828.md
Labels: :white_check_mark: approved

#4912 Allow-return-to-trigger-default-actions
  packages/component-library/package.json
  packages/component-library/src/InitialFocus.ts
  packages/component-library/src/InitialFocus.web.test.tsx
  packages/component-library/vitest.web.config.ts
  packages/desktop-client/src/components/accounts/Header.tsx
  packages/desktop-client/src/components/budget/envelope/CoverMenu.tsx
  packages/desktop-client/src/components/sidebar/Account.tsx
  upcoming-release-notes/4912.md
  yarn.lock
Labels: :white_check_mark: approved

#5008 Make InitialFocus component generic
  packages/component-library/src/InitialFocus.ts
  packages/desktop-client/src/components/budget/envelope/CoverMenu.tsx
  upcoming-release-notes/5008.md
Labels: :white_check_mark: approved

#5011 Set yarn engine version
  package.json
  upcoming-release-notes/5011.md
Labels: :white_check_mark: approved

#5017 remove dependency on ip
  package.json
  upcoming-release-notes/5017.md
  yarn.lock
Labels: :white_check_mark: approved, dependencies

#5018 ⬆️ bump jq
  package.json
  upcoming-release-notes/5018.md
  yarn.lock
Labels: :white_check_mark: approved, dependencies

#5014 ⬆️ upgrade yarn from v4.7.0 to v4.9.1
  .yarn/releases/yarn-4.7.0.cjs
  .yarn/releases/yarn-4.9.1.cjs
  .yarnrc.yml
  package.json
  upcoming-release-notes/5014.md
Labels: :white_check_mark: approved, dependencies

#5015 ⬆️ bump dependency patch versions
  package.json
  packages/api/package.json
  packages/component-library/package.json
  packages/crdt/package.json
  packages/desktop-client/package.json
  packages/desktop-electron/package.json
  packages/eslint-plugin-actual/package.json
  packages/loot-core/package.json
  packages/loot-core/src/platform/server/sqlite/index.electron.ts
  packages/sync-server/package.json
  upcoming-release-notes/5015.md
  yarn.lock
Labels: :white_check_mark: approved, dependencies

#5019 ⬆️ bump adm zip to 0.5.16
  .yarn/patches/adm-zip-npm-0.5.16-4556fea098.patch
  packages/loot-core/package.json
  upcoming-release-notes/5019.md
  yarn.lock
Labels: :white_check_mark: approved, dependencies

#5024 resolve loot-core peer dependency warnings
  packages/desktop-client/package.json
  packages/loot-core/package.json
  upcoming-release-notes/5024.md
  yarn.lock
Labels: :white_check_mark: approved

#5029 ⬆️ upgrade electron dependencies to their newest minor version
  packages/desktop-electron/package.json
  upcoming-release-notes/5029.md
  yarn.lock
Labels: :white_check_mark: approved, dependencies

#5034 Automatically upload to the MS store on release
  .github/workflows/electron-master.yml
  upcoming-release-notes/5034.md
Labels: :white_check_mark: approved

#5027 ⬆️ upgrade react dependencies to their newest minor version
  packages/component-library/package.json
  packages/desktop-client/package.json
  upcoming-release-notes/5027.md
  yarn.lock
Labels: :white_check_mark: approved, dependencies

#4986 Add types to budget template files and some cleanup
  packages/loot-core/src/server/budget/app.ts
  packages/loot-core/src/server/budget/category-template-context.test.ts
  packages/loot-core/src/server/budget/category-template-context.ts
  packages/loot-core/src/server/budget/goal-template.ts
  packages/loot-core/src/server/budget/goaltemplates.ts
  packages/loot-core/src/server/budget/schedule-template.test.ts
  packages/loot-core/src/server/budget/schedule-template.ts
  packages/loot-core/src/server/budget/types/templates.d.ts
  upcoming-release-notes/4986.md
Labels: :white_check_mark: approved

#5038 if BankSyncError is caused by rate limit. display that in toast
  packages/loot-core/src/server/accounts/app.ts
  upcoming-release-notes/5038.md
Labels: :white_check_mark: approved

#5036 Fix category schedule indicators not showing up in budget page
  packages/desktop-client/src/hooks/useCategoryScheduleGoalTemplates.ts
  upcoming-release-notes/5036.md
Labels: :white_check_mark: approved

#4955 Update @actual-app/components/input to be based on react-aria-components Input component
  packages/component-library/src/Input.tsx
  packages/desktop-client/e2e/transactions.test.ts-snapshots/Transactions-creates-a-transfer-test-transaction-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.ts-snapshots/Transactions-creates-a-transfer-test-transaction-3-chromium-linux.png
  packages/desktop-client/src/components/EditablePageHeaderTitle.tsx
  packages/desktop-client/src/components/accounts/Header.tsx
  packages/desktop-client/src/components/accounts/Reconcile.tsx
  packages/desktop-client/src/components/autocomplete/Autocomplete.tsx
  packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.tsx
  packages/desktop-client/src/components/budget/envelope/CoverMenu.tsx
  packages/desktop-client/src/components/budget/envelope/HoldMenu.tsx
  packages/desktop-client/src/components/budget/envelope/TransferMenu.tsx
  packages/desktop-client/src/components/common/Modal.tsx
  packages/desktop-client/src/components/common/Search.tsx
  packages/desktop-client/src/components/filters/FiltersMenu.jsx
  packages/desktop-client/src/components/filters/NameFilter.tsx
  packages/desktop-client/src/components/manager/ConfigServer.tsx
  packages/desktop-client/src/components/manager/subscribe/ConfirmPasswordForm.tsx
  packages/desktop-client/src/components/manager/subscribe/Login.tsx
  packages/desktop-client/src/components/mobile/MobileForms.tsx
  packages/desktop-client/src/components/mobile/transactions/TransactionListWithBalances.tsx
  packages/desktop-client/src/components/modals/CreateEncryptionKeyModal.tsx
  packages/desktop-client/src/components/modals/CreateLocalAccountModal.tsx
  packages/desktop-client/src/components/modals/EditFieldModal.tsx
  packages/desktop-client/src/components/modals/EditUser.tsx
  packages/desktop-client/src/components/modals/FixEncryptionKeyModal.tsx
  packages/desktop-client/src/components/modals/manager/DuplicateFileModal.tsx
  packages/desktop-client/src/components/reports/ReportCardName.tsx
  packages/desktop-client/src/components/reports/SaveReportChoose.tsx
  packages/desktop-client/src/components/reports/SaveReportName.tsx
  packages/desktop-client/src/components/schedules/CustomUpcomingLength.tsx
  packages/desktop-client/src/components/select/DateSelect.tsx
  packages/desktop-client/src/components/select/RecurringSchedulePicker.tsx
  packages/desktop-client/src/components/sidebar/Account.tsx
  packages/desktop-client/src/components/sidebar/BudgetName.tsx
  packages/desktop-client/src/components/table.tsx
  packages/desktop-client/src/components/util/AmountInput.tsx
  packages/desktop-client/src/components/util/GenericInput.jsx
  packages/desktop-client/src/components/util/PercentInput.tsx
  upcoming-release-notes/4955.md
Labels: :white_check_mark: approved

#5041 ⬆️ upgrade date-fns from v2.30.0 -> v4.1.0
  packages/desktop-client/package.json
  packages/desktop-client/src/components/banksync/AccountRow.tsx
  packages/desktop-client/src/components/reports/spreadsheets/cash-flow-spreadsheet.tsx
  packages/desktop-client/src/components/reports/spreadsheets/net-worth-spreadsheet.ts
  packages/desktop-client/src/components/reports/spreadsheets/summary-spreadsheet.ts
  packages/desktop-client/src/components/select/DateSelect.tsx
  packages/desktop-client/src/hooks/useCategoryScheduleGoalTemplateIndicator.ts
  packages/loot-core/package.json
  packages/loot-core/src/shared/months.ts
  packages/loot-core/src/shared/schedules.ts
  packages/loot-core/src/shared/util.ts
  packages/sync-server/package.json
  packages/sync-server/src/app-gocardless/banks/easybank_bawaatww.js
  packages/sync-server/src/app-gocardless/banks/lhv-lhvbee22.js
  packages/sync-server/src/app-gocardless/banks/swedbank_habalv22.js
  upcoming-release-notes/5041.md
  yarn.lock
Labels: :white_check_mark: approved, dependencies

#5045 fix "delete x users" translation string
  packages/desktop-client/src/components/admin/UserDirectory/UserDirectory.tsx
  upcoming-release-notes/5045.md
Labels: :white_check_mark: approved

#5050 Fix: restrict electron-embedded sync server to bind only to configured hostname for security
  packages/desktop-electron/index.ts
  upcoming-release-notes/5050.md
Labels: :white_check_mark: approved

#5070 :wrench: added needs-triage label to all new bug issues
  .github/ISSUE_TEMPLATE/bug-report.yml
  upcoming-release-notes/5070.md
Labels: :mag: ready for review
