Repository actualbudget/actual, pull requests merged in 2025-04, with the labels that each got.

#4729 fix balance menu alignment
  packages/desktop-client/src/components/budget/envelope/EnvelopeBudgetComponents.tsx
  upcoming-release-notes/4729.md
Labels: :white_check_mark: Approved

#4674 :electron: Playwright testing for electron
  .github/workflows/e2e-test.yml
  .github/workflows/update-vrt.yml
  bin/package-electron
  package.json
  packages/desktop-electron/.gitignore
  packages/desktop-electron/e2e/__screenshots__/onboarding.test.ts/Onboarding-checks-the-page-visuals-1-linux.png
  packages/desktop-electron/e2e/data/.gitkeep
  packages/desktop-electron/e2e/onboarding.test.ts
  packages/desktop-electron/index.ts
  packages/desktop-electron/package.json
  packages/desktop-electron/playwright.config.ts
  packages/desktop-electron/tsconfig.dist.json
  packages/desktop-electron/window-state.ts
  upcoming-release-notes/4674.md
  yarn.lock
Labels: :white_check_mark: Approved

#4710 :wrench: improving typechecker and lint local performance
  .devcontainer/devcontainer.json
  .gitignore
  .prettierignore
  README.md
  docker-compose.yml
  eslint.config.mjs
  package.json
  packages/desktop-client/README.md
  packages/desktop-client/bin/remove-untranslated-languages
  packages/desktop-client/globals.d.ts
  packages/desktop-client/src/fonts.scss
  packages/desktop-electron/.babelrc
  packages/desktop-electron/loading.html
  packages/loot-core/src/mocks/files/default-budget-template/metadata.json
  packages/loot-core/src/types/server-handlers.d.ts
  packages/loot-core/tsconfig.api.json
  packages/sync-server/src/app-gocardless/README.md
  tsconfig.json
  upcoming-release-notes/4710.md
  yarn.lock
Labels: :white_check_mark: Approved

#4672 :recycle: (typescript) converted indexeddb to strict TS
  packages/loot-core/package.json
  packages/loot-core/src/platform/server/asyncStorage/index.ts
  packages/loot-core/src/platform/server/fs/index.web.ts
  packages/loot-core/src/platform/server/indexeddb/index.d.ts
  packages/loot-core/src/platform/server/indexeddb/index.js
  packages/loot-core/src/platform/server/indexeddb/index.ts
  packages/loot-core/src/platform/server/indexeddb/index.web.ts
  upcoming-release-notes/4672.md
Labels: :white_check_mark: Approved

#4743 Add KBCBE (KBC_KREDBEBB) to banks with limited history
  packages/sync-server/src/app-gocardless/bank-factory.js
  upcoming-release-notes/4743.md
Labels: :white_check_mark: Approved

#4752 :electron: Playwright test fixture
  .github/workflows/update-vrt.yml
  packages/desktop-electron/e2e/__screenshots__/onboarding.test.ts/Onboarding-checks-the-page-visuals-2-linux.png
  packages/desktop-electron/e2e/fixtures.ts
  packages/desktop-electron/e2e/onboarding.test.ts
  packages/desktop-electron/playwright.config.ts
  upcoming-release-notes/4752.md
Labels: :white_check_mark: Approved

#4768 :electron: Remove ngrok from electron server embed
  packages/desktop-electron/index.ts
  packages/desktop-electron/package.json
  packages/loot-core/src/types/prefs.d.ts
  upcoming-release-notes/4768.md
  yarn.lock
Labels: :white_check_mark: Approved

#4769 🐛 [Bug]: Fixed bug where closing account did not properly validate transfer or category
  packages/desktop-client/src/components/modals/CloseAccountModal.tsx
  upcoming-release-notes/4769.md
Labels: :white_check_mark: Approved

#4735 🐛 [Bug]: Focused console warning
  packages/desktop-client/src/components/autocomplete/Autocomplete.tsx
  upcoming-release-notes/4735.md
Labels: :white_check_mark: Approved

#4692 feat: add previous/next month navigation to the MonthPicker
  packages/desktop-client/e2e/budget.test.ts-snapshots/Budget-renders-the-summary-information-available-funds-overspent-budgeted-and-for-next-month-1-chromium-linux.png
  packages/desktop-client/e2e/budget.test.ts-snapshots/Budget-renders-the-summary-information-available-funds-overspent-budgeted-and-for-next-month-2-chromium-linux.png
  packages/desktop-client/e2e/budget.test.ts-snapshots/Budget-renders-the-summary-information-available-funds-overspent-budgeted-and-for-next-month-3-chromium-linux.png
  packages/desktop-client/e2e/budget.test.ts-snapshots/Budget-transfer-funds-to-another-category-1-chromium-linux.png
  packages/desktop-client/e2e/budget.test.ts-snapshots/Budget-transfer-funds-to-another-category-2-chromium-linux.png
  packages/desktop-client/e2e/budget.test.ts-snapshots/Budget-transfer-funds-to-another-category-3-chromium-linux.png
  packages/desktop-client/src/components/budget/MonthPicker.tsx
  upcoming-release-notes/4692.md
Labels: :sparkles: Merged

#4733 🐛 [Bug] Pinning sidebar doesnt persist on reload
  packages/loot-core/src/platform/server/asyncStorage/__mocks__/index.ts
  packages/loot-core/src/platform/server/asyncStorage/index.d.ts
  packages/loot-core/src/platform/server/asyncStorage/index.electron.ts
  packages/loot-core/src/platform/server/asyncStorage/index.ts
  packages/loot-core/src/server/preferences/app.ts
  upcoming-release-notes/4733.md
Labels: :white_check_mark: Approved

#4421 ✨ OPENID: Added option to create users on login
  packages/sync-server/src/accounts/openid.js
  packages/sync-server/src/config-types.ts
  packages/sync-server/src/load-config.js
  packages/sync-server/src/services/user-service.js
  upcoming-release-notes/4421.md
Labels: :white_check_mark: Approved

#4767 :electron: Fix loot-core resolution
  packages/loot-core/package.json
  upcoming-release-notes/4767.md
Labels: :white_check_mark: Approved

#4446 ✨ New OpenID first login UX
  packages/component-library/src/Input.tsx
  packages/desktop-client/src/components/manager/subscribe/ConfirmPasswordForm.tsx
  packages/desktop-client/src/components/manager/subscribe/Login.tsx
  packages/desktop-client/src/components/manager/subscribe/OpenIdForm.tsx
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/types/server-handlers.d.ts
  packages/sync-server/src/accounts/openid.js
  packages/sync-server/src/accounts/password.js
  packages/sync-server/src/app-account.js
  packages/sync-server/src/app-openid.js
  upcoming-release-notes/4446.md
Labels: :white_check_mark: Approved

#4749 [Goals]: fix remove goals bug
  packages/loot-core/src/server/budget/goaltemplates.ts
  upcoming-release-notes/4749.md
Labels: :white_check_mark: Approved

#4547 Extract budget file related server handlers from main.ts to server/budgetfiles/app.ts
  packages/desktop-client/src/components/modals/LoadBackupModal.tsx
  packages/desktop-client/src/components/modals/manager/DuplicateFileModal.tsx
  packages/desktop-client/src/components/settings/Export.tsx
  packages/loot-core/src/client/budgets/budgetsSlice.ts
  packages/loot-core/src/client/data-hooks/schedules.tsx
  packages/loot-core/src/server/api.ts
  packages/loot-core/src/server/budgetfiles/__snapshots__/backups.test.ts.snap
  packages/loot-core/src/server/budgetfiles/app.ts
  packages/loot-core/src/server/budgetfiles/backups.test.ts
  packages/loot-core/src/server/budgetfiles/backups.ts
  packages/loot-core/src/server/cloud-storage.ts
  packages/loot-core/src/server/errors.ts
  packages/loot-core/src/server/importers/index.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/server/spreadsheet/spreadsheet.ts
  packages/loot-core/src/shared/errors.ts
  packages/loot-core/src/types/handlers.d.ts
  packages/loot-core/src/types/server-events.d.ts
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/4547.md
Labels: :white_check_mark: Approved

#4544 Replace category DB queries in server handlers with AQL queries + implement category_groups AQL executor
  packages/desktop-client/src/components/autocomplete/CategoryAutocomplete.tsx
  packages/desktop-client/src/components/budget/BudgetCategories.jsx
  packages/desktop-client/src/components/budget/ExpenseCategory.tsx
  packages/desktop-client/src/components/budget/index.tsx
  packages/desktop-client/src/components/budget/util.ts
  packages/desktop-client/src/components/mobile/budget/IncomeCategoryList.tsx
  packages/desktop-client/src/components/modals/CategoryMenuModal.tsx
  packages/desktop-client/src/components/reports/ReportOptions.ts
  packages/loot-core/src/mocks/budget.ts
  packages/loot-core/src/mocks/index.ts
  packages/loot-core/src/server/api-models.ts
  packages/loot-core/src/server/api.ts
  packages/loot-core/src/server/aql/schema/executors.ts
  packages/loot-core/src/server/aql/schema/index.ts
  packages/loot-core/src/server/budget/app.ts
  packages/loot-core/src/server/budget/base.ts
  packages/loot-core/src/server/budget/goalsSchedule.test.ts
  packages/loot-core/src/server/db/index.ts
  packages/loot-core/src/server/importers/ynab5.ts
  packages/loot-core/src/server/models.ts
  packages/loot-core/src/types/models/category-group.d.ts
  packages/loot-core/src/types/models/category.d.ts
  upcoming-release-notes/4544.md
Labels: :white_check_mark: Approved

#4662 Extract encryption related server handlers from main.ts to server/encryption/app.ts
  packages/desktop-client/src/components/modals/FixEncryptionKeyModal.tsx
  packages/loot-core/src/server/api.ts
  packages/loot-core/src/server/auth/app.ts
  packages/loot-core/src/server/encryption/app.ts
  packages/loot-core/src/server/encryption/encryption-internals.ts
  packages/loot-core/src/server/encryption/encryption-internals.web.ts
  packages/loot-core/src/server/encryption/encryption.test.ts
  packages/loot-core/src/server/encryption/index.test.ts
  packages/loot-core/src/server/encryption/index.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/types/handlers.d.ts
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/4662.md
Labels: :white_check_mark: Approved

#4774 [Mobile] Fix income categories not changing colors based on active month
  packages/desktop-client/src/components/mobile/budget/IncomeCategoryList.tsx
  upcoming-release-notes/4774.md
Labels: :white_check_mark: Approved

#4756 :bug: (bank-sync) improved error handling for initial gocardless account linking
  packages/desktop-client/src/components/modals/GoCardlessExternalMsgModal.tsx
  packages/loot-core/src/client/modals/modalsSlice.ts
  packages/loot-core/src/server/accounts/app.ts
  upcoming-release-notes/4756.md
Labels: :white_check_mark: Approved

#4740 Fix bump versions script
  .github/actions/bump-package-versions
  upcoming-release-notes/4740.md
Labels: :white_check_mark: Approved

#4773 ✨ [Feature] Plugin enable/disable button
  packages/desktop-client/src/components/plugins/ManagePlugins.tsx
  packages/desktop-client/src/plugin/core/pluginLoader.ts
  packages/desktop-client/src/plugin/core/pluginStore.ts
  packages/loot-core/src/client/notifications/notificationsSlice.ts
  packages/plugins-core/src/types/actualPluginManifest.d.ts
Labels: :mag: Ready for review

#4584 Show closed accounts on mobile UI (#4581)
  packages/desktop-client/src/components/mobile/accounts/Account.tsx
  packages/desktop-client/src/components/mobile/accounts/AccountTransactions.tsx
  packages/desktop-client/src/components/mobile/accounts/Accounts.tsx
  packages/desktop-client/src/components/mobile/transactions/TransactionListWithBalances.tsx
  packages/desktop-client/src/components/spreadsheet/index.ts
  packages/loot-core/src/client/queries.ts
  upcoming-release-notes/4584.md
Labels: :white_check_mark: Approved

#4660 Extract auth related server handlers from main.ts to server/auth/app.ts
  packages/desktop-client/src/browser-preload.browser.js
  packages/desktop-client/src/components/ServerContext.tsx
  packages/desktop-client/src/components/manager/subscribe/Login.tsx
  packages/loot-core/src/client/app/appSlice.ts
  packages/loot-core/src/server/auth/app.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/types/handlers.d.ts
  packages/loot-core/src/types/server-handlers.d.ts
  packages/loot-core/typings/window.d.ts
  upcoming-release-notes/4660.md
Labels: :white_check_mark: Approved

#4593 Add option to control note imports during transaction import
  packages/api/methods.test.ts
  packages/desktop-client/e2e/accounts.test.ts
  packages/desktop-client/e2e/accounts.test.ts-snapshots/Accounts-Import-Transactions-import-csv-file-twice-1-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.ts-snapshots/Accounts-Import-Transactions-import-csv-file-twice-2-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.ts-snapshots/Accounts-Import-Transactions-import-csv-file-twice-3-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.ts-snapshots/Accounts-Import-Transactions-imports-transactions-from-a-CSV-file-1-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.ts-snapshots/Accounts-Import-Transactions-imports-transactions-from-a-CSV-file-2-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.ts-snapshots/Accounts-Import-Transactions-imports-transactions-from-a-CSV-file-3-chromium-linux.png
  packages/desktop-client/src/components/modals/ImportTransactionsModal/ImportTransactionsModal.jsx
  packages/loot-core/src/server/transactions/import/__snapshots__/parse-file.test.ts.snap
  packages/loot-core/src/server/transactions/import/parse-file.test.ts
  packages/loot-core/src/server/transactions/import/parse-file.ts
  upcoming-release-notes/4593.md
Labels: :white_check_mark: Approved

#4757 :wrench: added eslint auto-fix to the lint-staged step
  package.json
  upcoming-release-notes/4757.md
Labels: :white_check_mark: Approved

#4700 :arrow_up: upgrade to React v19
  package.json
  packages/component-library/package.json
  packages/component-library/src/Stack.tsx
  packages/component-library/src/Tooltip.tsx
  packages/desktop-client/e2e/reports.test.ts-snapshots/Reports-custom-reports-Switches-to-Bar-Graph-and-checks-the-visuals-1-chromium-linux.png
  packages/desktop-client/package.json
  packages/desktop-client/src/components/AppBackground.tsx
  packages/desktop-client/src/components/BankSyncStatus.tsx
  packages/desktop-client/src/components/FixedSizeList.tsx
  packages/desktop-client/src/components/Notes.tsx
  packages/desktop-client/src/components/Notifications.tsx
  packages/desktop-client/src/components/accounts/Account.tsx
  packages/desktop-client/src/components/accounts/Balance.tsx
  packages/desktop-client/src/components/budget/BudgetSummaries.tsx
  packages/desktop-client/src/components/budget/ExpenseCategory.tsx
  packages/desktop-client/src/components/budget/ExpenseGroup.tsx
  packages/desktop-client/src/components/budget/IncomeCategory.tsx
  packages/desktop-client/src/components/budget/IncomeGroup.tsx
  packages/desktop-client/src/components/budget/IncomeHeader.tsx
  packages/desktop-client/src/components/budget/RenderMonths.tsx
  packages/desktop-client/src/components/budget/SidebarGroup.tsx
  packages/desktop-client/src/components/mobile/MobileNavTabs.tsx
  packages/desktop-client/src/components/mobile/transactions/FocusableAmountInput.tsx
  packages/desktop-client/src/components/reports/SaveReportName.tsx
  packages/desktop-client/src/components/reports/graphs/BarGraph.tsx
  packages/desktop-client/src/components/reports/graphs/BarLineGraph.tsx
  packages/desktop-client/src/components/reports/graphs/LineGraph.tsx
  packages/desktop-client/src/components/reports/graphs/StackedBarGraph.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTable.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableHeader.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableRow.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableTotals.tsx
  packages/desktop-client/src/components/reports/reports/Calendar.tsx
  packages/desktop-client/src/components/reports/reports/CalendarCard.tsx
  packages/desktop-client/src/components/reports/reports/MarkdownCard.tsx
  packages/desktop-client/src/components/reports/spreadsheets/cash-flow-spreadsheet.tsx
  packages/desktop-client/src/components/select/DateSelect.tsx
  packages/desktop-client/src/components/sidebar/Account.tsx
  packages/desktop-client/src/components/sort.tsx
  packages/desktop-client/src/components/table.tsx
  packages/desktop-client/src/components/util/AmountInput.tsx
  packages/desktop-client/src/hooks/useDragRef.ts
  packages/desktop-client/src/hooks/useIsInViewport.ts
  packages/desktop-client/src/hooks/useMergedRefs.ts
  packages/desktop-client/src/hooks/usePrevious.ts
  packages/desktop-client/src/hooks/useProperFocus.tsx
  packages/loot-core/package.json
  packages/sync-server/package.json
  upcoming-release-notes/4700.md
  yarn.lock
Labels: :mag: Ready for review

#4714 Unlink account via bank sync page
  packages/desktop-client/src/components/accounts/Account.tsx
  packages/desktop-client/src/components/banksync/AccountRow.tsx
  packages/desktop-client/src/components/banksync/EditSyncAccount.tsx
  packages/desktop-client/src/components/modals/ConfirmUnlinkAccountModal.tsx
  packages/desktop-client/src/components/modals/GoCardlessExternalMsgModal.tsx
  packages/desktop-client/src/components/modals/GoCardlessInitialiseModal.tsx
  packages/desktop-client/src/components/modals/PluggyAiInitialiseModal.tsx
  packages/desktop-client/src/components/modals/SelectLinkedAccountsModal.jsx
  packages/desktop-client/src/components/modals/SimpleFinInitialiseModal.tsx
  packages/loot-core/src/client/modals/modalsSlice.ts
  upcoming-release-notes/4714.md
Labels: :white_check_mark: Approved

#4798 🆕 Sync server as npm package
  .github/workflows/publish-npm-packages.yml
  .gitignore
  packages/sync-server/LICENSE
  packages/sync-server/README.md
  packages/sync-server/bin/actual-server.js
  packages/sync-server/package.json
  upcoming-release-notes/4798.md
  yarn.lock
Labels: :white_check_mark: Approved

#4599 [Mobile] Drag and drop expense category groups to re-order
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  packages/desktop-client/src/components/mobile/budget/ExpenseCategoryList.tsx
  packages/desktop-client/src/components/mobile/budget/ExpenseCategoryListItem.tsx
  packages/desktop-client/src/components/mobile/budget/ExpenseGroupList.tsx
  packages/desktop-client/src/components/mobile/budget/ExpenseGroupListItem.tsx
  packages/desktop-client/src/components/mobile/budget/IncomeGroup.tsx
  packages/desktop-client/src/components/mobile/budget/ListItem.tsx
  packages/loot-core/src/client/queries/queriesSlice.ts
  upcoming-release-notes/4599.md
Labels: :white_check_mark: Approved

#4812 Fix crash on transactions table with new transaction popup open
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  upcoming-release-notes/4812.md
Labels: :white_check_mark: Approved

#4567 Do not count hidden categories in tracking budgets + cleanup table math
  packages/loot-core/src/server/budget/base.test.ts
  packages/loot-core/src/server/budget/base.ts
  packages/loot-core/src/server/budget/envelope.ts
  packages/loot-core/src/server/budget/report.ts
  upcoming-release-notes/4567.md
Labels: :white_check_mark: Approved

#4780 add support for longer running SimpleFIN transaction requests
  packages/sync-server/src/app-simplefin/app-simplefin.js
  upcoming-release-notes/4780.md
Labels: :white_check_mark: Approved

#4706 Reload on all redirects to handle Cloudflare Access auth expiration
  packages/loot-core/src/platform/server/fetch/index.ts
  upcoming-release-notes/4706.md
Labels: :white_check_mark: Approved

#4739 ✨ [Feature] Manually merge transactions
  packages/desktop-client/src/components/accounts/Account.tsx
  packages/desktop-client/src/components/accounts/Header.tsx
  packages/desktop-client/src/components/mobile/transactions/TransactionList.tsx
  packages/desktop-client/src/components/transactions/SelectedTransactionsButton.tsx
  packages/desktop-client/src/hooks/useTransactionBatchActions.ts
  packages/loot-core/src/server/db/index.ts
  packages/loot-core/src/server/transactions/app.ts
  packages/loot-core/src/server/transactions/merge.test.ts
  packages/loot-core/src/server/transactions/merge.ts
  upcoming-release-notes/4739.md
Labels: :white_check_mark: Approved

#4824 Slow improvements to `Account.tsx` (1/many)
  packages/desktop-client/src/components/accounts/Account.tsx
  packages/desktop-client/src/components/accounts/AccountEmptyMessage.tsx
  packages/desktop-client/src/components/accounts/Header.tsx
  upcoming-release-notes/4824.md
Labels: :white_check_mark: Approved

#4835 Revert "Reload on all redirects to handle Cloudflare Access auth expiration"
  packages/loot-core/src/platform/server/fetch/index.ts
  upcoming-release-notes/4706.md
Labels: :white_check_mark: Approved

#4715 4571: Fix UI lockout when using In/Out mode with existing split columns
  packages/desktop-client/e2e/accounts.test.ts-snapshots/Accounts-Import-Transactions-import-csv-file-twice-1-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.ts-snapshots/Accounts-Import-Transactions-import-csv-file-twice-2-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.ts-snapshots/Accounts-Import-Transactions-import-csv-file-twice-3-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.ts-snapshots/Accounts-Import-Transactions-imports-transactions-from-a-CSV-file-1-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.ts-snapshots/Accounts-Import-Transactions-imports-transactions-from-a-CSV-file-2-chromium-linux.png
  packages/desktop-client/e2e/accounts.test.ts-snapshots/Accounts-Import-Transactions-imports-transactions-from-a-CSV-file-3-chromium-linux.png
  packages/desktop-client/src/components/modals/ImportTransactionsModal/FieldMappings.tsx
  packages/desktop-client/src/components/modals/ImportTransactionsModal/ImportTransactionsModal.jsx
  packages/desktop-client/src/components/modals/ImportTransactionsModal/InOutOption.tsx
  packages/desktop-client/src/components/modals/ImportTransactionsModal/MultiplierOption.tsx
  packages/desktop-client/src/components/modals/ImportTransactionsModal/SelectField.tsx
  packages/desktop-client/src/components/modals/ImportTransactionsModal/Transaction.tsx
  packages/desktop-client/src/components/modals/ImportTransactionsModal/utils.ts
  upcoming-release-notes/4715.md
Labels: :white_check_mark: Approved

#4724 fix: persist filters in Custom Report on interval or date range change
  packages/desktop-client/src/components/reports/reports/CustomReport.tsx
  upcoming-release-notes/4724.md
Labels: :white_check_mark: Approved

#4825 🐛 CLI: Fix ACTUAL_DATA_DIR env variable not respected in some cases
  packages/sync-server/bin/actual-server.js
  upcoming-release-notes/4825.md
Labels: :white_check_mark: Approved

#4807 feat: expandable budget categories
  packages/component-library/src/icons/v2/ArrowButtonSingleLeft1.tsx
  packages/component-library/src/icons/v2/arrow-button-single-left-1.svg
  packages/component-library/src/icons/v2/index.ts
  packages/desktop-client/e2e/budget.test.ts-snapshots/Budget-renders-the-summary-information-available-funds-overspent-budgeted-and-for-next-month-1-chromium-linux.png
  packages/desktop-client/e2e/budget.test.ts-snapshots/Budget-renders-the-summary-information-available-funds-overspent-budgeted-and-for-next-month-2-chromium-linux.png
  packages/desktop-client/e2e/budget.test.ts-snapshots/Budget-renders-the-summary-information-available-funds-overspent-budgeted-and-for-next-month-3-chromium-linux.png
  packages/desktop-client/e2e/budget.test.ts-snapshots/Budget-transfer-funds-to-another-category-1-chromium-linux.png
  packages/desktop-client/e2e/budget.test.ts-snapshots/Budget-transfer-funds-to-another-category-2-chromium-linux.png
  packages/desktop-client/e2e/budget.test.ts-snapshots/Budget-transfer-funds-to-another-category-3-chromium-linux.png
  packages/desktop-client/src/components/budget/BudgetPageHeader.tsx
  packages/desktop-client/src/components/budget/BudgetTable.tsx
  packages/desktop-client/src/components/budget/BudgetTotals.tsx
  packages/desktop-client/src/components/budget/DynamicBudgetTable.tsx
  packages/desktop-client/src/components/budget/IncomeHeader.tsx
  packages/desktop-client/src/components/budget/SidebarCategory.tsx
  packages/desktop-client/src/components/budget/SidebarGroup.tsx
  packages/loot-core/src/server/preferences/app.ts
  packages/loot-core/src/types/prefs.d.ts
  upcoming-release-notes/4807.md
Labels: :white_check_mark: Approved

#4838 Fix bug in ofx2json logic
  packages/loot-core/src/server/transactions/import/__snapshots__/parse-file.test.ts.snap
  packages/loot-core/src/server/transactions/import/ofx2json.test.ts
  packages/loot-core/src/server/transactions/import/ofx2json.ts
  upcoming-release-notes/4838.md
Labels: :white_check_mark: Approved

#4719 Fixes Bug #4705 scheduled transaction date when posting early.
  packages/loot-core/src/server/schedules/app.ts
  upcoming-release-notes/4719.md
Labels: :white_check_mark: Approved

#4844 Restore"Reload on all redirects to handle Cloudflare Access auth expiration"
  packages/loot-core/src/platform/server/fetch/index.ts
  upcoming-release-notes/4844.md
Labels: :white_check_mark: Approved

#4847 :electron: Prep for configure server page
  packages/desktop-client/src/browser-preload.browser.js
  packages/desktop-electron/index.ts
  packages/desktop-electron/preload.ts
  packages/loot-core/src/platform/server/asyncStorage/__mocks__/index.ts
  packages/loot-core/src/platform/server/asyncStorage/index.d.ts
  packages/loot-core/src/platform/server/asyncStorage/index.electron.ts
  packages/loot-core/src/platform/server/asyncStorage/index.ts
  packages/loot-core/src/server/accounts/app.ts
  packages/loot-core/src/server/preferences/app.ts
  packages/loot-core/typings/window.d.ts
  upcoming-release-notes/4847.md
Labels: :white_check_mark: Approved

#4840 Move sync-server to vitest
  eslint.config.mjs
  packages/sync-server/jest.config.json
  packages/sync-server/jest.global-teardown.js
  packages/sync-server/package.json
  packages/sync-server/src/app-gocardless/banks/tests/integration_bank.spec.js
  packages/sync-server/src/app-gocardless/banks/tests/spk_marburg_biedenkopf_heladef1mar.spec.js
  packages/sync-server/src/app-gocardless/banks/tests/ssk_dusseldorf_dussdeddxxx.spec.js
  packages/sync-server/src/app-gocardless/services/tests/gocardless-service.spec.js
  packages/sync-server/src/app-sync/tests/services/files-service.test.js
  packages/sync-server/tsconfig.json
  packages/sync-server/vitest.config.ts
  packages/sync-server/vitest.globalSetup.js
  upcoming-release-notes/4840.md
  yarn.lock
Labels: :mag: Ready for review

#4851 Move crdt to vitest
  packages/crdt/jest.config.js
  packages/crdt/package.json
  packages/crdt/src/crdt/__snapshots__/merkle.test.ts.snap
  packages/loot-core/src/server/encryption/encryption-internals.ts
  packages/loot-core/src/server/encryption/encryption-internals.web.ts
  upcoming-release-notes/4851.md
  yarn.lock
Labels: :white_check_mark: Approved

#4857 invert Strawberry credit card transaction amounts
  packages/sync-server/bin/actual-server.js
  packages/sync-server/src/app-gocardless/banks/seb_kort_bank_ab.js
  upcoming-release-notes/4857.md
Labels: :white_check_mark: Approved

#4853 :electron: Fix Load Backup backup modal
  packages/desktop-electron/menu.ts
  upcoming-release-notes/4853.md
Labels: :white_check_mark: Approved

#4856 Move remaining non-loot-core packages to latest vitest
  packages/api/__snapshots__/methods.test.ts.snap
  packages/api/jest.config.js
  packages/api/methods.test.ts
  packages/api/package.json
  packages/api/vitest.config.ts
  packages/desktop-client/package.json
  packages/desktop-client/vite.config.mts
  packages/eslint-plugin-actual/package.json
  upcoming-release-notes/4856.md
  yarn.lock
Labels: :white_check_mark: Approved

#4859 Move loot-core to vitest
  eslint.config.mjs
  packages/crdt/index.ts
  packages/crdt/src/index.ts
  packages/desktop-client/package.json
  packages/desktop-client/src/setupTests.js
  packages/loot-core/jest.config.js
  packages/loot-core/jest.web.config.js
  packages/loot-core/package.json
  packages/loot-core/peg-transform.mjs
  packages/loot-core/src/client/query-helpers.test.ts
  packages/loot-core/src/mocks/setup.ts
  packages/loot-core/src/mocks/util.ts
  packages/loot-core/src/platform/server/fs/index.web.test.ts
  packages/loot-core/src/platform/server/sqlite/index.web.test.ts
  packages/loot-core/src/platform/server/sqlite/index.web.ts
  packages/loot-core/src/server/__snapshots__/main.test.ts.snap
  packages/loot-core/src/server/__snapshots__/sheet.test.ts.snap
  packages/loot-core/src/server/accounts/__snapshots__/sync.test.ts.snap
  packages/loot-core/src/server/accounts/sync.test.ts
  packages/loot-core/src/server/api.test.ts
  packages/loot-core/src/server/aql/schema/executors.test.ts
  packages/loot-core/src/server/budget/goalsSchedule.test.ts
  packages/loot-core/src/server/budget/template-notes.test.ts
  packages/loot-core/src/server/budgetfiles/__snapshots__/backups.test.ts.snap
  packages/loot-core/src/server/db/__snapshots__/index.test.ts.snap
  packages/loot-core/src/server/main.test.ts
  packages/loot-core/src/server/migrate/__snapshots__/migrations.test.ts.snap
  packages/loot-core/src/server/rules/index.test.ts
  packages/loot-core/src/server/spreadsheet/__snapshots__/spreadsheet.test.ts.snap
  packages/loot-core/src/server/spreadsheet/spreadsheet.test.ts
  packages/loot-core/src/server/sync/__snapshots__/sync.test.ts.snap
  packages/loot-core/src/server/sync/sync.property.test.ts
  packages/loot-core/src/server/transactions/__snapshots__/transaction-rules.test.ts.snap
  packages/loot-core/src/server/transactions/__snapshots__/transfer.test.ts.snap
  packages/loot-core/src/server/transactions/import/__snapshots__/parse-file.test.ts.snap
  packages/loot-core/src/server/transactions/transaction-rules.test.ts
  packages/loot-core/src/shared/__snapshots__/months.test.ts.snap
  packages/loot-core/typings/vite-plugin-peggy-loader.d.ts
  packages/loot-core/vitest.config.ts
  packages/loot-core/vitest.web.config.ts
  packages/loot-core/webpack/webpack.desktop.config.js
  tsconfig.json
  upcoming-release-notes/4859.md
  yarn.lock
Labels: :white_check_mark: Approved

#4862 Move some .d.ts files to .ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/server/transactions/index.ts
  packages/loot-core/src/types/api-handlers.ts
  packages/loot-core/src/types/budget.ts
  packages/loot-core/src/types/file.ts
  packages/loot-core/src/types/handlers.ts
  packages/loot-core/src/types/models/bank-sync.ts
  packages/loot-core/src/types/models/category-group.ts
  packages/loot-core/src/types/models/category.ts
  packages/loot-core/src/types/models/dashboard.ts
  packages/loot-core/src/types/models/gocardless.ts
  packages/loot-core/src/types/models/index.ts
  packages/loot-core/src/types/models/note.ts
  packages/loot-core/src/types/models/openid.ts
  packages/loot-core/src/types/models/payee.ts
  packages/loot-core/src/types/models/reports.ts
  packages/loot-core/src/types/models/rule.ts
  packages/loot-core/src/types/models/schedule.ts
  packages/loot-core/src/types/models/simplefin.ts
  packages/loot-core/src/types/models/transaction-filter.ts
  packages/loot-core/src/types/models/transaction.ts
  packages/loot-core/src/types/server-events.ts
  packages/loot-core/src/types/server-handlers.ts
  packages/loot-core/src/types/util.ts
  upcoming-release-notes/4862.md
Labels: :white_check_mark: Approved

#4860 :electron: Fix some menu links
  packages/desktop-electron/menu.ts
  upcoming-release-notes/4860.md
Labels: :white_check_mark: Approved

#4845 fix: commerzbank escape payee
  packages/sync-server/src/app-gocardless/banks/commerzbank_cobadeff.js
  packages/sync-server/src/app-gocardless/banks/tests/commerzbank_cobadeff.spec.js
  packages/sync-server/src/app-gocardless/banks/util/escape-regexp.js
  upcoming-release-notes/4845.md
Labels: :white_check_mark: Approved

#4875 [Mobile] Fix uncategorized banner + overspent banner showing previously active month's overspent categories
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-set-budget-to-12-month-average-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-set-budget-to-12-month-average-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-set-budget-to-12-month-average-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-set-budget-to-3-month-average-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-set-budget-to-3-month-average-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-set-budget-to-3-month-average-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-set-budget-to-6-month-average-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-set-budget-to-6-month-average-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-set-budget-to-6-month-average-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-applies-budget-template-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-applies-budget-template-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-applies-budget-template-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--0ba04-nt-amount-opens-the-budget-summary-menu-modal-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--0dfe7-page-header-shows-the-previous-month-s-budget-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--1ce6d-nt-amount-opens-the-budget-summary-menu-modal-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--42062-in-the-page-header-opens-the-month-menu-modal-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--49fb6-in-the-page-header-opens-the-month-menu-modal-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--5f098-roup-name-opens-the-category-group-menu-modal-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--929be-roup-name-opens-the-category-group-menu-modal-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--a3783-in-the-page-header-opens-the-budget-page-menu-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--a8b5e-in-the-page-header-opens-the-budget-page-menu-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--b1562-in-the-page-header-opens-the-month-menu-modal-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--cfb69-page-header-shows-the-previous-month-s-budget-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--dc927-roup-name-opens-the-category-group-menu-modal-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--f224f-nt-amount-opens-the-budget-summary-menu-modal-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--f7fa3-page-header-shows-the-previous-month-s-budget-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--f8a19-in-the-page-header-opens-the-budget-page-menu-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking-the-balance-cell-opens-the-balance-menu-modal-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking-the-balance-cell-opens-the-balance-menu-modal-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking-the-balance-cell-opens-the-balance-menu-modal-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking-the-budgeted-cell-opens-the-budget-menu-modal-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking-the-budgeted-cell-opens-the-budget-menu-modal-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking-the-budgeted-cell-opens-the-budget-menu-modal-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking-the-category-name-opens-the-category-menu-modal-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking-the-category-name-opens-the-category-menu-modal-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking-the-category-name-opens-the-category-menu-modal-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-copies-last-month-s-budget-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-copies-last-month-s-budget-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-copies-last-month-s-budget-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-loads-the-budget-page-with-budgeted-amounts-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-loads-the-budget-page-with-budgeted-amounts-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-loads-the-budget-page-with-budgeted-amounts-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-set-budget-to-12-month-average-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-set-budget-to-12-month-average-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-set-budget-to-12-month-average-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-set-budget-to-3-month-average-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-set-budget-to-3-month-average-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-set-budget-to-3-month-average-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-set-budget-to-6-month-average-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-set-budget-to-6-month-average-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-set-budget-to-6-month-average-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-updates-the-budgeted-amount-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-updates-the-budgeted-amount-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-updates-the-budgeted-amount-3-chromium-linux.png
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  packages/desktop-client/src/hooks/useOverspentCategories.ts
  upcoming-release-notes/4875.md
Labels: :sparkles: Merged

#4880 [Mobile] Fix hidden category groups not being hidden
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  packages/desktop-client/src/components/mobile/budget/ExpenseCategoryList.tsx
  packages/desktop-client/src/components/mobile/budget/ExpenseCategoryListItem.tsx
  packages/desktop-client/src/components/mobile/budget/ExpenseGroupList.tsx
  packages/desktop-client/src/components/mobile/budget/ExpenseGroupListItem.tsx
  packages/desktop-client/src/components/mobile/budget/IncomeGroup.tsx
  packages/desktop-client/src/components/mobile/budget/index.tsx
  upcoming-release-notes/4880.md
Labels: :mag: ready for review, :white_check_mark: approved
