Repository actualbudget/actual, pull requests merged in 2025-03, with the labels that each got.

#4483 🐳 Docker images to be published under the actual repo
  .github/workflows/docker-edge.yml
  .github/workflows/docker-release.yml
  upcoming-release-notes/4483.md
Labels: :white_check_mark: Approved

#4464 Update transaction repair tool to remove erroneous transaction errors
  packages/desktop-client/src/components/settings/RepairTransactions.tsx
  packages/loot-core/src/server/tools/app.ts
  packages/loot-core/src/server/tools/types/handlers.d.ts
  upcoming-release-notes/4464.md
Labels: :white_check_mark: Approved

#4474 align month picker years to the month text
  packages/desktop-client/e2e/budget.test.ts-snapshots/Budget-renders-the-summary-information-available-funds-overspent-budgeted-and-for-next-month-1-chromium-linux.png
  packages/desktop-client/e2e/budget.test.ts-snapshots/Budget-renders-the-summary-information-available-funds-overspent-budgeted-and-for-next-month-2-chromium-linux.png
  packages/desktop-client/e2e/budget.test.ts-snapshots/Budget-renders-the-summary-information-available-funds-overspent-budgeted-and-for-next-month-3-chromium-linux.png
  packages/desktop-client/e2e/budget.test.ts-snapshots/Budget-transfer-funds-to-another-category-1-chromium-linux.png
  packages/desktop-client/e2e/budget.test.ts-snapshots/Budget-transfer-funds-to-another-category-2-chromium-linux.png
  packages/desktop-client/e2e/budget.test.ts-snapshots/Budget-transfer-funds-to-another-category-3-chromium-linux.png
  packages/desktop-client/src/components/budget/MonthPicker.tsx
  upcoming-release-notes/4474.md
Labels: :white_check_mark: Approved

#4485 prevent subsequent builds from failing when fetching translations
  bin/package-browser
  bin/package-electron
  upcoming-release-notes/4485.md
Labels: :white_check_mark: Approved

#4416 Update bank-factory.js add bank to BANKS_WITH_LIMITED_HISTORY
  packages/sync-server/src/app-gocardless/bank-factory.js
  upcoming-release-notes/4416.md
Labels: :white_check_mark: Approved

#4489 fix negative amount parsing
  packages/loot-core/src/shared/util.ts
  upcoming-release-notes/4489.md
Labels: :white_check_mark: Approved

#4114 [Redux Toolkit Migration] budgetsSlice
  packages/desktop-client/src/components/App.tsx
  packages/desktop-client/src/components/LoggedInUser.tsx
  packages/desktop-client/src/components/manager/BudgetList.tsx
  packages/desktop-client/src/components/manager/ConfigServer.tsx
  packages/desktop-client/src/components/manager/WelcomeScreen.tsx
  packages/desktop-client/src/components/manager/subscribe/Bootstrap.tsx
  packages/desktop-client/src/components/modals/CreateEncryptionKeyModal.tsx
  packages/desktop-client/src/components/modals/LoadBackupModal.tsx
  packages/desktop-client/src/components/modals/OpenIDEnableModal.tsx
  packages/desktop-client/src/components/modals/OutOfSyncMigrationsModal.tsx
  packages/desktop-client/src/components/modals/PasswordEnableModal.tsx
  packages/desktop-client/src/components/modals/TransferOwnership.tsx
  packages/desktop-client/src/components/modals/manager/DeleteFileModal.tsx
  packages/desktop-client/src/components/modals/manager/DuplicateFileModal.tsx
  packages/desktop-client/src/components/modals/manager/FilesSettingsModal.tsx
  packages/desktop-client/src/components/modals/manager/ImportActualModal.tsx
  packages/desktop-client/src/components/modals/manager/ImportYNAB4Modal.tsx
  packages/desktop-client/src/components/modals/manager/ImportYNAB5Modal.tsx
  packages/desktop-client/src/components/settings/index.tsx
  packages/desktop-client/src/components/sidebar/BudgetName.tsx
  packages/desktop-client/src/global-events.ts
  packages/desktop-client/src/index.tsx
  packages/loot-core/src/client/actions/backups.ts
  packages/loot-core/src/client/actions/budgets.ts
  packages/loot-core/src/client/actions/index.ts
  packages/loot-core/src/client/actions/user.ts
  packages/loot-core/src/client/budgets/budgetsSlice.ts
  packages/loot-core/src/client/reducers/budgets.ts
  packages/loot-core/src/client/reducers/index.ts
  packages/loot-core/src/client/reducers/modals.ts
  packages/loot-core/src/client/shared-listeners.ts
  packages/loot-core/src/client/state-types/budgets.d.ts
  packages/loot-core/src/client/state-types/index.d.ts
  packages/loot-core/src/client/store/index.ts
  packages/loot-core/src/client/store/mock.ts
  upcoming-release-notes/4114.md
Labels: :white_check_mark: Approved

#4278 Fix react-hooks/exhaustive-deps error on useSheetValue.ts
  eslint.config.mjs
  packages/desktop-client/src/components/spreadsheet/index.ts
  packages/desktop-client/src/components/spreadsheet/useSheetValue.ts
  packages/loot-core/src/client/SpreadsheetProvider.tsx
  upcoming-release-notes/4278.md
Labels: :white_check_mark: Approved

#4248 [TypeScript] Make `db.first` generic to make it easy to type DB query results
  packages/loot-core/src/mocks/budget.ts
  packages/loot-core/src/server/accounts/app.ts
  packages/loot-core/src/server/accounts/link.ts
  packages/loot-core/src/server/accounts/payees.ts
  packages/loot-core/src/server/accounts/sync.ts
  packages/loot-core/src/server/api.ts
  packages/loot-core/src/server/budget/actions.ts
  packages/loot-core/src/server/budget/base.ts
  packages/loot-core/src/server/budget/cleanup-template.ts
  packages/loot-core/src/server/budget/goalsSchedule.ts
  packages/loot-core/src/server/dashboard/app.ts
  packages/loot-core/src/server/db/index.ts
  packages/loot-core/src/server/filters/app.ts
  packages/loot-core/src/server/main.test.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/server/migrate/migrations.test.ts
  packages/loot-core/src/server/reports/app.ts
  packages/loot-core/src/server/schedules/app.ts
  packages/loot-core/src/server/schedules/find-schedules.ts
  packages/loot-core/src/server/sheet.ts
  packages/loot-core/src/server/transactions/transaction-rules.test.ts
  packages/loot-core/src/server/transactions/transaction-rules.ts
  packages/loot-core/src/server/transactions/transfer.test.ts
  packages/loot-core/src/server/transactions/transfer.ts
  packages/loot-core/src/server/update.ts
  packages/loot-core/src/types/models/index.d.ts
  upcoming-release-notes/4248.md
Labels: :white_check_mark: Approved

#4503 Fix number input on mobile with hidden decimals
  packages/loot-core/src/shared/util.test.ts
  packages/loot-core/src/shared/util.ts
  upcoming-release-notes/4503.md
Labels: :white_check_mark: Approved

#4497 🔖 (25.3.1)
  packages/api/package.json
  packages/desktop-client/package.json
  packages/desktop-electron/package.json
  packages/loot-core/src/shared/util.test.ts
  packages/loot-core/src/shared/util.ts
  packages/sync-server/package.json
  yarn.lock
Labels: :white_check_mark: Approved

#4506 Fix typo
  packages/desktop-client/src/components/filters/FilterMenu.tsx
  upcoming-release-notes/4506.md
Labels: :white_check_mark: Approved

#4508 Ignore user's fly.toml
  .gitignore
  upcoming-release-notes/4508.md
Labels: :white_check_mark: Approved

#4515 increase timeout for SimpleFIN batch sync and add debug logging
  packages/desktop-client/src/components/accounts/AccountSyncCheck.tsx
  packages/loot-core/src/server/accounts/app.ts
  packages/loot-core/src/server/accounts/sync.ts
  upcoming-release-notes/4515.md
Labels: :white_check_mark: Approved

#4507 :electron: Copy budget files to succeed even if cleanup fails & adding retries
  packages/desktop-electron/index.ts
  packages/desktop-electron/package.json
  upcoming-release-notes/4507.md
  yarn.lock
Labels: :white_check_mark: Approved

#4519 fix: filtering of transfer transactions
  packages/loot-core/src/client/queries.ts
  upcoming-release-notes/4519.md
Labels: :white_check_mark: Approved

#4459 feat: add "last reconciled" timestamp to accounts
  packages/desktop-client/src/components/accounts/Account.tsx
  packages/desktop-client/src/components/accounts/Balance.tsx
  packages/desktop-client/src/components/accounts/Header.tsx
  packages/desktop-client/src/components/spreadsheet/index.ts
  packages/loot-core/migrations/1740506588539_add_last_reconciled_at.sql
  packages/loot-core/src/mocks/index.ts
  packages/loot-core/src/server/accounts/app.ts
  packages/loot-core/src/server/aql/schema/index.ts
  packages/loot-core/src/shared/util.ts
  packages/loot-core/src/types/models/account.d.ts
  upcoming-release-notes/4459.md
Labels: :white_check_mark: Approved

#4523 Show the last bank sync in plain language instead of timestamp
  packages/desktop-client/src/components/banksync/AccountRow.tsx
  packages/loot-core/src/shared/util.ts
  upcoming-release-notes/4523.md
Labels: :white_check_mark: Approved

#4522 :bug: make custom report side nav bar responsive
  packages/desktop-client/src/components/reports/CategorySelector.tsx
  packages/desktop-client/src/components/reports/ReportSidebar.tsx
  upcoming-release-notes/4522.md
Labels: :white_check_mark: Approved

#4049 Pluggy.ai bank sync
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/banksync/EditSyncAccount.tsx
  packages/desktop-client/src/components/banksync/index.tsx
  packages/desktop-client/src/components/modals/CreateAccountModal.tsx
  packages/desktop-client/src/components/modals/PluggyAiInitialiseModal.tsx
  packages/desktop-client/src/components/modals/SelectLinkedAccountsModal.jsx
  packages/desktop-client/src/components/settings/Experimental.tsx
  packages/desktop-client/src/hooks/useFeatureFlag.ts
  packages/desktop-client/src/hooks/usePluggyAiStatus.ts
  packages/loot-core/src/client/accounts/accountsSlice.ts
  packages/loot-core/src/client/state-types/modals.d.ts
  packages/loot-core/src/server/accounts/app.ts
  packages/loot-core/src/server/accounts/sync.ts
  packages/loot-core/src/server/server-config.ts
  packages/loot-core/src/types/models/bank-sync.d.ts
  packages/loot-core/src/types/models/index.d.ts
  packages/loot-core/src/types/models/pluggyai.d.ts
  packages/loot-core/src/types/prefs.d.ts
  packages/sync-server/package.json
  packages/sync-server/src/app-pluggyai/app-pluggyai.js
  packages/sync-server/src/app-pluggyai/pluggyai-service.js
  packages/sync-server/src/app.js
  packages/sync-server/src/services/secrets-service.js
  upcoming-release-notes/4049.md
  yarn.lock
Labels: do not merge, :white_check_mark: Approved

#4440 🔨 Refactoring load-config.js
  packages/sync-server/migrations/1694360000000-create-folders.js
  packages/sync-server/package.json
  packages/sync-server/src/account-db.js
  packages/sync-server/src/accounts/openid.js
  packages/sync-server/src/accounts/password.js
  packages/sync-server/src/app.js
  packages/sync-server/src/config-types.ts
  packages/sync-server/src/load-config.js
  packages/sync-server/src/migrations.js
  packages/sync-server/src/scripts/enable-openid.js
  packages/sync-server/src/scripts/health-check.js
  packages/sync-server/src/util/paths.js
  packages/sync-server/src/util/validate-user.js
  upcoming-release-notes/4440.md
  yarn.lock
Labels: :white_check_mark: Approved

#4302 improve summary report monthly average calculation
  packages/desktop-client/src/components/reports/spreadsheets/summary-spreadsheet.ts
  upcoming-release-notes/4302.md
Labels: :white_check_mark: Approved

#4529 🐛 Fix on typed select
  packages/loot-core/src/server/accounts/app.ts
  upcoming-release-notes/4529.md
Labels: :white_check_mark: Approved

#4493 Fixed transaction dates in bank sync with `MBANK_RETAIL_BREXPLPW`
  packages/sync-server/src/app-gocardless/banks/mbank_retail_brexplpw.js
  upcoming-release-notes/4493.md
Labels: :white_check_mark: Approved

#4511 Allow marking transactions as Transfers on mobile devices
  packages/desktop-client/src/components/accounts/Account.tsx
  packages/desktop-client/src/components/mobile/accounts/AccountTransactions.tsx
  packages/desktop-client/src/components/mobile/budget/CategoryTransactions.tsx
  packages/desktop-client/src/components/mobile/transactions/TransactionList.tsx
  packages/desktop-client/src/components/mobile/transactions/TransactionListWithBalances.tsx
  packages/desktop-client/src/components/reports/reports/Calendar.tsx
  packages/desktop-client/src/hooks/useTransactionBatchActions.ts
  upcoming-release-notes/4511.md
Labels: :white_check_mark: Approved

#4530 🐛 Fixes for OpenID with the new config
  packages/desktop-client/src/components/manager/subscribe/OpenIdForm.tsx
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/types/models/openid.d.ts
  packages/sync-server/src/accounts/openid.js
  upcoming-release-notes/4530.md
Labels: :white_check_mark: Approved

#4534 🐛 Fix production builds missing `convict` and `pluggy-sdk`
  packages/sync-server/package.json
  upcoming-release-notes/4534.md
Labels: :white_check_mark: Approved

#4535 🐛 Fix config for default data dir
  packages/sync-server/src/load-config.js
  upcoming-release-notes/4535.md
Labels: :white_check_mark: Approved

#4532 disable mangling when building
  packages/desktop-client/vite.config.mts
  packages/loot-core/webpack/webpack.browser.config.js
  upcoming-release-notes/4532.md
Labels: :white_check_mark: Approved

#4524 [TypeScript] More specific types on budget table components
  packages/desktop-client/src/components/budget/IncomeCategory.tsx
  packages/desktop-client/src/components/budget/IncomeGroup.tsx
  packages/desktop-client/src/components/budget/SidebarCategory.tsx
  packages/desktop-client/src/components/budget/SidebarGroup.tsx
  packages/desktop-client/src/components/budget/envelope/EnvelopeBudgetComponents.tsx
  packages/desktop-client/src/components/budget/tracking/TrackingBudgetComponents.tsx
  upcoming-release-notes/4524.md
Labels: :white_check_mark: Approved

#4267 Add "payee is nothing" condition to rule if there is no payee set in a schedule
  packages/desktop-client/src/components/schedules/ScheduleDetails.tsx
  upcoming-release-notes/4267.md
Labels: :white_check_mark: Approved

#4537 🐛 Fix for ACTUAL_PORT and PORT vars
  packages/sync-server/src/load-config.js
  upcoming-release-notes/4537.md
Labels: :white_check_mark: Approved

#4443 Extract payees related server handlers from main.ts to server/payees/app.ts
  packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.test.tsx
  packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.tsx
  packages/desktop-client/src/components/payees/ManagePayees.tsx
  packages/desktop-client/src/components/payees/ManagePayeesWithData.tsx
  packages/desktop-client/src/components/payees/PayeeTableRow.tsx
  packages/desktop-client/src/components/transactions/TransactionsTable.test.tsx
  packages/loot-core/src/server/aql/schema/index.ts
  packages/loot-core/src/server/db/index.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/server/models.ts
  packages/loot-core/src/server/payees/app.ts
  packages/loot-core/src/server/undo.ts
  packages/loot-core/src/shared/util.ts
  packages/loot-core/src/types/handlers.d.ts
  packages/loot-core/src/types/models/payee.d.ts
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/4443.md
Labels: :white_check_mark: Approved

#4249 [TypeScript] Make `db.firstSync` generic to make it easy to type DB query results
  packages/loot-core/src/server/budget/actions.ts
  packages/loot-core/src/server/db/index.ts
  upcoming-release-notes/4249.md
Labels: :white_check_mark: Approved

#4540 ✨ Memoize external accounts for bank sync
  packages/desktop-client/src/components/modals/SelectLinkedAccountsModal.jsx
  upcoming-release-notes/4540.md
Labels: :white_check_mark: Approved

#4211 📚 Translate calendar related strings
  packages/desktop-client/src/components/accounts/Header.tsx
  packages/desktop-client/src/components/banksync/AccountRow.tsx
  packages/desktop-client/src/components/banksync/AccountsList.tsx
  packages/desktop-client/src/components/budget/MonthPicker.tsx
  packages/desktop-client/src/components/budget/envelope/budgetsummary/BudgetSummary.tsx
  packages/desktop-client/src/components/budget/tracking/budgetsummary/BudgetSummary.tsx
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  packages/desktop-client/src/components/mobile/budget/CategoryTransactions.tsx
  packages/desktop-client/src/components/mobile/budget/index.tsx
  packages/desktop-client/src/components/mobile/transactions/TransactionList.tsx
  packages/desktop-client/src/components/modals/EnvelopeBudgetMonthMenuModal.tsx
  packages/desktop-client/src/components/modals/EnvelopeBudgetSummaryModal.tsx
  packages/desktop-client/src/components/modals/ScheduledTransactionMenuModal.tsx
  packages/desktop-client/src/components/modals/TrackingBudgetMonthMenuModal.tsx
  packages/desktop-client/src/components/reports/DateRange.tsx
  packages/desktop-client/src/components/reports/Header.tsx
  packages/desktop-client/src/components/reports/ReportSummary.tsx
  packages/desktop-client/src/components/reports/graphs/CashFlowGraph.tsx
  packages/desktop-client/src/components/reports/reports/Calendar.tsx
  packages/desktop-client/src/components/reports/reports/CashFlow.tsx
  packages/desktop-client/src/components/reports/reports/CustomReport.tsx
  packages/desktop-client/src/components/reports/reports/NetWorth.tsx
  packages/desktop-client/src/components/reports/reports/NetWorthCard.tsx
  packages/desktop-client/src/components/reports/reports/Spending.tsx
  packages/desktop-client/src/components/reports/reports/Summary.tsx
  packages/desktop-client/src/components/reports/reports/SummaryCard.tsx
  packages/desktop-client/src/components/reports/spreadsheets/cash-flow-spreadsheet.tsx
  packages/desktop-client/src/components/reports/spreadsheets/net-worth-spreadsheet.ts
  packages/desktop-client/src/components/reports/spreadsheets/summary-spreadsheet.ts
  packages/desktop-client/src/components/rules/Value.tsx
  packages/desktop-client/src/components/schedules/DiscoverSchedules.tsx
  packages/desktop-client/src/components/schedules/ScheduleDetails.tsx
  packages/desktop-client/src/components/select/DateSelect.tsx
  packages/desktop-client/src/components/select/RecurringSchedulePicker.tsx
  packages/desktop-client/src/components/settings/LanguageSettings.tsx
  packages/desktop-client/src/hooks/useLocale.ts
  packages/loot-core/src/server/budget/actions.ts
  packages/loot-core/src/shared/locale.ts
  packages/loot-core/src/shared/months.ts
  packages/loot-core/src/shared/rules.ts
  packages/loot-core/src/shared/schedules.test.ts
  packages/loot-core/src/shared/schedules.ts
  packages/loot-core/src/shared/util.ts
  upcoming-release-notes/4211.md
Labels: :white_check_mark: Approved

#4555 :recycle: removing usages of MenuButton
  packages/desktop-client/src/components/accounts/Header.tsx
  packages/desktop-client/src/components/common/MenuButton.tsx
  packages/desktop-client/src/components/reports/Overview.tsx
  packages/desktop-client/src/components/reports/ReportCard.tsx
  upcoming-release-notes/4555.md
Labels: :white_check_mark: Approved

#4546 Display Goal/Target Information on Mobile
  packages/desktop-client/src/components/budget/BalanceWithCarryover.tsx
  packages/desktop-client/src/components/modals/EnvelopeBalanceMenuModal.tsx
  upcoming-release-notes/4546.md
Labels: :white_check_mark: Approved

#4126 [Redux Toolkit Migration] notificationsSlice
  packages/desktop-client/src/components/App.tsx
  packages/desktop-client/src/components/FinancesApp.tsx
  packages/desktop-client/src/components/Notifications.tsx
  packages/desktop-client/src/components/ServerContext.tsx
  packages/desktop-client/src/components/accounts/Account.tsx
  packages/desktop-client/src/components/admin/UserAccess/UserAccess.tsx
  packages/desktop-client/src/components/admin/UserAccess/UserAccessRow.tsx
  packages/desktop-client/src/components/admin/UserDirectory/UserDirectory.tsx
  packages/desktop-client/src/components/budget/index.tsx
  packages/desktop-client/src/components/manager/subscribe/OpenIdForm.tsx
  packages/desktop-client/src/components/mobile/transactions/TransactionList.tsx
  packages/desktop-client/src/components/modals/CreateAccountModal.tsx
  packages/desktop-client/src/components/modals/EditAccess.tsx
  packages/desktop-client/src/components/modals/EditUser.tsx
  packages/desktop-client/src/components/modals/TransferOwnership.tsx
  packages/desktop-client/src/components/modals/manager/ConfirmChangeDocumentDir.tsx
  packages/desktop-client/src/components/modals/manager/DuplicateFileModal.tsx
  packages/desktop-client/src/components/reports/Overview.tsx
  packages/desktop-client/src/components/reports/reports/Calendar.tsx
  packages/desktop-client/src/components/reports/reports/CashFlow.tsx
  packages/desktop-client/src/components/reports/reports/CustomReportListCards.tsx
  packages/desktop-client/src/components/reports/reports/NetWorth.tsx
  packages/desktop-client/src/components/reports/reports/Spending.tsx
  packages/desktop-client/src/components/reports/reports/Summary.tsx
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  packages/desktop-client/src/global-events.ts
  packages/desktop-client/src/hooks/useUndo.ts
  packages/desktop-client/src/index.tsx
  packages/loot-core/src/client/accounts/accountsSlice.ts
  packages/loot-core/src/client/actions/index.ts
  packages/loot-core/src/client/actions/notifications.ts
  packages/loot-core/src/client/notifications/notificationsSlice.ts
  packages/loot-core/src/client/queries/queriesSlice.ts
  packages/loot-core/src/client/reducers/index.ts
  packages/loot-core/src/client/reducers/notifications.ts
  packages/loot-core/src/client/shared-listeners.ts
  packages/loot-core/src/client/state-types/index.d.ts
  packages/loot-core/src/client/state-types/notifications.d.ts
  packages/loot-core/src/client/store/index.ts
  packages/loot-core/src/client/store/mock.ts
  packages/loot-core/src/server/budget/cleanup-template.ts
  packages/loot-core/src/server/budget/goaltemplates.ts
  packages/loot-core/src/server/budget/template-notes.ts
  packages/loot-core/src/server/budget/types/handlers.d.ts
  upcoming-release-notes/4126.md
Labels: :white_check_mark: Approved

#4560 Replace usage of deprecated Button in TransactionEdit with new Button component
  packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
  upcoming-release-notes/4560.md
Labels: :white_check_mark: Approved

#4557 :recycle: removing 'focused' prop from generic Input component
  packages/desktop-client/src/components/accounts/Reconcile.tsx
  packages/desktop-client/src/components/common/Input.tsx
  packages/desktop-client/src/components/common/InputWithContent.tsx
  packages/desktop-client/src/components/common/Modal.tsx
  packages/desktop-client/src/components/modals/EditFieldModal.tsx
  packages/desktop-client/src/components/select/DateSelect.tsx
  packages/desktop-client/src/components/util/AmountInput.tsx
  packages/desktop-client/src/components/util/PercentInput.tsx
  upcoming-release-notes/4557.md
Labels: :white_check_mark: Approved

#4556 :recycle: (components) moving select component to component library
  packages/component-library/package.json
  packages/component-library/src/Select.tsx
  packages/desktop-client/src/components/banksync/FieldMapping.tsx
  packages/desktop-client/src/components/filters/FiltersMenu.jsx
  packages/desktop-client/src/components/manager/subscribe/Login.tsx
  packages/desktop-client/src/components/manager/subscribe/OpenIdForm.tsx
  packages/desktop-client/src/components/modals/EditAccess.tsx
  packages/desktop-client/src/components/modals/EditRuleModal.jsx
  packages/desktop-client/src/components/modals/EditUser.tsx
  packages/desktop-client/src/components/modals/ImportTransactionsModal/DateFormatSelect.tsx
  packages/desktop-client/src/components/modals/ImportTransactionsModal/ImportTransactionsModal.jsx
  packages/desktop-client/src/components/modals/ImportTransactionsModal/SelectField.tsx
  packages/desktop-client/src/components/modals/TransferOwnership.tsx
  packages/desktop-client/src/components/reports/Header.tsx
  packages/desktop-client/src/components/reports/ReportSidebar.tsx
  packages/desktop-client/src/components/reports/reports/Spending.tsx
  packages/desktop-client/src/components/schedules/CustomUpcomingLength.tsx
  packages/desktop-client/src/components/schedules/UpcomingLength.tsx
  packages/desktop-client/src/components/select/RecurringSchedulePicker.tsx
  packages/desktop-client/src/components/settings/Format.tsx
  packages/desktop-client/src/components/settings/LanguageSettings.tsx
  packages/desktop-client/src/components/settings/Themes.tsx
  upcoming-release-notes/4556.md
Labels: :white_check_mark: Approved

#4476 [Mobile] Drag and drop on accounts to re-order
  packages/desktop-client/src/components/mobile/accounts/Accounts.tsx
  packages/desktop-client/src/components/mobile/transactions/TransactionListItem.tsx
  packages/loot-core/src/client/accounts/accountsSlice.ts
  packages/loot-core/src/server/accounts/app.ts
  packages/loot-core/src/server/db/index.ts
  packages/loot-core/src/server/db/sort.ts
  upcoming-release-notes/4476.md
Labels: :white_check_mark: Approved

#4559 Replace usage of deprecated Button component in MobileForms with new Button component
  packages/desktop-client/e2e/transactions.mobile.test.ts-snapshots/Mobile-Transactions-creates-a-transaction-from-accounts-id-page-1-chromium-linux.png
  packages/desktop-client/e2e/transactions.mobile.test.ts-snapshots/Mobile-Transactions-creates-a-transaction-from-accounts-id-page-2-chromium-linux.png
  packages/desktop-client/e2e/transactions.mobile.test.ts-snapshots/Mobile-Transactions-creates-a-transaction-from-accounts-id-page-3-chromium-linux.png
  packages/desktop-client/e2e/transactions.mobile.test.ts-snapshots/Mobile-Transactions-creates-a-transaction-via-footer-button-4-chromium-linux.png
  packages/desktop-client/e2e/transactions.mobile.test.ts-snapshots/Mobile-Transactions-creates-a-transaction-via-footer-button-5-chromium-linux.png
  packages/desktop-client/e2e/transactions.mobile.test.ts-snapshots/Mobile-Transactions-creates-a-transaction-via-footer-button-6-chromium-linux.png
  packages/desktop-client/src/components/mobile/MobileForms.tsx
  packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
  packages/desktop-client/src/components/modals/CoverModal.tsx
  packages/desktop-client/src/components/modals/TransferModal.tsx
  upcoming-release-notes/4559.md
Labels: :white_check_mark: Approved

#4563 :recycle: (components) moving Input component to comp. library
  packages/component-library/package.json
  packages/component-library/src/Input.tsx
  packages/desktop-client/src/components/common/InfoBubble.tsx
  packages/desktop-client/src/components/common/Input.ts
  packages/desktop-client/src/components/common/InputWithContent.tsx
  packages/desktop-client/src/style/styles.ts
  upcoming-release-notes/4563.md
Labels: :mag: Ready for review

#4564 Delete no longer used deprecated Button component
  packages/desktop-client/src/components/common/Button.tsx
  upcoming-release-notes/4564.md
Labels: :white_check_mark: Approved

#4572 Upgrade React Aria packages and address deprecated Section component warnings
  packages/component-library/package.json
  packages/desktop-client/package.json
  packages/desktop-client/src/components/mobile/transactions/TransactionList.tsx
  upcoming-release-notes/4572.md
  yarn.lock
Labels: :white_check_mark: Approved

#4533 🐛 Fix for var `ACTUAL_OPENID_ENFORCE`
  packages/desktop-client/src/components/manager/subscribe/Login.tsx
  packages/sync-server/src/app-account.js
  upcoming-release-notes/4533.md
Labels: :white_check_mark: Approved

#4578 :recycle: (components) rename SimpleTable to InfiniteScrollWrapper and cleanup
  packages/desktop-client/src/components/ManageRules.tsx
  packages/desktop-client/src/components/admin/UserAccess/UserAccess.tsx
  packages/desktop-client/src/components/admin/UserDirectory/UserDirectory.tsx
  packages/desktop-client/src/components/common/InfiniteScrollWrapper.tsx
  upcoming-release-notes/4578.md
Labels: :white_check_mark: Approved

#4585 Typo fix in OutOfSyncMigrationsModal
  packages/desktop-client/src/components/modals/OutOfSyncMigrationsModal.tsx
  upcoming-release-notes/4585.md
Labels: :white_check_mark: Approved

#4586 :bug: fix rules page table incorrect row heights
  packages/desktop-client/src/components/common/InfiniteScrollWrapper.tsx
  upcoming-release-notes/4586.md
Labels: :white_check_mark: Approved

#4482 [Mobile] Drag and drop income categories to re-order
  packages/desktop-client/src/components/mobile/accounts/Accounts.tsx
  packages/desktop-client/src/components/mobile/budget/BudgetCell.tsx
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  packages/desktop-client/src/components/mobile/budget/IncomeCategoryList.tsx
  packages/desktop-client/src/components/mobile/budget/IncomeGroup.tsx
  packages/loot-core/src/client/queries/queriesSlice.ts
  packages/loot-core/src/server/db/index.ts
  packages/loot-core/src/server/sync/sync.test.ts
  upcoming-release-notes/4482.md
Labels: :white_check_mark: Approved

#4568 :recycle: (components) refactor useResponsive and move to comp. lib
  packages/component-library/package.json
  packages/component-library/src/hooks/useResponsive.ts
  packages/desktop-client/src/components/App.tsx
  packages/desktop-client/src/components/FinancesApp.tsx
  packages/desktop-client/src/components/Notes.tsx
  packages/desktop-client/src/components/Notifications.tsx
  packages/desktop-client/src/components/Page.tsx
  packages/desktop-client/src/components/PrivacyFilter.tsx
  packages/desktop-client/src/components/ThemeSelector.tsx
  packages/desktop-client/src/components/Titlebar.tsx
  packages/desktop-client/src/components/autocomplete/AccountAutocomplete.tsx
  packages/desktop-client/src/components/autocomplete/Autocomplete.tsx
  packages/desktop-client/src/components/autocomplete/CategoryAutocomplete.tsx
  packages/desktop-client/src/components/autocomplete/ItemHeader.tsx
  packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.test.tsx
  packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.tsx
  packages/desktop-client/src/components/banksync/index.tsx
  packages/desktop-client/src/components/budget/BalanceWithCarryover.tsx
  packages/desktop-client/src/components/common/Modal.tsx
  packages/desktop-client/src/components/manager/BudgetList.tsx
  packages/desktop-client/src/components/manager/ManagementApp.tsx
  packages/desktop-client/src/components/manager/subscribe/Login.tsx
  packages/desktop-client/src/components/mobile/MobileNavTabs.tsx
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  packages/desktop-client/src/components/modals/AccountAutocompleteModal.tsx
  packages/desktop-client/src/components/modals/CategoryAutocompleteModal.tsx
  packages/desktop-client/src/components/modals/CloseAccountModal.tsx
  packages/desktop-client/src/components/modals/ConfirmTransactionDeleteModal.tsx
  packages/desktop-client/src/components/modals/CreateEncryptionKeyModal.tsx
  packages/desktop-client/src/components/modals/EditFieldModal.tsx
  packages/desktop-client/src/components/modals/FixEncryptionKeyModal.tsx
  packages/desktop-client/src/components/modals/PayeeAutocompleteModal.tsx
  packages/desktop-client/src/components/reports/Header.tsx
  packages/desktop-client/src/components/reports/Overview.tsx
  packages/desktop-client/src/components/reports/ReportCard.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableRow.tsx
  packages/desktop-client/src/components/reports/reports/Calendar.tsx
  packages/desktop-client/src/components/reports/reports/CalendarCard.tsx
  packages/desktop-client/src/components/reports/reports/CashFlow.tsx
  packages/desktop-client/src/components/reports/reports/CustomReport.tsx
  packages/desktop-client/src/components/reports/reports/GetCardData.tsx
  packages/desktop-client/src/components/reports/reports/NetWorth.tsx
  packages/desktop-client/src/components/reports/reports/NetWorthCard.tsx
  packages/desktop-client/src/components/reports/reports/Spending.tsx
  packages/desktop-client/src/components/reports/reports/Summary.tsx
  packages/desktop-client/src/components/responsive/ResponsiveProvider.tsx
  packages/desktop-client/src/components/responsive/index.tsx
  packages/desktop-client/src/components/settings/index.tsx
  packages/desktop-client/src/components/sidebar/Sidebar.tsx
  packages/desktop-client/src/components/sidebar/SidebarProvider.tsx
  packages/desktop-client/src/components/sidebar/index.tsx
  packages/desktop-client/src/components/transactions/TransactionsTable.test.tsx
  packages/desktop-client/src/hooks/useUndo.ts
  upcoming-release-notes/4568.md
  yarn.lock
Labels: :white_check_mark: Approved

#4566 :recycle: (components) remove InputWithContent component
  packages/desktop-client/e2e/accounts.mobile.test.ts-snapshots/Mobile-Accounts-opens-individual-account-page-and-checks-that-filtering-is-working-6-chromium-linux.png
  packages/desktop-client/e2e/accounts.mobile.test.ts-snapshots/Mobile-Accounts-opens-individual-account-page-and-checks-that-filtering-is-working-9-chromium-linux.png
  packages/desktop-client/src/components/common/InputWithContent.tsx
  packages/desktop-client/src/components/common/Search.tsx
  packages/desktop-client/src/components/mobile/transactions/TransactionListWithBalances.tsx
  packages/desktop-client/src/components/util/AmountInput.tsx
  upcoming-release-notes/4566.md
Labels: :white_check_mark: Approved

#4604 fix: align action buttons in modal for confirming transaction edit
  packages/desktop-client/src/components/modals/ConfirmTransactionEditModal.tsx
  upcoming-release-notes/4604.md
Labels: :white_check_mark: Approved

#4606 Swipe to dismiss notifications
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-applies-budget-template-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-applies-budget-template-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-applies-budget-template-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-copies-last-month-s-budget-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-copies-last-month-s-budget-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-copies-last-month-s-budget-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-set-budget-to-12-month-average-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-set-budget-to-12-month-average-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-set-budget-to-12-month-average-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-set-budget-to-3-month-average-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-set-budget-to-3-month-average-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-set-budget-to-3-month-average-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-set-budget-to-6-month-average-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-set-budget-to-6-month-average-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-set-budget-to-6-month-average-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-updates-the-budgeted-amount-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-updates-the-budgeted-amount-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Envelope-updates-the-budgeted-amount-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-applies-budget-template-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-applies-budget-template-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-applies-budget-template-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-copies-last-month-s-budget-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-copies-last-month-s-budget-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-copies-last-month-s-budget-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-set-budget-to-12-month-average-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-set-budget-to-12-month-average-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-set-budget-to-12-month-average-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-set-budget-to-3-month-average-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-set-budget-to-3-month-average-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-set-budget-to-3-month-average-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-set-budget-to-6-month-average-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-set-budget-to-6-month-average-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-set-budget-to-6-month-average-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-updates-the-budgeted-amount-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-updates-the-budgeted-amount-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-updates-the-budgeted-amount-3-chromium-linux.png
  packages/desktop-client/package.json
  packages/desktop-client/src/components/Notifications.tsx
  upcoming-release-notes/4606.md
  yarn.lock
Labels: :white_check_mark: Approved

#4605 :recycle: (sync-server) align dependency versions; cleanup lint & typecheck
  package.json
  packages/api/__snapshots__/methods.test.ts.snap
  packages/api/package.json
  packages/crdt/package.json
  packages/crdt/src/crdt/__snapshots__/merkle.test.ts.snap
  packages/desktop-client/package.json
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  packages/desktop-client/src/components/modals/CreateEncryptionKeyModal.tsx
  packages/desktop-electron/package.json
  packages/loot-core/package.json
  packages/loot-core/peg-transform.mjs
  packages/loot-core/src/server/__snapshots__/backups.test.ts.snap
  packages/loot-core/src/server/__snapshots__/main.test.ts.snap
  packages/loot-core/src/server/__snapshots__/sheet.test.ts.snap
  packages/loot-core/src/server/accounts/__snapshots__/sync.test.ts.snap
  packages/loot-core/src/server/db/__snapshots__/index.test.ts.snap
  packages/loot-core/src/server/migrate/__snapshots__/migrations.test.ts.snap
  packages/loot-core/src/server/sync/__snapshots__/sync.test.ts.snap
  packages/loot-core/src/server/transactions/__snapshots__/transaction-rules.test.ts.snap
  packages/loot-core/src/server/transactions/__snapshots__/transfer.test.ts.snap
  packages/loot-core/src/server/transactions/import/__snapshots__/parse-file.test.ts.snap
  packages/loot-core/src/shared/__snapshots__/months.test.ts.snap
  packages/sync-server/package.json
  upcoming-release-notes/4605.md
  yarn.lock
Labels: :white_check_mark: Approved

#4609 :recycle: (loot-core) updated all data model imports to use barrel file
  packages/desktop-client/src/components/admin/UserAccess/UserAccess.tsx
  packages/desktop-client/src/components/admin/UserDirectory/UserDirectory.tsx
  packages/desktop-client/src/components/admin/UserDirectory/UserDirectoryRow.tsx
  packages/desktop-client/src/components/autocomplete/FilterAutocomplete.tsx
  packages/desktop-client/src/components/autocomplete/ReportAutocomplete.tsx
  packages/desktop-client/src/components/banksync/AccountRow.tsx
  packages/desktop-client/src/components/banksync/AccountsList.tsx
  packages/desktop-client/src/components/banksync/EditSyncAccount.tsx
  packages/desktop-client/src/components/filters/FiltersStack.tsx
  packages/desktop-client/src/components/filters/SavedFilterMenuButton.tsx
  packages/desktop-client/src/components/manager/subscribe/Login.tsx
  packages/desktop-client/src/components/manager/subscribe/OpenIdForm.tsx
  packages/desktop-client/src/components/mobile/transactions/TransactionList.tsx
  packages/desktop-client/src/components/mobile/transactions/TransactionListItem.tsx
  packages/desktop-client/src/components/mobile/transactions/TransactionListWithBalances.tsx
  packages/desktop-client/src/components/modals/EditUser.tsx
  packages/desktop-client/src/components/modals/OpenIDEnableModal.tsx
  packages/desktop-client/src/components/modals/PluggyAiInitialiseModal.tsx
  packages/desktop-client/src/components/reports/ChooseGraph.tsx
  packages/desktop-client/src/components/reports/ReportSidebar.tsx
  packages/desktop-client/src/components/reports/ReportSummary.tsx
  packages/desktop-client/src/components/reports/ReportTopbar.tsx
  packages/desktop-client/src/components/reports/SaveReportName.tsx
  packages/desktop-client/src/components/reports/graphs/AreaGraph.tsx
  packages/desktop-client/src/components/reports/graphs/BarGraph.tsx
  packages/desktop-client/src/components/reports/graphs/DonutGraph.tsx
  packages/desktop-client/src/components/reports/graphs/LineGraph.tsx
  packages/desktop-client/src/components/reports/graphs/SpendingGraph.tsx
  packages/desktop-client/src/components/reports/graphs/StackedBarGraph.tsx
  packages/desktop-client/src/components/reports/graphs/showActivity.ts
  packages/desktop-client/src/components/reports/graphs/tableGraph/RenderTableRow.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTable.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableHeader.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableList.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableRow.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableTotals.tsx
  packages/desktop-client/src/components/reports/reports/CustomReport.tsx
  packages/desktop-client/src/components/reports/reports/CustomReportListCards.tsx
  packages/desktop-client/src/components/reports/reports/GetCardData.tsx
  packages/desktop-client/src/components/reports/reports/Spending.tsx
  packages/desktop-client/src/components/reports/setSessionReport.ts
  packages/desktop-client/src/components/reports/spreadsheets/calculateLegend.ts
  packages/desktop-client/src/components/reports/spreadsheets/custom-spreadsheet.ts
  packages/desktop-client/src/components/reports/spreadsheets/filterEmptyRows.ts
  packages/desktop-client/src/components/reports/spreadsheets/grouped-spreadsheet.ts
  packages/desktop-client/src/components/reports/spreadsheets/recalculate.ts
  packages/desktop-client/src/components/reports/spreadsheets/sortData.ts
  packages/desktop-client/src/components/reports/spreadsheets/spending-spreadsheet.ts
  packages/desktop-client/src/hooks/useFilters.ts
  packages/desktop-client/src/hooks/usePluggyAiStatus.ts
  packages/loot-core/src/shared/user.ts
  packages/loot-core/src/types/models/index.d.ts
  packages/loot-core/src/types/models/user.ts
  upcoming-release-notes/4609.md
Labels: :white_check_mark: Approved

#4613 :recycle: solve most peer dependency issues reported on install
  packages/component-library/package.json
  packages/desktop-client/package.json
  packages/desktop-client/src/components/budget/envelope/budgetsummary/BudgetSummary.tsx
  packages/desktop-client/src/components/budget/index.tsx
  packages/desktop-client/src/components/budget/tracking/budgetsummary/BudgetSummary.tsx
  packages/eslint-plugin-actual/package.json
  packages/loot-core/package.json
  packages/sync-server/package.json
  upcoming-release-notes/4613.md
  yarn.lock
Labels: :white_check_mark: Approved

#4536 Modified transaction edit button on mobile to display "Add New Split"
  packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
  upcoming-release-notes/4536.md
Labels: :white_check_mark: Approved

#4600 improvement: enable collapse split transactions with searches or filters
  packages/desktop-client/e2e/transactions.test.ts-snapshots/Transactions-filters-transactions-by-category-7-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.ts-snapshots/Transactions-filters-transactions-by-category-8-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.ts-snapshots/Transactions-filters-transactions-by-category-9-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.ts-snapshots/Transactions-filters-transactions-by-date-7-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.ts-snapshots/Transactions-filters-transactions-by-date-8-chromium-linux.png
  packages/desktop-client/e2e/transactions.test.ts-snapshots/Transactions-filters-transactions-by-date-9-chromium-linux.png
  packages/desktop-client/src/components/accounts/Header.tsx
  upcoming-release-notes/4600.md
Labels: :white_check_mark: Approved

#4621 [Mobile] Click on income category balance to show transactions
  packages/desktop-client/src/components/budget/envelope/EnvelopeBudgetComponents.tsx
  packages/desktop-client/src/components/mobile/budget/IncomeCategoryList.tsx
  upcoming-release-notes/4621.md
Labels: :white_check_mark: Approved

#4620 Remove height transition animation from modals when adjusting to viewport height for smoother experience
  packages/desktop-client/src/components/common/Modal.tsx
  upcoming-release-notes/4620.md
Labels: :white_check_mark: Approved

#4428 🔨 OPENID: Refactor mixed stuff
  packages/sync-server/package.json
  packages/sync-server/src/account-db.js
  packages/sync-server/src/app.js
  packages/sync-server/src/config-types.ts
  upcoming-release-notes/4428.md
Labels: :white_check_mark: Approved

#4127 [Redux Toolkit Migration] prefsSlice
  packages/desktop-client/src/browser-preload.browser.js
  packages/desktop-client/src/components/App.tsx
  packages/desktop-client/src/components/modals/CreateEncryptionKeyModal.tsx
  packages/desktop-client/src/components/settings/index.tsx
  packages/desktop-client/src/global-events.ts
  packages/desktop-client/src/hooks/useGlobalPref.ts
  packages/desktop-client/src/hooks/useMetadataPref.ts
  packages/desktop-client/src/hooks/useSyncedPref.ts
  packages/desktop-client/src/hooks/useSyncedPrefs.ts
  packages/desktop-client/src/index.tsx
  packages/desktop-electron/index.ts
  packages/loot-core/src/client/actions/index.ts
  packages/loot-core/src/client/actions/prefs.ts
  packages/loot-core/src/client/actions/user.ts
  packages/loot-core/src/client/app/appSlice.ts
  packages/loot-core/src/client/budgets/budgetsSlice.ts
  packages/loot-core/src/client/prefs/prefsSlice.ts
  packages/loot-core/src/client/reducers/index.ts
  packages/loot-core/src/client/reducers/prefs.ts
  packages/loot-core/src/client/shared-listeners.ts
  packages/loot-core/src/client/state-types/index.d.ts
  packages/loot-core/src/client/state-types/prefs.d.ts
  packages/loot-core/src/client/store/index.ts
  packages/loot-core/src/client/store/mock.ts
  packages/loot-core/src/server/preferences/app.ts
  upcoming-release-notes/4127.md
Labels: :white_check_mark: Approved

#4526 :electron: Embed the sync-server (experimental)
  bin/package-electron
  package.json
  packages/desktop-electron/index.ts
  packages/desktop-electron/package.json
  packages/loot-core/src/types/prefs.d.ts
  packages/sync-server/src/app.js
  upcoming-release-notes/4526.md
  yarn.lock
Labels: :white_check_mark: Approved

#4610 :recycle: (loot-core) unify some electron/web/api logic
  packages/loot-core/src/mocks/setup.ts
  packages/loot-core/src/platform/client/undo/index.d.ts
  packages/loot-core/src/platform/client/undo/index.ts
  packages/loot-core/src/platform/exceptions/__mocks__/index.ts
  packages/loot-core/src/platform/exceptions/index.browser.ts
  packages/loot-core/src/platform/exceptions/index.d.ts
  packages/loot-core/src/platform/exceptions/index.electron.ts
  packages/loot-core/src/platform/exceptions/index.testing.ts
  packages/loot-core/src/platform/exceptions/index.ts
  packages/loot-core/src/platform/exceptions/index.web.ts
  packages/loot-core/src/platform/server/log/index.api.ts
  packages/loot-core/src/platform/server/log/index.d.ts
  packages/loot-core/src/platform/server/log/index.electron.ts
  packages/loot-core/src/platform/server/log/index.ts
  packages/loot-core/src/platform/server/log/index.web.ts
  upcoming-release-notes/4610.md
Labels: :white_check_mark: Approved

#4628 🐛 Pluggy.ai credit card transactions were inverted
  packages/sync-server/src/app-pluggyai/app-pluggyai.js
  upcoming-release-notes/4628.md
Labels: :white_check_mark: Approved

#4627 🐛 added null/undefined check for scheduleIsRecurring
  packages/loot-core/src/shared/schedules.ts
  upcoming-release-notes/4627.md
Labels: :white_check_mark: Approved

#4128 [Redux Toolkit Migration] usersSlice [Final PR]
  packages/desktop-client/src/components/App.tsx
  packages/desktop-client/src/components/LoggedInUser.tsx
  packages/desktop-client/src/components/admin/UserAccess/UserAccessRow.tsx
  packages/desktop-client/src/components/admin/UserDirectory/UserDirectory.tsx
  packages/desktop-client/src/components/manager/BudgetList.tsx
  packages/desktop-client/src/components/manager/ConfigServer.tsx
  packages/desktop-client/src/components/manager/ManagementApp.tsx
  packages/desktop-client/src/components/manager/subscribe/Login.tsx
  packages/desktop-client/src/components/manager/subscribe/OpenIdCallback.ts
  packages/desktop-client/src/components/modals/EditAccess.tsx
  packages/desktop-client/src/components/modals/EditUser.tsx
  packages/desktop-client/src/index.tsx
  packages/loot-core/src/client/accounts/accountsSlice.ts
  packages/loot-core/src/client/actions/index.ts
  packages/loot-core/src/client/actions/user.ts
  packages/loot-core/src/client/app/appSlice.ts
  packages/loot-core/src/client/budgets/budgetsSlice.ts
  packages/loot-core/src/client/constants.ts
  packages/loot-core/src/client/modals/modalsSlice.ts
  packages/loot-core/src/client/notifications/notificationsSlice.ts
  packages/loot-core/src/client/prefs/prefsSlice.ts
  packages/loot-core/src/client/queries/queriesSlice.ts
  packages/loot-core/src/client/reducers/index.ts
  packages/loot-core/src/client/reducers/user.ts
  packages/loot-core/src/client/shared-listeners.ts
  packages/loot-core/src/client/state-types/index.d.ts
  packages/loot-core/src/client/state-types/user.d.ts
  packages/loot-core/src/client/store/index.ts
  packages/loot-core/src/client/store/mock.ts
  packages/loot-core/src/client/users/usersSlice.ts
  upcoming-release-notes/4128.md
Labels: :white_check_mark: Approved

#4635 📚 More translations for rules and fields
  packages/desktop-client/src/components/filters/FiltersButton.tsx
  packages/desktop-client/src/components/filters/FiltersMenu.jsx
  packages/desktop-client/src/components/modals/EditRuleModal.jsx
  packages/desktop-client/src/components/rules/Value.tsx
  packages/desktop-client/src/components/select/RecurringSchedulePicker.tsx
  packages/desktop-client/src/components/util/GenericInput.jsx
  packages/loot-core/src/client/data-hooks/schedules.tsx
  packages/loot-core/src/shared/schedules.ts
  upcoming-release-notes/4635.md
Labels: :white_check_mark: Approved

#4640 :recycle: (api) do not bundle test files in package output
  packages/api/tsconfig.dist.json
  upcoming-release-notes/4640.md
Labels: :white_check_mark: Approved

#4641 :arrow_up: upgrade yarn from v4.3.1 to v4.7.0
  .yarn/releases/yarn-4.3.1.cjs
  .yarn/releases/yarn-4.7.0.cjs
  .yarnrc.yml
  package.json
  upcoming-release-notes/4641.md
  yarn.lock
Labels: :white_check_mark: Approved

#4442 Extract budget category related server handlers from main.ts to server/budget/app.ts
  packages/loot-core/src/mocks/budget.ts
  packages/loot-core/src/server/budget/app.ts
  packages/loot-core/src/server/budget/types/handlers.d.ts
  packages/loot-core/src/server/db/index.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/server/models.ts
  packages/loot-core/src/types/handlers.d.ts
  upcoming-release-notes/4442.md
Labels: :white_check_mark: Approved

#4632 :recycle: removal of '.testing.ts' file extensions in favour of mocks
  packages/api/jest.config.js
  packages/loot-core/jest.config.js
  packages/loot-core/jest.web.config.js
  packages/loot-core/src/client/__mocks__/platform.web.ts
  packages/loot-core/src/mocks/setup.ts
  packages/loot-core/src/platform/client/fetch/__mocks__/index.ts
  packages/loot-core/src/platform/client/fetch/index.browser.ts
  packages/loot-core/src/platform/client/fetch/index.testing.ts
  packages/loot-core/src/platform/client/fetch/index.ts
  packages/loot-core/src/platform/server/asyncStorage/__mocks__/index.ts
  packages/loot-core/src/platform/server/asyncStorage/index.electron.ts
  packages/loot-core/src/platform/server/asyncStorage/index.ts
  packages/loot-core/src/platform/server/connection/__mocks__/index.ts
  packages/loot-core/src/platform/server/connection/index.api.ts
  packages/loot-core/src/platform/server/connection/index.d.ts
  packages/loot-core/src/platform/server/connection/index.electron.ts
  packages/loot-core/src/platform/server/connection/index.ts
  packages/loot-core/src/platform/server/fetch/__mocks__/index.ts
  packages/loot-core/src/platform/server/fetch/index.d.ts
  packages/loot-core/src/platform/server/fetch/index.ts
  packages/loot-core/src/server/cloud-storage.ts
  upcoming-release-notes/4632.md
Labels: :white_check_mark: Approved

#4647 Simplify Modals component by destructuring modal.options instead of passing options one by one
  packages/desktop-client/src/components/Modals.tsx
  upcoming-release-notes/4647.md
Labels: :white_check_mark: Approved

#4650 Update server handlers to use the implementation function type instead of duplicating the function arguments/return types
  packages/desktop-client/src/components/admin/UserAccess/UserAccessRow.tsx
  packages/desktop-client/src/components/modals/MergeUnusedPayeesModal.tsx
  packages/desktop-client/src/components/schedules/ScheduleDetails.tsx
  packages/loot-core/src/server/admin/app.ts
  packages/loot-core/src/server/admin/types/handlers.ts
  packages/loot-core/src/server/dashboard/app.ts
  packages/loot-core/src/server/dashboard/types/handlers.d.ts
  packages/loot-core/src/server/filters/app.ts
  packages/loot-core/src/server/filters/types/handlers.d.ts
  packages/loot-core/src/server/notes/app.ts
  packages/loot-core/src/server/notes/types/handlers.d.ts
  packages/loot-core/src/server/reports/app.ts
  packages/loot-core/src/server/reports/types/handlers.ts
  packages/loot-core/src/server/rules/app.ts
  packages/loot-core/src/server/rules/types/handlers.ts
  packages/loot-core/src/server/schedules/app.ts
  packages/loot-core/src/server/schedules/find-schedules.ts
  packages/loot-core/src/server/schedules/types/handlers.ts
  packages/loot-core/src/server/tools/app.ts
  packages/loot-core/src/server/tools/types/handlers.d.ts
  packages/loot-core/src/types/handlers.d.ts
  packages/loot-core/src/types/models/index.d.ts
  packages/loot-core/src/types/models/user-access.d.ts
  packages/loot-core/src/types/models/user.d.ts
  upcoming-release-notes/4650.md
Labels: :white_check_mark: Approved

#4648 add weblate widget to readme
  README.md
Labels: :white_check_mark: Approved

#4592 :recycle: moved loot-core import resolution from TS to yarn workspaces
  packages/desktop-client/package.json
  packages/desktop-client/src/components/Titlebar.tsx
  packages/desktop-client/src/components/reports/reports/CustomReportListCards.tsx
  packages/desktop-client/src/components/sidebar/BudgetName.tsx
  packages/loot-core/package.json
  tsconfig.json
  upcoming-release-notes/4592.md
  yarn.lock
Labels: :white_check_mark: Approved

#4644 ✨ Bank sync avoid reimporting deleted transactions
  packages/desktop-client/src/components/banksync/EditSyncAccount.tsx
  packages/loot-core/src/server/accounts/__snapshots__/sync.test.ts.snap
  packages/loot-core/src/server/accounts/sync.test.ts
  packages/loot-core/src/server/accounts/sync.ts
  packages/loot-core/src/types/prefs.d.ts
  upcoming-release-notes/4644.md
Labels: :white_check_mark: Approved

#4646 ✨ Add org name to bank sync UI
  packages/desktop-client/src/components/modals/SelectLinkedAccountsModal.jsx
  upcoming-release-notes/4646.md
Labels: :sparkles: Merged

#4595 Added CZ AirBank to banks with only 90 days of history
  packages/sync-server/src/app-gocardless/bank-factory.js
  upcoming-release-notes/4595.md
Labels: :white_check_mark: Approved

#4652 :bug: (reports) fix conditionsOp not applying for saved reports
  packages/desktop-client/src/components/reports/reports/CustomReport.tsx
  upcoming-release-notes/4652.md
Labels: :white_check_mark: Approved

#4651 :bug: (mobile) fix for iOS - keyboard focus when editing budget
  packages/desktop-client/package.json
  packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
  packages/desktop-client/src/components/modals/EnvelopeBudgetMenuModal.tsx
  packages/desktop-client/src/components/modals/TrackingBudgetMenuModal.tsx
  packages/loot-core/package.json
  packages/loot-core/src/client/__mocks__/platform.web.ts
  packages/loot-core/src/client/platform.electron.ts
  packages/loot-core/src/client/platform.ts
  packages/loot-core/src/client/platform.web.ts
  upcoming-release-notes/4651.md
  yarn.lock
Labels: :white_check_mark: Approved

#4629 🐛 fixed current month upcoming calculation
  packages/loot-core/src/client/data-hooks/transactions.ts
  packages/loot-core/src/shared/schedules.test.ts
  packages/loot-core/src/shared/schedules.ts
  upcoming-release-notes/4629.md
Labels: :white_check_mark: Approved

#4649 Extract spreadsheet related server handlers from main.ts to server/spreadsheet/app.ts
  packages/desktop-client/src/components/transactions/TransactionsTable.test.tsx
  packages/loot-core/src/client/SpreadsheetProvider.tsx
  packages/loot-core/src/platform/client/fetch/index.d.ts
  packages/loot-core/src/server/budget/app.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/server/spreadsheet/app.ts
  packages/loot-core/src/server/spreadsheet/spreadsheet.ts
  packages/loot-core/src/shared/async.ts
  packages/loot-core/src/types/handlers.d.ts
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/4649.md
Labels: :white_check_mark: Approved

#4665 🐛 Allowing service worker to cache files up to 5mb - fixes edge & offline mode
  packages/desktop-client/vite.config.mts
  upcoming-release-notes/4665.md
Labels: :white_check_mark: Approved

#4656 bump various dependencies
  package.json
  packages/api/package.json
  packages/component-library/package.json
  packages/crdt/package.json
  packages/desktop-client/package.json
  packages/desktop-client/src/hooks/useLocalPref.ts
  packages/desktop-electron/package.json
  packages/eslint-plugin-actual/package.json
  packages/loot-core/package.json
  packages/loot-core/src/platform/server/fs/index.electron.ts
  packages/sync-server/package.json
  upcoming-release-notes/4656.md
  yarn.lock
Labels: :white_check_mark: Approved, dependencies

#4625 Fix nested button error in budget file selection page
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/manager/BudgetFileSelection.tsx
  packages/desktop-client/src/components/manager/ManagementApp.tsx
  packages/desktop-client/src/components/modals/BudgetListModal.tsx
  upcoming-release-notes/4625.md
Labels: :white_check_mark: Approved

#4668 :electron: Fix electron loot core resolutions
  packages/desktop-electron/package.json
  tsconfig.json
  upcoming-release-notes/4668.md
Labels: :white_check_mark: Approved

#4670 Fix error on budget file selection page when using server
  packages/desktop-client/src/components/Modals.tsx
  packages/desktop-client/src/components/manager/BudgetFileSelection.tsx
  packages/desktop-client/src/components/mobile/budget/index.tsx
  packages/desktop-client/src/components/modals/BudgetFileSelectionModal.tsx
  packages/loot-core/src/client/modals/modalsSlice.ts
  upcoming-release-notes/4670.md
Labels: :white_check_mark: Approved

#4667 🐛 Fixed GoCardless SelectLinkedAccounts institution bug
  packages/desktop-client/src/components/modals/SelectLinkedAccountsModal.jsx
  upcoming-release-notes/4667.md
Labels: :white_check_mark: Approved

#4661 Extract sync related server handlers from main.ts to server/sync/app.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/server/sync/app.ts
  packages/loot-core/src/types/handlers.d.ts
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/4661.md
Labels: :white_check_mark: Approved

#4623 🐛 [Bug] fixed bug in Accounts.tsx for applying rules that split transactions
  packages/desktop-client/src/components/accounts/Account.tsx
  upcoming-release-notes/4623.md
Labels: :white_check_mark: Approved

#4675 🐛 fixed can't rename notes
  packages/loot-core/src/server/aql/schema/index.ts
  upcoming-release-notes/4675.md
Labels: :white_check_mark: Approved

#4677 Local docker build fix
  sync-server.Dockerfile
  upcoming-release-notes/4677.md
Labels: :white_check_mark: Approved

#4686 🐛 [Bug] Cant edit template rules
  packages/desktop-client/src/components/modals/EditRuleModal.jsx
  upcoming-release-notes/4686.md
Labels: :white_check_mark: Approved

#4680 [Mobile] Show hidden overspent categories on Cover overspending modal
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  upcoming-release-notes/4680.md
Labels: :white_check_mark: Approved

#4683 fix: apply filters in Reports dashboard for cash flow widget
  packages/desktop-client/src/components/reports/spreadsheets/cash-flow-spreadsheet.tsx
  upcoming-release-notes/4683.md
Labels: :white_check_mark: Approved

#4689 Fix error spread in non-batch bank sync
  packages/loot-core/src/server/api.test.ts
  packages/loot-core/src/server/api.ts
  upcoming-release-notes/4689.md
Labels: :white_check_mark: Approved

#4626 Fix for iss parameter missing from openid response
  packages/sync-server/src/accounts/openid.js
  upcoming-release-notes/4626.md
Labels: :white_check_mark: Approved

#4697 🐛 Fix `Make Transfer` closing the Popover when clicked
  packages/desktop-client/src/components/autocomplete/Autocomplete.tsx
  upcoming-release-notes/4697.md
Labels: :white_check_mark: Approved

#4712 🐛 Fix pluggy.ai foreigner currency transaction
  packages/sync-server/src/app-pluggyai/app-pluggyai.js
  upcoming-release-notes/4712.md
Labels: :white_check_mark: Approved

#4716 :bug: fix menu not closing when menu item is clicked
  packages/component-library/src/Menu.tsx
  packages/desktop-client/e2e/page-models/mobile-budget-page.ts
  packages/desktop-client/e2e/page-models/mobile-category-menu-modal.ts
  packages/desktop-client/src/components/accounts/Header.tsx
  packages/desktop-client/src/components/modals/CreateAccountModal.tsx
  packages/desktop-client/src/components/reports/Overview.tsx
  upcoming-release-notes/4716.md
Labels: :white_check_mark: Approved
