Repository actualbudget/actual, pull requests merged in 2025-10, with the labels that each got.

#5831 fix decimal input in amount input boxes
  packages/loot-core/src/shared/rules.ts
  upcoming-release-notes/5831.md
Labels: :white_check_mark: approved

#5843 🛠️ Add retries to electron loot-core import
  package.json
  packages/desktop-electron/server.ts
  upcoming-release-notes/5843.md
Labels: :white_check_mark: approved

#5641 ✨ Reports - Add an option to trim the start & end intervals
  packages/desktop-client/src/components/reports/ReportOptions.ts
  packages/desktop-client/src/components/reports/ReportSidebar.tsx
  packages/desktop-client/src/components/reports/reports/CustomReport.tsx
  packages/desktop-client/src/components/reports/reports/GetCardData.tsx
  packages/desktop-client/src/components/reports/spreadsheets/custom-spreadsheet.ts
  packages/desktop-client/src/components/reports/spreadsheets/grouped-spreadsheet.ts
  packages/desktop-client/src/components/reports/spreadsheets/trimIntervals.ts
  packages/desktop-client/src/hooks/useReports.ts
  packages/loot-core/migrations/1759260219000_add_trim_interval_report_setting.sql
  packages/loot-core/src/server/aql/schema/index.ts
  packages/loot-core/src/server/reports/app.ts
  packages/loot-core/src/types/models/reports.ts
  upcoming-release-notes/5641.md
Labels: :white_check_mark: approved

#5838 add average per year calculation to the summary report
  packages/desktop-client/src/components/reports/reports/Summary.tsx
  packages/desktop-client/src/components/reports/spreadsheets/summary-spreadsheet.ts
  packages/loot-core/src/types/models/dashboard.ts
  upcoming-release-notes/5838.md
Labels: :white_check_mark: approved

#5827 expand eslint untranslated string rule
  packages/desktop-client/src/components/manager/ManagementApp.tsx
  packages/desktop-client/src/components/modals/CreateAccountModal.tsx
  packages/desktop-client/src/components/modals/LoadBackupModal.tsx
  packages/desktop-client/src/components/payees/ManagePayees.tsx
  packages/desktop-client/src/components/reports/reports/NetWorth.tsx
  packages/eslint-plugin-actual/lib/rules/no-untranslated-strings.js
  packages/eslint-plugin-actual/lib/rules/prefer-logger-over-console.js
  packages/eslint-plugin-actual/lib/rules/prefer-trans-over-t.js
  packages/eslint-plugin-actual/lib/utils/import-helpers.js
  upcoming-release-notes/5827.md
Labels: :white_check_mark: approved

#5807 fix: losing transaction amount decimals on update
  packages/desktop-client/src/components/transactions/TransactionsTable.tsx
  upcoming-release-notes/5807.md
Labels: :white_check_mark: approved

#5747 Align amount conversion utilities between api and loot-core
  packages/api/utils.js
  packages/api/utils.ts
  packages/loot-core/src/server/importers/ynab4.ts
  upcoming-release-notes/5747.md
Labels: :white_check_mark: approved

#5842 Mobile payees - add loading indicator to rules count label
  packages/desktop-client/src/components/mobile/payees/MobilePayeesPage.tsx
  packages/desktop-client/src/components/mobile/payees/PayeesList.tsx
  packages/desktop-client/src/components/mobile/payees/PayeesListItem.tsx
  packages/desktop-client/src/components/payees/ManagePayeesWithData.tsx
  packages/desktop-client/src/components/payees/PayeeRuleCountLabel.tsx
  packages/desktop-client/src/hooks/usePayeeRuleCounts.ts
  upcoming-release-notes/5842.md
Labels: :white_check_mark: approved, AI generated

#5858 ♻️ bump non-react deps in desktop-client
  .github/workflows/e2e-test.yml
  .github/workflows/update-vrt.yml
  bin/run-vrt
  package.json
  packages/desktop-client/README.md
  packages/desktop-client/index.html
  packages/desktop-client/package.json
  packages/desktop-client/src/components/autocomplete/Autocomplete.tsx
  packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.test.tsx
  packages/desktop-client/src/components/forms.tsx
  packages/desktop-client/src/index.tsx
  packages/desktop-client/vite.config.mts
  packages/desktop-electron/package.json
  packages/loot-core/package.json
  upcoming-release-notes/5858.md
  yarn.lock
Labels: :white_check_mark: approved, dependencies

#5870 run schedule rules regardless of posted date
  packages/loot-core/src/server/transactions/transaction-rules.ts
  upcoming-release-notes/5870.md
Labels: :white_check_mark: approved

#5848 feat(currency): add LKR and CRC currencies
  packages/desktop-client/src/components/settings/Currency.tsx
  packages/loot-core/src/shared/currencies.ts
  upcoming-release-notes/5848.md
Labels: :white_check_mark: approved

#5847 :electron: Hide the Electron menu
  package.json
  packages/desktop-client/src/browser-preload.browser.js
  packages/desktop-client/src/components/App.tsx
  packages/desktop-client/src/components/Titlebar.tsx
  packages/desktop-client/src/components/sidebar/BudgetName.tsx
  packages/desktop-client/src/index.tsx
  packages/desktop-electron/e2e/__screenshots__/onboarding.test.ts/Onboarding-checks-the-page-visuals-1-linux.png
  packages/desktop-electron/e2e/__screenshots__/onboarding.test.ts/Onboarding-checks-the-page-visuals-2-linux.png
  packages/desktop-electron/index.ts
  packages/desktop-electron/menu.ts
  packages/desktop-electron/preload.ts
  packages/loot-core/typings/window.ts
  upcoming-release-notes/5847.md
Labels: :white_check_mark: approved

#5824 Mobile payees - swipe to delete
  packages/desktop-client/src/components/mobile/ActionableGridListItem.tsx
  packages/desktop-client/src/components/mobile/payees/MobilePayeesPage.tsx
  packages/desktop-client/src/components/mobile/payees/PayeesList.tsx
  packages/desktop-client/src/components/mobile/payees/PayeesListItem.tsx
  upcoming-release-notes/5824.md
Labels: :white_check_mark: approved, AI generated

#5876 Added support for Uzbek Soum (UZS) currency
  packages/desktop-client/src/components/settings/Currency.tsx
  packages/loot-core/src/shared/currencies.ts
  upcoming-release-notes/5876.md
Labels: :white_check_mark: approved

#5869 Added ARS currency
  packages/desktop-client/src/components/settings/Currency.tsx
  packages/loot-core/src/shared/currencies.ts
  upcoming-release-notes/5869.md
Labels: :mag: ready for review

#5812 📚 More Translations
  packages/desktop-client/src/budget/budgetSlice.ts
  packages/desktop-client/src/components/modals/EnvelopeBudgetMonthMenuModal.tsx
  packages/desktop-client/src/hooks/useUndo.ts
  packages/desktop-client/src/payees/payeesSlice.ts
  upcoming-release-notes/5812.md
Labels: :white_check_mark: approved

#5878 🐛 Fix for worker in dev mode
  packages/plugins-service/bin/build-service-worker
  upcoming-release-notes/5878.md
Labels: :white_check_mark: approved

#5797 feat(currency): Currency-influenced initial number formats
  packages/desktop-client/src/components/settings/Currency.tsx
  packages/desktop-client/src/hooks/useFormat.ts
  packages/loot-core/src/shared/arithmetic.test.ts
  packages/loot-core/src/shared/arithmetic.ts
  packages/loot-core/src/shared/currencies.ts
  packages/loot-core/src/shared/util.test.ts
  packages/loot-core/src/shared/util.ts
  upcoming-release-notes/5797.md
Labels: :white_check_mark: approved

#5871 Add swipe to delete to mobile rules
  packages/desktop-client/e2e/rules.mobile.test.ts-snapshots/Mobile-Rules-checks-the-page-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/rules.mobile.test.ts-snapshots/Mobile-Rules-checks-the-page-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/rules.mobile.test.ts-snapshots/Mobile-Rules-checks-the-page-visuals-3-chromium-linux.png
  packages/desktop-client/e2e/rules.mobile.test.ts-snapshots/Mobile-Rules-clicking-on-a-rule-opens-edit-form-1-chromium-linux.png
  packages/desktop-client/e2e/rules.mobile.test.ts-snapshots/Mobile-Rules-clicking-on-a-rule-opens-edit-form-2-chromium-linux.png
  packages/desktop-client/e2e/rules.mobile.test.ts-snapshots/Mobile-Rules-clicking-on-a-rule-opens-edit-form-3-chromium-linux.png
  packages/desktop-client/src/components/mobile/rules/MobileRuleEditPage.tsx
  packages/desktop-client/src/components/mobile/rules/MobileRulesPage.tsx
  packages/desktop-client/src/components/mobile/rules/RulesList.tsx
  packages/desktop-client/src/components/mobile/rules/RulesListItem.tsx
  packages/loot-core/src/server/rules/app.ts
  upcoming-release-notes/5871.md
Labels: :white_check_mark: approved, AI generated
