Repository actualbudget/actual, pull requests merged in 2025-07, with the labels that each got.

#5270 :bug: fix amount input
  packages/desktop-client/src/components/util/AmountInput.tsx
  upcoming-release-notes/5270.md
Labels: :white_check_mark: approved

#5263 Fixes #5228 - has tag(s) filter now takes values when pressing Enter
  packages/desktop-client/src/components/util/GenericInput.jsx
  upcoming-release-notes/5263.md
Labels: :white_check_mark: approved

#5259 Fix rule templating on date causing crash
  packages/loot-core/src/server/rules/index.ts
  upcoming-release-notes/5259.md
Labels: :white_check_mark: approved

#5207 use correct running balance when adding a new transaction
  packages/desktop-client/src/components/transactions/TransactionsTable.tsx
  upcoming-release-notes/5207.md
Labels: :white_check_mark: approved

#5208 Move remaining `.d.ts` files to `.ts`
  .gitignore
  packages/crdt/bin/generate-proto
  packages/crdt/package.json
  packages/crdt/src/proto/sync_pb.js
  packages/crdt/src/proto/sync_pb.ts
  packages/desktop-client/globals.d.ts
  packages/desktop-client/globals.ts
  packages/desktop-electron/modules.ts
  packages/loot-core/src/platform/server/asyncStorage/__mocks__/index.ts
  packages/loot-core/src/platform/server/asyncStorage/index-types.ts
  packages/loot-core/src/platform/server/asyncStorage/index.d.ts
  packages/loot-core/src/platform/server/asyncStorage/index.electron.ts
  packages/loot-core/src/platform/server/asyncStorage/index.ts
  upcoming-release-notes/5208.md
  yarn.lock
Labels: :white_check_mark: approved

#5167 feat(currency): add currency setting and format
  packages/desktop-client/src/components/budget/envelope/EnvelopeBudgetComponents.tsx
  packages/desktop-client/src/components/settings/Currency.tsx
  packages/desktop-client/src/components/settings/Experimental.tsx
  packages/desktop-client/src/components/settings/Format.tsx
  packages/desktop-client/src/components/settings/Themes.tsx
  packages/desktop-client/src/components/settings/UI.tsx
  packages/desktop-client/src/components/settings/index.tsx
  packages/desktop-client/src/components/spreadsheet/CellValue.tsx
  packages/desktop-client/src/components/util/PercentInput.tsx
  packages/desktop-client/src/hooks/useFeatureFlag.ts
  packages/desktop-client/src/hooks/useFormat.ts
  packages/loot-core/src/shared/arithmetic.ts
  packages/loot-core/src/shared/currencies.ts
  packages/loot-core/src/shared/util.ts
  packages/loot-core/src/types/prefs.ts
  upcoming-release-notes/5167.md
Labels: :sparkles: merged

#5169 Update contributor points calculation logic
  .github/scripts/count-points.mjs
  upcoming-release-notes/5169.md
Labels: :sparkles: merged

#5286 💬 Added Discord link to the help menu for discoverability
  packages/desktop-client/src/components/HelpMenu.tsx
  packages/desktop-electron/menu.ts
  upcoming-release-notes/5286.md
Labels: :white_check_mark: approved

#5290 add notes to scheduled transactions table
  packages/desktop-client/src/components/schedules/ScheduleDetails.tsx
  upcoming-release-notes/5290.md
Labels: :white_check_mark: approved

#5279 Run rules on transactions created by a transfer.
  packages/loot-core/src/server/transactions/transfer.ts
  upcoming-release-notes/5279.md
Labels: :white_check_mark: approved

#5295 [Goals] upgrade week template to be a periodic template
  packages/desktop-client/src/components/budget/goals/constants.ts
  packages/desktop-client/src/components/budget/goals/editor/WeekAutomation.tsx
  packages/desktop-client/src/components/budget/goals/editor/WeekAutomationReadOnly.tsx
  packages/desktop-client/src/components/budget/goals/reducer.ts
  packages/loot-core/src/server/budget/category-template-context.test.ts
  packages/loot-core/src/server/budget/category-template-context.ts
  packages/loot-core/src/server/budget/goal-template.pegjs
  packages/loot-core/src/types/models/templates.ts
  upcoming-release-notes/5295.md
Labels: :white_check_mark: approved

#5307 Reword the overspending banner for tracking budget.
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-applies-budget-template-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-applies-budget-template-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-applies-budget-template-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--0ba04-nt-amount-opens-the-budget-summary-menu-modal-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--0dfe7-page-header-shows-the-previous-month-s-budget-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--1ce6d-nt-amount-opens-the-budget-summary-menu-modal-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--42062-in-the-page-header-opens-the-month-menu-modal-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--49fb6-in-the-page-header-opens-the-month-menu-modal-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--5f098-roup-name-opens-the-category-group-menu-modal-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--929be-roup-name-opens-the-category-group-menu-modal-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--a3783-in-the-page-header-opens-the-budget-page-menu-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--a8b5e-in-the-page-header-opens-the-budget-page-menu-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--b1562-in-the-page-header-opens-the-month-menu-modal-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--cfb69-page-header-shows-the-previous-month-s-budget-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--dc927-roup-name-opens-the-category-group-menu-modal-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--f224f-nt-amount-opens-the-budget-summary-menu-modal-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--f7fa3-page-header-shows-the-previous-month-s-budget-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking--f8a19-in-the-page-header-opens-the-budget-page-menu-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking-the-balance-cell-opens-the-balance-menu-modal-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking-the-balance-cell-opens-the-balance-menu-modal-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking-the-balance-cell-opens-the-balance-menu-modal-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking-the-budgeted-cell-opens-the-budget-menu-modal-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking-the-budgeted-cell-opens-the-budget-menu-modal-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking-the-budgeted-cell-opens-the-budget-menu-modal-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking-the-category-name-opens-the-category-menu-modal-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking-the-category-name-opens-the-category-menu-modal-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-checks-that-clicking-the-category-name-opens-the-category-menu-modal-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-copies-last-month-s-budget-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-copies-last-month-s-budget-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-copies-last-month-s-budget-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-loads-the-budget-page-with-budgeted-amounts-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-loads-the-budget-page-with-budgeted-amounts-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-loads-the-budget-page-with-budgeted-amounts-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-set-budget-to-12-month-average-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-set-budget-to-12-month-average-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-set-budget-to-12-month-average-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-set-budget-to-3-month-average-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-set-budget-to-3-month-average-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-set-budget-to-3-month-average-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-set-budget-to-6-month-average-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-set-budget-to-6-month-average-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-set-budget-to-6-month-average-3-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-updates-the-budgeted-amount-1-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-updates-the-budgeted-amount-2-chromium-linux.png
  packages/desktop-client/e2e/budget.mobile.test.ts-snapshots/Mobile-Budget-Tracking-updates-the-budgeted-amount-3-chromium-linux.png
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  packages/desktop-client/src/hooks/useOverspentCategories.ts
  upcoming-release-notes/5307.md
Labels: :white_check_mark: approved

#5309 Added Bank of Valletta as a limited history bank
  packages/sync-server/src/app-gocardless/bank-factory.js
  upcoming-release-notes/5309.md
Labels: :white_check_mark: approved

#5282 enhancement: add interval selector for net worth report
  packages/desktop-client/e2e/reports.test.ts-snapshots/Reports-loads-cash-flow-graph-and-checks-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.ts-snapshots/Reports-loads-cash-flow-graph-and-checks-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/reports.test.ts-snapshots/Reports-loads-cash-flow-graph-and-checks-visuals-3-chromium-linux.png
  packages/desktop-client/e2e/reports.test.ts-snapshots/Reports-loads-net-worth-and-cash-flow-reports-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.ts-snapshots/Reports-loads-net-worth-and-cash-flow-reports-2-chromium-linux.png
  packages/desktop-client/e2e/reports.test.ts-snapshots/Reports-loads-net-worth-and-cash-flow-reports-3-chromium-linux.png
  packages/desktop-client/e2e/reports.test.ts-snapshots/Reports-loads-net-worth-graph-and-checks-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/reports.test.ts-snapshots/Reports-loads-net-worth-graph-and-checks-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/reports.test.ts-snapshots/Reports-loads-net-worth-graph-and-checks-visuals-3-chromium-linux.png
  packages/desktop-client/src/components/reports/Header.tsx
  packages/desktop-client/src/components/reports/graphs/NetWorthGraph.tsx
  packages/desktop-client/src/components/reports/reports/NetWorth.tsx
  packages/desktop-client/src/components/reports/reports/NetWorthCard.tsx
  packages/desktop-client/src/components/reports/spreadsheets/net-worth-spreadsheet.ts
  packages/loot-core/src/types/models/dashboard.ts
  upcoming-release-notes/5282.md
Labels: :white_check_mark: approved

#5335 fix pseudo-element quotes in ColorPicker
  packages/component-library/src/ColorPicker.tsx
  upcoming-release-notes/5335.md
Labels: :white_check_mark: approved

#5293 add action button to trigger applyBudgetTemplatesInGroup to mobile
  packages/desktop-client/src/components/mobile/budget/CategoryGroupActionMenu.tsx
  packages/desktop-client/src/components/mobile/budget/index.tsx
  packages/desktop-client/src/components/modals/CategoryGroupMenuModal.tsx
  packages/desktop-client/src/modals/modalsSlice.ts
  upcoming-release-notes/5293.md
Labels: :white_check_mark: approved

#5344 Fix Boursorama GoCardless transaction ordering
  packages/sync-server/src/app-gocardless/banks/boursobank_bousfrppxxx.js
  packages/sync-server/src/app-gocardless/banks/tests/boursobank_bousfrppxxx.spec.js
  upcoming-release-notes/5344.md
Labels: :white_check_mark: approved

#5348 feat(CommandBar): add aggregated acct views
  packages/desktop-client/src/components/CommandBar.tsx
  upcoming-release-notes/5348.md
Labels: :white_check_mark: approved

#5352 [Feature] Only Show Sidebar Tooltip on Desktop
  packages/desktop-client/src/components/sidebar/Account.tsx
  upcoming-release-notes/5352.md
Labels: :white_check_mark: approved

#5353 Add extra date format
  packages/desktop-client/src/components/settings/Format.tsx
  upcoming-release-notes/5353.md
Labels: :white_check_mark: approved

#5059 Convert `SelectLinkedAccountsModal` to TypeScript
  packages/desktop-client/src/components/autocomplete/Autocomplete.tsx
  packages/desktop-client/src/components/modals/SelectLinkedAccountsModal.tsx
  packages/desktop-client/src/modals/modalsSlice.ts
  packages/loot-core/src/types/models/gocardless.ts
  packages/loot-core/src/types/models/pluggyai.ts
  packages/loot-core/src/types/models/simplefin.ts
  upcoming-release-notes/5059.md
Labels: :white_check_mark: approved

#5360 fix crash when using bulk amount update
  packages/desktop-client/src/components/modals/EditFieldModal.tsx
  upcoming-release-notes/5360.md
Labels: :white_check_mark: approved

#5364 Fixes #5343: Color of the resize handle now adapts to color scheme (dark theme/midnight theme/light theme)
  packages/desktop-client/src/components/reports/overview.scss
  upcoming-release-notes/5364.md
Labels: :white_check_mark: approved

#5359 add options to post schedule today or the next scheduled date
  packages/desktop-client/e2e/schedules.test.ts-snapshots/Schedules-creates-a-new-schedule-posts-the-transaction-and-later-completes-it-6-chromium-linux.png
  packages/desktop-client/src/components/accounts/Account.tsx
  packages/desktop-client/src/components/mobile/accounts/AccountTransactions.tsx
  packages/desktop-client/src/components/modals/ScheduledTransactionMenuModal.tsx
  packages/desktop-client/src/components/schedules/SchedulesTable.tsx
  packages/desktop-client/src/components/schedules/index.tsx
  packages/desktop-client/src/components/transactions/SelectedTransactionsButton.tsx
  packages/desktop-client/src/components/transactions/TransactionMenu.tsx
  packages/desktop-client/src/components/transactions/TransactionsTable.tsx
  packages/desktop-client/src/modals/modalsSlice.ts
  packages/loot-core/src/server/schedules/app.ts
  upcoming-release-notes/5359.md
Labels: :white_check_mark: approved

#5356 fix datepicker month input validation to allow mm/yyyy on resubmission
  packages/desktop-client/src/components/filters/FiltersMenu.jsx
  upcoming-release-notes/5356.md
Labels: :white_check_mark: approved

#5340 :keyboard: Enhanced keyboard shortcuts modal
  packages/desktop-client/src/components/modals/KeyboardShortcutModal.tsx
  upcoming-release-notes/5340.md
Labels: :white_check_mark: approved

#5371 VRT's for Help menu
  packages/desktop-client/e2e/help-menu.test.ts
  packages/desktop-client/e2e/help-menu.test.ts-snapshots/Help-menu-Check-the-help-menu-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/help-menu.test.ts-snapshots/Help-menu-Check-the-help-menu-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/help-menu.test.ts-snapshots/Help-menu-Check-the-help-menu-visuals-3-chromium-linux.png
  packages/desktop-client/e2e/help-menu.test.ts-snapshots/Help-menu-Check-the-keyboard-shortcuts-modal-visuals-1-chromium-linux.png
  packages/desktop-client/e2e/help-menu.test.ts-snapshots/Help-menu-Check-the-keyboard-shortcuts-modal-visuals-2-chromium-linux.png
  packages/desktop-client/e2e/help-menu.test.ts-snapshots/Help-menu-Check-the-keyboard-shortcuts-modal-visuals-3-chromium-linux.png
  packages/desktop-client/e2e/help-menu.test.ts-snapshots/Help-menu-Check-the-keyboard-shortcuts-modal-visuals-4-chromium-linux.png
  packages/desktop-client/e2e/help-menu.test.ts-snapshots/Help-menu-Check-the-keyboard-shortcuts-modal-visuals-5-chromium-linux.png
  packages/desktop-client/e2e/help-menu.test.ts-snapshots/Help-menu-Check-the-keyboard-shortcuts-modal-visuals-6-chromium-linux.png
  packages/desktop-client/e2e/help-menu.test.ts-snapshots/Help-menu-Check-the-keyboard-shortcuts-modal-visuals-7-chromium-linux.png
  packages/desktop-client/e2e/help-menu.test.ts-snapshots/Help-menu-Check-the-keyboard-shortcuts-modal-visuals-8-chromium-linux.png
  packages/desktop-client/e2e/help-menu.test.ts-snapshots/Help-menu-Check-the-keyboard-shortcuts-modal-visuals-9-chromium-linux.png
  upcoming-release-notes/5371.md
Labels: :white_check_mark: approved

#5377 Only use fund from local group during cleanup.
  packages/loot-core/src/server/budget/cleanup-template.ts
  upcoming-release-notes/5377.md
Labels: :white_check_mark: approved

#5368 Add button to import existing tag from transactions notes
  packages/desktop-client/src/components/payees/PayeeTableRow.tsx
  packages/desktop-client/src/components/tags/ManageTags.tsx
  packages/desktop-client/src/components/tags/TagRow.tsx
  packages/desktop-client/src/queries/queriesSlice.ts
  packages/desktop-client/src/style/tags.ts
  packages/loot-core/src/server/db/index.ts
  packages/loot-core/src/server/tags/app.ts
  upcoming-release-notes/5368.md
Labels: :white_check_mark: approved

#5362 [Enhancement] Disable Sidebar Tooltip on Touchscreen Device
  packages/desktop-client/src/components/sidebar/Account.tsx
  upcoming-release-notes/5362.md
Labels: :white_check_mark: approved

#5373 fix: reconcile select number on click
  packages/desktop-client/src/components/accounts/Reconcile.tsx
  upcoming-release-notes/5373.md
Labels: :white_check_mark: approved

#5391 tags fixes
  packages/desktop-client/src/components/tags/TagCreationRow.tsx
  packages/desktop-client/src/components/tags/TagEditor.tsx
  packages/desktop-client/src/style/tags.ts
Labels: :mag: ready for review

#5393 Fix potential undefined points issue in contributor points calculation
  .github/scripts/count-points.mjs
  upcoming-release-notes/5393.md
Labels: :white_check_mark: approved, AI generated

#5386 Fix tag matching of filter and make hasTags op case-sensitive
  packages/loot-core/src/server/rules/index.ts
  packages/loot-core/src/server/transactions/transaction-rules.ts
  upcoming-release-notes/5386.md
Labels: :white_check_mark: approved

#5405 Revert "Mobile running balance" because its causing extreme slowness in large accounts.
  packages/desktop-client/src/components/mobile/accounts/AccountTransactions.tsx
  packages/desktop-client/src/components/mobile/budget/CategoryTransactions.tsx
  packages/desktop-client/src/components/mobile/transactions/TransactionList.tsx
  packages/desktop-client/src/components/mobile/transactions/TransactionListItem.tsx
  packages/desktop-client/src/components/mobile/transactions/TransactionListWithBalances.tsx
  packages/desktop-client/src/components/modals/AccountMenuModal.tsx
  packages/desktop-client/src/components/reports/reports/Calendar.tsx
  packages/desktop-client/src/hooks/useAccountPreviewTransactions.ts
  packages/desktop-client/src/hooks/useCategoryPreviewTransactions.ts
  packages/desktop-client/src/hooks/usePreviewTransactions.ts
  packages/desktop-client/src/modals/modalsSlice.ts
  upcoming-release-notes/5219.md
  upcoming-release-notes/5405.md
Labels: :white_check_mark: approved
