Repository actualbudget/actual, pull requests merged in 2025-02, with the labels that each got.

#4276 report sorting on dashboard
  packages/desktop-client/src/components/reports/ReportOptions.ts
  packages/desktop-client/src/components/reports/ReportSidebar.tsx
  packages/desktop-client/src/components/reports/disabledList.ts
  packages/desktop-client/src/components/reports/reports/CustomReport.tsx
  packages/desktop-client/src/components/reports/reports/GetCardData.tsx
  packages/loot-core/migrations/1738491452000__sorting_rename.sql
  packages/loot-core/src/types/models/reports.d.ts
  upcoming-release-notes/4276.md
Labels: :white_check_mark: Approved

#4256 fix first occurrence of some schedules moved after the weekend not showing in preview
  packages/loot-core/src/client/data-hooks/transactions.ts
  upcoming-release-notes/4256.md
Labels: :white_check_mark: Approved

#4266 Make password login page more mobile responsive
  packages/desktop-client/src/components/manager/subscribe/Login.tsx
  upcoming-release-notes/4266.md
Labels: :white_check_mark: Approved

#4241 fix(#2495): fix GoCardless transaction ID to fallback to it's own generated ID on sync
  packages/loot-core/src/server/accounts/sync.ts
  upcoming-release-notes/4241.md
Labels: :white_check_mark: Approved

#4224 fix deleting rules considering the applied filters
  packages/desktop-client/src/components/ManageRules.tsx
  upcoming-release-notes/4224.md
Labels: :white_check_mark: Approved

#4300 [Goals]: Handle tracking budget income categories
  packages/loot-core/src/server/budget/categoryTemplate.ts
  upcoming-release-notes/4300.md
Labels: :white_check_mark: Approved

#4303 Fix crashes on reports page with translations enabled
  packages/desktop-client/src/components/reports/ReportOptions.ts
  packages/desktop-client/src/components/reports/ReportSidebar.tsx
  packages/desktop-client/src/components/reports/disabledList.ts
  packages/desktop-client/src/components/reports/reports/CustomReport.tsx
  upcoming-release-notes/4303.md
Labels: :white_check_mark: Approved

#4306 Add an action to automatically generate release PRs
  .github/actions/bump-package-versions
  .github/workflows/generate-release-pr.yml
  upcoming-release-notes/4306.md
Labels: :white_check_mark: Approved

#4293 Handle duplicate categories/groups in nYNAB importer.
  packages/loot-core/src/server/importers/ynab5.ts
  upcoming-release-notes/4293.md
Labels: :white_check_mark: Approved

#4294 nYNAB import - properly handle hidden categories and groups
  packages/desktop-client/e2e/data/ynab5-demo-budget.json
  packages/loot-core/src/server/api.ts
  packages/loot-core/src/server/importers/ynab5-types.d.ts
  packages/loot-core/src/server/importers/ynab5.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/4294.md
Labels: :white_check_mark: Approved

#4312 fix Weblate URL if language has never been changed
  packages/desktop-client/src/components/settings/LanguageSettings.tsx
  upcoming-release-notes/4312.md
Labels: :white_check_mark: Approved

#4317 Fix electron translations
  bin/package-electron
  packages/desktop-client/src/i18n.ts
  upcoming-release-notes/4317.md
Labels: :white_check_mark: Approved

#4319 🔖 (25.2.1) fix desktop apps and reports page
  packages/api/package.json
  packages/desktop-client/package.json
  packages/desktop-electron/package.json
  upcoming-release-notes/4303.md
  upcoming-release-notes/4312.md
  upcoming-release-notes/4317.md
Labels: :mag: Ready for review

#4322 Fix hard crash when closing budget thats synced to cloud file
  packages/desktop-client/src/components/App.tsx
  upcoming-release-notes/4322.md
Labels: :white_check_mark: Approved

#4169 :sparkles: component library - minimalistic infrastructure
  packages/component-library/package.json
  packages/component-library/src/Button.tsx
  packages/component-library/src/View.tsx
  packages/component-library/src/icons/AnimatedLoading.tsx
  packages/component-library/src/icons/Loading.tsx
  packages/component-library/src/styles.ts
  packages/component-library/src/theme.ts
  packages/component-library/src/tokens.ts
  packages/desktop-client/package.json
  packages/desktop-client/src/components/FatalError.tsx
  packages/desktop-client/src/components/common/Button.tsx
  packages/desktop-client/src/components/common/Button2.ts
  packages/desktop-client/src/components/common/View.ts
  packages/desktop-client/src/icons/AnimatedLoading.tsx
  packages/desktop-client/src/style/styles.ts
  packages/desktop-client/src/style/theme.tsx
  packages/desktop-client/src/tokens.ts
  upcoming-release-notes/4169.md
  yarn.lock
Labels: :white_check_mark: Approved

#4352 ⚒ Workflow updates to only trigger when needed
  .github/workflows/docker-edge.yml
  .github/workflows/e2e-test.yml
  .github/workflows/size-compare.yml
  upcoming-release-notes/4352.md
Labels: :white_check_mark: Approved

#4347 :recycle: (eslint) disallow importing actual-app/web in loot-core
  eslint.config.mjs
  packages/loot-core/src/client/actions/prefs.ts
  packages/loot-core/src/client/data-hooks/schedules.tsx
  packages/loot-core/src/client/data-hooks/transactions.ts
  upcoming-release-notes/4347.md
Labels: :white_check_mark: Approved

#4350 :recycle: (api) removing deprecated 'methods' export
  packages/api/index.ts
  upcoming-release-notes/4350.md
Labels: :white_check_mark: Approved

#4346 :recycle: moving more components to the new component-lib pkg
  eslint.config.mjs
  packages/component-library/package.json
  packages/component-library/src/AlignedText.tsx
  packages/component-library/src/Block.tsx
  packages/component-library/src/Card.tsx
  packages/component-library/src/FormError.tsx
  packages/component-library/src/InitialFocus.ts
  packages/component-library/src/InlineField.tsx
  packages/component-library/src/Label.tsx
  packages/component-library/src/Menu.tsx
  packages/component-library/src/Paragraph.tsx
  packages/component-library/src/Popover.tsx
  packages/component-library/src/SpaceBetween.tsx
  packages/component-library/src/Stack.tsx
  packages/component-library/src/Text.tsx
  packages/component-library/src/TextOneLine.tsx
  packages/component-library/src/Toggle.tsx
  packages/component-library/src/Tooltip.tsx
  packages/desktop-client/src/components/common/AlignedText.ts
  packages/desktop-client/src/components/common/Block.ts
  packages/desktop-client/src/components/common/Button.tsx
  packages/desktop-client/src/components/common/Card.ts
  packages/desktop-client/src/components/common/FormError.ts
  packages/desktop-client/src/components/common/InitialFocus.ts
  packages/desktop-client/src/components/common/InlineField.ts
  packages/desktop-client/src/components/common/Label.ts
  packages/desktop-client/src/components/common/Menu.ts
  packages/desktop-client/src/components/common/Modal.tsx
  packages/desktop-client/src/components/common/Paragraph.ts
  packages/desktop-client/src/components/common/Popover.ts
  packages/desktop-client/src/components/common/SpaceBetween.ts
  packages/desktop-client/src/components/common/Stack.ts
  packages/desktop-client/src/components/common/Text.ts
  packages/desktop-client/src/components/common/TextOneLine.ts
  packages/desktop-client/src/components/common/Toggle.ts
  packages/desktop-client/src/components/common/Tooltip.ts
  packages/desktop-client/src/components/mobile/transactions/TransactionList.tsx
  packages/desktop-client/src/components/table.tsx
  upcoming-release-notes/4346.md
Labels: :white_check_mark: Approved

#4356 fix: helpers with empty or undefined values
  packages/loot-core/src/server/accounts/rules.test.ts
  packages/loot-core/src/server/accounts/rules.ts
  upcoming-release-notes/4356.md
Labels: :white_check_mark: Approved

#4353 Correct link to translation setup for local install
  packages/desktop-client/src/components/settings/LanguageSettings.tsx
  upcoming-release-notes/4353.md
Labels: :white_check_mark: Approved

#4358 :recycle: (imports) updating some common component import paths to th…
  packages/desktop-client/src/components/AppBackground.tsx
  packages/desktop-client/src/components/FatalError.tsx
  packages/desktop-client/src/components/budget/envelope/budgetsummary/ToBudgetAmount.tsx
  packages/desktop-client/src/components/budget/envelope/budgetsummary/TotalsList.tsx
  packages/desktop-client/src/components/budget/tracking/budgetsummary/Saved.tsx
  packages/desktop-client/src/components/common/AlignedText.ts
  packages/desktop-client/src/components/common/Block.ts
  packages/desktop-client/src/components/modals/ConfirmCategoryDeleteModal.tsx
  packages/desktop-client/src/components/modals/ConfirmTransactionEditModal.tsx
  packages/desktop-client/src/components/modals/LoadBackupModal.tsx
  packages/desktop-client/src/components/modals/manager/ImportActualModal.tsx
  packages/desktop-client/src/components/modals/manager/ImportModal.tsx
  packages/desktop-client/src/components/modals/manager/ImportYNAB4Modal.tsx
  packages/desktop-client/src/components/modals/manager/ImportYNAB5Modal.tsx
  packages/desktop-client/src/components/reports/Change.tsx
  packages/desktop-client/src/components/reports/DateRange.tsx
  packages/desktop-client/src/components/reports/LoadingIndicator.tsx
  packages/desktop-client/src/components/reports/ReportCardName.tsx
  packages/desktop-client/src/components/reports/graphs/AreaGraph.tsx
  packages/desktop-client/src/components/reports/graphs/BarGraph.tsx
  packages/desktop-client/src/components/reports/graphs/BarLineGraph.tsx
  packages/desktop-client/src/components/reports/graphs/CashFlowGraph.tsx
  packages/desktop-client/src/components/reports/graphs/LineGraph.tsx
  packages/desktop-client/src/components/reports/graphs/NetWorthGraph.tsx
  packages/desktop-client/src/components/reports/graphs/SpendingGraph.tsx
  packages/desktop-client/src/components/reports/graphs/StackedBarGraph.tsx
  packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTable.tsx
  packages/desktop-client/src/components/reports/reports/CalendarCard.tsx
  packages/desktop-client/src/components/reports/reports/CashFlow.tsx
  packages/desktop-client/src/components/reports/reports/CustomReport.tsx
  packages/desktop-client/src/components/reports/reports/NetWorthCard.tsx
  packages/desktop-client/src/components/reports/reports/Spending.tsx
  packages/desktop-client/src/components/reports/reports/SpendingCard.tsx
  packages/desktop-client/src/components/reports/spreadsheets/cash-flow-spreadsheet.tsx
  packages/desktop-client/src/components/settings/Export.tsx
  packages/desktop-client/src/components/sidebar/Account.tsx
  packages/desktop-client/src/components/sidebar/Item.tsx
  packages/desktop-client/src/components/sidebar/SecondaryItem.tsx
  packages/desktop-client/src/components/util/LoadComponent.tsx
  upcoming-release-notes/4358.md
Labels: :white_check_mark: Approved

#4360 :bug: fix category is nothing rule crashing spending report widget
  packages/desktop-client/src/components/reports/spreadsheets/spending-spreadsheet.ts
  packages/loot-core/src/server/accounts/transaction-rules.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/4360.md
Labels: :white_check_mark: Approved

#4363 Re-enable linting on the server
  eslint.config.mjs
  packages/sync-server/app.js
  packages/sync-server/jest.global-setup.js
  packages/sync-server/jest.global-teardown.js
  packages/sync-server/migrations/1694360000000-create-folders.js
  packages/sync-server/migrations/1694360479680-create-account-db.js
  packages/sync-server/migrations/1694362247011-create-secret-table.js
  packages/sync-server/migrations/1702667624000-rename-nordigen-secrets.js
  packages/sync-server/migrations/1718889148000-openid.js
  packages/sync-server/migrations/1719409568000-multiuser.js
  packages/sync-server/src/account-db.js
  packages/sync-server/src/accounts/openid.js
  packages/sync-server/src/accounts/password.js
  packages/sync-server/src/app-account.js
  packages/sync-server/src/app-admin.js
  packages/sync-server/src/app-admin.test.js
  packages/sync-server/src/app-gocardless/bank-factory.js
  packages/sync-server/src/app-gocardless/banks/easybank_bawaatww.js
  packages/sync-server/src/app-gocardless/banks/hype_hyeeit22.js
  packages/sync-server/src/app-gocardless/services/gocardless-service.js
  packages/sync-server/src/app-gocardless/tests/bank-factory.spec.js
  packages/sync-server/src/app-secrets.js
  packages/sync-server/src/app-simplefin/app-simplefin.js
  packages/sync-server/src/app-sync.js
  packages/sync-server/src/app-sync.test.js
  packages/sync-server/src/app-sync/services/files-service.js
  packages/sync-server/src/app-sync/tests/services/files-service.test.js
  packages/sync-server/src/app.js
  packages/sync-server/src/db.js
  packages/sync-server/src/load-config.js
  packages/sync-server/src/migrations.js
  packages/sync-server/src/run-migrations.js
  packages/sync-server/src/scripts/enable-openid.js
  packages/sync-server/src/scripts/health-check.js
  packages/sync-server/src/services/secrets-service.js
  packages/sync-server/src/services/user-service.js
  packages/sync-server/src/sync-simple.js
  packages/sync-server/src/util/middlewares.js
  packages/sync-server/src/util/paths.js
  packages/sync-server/src/util/validate-user.js
  upcoming-release-notes/4363.md
Labels: :white_check_mark: Approved

#4214 Make `loot-core` compatible with `exactOptionalPropertyTypes`
  packages/loot-core/src/client/accounts/accountsSlice.ts
  packages/loot-core/src/client/actions/budgets.ts
  packages/loot-core/src/client/data-hooks/reports.ts
  packages/loot-core/src/client/data-hooks/transactions.ts
  packages/loot-core/src/client/query-hooks.ts
  packages/loot-core/src/client/state-types/modals.d.ts
  packages/loot-core/src/client/state-types/notifications.d.ts
  packages/loot-core/src/mocks/index.ts
  packages/loot-core/src/server/api-models.ts
  packages/loot-core/src/server/errors.ts
  packages/loot-core/src/shared/test-helpers.ts
  packages/loot-core/src/shared/transactions.ts
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/4214.md
Labels: :white_check_mark: Approved

#4375 🐛 Fix Initializing the connection to the local database hang
  packages/loot-core/src/platform/client/fetch/index.browser.ts
  packages/loot-core/src/platform/server/connection/index.web.ts
  upcoming-release-notes/4375.md
Labels: :white_check_mark: Approved

#4257 Add percentage adjustments to schedule templates (#4098)
  packages/loot-core/src/server/budget/goal-template.pegjs
  packages/loot-core/src/server/budget/goalsSchedule.ts
  packages/loot-core/src/server/budget/template-notes.test.ts
  packages/loot-core/src/server/budget/template-notes.ts
  packages/loot-core/src/server/budget/types/templates.d.ts
  upcoming-release-notes/4257.md
Labels: :white_check_mark: Approved

#4218 [TypeScript] Convert test page models to TS
  packages/desktop-client/e2e/budget.mobile.test.ts
  packages/desktop-client/e2e/page-models/account-page.ts
  packages/desktop-client/e2e/page-models/budget-page.js
  packages/desktop-client/e2e/page-models/budget-page.ts
  packages/desktop-client/e2e/page-models/close-account-modal.ts
  packages/desktop-client/e2e/page-models/configuration-page.ts
  packages/desktop-client/e2e/page-models/custom-report-page.ts
  packages/desktop-client/e2e/page-models/mobile-account-page.ts
  packages/desktop-client/e2e/page-models/mobile-accounts-page.ts
  packages/desktop-client/e2e/page-models/mobile-balance-menu-modal.ts
  packages/desktop-client/e2e/page-models/mobile-budget-menu-modal.ts
  packages/desktop-client/e2e/page-models/mobile-budget-page.ts
  packages/desktop-client/e2e/page-models/mobile-category-menu-modal.ts
  packages/desktop-client/e2e/page-models/mobile-edit-notes-modal.ts
  packages/desktop-client/e2e/page-models/mobile-envelope-budget-summary-modal.ts
  packages/desktop-client/e2e/page-models/mobile-navigation.ts
  packages/desktop-client/e2e/page-models/mobile-reports-page.js
  packages/desktop-client/e2e/page-models/mobile-reports-page.ts
  packages/desktop-client/e2e/page-models/mobile-tracking-budget-summary-modal.ts
  packages/desktop-client/e2e/page-models/mobile-transaction-entry-page.ts
  packages/desktop-client/e2e/page-models/navigation.ts
  packages/desktop-client/e2e/page-models/reports-page.ts
  packages/desktop-client/e2e/page-models/rules-page.ts
  packages/desktop-client/e2e/page-models/schedules-page.ts
  packages/desktop-client/e2e/page-models/settings-page.ts
  packages/desktop-client/e2e/transactions.test.ts
  upcoming-release-notes/4218.md
Labels: :white_check_mark: Approved

#4370 Updating sync server package name to @actual-app/sync-server
  package.json
  packages/sync-server/docker/edge-alpine.Dockerfile
  packages/sync-server/docker/edge-ubuntu.Dockerfile
  packages/sync-server/docker/stable-alpine.Dockerfile
  packages/sync-server/docker/stable-ubuntu.Dockerfile
  packages/sync-server/package.json
  sync-server.Dockerfile
  upcoming-release-notes/4370.md
  yarn.lock
Labels: :white_check_mark: Approved

#4372 Development mode for sync server (React Fast Refresh on port 5006)
  package.json
  packages/desktop-client/vite.config.mts
  packages/sync-server/package.json
  packages/sync-server/src/app.js
  upcoming-release-notes/4372.md
  yarn.lock
Labels: :white_check_mark: Approved

#4400 🐛 Fix new proxy middleware dependency missing on prod build
  packages/sync-server/src/app.js
  upcoming-release-notes/4400.md
Labels: :white_check_mark: Approved

#4382 Fixes #4069 : Ignore CSV inOutMode during OFX imports
  packages/desktop-client/src/components/modals/ImportTransactionsModal/ImportTransactionsModal.jsx
  upcoming-release-notes/4382.md
Labels: :white_check_mark: Approved

#4402 Fix goals tooltip translation
  packages/desktop-client/src/components/budget/BalanceWithCarryover.tsx
Labels: :white_check_mark: Approved

#4247 [TypeScript] Make `db.runQuery` generic to make it easy to type DB query results
  packages/loot-core/src/server/budget/base.ts
  packages/loot-core/src/server/budget/statements.ts
  packages/loot-core/src/server/budget/template-notes.test.ts
  packages/loot-core/src/server/db/index.ts
  packages/loot-core/src/server/db/mappings.ts
  packages/loot-core/src/server/db/types.d.ts
  packages/loot-core/src/server/db/types/index.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/server/sync/index.ts
  packages/loot-core/src/server/sync/migrate.test.ts
  packages/loot-core/src/server/tools/app.ts
  upcoming-release-notes/4247.md
Labels: :white_check_mark: Approved

#4403 update mapping data for existing synced transactions and always show direction dropdown
  packages/desktop-client/src/components/banksync/EditSyncAccount.tsx
  packages/desktop-client/src/components/banksync/FieldMapping.tsx
  packages/loot-core/src/server/accounts/sync.ts
  upcoming-release-notes/4403.md
Labels: :white_check_mark: Approved

#4145 Fix top-level types of `send` function
  packages/desktop-client/src/components/modals/EditAccess.tsx
  packages/loot-core/src/platform/client/fetch/index.browser.ts
  packages/loot-core/src/platform/client/fetch/index.d.ts
  packages/loot-core/src/platform/client/fetch/index.web.ts
  upcoming-release-notes/4145.md
Labels: :white_check_mark: Approved

#4308 Foundations for the budget automations UI
  packages/component-library/src/styles.ts
  packages/desktop-client/src/components/budget/SidebarCategory.tsx
  packages/desktop-client/src/components/budget/goals/CategoryAutomationButton.tsx
  packages/desktop-client/src/components/modals/EditRuleModal.jsx
  packages/desktop-client/src/components/settings/Experimental.tsx
  packages/desktop-client/src/hooks/useFeatureFlag.ts
  packages/loot-core/src/client/data-hooks/schedules.tsx
  packages/loot-core/src/client/state-types/modals.d.ts
  packages/loot-core/src/server/budget/types/templates.d.ts
  packages/loot-core/src/types/prefs.d.ts
  upcoming-release-notes/4308.md
Labels: :white_check_mark: Approved

#4260 Fix react-hooks/exhaustive-deps error on usePayees.ts
  eslint.config.mjs
  packages/desktop-client/src/hooks/usePayees.ts
  upcoming-release-notes/4260.md
Labels: :white_check_mark: Approved

#4262 Fix react-hooks/exhaustive-deps error on useAccounts.ts
  eslint.config.mjs
  packages/desktop-client/src/hooks/useAccounts.ts
  upcoming-release-notes/4262.md
Labels: :white_check_mark: Approved

#4273 Fix react-hooks/exhaustive-deps error on Titlebar.tsx
  eslint.config.mjs
  packages/desktop-client/src/components/Titlebar.tsx
  upcoming-release-notes/4273.md
Labels: :white_check_mark: Approved

#4388 [WIP] BANKS_WITH_LIMITED_HISTORY constant update
  packages/sync-server/src/app-gocardless/bank-factory.js
  upcoming-release-notes/4388.md
Labels: :construction: WIP

#4259 Fix react-hooks/exhaustive-deps error on useProperFocus.tsx
  eslint.config.mjs
  packages/desktop-client/src/hooks/useProperFocus.tsx
  upcoming-release-notes/4259.md
Labels: :white_check_mark: Approved

#4268 Fix react-hooks/exhaustive-deps error on TransactionsTable.jsx
  eslint.config.mjs
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  packages/desktop-client/src/components/transactions/TransactionsTable.test.tsx
  upcoming-release-notes/4268.md
Labels: :white_check_mark: Approved

#4274 Fix react-hooks/exhaustive-deps error on table.tsx
  eslint.config.mjs
  packages/desktop-client/src/components/table.tsx
  upcoming-release-notes/4274.md
Labels: :white_check_mark: Approved

#4261 Fix react-hooks/exhaustive-deps error on useCategories.ts
  eslint.config.mjs
  packages/desktop-client/src/hooks/useCategories.ts
  upcoming-release-notes/4261.md
Labels: :white_check_mark: Approved

#4369 👷 Typescript: Improving typing of asyncStorage (global-store.json)
  packages/loot-core/src/platform/server/asyncStorage/index.d.ts
  packages/loot-core/src/platform/server/asyncStorage/index.electron.ts
  packages/loot-core/src/platform/server/asyncStorage/index.testing.ts
  packages/loot-core/src/platform/server/asyncStorage/index.web.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/types/prefs.d.ts
  upcoming-release-notes/4369.md
Labels: :white_check_mark: Approved

#4408 📚 Translation batch #1
  packages/desktop-client/src/components/accounts/Account.tsx
  packages/desktop-client/src/components/budget/SidebarCategory.tsx
  packages/desktop-client/src/components/budget/envelope/budgetsummary/TotalsList.tsx
  packages/desktop-client/src/components/mobile/MobileNavTabs.tsx
  packages/desktop-client/src/components/mobile/accounts/AccountTransactions.tsx
  packages/desktop-client/src/components/mobile/accounts/Accounts.tsx
  packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
  packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
  packages/desktop-client/src/components/mobile/transactions/TransactionList.tsx
  packages/desktop-client/src/components/mobile/transactions/TransactionListItem.tsx
  packages/desktop-client/src/components/modals/CategoryMenuModal.tsx
  packages/desktop-client/src/components/modals/CreateLocalAccountModal.tsx
  packages/desktop-client/src/components/modals/manager/ImportModal.tsx
  packages/desktop-client/src/components/reports/ReportSidebar.tsx
  packages/desktop-client/src/components/reports/reports/CustomReport.tsx
  packages/desktop-client/src/components/reports/reports/Spending.tsx
  packages/desktop-client/src/components/settings/Export.tsx
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  upcoming-release-notes/4408.md
Labels: :white_check_mark: Approved

#4383 Fix currencyToAmount incorrectly converting input
  packages/desktop-client/e2e/page-models/account-page.ts
  packages/loot-core/src/shared/util.ts
  upcoming-release-notes/4383.md
Labels: :white_check_mark: Approved

#4213 useDisplayPayee hook to unify payee names in mobile and desktop.
  packages/desktop-client/e2e/accounts.mobile.test.ts-snapshots/Mobile-Accounts-opens-individual-account-page-and-checks-that-filtering-is-working-1-chromium-linux.png
  packages/desktop-client/e2e/accounts.mobile.test.ts-snapshots/Mobile-Accounts-opens-individual-account-page-and-checks-that-filtering-is-working-2-chromium-linux.png
  packages/desktop-client/e2e/accounts.mobile.test.ts-snapshots/Mobile-Accounts-opens-individual-account-page-and-checks-that-filtering-is-working-3-chromium-linux.png
  packages/desktop-client/e2e/reports.test.ts-snapshots/Reports-loads-cash-flow-graph-and-checks-visuals-1-chromium-linux.png
  packages/desktop-client/src/components/mobile/budget/CategoryTransactions.tsx
  packages/desktop-client/src/components/mobile/transactions/TransactionListItem.tsx
  packages/desktop-client/src/components/transactions/TransactionsTable.jsx
  packages/desktop-client/src/components/transactions/TransactionsTable.test.tsx
  packages/desktop-client/src/hooks/useDisplayPayee.ts
  packages/loot-core/src/client/data-hooks/transactions.ts
  upcoming-release-notes/4213.md
Labels: :white_check_mark: Approved

#4221 Extract transaction related server handlers from `main.ts` to `server/transactions/app.ts`
  packages/loot-core/src/mocks/setup.ts
  packages/loot-core/src/server/accounts/sync.test.ts
  packages/loot-core/src/server/accounts/sync.ts
  packages/loot-core/src/server/api.ts
  packages/loot-core/src/server/filters/app.ts
  packages/loot-core/src/server/main.test.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/server/rules/app.ts
  packages/loot-core/src/server/rules/index.test.ts
  packages/loot-core/src/server/rules/index.ts
  packages/loot-core/src/server/rules/types/handlers.ts
  packages/loot-core/src/server/schedules/app.test.ts
  packages/loot-core/src/server/schedules/app.ts
  packages/loot-core/src/server/schedules/find-schedules.ts
  packages/loot-core/src/server/tools/app.ts
  packages/loot-core/src/server/transactions/__snapshots__/transaction-rules.test.ts.snap
  packages/loot-core/src/server/transactions/__snapshots__/transfer.test.ts.snap
  packages/loot-core/src/server/transactions/app.ts
  packages/loot-core/src/server/transactions/export/export-to-csv.ts
  packages/loot-core/src/server/transactions/import/__snapshots__/parse-file.test.ts.snap
  packages/loot-core/src/server/transactions/import/ofx2json.ts
  packages/loot-core/src/server/transactions/import/parse-file.test.ts
  packages/loot-core/src/server/transactions/import/parse-file.ts
  packages/loot-core/src/server/transactions/import/qif2json.ts
  packages/loot-core/src/server/transactions/import/xmlcamt2json.ts
  packages/loot-core/src/server/transactions/index.ts
  packages/loot-core/src/server/transactions/transaction-rules.test.ts
  packages/loot-core/src/server/transactions/transaction-rules.ts
  packages/loot-core/src/server/transactions/transfer.test.ts
  packages/loot-core/src/server/transactions/transfer.ts
  packages/loot-core/src/shared/schedules.ts
  packages/loot-core/src/types/api-handlers.d.ts
  packages/loot-core/src/types/handlers.d.ts
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/4221.md
Labels: :white_check_mark: Approved

#4417 🐛 Fix `On budget` / `Off budget` underline with translated languages
  packages/desktop-client/src/components/sidebar/Account.tsx
  packages/desktop-client/src/components/sidebar/Accounts.tsx
  upcoming-release-notes/4417.md
Labels: :white_check_mark: Approved

#4409 [TypeScript] Add types to SpreadsheetProvider
  packages/desktop-client/src/components/budget/envelope/HoldMenu.tsx
  packages/desktop-client/src/components/spreadsheet/useSheetValue.ts
  packages/loot-core/package.json
  packages/loot-core/src/client/SpreadsheetProvider.tsx
  packages/loot-core/src/platform/server/sqlite/unicodeLike.ts
  packages/loot-core/src/server/db/index.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/types/server-handlers.d.ts
  packages/loot-core/webpack/webpack.browser.config.js
  upcoming-release-notes/4409.md
  yarn.lock
Labels: :white_check_mark: Approved

#4411 bump express dependencies
  packages/sync-server/package.json
  upcoming-release-notes/4411.md
  yarn.lock
Labels: :white_check_mark: Approved, dependencies

#4413 prevent bank sync from crashing when payee not found
  packages/loot-core/src/server/transactions/transfer.ts
  upcoming-release-notes/4413.md
Labels: :white_check_mark: Approved

#4227 Extract accounts related server handlers from `main.ts` to `server/accounts/app.ts`
  packages/desktop-client/src/components/accounts/AccountSyncCheck.tsx
  packages/desktop-client/src/components/modals/CreateAccountModal.tsx
  packages/desktop-client/src/gocardless.ts
  packages/loot-core/src/client/accounts/accountsSlice.ts
  packages/loot-core/src/server/accounts/app.ts
  packages/loot-core/src/server/accounts/payees.ts
  packages/loot-core/src/server/accounts/sync.ts
  packages/loot-core/src/server/errors.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/server/post.ts
  packages/loot-core/src/types/handlers.d.ts
  packages/loot-core/src/types/models/bank.d.ts
  packages/loot-core/src/types/models/gocardless.d.ts
  packages/loot-core/src/types/models/simplefin.d.ts
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/4227.md
Labels: :white_check_mark: Approved

#4272 Fix react-hooks/exhaustive-deps error on TransactionList.jsx
  eslint.config.mjs
  packages/desktop-client/src/components/transactions/TransactionList.jsx
  upcoming-release-notes/4272.md
Labels: :white_check_mark: Approved

#4423 ✨Enforce OPENID login
  packages/sync-server/src/account-db.js
  packages/sync-server/src/config-types.ts
  packages/sync-server/src/load-config.js
  upcoming-release-notes/4423.md
Labels: :white_check_mark: Approved

#4420 Extract preferences related server handlers from main.ts to server/preferences/app.ts
  packages/loot-core/src/server/main.ts
  packages/loot-core/src/server/preferences/app.ts
  packages/loot-core/src/server/preferences/types/handlers.d.ts
  packages/loot-core/src/types/handlers.d.ts
  packages/loot-core/src/types/server-handlers.d.ts
  upcoming-release-notes/4420.md
Labels: :white_check_mark: Approved

#4407 :electron: Improving electron logs
  packages/desktop-electron/index.ts
  packages/loot-core/src/platform/server/connection/index.web.ts
  upcoming-release-notes/4407.md
Labels: :white_check_mark: Approved

#4427 Mobile: adjust modals height to visual viewport
  packages/desktop-client/src/components/common/Modal.tsx
  packages/desktop-client/src/components/modals/AccountAutocompleteModal.tsx
  packages/desktop-client/src/components/modals/CategoryAutocompleteModal.tsx
  packages/desktop-client/src/components/modals/EditFieldModal.tsx
  packages/desktop-client/src/components/modals/PayeeAutocompleteModal.tsx
  upcoming-release-notes/4427.md
Labels: :white_check_mark: Approved

#4415 📚 Start the application with the browser default language
  packages/desktop-client/src/components/App.tsx
  upcoming-release-notes/4415.md
Labels: :white_check_mark: Approved

#4439 🐛 Fix the default language init for electron
  packages/desktop-client/src/components/App.tsx
  upcoming-release-notes/4439.md
Labels: :mag: Ready for review

#4452 sort schedule previews by date, then amount
  packages/loot-core/src/client/data-hooks/transactions.ts
  upcoming-release-notes/4452.md
Labels: :white_check_mark: Approved

#4453 change i18n errors to info
  packages/desktop-client/src/i18n.test.ts
  packages/desktop-client/src/i18n.ts
  upcoming-release-notes/4453.md
Labels: :white_check_mark: Approved

#4462 Resolves #4429 crash where clicking "manage payees" with an empty payee then clicking dropdown
  packages/desktop-client/src/components/transactions/TransactionList.jsx
  upcoming-release-notes/4462.md
Labels: :white_check_mark: Approved

#4461 resets transaction search even if search text is not empty
  packages/loot-core/src/client/data-hooks/transactions.ts
  upcoming-release-notes/4461.md
Labels: :white_check_mark: Approved

#4458 fix row spacing on bank sync page
  packages/desktop-client/src/components/banksync/AccountsList.tsx
  packages/desktop-client/src/components/banksync/index.tsx
  upcoming-release-notes/4458.md
Labels: :white_check_mark: Approved

#4463 Fix missing space in bank sync strings
  packages/desktop-client/src/components/modals/CreateAccountModal.tsx
  upcoming-release-notes/4463.md
Labels: :white_check_mark: Approved

#4468 fix #4445
  packages/loot-core/src/server/budget/cleanup-template.ts
  upcoming-release-notes/4468.md
Labels: :white_check_mark: Approved

#4472 add last bank sync tracking back in
  packages/loot-core/src/server/accounts/app.ts
  upcoming-release-notes/4472.md
Labels: :white_check_mark: Approved

#4477 Update bump-package-versions script to handle no input version
  .github/actions/bump-package-versions
Labels: :white_check_mark: Approved
